OpenFOAM: linearDamper Class Reference
linearDamper Class Reference
sixDoFRigidBodyMotionRestraints model. Linear spring.
Public Member Functions
TypeName ("linearDamper")
Runtime type information.
linearDamper (const word &name, const dictionary &sDoFRBMRDict)
Construct from components.
virtual autoPtr< sixDoFRigidBodyMotionRestraint > clone () const
Construct and return a clone.
virtual ~linearDamper ()
Destructor.
virtual void restrain (const sixDoFRigidBodyMotion &motion, vector &restraintPosition, vector &restraintForce, vector &restraintMoment) const
Calculate the restraint position, force and moment.
virtual bool read (const dictionary &sDoFRBMRCoeff)
Update properties from given dictionary.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from sixDoFRigidBodyMotionRestraint
TypeName ("sixDoFRigidBodyMotionRestraint")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, sixDoFRigidBodyMotionRestraint, dictionary,(const word &name, const dictionary &sDoFRBMRDict),(name, sDoFRBMRDict))
sixDoFRigidBodyMotionRestraint (const word &name, const dictionary &sDoFRBMRDict)
Construct from the sDoFRBMRDict dictionary and Time.
virtual ~sixDoFRigidBodyMotionRestraint ()
Destructor.
const word & name () const
Return the name.
const dictionary & coeffDict () const
Additional Inherited Members
Static Public Member Functions inherited from sixDoFRigidBodyMotionRestraint
static autoPtr< sixDoFRigidBodyMotionRestraint > New (const word &name, const dictionary &sDoFRBMRDict)
Select constructed from the sDoFRBMRDict dictionary and Time.
Protected Attributes inherited from sixDoFRigidBodyMotionRestraint
word name_
Name of the restraint.
dictionary sDoFRBMRCoeffs_
Restraint model specific coefficient dictionary.
Detailed Description
sixDoFRigidBodyMotionRestraints model. Linear spring.
Source files
linearDamper.H
linearDamper.C
Definition at line 52 of file linearDamper.H.
Constructor & Destructor Documentation
linearDamper()
linearDamper (const word & name, const dictionary & sDoFRBMRDict)
Construct from components.
Definition at line 51 of file linearDamper.C.
References Foam::read().
Referenced by linearDamper::clone().
~linearDamper()
~linearDamper () virtual
Destructor.
Definition at line 65 of file linearDamper.C.
References linearDamper::restrain().
Referenced by linearDamper::clone().
Member Function Documentation
TypeName()
TypeName ("linearDamper")
Runtime type information.
clone()
virtual autoPtr<sixDoFRigidBodyMotionRestraint> clone () const inline virtual
Construct and return a clone.
Implements sixDoFRigidBodyMotionRestraint.
Definition at line 78 of file linearDamper.H.
References linearDamper::linearDamper(), linearDamper::read(), linearDamper::restrain(), linearDamper::write(), and linearDamper::~linearDamper().
restrain()
void restrain (const sixDoFRigidBodyMotion & motion, vector & restraintPosition, vector & restraintForce, vector & restraintMoment) const virtual
Calculate the restraint position, force and moment.
Global reference frame vectors.
Implements sixDoFRigidBodyMotionRestraint.
Definition at line 72 of file linearDamper.C.
References Foam::endl(), Foam::Info, linearDamper::read(), sixDoFRigidBodyMotion::report(), and Foam::Zero.
Referenced by linearDamper::clone(), and linearDamper::~linearDamper().
read()
bool read (const dictionary & sDoFRBMRCoeff) virtual
Update properties from given dictionary.
Reimplemented from sixDoFRigidBodyMotionRestraint.
Definition at line 91 of file linearDamper.C.
References sixDoFRigidBodyMotionRestraint::read(), and linearDamper::write().
Referenced by linearDamper::clone(), and linearDamper::restrain().
write()
void write (Ostream & os) const virtual
Write.
Implements sixDoFRigidBodyMotionRestraint.
Definition at line 104 of file linearDamper.C.
References token::END_STATEMENT, Foam::nl, and Ostream::writeKeyword().
Referenced by linearDamper::clone(), and linearDamper::read().
The documentation for this class was generated from the following files:
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/restraints/linearDamper/linearDamper.H
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/restraints/linearDamper/linearDamper.C