OpenFOAM: foamSurfaceWriter Class Reference
foamSurfaceWriter Class Reference
A surfaceWriter for foams.
Public Member Functions
TypeName ("foam")
Runtime type information.
foamSurfaceWriter ()
Construct null.
virtual ~foamSurfaceWriter ()
Destructor.
virtual bool separateGeometry ()
True if the surface format supports geometry in a separate file.
virtual void write (const fileName &outputDir, const fileName &surfaceName, const pointField &points, const faceList &faces, const bool verbose=false) const
Write single surface geometry to file.
virtual void write (const fileName &outputDir, const fileName &surfaceName, const pointField &points, const faceList &faces, const word &fieldName, const Field< scalar > &values, const bool isNodeValues, const bool verbose=false) const
Write scalarField for a single surface to file.
virtual void write (const fileName &outputDir, const fileName &surfaceName, const pointField &points, const faceList &faces, const word &fieldName, const Field< vector > &values, const bool isNodeValues, const bool verbose=false) const
Write vectorField for a single surface to file.
virtual void write (const fileName &outputDir, const fileName &surfaceName, const pointField &points, const faceList &faces, const word &fieldName, const Field< sphericalTensor > &values, const bool isNodeValues, const bool verbose=false) const
Write sphericalTensorField for a single surface to file.
virtual void write (const fileName &outputDir, const fileName &surfaceName, const pointField &points, const faceList &faces, const word &fieldName, const Field< symmTensor > &values, const bool isNodeValues, const bool verbose=false) const
Write symmTensorField for a single surface to file.
virtual void write (const fileName &outputDir, const fileName &surfaceName, const pointField &points, const faceList &faces, const word &fieldName, const Field< tensor > &values, const bool isNodeValues, const bool verbose=false) const
Write tensorField for a single surface to file.
Public Member Functions inherited from surfaceWriter
TypeName ("surfaceWriter")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, surfaceWriter, word,(),())
declareRunTimeSelectionTable (autoPtr, surfaceWriter, wordDict,(const dictionary &optDict),(optDict))
surfaceWriter ()
Construct null.
virtual ~surfaceWriter ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from surfaceWriter
static autoPtr< surfaceWriter > New (const word &writeType)
Return a reference to the selected surfaceWriter.
static autoPtr< surfaceWriter > New (const word &writeType, const dictionary &writeOptions)
Return a reference to the selected surfaceWriter.
Detailed Description
A surfaceWriter for foams.
Source files
foamSurfaceWriter.H
foamSurfaceWriter.C
Definition at line 48 of file foamSurfaceWriter.H.
Constructor & Destructor Documentation
foamSurfaceWriter()
foamSurfaceWriter ()
Construct null.
Definition at line 86 of file foamSurfaceWriter.C.
~foamSurfaceWriter()
~foamSurfaceWriter () virtual
Destructor.
Definition at line 94 of file foamSurfaceWriter.C.
References foamSurfaceWriter::write().
Member Function Documentation
TypeName()
TypeName ("foam")
Runtime type information.
separateGeometry()
virtual bool separateGeometry () inline virtual
True if the surface format supports geometry in a separate file.
False if geometry and field must be in a single file
Reimplemented from surfaceWriter.
Definition at line 89 of file foamSurfaceWriter.H.
write() [1/6]
void write (const fileName & outputDir, const fileName & surfaceName, const pointField & points, const faceList & faces, const bool verbose = false) const virtual
Write single surface geometry to file.
Reimplemented from surfaceWriter.
Definition at line 101 of file foamSurfaceWriter.C.
References Foam::defineSurfaceWriterWriteFields(), Foam::endl(), forAll, Foam::Info, Foam::isDir(), Foam::mkDir(), List< T >::size(), and VectorSpace< Vector< scalar >, scalar, 3 >::zero.
Referenced by foamSurfaceWriter::~foamSurfaceWriter().
write() [2/6]
virtual void write (const fileName & outputDir, const fileName & surfaceName, const pointField & points, const faceList & faces, const word & fieldName, const Field< scalar > & values, const bool isNodeValues, const bool verbose = false) const virtual
Write scalarField for a single surface to file.
One value per face or vertex (isNodeValues = true)
Reimplemented from surfaceWriter.
write() [3/6]
virtual void write (const fileName & outputDir, const fileName & surfaceName, const pointField & points, const faceList & faces, const word & fieldName, const Field< vector > & values, const bool isNodeValues, const bool verbose = false) const virtual
Write vectorField for a single surface to file.
One value per face or vertex (isNodeValues = true)
Reimplemented from surfaceWriter.
write() [4/6]
virtual void write (const fileName & outputDir, const fileName & surfaceName, const pointField & points, const faceList & faces, const word & fieldName, const Field< sphericalTensor > & values, const bool isNodeValues, const bool verbose = false) const virtual
Write sphericalTensorField for a single surface to file.
One value per face or vertex (isNodeValues = true)
Reimplemented from surfaceWriter.
write() [5/6]
virtual void write (const fileName & outputDir, const fileName & surfaceName, const pointField & points, const faceList & faces, const word & fieldName, const Field< symmTensor > & values, const bool isNodeValues, const bool verbose = false) const virtual
Write symmTensorField for a single surface to file.
One value per face or vertex (isNodeValues = true)
Reimplemented from surfaceWriter.
write() [6/6]
virtual void write (const fileName & outputDir, const fileName & surfaceName, const pointField & points, const faceList & faces, const word & fieldName, const Field< tensor > & values, const bool isNodeValues, const bool verbose = false) const virtual
Write tensorField for a single surface to file.
One value per face or vertex (isNodeValues = true)
Reimplemented from surfaceWriter.
The documentation for this class was generated from the following files:
src/sampling/sampledSurface/writers/foam/foamSurfaceWriter.H
src/sampling/sampledSurface/writers/foam/foamSurfaceWriter.C