OpenFOAM: linearSpring Class Reference
linearSpring Class Reference
sixDoFRigidBodyMotionRestraints model. Linear spring.
Public Member Functions
TypeName ("linearSpring")
Runtime type information.
linearSpring (const word &name, const dictionary &sDoFRBMRDict)
Construct from components.
virtual autoPtr< sixDoFRigidBodyMotionRestraint > clone () const
Construct and return a clone.
virtual ~linearSpring ()
Destructor.
virtual void restrain (const sixDoFRigidBodyMotion &motion, vector &restraintPosition, vector &restraintForce, vector &restraintMoment) const
Calculate the restraint position, force and moment.
virtual bool read (const dictionary &sDoFRBMRCoeff)
Update properties from given dictionary.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from sixDoFRigidBodyMotionRestraint
TypeName ("sixDoFRigidBodyMotionRestraint")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, sixDoFRigidBodyMotionRestraint, dictionary,(const word &name, const dictionary &sDoFRBMRDict),(name, sDoFRBMRDict))
sixDoFRigidBodyMotionRestraint (const word &name, const dictionary &sDoFRBMRDict)
Construct from the sDoFRBMRDict dictionary and Time.
virtual ~sixDoFRigidBodyMotionRestraint ()
Destructor.
const word & name () const
Return the name.
const dictionary & coeffDict () const
Additional Inherited Members
Static Public Member Functions inherited from sixDoFRigidBodyMotionRestraint
static autoPtr< sixDoFRigidBodyMotionRestraint > New (const word &name, const dictionary &sDoFRBMRDict)
Select constructed from the sDoFRBMRDict dictionary and Time.
Protected Attributes inherited from sixDoFRigidBodyMotionRestraint
word name_
Name of the restraint.
dictionary sDoFRBMRCoeffs_
Restraint model specific coefficient dictionary.
Detailed Description
sixDoFRigidBodyMotionRestraints model. Linear spring.
Source files
linearSpring.H
linearSpring.C
Definition at line 52 of file linearSpring.H.
Constructor & Destructor Documentation
linearSpring()
linearSpring (const word & name, const dictionary & sDoFRBMRDict)
Construct from components.
Definition at line 51 of file linearSpring.C.
References Foam::read().
Referenced by linearSpring::clone().
~linearSpring()
~linearSpring () virtual
Destructor.
Definition at line 69 of file linearSpring.C.
References linearSpring::restrain().
Referenced by linearSpring::clone().
Member Function Documentation
TypeName()
TypeName ("linearSpring")
Runtime type information.
clone()
virtual autoPtr<sixDoFRigidBodyMotionRestraint> clone () const inline virtual
Construct and return a clone.
Implements sixDoFRigidBodyMotionRestraint.
Definition at line 91 of file linearSpring.H.
References linearSpring::linearSpring(), linearSpring::read(), linearSpring::restrain(), linearSpring::write(), and linearSpring::~linearSpring().
restrain()
void restrain (const sixDoFRigidBodyMotion & motion, vector & restraintPosition, vector & restraintForce, vector & restraintMoment) const virtual
Calculate the restraint position, force and moment.
Global reference frame vectors.
Implements sixDoFRigidBodyMotionRestraint.
Definition at line 76 of file linearSpring.C.
References Foam::endl(), Foam::Info, Foam::mag(), linearSpring::read(), sixDoFRigidBodyMotion::report(), sixDoFRigidBodyMotion::transform(), sixDoFRigidBodyMotion::velocity(), and Foam::Zero.
Referenced by linearSpring::clone(), and linearSpring::~linearSpring().
read()
bool read (const dictionary & sDoFRBMRCoeff) virtual
Update properties from given dictionary.
Reimplemented from sixDoFRigidBodyMotionRestraint.
Definition at line 107 of file linearSpring.C.
References sixDoFRigidBodyMotionRestraint::read(), and linearSpring::write().
Referenced by linearSpring::clone(), and linearSpring::restrain().
write()
void write (Ostream & os) const virtual
Write.
Implements sixDoFRigidBodyMotionRestraint.
Definition at line 124 of file linearSpring.C.
References token::END_STATEMENT, Foam::nl, and Ostream::writeKeyword().
Referenced by linearSpring::clone(), and linearSpring::read().
The documentation for this class was generated from the following files:
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/restraints/linearSpring/linearSpring.H
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/restraints/linearSpring/linearSpring.C