OpenFOAM: surfaceWriter Class Reference
surfaceWriter Class Reference
Base class for surface writers.
Public Member Functions
TypeName ("surfaceWriter")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, surfaceWriter, word,(),())
declareRunTimeSelectionTable (autoPtr, surfaceWriter, wordDict,(const dictionary &optDict),(optDict))
surfaceWriter ()
Construct null.
virtual ~surfaceWriter ()
Destructor.
virtual bool separateGeometry ()
True if the surface format supports geometry in a separate file.
virtual void write (const fileName &outputDir, const fileName &surfaceName, const pointField &points, const faceList &faces, const bool verbose=false) const
Write single surface geometry to file.
virtual void write (const fileName &outputDir, const fileName &surfaceName, const pointField &points, const faceList &faces, const word &fieldName, const Field< scalar > &values, const bool isNodeValues, const bool verbose=false) const
Write scalarField for a single surface to file.
virtual void write (const fileName &outputDir, const fileName &surfaceName, const pointField &points, const faceList &faces, const word &fieldName, const Field< vector > &values, const bool isNodeValues, const bool verbose=false) const
Write vectorField for a single surface to file.
virtual void write (const fileName &outputDir, const fileName &surfaceName, const pointField &points, const faceList &faces, const word &fieldName, const Field< sphericalTensor > &values, const bool isNodeValues, const bool verbose=false) const
Write sphericalTensorField for a single surface to file.
virtual void write (const fileName &outputDir, const fileName &surfaceName, const pointField &points, const faceList &faces, const word &fieldName, const Field< symmTensor > &values, const bool isNodeValues, const bool verbose=false) const
Write symmTensorField for a single surface to file.
virtual void write (const fileName &outputDir, const fileName &surfaceName, const pointField &points, const faceList &faces, const word &fieldName, const Field< tensor > &values, const bool isNodeValues, const bool verbose=false) const
Write tensorField for a single surface to file.
Static Public Member Functions
static autoPtr< surfaceWriter > New (const word &writeType)
Return a reference to the selected surfaceWriter.
static autoPtr< surfaceWriter > New (const word &writeType, const dictionary &writeOptions)
Return a reference to the selected surfaceWriter.
Detailed Description
Base class for surface writers.
Source files
surfaceWriter.H
surfaceWriter.C
Definition at line 54 of file surfaceWriter.H.
Constructor & Destructor Documentation
surfaceWriter()
surfaceWriter ()
Construct null.
Definition at line 104 of file surfaceWriter.C.
~surfaceWriter()
~surfaceWriter () virtual
Destructor.
Definition at line 110 of file surfaceWriter.C.
Member Function Documentation
TypeName()
TypeName ("surfaceWriter")
Runtime type information.
declareRunTimeSelectionTable() [1/2]
declareRunTimeSelectionTable (autoPtr , surfaceWriter , word , () , ())
declareRunTimeSelectionTable() [2/2]
declareRunTimeSelectionTable (autoPtr , surfaceWriter , wordDict , (const dictionary &optDict) , (optDict))
New() [1/2]
Foam::autoPtr< Foam::surfaceWriter > New (const word & writeType) static
Return a reference to the selected surfaceWriter.
Definition at line 55 of file surfaceWriter.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::nl, and MeshedSurfaceProxy< Face >::writeTypes().
Referenced by surfaceFieldValue::initialise(), surfaceWriter::New(), and sampledSurfaces::read().
New() [2/2]
Foam::autoPtr< Foam::surfaceWriter > New (const word & writeType, const dictionary & writeOptions) static
Return a reference to the selected surfaceWriter.
Select with extra write option
Definition at line 86 of file surfaceWriter.C.
References surfaceWriter::New().
separateGeometry()
virtual bool separateGeometry () inline virtual
True if the surface format supports geometry in a separate file.
False if geometry and field must be in a single file
Reimplemented in nastranSurfaceWriter, starcdSurfaceWriter, ensightSurfaceWriter, foamSurfaceWriter, and proxySurfaceWriter.
Definition at line 112 of file surfaceWriter.H.
write() [1/6]
virtual void write (const fileName & outputDir, const fileName & surfaceName, const pointField & points, const faceList & faces, const bool verbose = false) const inline virtual
Write single surface geometry to file.
Reimplemented in nastranSurfaceWriter, rawSurfaceWriter, starcdSurfaceWriter, ensightSurfaceWriter, foamSurfaceWriter, vtkSurfaceWriter, and proxySurfaceWriter.
Definition at line 119 of file surfaceWriter.H.
Referenced by surfaceWriter::write().
write() [2/6]
virtual void write (const fileName & outputDir, const fileName & surfaceName, const pointField & points, const faceList & faces, const word & fieldName, const Field< scalar > & values, const bool isNodeValues, const bool verbose = false) const inline virtual
Write scalarField for a single surface to file.
One value per face or vertex (isNodeValues = true)
Reimplemented in nastranSurfaceWriter, rawSurfaceWriter, starcdSurfaceWriter, ensightSurfaceWriter, foamSurfaceWriter, vtkSurfaceWriter, and dxSurfaceWriter.
Definition at line 131 of file surfaceWriter.H.
References surfaceWriter::write().
write() [3/6]
virtual void write (const fileName & outputDir, const fileName & surfaceName, const pointField & points, const faceList & faces, const word & fieldName, const Field< vector > & values, const bool isNodeValues, const bool verbose = false) const inline virtual
Write vectorField for a single surface to file.
One value per face or vertex (isNodeValues = true)
Reimplemented in nastranSurfaceWriter, rawSurfaceWriter, starcdSurfaceWriter, ensightSurfaceWriter, foamSurfaceWriter, vtkSurfaceWriter, and dxSurfaceWriter.
Definition at line 146 of file surfaceWriter.H.
References surfaceWriter::write().
write() [4/6]
virtual void write (const fileName & outputDir, const fileName & surfaceName, const pointField & points, const faceList & faces, const word & fieldName, const Field< sphericalTensor > & values, const bool isNodeValues, const bool verbose = false) const inline virtual
Write sphericalTensorField for a single surface to file.
One value per face or vertex (isNodeValues = true)
Reimplemented in nastranSurfaceWriter, rawSurfaceWriter, starcdSurfaceWriter, ensightSurfaceWriter, foamSurfaceWriter, vtkSurfaceWriter, and dxSurfaceWriter.
Definition at line 161 of file surfaceWriter.H.
References surfaceWriter::write().
write() [5/6]
virtual void write (const fileName & outputDir, const fileName & surfaceName, const pointField & points, const faceList & faces, const word & fieldName, const Field< symmTensor > & values, const bool isNodeValues, const bool verbose = false) const inline virtual
Write symmTensorField for a single surface to file.
One value per face or vertex (isNodeValues = true)
Reimplemented in nastranSurfaceWriter, rawSurfaceWriter, ensightSurfaceWriter, foamSurfaceWriter, vtkSurfaceWriter, and dxSurfaceWriter.
Definition at line 176 of file surfaceWriter.H.
References surfaceWriter::write().
write() [6/6]
virtual void write (const fileName & outputDir, const fileName & surfaceName, const pointField & points, const faceList & faces, const word & fieldName, const Field< tensor > & values, const bool isNodeValues, const bool verbose = false) const inline virtual
Write tensorField for a single surface to file.
One value per face or vertex (isNodeValues = true)
Reimplemented in nastranSurfaceWriter, rawSurfaceWriter, ensightSurfaceWriter, foamSurfaceWriter, vtkSurfaceWriter, and dxSurfaceWriter.
Definition at line 191 of file surfaceWriter.H.
The documentation for this class was generated from the following files:
src/sampling/sampledSurface/writers/surfaceWriter.H
src/sampling/sampledSurface/writers/surfaceWriter.C