OpenFOAM: line Class Reference
line Class Reference
Translation constraint on the centre of rotation: may only move along a line.
Public Member Functions
TypeName ("line")
Runtime type information.
line (const word &name, const dictionary &sDoFRBMCDict, const sixDoFRigidBodyMotion &motion)
Construct from components.
virtual autoPtr< sixDoFRigidBodyMotionConstraint > clone () const
Construct and return a clone.
virtual ~line ()
Destructor.
virtual void setCentreOfRotation (point &) const
Set the centre of rotation to the projection of the.
virtual void constrainTranslation (pointConstraint &) const
Apply and accumulate translational constraints.
virtual void constrainRotation (pointConstraint &) const
Apply and accumulate rotational constraints.
virtual bool read (const dictionary &sDoFRBMCCoeff)
Update properties from given dictionary.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from sixDoFRigidBodyMotionConstraint
TypeName ("sixDoFRigidBodyMotionConstraint")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, sixDoFRigidBodyMotionConstraint, dictionary,(const word &name, const dictionary &sDoFRBMCDict, const sixDoFRigidBodyMotion &motion),(name, sDoFRBMCDict, motion))
sixDoFRigidBodyMotionConstraint (const word &name, const dictionary &sDoFRBMCDict, const sixDoFRigidBodyMotion &motion)
Construct from the sDoFRBMCDict dictionary and Time.
virtual ~sixDoFRigidBodyMotionConstraint ()
Destructor.
const word & name () const
Return the name.
virtual void setCentreOfRotation (point &) const
Set the centre of rotation if not the centre of mass.
const dictionary & coeffDict () const
Additional Inherited Members
Static Public Member Functions inherited from sixDoFRigidBodyMotionConstraint
static autoPtr< sixDoFRigidBodyMotionConstraint > New (const word &name, const dictionary &sDoFRBMCDict, const sixDoFRigidBodyMotion &motion)
Select constructed from the sDoFRBMCDict dictionary and Time.
Protected Attributes inherited from sixDoFRigidBodyMotionConstraint
word name_
Name of the constraint.
dictionary sDoFRBMCCoeffs_
Constraint model specific coefficient dictionary.
const sixDoFRigidBodyMotion & motion_
Reference to the body motion.
Detailed Description
Translation constraint on the centre of rotation: may only move along a line.
If 'centreOfRotation' is not provided in the dictionary the centre of mass is used.
Source files
sixDoFRigidBodyMotionLineConstraint.H
sixDoFRigidBodyMotionLineConstraint.C
Definition at line 55 of file sixDoFRigidBodyMotionLineConstraint.H.
Constructor & Destructor Documentation
line()
line (const word & name, const dictionary & sDoFRBMCDict, const sixDoFRigidBodyMotion & motion)
Construct from components.
Definition at line 51 of file sixDoFRigidBodyMotionLineConstraint.C.
References Foam::read().
Referenced by line::clone().
~line()
~line () virtual
Destructor.
Definition at line 65 of file sixDoFRigidBodyMotionLineConstraint.C.
References line::setCentreOfRotation().
Referenced by line::clone().
Member Function Documentation
TypeName()
TypeName ("line")
Runtime type information.
clone()
virtual autoPtr<sixDoFRigidBodyMotionConstraint> clone () const inline virtual
Construct and return a clone.
Implements sixDoFRigidBodyMotionConstraint.
Definition at line 85 of file sixDoFRigidBodyMotionLineConstraint.H.
References line::constrainRotation(), line::constrainTranslation(), line::line(), line::read(), line::setCentreOfRotation(), line::write(), and line::~line().
setCentreOfRotation()
void setCentreOfRotation (point & CofR) const virtual
Set the centre of rotation to the projection of the.
centre of mass onto the line
Definition at line 72 of file sixDoFRigidBodyMotionLineConstraint.C.
References line::constrainTranslation().
Referenced by line::clone(), and line::~line().
constrainTranslation()
void constrainTranslation (pointConstraint & pc) const virtual
Apply and accumulate translational constraints.
Implements sixDoFRigidBodyMotionConstraint.
Definition at line 81 of file sixDoFRigidBodyMotionLineConstraint.C.
References pointConstraint::combine(), and line::constrainRotation().
Referenced by line::clone(), and line::setCentreOfRotation().
constrainRotation()
void constrainRotation (pointConstraint & pc) const virtual
Apply and accumulate rotational constraints.
Implements sixDoFRigidBodyMotionConstraint.
Definition at line 90 of file sixDoFRigidBodyMotionLineConstraint.C.
References line::read().
Referenced by line::clone(), and line::constrainTranslation().
read()
bool read (const dictionary & sDoFRBMCCoeff) virtual
Update properties from given dictionary.
Reimplemented from sixDoFRigidBodyMotionConstraint.
Definition at line 97 of file sixDoFRigidBodyMotionLineConstraint.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, Foam::mag(), sixDoFRigidBodyMotionConstraint::read(), and line::write().
Referenced by line::clone(), and line::constrainRotation().
write()
void write (Ostream & os) const virtual
Write.
Reimplemented from sixDoFRigidBodyMotionConstraint.
Definition at line 129 of file sixDoFRigidBodyMotionLineConstraint.C.
References token::END_STATEMENT, Foam::nl, and Ostream::writeKeyword().
Referenced by line::clone(), and line::read().
The documentation for this class was generated from the following files:
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/constraints/line/sixDoFRigidBodyMotionLineConstraint.H
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/constraints/line/sixDoFRigidBodyMotionLineConstraint.C