OpenFOAM: nastranSurfaceWriter Class Reference
nastranSurfaceWriter Class Reference
A surface writer for the Nastran file format - both surface mesh and fields.
Public Types
enum writeFormat { wfShort, wfLong, wfFree }
Public Member Functions
TypeName ("nastran")
Runtime type information.
nastranSurfaceWriter ()
Construct null.
nastranSurfaceWriter (const dictionary &options)
Construct with some output options.
virtual ~nastranSurfaceWriter ()
Destructor.
virtual bool separateGeometry ()
True if the surface format supports geometry in a separate file.
virtual void write (const fileName &outputDir, const fileName &surfaceName, const pointField &points, const faceList &faces, const bool verbose=false) const
Write single surface geometry to file.
virtual void write (const fileName &outputDir, const fileName &surfaceName, const pointField &points, const faceList &faces, const word &fieldName, const Field< scalar > &values, const bool isNodeValues, const bool verbose=false) const
Write scalarField for a single surface to file.
virtual void write (const fileName &outputDir, const fileName &surfaceName, const pointField &points, const faceList &faces, const word &fieldName, const Field< vector > &values, const bool isNodeValues, const bool verbose=false) const
Write vectorField for a single surface to file.
virtual void write (const fileName &outputDir, const fileName &surfaceName, const pointField &points, const faceList &faces, const word &fieldName, const Field< sphericalTensor > &values, const bool isNodeValues, const bool verbose=false) const
Write sphericalTensorField for a single surface to file.
virtual void write (const fileName &outputDir, const fileName &surfaceName, const pointField &points, const faceList &faces, const word &fieldName, const Field< symmTensor > &values, const bool isNodeValues, const bool verbose=false) const
Write symmTensorField for a single surface to file.
virtual void write (const fileName &outputDir, const fileName &surfaceName, const pointField &points, const faceList &faces, const word &fieldName, const Field< tensor > &values, const bool isNodeValues, const bool verbose=false) const
Write tensorField for a single surface to file.
Public Member Functions inherited from surfaceWriter
TypeName ("surfaceWriter")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, surfaceWriter, word,(),())
declareRunTimeSelectionTable (autoPtr, surfaceWriter, wordDict,(const dictionary &optDict),(optDict))
surfaceWriter ()
Construct null.
virtual ~surfaceWriter ()
Destructor.
Static Public Attributes
static const NamedEnum< writeFormat, 3 > writeFormatNames_
Additional Inherited Members
Static Public Member Functions inherited from surfaceWriter
static autoPtr< surfaceWriter > New (const word &writeType)
Return a reference to the selected surfaceWriter.
static autoPtr< surfaceWriter > New (const word &writeType, const dictionary &writeOptions)
Return a reference to the selected surfaceWriter.
Detailed Description
A surface writer for the Nastran file format - both surface mesh and fields.
formatOptions { nastran { From OpenFOAM field name to Nastran field name fields ((pMean PLOAD2)); Optional scale scale 2.0; Optional format format free; //short, long, free } };
Source files
nastranSurfaceWriter.H
nastranSurfaceWriter.C
nastranSurfaceWriterTemplates.C
Definition at line 64 of file nastranSurfaceWriter.H.
Member Enumeration Documentation
writeFormat
enum writeFormat
Enumerator
wfShort
wfLong
wfFree
Definition at line 70 of file nastranSurfaceWriter.H.
Constructor & Destructor Documentation
nastranSurfaceWriter() [1/2]
nastranSurfaceWriter ()
Construct null.
Definition at line 321 of file nastranSurfaceWriter.C.
nastranSurfaceWriter() [2/2]
nastranSurfaceWriter (const dictionary & options)
Construct with some output options.
Definition at line 330 of file nastranSurfaceWriter.C.
References forAll, dictionary::found(), dictionary::lookup(), NamedEnum< Enum, nEnum >::read(), and nastranSurfaceWriter::writeFormatNames_.
~nastranSurfaceWriter()
~nastranSurfaceWriter () virtual
Destructor.
Definition at line 353 of file nastranSurfaceWriter.C.
References nastranSurfaceWriter::write().
Member Function Documentation
TypeName()
TypeName ("nastran")
Runtime type information.
separateGeometry()
virtual bool separateGeometry () inline virtual
True if the surface format supports geometry in a separate file.
False if geometry and field must be in a single file
Reimplemented from surfaceWriter.
Definition at line 173 of file nastranSurfaceWriter.H.
write() [1/6]
void write (const fileName & outputDir, const fileName & surfaceName, const pointField & points, const faceList & faces, const bool verbose = false) const virtual
Write single surface geometry to file.
Reimplemented from surfaceWriter.
Definition at line 360 of file nastranSurfaceWriter.C.
References Foam::endl(), Foam::Info, Foam::isDir(), Foam::mkDir(), OFstream::name(), Foam::nl, and List< T >::size().
Referenced by nastranSurfaceWriter::~nastranSurfaceWriter().
write() [2/6]
virtual void write (const fileName & outputDir, const fileName & surfaceName, const pointField & points, const faceList & faces, const word & fieldName, const Field< scalar > & values, const bool isNodeValues, const bool verbose = false) const virtual
Write scalarField for a single surface to file.
One value per face or vertex (isNodeValues = true)
Reimplemented from surfaceWriter.
write() [3/6]
virtual void write (const fileName & outputDir, const fileName & surfaceName, const pointField & points, const faceList & faces, const word & fieldName, const Field< vector > & values, const bool isNodeValues, const bool verbose = false) const virtual
Write vectorField for a single surface to file.
One value per face or vertex (isNodeValues = true)
Reimplemented from surfaceWriter.
write() [4/6]
virtual void write (const fileName & outputDir, const fileName & surfaceName, const pointField & points, const faceList & faces, const word & fieldName, const Field< sphericalTensor > & values, const bool isNodeValues, const bool verbose = false) const virtual
Write sphericalTensorField for a single surface to file.
One value per face or vertex (isNodeValues = true)
Reimplemented from surfaceWriter.
write() [5/6]
virtual void write (const fileName & outputDir, const fileName & surfaceName, const pointField & points, const faceList & faces, const word & fieldName, const Field< symmTensor > & values, const bool isNodeValues, const bool verbose = false) const virtual
Write symmTensorField for a single surface to file.
One value per face or vertex (isNodeValues = true)
Reimplemented from surfaceWriter.
write() [6/6]
virtual void write (const fileName & outputDir, const fileName & surfaceName, const pointField & points, const faceList & faces, const word & fieldName, const Field< tensor > & values, const bool isNodeValues, const bool verbose = false) const virtual
Write tensorField for a single surface to file.
One value per face or vertex (isNodeValues = true)
Reimplemented from surfaceWriter.
Member Data Documentation
writeFormatNames_
const NamedEnum< nastranSurfaceWriter::writeFormat, 3 > writeFormatNames_ static
Definition at line 77 of file nastranSurfaceWriter.H.
Referenced by NamedEnum< directionType, 3 >::names(), and nastranSurfaceWriter::nastranSurfaceWriter().
The documentation for this class was generated from the following files:
src/sampling/sampledSurface/writers/nastran/nastranSurfaceWriter.H
src/sampling/sampledSurface/writers/nastran/nastranSurfaceWriter.C
src/sampling/sampledSurface/writers/nastran/nastranSurfaceWriterTemplates.C