OpenFOAM: starcdSurfaceWriter Class Reference
starcdSurfaceWriter Class Reference
A surfaceWriter for STARCD files.
Public Member Functions
TypeName ("starcd")
Runtime type information.
starcdSurfaceWriter ()
Construct null.
virtual ~starcdSurfaceWriter ()
Destructor.
virtual bool separateGeometry ()
True if the surface format supports geometry in a separate file.
virtual void write (const fileName &outputDir, const fileName &surfaceName, const pointField &points, const faceList &faces, const bool verbose=false) const
Write single surface geometry to file.
virtual void write (const fileName &outputDir, const fileName &surfaceName, const pointField &points, const faceList &faces, const word &fieldName, const Field< scalar > &values, const bool isNodeValues, const bool verbose=false) const
Write scalarField for a single surface to file.
virtual void write (const fileName &outputDir, const fileName &surfaceName, const pointField &points, const faceList &faces, const word &fieldName, const Field< vector > &values, const bool isNodeValues, const bool verbose=false) const
Write vectorField for a single surface to file.
virtual void write (const fileName &outputDir, const fileName &surfaceName, const pointField &points, const faceList &faces, const word &fieldName, const Field< sphericalTensor > &values, const bool isNodeValues, const bool verbose=false) const
Write sphericalTensorField for a single surface to file.
template<>
void writeData (Ostream &os, const scalar &v)
template<>
void writeData (Ostream &os, const vector &v)
template<>
void writeData (Ostream &os, const sphericalTensor &v)
Public Member Functions inherited from surfaceWriter
TypeName ("surfaceWriter")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, surfaceWriter, word,(),())
declareRunTimeSelectionTable (autoPtr, surfaceWriter, wordDict,(const dictionary &optDict),(optDict))
surfaceWriter ()
Construct null.
virtual ~surfaceWriter ()
Destructor.
virtual void write (const fileName &outputDir, const fileName &surfaceName, const pointField &points, const faceList &faces, const word &fieldName, const Field< symmTensor > &values, const bool isNodeValues, const bool verbose=false) const
Write symmTensorField for a single surface to file.
virtual void write (const fileName &outputDir, const fileName &surfaceName, const pointField &points, const faceList &faces, const word &fieldName, const Field< tensor > &values, const bool isNodeValues, const bool verbose=false) const
Write tensorField for a single surface to file.
Additional Inherited Members
Static Public Member Functions inherited from surfaceWriter
static autoPtr< surfaceWriter > New (const word &writeType)
Return a reference to the selected surfaceWriter.
static autoPtr< surfaceWriter > New (const word &writeType, const dictionary &writeOptions)
Return a reference to the selected surfaceWriter.
Detailed Description
A surfaceWriter for STARCD files.
The geometry is written via the MeshedSurfaceProxy, the fields are written in a trivial ASCII format with ID and VALUE as so-called user data. These .usr files can be read into proSTAR with these types of commands. For element data:
    getuser FILENAME.usr cell scalar free
    getuser FILENAME.usr cell vector free
and for vertex data:
    getuser FILENAME.usr vertex scalar free
    getuser FILENAME.usr vertex vector free
Note
Only scalar and vector fields are supported directly. A sphericalTensor is written as a scalar. Other field types are not written.
Source files
starcdSurfaceWriter.H
starcdSurfaceWriter.C
Definition at line 67 of file starcdSurfaceWriter.H.
Constructor & Destructor Documentation
starcdSurfaceWriter()
starcdSurfaceWriter ()
Construct null.
Definition at line 127 of file starcdSurfaceWriter.C.
~starcdSurfaceWriter()
~starcdSurfaceWriter () virtual
Destructor.
Definition at line 135 of file starcdSurfaceWriter.C.
References starcdSurfaceWriter::write().
Member Function Documentation
TypeName()
TypeName ("starcd")
Runtime type information.
separateGeometry()
virtual bool separateGeometry () inline virtual
True if the surface format supports geometry in a separate file.
False if geometry and field must be in a single file
Reimplemented from surfaceWriter.
Definition at line 112 of file starcdSurfaceWriter.H.
write() [1/4]
void write (const fileName & outputDir, const fileName & surfaceName, const pointField & points, const faceList & faces, const bool verbose = false) const virtual
Write single surface geometry to file.
Reimplemented from surfaceWriter.
Definition at line 142 of file starcdSurfaceWriter.C.
References defineSurfaceWriterWriteField(), Foam::endl(), Foam::Info, Foam::isDir(), Foam::mkDir(), and points.
Referenced by starcdSurfaceWriter::~starcdSurfaceWriter().
write() [2/4]
virtual void write (const fileName & outputDir, const fileName & surfaceName, const pointField & points, const faceList & faces, const word & fieldName, const Field< scalar > & values, const bool isNodeValues, const bool verbose = false) const virtual
Write scalarField for a single surface to file.
One value per face or vertex (isNodeValues = true)
Reimplemented from surfaceWriter.
write() [3/4]
virtual void write (const fileName & outputDir, const fileName & surfaceName, const pointField & points, const faceList & faces, const word & fieldName, const Field< vector > & values, const bool isNodeValues, const bool verbose = false) const virtual
Write vectorField for a single surface to file.
One value per face or vertex (isNodeValues = true)
Reimplemented from surfaceWriter.
write() [4/4]
virtual void write (const fileName & outputDir, const fileName & surfaceName, const pointField & points, const faceList & faces, const word & fieldName, const Field< sphericalTensor > & values, const bool isNodeValues, const bool verbose = false) const virtual
Write sphericalTensorField for a single surface to file.
One value per face or vertex (isNodeValues = true)
Reimplemented from surfaceWriter.
writeData() [1/3]
void writeData (Ostream & os, const scalar & v) inline
Definition at line 48 of file starcdSurfaceWriter.C.
References Foam::nl.
writeData() [2/3]
void writeData (Ostream & os, const vector & v) inline
Definition at line 59 of file starcdSurfaceWriter.C.
References Foam::nl.
writeData() [3/3]
void writeData (Ostream & os, const sphericalTensor & v) inline
Definition at line 70 of file starcdSurfaceWriter.C.
References Foam::endl(), forAll, Foam::Info, Foam::isDir(), Foam::mkDir(), OFstream::name(), Foam::nl, points, and writeData().
The documentation for this class was generated from the following files:
src/sampling/sampledSurface/writers/starcd/starcdSurfaceWriter.H
src/sampling/sampledSurface/writers/starcd/starcdSurfaceWriter.C