OpenFOAM: sixDoFRigidBodyMotionRestraint Class Reference
sixDoFRigidBodyMotionRestraint Class Reference abstract
Base class for defining restraints for sixDoF motions.
Public Member Functions
TypeName ("sixDoFRigidBodyMotionRestraint")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, sixDoFRigidBodyMotionRestraint, dictionary,(const word &name, const dictionary &sDoFRBMRDict),(name, sDoFRBMRDict))
sixDoFRigidBodyMotionRestraint (const word &name, const dictionary &sDoFRBMRDict)
Construct from the sDoFRBMRDict dictionary and Time.
virtual autoPtr< sixDoFRigidBodyMotionRestraint > clone () const =0
Construct and return a clone.
virtual ~sixDoFRigidBodyMotionRestraint ()
Destructor.
const word & name () const
Return the name.
virtual void restrain (const sixDoFRigidBodyMotion &motion, vector &restraintPosition, vector &restraintForce, vector &restraintMoment) const =0
Calculate the restraint position, force and moment.
virtual bool read (const dictionary &sDoFRBMRDict)
Update properties from given dictionary.
const dictionary & coeffDict () const
virtual void write (Ostream &) const =0
Write.
Static Public Member Functions
static autoPtr< sixDoFRigidBodyMotionRestraint > New (const word &name, const dictionary &sDoFRBMRDict)
Select constructed from the sDoFRBMRDict dictionary and Time.
Protected Attributes
word name_
Name of the restraint.
dictionary sDoFRBMRCoeffs_
Restraint model specific coefficient dictionary.
Detailed Description
Base class for defining restraints for sixDoF motions.
Source files
sixDoFRigidBodyMotionRestraint.H
sixDoFRigidBodyMotionRestraint.C
sixDoFRigidBodyMotionRestraintNew.C
Definition at line 64 of file sixDoFRigidBodyMotionRestraint.H.
Constructor & Destructor Documentation
sixDoFRigidBodyMotionRestraint()
sixDoFRigidBodyMotionRestraint (const word & name, const dictionary & sDoFRBMRDict)
Construct from the sDoFRBMRDict dictionary and Time.
Definition at line 40 of file sixDoFRigidBodyMotionRestraint.C.
~sixDoFRigidBodyMotionRestraint()
~sixDoFRigidBodyMotionRestraint () virtual
Destructor.
Definition at line 52 of file sixDoFRigidBodyMotionRestraint.C.
References sixDoFRigidBodyMotionRestraint::read().
Member Function Documentation
TypeName()
TypeName ("sixDoFRigidBodyMotionRestraint")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , sixDoFRigidBodyMotionRestraint , dictionary , (const word &name, const dictionary &sDoFRBMRDict) , (name, sDoFRBMRDict))
clone()
virtual autoPtr<sixDoFRigidBodyMotionRestraint> clone () const pure virtual
Construct and return a clone.
Implemented in tabulatedAxialAngularSpring, linearSpring, linearAxialAngularSpring, sphericalAngularSpring, linearDamper, and sphericalAngularDamper.
New()
Foam::autoPtr< Foam::sixDoFRigidBodyMotionRestraint > New (const word & name, const dictionary & sDoFRBMRDict) static
Select constructed from the sDoFRBMRDict dictionary and Time.
Definition at line 32 of file sixDoFRigidBodyMotionRestraintNew.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, dictionary::lookup(), Foam::name(), and Foam::nl.
Referenced by sixDoFRigidBodyMotion::addRestraints().
name()
const word& name () const inline
Return the name.
Definition at line 126 of file sixDoFRigidBodyMotionRestraint.H.
References sixDoFRigidBodyMotionRestraint::name_, sixDoFRigidBodyMotionRestraint::read(), and sixDoFRigidBodyMotionRestraint::restrain().
restrain()
virtual void restrain (const sixDoFRigidBodyMotion & motion, vector & restraintPosition, vector & restraintForce, vector & restraintMoment) const pure virtual
Calculate the restraint position, force and moment.
Global reference frame vectors.
Implemented in tabulatedAxialAngularSpring, linearSpring, linearAxialAngularSpring, sphericalAngularSpring, linearDamper, and sphericalAngularDamper.
Referenced by sixDoFRigidBodyMotionRestraint::name().
read()
bool read (const dictionary & sDoFRBMRDict) virtual
Update properties from given dictionary.
Reimplemented in tabulatedAxialAngularSpring, linearSpring, linearAxialAngularSpring, sphericalAngularSpring, linearDamper, and sphericalAngularDamper.
Definition at line 59 of file sixDoFRigidBodyMotionRestraint.C.
Referenced by sixDoFRigidBodyMotionRestraint::name(), sphericalAngularDamper::read(), linearDamper::read(), sphericalAngularSpring::read(), linearAxialAngularSpring::read(), linearSpring::read(), tabulatedAxialAngularSpring::read(), and sixDoFRigidBodyMotionRestraint::~sixDoFRigidBodyMotionRestraint().
coeffDict()
const dictionary& coeffDict () const inline
Definition at line 147 of file sixDoFRigidBodyMotionRestraint.H.
References sixDoFRigidBodyMotionRestraint::sDoFRBMRCoeffs_, and sixDoFRigidBodyMotionRestraint::write().
write()
virtual void write (Ostream &) const pure virtual
Write.
Implemented in tabulatedAxialAngularSpring, linearSpring, linearAxialAngularSpring, sphericalAngularSpring, linearDamper, and sphericalAngularDamper.
Referenced by sixDoFRigidBodyMotionRestraint::coeffDict().
Member Data Documentation
name_
word name_ protected
Name of the restraint.
Definition at line 72 of file sixDoFRigidBodyMotionRestraint.H.
Referenced by sixDoFRigidBodyMotionRestraint::name().
sDoFRBMRCoeffs_
dictionary sDoFRBMRCoeffs_ protected
Restraint model specific coefficient dictionary.
Definition at line 75 of file sixDoFRigidBodyMotionRestraint.H.
Referenced by sixDoFRigidBodyMotionRestraint::coeffDict().
The documentation for this class was generated from the following files:
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/restraints/sixDoFRigidBodyMotionRestraint/sixDoFRigidBodyMotionRestraint.H
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/restraints/sixDoFRigidBodyMotionRestraint/sixDoFRigidBodyMotionRestraint.C
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/restraints/sixDoFRigidBodyMotionRestraint/sixDoFRigidBodyMotionRestraintNew.C