OpenFOAM: MeshedSurfaceIOAllocator Class Reference
MeshedSurfaceIOAllocator Class Reference
A helper class for storing points, faces and zones with IO capabilities.
Public Member Functions
MeshedSurfaceIOAllocator (const IOobject &ioPoints, const IOobject &ioFaces, const IOobject &ioZones)
Read construct from IOobjects.
MeshedSurfaceIOAllocator (const IOobject &ioPoints, const pointField &points, const IOobject &ioFaces, const faceList &faces, const IOobject &ioZones, const surfZoneList &zones)
Construct from IOobjects, copying components.
MeshedSurfaceIOAllocator (const IOobject &ioPoints, const Xfer< pointField > &points, const IOobject &ioFaces, const Xfer< faceList > &faces, const IOobject &ioZones, const Xfer< surfZoneList > &zones)
Construct from IOobjects, possibly transferring components.
pointIOField & storedIOPoints ()
Non-const access to the points.
faceCompactIOList & storedIOFaces ()
Non-const access to the faces.
surfZoneIOList & storedIOZones ()
Non-const access to the zones.
const pointIOField & storedIOPoints () const
Const access to the points.
const faceCompactIOList & storedIOFaces () const
Const access to the faces.
const surfZoneIOList & storedIOZones () const
Const access to the zones.
void clear ()
Clear primitive data (points, faces and zones)
void resetFaces (const Xfer< faceList > &faces, const Xfer< surfZoneList > &zones)
Reset primitive data (points, faces and zones)
void reset (const Xfer< pointField > &points, const Xfer< faceList > &faces, const Xfer< surfZoneList > &zones)
Reset primitive data (points, faces and zones)
void reset (const Xfer< List< point >> &points, const Xfer< faceList > &faces, const Xfer< surfZoneList > &zones)
Reset primitive data (points, faces and zones)
Detailed Description
A helper class for storing points, faces and zones with IO capabilities.
Source files
MeshedSurfaceIOAllocator.H
MeshedSurfaceIOAllocator.C
Definition at line 50 of file MeshedSurfaceIOAllocator.H.
Constructor & Destructor Documentation
MeshedSurfaceIOAllocator() [1/3]
MeshedSurfaceIOAllocator (const IOobject & ioPoints, const IOobject & ioFaces, const IOobject & ioZones)
Read construct from IOobjects.
Definition at line 31 of file MeshedSurfaceIOAllocator.C.
MeshedSurfaceIOAllocator() [2/3]
MeshedSurfaceIOAllocator (const IOobject & ioPoints, const pointField & points, const IOobject & ioFaces, const faceList & faces, const IOobject & ioZones, const surfZoneList & zones)
Construct from IOobjects, copying components.
Definition at line 44 of file MeshedSurfaceIOAllocator.C.
MeshedSurfaceIOAllocator() [3/3]
MeshedSurfaceIOAllocator (const IOobject & ioPoints, const Xfer< pointField > & points, const IOobject & ioFaces, const Xfer< faceList > & faces, const IOobject & ioZones, const Xfer< surfZoneList > & zones)
Construct from IOobjects, possibly transferring components.
Definition at line 60 of file MeshedSurfaceIOAllocator.C.
Member Function Documentation
storedIOPoints() [1/2]
pointIOField& storedIOPoints () inline
Non-const access to the points.
Definition at line 113 of file MeshedSurfaceIOAllocator.H.
Referenced by surfMesh::points(), surfMesh::pointsInstance(), surfMesh::readUpdate(), surfMesh::setInstance(), surfMesh::storedPoints(), and surfMesh::transfer().
storedIOFaces() [1/2]
faceCompactIOList& storedIOFaces () inline
Non-const access to the faces.
Definition at line 119 of file MeshedSurfaceIOAllocator.H.
Referenced by surfMesh::faces(), surfMesh::facesInstance(), surfMesh::setInstance(), surfMesh::storedFaces(), and surfMesh::transfer().
storedIOZones() [1/2]
surfZoneIOList& storedIOZones () inline
Non-const access to the zones.
Definition at line 125 of file MeshedSurfaceIOAllocator.H.
Referenced by surfMesh::addZones(), surfMesh::checkZones(), surfMesh::readUpdate(), surfMesh::setInstance(), surfMesh::storedZones(), surfMesh::surfZones(), and surfMesh::transfer().
storedIOPoints() [2/2]
const pointIOField& storedIOPoints () const inline
Const access to the points.
Definition at line 131 of file MeshedSurfaceIOAllocator.H.
storedIOFaces() [2/2]
const faceCompactIOList& storedIOFaces () const inline
Const access to the faces.
Definition at line 137 of file MeshedSurfaceIOAllocator.H.
storedIOZones() [2/2]
const surfZoneIOList& storedIOZones () const inline
Const access to the zones.
Definition at line 143 of file MeshedSurfaceIOAllocator.H.
References MeshedSurfaceIOAllocator::clear(), MeshedSurfaceIOAllocator::reset(), and MeshedSurfaceIOAllocator::resetFaces().
clear()
void clear ()
Clear primitive data (points, faces and zones)
Definition at line 77 of file MeshedSurfaceIOAllocator.C.
References List< T >::clear(), and MeshedSurfaceIOAllocator::resetFaces().
Referenced by MeshedSurfaceIOAllocator::storedIOZones().
resetFaces()
void resetFaces (const Xfer< faceList > & faces, const Xfer< surfZoneList > & zones)
Reset primitive data (points, faces and zones)
Note, optimized to avoid overwriting data (with Xfer::null)
Definition at line 86 of file MeshedSurfaceIOAllocator.C.
References Foam::notNull(), MeshedSurfaceIOAllocator::reset(), and List< T >::transfer().
Referenced by MeshedSurfaceIOAllocator::clear(), MeshedSurfaceIOAllocator::reset(), and MeshedSurfaceIOAllocator::storedIOZones().
reset() [1/2]
void reset (const Xfer< pointField > & points, const Xfer< faceList > & faces, const Xfer< surfZoneList > & zones)
Reset primitive data (points, faces and zones)
Note, optimized to avoid overwriting data (with Xfer::null)
Definition at line 104 of file MeshedSurfaceIOAllocator.C.
References Foam::notNull(), points, MeshedSurfaceIOAllocator::resetFaces(), and List< T >::transfer().
Referenced by MeshedSurfaceIOAllocator::resetFaces(), surfMesh::resetPrimitives(), and MeshedSurfaceIOAllocator::storedIOZones().
reset() [2/2]
void reset (const Xfer< List< point >> & points, const Xfer< faceList > & faces, const Xfer< surfZoneList > & zones)
Reset primitive data (points, faces and zones)
Note, optimized to avoid overwriting data (with Xfer::null)
Definition at line 122 of file MeshedSurfaceIOAllocator.C.
References Foam::notNull(), points, MeshedSurfaceIOAllocator::resetFaces(), and List< T >::transfer().
The documentation for this class was generated from the following files:
src/surfMesh/MeshedSurfaceAllocator/MeshedSurfaceIOAllocator.H
src/surfMesh/MeshedSurfaceAllocator/MeshedSurfaceIOAllocator.C