OpenFOAM: MeshedSurfaceProxy< Face > Class Template Reference
MeshedSurfaceProxy< Face > Class Template Reference
A proxy for writing MeshedSurface, UnsortedMeshedSurface and surfMesh to various file formats.
Public Types
typedef Face FaceType
Face type used.
Public Member Functions
ClassName ("MeshedSurfaceProxy")
Runtime type information.
MeshedSurfaceProxy (const pointField &, const List< Face > &, const List< surfZone > &=List< surfZone >(), const List< label > &faceMap=List< label >())
Construct from component references.
virtual ~MeshedSurfaceProxy ()
Destructor.
declareMemberFunctionSelectionTable (void, MeshedSurfaceProxy, write, fileExtension,(const fileName &name, const MeshedSurfaceProxy< Face > &surf),(name, surf))
const pointField & points () const
Return const access to the points.
const List< Face > & faces () const
Return const access to the faces.
const List< surfZone > & surfZones () const
Const access to the surface zones.
const List< label > & faceMap () const
Const access to the faceMap, zero-sized when unused.
bool useFaceMap () const
Use faceMap?
virtual void write (const fileName &name) const
Generic write routine. Chooses writer based on extension.
virtual void write (const Time &, const word &surfName="") const
Write to database.
Public Member Functions inherited from surfaceFormatsCore
surfaceFormatsCore ()
Construct null.
virtual ~surfaceFormatsCore ()
Destructor.
Static Public Member Functions
static wordHashSet writeTypes ()
The file format types that can be written via MeshedSurfaceProxy.
static bool canWriteType (const word &ext, const bool verbose=false)
Can this file format type be written via MeshedSurfaceProxy?
static void write (const fileName &, const MeshedSurfaceProxy< Face > &)
Write to file.
Static Public Member Functions inherited from surfaceFormatsCore
static bool checkSupport (const wordHashSet &available, const word &ext, const bool verbose, const word &functionName)
static fileName localMeshFileName (const word &surfName="")
Return the local file name (within time directory)
static fileName findMeshInstance (const Time &, const word &surfName="")
Find instance with surfName.
static fileName findMeshFile (const Time &, const word &surfName="")
Find mesh file with surfName.
Additional Inherited Members
Static Public Attributes inherited from surfaceFormatsCore
static word nativeExt
The file extension corresponding to 'native' surface format.
Static Protected Member Functions inherited from surfaceFormatsCore
template<class Container >
static List< surfZone > oneZone (const Container &container, const word &name="zone0")
Return a list with a single entry,.
static string getLineNoComment (IFstream &)
Read non-comment line.
Detailed Description
template<class Face>
class Foam::MeshedSurfaceProxy< Face >
A proxy for writing MeshedSurface, UnsortedMeshedSurface and surfMesh to various file formats.
Source files
MeshedSurfaceProxy.H
MeshedSurfaceProxy.C
MeshedSurfaceProxyCore.C
Definition at line 73 of file MeshedSurface.H.
Member Typedef Documentation
FaceType
typedef Face FaceType
Face type used.
Definition at line 83 of file MeshedSurfaceProxy.H.
Constructor & Destructor Documentation
MeshedSurfaceProxy()
MeshedSurfaceProxy (const pointField & pointLst, const List< Face > & faceLst, const List< surfZone > & zoneLst = List<surfZone>(), const List< label > & faceMap = List<label>())
Construct from component references.
Definition at line 217 of file MeshedSurfaceProxy.C.
Referenced by MeshedSurfaceProxy< Face >::write().
~MeshedSurfaceProxy()
~MeshedSurfaceProxy () virtual
Destructor.
Definition at line 234 of file MeshedSurfaceProxy.C.
Member Function Documentation
ClassName()
ClassName ("MeshedSurfaceProxy< Face >")
Runtime type information.
writeTypes()
Foam::wordHashSet writeTypes () static
The file format types that can be written via MeshedSurfaceProxy.
Definition at line 36 of file MeshedSurfaceProxy.C.
References MeshedSurfaceProxy< Face >::canWriteType().
Referenced by surfaceWriter::New().
canWriteType()
bool canWriteType (const word & ext, const bool verbose = false) static
Can this file format type be written via MeshedSurfaceProxy?
Definition at line 44 of file MeshedSurfaceProxy.C.
References Foam::endl(), Foam::exit(), fileName::ext(), Foam::FatalError, FatalErrorInFunction, InfoInFunction, Foam::name(), Foam::nl, and MeshedSurfaceProxy< Face >::write().
Referenced by MeshedSurfaceProxy< Face >::writeTypes().
declareMemberFunctionSelectionTable()
declareMemberFunctionSelectionTable (void , MeshedSurfaceProxy< Face > , write , fileExtension , (const fileName &name, const MeshedSurfaceProxy< Face > &surf) , (name, surf))
write() [1/3]
static void write (const fileName & , const MeshedSurfaceProxy< Face > &) static
Write to file.
Referenced by MeshedSurfaceProxy< Face >::canWriteType(), MeshedSurfaceProxy< Face >::write(), UnsortedMeshedSurface< Face >::write(), and MeshedSurface< Foam::face >::write().
points()
const pointField& points () const inline
Return const access to the points.
Definition at line 138 of file MeshedSurfaceProxy.H.
Referenced by X3DsurfaceFormat< Face >::write(), WRLsurfaceFormat< Face >::write(), SMESHsurfaceFormat< Face >::write(), OBJsurfaceFormat< Face >::write(), VTKsurfaceFormat< Face >::write(), AC3DsurfaceFormat< Face >::write(), OFFsurfaceFormat< Face >::write(), TRIsurfaceFormat< Face >::write(), STARCDsurfaceFormat< Face >::write(), OFSsurfaceFormat< Face >::write(), STLsurfaceFormat< Face >::writeAscii(), and STLsurfaceFormat< Face >::writeBinary().
faces()
const List<Face>& faces () const inline
Return const access to the faces.
Definition at line 144 of file MeshedSurfaceProxy.H.
References MeshedSurfaceProxy< Face >::surfZones().
Referenced by X3DsurfaceFormat< Face >::write(), WRLsurfaceFormat< Face >::write(), SMESHsurfaceFormat< Face >::write(), OBJsurfaceFormat< Face >::write(), VTKsurfaceFormat< Face >::write(), AC3DsurfaceFormat< Face >::write(), OFFsurfaceFormat< Face >::write(), TRIsurfaceFormat< Face >::write(), STARCDsurfaceFormat< Face >::write(), OFSsurfaceFormat< Face >::write(), STLsurfaceFormat< Face >::writeAscii(), and STLsurfaceFormat< Face >::writeBinary().
surfZones()
const List<surfZone>& surfZones () const inline
Const access to the surface zones.
If zones are defined, they must be contiguous and cover the entire surface
Definition at line 152 of file MeshedSurfaceProxy.H.
Referenced by MeshedSurfaceProxy< Face >::faces(), X3DsurfaceFormat< Face >::write(), WRLsurfaceFormat< Face >::write(), SMESHsurfaceFormat< Face >::write(), OBJsurfaceFormat< Face >::write(), VTKsurfaceFormat< Face >::write(), AC3DsurfaceFormat< Face >::write(), OFFsurfaceFormat< Face >::write(), TRIsurfaceFormat< Face >::write(), STARCDsurfaceFormat< Face >::write(), OFSsurfaceFormat< Face >::write(), STLsurfaceFormat< Face >::writeAscii(), and STLsurfaceFormat< Face >::writeBinary().
faceMap()
const List<label>& faceMap () const inline
Const access to the faceMap, zero-sized when unused.
Definition at line 158 of file MeshedSurfaceProxy.H.
Referenced by X3DsurfaceFormat< Face >::write(), WRLsurfaceFormat< Face >::write(), SMESHsurfaceFormat< Face >::write(), OBJsurfaceFormat< Face >::write(), VTKsurfaceFormat< Face >::write(), OFFsurfaceFormat< Face >::write(), TRIsurfaceFormat< Face >::write(), STARCDsurfaceFormat< Face >::write(), OFSsurfaceFormat< Face >::write(), STLsurfaceFormat< Face >::writeAscii(), and STLsurfaceFormat< Face >::writeBinary().
useFaceMap()
bool useFaceMap () const inline
Use faceMap?
Definition at line 164 of file MeshedSurfaceProxy.H.
Referenced by X3DsurfaceFormat< Face >::write(), WRLsurfaceFormat< Face >::write(), SMESHsurfaceFormat< Face >::write(), OBJsurfaceFormat< Face >::write(), VTKsurfaceFormat< Face >::write(), AC3DsurfaceFormat< Face >::write(), OFFsurfaceFormat< Face >::write(), TRIsurfaceFormat< Face >::write(), STARCDsurfaceFormat< Face >::write(), OFSsurfaceFormat< Face >::write(), STLsurfaceFormat< Face >::writeAscii(), and STLsurfaceFormat< Face >::writeBinary().
write() [2/3]
virtual void write (const fileName & name) const inline virtual
Generic write routine. Chooses writer based on extension.
Definition at line 172 of file MeshedSurfaceProxy.H.
References MeshedSurfaceProxy< Face >::write().
write() [3/3]
void write (const Time & t, const word & surfName = "") const virtual
Write to database.
Definition at line 88 of file MeshedSurfaceProxy.C.
References Foam::endl(), Foam::faceMap(), InfoInFunction, Foam::isDir(), MeshedSurfaceProxy< Face >::MeshedSurfaceProxy(), Foam::mkDir(), Foam::name(), IOobject::name(), points, Foam::reorder(), Time::timeName(), Time::timePath(), IOobject::writeEndDivider(), and IOobject::writeHeader().
The documentation for this class was generated from the following files:
src/surfMesh/MeshedSurface/MeshedSurface.H
src/surfMesh/MeshedSurfaceProxy/MeshedSurfaceProxy.H
src/surfMesh/MeshedSurfaceProxy/MeshedSurfaceProxy.C