OpenFOAM: sixDoFRigidBodyMotionState Class Reference
sixDoFRigidBodyMotionState Class Reference
Holds the motion state of sixDoF object. Wrapped up together to allow rapid scatter to other processors. The processors must all maintain exactly the same state data to avoid any drift or inconsistency.
Public Member Functions
sixDoFRigidBodyMotionState ()
Construct null.
sixDoFRigidBodyMotionState (const dictionary &dict)
Construct from dictionary.
sixDoFRigidBodyMotionState (const sixDoFRigidBodyMotionState &)
Construct as copy.
~sixDoFRigidBodyMotionState ()
Destructor.
const point & centreOfRotation () const
Return access to the centre of mass.
const tensor & Q () const
Return access to the orientation.
const vector & v () const
Return access to velocity.
const vector & a () const
Return access to acceleration.
const vector & pi () const
Return access to angular momentum.
const vector & tau () const
Return access to torque.
point & centreOfRotation ()
Return non-const access to the centre of mass.
tensor & Q ()
Return non-const access to the orientation.
vector & v ()
Return non-const access to vector.
vector & a ()
Return non-const access to acceleration.
vector & pi ()
Return non-const access to angular momentum.
vector & tau ()
Return non-const access to torque.
void write (dictionary &dict) const
Write to dictionary.
void write (Ostream &) const
Write to stream.
Friends
Istream & operator>> (Istream &, sixDoFRigidBodyMotionState &)
Ostream & operator<< (Ostream &, const sixDoFRigidBodyMotionState &)
Detailed Description
Holds the motion state of sixDoF object. Wrapped up together to allow rapid scatter to other processors. The processors must all maintain exactly the same state data to avoid any drift or inconsistency.
Source files
sixDoFRigidBodyMotionState.H
sixDoFRigidBodyMotionStateI.H
sixDoFRigidBodyMotionState.C
sixDoFRigidBodyMotionStateIO.C
Definition at line 66 of file sixDoFRigidBodyMotionState.H.
Constructor & Destructor Documentation
sixDoFRigidBodyMotionState() [1/3]
sixDoFRigidBodyMotionState ()
Construct null.
Definition at line 30 of file sixDoFRigidBodyMotionState.C.
Referenced by sixDoFRigidBodyMotionState::sixDoFRigidBodyMotionState().
sixDoFRigidBodyMotionState() [2/3]
sixDoFRigidBodyMotionState (const dictionary & dict)
Construct from dictionary.
Definition at line 42 of file sixDoFRigidBodyMotionState.C.
References sixDoFRigidBodyMotionState::sixDoFRigidBodyMotionState().
sixDoFRigidBodyMotionState() [3/3]
sixDoFRigidBodyMotionState (const sixDoFRigidBodyMotionState & sDoFRBMS)
Construct as copy.
Definition at line 63 of file sixDoFRigidBodyMotionState.C.
~sixDoFRigidBodyMotionState()
~sixDoFRigidBodyMotionState ()
Destructor.
Definition at line 78 of file sixDoFRigidBodyMotionState.C.
Member Function Documentation
centreOfRotation() [1/2]
const Foam::point & centreOfRotation () const inline
Return access to the centre of mass.
Definition at line 29 of file sixDoFRigidBodyMotionStateI.H.
Referenced by sixDoFSolver::centreOfRotation(), sixDoFRigidBodyMotion::centreOfRotation(), sixDoFSolver::centreOfRotation0(), sixDoFRigidBodyMotion::momentArm(), and sixDoFRigidBodyMotion::sixDoFRigidBodyMotion().
Q() [1/2]
const Foam::tensor & Q () const inline
Return access to the orientation.
Definition at line 35 of file sixDoFRigidBodyMotionStateI.H.
Referenced by sixDoFSolver::Q(), sixDoFSolver::Q0(), and sixDoFRigidBodyMotion::v().
v() [1/2]
const Foam::vector & v () const inline
Return access to velocity.
Definition at line 41 of file sixDoFRigidBodyMotionStateI.H.
Referenced by sixDoFSolver::v(), sixDoFRigidBodyMotion::v(), and sixDoFSolver::v0().
a() [1/2]
const Foam::vector & a () const inline
Return access to acceleration.
Definition at line 47 of file sixDoFRigidBodyMotionStateI.H.
Referenced by sixDoFSolver::a(), sixDoFSolver::a0(), and sixDoFRigidBodyMotion::v().
pi() [1/2]
const Foam::vector & pi () const inline
Return access to angular momentum.
Definition at line 53 of file sixDoFRigidBodyMotionStateI.H.
Referenced by sixDoFSolver::pi(), sixDoFSolver::pi0(), and sixDoFRigidBodyMotion::v().
tau() [1/2]
const Foam::vector & tau () const inline
Return access to torque.
Definition at line 59 of file sixDoFRigidBodyMotionStateI.H.
Referenced by sixDoFSolver::tau(), sixDoFSolver::tau0(), and sixDoFRigidBodyMotion::v().
centreOfRotation() [2/2]
Foam::point & centreOfRotation () inline
Return non-const access to the centre of mass.
Definition at line 65 of file sixDoFRigidBodyMotionStateI.H.
Q() [2/2]
Foam::tensor & Q () inline
Return non-const access to the orientation.
Definition at line 71 of file sixDoFRigidBodyMotionStateI.H.
v() [2/2]
Foam::vector & v () inline
Return non-const access to vector.
Definition at line 77 of file sixDoFRigidBodyMotionStateI.H.
a() [2/2]
Foam::vector & a () inline
Return non-const access to acceleration.
Definition at line 83 of file sixDoFRigidBodyMotionStateI.H.
pi() [2/2]
Foam::vector & pi () inline
Return non-const access to angular momentum.
Definition at line 89 of file sixDoFRigidBodyMotionStateI.H.
tau() [2/2]
Foam::vector & tau () inline
Return non-const access to torque.
Definition at line 95 of file sixDoFRigidBodyMotionStateI.H.
write() [1/2]
void write (dictionary & dict) const
Write to dictionary.
Definition at line 31 of file sixDoFRigidBodyMotionStateIO.C.
References dictionary::add().
Referenced by sixDoFRigidBodyMotion::write().
write() [2/2]
void write (Ostream & os) const
Write to stream.
Definition at line 42 of file sixDoFRigidBodyMotionStateIO.C.
References token::END_STATEMENT, Foam::nl, and Ostream::writeKeyword().
Friends And Related Function Documentation
operator>>
Istream& operator>> (Istream & , sixDoFRigidBodyMotionState &) friend
operator<<
Ostream& operator<< (Ostream & , const sixDoFRigidBodyMotionState &) friend
The documentation for this class was generated from the following files:
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/sixDoFRigidBodyMotionState.H
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/sixDoFRigidBodyMotionState.C
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/sixDoFRigidBodyMotionStateI.H
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/sixDoFRigidBodyMotionStateIO.C