OpenFOAM: OBJstream Class Reference
OBJstream Class Reference
OFstream which keeps track of vertices.
Public Member Functions
ClassName ("OBJstream")
OBJstream (const fileName &pathname, streamFormat format=ASCII, versionNumber version=currentVersion, compressionType compression=UNCOMPRESSED)
Construct from pathname.
~OBJstream ()
Destructor.
label nVertices () const
Return the number of vertices written.
virtual Ostream & write (const char)
Write character.
virtual Ostream & write (const char *)
Write character string.
virtual Ostream & write (const word &)
Write word.
virtual Ostream & write (const string &)
Write string.
virtual Ostream & writeQuoted (const std::string &, const bool quoted=true)
Write std::string surrounded by quotes.
Ostream & write (const point &)
Write point.
Ostream & write (const point &, const vector &)
Write point and vector normal ('vn')
Ostream & write (const edge &, const UList< point > &)
Write edge as points with line.
Ostream & write (const linePointRef &)
Write line.
Ostream & write (const linePointRef &, const vector &n0, const vector &n1)
Write line with points and vector normals ('vn')
Ostream & write (const triPointRef &, const bool lines=true)
Write triangle as points with lines or filled polygon.
Ostream & write (const face &, const UList< point > &, const bool lines=true)
Write face as points with lines or filled polygon.
Ostream & write (const faceList &, const pointField &, const bool lines=true)
Write patch as points and faces with lines or filled polygons.
Public Member Functions inherited from OFstream
ClassName ("OFstream")
OFstream (const fileName &pathname, streamFormat format=ASCII, versionNumber version=currentVersion, compressionType compression=UNCOMPRESSED)
Construct from pathname.
~OFstream ()
Destructor.
const fileName & name () const
Return the name of the stream.
fileName & name ()
Return non-const access to the name of the stream.
virtual ostream & stdStream ()
Access to underlying std::ostream.
virtual const ostream & stdStream () const
Const access to underlying std::ostream.
void print (Ostream &) const
Print description of IOstream to Ostream.
Public Member Functions inherited from OSstream
OSstream (ostream &os, const string &name, streamFormat format=ASCII, versionNumber version=currentVersion, compressionType compression=UNCOMPRESSED)
Set stream status.
virtual ios_base::fmtflags flags () const
Return flags of output stream.
virtual Ostream & write (const token &)
Write next token to stream.
virtual Ostream & write (const int32_t)
Write int32_t.
virtual Ostream & write (const int64_t)
Write int64_t.
virtual Ostream & write (const floatScalar)
Write floatScalar.
virtual Ostream & write (const doubleScalar)
Write doubleScalar.
virtual Ostream & write (const char *, std::streamsize)
Write binary block.
virtual void indent ()
Add indentation characters.
virtual ios_base::fmtflags flags (const ios_base::fmtflags flags)
Set flags of output stream.
virtual void flush ()
Flush stream.
virtual void endl ()
Add newline and flush stream.
virtual int width () const
Get width of output field.
virtual int width (const int)
Set width of output field (and return old width)
virtual int precision () const
Get precision of output field.
virtual int precision (const int)
Set precision of output field (and return old precision)
Public Member Functions inherited from Ostream
Ostream (streamFormat format=ASCII, versionNumber version=currentVersion, compressionType compression=UNCOMPRESSED)
Set stream status.
virtual ~Ostream ()
Destructor.
virtual Ostream & write (const keyType &)
Write keyType.
unsigned short indentLevel () const
Return indent level.
unsigned short & indentLevel ()
Access to indent level.
void incrIndent ()
Incrememt the indent level.
void decrIndent ()
Decrememt the indent level.
Ostream & writeKeyword (const keyType &)
Write the keyword followed by an appropriate indentation.
Ostream & operator() () const
Return a non-const reference to const Ostream.
Public Member Functions inherited from IOstream
IOstream (streamFormat format, versionNumber version, compressionType compression=UNCOMPRESSED)
Construct setting format and version.
virtual ~IOstream ()
Destructor.
virtual bool check (const char *operation) const
Check IOstream status for given operation.
void fatalCheck (const char *operation) const
Check IOstream status for given operation.
bool opened () const
Return true if stream has been opened.
bool closed () const
Return true if stream is closed.
bool good () const
Return true if next operation might succeed.
bool eof () const
Return true if end of input seen.
bool fail () const
Return true if next operation will fail.
bool bad () const
Return true if stream is corrupted.
operator void * () const
Return non-zero if the stream has not failed.
bool operator! () const
Return true if the stream has failed.
streamFormat format () const
Return current stream format.
streamFormat format (const streamFormat fmt)
Set the stream format.
streamFormat format (const word &fmt)
Set the stream format from word.
versionNumber version () const
Return the stream version.
versionNumber version (const versionNumber ver)
Set the stream version.
compressionType compression () const
Return the stream compression.
compressionType compression (const compressionType cmp)
Set the stream compression.
compressionType compression (const word &cmp)
Set the stream compression from word.
label lineNumber () const
Return current stream line number.
label & lineNumber ()
Return current stream line number.
label lineNumber (const label ln)
Set the stream line number.
void setEof ()
Set stream to have reached eof.
void setFail ()
Set stream to have failed.
void setBad ()
Set stream to be bad.
ios_base::fmtflags setf (const ios_base::fmtflags f)
Set flags of stream.
ios_base::fmtflags setf (const ios_base::fmtflags f, const ios_base::fmtflags mask)
Set flags of given field of stream.
void unsetf (const ios_base::fmtflags uf)
Unset flags of stream.
void print (Ostream &, const int streamState) const
Check given stream state bits.
InfoProxy< IOstream > info () const
Return info proxy.
Additional Inherited Members
Public Types inherited from IOstream
enum streamAccess { OPENED, CLOSED }
Enumeration for whether the stream open or closed.
enum streamFormat { ASCII, BINARY }
Enumeration for the format of data in the stream.
enum compressionType { UNCOMPRESSED, COMPRESSED }
Enumeration for the format of data in the stream.
Static Public Member Functions inherited from IOstream
static streamFormat formatEnum (const word &)
Return stream format of given format name.
static compressionType compressionEnum (const word &)
Return compression of given compression name.
static unsigned int defaultPrecision ()
Return the default precision.
static unsigned int defaultPrecision (unsigned int p)
Reset the default precision (and return old precision)
Static Public Attributes inherited from IOstream
static const versionNumber originalVersion
Original version number.
static const versionNumber currentVersion
Current version number.
static unsigned int precision_
Default precision.
Protected Member Functions inherited from IOstream
void setOpened ()
Set stream opened.
void setClosed ()
Set stream closed.
void setState (ios_base::iostate state)
Set stream state.
void setGood ()
Set stream to be good.
Protected Attributes inherited from Ostream
unsigned short indentLevel_
Current indent level.
Protected Attributes inherited from IOstream
label lineNumber_
Static Protected Attributes inherited from Ostream
static const unsigned short indentSize_ = 4
Number of spaces per indent level.
static const unsigned short entryIndentation_ = 16
Indentation of the entry from the start of the keyword.
Detailed Description
OFstream which keeps track of vertices.
Source files
OBJstream.H
OBJstream.C
Definition at line 53 of file OBJstream.H.
Constructor & Destructor Documentation
OBJstream()
OBJstream (const fileName & pathname, streamFormat format = ASCII, versionNumber version = currentVersion, compressionType compression = UNCOMPRESSED)
Construct from pathname.
Definition at line 61 of file OBJstream.C.
~OBJstream()
~OBJstream ()
Destructor.
Definition at line 76 of file OBJstream.C.
Member Function Documentation
ClassName()
ClassName ("OBJstream")
nVertices()
label nVertices () const inline
Return the number of vertices written.
Definition at line 95 of file OBJstream.H.
References Ostream::write(), OBJstream::write(), and OBJstream::writeQuoted().
write() [1/12]
Foam::Ostream & write (const char c) virtual
Write character.
Reimplemented from OSstream.
Definition at line 82 of file OBJstream.C.
Referenced by OBJstream::nVertices(), OBJstream::write(), extendedEdgeMesh::writeObj(), and meshRefinement::zonify().
write() [2/12]
Foam::Ostream & write (const char * str) virtual
Write character string.
Reimplemented from OSstream.
Definition at line 89 of file OBJstream.C.
References p.
write() [3/12]
Foam::Ostream & write (const word & str) virtual
Write word.
Reimplemented from OSstream.
Definition at line 99 of file OBJstream.C.
References write().
write() [4/12]
Foam::Ostream & write (const string & str) virtual
Write string.
In the rare case that the string contains a final trailing backslash, it will be dropped to the appearance of an escaped double-quote.
Reimplemented from OSstream.
Definition at line 106 of file OBJstream.C.
References token::BEGIN_STRING, token::END_STRING, token::NL, OSstream::write(), and OBJstream::writeQuoted().
writeQuoted()
Foam::Ostream & writeQuoted (const std::string & str, const bool quoted = true) virtual
Write std::string surrounded by quotes.
Optional write without quotes.
Reimplemented from OSstream.
Definition at line 150 of file OBJstream.C.
References token::BEGIN_STRING, token::END_STRING, token::NL, write(), and OSstream::write().
Referenced by OBJstream::nVertices(), and OBJstream::write().
write() [5/12]
Foam::Ostream & write (const point & pt)
Write point.
Definition at line 209 of file OBJstream.C.
References Foam::nl, write(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
write() [6/12]
Foam::Ostream & write (const point & pt, const vector & n)
Write point and vector normal ('vn')
Definition at line 217 of file OBJstream.C.
References Foam::nl, write(), OSstream::write(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
write() [7/12]
Foam::Ostream & write (const edge & e, const UList< point > & points)
Write edge as points with line.
Definition at line 226 of file OBJstream.C.
References Foam::nl, and write().
write() [8/12]
Foam::Ostream & write (const linePointRef & ln)
Write line.
Definition at line 235 of file OBJstream.C.
References line< Point, PointRef >::end(), Foam::nl, line< Point, PointRef >::start(), write(), and OBJstream::write().
write() [9/12]
Foam::Ostream & write (const linePointRef & ln, const vector & n0, const vector & n1)
Write line with points and vector normals ('vn')
Definition at line 245 of file OBJstream.C.
References line< Point, PointRef >::end(), Foam::nl, line< Point, PointRef >::start(), write(), and OBJstream::write().
write() [10/12]
Foam::Ostream & write (const triPointRef & f, const bool lines = true)
Write triangle as points with lines or filled polygon.
Definition at line 259 of file OBJstream.C.
References triangle< Point, PointRef >::a(), triangle< Point, PointRef >::b(), triangle< Point, PointRef >::c(), write(), and OBJstream::write().
write() [11/12]
Foam::Ostream & write (const face & f, const UList< point > & points, const bool lines = true)
Write face as points with lines or filled polygon.
Definition at line 291 of file OBJstream.C.
References forAll, write(), and OBJstream::write().
write() [12/12]
Foam::Ostream & write (const faceList & fcs, const pointField & points, const bool lines = true)
Write patch as points and faces with lines or filled polygons.
Definition at line 325 of file OBJstream.C.
References Foam::e, forAll, Foam::nl, List< T >::size(), and write().
The documentation for this class was generated from the following files:
src/surfMesh/surfaceFormats/obj/OBJstream.H
src/surfMesh/surfaceFormats/obj/OBJstream.C