OpenFOAM: Newmark Class Reference
Newmark Class Reference
Newmark 2nd-order time-integrator for 6DoF solid-body motion.
Public Member Functions
TypeName ("Newmark")
Runtime type information.
Newmark (const dictionary &dict, sixDoFRigidBodyMotion &body)
Construct from a dictionary and the body.
virtual ~Newmark ()
Destructor.
virtual void solve (bool firstIter, const vector &fGlobal, const vector &tauGlobal, scalar deltaT, scalar deltaT0)
Drag coefficient.
Public Member Functions inherited from sixDoFSolver
TypeName ("sixDoFSolver")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, sixDoFSolver, dictionary,(const dictionary &dict, sixDoFRigidBodyMotion &body),(dict, body))
sixDoFSolver (sixDoFRigidBodyMotion &body)
virtual ~sixDoFSolver ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from sixDoFSolver
static autoPtr< sixDoFSolver > New (const dictionary &dict, sixDoFRigidBodyMotion &body)
Protected Member Functions inherited from sixDoFSolver
point & centreOfRotation ()
Return the current centre of rotation.
tensor & Q ()
Return the orientation.
vector & v ()
Return non-const access to vector.
vector & a ()
Return non-const access to acceleration.
vector & pi ()
Return non-const access to angular momentum.
vector & tau ()
Return non-const access to torque.
const point & centreOfRotation0 () const
Return the centre of rotation at previous time-step.
const tensor & Q0 () const
Return the orientation at previous time-step.
const vector & v0 () const
Return the velocity at previous time-step.
const vector & a0 () const
Return the acceleration at previous time-step.
const vector & pi0 () const
Return the angular momentum at previous time-step.
const vector & tau0 () const
Return the torque at previous time-step.
scalar aDamp () const
Acceleration damping coefficient (for steady-state simulations)
tensor tConstraints () const
Translational constraint tensor.
tensor rConstraints () const
Rotational constraint tensor.
Tuple2< tensor, vector > rotate (const tensor &Q0, const vector &pi, const scalar deltaT) const
Apply rotation tensors to Q0 for the given torque (pi) and deltaT.
void updateAcceleration (const vector &fGlobal, const vector &tauGlobal)
Update and relax accelerations from the force and torque.
Protected Attributes inherited from sixDoFSolver
sixDoFRigidBodyMotion & body_
The rigid body.
Detailed Description
Newmark 2nd-order time-integrator for 6DoF solid-body motion.
Reference:
    Newmark, N. M. (1959).
    A method of computation for structural dynamics.
    Journal of the Engineering Mechanics Division, 85(3), 67-94.
Example specification in dynamicMeshDict:
solver
{
    type    Newmark;
    gamma   0.5;    // Velocity integration coefficient
    beta    0.25;   // Position integration coefficient
}
Source files
Newmark.H
Newmark.C
Definition at line 67 of file Newmark.H.
Constructor & Destructor Documentation
Newmark()
Newmark (const dictionary & dict, sixDoFRigidBodyMotion & body)
Construct from a dictionary and the body.
Definition at line 44 of file Newmark.C.
~Newmark()
~Newmark () virtual
Destructor.
Definition at line 64 of file Newmark.C.
References Newmark::solve().
Member Function Documentation
TypeName()
TypeName ("Newmark")
Runtime type information.
solve()
void solve (bool firstIter, const vector & fGlobal, const vector & tauGlobal, scalar deltaT, scalar deltaT0) virtual
Drag coefficient.
Implements sixDoFSolver.
Definition at line 71 of file Newmark.C.
References Foam::constant::atomic::a0, Tuple2< Type1, Type2 >::first(), Foam::constant::mathematical::pi(), and Foam::sqr().
Referenced by Newmark::~Newmark().
The documentation for this class was generated from the following files:
src/sixDoFRigidBodyMotion/sixDoFSolvers/Newmark/Newmark.H
src/sixDoFRigidBodyMotion/sixDoFSolvers/Newmark/Newmark.C