OpenFOAM: symplectic Class Reference
symplectic Class Reference
Symplectic 2nd-order explicit time-integrator for 6DoF solid-body motion.
Public Member Functions
TypeName ("symplectic")
Runtime type information.
symplectic (const dictionary &dict, sixDoFRigidBodyMotion &body)
Construct from a dictionary and the body.
virtual ~symplectic ()
Destructor.
virtual void solve (bool firstIter, const vector &fGlobal, const vector &tauGlobal, scalar deltaT, scalar deltaT0)
Drag coefficient.
Public Member Functions inherited from sixDoFSolver
TypeName ("sixDoFSolver")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, sixDoFSolver, dictionary,(const dictionary &dict, sixDoFRigidBodyMotion &body),(dict, body))
sixDoFSolver (sixDoFRigidBodyMotion &body)
virtual ~sixDoFSolver ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from sixDoFSolver
static autoPtr< sixDoFSolver > New (const dictionary &dict, sixDoFRigidBodyMotion &body)
Protected Member Functions inherited from sixDoFSolver
point & centreOfRotation ()
Return the current centre of rotation.
tensor & Q ()
Return the orientation.
vector & v ()
Return non-const access to vector.
vector & a ()
Return non-const access to acceleration.
vector & pi ()
Return non-const access to angular momentum.
vector & tau ()
Return non-const access to torque.
const point & centreOfRotation0 () const
Return the centre of rotation at previous time-step.
const tensor & Q0 () const
Return the orientation at previous time-step.
const vector & v0 () const
Return the velocity at previous time-step.
const vector & a0 () const
Return the acceleration at previous time-step.
const vector & pi0 () const
Return the angular momentum at previous time-step.
const vector & tau0 () const
Return the torque at previous time-step.
scalar aDamp () const
Acceleration damping coefficient (for steady-state simulations)
tensor tConstraints () const
Translational constraint tensor.
tensor rConstraints () const
Rotational constraint tensor.
Tuple2< tensor, vector > rotate (const tensor &Q0, const vector &pi, const scalar deltaT) const
Apply rotation tensors to Q0 for the given torque (pi) and deltaT.
void updateAcceleration (const vector &fGlobal, const vector &tauGlobal)
Update and relax accelerations from the force and torque.
Protected Attributes inherited from sixDoFSolver
sixDoFRigidBodyMotion & body_
The rigid body.
Detailed Description
Symplectic 2nd-order explicit time-integrator for 6DoF solid-body motion.
Reference:
    Dullweber, A., Leimkuhler, B., & McLachlan, R. (1997).
    Symplectic splitting methods for rigid body molecular dynamics.
    The Journal of chemical physics, 107(15), 5840-5851.
Can only be used for explicit integration of the motion of the body, i.e. may only be called once per time-step, no outer-correctors may be applied. For implicit integration with outer-correctors choose either CrankNicolson or Newmark schemes.
Example specification in dynamicMeshDict:
solver
{
    type    symplectic;
}
See also
Foam::sixDoFSolvers::CrankNicolson Foam::sixDoFSolvers::Newmark
Source files
symplectic.H
symplectic.C
Definition at line 74 of file symplectic.H.
Constructor & Destructor Documentation
symplectic()
symplectic (const dictionary & dict, sixDoFRigidBodyMotion & body)
Construct from a dictionary and the body.
Definition at line 44 of file symplectic.C.
~symplectic()
~symplectic () virtual
Destructor.
Definition at line 55 of file symplectic.C.
References symplectic::solve().
Member Function Documentation
TypeName()
TypeName ("symplectic")
Runtime type information.
solve()
void solve (bool firstIter, const vector & fGlobal, const vector & tauGlobal, scalar deltaT, scalar deltaT0) virtual
Drag coefficient.
Implements sixDoFSolver.
Definition at line 62 of file symplectic.C.
References Foam::constant::atomic::a0, Foam::exit(), Foam::FatalError, FatalErrorInFunction, Tuple2< Type1, Type2 >::first(), Foam::constant::mathematical::pi(), and Tuple2< Type1, Type2 >::second().
Referenced by symplectic::~symplectic().
The documentation for this class was generated from the following files:
src/sixDoFRigidBodyMotion/sixDoFSolvers/symplectic/symplectic.H
src/sixDoFRigidBodyMotion/sixDoFSolvers/symplectic/symplectic.C