OpenFOAM: STLpoint Class Reference
STLpoint Class Reference
A vertex point representation for STL files.
Public Member Functions
STLpoint ()
Construct null.
STLpoint (float x, float y, float z)
Construct from components.
STLpoint (const point &pt)
Construct from point.
STLpoint (Istream &is)
Construct from istream.
operator point () const
Conversion to point.
Public Member Functions inherited from Vector< float >
Vector ()
Construct null.
Vector (const Foam::zero)
Construct initialized to zero.
Vector (const VectorSpace< Vector< Cmpt2 >, Cmpt2, 3 > &)
Construct given VectorSpace of the same rank.
Vector (const float &vx, const float &vy, const float &vz)
Construct given three components.
Vector (Istream &)
Construct from Istream.
const float & x () const
float & x ()
const float & y () const
float & y ()
const float & z () const
float & z ()
const Vector< float > & centre (const Foam::List< Vector< float >> &) const
Return *this (used for point which is a typedef to Vector<scalar>.
Public Member Functions inherited from VectorSpace< Vector< float >, float, 3 >
VectorSpace ()
Construct null.
VectorSpace (const Foam::zero)
Construct initialized to zero.
VectorSpace (Istream &)
Construct from Istream.
VectorSpace (const VectorSpace< Vector< float >, float, Ncmpts > &)
Construct as copy.
VectorSpace (const VectorSpace< Form2, Cmpt2, Ncmpts > &)
Construct as copy of a VectorSpace with the same size.
const float & component (const direction) const
float & component (const direction)
void component (float &, const direction) const
void replace (const direction, const float &)
const ConstBlock< SubVector, BStart > block () const
const VectorSpace< Vector< float >, float, Ncmpts >::template ConstBlock< SubVector, BStart > block () const
const float & operator[] (const direction) const
float & operator[] (const direction)
void operator= (const VectorSpace< Vector< float >, float, Ncmpts > &)
void operator= (const Foam::zero)
void operator+= (const VectorSpace< Vector< float >, float, Ncmpts > &)
void operator-= (const VectorSpace< Vector< float >, float, Ncmpts > &)
void operator*= (const scalar)
void operator/= (const scalar)
Additional Inherited Members
Public Types inherited from Vector< float >
enum components
Component labeling enumeration.
typedef Vector< label > labelType
Equivalent type of labels used for valid component indexing.
Public Types inherited from VectorSpace< Vector< float >, float, 3 >
typedef VectorSpace< Vector< float >, float, Ncmpts > vsType
VectorSpace type.
typedef float cmptType
Component type.
Static Public Member Functions inherited from VectorSpace< Vector< float >, float, 3 >
static direction size ()
Return the number of elements in the VectorSpace = Ncmpts.
static Vector< float > uniform (const float &s)
Return a VectorSpace with all elements = s.
Public Attributes inherited from VectorSpace< Vector< float >, float, 3 >
float v_ [Ncmpts]
The components of this vector space.
Static Public Attributes inherited from Vector< float >
static const direction rank
Rank of Vector is 1.
Static Public Attributes inherited from VectorSpace< Vector< float >, float, 3 >
static const direction dim
Dimensionality of space.
static const direction nComponents
Number of components in this vector space.
static const direction mRows
static const direction nCols
static const char *const typeName
static const char *const componentNames []
static const Vector< float > zero
static const Vector< float > one
static const Vector< float > max
static const Vector< float > min
static const Vector< float > rootMax
static const Vector< float > rootMin
Detailed Description
A vertex point representation for STL files.
Source files
STLpoint.H
Definition at line 48 of file STLpoint.H.
Constructor & Destructor Documentation
STLpoint() [1/4]
STLpoint () inline
Construct null.
Definition at line 58 of file STLpoint.H.
STLpoint() [2/4]
STLpoint (float x, float y, float z) inline
Construct from components.
Definition at line 62 of file STLpoint.H.
STLpoint() [3/4]
STLpoint (const point & pt) inline
Construct from point.
Definition at line 68 of file STLpoint.H.
STLpoint() [4/4]
STLpoint (Istream & is) inline
Construct from istream.
Definition at line 74 of file STLpoint.H.
Member Function Documentation
operator point()
operator point () const inline
Conversion to point.
Definition at line 83 of file STLpoint.H.
References Vector< float >::x(), Vector< float >::y(), and Vector< float >::z().
The documentation for this class was generated from the following file:
src/surfMesh/surfaceFormats/stl/STLpoint.H