OpenFOAM: AC3DsurfaceFormatCore Class Reference
AC3DsurfaceFormatCore Class Reference
Internal class used by the AC3DsurfaceFormat.
Static Protected Member Functions
template<class Type >
static Type parse (const string &)
Read a type via IStringStream.
static bool readCmd (IFstream &, string &cmd, string &args)
Read cmd, args from IFstream.
static bool cueTo (IFstream &, const string &cmd, string &args)
Cue up to cmd, reading args.
static string cueToOrDie (IFstream &, const string &cmd, const string &errorMsg=string::null)
Cue up to cmd, reading args or exit with a FatalError.
static void writeHeader (Ostream &, const UList< surfZone > &)
Write header with materials.
Detailed Description
Internal class used by the AC3DsurfaceFormat.
Source files
AC3DsurfaceFormatCore.H
AC3DsurfaceFormatCore.C
Definition at line 53 of file AC3DsurfaceFormatCore.H.
Member Function Documentation
parse()
Type parse (const string & s) static protected
Read a type via IStringStream.
Definition at line 32 of file AC3DsurfaceFormatCoreTemplates.C.
readCmd()
bool readCmd (IFstream & is, string & cmd, string & args) static protected
Read cmd, args from IFstream.
Definition at line 34 of file AC3DsurfaceFormatCore.C.
References AC3DsurfaceFormatCore::cueTo(), ISstream::getLine(), and IOstream::good().
cueTo()
bool cueTo (IFstream & is, const string & cmd, string & args) static protected
Cue up to cmd, reading args.
Definition at line 62 of file AC3DsurfaceFormatCore.C.
References AC3DsurfaceFormatCore::cueToOrDie(), ISstream::getLine(), and IOstream::good().
Referenced by AC3DsurfaceFormatCore::readCmd().
cueToOrDie()
Foam::string cueToOrDie (IFstream & is, const string & cmd, const string & errorMsg = string::null) static protected
Cue up to cmd, reading args or exit with a FatalError.
returns the command args
Definition at line 91 of file AC3DsurfaceFormatCore.C.
References args, Foam::exit(), Foam::FatalError, FatalErrorInFunction, and AC3DsurfaceFormatCore::writeHeader().
Referenced by AC3DsurfaceFormatCore::cueTo().
writeHeader()
void writeHeader (Ostream & os, const UList< surfZone > & zoneLst) static protected
Write header with materials.
Definition at line 111 of file AC3DsurfaceFormatCore.C.
References Foam::endl(), forAll, Foam::nl, and UList< T >::size().
Referenced by AC3DsurfaceFormatCore::cueToOrDie().
The documentation for this class was generated from the following files:
src/surfMesh/surfaceFormats/ac3d/AC3DsurfaceFormatCore.H
src/surfMesh/surfaceFormats/ac3d/AC3DsurfaceFormatCore.C
src/surfMesh/surfaceFormats/ac3d/AC3DsurfaceFormatCoreTemplates.C