OpenFOAM: sixDoFRigidBodyMotion Class Reference
sixDoFRigidBodyMotion Class Reference
Six degree of freedom motion for a rigid body.
Public Member Functions
sixDoFRigidBodyMotion ()
Construct null.
sixDoFRigidBodyMotion (const dictionary &dict, const dictionary &stateDict)
Construct from constant and state dictionaries.
sixDoFRigidBodyMotion (const sixDoFRigidBodyMotion &)
Construct as copy.
~sixDoFRigidBodyMotion ()
Destructor.
scalar mass () const
Return the mass.
const diagTensor & momentOfInertia () const
Return the inertia tensor.
const sixDoFRigidBodyMotionState & state () const
Return the motion state.
const point & centreOfRotation () const
Return the current centre of rotation.
const point & initialCentreOfMass () const
Return the initial centre of mass.
point centreOfMass () const
Return the current centre of mass.
const tensor & orientation () const
Return the orientation tensor, Q.
vector omega () const
Return the angular velocity in the global frame.
const vector & v () const
Return the current velocity.
vector momentArm () const
bool report () const
Return the report Switch.
void newTime ()
Store the motion state at the beginning of the time-step.
point & centreOfRotation ()
Return non-const access to the centre of rotation.
void addRestraints (const dictionary &dict)
Add restraints to the motion, public to allow external.
void addConstraints (const dictionary &dict)
Add restraints to the motion, public to allow external.
void update (bool firstIter, const vector &fGlobal, const vector &tauGlobal, scalar deltaT, scalar deltaT0)
Symplectic integration of velocities, orientation and position.
void status () const
Report the status of the motion.
point velocity (const point &pt) const
Return the velocity of a position.
point transform (const point &initialPoints) const
Transform the given initial state point by the current motion.
tmp< pointField > transform (const pointField &initialPoints) const
Transform the given initial state pointField by the current.
tmp< pointField > transform (const pointField &initialPoints, const scalarField &scale) const
Transform the given initial state pointField by the current.
void write (Ostream &) const
Write.
bool read (const dictionary &dict)
Read coefficients dictionary and update system parameters,.
Friends
class sixDoFSolver
Detailed Description
Six degree of freedom motion for a rigid body.
Angular momentum stored in body fixed reference frame. Reference orientation of the body (where Q = I) must align with the cartesian axes such that the Inertia tensor is in principle component form. Can add restraints (e.g. a spring) and constraints (e.g. motion may only be on a plane).
The time-integrator for the motion is run-time selectable with options for symplectic (explicit), Crank-Nicolson and Newmark schemes.
Source files
sixDoFRigidBodyMotion.H
sixDoFRigidBodyMotionI.H
sixDoFRigidBodyMotion.C
sixDoFRigidBodyMotionIO.C
Definition at line 66 of file sixDoFRigidBodyMotion.H.
Constructor & Destructor Documentation
sixDoFRigidBodyMotion() [1/3]
sixDoFRigidBodyMotion ()
Construct null.
Definition at line 73 of file sixDoFRigidBodyMotion.C.
Referenced by sixDoFRigidBodyMotion::sixDoFRigidBodyMotion().
sixDoFRigidBodyMotion() [2/3]
sixDoFRigidBodyMotion (const dictionary & dict, const dictionary & stateDict)
Construct from constant and state dictionaries.
Definition at line 94 of file sixDoFRigidBodyMotion.C.
References sixDoFRigidBodyMotion::addConstraints(), sixDoFRigidBodyMotion::addRestraints(), sixDoFRigidBodyMotionState::centreOfRotation(), Foam::diag(), dictionary::found(), Foam::I, Foam::magSqr(), R, sixDoFRigidBodyMotion::sixDoFRigidBodyMotion(), and Foam::sqr().
sixDoFRigidBodyMotion() [3/3]
sixDoFRigidBodyMotion (const sixDoFRigidBodyMotion & sDoFRBM)
Construct as copy.
Definition at line 156 of file sixDoFRigidBodyMotion.C.
~sixDoFRigidBodyMotion()
~sixDoFRigidBodyMotion ()
Destructor.
Definition at line 179 of file sixDoFRigidBodyMotion.C.
References sixDoFRigidBodyMotion::addRestraints().
Member Function Documentation
mass()
Foam::scalar mass () const inline
Return the mass.
Definition at line 208 of file sixDoFRigidBodyMotionI.H.
Referenced by uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs(), and sixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs().
momentOfInertia()
const Foam::diagTensor & momentOfInertia () const inline
Return the inertia tensor.
Definition at line 215 of file sixDoFRigidBodyMotionI.H.
state()
const Foam::sixDoFRigidBodyMotionState & state () const inline
Return the motion state.
Definition at line 222 of file sixDoFRigidBodyMotionI.H.
centreOfRotation() [1/2]
const Foam::point & centreOfRotation () const inline
Return the current centre of rotation.
Definition at line 228 of file sixDoFRigidBodyMotionI.H.
References sixDoFRigidBodyMotionState::centreOfRotation().
Referenced by sphericalAngularSpring::restrain(), linearAxialAngularSpring::restrain(), tabulatedAxialAngularSpring::restrain(), sixDoFRigidBodyMotion::status(), sixDoFRigidBodyMotion::transform(), sixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs(), and sixDoFRigidBodyMotion::velocity().
initialCentreOfMass()
const Foam::point & initialCentreOfMass () const inline
Return the initial centre of mass.
Definition at line 235 of file sixDoFRigidBodyMotionI.H.
centreOfMass()
Foam::point centreOfMass () const inline
Return the current centre of mass.
Definition at line 241 of file sixDoFRigidBodyMotionI.H.
References sixDoFRigidBodyMotion::transform().
Referenced by sixDoFRigidBodyMotion::momentArm(), and sixDoFRigidBodyMotion::status().
orientation()
const Foam::tensor & orientation () const inline
Return the orientation tensor, Q.
globalVector = Q & bodyLocalVector bodyLocalVector = Q.T() & globalVector
Definition at line 254 of file sixDoFRigidBodyMotionI.H.
Referenced by sphericalAngularSpring::restrain(), linearAxialAngularSpring::restrain(), tabulatedAxialAngularSpring::restrain(), and sixDoFRigidBodyMotion::status().
omega()
Foam::vector omega () const inline
Return the angular velocity in the global frame.
Definition at line 260 of file sixDoFRigidBodyMotionI.H.
References Foam::inv(), and Foam::constant::mathematical::pi().
Referenced by sphericalAngularDamper::restrain(), sphericalAngularSpring::restrain(), linearAxialAngularSpring::restrain(), tabulatedAxialAngularSpring::restrain(), sixDoFRigidBodyMotion::status(), and sixDoFRigidBodyMotion::velocity().
v()
const Foam::vector & v () const inline
Return the current velocity.
Definition at line 140 of file sixDoFRigidBodyMotionI.H.
References sixDoFRigidBodyMotionState::a(), sixDoFRigidBodyMotionState::pi(), sixDoFRigidBodyMotionState::Q(), sixDoFRigidBodyMotionState::tau(), and sixDoFRigidBodyMotionState::v().
momentArm()
Foam::vector momentArm () const inline
Definition at line 247 of file sixDoFRigidBodyMotionI.H.
References sixDoFRigidBodyMotion::centreOfMass(), and sixDoFRigidBodyMotionState::centreOfRotation().
Referenced by sixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs().
report()
bool report () const inline
Return the report Switch.
Definition at line 266 of file sixDoFRigidBodyMotionI.H.
Referenced by sphericalAngularDamper::restrain(), linearDamper::restrain(), sphericalAngularSpring::restrain(), linearAxialAngularSpring::restrain(), linearSpring::restrain(), and tabulatedAxialAngularSpring::restrain().
newTime()
void newTime () inline
Store the motion state at the beginning of the time-step.
Definition at line 272 of file sixDoFRigidBodyMotionI.H.
Referenced by uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs(), and sixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs().
centreOfRotation() [2/2]
Foam::point & centreOfRotation () inline
Return non-const access to the centre of rotation.
Definition at line 278 of file sixDoFRigidBodyMotionI.H.
References sixDoFRigidBodyMotionState::centreOfRotation(), and sixDoFRigidBodyMotion::velocity().
addRestraints()
void addRestraints (const dictionary & dict)
Add restraints to the motion, public to allow external.
addition of restraints after construction
Definition at line 186 of file sixDoFRigidBodyMotion.C.
References sixDoFRigidBodyMotion::addConstraints(), dict, forAllConstIter(), dictionary::found(), sixDoFRigidBodyMotionRestraint::New(), and dictionary::subDict().
Referenced by sixDoFRigidBodyMotion::read(), sixDoFRigidBodyMotion::sixDoFRigidBodyMotion(), and sixDoFRigidBodyMotion::~sixDoFRigidBodyMotion().
addConstraints()
void addConstraints (const dictionary & dict)
Add restraints to the motion, public to allow external.
addition of restraints after construction
Definition at line 220 of file sixDoFRigidBodyMotion.C.
References pointConstraint::constraintTransformation(), dict, Foam::endl(), forAllConstIter(), dictionary::found(), Foam::Info, sixDoFRigidBodyMotionConstraint::New(), Foam::nl, dictionary::subDict(), Tensor< Cmpt >::T(), and sixDoFRigidBodyMotion::update().
Referenced by sixDoFRigidBodyMotion::addRestraints(), sixDoFRigidBodyMotion::read(), and sixDoFRigidBodyMotion::sixDoFRigidBodyMotion().
update()
void update (bool firstIter, const vector & fGlobal, const vector & tauGlobal, scalar deltaT, scalar deltaT0)
Symplectic integration of velocities, orientation and position.
Changes to Crank-Nicolson integration for subsequent iterations.
Definition at line 298 of file sixDoFRigidBodyMotion.C.
References UPstream::master(), Pstream::scatter(), and sixDoFRigidBodyMotion::status().
Referenced by sixDoFRigidBodyMotion::addConstraints(), uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs(), and sixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs().
status()
void status () const
Report the status of the motion.
Definition at line 320 of file sixDoFRigidBodyMotion.C.
References sixDoFRigidBodyMotion::centreOfMass(), sixDoFRigidBodyMotion::centreOfRotation(), Foam::endl(), Foam::Info, Foam::nl, sixDoFRigidBodyMotion::omega(), sixDoFRigidBodyMotion::orientation(), and sixDoFRigidBodyMotion::transform().
Referenced by sixDoFRigidBodyMotion::update().
velocity()
Foam::point velocity (const point & pt) const inline
Return the velocity of a position.
Definition at line 285 of file sixDoFRigidBodyMotionI.H.
References sixDoFRigidBodyMotion::centreOfRotation(), sixDoFRigidBodyMotion::omega(), and sixDoFRigidBodyMotion::transform().
Referenced by sixDoFRigidBodyMotion::centreOfRotation(), and linearSpring::restrain().
transform() [1/3]
Foam::point transform (const point & initialPoints) const inline
Transform the given initial state point by the current motion.
state
Definition at line 294 of file sixDoFRigidBodyMotionI.H.
References sixDoFRigidBodyMotion::centreOfRotation(), and Tensor< Cmpt >::T().
Referenced by sixDoFRigidBodyMotion::centreOfMass(), linearSpring::restrain(), sixDoFRigidBodyMotion::status(), sixDoFRigidBodyMotion::transform(), uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs(), sixDoFRigidBodyDisplacementPointPatchVectorField::updateCoeffs(), and sixDoFRigidBodyMotion::velocity().
transform() [2/3]
Foam::tmp< Foam::pointField > transform (const pointField & initialPoints) const
Transform the given initial state pointField by the current.
motion state
Definition at line 333 of file sixDoFRigidBodyMotion.C.
References sixDoFRigidBodyMotion::centreOfRotation(), Tensor< Cmpt >::T(), and sixDoFRigidBodyMotion::transform().
transform() [3/3]
Foam::tmp< Foam::pointField > transform (const pointField & initialPoints, const scalarField & scale) const
Transform the given initial state pointField by the current.
motion state scaled by the given scale
Definition at line 346 of file sixDoFRigidBodyMotion.C.
References sixDoFRigidBodyMotion::centreOfRotation(), forAll, septernion::I, septernion::invTransformPoint(), points, tmp< T >::ref(), s(), Foam::slerp(), Foam::T(), and sixDoFRigidBodyMotion::transform().
write()
void write (Ostream & os) const
Write.
Definition at line 49 of file sixDoFRigidBodyMotionIO.C.
References token::BEGIN_BLOCK, Foam::decrIndent(), token::END_BLOCK, token::END_STATEMENT, Foam::endl(), forAll, Foam::incrIndent(), Foam::indent(), Foam::nl, sixDoFRigidBodyMotionState::write(), and Ostream::writeKeyword().
Referenced by uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField::write(), and sixDoFRigidBodyDisplacementPointPatchVectorField::write().
read()
bool read (const dictionary & dict)
Read coefficients dictionary and update system parameters,.
constraints and restraints but not the current state
Definition at line 31 of file sixDoFRigidBodyMotionIO.C.
References sixDoFRigidBodyMotion::addConstraints(), sixDoFRigidBodyMotion::addRestraints(), dictionary::lookup(), and dictionary::lookupOrDefault().
Friends And Related Function Documentation
sixDoFSolver
friend class sixDoFSolver friend
Definition at line 68 of file sixDoFRigidBodyMotion.H.
The documentation for this class was generated from the following files:
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion.H
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion.C
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/sixDoFRigidBodyMotionI.H
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/sixDoFRigidBodyMotionIO.C