OpenFOAM: barotropicCompressibilityModel Class Reference
barotropicCompressibilityModel Class Reference abstract
Abstract class for barotropic compressibility models.
Public Member Functions
TypeName ("barotropicCompressibilityModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, barotropicCompressibilityModel, dictionary,(const dictionary &compressibilityProperties, const volScalarField &gamma, const word &psiName),(compressibilityProperties, gamma, psiName))
barotropicCompressibilityModel (const dictionary &compressibilityProperties, const volScalarField &gamma, const word &psiName="psi")
Construct from components.
virtual ~barotropicCompressibilityModel ()
Destructor.
const dictionary & compressibilityProperties () const
Return the phase transport properties dictionary.
const volScalarField & psi () const
Return the compressibility.
virtual void correct ()=0
Correct the compressibility.
virtual bool read (const dictionary &compressibilityProperties)=0
Read compressibilityProperties dictionary.
Static Public Member Functions
static autoPtr< barotropicCompressibilityModel > New (const dictionary &compressibilityProperties, const volScalarField &gamma, const word &psiName="psi")
Return a reference to the selected compressibility model.
Protected Member Functions
barotropicCompressibilityModel (const barotropicCompressibilityModel &)
Disallow copy construct.
void operator= (const barotropicCompressibilityModel &)
Disallow default bitwise assignment.
Protected Attributes
dictionary compressibilityProperties_
volScalarField psi_
const volScalarField & gamma_
Detailed Description
Abstract class for barotropic compressibility models.
Source files
barotropicCompressibilityModel.H
barotropicCompressibilityModel.C
newbarotropicCompressibilityModel.C
Definition at line 61 of file barotropicCompressibilityModel.H.
Constructor & Destructor Documentation
barotropicCompressibilityModel() [1/2]
barotropicCompressibilityModel (const barotropicCompressibilityModel &) protected
Disallow copy construct.
barotropicCompressibilityModel() [2/2]
barotropicCompressibilityModel (const dictionary & compressibilityProperties, const volScalarField & gamma, const word & psiName = "psi")
Construct from components.
Definition at line 42 of file barotropicCompressibilityModel.C.
References barotropicCompressibilityModel::read().
~barotropicCompressibilityModel()
virtual ~barotropicCompressibilityModel () inline virtual
Destructor.
Definition at line 128 of file barotropicCompressibilityModel.H.
Member Function Documentation
operator=()
void operator= (const barotropicCompressibilityModel &) protected
Disallow default bitwise assignment.
TypeName()
TypeName ("barotropicCompressibilityModel")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , barotropicCompressibilityModel , dictionary , (const dictionary &compressibilityProperties, const volScalarField &gamma, const word &psiName) , (compressibilityProperties, gamma, psiName))
New()
Foam::autoPtr< Foam::barotropicCompressibilityModel > New (const dictionary & compressibilityProperties, const volScalarField & gamma, const word & psiName = "psi") static
Return a reference to the selected compressibility model.
Definition at line 32 of file barotropicCompressibilityModelNew.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::Info, dictionary::lookup(), and Foam::nl.
compressibilityProperties()
const dictionary& compressibilityProperties () const inline
Return the phase transport properties dictionary.
Definition at line 135 of file barotropicCompressibilityModel.H.
References barotropicCompressibilityModel::compressibilityProperties_.
psi()
const volScalarField& psi () const inline
Return the compressibility.
Definition at line 141 of file barotropicCompressibilityModel.H.
References barotropicCompressibilityModel::correct(), barotropicCompressibilityModel::psi_, and barotropicCompressibilityModel::read().
correct()
virtual void correct () pure virtual
Correct the compressibility.
Implemented in Chung, Wallis, and linear.
Referenced by barotropicCompressibilityModel::psi().
read()
bool read (const dictionary & compressibilityProperties) pure virtual
Read compressibilityProperties dictionary.
Implemented in Chung, Wallis, and linear.
Definition at line 67 of file barotropicCompressibilityModel.C.
Referenced by barotropicCompressibilityModel::barotropicCompressibilityModel(), barotropicCompressibilityModel::psi(), linear::read(), Wallis::read(), and Chung::read().
Member Data Documentation
compressibilityProperties_
dictionary compressibilityProperties_ protected
Definition at line 68 of file barotropicCompressibilityModel.H.
Referenced by barotropicCompressibilityModel::compressibilityProperties().
psi_
volScalarField psi_ protected
Definition at line 70 of file barotropicCompressibilityModel.H.
Referenced by barotropicCompressibilityModel::psi().
gamma_
const volScalarField& gamma_ protected
Definition at line 71 of file barotropicCompressibilityModel.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/barotropicCompressibilityModel/barotropicCompressibilityModel/barotropicCompressibilityModel.H
src/thermophysicalModels/barotropicCompressibilityModel/barotropicCompressibilityModel/barotropicCompressibilityModel.C
src/thermophysicalModels/barotropicCompressibilityModel/barotropicCompressibilityModel/barotropicCompressibilityModelNew.C