OpenFOAM: STLsurfaceFormatCore Class Reference
STLsurfaceFormatCore Class Reference
Internal class used by the STLsurfaceFormat.
Public Member Functions
STLsurfaceFormatCore (const fileName &)
Read from file, filling in the information.
~STLsurfaceFormatCore ()
Destructor.
bool sorted () const
File read was already sorted.
void clear ()
Flush all values.
pointField & points ()
Return full access to the points.
List< label > & zoneIds ()
Return full access to the zoneIds.
List< word > & names ()
The list of solid names in the order of their first appearance.
List< label > & sizes ()
The list of solid sizes in the order of their first appearance.
Static Public Member Functions
static void writeHeaderBINARY (ostream &, unsigned int)
Write "STL binary file" and number of triangles to stream.
Static Public Attributes
static const unsigned int headerSize = 80
The number of bytes in the STL binary header.
Detailed Description
Internal class used by the STLsurfaceFormat.
Source files
STLsurfaceFormatCore.H
STLsurfaceFormatCore.C
STLsurfaceFormatASCII.L
Definition at line 54 of file STLsurfaceFormatCore.H.
Constructor & Destructor Documentation
STLsurfaceFormatCore()
STLsurfaceFormatCore (const fileName & filename)
Read from file, filling in the information.
Definition at line 210 of file STLsurfaceFormatCore.C.
References IOstream::BINARY, and Foam::fileSize().
~STLsurfaceFormatCore()
~STLsurfaceFormatCore ()
Destructor.
Definition at line 244 of file STLsurfaceFormatCore.C.
References STLsurfaceFormatCore::writeHeaderBINARY().
Member Function Documentation
writeHeaderBINARY()
void writeHeaderBINARY (ostream & os, unsigned int nTris) static
Write "STL binary file" and number of triangles to stream.
Definition at line 251 of file STLsurfaceFormatCore.C.
References STLsurfaceFormatCore::headerSize.
Referenced by STLsurfaceFormatCore::~STLsurfaceFormatCore().
sorted()
bool sorted () const inline
File read was already sorted.
Definition at line 118 of file STLsurfaceFormatCore.H.
Referenced by STLsurfaceFormat< Face >::read().
clear()
void clear () inline
Flush all values.
Definition at line 124 of file STLsurfaceFormatCore.H.
References List< T >::clear().
points()
pointField& points () inline
Return full access to the points.
Definition at line 134 of file STLsurfaceFormatCore.H.
Referenced by STLsurfaceFormat< Face >::read().
zoneIds()
List<label>& zoneIds () inline
Return full access to the zoneIds.
Definition at line 140 of file STLsurfaceFormatCore.H.
Referenced by STLsurfaceFormat< Face >::read().
names()
List<word>& names () inline
The list of solid names in the order of their first appearance.
Definition at line 146 of file STLsurfaceFormatCore.H.
Referenced by STLsurfaceFormat< Face >::read().
sizes()
List<label>& sizes () inline
The list of solid sizes in the order of their first appearance.
Definition at line 152 of file STLsurfaceFormatCore.H.
Referenced by STLsurfaceFormat< Face >::read().
Member Data Documentation
headerSize
const unsigned int headerSize = 80 static
The number of bytes in the STL binary header.
Definition at line 96 of file STLsurfaceFormatCore.H.
Referenced by STLsurfaceFormatCore::writeHeaderBINARY().
The documentation for this class was generated from the following files:
src/surfMesh/surfaceFormats/stl/STLsurfaceFormatCore.H
src/surfMesh/surfaceFormats/stl/STLsurfaceFormatCore.C