OpenFOAM: VTKsurfaceFormatCore Class Reference
VTKsurfaceFormatCore Class Reference
Internal class used by the VTKsurfaceFormat.
Static Protected Member Functions
static void writeHeader (Ostream &, const pointField &)
Write header information with points.
static void writeTail (Ostream &, const UList< surfZone > &)
Write trailing information with zone information.
static void writeTail (Ostream &, const labelUList &zoneIds)
Write trailing information with zone Ids.
Detailed Description
Internal class used by the VTKsurfaceFormat.
Source files
VTKsurfaceFormatCore.H
VTKsurfaceFormatCore.C
Definition at line 52 of file VTKsurfaceFormatCore.H.
Member Function Documentation
writeHeader()
void writeHeader (Ostream & os, const pointField & pointLst) static protected
Write header information with points.
Definition at line 32 of file VTKsurfaceFormatCore.C.
References forAll, Foam::nl, List< T >::size(), VTKsurfaceFormatCore::writeTail(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
writeTail() [1/2]
void writeTail (Ostream & os, const UList< surfZone > & zoneLst) static protected
Write trailing information with zone information.
Definition at line 56 of file VTKsurfaceFormatCore.C.
References forAll, Foam::nl, and UList< T >::size().
Referenced by VTKsurfaceFormatCore::writeHeader().
writeTail() [2/2]
void writeTail (Ostream & os, const labelUList & zoneIds) static protected
Write trailing information with zone Ids.
Definition at line 97 of file VTKsurfaceFormatCore.C.
References forAll, Foam::nl, and UList< T >::size().
The documentation for this class was generated from the following files:
src/surfMesh/surfaceFormats/vtk/VTKsurfaceFormatCore.H
src/surfMesh/surfaceFormats/vtk/VTKsurfaceFormatCore.C