OpenFOAM: surfMesh Class Reference
surfMesh Class Reference
A surface mesh consisting of general polygon faces.
Public Types
enum readUpdateState { UNCHANGED, POINTS_MOVED, TOPO_CHANGE, TOPO_PATCH_CHANGE }
Enumeration defining the state of the mesh after a read update.
typedef surfMesh Mesh
typedef bool BoundaryMesh
Placeholder only, but do not remove - it is needed for GeoMesh.
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Public Types inherited from HashTable< regIOobject *>
typedef regIOobject * value_type
Type of values the HashTable contains.
typedef regIOobject * & reference
Type that can be used for storing into HashTable::value_type.
typedef const regIOobject * & const_reference
Type that can be used for storing into constant.
typedef label size_type
The type that can represent the size of a HashTable.
Public Types inherited from PrimitivePatch< face, ::Foam::UList, ::Foam::SubField< point >, point >
enum surfaceTopo
Enumeration defining the surface type. Used in check routines.
typedef face FaceType
typedef ::Foam::UList< face > FaceListType
typedef ::Foam::SubField< point > PointFieldType
Public Types inherited from UList< face >
typedef face value_type
Type of values the UList contains.
typedef face & reference
Type that can be used for storing into.
typedef const face & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef face * iterator
Random access iterator for traversing UList.
typedef const face * const_iterator
Random access iterator for traversing UList.
typedef face * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const face * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Public Member Functions
TypeName ("surfMesh")
Runtime type information.
surfMesh (const IOobject &, const word &surfName="")
Construct from IOobject, with alternative surface name.
surfMesh (const IOobject &, const Xfer< pointField > &, const Xfer< faceList > &, const word &surfName="")
Construct by transferring components (points, faces) without zones.
surfMesh (const IOobject &, const Xfer< MeshedSurface< face >> &surf, const word &surfName="")
Construct copy/move from MeshedSurface.
virtual ~surfMesh ()
Destructor.
fileName meshDir () const
Return the local mesh directory (dbDir()/meshSubDir)
const fileName & pointsInstance () const
Return the current instance directory for points.
const fileName & facesInstance () const
Return the current instance directory for faces.
void setInstance (const fileName &)
Set the instance for mesh files.
virtual label nPoints () const
Return the number of raw points.
virtual label nFaces () const
Return the number of raw faces.
virtual label size () const
Return number of faces.
virtual const pointField & points () const
Return points.
virtual const faceList & faces () const
Return faces.
virtual const surfZoneList & surfZones () const
Return surface zones.
void checkZones ()
Check the surface zone definitions.
void addZones (const List< surfZone > &, const bool validate=true)
Add surface zones.
virtual readUpdateState readUpdate ()
Update the mesh based on the mesh files saved in.
void removeZones ()
Update the mesh corresponding to given map.
void resetPrimitives (const Xfer< pointField > &points, const Xfer< faceList > &faces, const Xfer< surfZoneList > &zones, const bool validate=true)
Reset mesh primitive data.
void transfer (MeshedSurface< face > &)
Transfer the contents of the argument and annul the argument.
void write (const fileName &)
Write to file.
Xfer< MeshedSurface< face > > xfer ()
Transfer contents to the Xfer container as a MeshedSurface.
void clearGeom ()
Clear geometry.
void clearAddressing ()
Clear addressing.
void clearOut ()
Clear all geometry and addressing unnecessary for CFD.
void clearPrimitives ()
Clear primitive data (points, faces and cells)
void removeFiles (const fileName &instanceDir) const
Remove all files from mesh instance.
void removeFiles () const
Remove all files from mesh instance()
Public Member Functions inherited from surfaceRegistry
TypeName ("surfaceRegistry")
Runtime type information.
surfaceRegistry (const objectRegistry &, const word &surfName="")
Construct for the given objectRegistry and named surface.
virtual ~surfaceRegistry ()
Destructor.
Public Member Functions inherited from objectRegistry
TypeName ("objectRegistry")
Declare type name for this IOobject.
objectRegistry (const Time &db, const label nIoObjects=128)
Construct the time objectRegistry given an initial estimate.
objectRegistry (const IOobject &io, const label nIoObjects=128)
Construct a sub-registry given an IObject to describe the registry.
virtual ~objectRegistry ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & parent () const
Return the parent objectRegistry.
virtual const fileName & dbDir () const
Local directory path of this objectRegistry relative to the time.
wordList names () const
Return the list of names of the IOobjects.
wordList sortedNames () const
Return the sorted list of names of the IOobjects.
wordList names (const word &className) const
Return the list of names of IOobjects of given class name.
wordList sortedNames (const word &className) const
Return the sorted list of names of IOobjects of given class name.
template<class Type >
wordList names () const
Return the list of names of the IOobjects of given type.
template<class Type >
wordList names (const wordRe &name) const
Return the list of objects whose name matches the input regExp.
template<class Type >
wordList names (const wordReList &name) const
Return the list of objects whose name matches the input regExp.
const objectRegistry & subRegistry (const word &name, const bool forceCreate=false) const
Lookup and return a const sub-objectRegistry. Optionally create.
template<class Type >
HashTable< const Type * > lookupClass (const bool strict=false) const
Lookup and return all objects of the given Type.
template<class Type >
HashTable< Type * > lookupClass (const bool strict=false)
Lookup and return all objects of the given Type.
template<class Type >
bool foundObject (const word &name) const
Is the named Type found?
template<class Type >
const Type & lookupObject (const word &name) const
Lookup and return the object of the given Type.
label getEvent () const
Return new event number.
virtual void rename (const word &newName)
Rename.
bool checkIn (regIOobject &) const
Add an regIOobject to registry.
bool checkOut (regIOobject &) const
Remove an regIOobject from registry.
virtual bool modified () const
Return true if any of the object's files have been modified.
void readModifiedObjects ()
Read the objects that have been modified.
virtual bool readIfModified ()
Read object if modified.
virtual bool writeData (Ostream &) const
writeData function required by regIOobject but not used
virtual bool writeObject (IOstream::streamFormat fmt, IOstream::versionNumber ver, IOstream::compressionType cmp) const
Write the objects.
template<class Type >
Foam::wordList names () const
template<class Type >
Foam::wordList names (const wordRe &name) const
template<class Type >
Foam::wordList names (const wordReList &patterns) const
template<class Type >
Foam::HashTable< const Type * > lookupClass (const bool strict) const
template<class Type >
Foam::HashTable< Type * > lookupClass (const bool strict)
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, transferring registry registration to copy.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Construct as copy with new name, transfering registry registration.
regIOobject (const IOobject &, const regIOobject &)
Construct as copy with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool readData (Istream &)
Virtual readData function.
virtual bool read ()
Read object.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Public Member Functions inherited from HashTable< regIOobject *>
bool set (const word &, const regIOobject * &newElmt)
Assign a new hashedEntry, overwriting existing entries.
HashTable (const label size=128)
Construct given initial table size.
HashTable (Istream &, const label size=128)
Construct from Istream.
HashTable (const HashTable< regIOobject *, word, string::hash > &)
Construct as copy.
HashTable (const Xfer< HashTable< regIOobject *, word, string::hash >> &)
Construct by transferring the parameter contents.
HashTable (std::initializer_list< Tuple2< word, regIOobject * >>)
Construct from an initializer list.
~HashTable ()
Destructor.
label capacity () const
The size of the underlying table.
label size () const
Return number of elements in table.
bool empty () const
Return true if the hash table is empty.
bool found (const word &) const
Return true if hashedEntry is found in table.
iterator find (const word &)
Find and return an iterator set at the hashedEntry.
const_iterator find (const word &) const
Find and return an const_iterator set at the hashedEntry.
List< word > toc () const
Return the table of contents.
List< word > sortedToc () const
Return the table of contents as a sorted list.
Ostream & printInfo (Ostream &) const
Print information.
bool insert (const word &, const regIOobject * &newElmt)
Insert a new hashedEntry.
bool erase (const iterator &)
Erase a hashedEntry specified by given iterator.
bool erase (const word &)
Erase a hashedEntry specified by the given key.
label erase (const UList< word > &)
Remove entries given by the listed keys from this HashTable.
label erase (const HashTable< AnyType, word, AnyHash > &)
Remove entries given by the given keys from this HashTable.
Foam::label erase (const HashTable< AnyType, word, AnyHash > &rhs)
void resize (const label newSize)
Resize the hash table for efficiency.
void clear ()
Clear all entries from table.
void clearStorage ()
Clear the table entries and the table itself.
void shrink ()
Shrink the allocated table to approx. twice number of elements.
void transfer (HashTable< regIOobject *, word, string::hash > &)
Transfer the contents of the argument table into this table.
Xfer< HashTable< regIOobject *, word, string::hash > > xfer ()
Transfer contents to the Xfer container.
regIOobject * & operator[] (const word &)
Find and return a hashedEntry.
const regIOobject * & operator[] (const word &) const
Find and return a hashedEntry.
regIOobject * & operator() (const word &)
Find and return a hashedEntry, create it null if not present.
void operator= (const HashTable< regIOobject *, word, string::hash > &)
Assignment.
void operator= (std::initializer_list< Tuple2< word, regIOobject * >>)
Assignment to an initializer list.
bool operator== (const HashTable< regIOobject *, word, string::hash > &) const
Equality. Hash tables are equal if the keys and values are equal.
bool operator!= (const HashTable< regIOobject *, word, string::hash > &) const
The opposite of the equality operation. Takes linear time.
iterator begin ()
Iterator set to the beginning of the HashTable.
const_iterator begin () const
const_iterator set to the beginning of the HashTable
const_iterator cbegin () const
const_iterator set to the beginning of the HashTable
Public Member Functions inherited from HashTableCore
HashTableCore ()
Construct null.
ClassName ("HashTable")
Define template name and debug.
Public Member Functions inherited from PrimitivePatch< face, ::Foam::UList, ::Foam::SubField< point >, point >
PrimitivePatch (const ::Foam::UList< face > &faces, const Field< point > &points)
Construct from components.
PrimitivePatch (const Xfer< ::Foam::UList< face >> &faces, const Xfer< List< point >> &points)
Construct from components.
PrimitivePatch (::Foam::UList< face > &faces, Field< point > &points, const bool reuse)
Construct from components, reuse storage.
PrimitivePatch (const PrimitivePatch< face, ::Foam::UList, ::Foam::SubField< point >, point > &)
Construct as copy.
virtual ~PrimitivePatch ()
Destructor.
void clearOut ()
void clearGeom ()
void clearTopology ()
void clearPatchMeshAddr ()
const Field< point > & points () const
Return reference to global points.
label nPoints () const
Return number of points supporting patch faces.
label nEdges () const
Return number of edges in patch.
const edgeList & edges () const
Return list of edges, address into LOCAL point list.
label nInternalEdges () const
Number of internal edges.
bool isInternalEdge (const label edgeI) const
Is internal edge?
const labelList & boundaryPoints () const
Return list of boundary points,.
const labelListList & faceFaces () const
Return face-face addressing.
const labelListList & edgeFaces () const
Return edge-face addressing.
const labelListList & faceEdges () const
Return face-edge addressing.
const labelListList & pointEdges () const
Return point-edge addressing.
const labelListList & pointFaces () const
Return point-face addressing.
const List< face > & localFaces () const
Return patch faces addressing into local point list.
const labelList & meshPoints () const
Return labelList of mesh points in patch. They are constructed.
const Map< label > & meshPointMap () const
Mesh point map. Given the global point index find its.
const Field< point > & localPoints () const
Return pointField of points in patch.
const labelList & localPointOrder () const
Return orders the local points for most efficient search.
label whichPoint (const label gp) const
Given a global point index, return the local point index.
label whichEdge (const edge &) const
Given an edge in local point labels, return its.
labelList meshEdges (const edgeList &allEdges, const labelListList &cellEdges, const labelList &faceCells) const
Return labels of patch edges in the global edge list using.
labelList meshEdges (const edgeList &allEdges, const labelListList &pointEdges) const
Return labels of patch edges in the global edge list using.
const Field< point > & faceCentres () const
Return face centres for patch.
const Field< point > & faceNormals () const
Return face normals for patch.
const Field< point > & pointNormals () const
Return point normals for patch.
List< objectHit > projectPoints (const ToPatch &targetPatch, const Field< point > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
Foam::List< Foam::objectHit > projectPoints (const ToPatch &targetPatch, const Field< point > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
List< objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< point > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
Foam::List< Foam::objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< point > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
const labelListList & edgeLoops () const
Return list of closed loops of boundary vertices.
surfaceTopo surfaceType () const
Calculate surface type formed by patch.
bool checkTopology (const bool report=false, labelHashSet *setPtr=nullptr) const
Check surface formed by patch for manifoldness (see above).
bool checkPointManifold (const bool report=false, labelHashSet *setPtr=nullptr) const
Checks primitivePatch for faces sharing point but not edge.
virtual void movePoints (const Field< point > &)
Correct patch after moving points.
void operator= (const PrimitivePatch< face, ::Foam::UList, ::Foam::SubField< point >, point > &)
Assignment.
Public Member Functions inherited from UList< face >
void operator= (const face &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
UList ()
Null constructor.
UList (face *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const face * cdata () const
Return a const pointer to the first data element,.
face * data ()
Return a pointer to the first data element,.
face & first ()
Return the first element of the list.
const face & first () const
Return first element of the list.
face & last ()
Return the last element of the list.
const face & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1)
void checkSize (const label size) const
Check size is within valid range (0 ... size)
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1)
void shallowCopy (const UList< face > &)
Copy the pointer held by the given UList.
void deepCopy (const UList< face > &)
Copy elements of the given UList.
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
face & operator[] (const label)
Return element of UList.
const face & operator[] (const label) const
Return element of constant UList.
const bool & operator[] (const label i) const
operator const Foam::List< face > & () const
Allow cast to a const List<T>&.
iterator begin ()
Return an iterator to begin traversing the UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero)
void swap (UList< face > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< face > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< face > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< face > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< face > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< face > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< face > &) const
Return true if !(a < b). Takes linear time.
Static Public Member Functions
static void write (const fileName &, const surfMesh &)
Write to file.
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Static Public Member Functions inherited from HashTableCore
static label canonicalSize (const label)
Return a canonical (power-of-two) size.
static iteratorEnd cend ()
iteratorEnd set to beyond the end of any HashTable
static iteratorEnd end ()
iteratorEnd set to beyond the end of any HashTable
Static Public Member Functions inherited from UList< face >
static const UList< face > & null ()
Return a null UList.
Static Public Attributes
static word meshSubDir = "surfMesh"
Return the mesh sub-directory name (normally "surfMesh")
Static Public Attributes inherited from surfaceRegistry
static const word prefix
The prefix to local: surfaces.
static word defaultName
The default surface name: default.
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Static Public Attributes inherited from HashTableCore
static const label maxTableSize
Maximum allowable table size.
Protected Member Functions
pointField & storedPoints ()
Non-const access to global points.
faceList & storedFaces ()
Non-const access to the faces.
surfZoneList & storedZones ()
Non-const access to the zones.
virtual void updateFacesRef ()
Update references to storedFaces.
virtual void updatePointsRef ()
Update references to storedPoints.
virtual void updateRefs ()
Update references to storedPoints/storedFaces.
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Friends
template<class Face >
class MeshedSurface
template<class Face >
class UnsortedMeshedSurface
Additional Inherited Members
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
A surface mesh consisting of general polygon faces.
Source files
surfMesh.H
surfMesh.C
surfMeshClear.C
surfMeshIO.C
Definition at line 55 of file surfMesh.H.
Member Typedef Documentation
Mesh
typedef surfMesh Mesh
Definition at line 142 of file surfMesh.H.
BoundaryMesh
typedef bool BoundaryMesh
Placeholder only, but do not remove - it is needed for GeoMesh.
Definition at line 145 of file surfMesh.H.
Member Enumeration Documentation
readUpdateState
enum readUpdateState
Enumeration defining the state of the mesh after a read update.
Used for post-processing applications, where the mesh needs to update based on the files written in time directores
Enumerator
UNCHANGED
POINTS_MOVED
TOPO_CHANGE
TOPO_PATCH_CHANGE
Definition at line 72 of file surfMesh.H.
Constructor & Destructor Documentation
surfMesh() [1/3]
surfMesh (const IOobject & io, const word & surfName = "") explicit
Construct from IOobject, with alternative surface name.
Definition at line 74 of file surfMesh.C.
surfMesh() [2/3]
surfMesh (const IOobject & io, const Xfer< pointField > & pointLst, const Xfer< faceList > & faceLst, const word & surfName = "")
Construct by transferring components (points, faces) without zones.
surfZones are added using addZones() member function
Definition at line 112 of file surfMesh.C.
surfMesh() [3/3]
surfMesh (const IOobject & io, const Xfer< MeshedSurface< face >> & surf, const word & surfName = "")
Construct copy/move from MeshedSurface.
Definition at line 158 of file surfMesh.C.
References IOobject::db(), objectRegistry::dbDir(), Foam::endl(), Foam::Info, IOobject::instance(), IOobject::local(), IOobject::name(), Foam::nl, Foam::notNull(), IOobject::path(), and surfMesh::transfer().
~surfMesh()
~surfMesh () virtual
Destructor.
Definition at line 221 of file surfMesh.C.
Member Function Documentation
storedPoints()
pointField& storedPoints () inline protected
Non-const access to global points.
Definition at line 111 of file surfMesh.H.
References MeshedSurfaceIOAllocator::storedIOPoints().
Referenced by MeshedSurface< Foam::face >::MeshedSurface(), surfMesh::updatePointsRef(), and surfMesh::xfer().
storedFaces()
faceList& storedFaces () inline protected
Non-const access to the faces.
Definition at line 117 of file surfMesh.H.
References MeshedSurfaceIOAllocator::storedIOFaces().
Referenced by MeshedSurface< Foam::face >::MeshedSurface(), surfMesh::readUpdate(), surfMesh::updateFacesRef(), and surfMesh::xfer().
storedZones()
surfZoneList& storedZones () inline protected
Non-const access to the zones.
Definition at line 123 of file surfMesh.H.
References MeshedSurfaceIOAllocator::storedIOZones(), surfMesh::updateFacesRef(), surfMesh::updatePointsRef(), and surfMesh::updateRefs().
Referenced by MeshedSurface< Foam::face >::MeshedSurface(), surfMesh::removeZones(), and surfMesh::xfer().
updateFacesRef()
void updateFacesRef () protected virtual
Update references to storedFaces.
Definition at line 240 of file surfMesh.C.
References UList< face >::shallowCopy(), and surfMesh::storedFaces().
Referenced by surfMesh::storedZones(), and surfMesh::updateRefs().
updatePointsRef()
void updatePointsRef () protected virtual
Update references to storedPoints.
Definition at line 230 of file surfMesh.C.
References PrimitivePatch< face, ::Foam::UList, ::Foam::SubField< point >, point >::points(), and surfMesh::storedPoints().
Referenced by surfMesh::storedZones(), and surfMesh::updateRefs().
updateRefs()
void updateRefs () protected virtual
Update references to storedPoints/storedFaces.
Definition at line 247 of file surfMesh.C.
References surfMesh::resetPrimitives(), surfMesh::updateFacesRef(), and surfMesh::updatePointsRef().
Referenced by surfMesh::resetPrimitives(), surfMesh::storedZones(), surfMesh::transfer(), and surfMesh::xfer().
TypeName()
TypeName ("surfMesh")
Runtime type information.
meshDir()
Foam::fileName meshDir () const
Return the local mesh directory (dbDir()/meshSubDir)
Definition at line 309 of file surfMesh.C.
References objectRegistry::dbDir(), and surfMesh::meshSubDir.
Referenced by surfMesh::readUpdate().
pointsInstance()
const Foam::fileName & pointsInstance () const
Return the current instance directory for points.
Used in the consruction of geometric mesh data dependent on points
Definition at line 315 of file surfMesh.C.
References IOobject::instance(), and MeshedSurfaceIOAllocator::storedIOPoints().
Referenced by surfMesh::readUpdate().
facesInstance()
const Foam::fileName & facesInstance () const
Return the current instance directory for faces.
Definition at line 321 of file surfMesh.C.
References IOobject::instance(), and MeshedSurfaceIOAllocator::storedIOFaces().
Referenced by surfMesh::readUpdate().
setInstance()
void setInstance (const fileName & inst)
Set the instance for mesh files.
Definition at line 31 of file surfMeshIO.C.
References IOobject::AUTO_WRITE, Foam::endl(), InfoInFunction, IOobject::instance(), MeshedSurfaceIOAllocator::storedIOFaces(), MeshedSurfaceIOAllocator::storedIOPoints(), MeshedSurfaceIOAllocator::storedIOZones(), and IOobject::writeOpt().
Referenced by surfMesh::readUpdate().
nPoints()
Foam::label nPoints () const virtual
Return the number of raw points.
Definition at line 327 of file surfMesh.C.
References surfMesh::points(), and List< T >::size().
Referenced by surfPointGeoMesh::size().
nFaces()
Foam::label nFaces () const virtual
Return the number of raw faces.
Definition at line 333 of file surfMesh.C.
References surfMesh::faces(), and List< T >::size().
Referenced by surfMesh::checkZones(), surfGeoMesh::size(), and surfMesh::size().
size()
virtual label size () const inline virtual
Return number of faces.
Definition at line 210 of file surfMesh.H.
References surfMesh::faces(), surfMesh::nFaces(), and surfMesh::points().
Referenced by surfMesh::checkZones().
points()
const Foam::pointField & points () const virtual
Return points.
Definition at line 339 of file surfMesh.C.
References MeshedSurfaceIOAllocator::storedIOPoints().
Referenced by MeshedSurface< Foam::face >::MeshedSurface(), surfMesh::nPoints(), surfMesh::size(), and surfMesh::write().
faces()
const Foam::faceList & faces () const virtual
Return faces.
Definition at line 345 of file surfMesh.C.
References MeshedSurfaceIOAllocator::storedIOFaces().
Referenced by MeshedSurface< Foam::face >::MeshedSurface(), surfMesh::nFaces(), surfMesh::size(), and surfMesh::write().
surfZones()
virtual const surfZoneList& surfZones () const inline virtual
Return surface zones.
Definition at line 223 of file surfMesh.H.
References surfMesh::addZones(), surfMesh::checkZones(), surfMesh::clearAddressing(), surfMesh::clearGeom(), surfMesh::clearOut(), surfMesh::clearPrimitives(), surfMesh::readUpdate(), surfMesh::removeFiles(), surfMesh::removeZones(), surfMesh::resetPrimitives(), MeshedSurfaceIOAllocator::storedIOZones(), surfMesh::transfer(), validate(), regIOobject::write(), and surfMesh::xfer().
Referenced by MeshedSurface< Foam::face >::MeshedSurface(), and surfMesh::write().
checkZones()
void checkZones ()
Check the surface zone definitions.
Definition at line 351 of file surfMesh.C.
References surfMesh::addZones(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, UList< T >::last(), surfMesh::nFaces(), surfMesh::removeZones(), List< T >::size(), surfMesh::size(), MeshedSurfaceIOAllocator::storedIOZones(), and WarningInFunction.
Referenced by surfMesh::addZones(), surfMesh::resetPrimitives(), and surfMesh::surfZones().
addZones()
void addZones (const List< surfZone > & , const bool validate = true)
Add surface zones.
Definition at line 391 of file surfMesh.C.
References surfMesh::checkZones(), forAll, and MeshedSurfaceIOAllocator::storedIOZones().
Referenced by surfMesh::checkZones(), and surfMesh::surfZones().
readUpdate()
Foam::surfMesh::readUpdateState readUpdate () virtual
Update the mesh based on the mesh files saved in.
time directories
Definition at line 51 of file surfMeshIO.C.
References surfMesh::clearGeom(), surfMesh::clearOut(), Foam::endl(), surfMesh::facesInstance(), forAll, Foam::Info, InfoInFunction, IOobject::instance(), surfMesh::meshDir(), surfMesh::meshSubDir, IOobject::MUST_READ, IOobject::name(), Foam::nl, IOobject::NO_WRITE, surfMesh::POINTS_MOVED, surfMesh::pointsInstance(), surfMesh::setInstance(), List< T >::size(), surfMesh::storedFaces(), MeshedSurfaceIOAllocator::storedIOPoints(), MeshedSurfaceIOAllocator::storedIOZones(), objectRegistry::time(), surfMesh::TOPO_CHANGE, surfMesh::TOPO_PATCH_CHANGE, List< T >::transfer(), surfMesh::UNCHANGED, and WarningInFunction.
Referenced by surfMesh::surfZones().
removeZones()
void removeZones ()
Update the mesh corresponding to given map.
Remove surface zones
Definition at line 32 of file surfMeshClear.C.
References List< T >::clear(), surfMesh::clearOut(), Foam::endl(), InfoInFunction, and surfMesh::storedZones().
Referenced by surfMesh::checkZones(), and surfMesh::surfZones().
resetPrimitives()
void resetPrimitives (const Xfer< pointField > & points, const Xfer< faceList > & faces, const Xfer< surfZoneList > & zones, const bool validate = true)
Reset mesh primitive data.
Definition at line 255 of file surfMesh.C.
References surfMesh::checkZones(), PrimitivePatch< face, ::Foam::UList, ::Foam::SubField< point >, point >::clearGeom(), MeshedSurfaceIOAllocator::reset(), surfMesh::transfer(), and surfMesh::updateRefs().
Referenced by surfMesh::surfZones(), and surfMesh::updateRefs().
transfer()
void transfer (MeshedSurface< face > & surf)
Transfer the contents of the argument and annul the argument.
Definition at line 276 of file surfMesh.C.
References PrimitivePatch< face, ::Foam::UList, ::Foam::SubField< point >, point >::clearGeom(), MeshedSurface< Face >::storedFaces(), MeshedSurfaceIOAllocator::storedIOFaces(), MeshedSurfaceIOAllocator::storedIOPoints(), MeshedSurfaceIOAllocator::storedIOZones(), MeshedSurface< Face >::storedPoints(), MeshedSurface< Face >::storedZones(), List< T >::transfer(), and surfMesh::updateRefs().
Referenced by surfMesh::resetPrimitives(), surfMesh::surfMesh(), and surfMesh::surfZones().
write() [1/2]
void write (const fileName & name, const surfMesh & surf) static
Write to file.
Definition at line 426 of file surfMesh.C.
References surfMesh::faces(), surfMesh::points(), surfMesh::surfZones(), and regIOobject::write().
write() [2/2]
void write (const fileName & name)
Write to file.
Definition at line 437 of file surfMesh.C.
References regIOobject::write().
xfer()
Foam::Xfer< Foam::MeshedSurface< Foam::face > > xfer ()
Transfer contents to the Xfer container as a MeshedSurface.
Definition at line 291 of file surfMesh.C.
References PrimitivePatch< face, ::Foam::UList, ::Foam::SubField< point >, point >::clearGeom(), surfMesh::storedFaces(), surfMesh::storedPoints(), surfMesh::storedZones(), and surfMesh::updateRefs().
Referenced by surfMesh::surfZones().
clearGeom()
void clearGeom ()
Clear geometry.
Definition at line 48 of file surfMeshClear.C.
References PrimitivePatch< face, ::Foam::UList, ::Foam::SubField< point >, point >::clearGeom(), Foam::endl(), and InfoInFunction.
Referenced by surfMesh::clearOut(), surfMesh::readUpdate(), and surfMesh::surfZones().
clearAddressing()
void clearAddressing ()
Clear addressing.
Definition at line 59 of file surfMeshClear.C.
References PrimitivePatch< face, ::Foam::UList, ::Foam::SubField< point >, point >::clearPatchMeshAddr(), Foam::endl(), and InfoInFunction.
Referenced by surfMesh::clearOut(), and surfMesh::surfZones().
clearOut()
void clearOut ()
Clear all geometry and addressing unnecessary for CFD.
Definition at line 70 of file surfMeshClear.C.
References surfMesh::clearAddressing(), and surfMesh::clearGeom().
Referenced by surfMesh::readUpdate(), surfMesh::removeZones(), and surfMesh::surfZones().
clearPrimitives()
void clearPrimitives ()
Clear primitive data (points, faces and cells)
Referenced by surfMesh::surfZones().
removeFiles() [1/2]
void removeFiles (const fileName & instanceDir) const
Remove all files from mesh instance.
Definition at line 411 of file surfMesh.C.
References IOobject::db(), surfMesh::meshSubDir, IOobject::path(), and Foam::rm().
removeFiles() [2/2]
void removeFiles () const
Remove all files from mesh instance()
Definition at line 420 of file surfMesh.C.
References IOobject::instance().
Referenced by surfMesh::surfZones().
Friends And Related Function Documentation
MeshedSurface
friend class MeshedSurface friend
Definition at line 62 of file surfMesh.H.
UnsortedMeshedSurface
friend class UnsortedMeshedSurface friend
Definition at line 63 of file surfMesh.H.
Member Data Documentation
meshSubDir
Foam::word meshSubDir = "surfMesh" static
Return the mesh sub-directory name (normally "surfMesh")
Definition at line 152 of file surfMesh.H.
Referenced by edgeMeshFormatsCore::getLineNoComment(), surfaceFormatsCore::getLineNoComment(), surfMesh::meshDir(), surfMesh::readUpdate(), and surfMesh::removeFiles().
The documentation for this class was generated from the following files:
src/surfMesh/surfMesh/surfMesh.H
src/surfMesh/surfMesh/surfMesh.C
src/surfMesh/surfMesh/surfMeshClear.C
src/surfMesh/surfMesh/surfMeshIO.C