OpenFOAM: surfZoneIdentifier Class Reference
surfZoneIdentifier Class Reference
An identifier for a surface zone on a meshed surface.
Public Member Functions
surfZoneIdentifier ()
Construct null.
surfZoneIdentifier (const word &name, const label index, const word &geometricType=word::null)
Construct from components.
surfZoneIdentifier (const word &name, const dictionary &, const label index)
Construct from dictionary.
surfZoneIdentifier (const surfZoneIdentifier &, const label index)
Construct from another zone identifier, resetting the index.
virtual ~surfZoneIdentifier ()
Destructor.
const word & name () const
Return name.
word & name ()
Return name for modification.
const word & geometricType () const
Return the geometric type of the zone.
word & geometricType ()
Return the geometric type of the zone for modification.
label index () const
Return the index of this zone in the surface mesh.
void write (Ostream &) const
Write surfZoneIdentifier as a dictionary.
Friends
Ostream & operator<< (Ostream &, const surfZoneIdentifier &)
Write surfZoneIdentifier as a dictionary.
Detailed Description
An identifier for a surface zone on a meshed surface.
Similar in concept to a faceZone on the surface, but can also have a "geometricType" as well.
Source files
surfZoneIdentifier.H
surfZoneIdentifier.C
Definition at line 60 of file surfZoneIdentifier.H.
Constructor & Destructor Documentation
surfZoneIdentifier() [1/4]
surfZoneIdentifier ()
Construct null.
Definition at line 31 of file surfZoneIdentifier.C.
Referenced by surfZoneIdentifier::surfZoneIdentifier().
surfZoneIdentifier() [2/4]
surfZoneIdentifier (const word & name, const label index, const word & geometricType = word::null)
Construct from components.
Definition at line 40 of file surfZoneIdentifier.C.
References surfZoneIdentifier::surfZoneIdentifier().
surfZoneIdentifier() [3/4]
surfZoneIdentifier (const word & name, const dictionary & dict, const label index)
Construct from dictionary.
Definition at line 53 of file surfZoneIdentifier.C.
References dictionary::readIfPresent(), and surfZoneIdentifier::surfZoneIdentifier().
surfZoneIdentifier() [4/4]
surfZoneIdentifier (const surfZoneIdentifier & p, const label index)
Construct from another zone identifier, resetting the index.
Definition at line 67 of file surfZoneIdentifier.C.
~surfZoneIdentifier()
~surfZoneIdentifier () virtual
Destructor.
Definition at line 80 of file surfZoneIdentifier.C.
Member Function Documentation
name() [1/2]
const word& name () const inline
Return name.
Definition at line 113 of file surfZoneIdentifier.H.
Referenced by surfZone::New(), surfZone::surfZone(), OBJsurfaceFormat< Face >::write(), AC3DsurfaceFormat< Face >::write(), STLsurfaceFormat< Face >::writeAscii(), and surfZone::writeDict().
name() [2/2]
word& name () inline
Return name for modification.
Definition at line 119 of file surfZoneIdentifier.H.
geometricType() [1/2]
const word& geometricType () const inline
Return the geometric type of the zone.
Definition at line 125 of file surfZoneIdentifier.H.
Referenced by surfZone::operator==().
geometricType() [2/2]
word& geometricType () inline
Return the geometric type of the zone for modification.
Definition at line 131 of file surfZoneIdentifier.H.
index()
label index () const inline
Return the index of this zone in the surface mesh.
Definition at line 137 of file surfZoneIdentifier.H.
References surfZoneIdentifier::operator<<, and surfZoneIdentifier::write().
write()
void write (Ostream & os) const
Write surfZoneIdentifier as a dictionary.
Definition at line 87 of file surfZoneIdentifier.C.
References token::END_STATEMENT, Foam::nl, and Ostream::writeKeyword().
Referenced by surfZoneIdentifier::index(), Foam::operator<<(), and surfZone::writeDict().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const surfZoneIdentifier &) friend
Write surfZoneIdentifier as a dictionary.
void writeDict(Ostream&) const;
Referenced by surfZoneIdentifier::index().
The documentation for this class was generated from the following files:
src/surfMesh/surfZone/surfZoneIdentifier/surfZoneIdentifier.H
src/surfMesh/surfZone/surfZoneIdentifier/surfZoneIdentifier.C