OpenFOAM: TDACChemistryModel< CompType, ThermoType > Class Template Reference
TDACChemistryModel< CompType, ThermoType > Class Template Reference abstract
Extends chemistryModel by adding the TDAC method.
Public Member Functions
TypeName ("TDACChemistryModel")
Runtime type information.
TDACChemistryModel (const fvMesh &mesh, const word &phaseName)
Construct from mesh.
virtual ~TDACChemistryModel ()
Destructor.
autoPtr< OFstream > logFile (const word &name) const
Create and return a TDAC log file of the given name.
PtrList< volScalarField > & Y ()
virtual void omega (const scalarField &c, const scalar T, const scalar p, scalarField &dcdt) const
dc/dt = omega, rate of change in concentration, for each species
virtual scalar omega (const Reaction< ThermoType > &r, const scalarField &c, const scalar T, const scalar p, scalar &pf, scalar &cf, label &lRef, scalar &pr, scalar &cr, label &rRef) const
Return the reaction rate for reaction r and the reference.
virtual scalar solve (const scalar deltaT)
Solve the reaction system for the given time step.
virtual scalar solve (const scalarField &deltaT)
Solve the reaction system for the given time step.
virtual void derivatives (const scalar t, const scalarField &c, scalarField &dcdt) const
Calculate the derivatives in dydx.
void jacobian (const scalar t, const scalarField &c, scalarSquareMatrix &dfdc) const
Pure jacobian function for tabulation.
virtual void jacobian (const scalar t, const scalarField &c, scalarField &dcdt, scalarSquareMatrix &dfdc) const
Calculate the Jacobian of the system.
virtual void solve (scalarField &c, scalar &T, scalar &p, scalar &deltaT, scalar &subDeltaT) const =0
void setNsDAC (const label newNsDAC)
void setNSpecie (const label newNs)
scalarField & completeC ()
scalarField & simplifiedC ()
Field< bool > & reactionsDisabled ()
bool active (const label i) const
void setActive (const label i)
DynamicList< label > & simplifiedToCompleteIndex ()
Field< label > & completeToSimplifiedIndex ()
const Field< label > & completeToSimplifiedIndex () const
List< List< specieElement > > & specieComp ()
autoPtr< chemistryReductionMethod< CompType, ThermoType > > & mechRed ()
template<class DeltaTType >
Foam::scalar solve (const DeltaTType &deltaT)
Public Member Functions inherited from chemistryModel< CompType, ThermoType >
TypeName ("chemistryModel")
Runtime type information.
chemistryModel (const fvMesh &mesh, const word &phaseName)
Construct from mesh.
virtual ~chemistryModel ()
Destructor.
const PtrList< Reaction< ThermoType > > & reactions () const
The reactions.
const PtrList< ThermoType > & specieThermo () const
Thermodynamic data of the species.
virtual label nSpecie () const
The number of species.
virtual label nReaction () const
The number of reactions.
scalar Treact () const
Temperature below which the reaction rates are assumed 0.
scalar & Treact ()
Temperature below which the reaction rates are assumed 0.
virtual scalar omegaI (label iReaction, const scalarField &c, const scalar T, const scalar p, scalar &pf, scalar &cf, label &lRef, scalar &pr, scalar &cr, label &rRef) const
Return the reaction rate for iReaction and the reference.
virtual void calculate ()
Calculates the reaction rates.
const volScalarField::Internal & RR (const label i) const
Return const access to the chemical source terms for specie, i.
virtual volScalarField::Internal & RR (const label i)
Return non const access to chemical source terms [kg/m3/s].
virtual tmp< volScalarField::Internal > calculateRR (const label reactionI, const label speciei) const
Return reaction rate of the speciei in reactionI.
virtual tmp< volScalarField > tc () const
Return the chemical time scale.
virtual tmp< volScalarField > Sh () const
Return source for enthalpy equation [kg/m/s3].
virtual tmp< volScalarField > dQ () const
Return the heat release, i.e. enthalpy/sec [kg/m2/s3].
virtual label nEqns () const
Number of ODE's to solve.
template<class DeltaTType >
Foam::scalar solve (const DeltaTType &deltaT)
Public Member Functions inherited from ODESystem
ODESystem ()
Construct null.
virtual ~ODESystem ()
Destructor.
Additional Inherited Members
Protected Types inherited from chemistryModel< CompType, ThermoType >
typedef ThermoType thermoType
Protected Member Functions inherited from chemistryModel< CompType, ThermoType >
PtrList< volScalarField::Internal > & RR ()
Write access to chemical source terms.
Protected Attributes inherited from chemistryModel< CompType, ThermoType >
PtrList< volScalarField > & Y_
Reference to the field of specie mass fractions.
const PtrList< Reaction< ThermoType > > & reactions_
Reactions.
const PtrList< ThermoType > & specieThermo_
Thermodynamic data of the species.
label nSpecie_
Number of species.
label nReaction_
Number of reactions.
scalar Treact_
Temperature below which the reaction rates are assumed 0.
PtrList< volScalarField::Internal > RR_
List of reaction rate per specie [kg/m3/s].
scalarField c_
Temporary concentration field.
scalarField dcdt_
Temporary rate-of-change of concentration field.
Detailed Description
template<class CompType, class ThermoType>
class Foam::TDACChemistryModel< CompType, ThermoType >
Extends chemistryModel by adding the TDAC method.
References:
    Contino, F., Jeanmart, H., Lucchini, T., & D’Errico, G. (2011).
    Coupling of in situ adaptive tabulation and dynamic adaptive chemistry:
    An effective method for solving combustion in engine simulations.
    Proceedings of the Combustion Institute, 33(2), 3057-3064.
    Contino, F., Lucchini, T., D'Errico, G., Duynslaegher, C.,
    Dias, V., & Jeanmart, H. (2012).
    Simulations of advanced combustion modes using detailed chemistry
    combined with tabulation and mechanism reduction techniques.
    SAE International Journal of Engines,
    5(2012-01-0145), 185-196.
    Contino, F., Foucher, F., Dagaut, P., Lucchini, T., D’Errico, G., &
    Mounaïm-Rousselle, C. (2013).
    Experimental and numerical analysis of nitric oxide effect on the
    ignition of iso-octane in a single cylinder HCCI engine.
    Combustion and Flame, 160(8), 1476-1483.
    Contino, F., Masurier, J. B., Foucher, F., Lucchini, T., D’Errico, G., &
    Dagaut, P. (2014).
    CFD simulations using the TDAC method to model iso-octane combustion
    for a large range of ozone seeding and temperature conditions
    in a single cylinder HCCI engine.
    Fuel, 137, 179-184.
Source files
TDACChemistryModel.H
TDACChemistryModelI.H
TDACChemistryModel.C
Definition at line 47 of file chemistryReductionMethod.H.
Constructor & Destructor Documentation
TDACChemistryModel()
TDACChemistryModel (const fvMesh & mesh, const word & phaseName)
Construct from mesh.
Definition at line 34 of file TDACChemistryModel.C.
References composition, forAll, mesh, Foam::name(), Foam::New(), basicMultiComponentMixture::setInactive(), basicMultiComponentMixture::species(), thermo, and Y.
~TDACChemistryModel()
~TDACChemistryModel () virtual
Destructor.
Definition at line 119 of file TDACChemistryModel.C.
References TDACChemistryModel< CompType, ThermoType >::omega().
Member Function Documentation
TypeName()
TypeName ("TDACChemistryModel< CompType, ThermoType >")
Runtime type information.
logFile()
Foam::autoPtr< Foam::OFstream > logFile (const word & name) const inline
Create and return a TDAC log file of the given name.
Definition at line 30 of file TDACChemistryModelI.H.
References mesh, Foam::mkDir(), and path().
Referenced by ISAT< CompType, ThermoType >::ISAT().
Y()
Foam::PtrList< Foam::volScalarField > & Y () inline
Definition at line 45 of file TDACChemistryModelI.H.
Referenced by DAC< CompType, ThermoType >::DAC(), DRG< CompType, ThermoType >::DRG(), DRGEP< CompType, ThermoType >::DRGEP(), and PFA< CompType, ThermoType >::PFA().
omega() [1/2]
void omega (const scalarField & c, const scalar T, const scalar p, scalarField & dcdt) const virtual
dc/dt = omega, rate of change in concentration, for each species
Reimplemented from chemistryModel< CompType, ThermoType >.
Definition at line 127 of file TDACChemistryModel.C.
References forAll, Reaction< ReactionThermo >::lhs(), R, Reaction< ReactionThermo >::rhs(), s(), and Foam::Zero.
Referenced by TDACChemistryModel< CompType, ThermoType >::~TDACChemistryModel().
omega() [2/2]
Foam::scalar omega (const Reaction< ThermoType > & r, const scalarField & c, const scalar T, const scalar p, scalar & pf, scalar & cf, label & lRef, scalar & pr, scalar & cr, label & rRef) const virtual
Return the reaction rate for reaction r and the reference.
species and charateristic times
Reimplemented from chemistryModel< CompType, ThermoType >.
Definition at line 181 of file TDACChemistryModel.C.
References TDACChemistryModel< CompType, ThermoType >::derivatives(), Foam::exp(), Reaction< ReactionThermo >::kf(), Reaction< ReactionThermo >::kr(), Reaction< ReactionThermo >::lhs(), Foam::max(), Foam::pow(), Reaction< ReactionThermo >::rhs(), and s().
solve() [1/4]
Foam::scalar solve (const scalar deltaT) virtual
Solve the reaction system for the given time step.
and return the characteristic time
Reimplemented from chemistryModel< CompType, ThermoType >.
Definition at line 820 of file TDACChemistryModel.C.
References Foam::min(), and solve().
solve() [2/4]
Foam::scalar solve (const scalarField & deltaT) virtual
Solve the reaction system for the given time step.
and return the characteristic time
Reimplemented from chemistryModel< CompType, ThermoType >.
Definition at line 835 of file TDACChemistryModel.C.
derivatives()
void derivatives (const scalar x, const scalarField & y, scalarField & dydx) const virtual
Calculate the derivatives in dydx.
Reimplemented from chemistryModel< CompType, ThermoType >.
Definition at line 290 of file TDACChemistryModel.C.
References cp, TDACChemistryModel< CompType, ThermoType >::jacobian(), Foam::max(), nSpecie, and rho.
Referenced by TDACChemistryModel< CompType, ThermoType >::omega().
jacobian() [1/2]
void jacobian (const scalar t, const scalarField & c, scalarSquareMatrix & dfdc) const
Pure jacobian function for tabulation.
Definition at line 374 of file TDACChemistryModel.C.
References delta, Foam::constant::electromagnetic::e, forAll, Reaction< ReactionThermo >::kf(), Reaction< ReactionThermo >::kr(), Reaction< ReactionThermo >::lhs(), Foam::max(), Foam::pow(), Reaction< ReactionThermo >::rhs(), and Foam::Zero.
Referenced by TDACChemistryModel< CompType, ThermoType >::derivatives().
jacobian() [2/2]
void jacobian (const scalar x, const scalarField & y, scalarField & dfdx, scalarSquareMatrix & dfdy) const virtual
Calculate the Jacobian of the system.
Need by the stiff-system solvers
Reimplemented from chemistryModel< CompType, ThermoType >.
Definition at line 558 of file TDACChemistryModel.C.
solve() [3/4]
virtual void solve (scalarField & c, scalar & T, scalar & p, scalar & deltaT, scalar & subDeltaT) const pure virtual
Implements chemistryModel< CompType, ThermoType >.
setNsDAC()
void setNsDAC (const label newNsDAC) inline
Definition at line 81 of file TDACChemistryModelI.H.
setNSpecie()
void setNSpecie (const label newNs) inline
Definition at line 89 of file TDACChemistryModelI.H.
completeC()
Foam::scalarField & completeC () inline
Definition at line 130 of file TDACChemistryModelI.H.
simplifiedC()
Foam::scalarField & simplifiedC () inline
Definition at line 138 of file TDACChemistryModelI.H.
reactionsDisabled()
Foam::Field< bool > & reactionsDisabled () inline
Definition at line 122 of file TDACChemistryModelI.H.
active()
bool active (const label i) const inline
Definition at line 71 of file TDACChemistryModelI.H.
References thermo.
Referenced by TDACChemistryModel< CompType, ThermoType >::setActive(), and TDACChemistryModel< CompType, ThermoType >::solve().
setActive()
void setActive (const label i) inline
Definition at line 61 of file TDACChemistryModelI.H.
References TDACChemistryModel< CompType, ThermoType >::active(), and thermo.
Referenced by TDACChemistryModel< CompType, ThermoType >::mechRed().
simplifiedToCompleteIndex()
Foam::DynamicList< Foam::label > & simplifiedToCompleteIndex () inline
Definition at line 97 of file TDACChemistryModelI.H.
Referenced by chemPointISAT< CompType, ThermoType >::chemPointISAT().
completeToSimplifiedIndex() [1/2]
Foam::Field< Foam::label > & completeToSimplifiedIndex () inline
Definition at line 105 of file TDACChemistryModelI.H.
Referenced by chemPointISAT< CompType, ThermoType >::chemPointISAT().
completeToSimplifiedIndex() [2/2]
const Foam::Field< Foam::label > & completeToSimplifiedIndex () const inline
Definition at line 114 of file TDACChemistryModelI.H.
specieComp()
Foam::List< Foam::List< Foam::specieElement > > & specieComp () inline
Definition at line 146 of file TDACChemistryModelI.H.
Referenced by DAC< CompType, ThermoType >::DAC().
mechRed()
Foam::autoPtr< Foam::chemistryReductionMethod< CompType, ThermoType > > & mechRed () inline
Definition at line 53 of file TDACChemistryModelI.H.
References TDACChemistryModel< CompType, ThermoType >::setActive().
solve() [4/4]
Foam::scalar solve (const DeltaTType & deltaT)
Definition at line 578 of file TDACChemistryModel.C.
References basicMultiComponentMixture::active(), TDACChemistryModel< CompType, ThermoType >::active(), Foam::constant::universal::c, composition, correct, Foam::endl(), forAll, mesh, Foam::min(), nSpecie, Foam::constant::mathematical::pi(), rho, basicMultiComponentMixture::setActive(), List< T >::size(), solve(), thermo, clockTime::timeIncrement(), timeName, Y, and Foam::Zero.
The documentation for this class was generated from the following files:
src/thermophysicalModels/chemistryModel/chemistryModel/TDACChemistryModel/reduction/chemistryReductionMethod/chemistryReductionMethod.H
src/thermophysicalModels/chemistryModel/chemistryModel/TDACChemistryModel/TDACChemistryModel.H
src/thermophysicalModels/chemistryModel/chemistryModel/TDACChemistryModel/TDACChemistryModel.C
src/thermophysicalModels/chemistryModel/chemistryModel/TDACChemistryModel/TDACChemistryModelI.H