OpenFOAM: pureMixture< ThermoType > Class Template Reference
pureMixture< ThermoType > Class Template Reference
Foam::pureMixture.
Public Types
typedef ThermoType thermoType
The type of thermodynamics this mixture is instantiated for.
Public Types inherited from basicMixture
typedef basicMixture basicMixtureType
The base class of the mixture.
Public Member Functions
pureMixture (const dictionary &, const fvMesh &, const word &)
Construct from dictionary, mesh and phase name.
const ThermoType & cellMixture (const label) const
const ThermoType & patchFaceMixture (const label, const label) const
const ThermoType & cellVolMixture (const scalar, const scalar, const label) const
const ThermoType & patchFaceVolMixture (const scalar, const scalar, const label, const label) const
void read (const dictionary &)
Read dictionary.
Public Member Functions inherited from basicMixture
basicMixture (const dictionary &, const fvMesh &, const word &)
Construct from dictionary, mesh and phase name.
Detailed Description
template<class ThermoType>
class Foam::pureMixture< ThermoType >
Foam::pureMixture.
Source files
pureMixture.H
pureMixture.C
Definition at line 49 of file pureMixture.H.
Member Typedef Documentation
thermoType
typedef ThermoType thermoType
The type of thermodynamics this mixture is instantiated for.
Definition at line 64 of file pureMixture.H.
Constructor & Destructor Documentation
pureMixture()
pureMixture (const dictionary & thermoDict, const fvMesh & mesh, const word & phaseName)
Construct from dictionary, mesh and phase name.
Definition at line 33 of file pureMixture.C.
Member Function Documentation
cellMixture()
const ThermoType& cellMixture (const label) const inline
Definition at line 75 of file pureMixture.H.
References pureMixture< ThermoType >::patchFaceMixture().
patchFaceMixture()
const ThermoType& patchFaceMixture (const label , const label) const inline
Definition at line 81 of file pureMixture.H.
References pureMixture< ThermoType >::cellVolMixture().
Referenced by pureMixture< ThermoType >::cellMixture().
cellVolMixture()
const ThermoType& cellVolMixture (const scalar , const scalar , const label) const inline
Definition at line 90 of file pureMixture.H.
References pureMixture< ThermoType >::patchFaceVolMixture().
Referenced by pureMixture< ThermoType >::patchFaceMixture().
patchFaceVolMixture()
const ThermoType& patchFaceVolMixture (const scalar , const scalar , const label , const label) const inline
Definition at line 100 of file pureMixture.H.
References pureMixture< ThermoType >::read().
Referenced by pureMixture< ThermoType >::cellVolMixture().
read()
void read (const dictionary & thermoDict)
Read dictionary.
Definition at line 47 of file pureMixture.C.
References dictionary::subDict().
Referenced by pureMixture< ThermoType >::patchFaceVolMixture().
The documentation for this class was generated from the following files:
src/thermophysicalModels/basic/mixtures/pureMixture/pureMixture.H
src/thermophysicalModels/basic/mixtures/pureMixture/pureMixture.C