OpenFOAM: chemistryReductionMethod< CompType, ThermoType > Class Template Reference
chemistryReductionMethod< CompType, ThermoType > Class Template Reference abstract
An abstract class for methods of chemical mechanism reduction.
Public Member Functions
TypeName ("chemistryReductionMethod")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, chemistryReductionMethod, dictionary,(const IOdictionary &dict, TDACChemistryModel< CompType, ThermoType > &chemistry),(dict, chemistry))
chemistryReductionMethod (const IOdictionary &dict, TDACChemistryModel< CompType, ThermoType > &chemistry)
Construct from components.
virtual ~chemistryReductionMethod ()
Destructor.
bool active () const
Is mechanism reduction active?
bool log () const
Is performance data logging enabled?
const List< bool > & activeSpecies () const
Return the active species.
label NsSimp ()
Return the number of active species.
label nSpecie ()
Return the initial number of species.
scalar tolerance () const
Return the tolerance.
virtual void reduceMechanism (const scalarField &c, const scalar T, const scalar p)=0
Reduce the mechanism.
Static Public Member Functions
static autoPtr< chemistryReductionMethod< CompType, ThermoType > > New (const IOdictionary &dict, TDACChemistryModel< CompType, ThermoType > &chemistry)
Protected Attributes
const IOdictionary & dict_
const dictionary coeffsDict_
Dictionary that store the algorithm data.
Switch active_
Is mechanism reduction active?
Switch log_
Switch to select performance logging.
TDACChemistryModel< CompType, ThermoType > & chemistry_
List< bool > activeSpecies_
List of active species (active = true)
label NsSimp_
Number of active species.
const label nSpecie_
Number of species.
scalar tolerance_
Tolerance for the mechanism reduction algorithm.
Detailed Description
template<class CompType, class ThermoType>
class Foam::chemistryReductionMethod< CompType, ThermoType >
An abstract class for methods of chemical mechanism reduction.
An abstract class for reducing chemical mechanism.
Source files
chemistryReductionMethod.H
chemistryReductionMethod.C
Source files
chemistryReductionMethodI.H
chemistryReductionMethod.C
Definition at line 54 of file chemistryReductionMethod.H.
Constructor & Destructor Documentation
chemistryReductionMethod()
chemistryReductionMethod (const IOdictionary & dict, Foam::TDACChemistryModel< CompType, ThermoType > & chemistry)
Construct from components.
Definition at line 33 of file chemistryReductionMethod.C.
References chemistryReductionMethod< CompType, ThermoType >::~chemistryReductionMethod().
~chemistryReductionMethod()
~chemistryReductionMethod () virtual
Destructor.
Definition at line 54 of file chemistryReductionMethod.C.
Referenced by chemistryReductionMethod< CompType, ThermoType >::chemistryReductionMethod().
Member Function Documentation
TypeName()
TypeName ("chemistryReductionMethod< CompType, ThermoType >")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , chemistryReductionMethod< CompType, ThermoType > , dictionary , (const IOdictionary &dict, TDACChemistryModel< CompType, ThermoType > &chemistry) , (dict, chemistry))
New()
Foam::autoPtr< Foam::chemistryReductionMethod< CompType, ThermoType > > New (const IOdictionary & dict, TDACChemistryModel< CompType, ThermoType > & chemistry) static
Definition at line 34 of file chemistryReductionMethodNew.C.
References chemistry, TimePaths::constant(), IOobject::db(), dict, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::FatalIOError, FatalIOErrorInFunction, dictionary::isDict(), dictionary::lookup(), dictionary::subDict(), and objectRegistry::time().
active()
bool active () const inline
Is mechanism reduction active?
Definition at line 38 of file chemistryReductionMethodI.H.
log()
bool log () const inline
Is performance data logging enabled?
Definition at line 46 of file chemistryReductionMethodI.H.
activeSpecies()
const Foam::List< bool > & activeSpecies () const inline
Return the active species.
Definition at line 54 of file chemistryReductionMethodI.H.
NsSimp()
Foam::label NsSimp () inline
Return the number of active species.
Definition at line 61 of file chemistryReductionMethodI.H.
nSpecie()
Foam::label nSpecie () inline
Return the initial number of species.
Definition at line 69 of file chemistryReductionMethodI.H.
tolerance()
Foam::scalar tolerance () const inline
Return the tolerance.
Definition at line 77 of file chemistryReductionMethodI.H.
reduceMechanism()
virtual void reduceMechanism (const scalarField & c, const scalar T, const scalar p) pure virtual
Reduce the mechanism.
Implemented in DRGEP< CompType, ThermoType >, DAC< CompType, ThermoType >, DRG< CompType, ThermoType >, PFA< CompType, ThermoType >, EFA< CompType, ThermoType >, and none< CompType, ThermoType >.
Member Data Documentation
dict_
const IOdictionary& dict_ protected
Definition at line 59 of file chemistryReductionMethod.H.
coeffsDict_
const dictionary coeffsDict_ protected
Dictionary that store the algorithm data.
Definition at line 62 of file chemistryReductionMethod.H.
active_
Switch active_ protected
Is mechanism reduction active?
Definition at line 65 of file chemistryReductionMethod.H.
log_
Switch log_ protected
Switch to select performance logging.
Definition at line 68 of file chemistryReductionMethod.H.
chemistry_
TDACChemistryModel<CompType, ThermoType>& chemistry_ protected
Definition at line 70 of file chemistryReductionMethod.H.
activeSpecies_
List<bool> activeSpecies_ protected
List of active species (active = true)
Definition at line 73 of file chemistryReductionMethod.H.
NsSimp_
label NsSimp_ protected
Number of active species.
Definition at line 76 of file chemistryReductionMethod.H.
nSpecie_
const label nSpecie_ protected
Number of species.
Definition at line 79 of file chemistryReductionMethod.H.
tolerance_
scalar tolerance_ protected
Tolerance for the mechanism reduction algorithm.
Definition at line 82 of file chemistryReductionMethod.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/chemistryModel/chemistryModel/TDACChemistryModel/reduction/chemistryReductionMethod/chemistryReductionMethod.H
src/thermophysicalModels/chemistryModel/chemistryModel/TDACChemistryModel/reduction/chemistryReductionMethod/chemistryReductionMethod.C
src/thermophysicalModels/chemistryModel/chemistryModel/TDACChemistryModel/reduction/chemistryReductionMethod/chemistryReductionMethodI.H
src/thermophysicalModels/chemistryModel/chemistryModel/TDACChemistryModel/reduction/chemistryReductionMethod/chemistryReductionMethodNew.C