OpenFOAM: heThermo< BasicThermo, MixtureType > Class Template Reference
heThermo< BasicThermo, MixtureType > Class Template Reference
Enthalpy/Internal energy for a mixture.
Public Member Functions
heThermo (const fvMesh &, const word &phaseName)
Construct from mesh.
heThermo (const fvMesh &, const dictionary &, const word &phaseName)
Construct from mesh and dictionary.
virtual ~heThermo ()
Destructor.
virtual MixtureType::basicMixtureType & composition ()
Return the compostion of the mixture.
virtual const MixtureType::basicMixtureType & composition () const
Return the compostion of the mixture.
virtual bool incompressible () const
Return true if the equation of state is incompressible.
virtual bool isochoric () const
Return true if the equation of state is isochoric.
virtual volScalarField & he ()
Enthalpy/Internal energy [J/kg].
virtual const volScalarField & he () const
Enthalpy/Internal energy [J/kg].
virtual tmp< volScalarField > he (const volScalarField &p, const volScalarField &T) const
Enthalpy/Internal energy.
virtual tmp< scalarField > he (const scalarField &p, const scalarField &T, const labelList &cells) const
Enthalpy/Internal energy for cell-set [J/kg].
virtual tmp< scalarField > he (const scalarField &p, const scalarField &T, const label patchi) const
Enthalpy/Internal energy for patch [J/kg].
virtual tmp< volScalarField > hc () const
Chemical enthalpy [J/kg].
virtual tmp< scalarField > THE (const scalarField &he, const scalarField &p, const scalarField &T0, const labelList &cells) const
Temperature from enthalpy/internal energy for cell-set.
virtual tmp< scalarField > THE (const scalarField &he, const scalarField &p, const scalarField &T0, const label patchi) const
Temperature from enthalpy/internal energy for patch.
virtual tmp< scalarField > Cp (const scalarField &p, const scalarField &T, const label patchi) const
Heat capacity at constant pressure for patch [J/kg/K].
virtual tmp< volScalarField > Cp () const
Heat capacity at constant pressure [J/kg/K].
virtual tmp< scalarField > Cv (const scalarField &p, const scalarField &T, const label patchi) const
Heat capacity at constant volume for patch [J/kg/K].
virtual tmp< volScalarField > Cv () const
Heat capacity at constant volume [J/kg/K].
virtual tmp< volScalarField > gamma () const
Gamma = Cp/Cv [].
virtual tmp< scalarField > gamma (const scalarField &p, const scalarField &T, const label patchi) const
Gamma = Cp/Cv for patch [].
virtual tmp< scalarField > Cpv (const scalarField &p, const scalarField &T, const label patchi) const
Heat capacity at constant pressure/volume for patch [J/kg/K].
virtual tmp< volScalarField > Cpv () const
Heat capacity at constant pressure/volume [J/kg/K].
virtual tmp< volScalarField > CpByCpv () const
Heat capacity ratio [].
virtual tmp< scalarField > CpByCpv (const scalarField &p, const scalarField &T, const label patchi) const
Heat capacity ratio for patch [].
virtual tmp< volScalarField > kappa () const
Thermal diffusivity for temperature of mixture [J/m/s/K].
virtual tmp< scalarField > kappa (const label patchi) const
Thermal diffusivity for temperature.
virtual tmp< volScalarField > kappaEff (const volScalarField &) const
Effective thermal diffusivity for temperature.
virtual tmp< scalarField > kappaEff (const scalarField &alphat, const label patchi) const
Effective thermal diffusivity for temperature.
virtual tmp< volScalarField > alphaEff (const volScalarField &alphat) const
Effective thermal diffusivity of mixture [kg/m/s].
virtual tmp< scalarField > alphaEff (const scalarField &alphat, const label patchi) const
Effective thermal diffusivity of mixture for patch [kg/m/s].
virtual bool read ()
Read thermophysical properties dictionary.
Protected Member Functions
void heBoundaryCorrection (volScalarField &he)
Correct the enthalpy/internal energy field boundaries.
Protected Attributes
volScalarField he_
Energy field.
Detailed Description
template<class BasicThermo, class MixtureType>
class Foam::heThermo< BasicThermo, MixtureType >
Enthalpy/Internal energy for a mixture.
Source files
heThermo.H
heThermo.C
Definition at line 49 of file heThermo.H.
Constructor & Destructor Documentation
heThermo() [1/2]
heThermo (const fvMesh & mesh, const word & phaseName)
Construct from mesh.
Definition at line 88 of file heThermo.C.
heThermo() [2/2]
heThermo (const fvMesh & mesh, const dictionary & dict, const word & phaseName)
Construct from mesh and dictionary.
Definition at line 121 of file heThermo.C.
~heThermo()
~heThermo () virtual
Destructor.
Definition at line 156 of file heThermo.C.
Member Function Documentation
heBoundaryCorrection()
void heBoundaryCorrection (volScalarField & he) protected
Correct the enthalpy/internal energy field boundaries.
Definition at line 34 of file heThermo.C.
composition() [1/2]
virtual MixtureType::basicMixtureType& composition () inline virtual
Return the compostion of the mixture.
Definition at line 110 of file heThermo.H.
composition() [2/2]
virtual const MixtureType::basicMixtureType& composition () const inline virtual
Return the compostion of the mixture.
Definition at line 117 of file heThermo.H.
incompressible()
virtual bool incompressible () const inline virtual
Return true if the equation of state is incompressible.
i.e. rho != f(p)
Definition at line 124 of file heThermo.H.
Referenced by heThermo< BasicSolidThermo, MixtureType >::composition().
isochoric()
virtual bool isochoric () const inline virtual
Return true if the equation of state is isochoric.
i.e. rho = const
Definition at line 131 of file heThermo.H.
Referenced by heThermo< BasicSolidThermo, MixtureType >::composition().
he() [1/5]
virtual volScalarField& he () inline virtual
Enthalpy/Internal energy [J/kg].
Non-const access allowed for transport equations
Definition at line 141 of file heThermo.H.
Referenced by heThermo< BasicSolidThermo, MixtureType >::composition(), heThermo< BasicSolidThermo, MixtureType >::he(), and heThermo< BasicSolidThermo, MixtureType >::~heThermo().
he() [2/5]
virtual const volScalarField& he () const inline virtual
Enthalpy/Internal energy [J/kg].
Definition at line 147 of file heThermo.H.
he() [3/5]
Foam::tmp< Foam::volScalarField > he (const volScalarField & p, const volScalarField & T) const virtual
Enthalpy/Internal energy.
for given pressure and temperature [J/kg]
Definition at line 164 of file heThermo.C.
he() [4/5]
Foam::tmp< Foam::scalarField > he (const scalarField & p, const scalarField & T, const labelList & cells) const virtual
Enthalpy/Internal energy for cell-set [J/kg].
Definition at line 221 of file heThermo.C.
he() [5/5]
Foam::tmp< Foam::scalarField > he (const scalarField & p, const scalarField & T, const label patchi) const virtual
Enthalpy/Internal energy for patch [J/kg].
Definition at line 241 of file heThermo.C.
hc()
Foam::tmp< Foam::volScalarField > hc () const virtual
Chemical enthalpy [J/kg].
Definition at line 262 of file heThermo.C.
Referenced by heThermo< BasicSolidThermo, MixtureType >::he().
THE() [1/2]
Foam::tmp< Foam::scalarField > THE (const scalarField & he, const scalarField & p, const scalarField & T0, const labelList & cells) const virtual
Temperature from enthalpy/internal energy for cell-set.
Definition at line 678 of file heThermo.C.
Referenced by heThermo< BasicSolidThermo, MixtureType >::CpByCpv(), heThermo< BasicSolidThermo, MixtureType >::he(), and heThermo< BasicSolidThermo, MixtureType >::THE().
THE() [2/2]
Foam::tmp< Foam::scalarField > THE (const scalarField & he, const scalarField & p, const scalarField & T0, const label patchi) const virtual
Temperature from enthalpy/internal energy for patch.
Definition at line 700 of file heThermo.C.
Cp() [1/2]
Foam::tmp< Foam::scalarField > Cp (const scalarField & p, const scalarField & T, const label patchi) const virtual
Heat capacity at constant pressure for patch [J/kg/K].
Definition at line 310 of file heThermo.C.
Cp() [2/2]
Foam::tmp< Foam::volScalarField > Cp () const virtual
Heat capacity at constant pressure [J/kg/K].
Definition at line 331 of file heThermo.C.
Referenced by heThermo< BasicSolidThermo, MixtureType >::hc(), and heThermo< BasicSolidThermo, MixtureType >::he().
Cv() [1/2]
Foam::tmp< Foam::scalarField > Cv (const scalarField & p, const scalarField & T, const label patchi) const virtual
Heat capacity at constant volume for patch [J/kg/K].
Definition at line 383 of file heThermo.C.
Cv() [2/2]
Foam::tmp< Foam::volScalarField > Cv () const virtual
Heat capacity at constant volume [J/kg/K].
Definition at line 404 of file heThermo.C.
Referenced by heThermo< BasicSolidThermo, MixtureType >::Cp(), and heThermo< BasicSolidThermo, MixtureType >::he().
gamma() [1/2]
Foam::tmp< Foam::volScalarField > gamma () const virtual
Gamma = Cp/Cv [].
Definition at line 473 of file heThermo.C.
Referenced by heThermo< BasicSolidThermo, MixtureType >::Cv(), and heThermo< BasicSolidThermo, MixtureType >::he().
gamma() [2/2]
Foam::tmp< Foam::scalarField > gamma (const scalarField & p, const scalarField & T, const label patchi) const virtual
Gamma = Cp/Cv for patch [].
Definition at line 452 of file heThermo.C.
Cpv() [1/2]
Foam::tmp< Foam::scalarField > Cpv (const scalarField & p, const scalarField & T, const label patchi) const virtual
Heat capacity at constant pressure/volume for patch [J/kg/K].
Definition at line 527 of file heThermo.C.
Cpv() [2/2]
Foam::tmp< Foam::volScalarField > Cpv () const virtual
Heat capacity at constant pressure/volume [J/kg/K].
Definition at line 548 of file heThermo.C.
Referenced by heThermo< BasicSolidThermo, MixtureType >::gamma(), and heThermo< BasicSolidThermo, MixtureType >::he().
CpByCpv() [1/2]
Foam::tmp< Foam::volScalarField > CpByCpv () const virtual
Heat capacity ratio [].
Definition at line 620 of file heThermo.C.
Referenced by heThermo< BasicSolidThermo, MixtureType >::Cpv(), and heThermo< BasicSolidThermo, MixtureType >::he().
CpByCpv() [2/2]
Foam::tmp< Foam::scalarField > CpByCpv (const scalarField & p, const scalarField & T, const label patchi) const virtual
Heat capacity ratio for patch [].
Definition at line 599 of file heThermo.C.
kappa() [1/2]
Foam::tmp< Foam::volScalarField > kappa () const virtual
Thermal diffusivity for temperature of mixture [J/m/s/K].
Definition at line 725 of file heThermo.C.
Referenced by heThermo< BasicSolidThermo, MixtureType >::he(), and heThermo< BasicSolidThermo, MixtureType >::kappa().
kappa() [2/2]
Foam::tmp< Foam::scalarField > kappa (const label patchi) const virtual
Thermal diffusivity for temperature.
of mixture for patch [J/m/s/K]
Definition at line 735 of file heThermo.C.
kappaEff() [1/2]
Foam::tmp< Foam::volScalarField > kappaEff (const volScalarField & alphat) const virtual
Effective thermal diffusivity for temperature.
of mixture [J/m/s/K]
Definition at line 752 of file heThermo.C.
Referenced by heThermo< BasicSolidThermo, MixtureType >::he(), heThermo< BasicSolidThermo, MixtureType >::kappa(), and heThermo< BasicSolidThermo, MixtureType >::kappaEff().
kappaEff() [2/2]
Foam::tmp< Foam::scalarField > kappaEff (const scalarField & alphat, const label patchi) const virtual
Effective thermal diffusivity for temperature.
of mixture for patch [J/m/s/K]
Definition at line 765 of file heThermo.C.
alphaEff() [1/2]
Foam::tmp< Foam::volScalarField > alphaEff (const volScalarField & alphat) const virtual
Effective thermal diffusivity of mixture [kg/m/s].
Definition at line 787 of file heThermo.C.
Referenced by heThermo< BasicSolidThermo, MixtureType >::alphaEff(), heThermo< BasicSolidThermo, MixtureType >::he(), and heThermo< BasicSolidThermo, MixtureType >::kappaEff().
alphaEff() [2/2]
Foam::tmp< Foam::scalarField > alphaEff (const scalarField & alphat, const label patchi) const virtual
Effective thermal diffusivity of mixture for patch [kg/m/s].
Definition at line 800 of file heThermo.C.
read()
bool read () virtual
Read thermophysical properties dictionary.
Definition at line 820 of file heThermo.C.
Referenced by heThermo< BasicSolidThermo, MixtureType >::he().
Member Data Documentation
he_
volScalarField he_ protected
Energy field.
Definition at line 59 of file heThermo.H.
Referenced by heThermo< BasicSolidThermo, MixtureType >::composition(), and heThermo< BasicSolidThermo, MixtureType >::he().
The documentation for this class was generated from the following files:
src/thermophysicalModels/basic/heThermo/heThermo.H
src/thermophysicalModels/basic/heThermo/heThermo.C