OpenFOAM: DAC< CompType, ThermoType > Class Template Reference
DAC< CompType, ThermoType > Class Template Reference
The Dynamic Adaptive Chemistry (DAC) method [1] simplify the chemistry using the matrix rAB defined by (DRGEP algorithm [2])
Public Member Functions
TypeName ("DAC")
Runtime type information.
DAC (const IOdictionary &dict, TDACChemistryModel< CompType, ThermoType > &chemistry)
Construct from components.
virtual ~DAC ()
Destructor.
virtual void reduceMechanism (const scalarField &c, const scalar T, const scalar p)
Reduce the mechanism.
Public Member Functions inherited from chemistryReductionMethod< CompType, ThermoType >
TypeName ("chemistryReductionMethod")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, chemistryReductionMethod, dictionary,(const IOdictionary &dict, TDACChemistryModel< CompType, ThermoType > &chemistry),(dict, chemistry))
chemistryReductionMethod (const IOdictionary &dict, TDACChemistryModel< CompType, ThermoType > &chemistry)
Construct from components.
virtual ~chemistryReductionMethod ()
Destructor.
bool active () const
Is mechanism reduction active?
bool log () const
Is performance data logging enabled?
const List< bool > & activeSpecies () const
Return the active species.
label NsSimp ()
Return the number of active species.
label nSpecie ()
Return the initial number of species.
scalar tolerance () const
Return the tolerance.
Additional Inherited Members
Static Public Member Functions inherited from chemistryReductionMethod< CompType, ThermoType >
static autoPtr< chemistryReductionMethod< CompType, ThermoType > > New (const IOdictionary &dict, TDACChemistryModel< CompType, ThermoType > &chemistry)
Protected Attributes inherited from chemistryReductionMethod< CompType, ThermoType >
const IOdictionary & dict_
const dictionary coeffsDict_
Dictionary that store the algorithm data.
Switch active_
Is mechanism reduction active?
Switch log_
Switch to select performance logging.
TDACChemistryModel< CompType, ThermoType > & chemistry_
List< bool > activeSpecies_
List of active species (active = true)
label NsSimp_
Number of active species.
const label nSpecie_
Number of species.
scalar tolerance_
Tolerance for the mechanism reduction algorithm.
Detailed Description
template<class CompType, class ThermoType>
class Foam::chemistryReductionMethods::DAC< CompType, ThermoType >
The Dynamic Adaptive Chemistry (DAC) method [1] simplify the chemistry using the matrix rAB defined by (DRGEP algorithm [2])
|sum_i=1->Nr vAi wi dBi| rAB = ————————— , max(PA, CA)
PA = sum_i=1->Nr (max (0, vAi wi)) -> production of species A
CA = sum_i=1->Nr (max (0, -vAi wi)) -> consumption of species A
where i is the reaction index, Nr the number of reactions, vAi is the net stoechiometric coefficient of species A in the ith reaction (vAi = v''-v') , wi is the progress variable of reaction i and dBi equals 1 if reaction i involves B and O otherwise. rAB show the error introduced to the production rates of A when B and all the reactions including it are removed. It is computed as in [3] so that the algorithm is O(Nr).
DAC uses a initial set of species that represents the major parts of the combustion mechanism, i.e. H2/O2, fuel decomposition and CO2 production. Usualy, it includes the fuel, HO2 and CO. Then it computes the dependance of these set to the other species. This is done by introducing R-value defined by
R_V0 (V) = max_SP(product(rij)),
where SP is the set of all possible paths leading from V0 to V and product(rij) is the chain product of the weights of the edges along the given path. The R-value for the initial set species is 1.
When the R-value of a species is larger than a user-defined tolerance then the species is included in the simplified mechanism. Otherwise, the species is removed along with all the reactions including it.
During this process, instead of looking over all species like described in [1], the algorithm implemented here creates dynamic list to retain the initialized edges only (see [3]).
References:
    [1] Liang, L., Stevens, J. G., & Farrell, J. T. (2009).
    A dynamic adaptive chemistry scheme for reactive flow computations.
    Proceedings of the Combustion Institute, 32(1), 527-534.
    [2] Pepiot-Desjardins, P., & Pitsch, H. (2008).
    An efficient error-propagation-based reduction method for large
    chemical kinetic mechanisms.
    Combustion and Flame, 154(1), 67-81.
    [3] Lu, T., & Law, C. K. (2006).
    Linear time reduction of large kinetic mechanisms with directed
    relation graph: n-Heptane and iso-octane.
    Combustion and Flame, 144(1), 24-36.
Source files
DAC.H
DAC.C
Definition at line 102 of file DAC.H.
Constructor & Destructor Documentation
DAC()
DAC (const IOdictionary & dict, TDACChemistryModel< CompType, ThermoType > & chemistry)
Construct from components.
Definition at line 32 of file DAC.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, dictionary::found(), Foam::Info, dictionary::lookup(), specieElement::name(), specieElement::nAtoms(), chemistryModel< CompType, ThermoType >::nSpecie(), Foam::readLabel(), readScalar, TDACChemistryModel< CompType, ThermoType >::specieComp(), dictionary::subDict(), dictionary::toc(), and TDACChemistryModel< CompType, ThermoType >::Y().
~DAC()
~DAC () virtual
Destructor.
Definition at line 263 of file DAC.C.
References DAC< CompType, ThermoType >::reduceMechanism().
Member Function Documentation
TypeName()
TypeName ("DAC< CompType, ThermoType >")
Runtime type information.
reduceMechanism()
void reduceMechanism (const scalarField & c, const scalar T, const scalar p) virtual
Reduce the mechanism.
Implements chemistryReductionMethod< CompType, ThermoType >.
Definition at line 272 of file DAC.C.
References Foam::constant::physicoChemical::c1, Foam::endl(), forAll, found, Foam::Info, Reaction< ReactionThermo >::lhs(), Foam::mag(), Foam::max(), p, FIFOStack< T >::pop(), FIFOStack< T >::push(), R, Reaction< ReactionThermo >::rhs(), s(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::setSize(), List< T >::setSize(), List< T >::size(), and T.
Referenced by DAC< CompType, ThermoType >::~DAC().
The documentation for this class was generated from the following files:
src/thermophysicalModels/chemistryModel/chemistryModel/TDACChemistryModel/reduction/DAC/DAC.H
src/thermophysicalModels/chemistryModel/chemistryModel/TDACChemistryModel/reduction/DAC/DAC.C