OpenFOAM: chemistryTabulationMethod< CompType, ThermoType > Class Template Reference
chemistryTabulationMethod< CompType, ThermoType > Class Template Reference abstract
An abstract class for chemistry tabulation.
Public Member Functions
TypeName ("chemistryTabulationMethod")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, chemistryTabulationMethod, dictionary,(const dictionary &dict, TDACChemistryModel< CompType, ThermoType > &chemistry),(dict, chemistry))
chemistryTabulationMethod (const dictionary &dict, TDACChemistryModel< CompType, ThermoType > &chemistry)
Construct from components.
virtual ~chemistryTabulationMethod ()
Destructor.
bool active ()
bool log ()
scalar tolerance () const
virtual label size ()=0
virtual void writePerformance ()=0
virtual bool retrieve (const scalarField &phiQ, scalarField &RphiQ)=0
virtual bool add (const scalarField &phiQ, const scalarField &RphiQ, const scalar rho)=0
virtual bool update ()=0
Static Public Member Functions
static autoPtr< chemistryTabulationMethod > New (const IOdictionary &dict, TDACChemistryModel< CompType, ThermoType > &chemistry)
Protected Attributes
const dictionary & dict_
const dictionary coeffsDict_
Switch active_
Is tabulation active?
Switch log_
Switch to select performance logging.
TDACChemistryModel< CompType, ThermoType > & chemistry_
scalar tolerance_
Detailed Description
template<class CompType, class ThermoType>
class Foam::chemistryTabulationMethod< CompType, ThermoType >
An abstract class for chemistry tabulation.
Source files
chemistryTabulationMethod.H
chemistryTabulationMethod.C
Definition at line 57 of file chemistryTabulationMethod.H.
Constructor & Destructor Documentation
chemistryTabulationMethod()
chemistryTabulationMethod (const dictionary & dict, TDACChemistryModel< CompType, ThermoType > & chemistry)
Construct from components.
Definition at line 33 of file chemistryTabulationMethod.C.
References chemistryTabulationMethod< CompType, ThermoType >::~chemistryTabulationMethod().
~chemistryTabulationMethod()
~chemistryTabulationMethod () virtual
Destructor.
Definition at line 51 of file chemistryTabulationMethod.C.
Referenced by chemistryTabulationMethod< CompType, ThermoType >::chemistryTabulationMethod().
Member Function Documentation
TypeName()
TypeName ("chemistryTabulationMethod< CompType, ThermoType >")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , chemistryTabulationMethod< CompType, ThermoType > , dictionary , (const dictionary &dict, TDACChemistryModel< CompType, ThermoType > &chemistry) , (dict, chemistry))
New()
Foam::autoPtr< Foam::chemistryTabulationMethod< CompType, ThermoType > > New (const IOdictionary & dict, TDACChemistryModel< CompType, ThermoType > & chemistry) static
Definition at line 34 of file chemistryTabulationMethodNew.C.
References chemistry, TimePaths::constant(), IOobject::db(), dict, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::FatalIOError, FatalIOErrorInFunction, dictionary::isDict(), dictionary::lookup(), dictionary::subDict(), and objectRegistry::time().
active()
bool active () inline
Definition at line 122 of file chemistryTabulationMethod.H.
References chemistryTabulationMethod< CompType, ThermoType >::active_.
Referenced by ISAT< CompType, ThermoType >::~ISAT().
log()
bool log () inline
Definition at line 127 of file chemistryTabulationMethod.H.
References chemistryTabulationMethod< CompType, ThermoType >::log_.
tolerance()
scalar tolerance () const inline
Definition at line 132 of file chemistryTabulationMethod.H.
References chemistryTabulationMethod< CompType, ThermoType >::add(), chemistryTabulationMethod< CompType, ThermoType >::retrieve(), rho, chemistryTabulationMethod< CompType, ThermoType >::size(), chemistryTabulationMethod< CompType, ThermoType >::tolerance_, chemistryTabulationMethod< CompType, ThermoType >::update(), and chemistryTabulationMethod< CompType, ThermoType >::writePerformance().
size()
virtual label size () pure virtual
Implemented in ISAT< CompType, ThermoType >, and none< CompType, ThermoType >.
Referenced by chemistryTabulationMethod< CompType, ThermoType >::tolerance().
writePerformance()
virtual void writePerformance () pure virtual
Implemented in ISAT< CompType, ThermoType >, and none< CompType, ThermoType >.
Referenced by chemistryTabulationMethod< CompType, ThermoType >::tolerance().
retrieve()
virtual bool retrieve (const scalarField & phiQ, scalarField & RphiQ) pure virtual
Implemented in ISAT< CompType, ThermoType >, and none< CompType, ThermoType >.
Referenced by chemistryTabulationMethod< CompType, ThermoType >::tolerance().
add()
virtual bool add (const scalarField & phiQ, const scalarField & RphiQ, const scalar rho) pure virtual
Implemented in ISAT< CompType, ThermoType >, and none< CompType, ThermoType >.
Referenced by chemistryTabulationMethod< CompType, ThermoType >::tolerance().
update()
virtual bool update () pure virtual
Implemented in ISAT< CompType, ThermoType >, and none< CompType, ThermoType >.
Referenced by chemistryTabulationMethod< CompType, ThermoType >::tolerance().
Member Data Documentation
dict_
const dictionary& dict_ protected
Definition at line 62 of file chemistryTabulationMethod.H.
coeffsDict_
const dictionary coeffsDict_ protected
Definition at line 64 of file chemistryTabulationMethod.H.
active_
Switch active_ protected
Is tabulation active?
Definition at line 67 of file chemistryTabulationMethod.H.
Referenced by chemistryTabulationMethod< CompType, ThermoType >::active().
log_
Switch log_ protected
Switch to select performance logging.
Definition at line 70 of file chemistryTabulationMethod.H.
Referenced by chemistryTabulationMethod< CompType, ThermoType >::log().
chemistry_
TDACChemistryModel<CompType, ThermoType>& chemistry_ protected
Definition at line 72 of file chemistryTabulationMethod.H.
tolerance_
scalar tolerance_ protected
Definition at line 74 of file chemistryTabulationMethod.H.
Referenced by chemistryTabulationMethod< CompType, ThermoType >::tolerance().
The documentation for this class was generated from the following files:
src/thermophysicalModels/chemistryModel/chemistryModel/TDACChemistryModel/tabulation/chemistryTabulationMethod/chemistryTabulationMethod.H
src/thermophysicalModels/chemistryModel/chemistryModel/TDACChemistryModel/tabulation/chemistryTabulationMethod/chemistryTabulationMethod.C
src/thermophysicalModels/chemistryModel/chemistryModel/TDACChemistryModel/tabulation/chemistryTabulationMethod/chemistryTabulationMethodNew.C