OpenFOAM: none< CompType, ThermoType > Class Template Reference
none< CompType, ThermoType > Class Template Reference
Public Member Functions
TypeName ("none")
Runtime type information.
none (const dictionary &chemistryProperties, TDACChemistryModel< CompType, ThermoType > &chemistry)
Construct from dictionary.
virtual ~none ()
virtual label size ()
Return the size of the binary tree.
virtual void writePerformance ()
virtual bool retrieve (const Foam::scalarField &phiq, scalarField &Rphiq)
Find the closest stored leaf of phiQ and store the result in.
virtual bool add (const scalarField &phiq, const scalarField &Rphiq, const scalar rho)
virtual bool update ()
Public Member Functions inherited from chemistryTabulationMethod< CompType, ThermoType >
TypeName ("chemistryTabulationMethod")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, chemistryTabulationMethod, dictionary,(const dictionary &dict, TDACChemistryModel< CompType, ThermoType > &chemistry),(dict, chemistry))
chemistryTabulationMethod (const dictionary &dict, TDACChemistryModel< CompType, ThermoType > &chemistry)
Construct from components.
virtual ~chemistryTabulationMethod ()
Destructor.
bool active ()
bool log ()
scalar tolerance () const
Additional Inherited Members
Static Public Member Functions inherited from chemistryTabulationMethod< CompType, ThermoType >
static autoPtr< chemistryTabulationMethod > New (const IOdictionary &dict, TDACChemistryModel< CompType, ThermoType > &chemistry)
Protected Attributes inherited from chemistryTabulationMethod< CompType, ThermoType >
const dictionary & dict_
const dictionary coeffsDict_
Switch active_
Is tabulation active?
Switch log_
Switch to select performance logging.
TDACChemistryModel< CompType, ThermoType > & chemistry_
scalar tolerance_
Detailed Description
template<class CompType, class ThermoType>
class Foam::chemistryTabulationMethods::none< CompType, ThermoType >
Definition at line 47 of file noChemistryTabulation.H.
Constructor & Destructor Documentation
none()
none (const dictionary & chemistryProperties, TDACChemistryModel< CompType, ThermoType > & chemistry)
Construct from dictionary.
Definition at line 32 of file noChemistryTabulation.C.
~none()
~none () virtual
Definition at line 50 of file noChemistryTabulation.C.
Member Function Documentation
TypeName()
TypeName ("none< CompType, ThermoType >")
Runtime type information.
size()
virtual label size () inline virtual
Return the size of the binary tree.
Implements chemistryTabulationMethod< CompType, ThermoType >.
Definition at line 79 of file noChemistryTabulation.H.
References NotImplemented.
writePerformance()
virtual void writePerformance () inline virtual
Implements chemistryTabulationMethod< CompType, ThermoType >.
Definition at line 85 of file noChemistryTabulation.H.
References NotImplemented, and none< CompType, ThermoType >::retrieve().
retrieve()
virtual bool retrieve (const Foam::scalarField & phiq, scalarField & Rphiq) inline virtual
Find the closest stored leaf of phiQ and store the result in.
RphiQ or return false.
Implements chemistryTabulationMethod< CompType, ThermoType >.
Definition at line 93 of file noChemistryTabulation.H.
References none< CompType, ThermoType >::add(), and NotImplemented.
Referenced by none< CompType, ThermoType >::writePerformance().
add()
virtual bool add (const scalarField & phiq, const scalarField & Rphiq, const scalar rho) inline virtual
Implements chemistryTabulationMethod< CompType, ThermoType >.
Definition at line 107 of file noChemistryTabulation.H.
References NotImplemented.
Referenced by none< CompType, ThermoType >::retrieve().
update()
virtual bool update () inline virtual
Implements chemistryTabulationMethod< CompType, ThermoType >.
Definition at line 117 of file noChemistryTabulation.H.
References NotImplemented.
The documentation for this class was generated from the following files:
src/thermophysicalModels/chemistryModel/chemistryModel/TDACChemistryModel/tabulation/noChemistryTabulation/noChemistryTabulation.H
src/thermophysicalModels/chemistryModel/chemistryModel/TDACChemistryModel/tabulation/noChemistryTabulation/noChemistryTabulation.C