OpenFOAM: RaviPetersen Class Reference
RaviPetersen Class Reference
Laminar flame speed obtained from Ravi and Petersen's correlation.
Public Member Functions
TypeName ("RaviPetersen")
Runtime type information.
RaviPetersen (const dictionary &, const psiuReactionThermo &)
Construct from dictionary and psiuReactionThermo.
virtual ~RaviPetersen ()
Destructor.
tmp< volScalarField > operator() () const
Return the laminar flame speed [m/s].
Public Member Functions inherited from laminarFlameSpeed
TypeName ("laminarFlameSpeed")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, laminarFlameSpeed, dictionary,(const dictionary &dict, const psiuReactionThermo &ct),(dict, ct))
laminarFlameSpeed (const dictionary &, const psiuReactionThermo &)
Construct from dictionary and psiuReactionThermo.
virtual ~laminarFlameSpeed ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from laminarFlameSpeed
static autoPtr< laminarFlameSpeed > New (const psiuReactionThermo &)
Protected Attributes inherited from laminarFlameSpeed
const psiuReactionThermo & psiuReactionThermo_
word fuel_
Fuel.
scalar equivalenceRatio_
Equivalence ratio of a homogeneous mixture.
Detailed Description
Laminar flame speed obtained from Ravi and Petersen's correlation.
The correlation for the laminar flame speed is of the following form:
Where is the equivalence ratio, and and are polynomial coefficients given for a number of pressure and equivalence ratio points.
Source files
RaviPetersen.H
RaviPetersen.C
Definition at line 61 of file RaviPetersen.H.
Constructor & Destructor Documentation
RaviPetersen()
RaviPetersen (const dictionary & dict, const psiuReactionThermo & ct)
Construct from dictionary and psiuReactionThermo.
Definition at line 50 of file RaviPetersen.C.
~RaviPetersen()
~RaviPetersen () virtual
Destructor.
Definition at line 72 of file RaviPetersen.C.
References Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, UList< T >::first(), forAll, UList< T >::last(), Foam::log(), Foam::max(), Foam::name(), p, Foam::pow(), s(), List< T >::size(), Foam::fvc::Su(), x, and y.
Member Function Documentation
TypeName()
TypeName ("RaviPetersen")
Runtime type information.
operator()()
Foam::tmp< Foam::volScalarField > operator() () const virtual
Return the laminar flame speed [m/s].
Implements laminarFlameSpeed.
Definition at line 293 of file RaviPetersen.C.
References IOobject::db(), Foam::dimless, Foam::dimVelocity, forAll, Foam::max(), DimensionedField< Type, GeoMesh >::mesh(), IOobject::NO_READ, IOobject::NO_WRITE, tmp< T >::ref(), IOobject::time(), and Time::timeName().
The documentation for this class was generated from the following files:
src/thermophysicalModels/laminarFlameSpeed/RaviPetersen/RaviPetersen.H
src/thermophysicalModels/laminarFlameSpeed/RaviPetersen/RaviPetersen.C