OpenFOAM: Gulders Class Reference
Gulders Class Reference
Laminar flame speed obtained from Gulder's correlation.
Public Member Functions
TypeName ("Gulders")
Runtime type information.
Gulders (const dictionary &, const psiuReactionThermo &)
Construct from dictionary and psiuReactionThermo.
virtual ~Gulders ()
Destructor.
tmp< volScalarField > operator() () const
Return the laminar flame speed [m/s].
Public Member Functions inherited from laminarFlameSpeed
TypeName ("laminarFlameSpeed")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, laminarFlameSpeed, dictionary,(const dictionary &dict, const psiuReactionThermo &ct),(dict, ct))
laminarFlameSpeed (const dictionary &, const psiuReactionThermo &)
Construct from dictionary and psiuReactionThermo.
virtual ~laminarFlameSpeed ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from laminarFlameSpeed
static autoPtr< laminarFlameSpeed > New (const psiuReactionThermo &)
Protected Attributes inherited from laminarFlameSpeed
const psiuReactionThermo & psiuReactionThermo_
word fuel_
Fuel.
scalar equivalenceRatio_
Equivalence ratio of a homogeneous mixture.
Detailed Description
Laminar flame speed obtained from Gulder's correlation.
Source files
Gulders.H
Gulders.C
Definition at line 50 of file Gulders.H.
Constructor & Destructor Documentation
Gulders()
Gulders (const dictionary & dict, const psiuReactionThermo & ct)
Construct from dictionary and psiuReactionThermo.
Definition at line 50 of file Gulders.C.
~Gulders()
~Gulders () virtual
Destructor.
Definition at line 69 of file Gulders.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), IOobject::db(), Foam::dimVelocity, Foam::exp(), forAll, DimensionedField< Type, GeoMesh >::mesh(), IOobject::NO_READ, IOobject::NO_WRITE, p, patchi, phi, Foam::pow(), pRef, tmp< T >::ref(), Foam::sqr(), IOobject::time(), and Time::timeName().
Member Function Documentation
TypeName()
TypeName ("Gulders")
Runtime type information.
operator()()
Foam::tmp< Foam::volScalarField > operator() () const virtual
Return the laminar flame speed [m/s].
Implements laminarFlameSpeed.
Definition at line 213 of file Gulders.C.
References Foam::max().
The documentation for this class was generated from the following files:
src/thermophysicalModels/laminarFlameSpeed/Gulders/Gulders.H
src/thermophysicalModels/laminarFlameSpeed/Gulders/Gulders.C