OpenFOAM: EulerImplicit< ChemistryModel > Class Template Reference
EulerImplicit< ChemistryModel > Class Template Reference
An Euler implicit solver for chemistry.
Public Member Functions
TypeName ("EulerImplicit")
Runtime type information.
EulerImplicit (const fvMesh &mesh, const word &phaseName)
Construct from mesh and phase name.
virtual ~EulerImplicit ()
Destructor.
void updateRRInReactionI (const label index, const scalar pr, const scalar pf, const scalar corr, const label lRef, const label rRef, const scalar p, const scalar T, simpleMatrix< scalar > &RR) const
virtual void solve (scalarField &c, scalar &T, scalar &p, scalar &deltaT, scalar &subDeltaT) const
Update the concentrations and return the chemical time.
Public Member Functions inherited from chemistrySolver< ChemistryModel >
chemistrySolver (const fvMesh &mesh, const word &phaseName)
Construct from components and phase name.
virtual ~chemistrySolver ()
Destructor.
Detailed Description
template<class ChemistryModel>
class Foam::EulerImplicit< ChemistryModel >
An Euler implicit solver for chemistry.
Source files
EulerImplicit.H
EulerImplicit.C
Definition at line 49 of file EulerImplicit.H.
Constructor & Destructor Documentation
EulerImplicit()
EulerImplicit (const fvMesh & mesh, const word & phaseName)
Construct from mesh and phase name.
Definition at line 34 of file EulerImplicit.C.
~EulerImplicit()
~EulerImplicit () virtual
Destructor.
Definition at line 50 of file EulerImplicit.C.
References EulerImplicit< ChemistryModel >::updateRRInReactionI().
Member Function Documentation
TypeName()
TypeName ("EulerImplicit< ChemistryModel >")
Runtime type information.
updateRRInReactionI()
void updateRRInReactionI (const label index, const scalar pr, const scalar pf, const scalar corr, const label lRef, const label rRef, const scalar p, const scalar T, simpleMatrix< scalar > & RR) const
Definition at line 58 of file EulerImplicit.C.
References forAll, Reaction< ReactionThermo >::lhs(), R, Reaction< ReactionThermo >::rhs(), s(), and EulerImplicit< ChemistryModel >::solve().
Referenced by EulerImplicit< ChemistryModel >::~EulerImplicit().
solve()
void solve (scalarField & c, scalar & T, scalar & p, scalar & deltaT, scalar & subDeltaT) const virtual
Update the concentrations and return the chemical time.
Implements chemistrySolver< ChemistryModel >.
Definition at line 93 of file EulerImplicit.C.
References Foam::constant::electromagnetic::e, forAll, simpleMatrix< Type >::LUsolve(), Foam::max(), Foam::min(), mixture, nSpecie, Foam::constant::thermodynamic::RR, simpleMatrix< Type >::source(), and Foam::sum().
Referenced by EulerImplicit< ChemistryModel >::updateRRInReactionI().
The documentation for this class was generated from the following files:
src/thermophysicalModels/chemistryModel/chemistrySolver/EulerImplicit/EulerImplicit.H
src/thermophysicalModels/chemistryModel/chemistrySolver/EulerImplicit/EulerImplicit.C