OpenFOAM: binaryTree< CompType, ThermoType > Class Template Reference
binaryTree< CompType, ThermoType > Class Template Reference
Data storage of the chemistryOnLineLibrary according to a binary tree structure.
Public Types
typedef binaryNode< CompType, ThermoType > bn
typedef chemPointISAT< CompType, ThermoType > chP
Public Member Functions
binaryTree (TDACChemistryModel< CompType, ThermoType > &chemistry, dictionary coeffsDict)
Constructors.
label size ()
Member functions.
label depth (bn *subTreeRoot)
Computes iteratively the depth of the subTree.
label depth ()
bn * root ()
label maxNLeafs ()
void insertNewLeaf (const scalarField &phiq, const scalarField &Rphiq, const scalarSquareMatrix &A, const scalarField &scaleFactor, const scalar &epsTol, const label nCols, chP *&phi0)
void binaryTreeSearch (const scalarField &phiq, bn *node, chP *&nearest)
bool secondaryBTSearch (const scalarField &phiq, chP *&x)
void deleteLeaf (chP *&phi0)
Delete a leaf from the binary tree and reshape the binary tree for.
void balance ()
Cheap balance function.
void deleteAllNode ()
chP * treeMin (bn *subTreeRoot)
chP * treeMin ()
chP * treeSuccessor (chP *x)
void clear ()
Removes every entries of the tree and delete the associated objects.
bool isFull ()
ListFull.
Detailed Description
template<class CompType, class ThermoType>
class Foam::binaryTree< CompType, ThermoType >
Data storage of the chemistryOnLineLibrary according to a binary tree structure.
0 (root node) / \ 0 0 / \ / \ L R L 0 / \ L R
L: leafLeft_ R: leafRight_
Definition at line 57 of file binaryTree.H.
Member Typedef Documentation
bn
typedef binaryNode<CompType, ThermoType> bn
Definition at line 61 of file binaryTree.H.
chP
typedef chemPointISAT<CompType, ThermoType> chP
Definition at line 62 of file binaryTree.H.
Constructor & Destructor Documentation
binaryTree()
binaryTree (TDACChemistryModel< CompType, ThermoType > & chemistry, dictionary coeffsDict)
Constructors.
Construct from dictionary and chemistryOnLineLibrary
Definition at line 344 of file binaryTree.C.
Member Function Documentation
size()
label size () inline
Member functions.
Definition at line 132 of file binaryTree.H.
References binaryTree< CompType, ThermoType >::depth().
Referenced by ISAT< CompType, ThermoType >::size().
depth() [1/2]
Foam::label depth (bn * subTreeRoot)
Computes iteratively the depth of the subTree.
Definition at line 361 of file binaryTree.C.
References binaryTree< CompType, ThermoType >::insertNewLeaf(), Foam::max(), binaryNode< CompType, ThermoType >::nodeLeft(), and binaryNode< CompType, ThermoType >::nodeRight().
depth() [2/2]
label depth () inline
Definition at line 140 of file binaryTree.H.
Referenced by binaryTree< CompType, ThermoType >::size().
root()
bn* root () inline
Definition at line 145 of file binaryTree.H.
maxNLeafs()
label maxNLeafs () inline
Definition at line 150 of file binaryTree.H.
References binaryTree< CompType, ThermoType >::balance(), binaryTree< CompType, ThermoType >::binaryTreeSearch(), binaryTree< CompType, ThermoType >::deleteLeaf(), binaryTree< CompType, ThermoType >::insertNewLeaf(), Foam::constant::electromagnetic::phi0, binaryTree< CompType, ThermoType >::secondaryBTSearch(), and x.
insertNewLeaf()
void insertNewLeaf (const scalarField & phiq, const scalarField & Rphiq, const scalarSquareMatrix & A, const scalarField & scaleFactor, const scalar & epsTol, const label nCols, chP *& phi0)
Definition at line 381 of file binaryTree.C.
References binaryTree< CompType, ThermoType >::binaryTreeSearch(), Foam::deleteDemandDrivenData(), and chemPointISAT< CompType, ThermoType >::node().
Referenced by binaryTree< CompType, ThermoType >::depth(), and binaryTree< CompType, ThermoType >::maxNLeafs().
binaryTreeSearch()
void binaryTreeSearch (const scalarField & phiq, bn * node, chP *& nearest)
Definition at line 464 of file binaryTree.C.
References binaryNode< CompType, ThermoType >::a(), binaryNode< CompType, ThermoType >::leafLeft(), binaryNode< CompType, ThermoType >::leafRight(), binaryNode< CompType, ThermoType >::nodeLeft(), binaryNode< CompType, ThermoType >::nodeRight(), binaryTree< CompType, ThermoType >::secondaryBTSearch(), List< T >::size(), and binaryNode< CompType, ThermoType >::v().
Referenced by binaryTree< CompType, ThermoType >::insertNewLeaf(), and binaryTree< CompType, ThermoType >::maxNLeafs().
secondaryBTSearch()
bool secondaryBTSearch (const scalarField & phiq, chP *& x)
Definition at line 518 of file binaryTree.C.
References chemPointISAT< CompType, ThermoType >::inEOA(), chemPointISAT< CompType, ThermoType >::node(), and binaryNode< CompType, ThermoType >::parent().
Referenced by binaryTree< CompType, ThermoType >::binaryTreeSearch(), and binaryTree< CompType, ThermoType >::maxNLeafs().
deleteLeaf()
void deleteLeaf (chP *& phi0)
Delete a leaf from the binary tree and reshape the binary tree for.
the following binary tree search Return the index in the nodeList of the removed node (-1 when no node)
Definition at line 575 of file binaryTree.C.
References Foam::deleteDemandDrivenData(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, chemPointISAT< CompType, ThermoType >::node(), binaryNode< CompType, ThermoType >::parent(), and x.
Referenced by binaryTree< CompType, ThermoType >::maxNLeafs().
balance()
void balance ()
Cheap balance function.
This function just roughly separate the space in two parts with a hyperplane which separate the two extreme chemPoint in the direction of the maximum the variance Then, it repopulate the tree with this hyperplane stored at the root and by inserting the chemPoint in increasing order of value in that direction
Definition at line 639 of file binaryTree.C.
References forAll, SortableList< T >::indices(), chemPointISAT< CompType, ThermoType >::node(), chemPointISAT< CompType, ThermoType >::phi(), Foam::constant::electromagnetic::phi0, List< T >::size(), SortableList< T >::sort(), Foam::sqr(), and x.
Referenced by binaryTree< CompType, ThermoType >::maxNLeafs().
deleteAllNode()
void deleteAllNode () inline
Definition at line 213 of file binaryTree.H.
References binaryTree< CompType, ThermoType >::treeMin().
treeMin() [1/2]
Foam::chemPointISAT< CompType, ThermoType > * treeMin (bn * subTreeRoot)
Definition at line 730 of file binaryTree.C.
References binaryNode< CompType, ThermoType >::leafLeft(), and binaryNode< CompType, ThermoType >::nodeLeft().
treeMin() [2/2]
chP* treeMin () inline
Definition at line 220 of file binaryTree.H.
References binaryTree< CompType, ThermoType >::clear(), binaryTree< CompType, ThermoType >::isFull(), and binaryTree< CompType, ThermoType >::treeSuccessor().
Referenced by binaryTree< CompType, ThermoType >::deleteAllNode().
treeSuccessor()
Foam::chemPointISAT< CompType, ThermoType > * treeSuccessor (chP * x)
Definition at line 749 of file binaryTree.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, chemPointISAT< CompType, ThermoType >::node(), and binaryNode< CompType, ThermoType >::parent().
Referenced by binaryTree< CompType, ThermoType >::treeMin().
clear()
void clear ()
Removes every entries of the tree and delete the associated objects.
Definition at line 801 of file binaryTree.C.
Referenced by binaryTree< CompType, ThermoType >::treeMin().
isFull()
bool isFull ()
ListFull.
Definition at line 815 of file binaryTree.C.
Referenced by binaryTree< CompType, ThermoType >::treeMin().
The documentation for this class was generated from the following files:
src/thermophysicalModels/chemistryModel/chemistryModel/TDACChemistryModel/tabulation/ISAT/binaryTree/binaryTree.H
src/thermophysicalModels/chemistryModel/chemistryModel/TDACChemistryModel/tabulation/ISAT/binaryTree/binaryTree.C