OpenFOAM: liquidProperties Class Reference
liquidProperties Class Reference
The thermophysical properties of a liquidProperties.
Public Member Functions
TypeName ("liquidProperties")
declareRunTimeSelectionTable (autoPtr, liquidProperties,,(),())
declareRunTimeSelectionTable (autoPtr, liquidProperties, Istream,(Istream &is),(is))
declareRunTimeSelectionTable (autoPtr, liquidProperties, dictionary,(const dictionary &dict),(dict))
liquidProperties (scalar W, scalar Tc, scalar Pc, scalar Vc, scalar Zc, scalar Tt, scalar Pt, scalar Tb, scalar dipm, scalar omega, scalar delta)
Construct from components.
liquidProperties (Istream &is)
Construct from Istream.
liquidProperties (const dictionary &dict)
Construct from dictionary.
liquidProperties (const liquidProperties &liq)
Construct copy.
virtual autoPtr< liquidProperties > clone () const
Construct and return clone.
virtual ~liquidProperties ()
Destructor.
scalar W () const
Molecular weight [kg/kmol].
scalar Tc () const
Critical temperature [K].
scalar Pc () const
Critical pressure [Pa].
scalar Vc () const
Critical volume [m^3/kmol].
scalar Zc () const
Critical compressibilty factor.
scalar Tt () const
Triple point temperature [K].
scalar Pt () const
Triple point pressure [Pa].
scalar Tb () const
Normal boiling temperature [K].
scalar dipm () const
Dipole moment [].
scalar omega () const
Pitzer's ascentric factor [].
scalar delta () const
Solubility parameter [(J/m^3)^(1/2)].
virtual scalar rho (scalar p, scalar T) const
Liquid rho [kg/m^3].
virtual scalar pv (scalar p, scalar T) const
Vapour pressure [Pa].
virtual scalar hl (scalar p, scalar T) const
Heat of vapourisation [J/kg].
virtual scalar Cp (scalar p, scalar T) const
Liquid heat capacity [J/(kg K)].
virtual scalar h (scalar p, scalar T) const
Liquid enthalpy [J/kg] - reference to 298.15 K.
virtual scalar Cpg (scalar p, scalar T) const
Ideal gas heat capacity [J/(kg K)].
virtual scalar mu (scalar p, scalar T) const
Liquid viscosity [Pa s].
virtual scalar mug (scalar p, scalar T) const
Vapour viscosity [Pa s].
virtual scalar K (scalar p, scalar T) const
Liquid thermal conductivity [W/(m K)].
virtual scalar Kg (scalar p, scalar T) const
Vapour thermal conductivity [W/(m K)].
virtual scalar sigma (scalar p, scalar T) const
Surface tension [N/m].
virtual scalar D (scalar p, scalar T) const
Vapour diffussivity [m2/s].
virtual scalar D (scalar p, scalar T, scalar Wb) const
Vapour diffussivity [m2/s] with specified binary pair.
virtual scalar pvInvert (scalar p) const
Invert the vapour pressure relationship to retrieve the.
virtual void writeData (Ostream &os) const
Write the function coefficients.
Static Public Member Functions
static autoPtr< liquidProperties > New (Istream &is)
Return a pointer to a new liquidProperties created from input.
static autoPtr< liquidProperties > New (const dictionary &dict)
Return a pointer to a new liquidProperties created from dictionary.
Friends
Ostream & operator<< (Ostream &os, const liquidProperties &l)
Ostream Operator.
Detailed Description
The thermophysical properties of a liquidProperties.
Source files
liquidProperties.H
liquidProperties.C
Definition at line 53 of file liquidProperties.H.
Constructor & Destructor Documentation
liquidProperties() [1/4]
liquidProperties (scalar W, scalar Tc, scalar Pc, scalar Vc, scalar Zc, scalar Tt, scalar Pt, scalar Tb, scalar dipm, scalar omega, scalar delta)
Construct from components.
Definition at line 43 of file liquidProperties.C.
Referenced by liquidProperties::clone(), and liquidProperties::New().
liquidProperties() [2/4]
liquidProperties (Istream & is)
Construct from Istream.
Definition at line 71 of file liquidProperties.C.
liquidProperties() [3/4]
liquidProperties (const dictionary & dict)
Construct from dictionary.
Definition at line 87 of file liquidProperties.C.
liquidProperties() [4/4]
liquidProperties (const liquidProperties & liq)
Construct copy.
Definition at line 103 of file liquidProperties.C.
~liquidProperties()
virtual ~liquidProperties () inline virtual
Destructor.
Definition at line 170 of file liquidProperties.H.
References liquidProperties::Cp(), liquidProperties::Cpg(), liquidProperties::D(), liquidProperties::delta(), liquidProperties::dipm(), liquidProperties::h(), liquidProperties::hl(), liquidProperties::K(), liquidProperties::Kg(), liquidProperties::mu(), liquidProperties::mug(), liquidProperties::omega(), p, liquidProperties::Pc(), liquidProperties::Pt(), liquidProperties::pv(), liquidProperties::pvInvert(), liquidProperties::rho(), liquidProperties::sigma(), Foam::T(), liquidProperties::Tb(), liquidProperties::Tc(), liquidProperties::Tt(), liquidProperties::Vc(), liquidProperties::W(), liquidProperties::writeData(), and liquidProperties::Zc().
Member Function Documentation
TypeName()
TypeName ("liquidProperties")
declareRunTimeSelectionTable() [1/3]
declareRunTimeSelectionTable (autoPtr , liquidProperties , () , ())
declareRunTimeSelectionTable() [2/3]
declareRunTimeSelectionTable (autoPtr , liquidProperties , Istream , (Istream &is) , (is))
declareRunTimeSelectionTable() [3/3]
declareRunTimeSelectionTable (autoPtr , liquidProperties , dictionary , (const dictionary &dict) , (dict))
clone()
virtual autoPtr<liquidProperties> clone () const inline virtual
Construct and return clone.
Reimplemented in IDEA, aC10H7CH3, Ar, bC10H7CH3, C10H22, C12H26, C13H28, C14H30, C16H34, C2H5OH, C2H6, C2H6O, C3H6O, C3H8, C4H10O, C6H14, C6H6, C7H16, C7H8, C8H18, C9H20, CH3OH, CH4N2O, IC8H18, MB, N2, C8H10, H2O, iC3H8O, and nC3H8O.
Definition at line 154 of file liquidProperties.H.
References liquidProperties::liquidProperties(), and liquidProperties::New().
New() [1/2]
Foam::autoPtr< Foam::liquidProperties > New (Istream & is) static
Return a pointer to a new liquidProperties created from input.
Definition at line 121 of file liquidProperties.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, InfoInFunction, liquidProperties::liquidProperties(), and Foam::nl.
Referenced by liquidProperties::clone().
New() [2/2]
Foam::autoPtr< Foam::liquidProperties > New (const dictionary & dict) static
Return a pointer to a new liquidProperties created from dictionary.
Definition at line 166 of file liquidProperties.C.
References Foam::abort(), dictionaryName::dictName(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, InfoInFunction, dictionary::lookup(), Foam::nl, and dictionary::subDict().
W()
Foam::scalar W () const inline
Molecular weight [kg/kmol].
Definition at line 26 of file liquidPropertiesI.H.
Referenced by liquidFilmThermo::W(), and liquidProperties::~liquidProperties().
Tc()
Foam::scalar Tc () const inline
Critical temperature [K].
Definition at line 32 of file liquidPropertiesI.H.
Referenced by liquidProperties::~liquidProperties().
Pc()
Foam::scalar Pc () const inline
Critical pressure [Pa].
Definition at line 38 of file liquidPropertiesI.H.
Referenced by liquidProperties::~liquidProperties().
Vc()
Foam::scalar Vc () const inline
Critical volume [m^3/kmol].
Definition at line 44 of file liquidPropertiesI.H.
Referenced by liquidProperties::~liquidProperties().
Zc()
Foam::scalar Zc () const inline
Critical compressibilty factor.
Definition at line 50 of file liquidPropertiesI.H.
Referenced by liquidProperties::~liquidProperties().
Tt()
Foam::scalar Tt () const inline
Triple point temperature [K].
Definition at line 56 of file liquidPropertiesI.H.
Referenced by liquidProperties::~liquidProperties().
Pt()
Foam::scalar Pt () const inline
Triple point pressure [Pa].
Definition at line 62 of file liquidPropertiesI.H.
Referenced by liquidProperties::~liquidProperties().
Tb()
Foam::scalar Tb () const inline
Normal boiling temperature [K].
Definition at line 68 of file liquidPropertiesI.H.
Referenced by liquidProperties::~liquidProperties().
dipm()
Foam::scalar dipm () const inline
Dipole moment [].
Definition at line 74 of file liquidPropertiesI.H.
Referenced by liquidProperties::~liquidProperties().
omega()
Foam::scalar omega () const inline
Pitzer's ascentric factor [].
Definition at line 80 of file liquidPropertiesI.H.
Referenced by liquidProperties::~liquidProperties().
delta()
Foam::scalar delta () const inline
Solubility parameter [(J/m^3)^(1/2)].
Definition at line 86 of file liquidPropertiesI.H.
Referenced by liquidProperties::~liquidProperties().
rho()
Foam::scalar rho (scalar p, scalar T) const virtual
Liquid rho [kg/m^3].
Reimplemented in IDEA, aC10H7CH3, Ar, bC10H7CH3, C10H22, C12H26, C13H28, C14H30, C16H34, C2H5OH, C2H6, C2H6O, C3H6O, C3H8, C4H10O, C6H14, C6H6, C7H16, C7H8, C8H18, C9H20, CH3OH, CH4N2O, IC8H18, MB, N2, C8H10, H2O, iC3H8O, and nC3H8O.
Definition at line 221 of file liquidProperties.C.
References NotImplemented.
Referenced by SprayParcel< ParcelType >::chi(), liquidFilmThermo::rho(), and liquidProperties::~liquidProperties().
pv()
Foam::scalar pv (scalar p, scalar T) const virtual
Vapour pressure [Pa].
Reimplemented in IDEA, aC10H7CH3, Ar, bC10H7CH3, C10H22, C12H26, C13H28, C14H30, C16H34, C2H5OH, C2H6, C2H6O, C3H6O, C3H8, C4H10O, C6H14, C6H6, C7H16, C7H8, C8H18, C9H20, CH3OH, CH4N2O, IC8H18, MB, N2, C8H10, H2O, iC3H8O, and nC3H8O.
Definition at line 228 of file liquidProperties.C.
References NotImplemented.
Referenced by liquidFilmThermo::pv(), liquidProperties::pvInvert(), and liquidProperties::~liquidProperties().
hl()
Foam::scalar hl (scalar p, scalar T) const virtual
Heat of vapourisation [J/kg].
Reimplemented in IDEA, aC10H7CH3, Ar, bC10H7CH3, C10H22, C12H26, C13H28, C14H30, C16H34, C2H5OH, C2H6, C2H6O, C3H6O, C3H8, C4H10O, C6H14, C6H6, C7H16, C7H8, C8H18, C9H20, CH3OH, CH4N2O, IC8H18, MB, N2, C8H10, H2O, iC3H8O, and nC3H8O.
Definition at line 235 of file liquidProperties.C.
References NotImplemented.
Referenced by SprayParcel< ParcelType >::chi(), liquidFilmThermo::hl(), and liquidProperties::~liquidProperties().
Cp()
Foam::scalar Cp (scalar p, scalar T) const virtual
Liquid heat capacity [J/(kg K)].
Reimplemented in IDEA, aC10H7CH3, Ar, bC10H7CH3, C10H22, C12H26, C13H28, C14H30, C16H34, C2H5OH, C2H6, C2H6O, C3H6O, C3H8, C4H10O, C6H14, C6H6, C7H16, C7H8, C8H18, C9H20, CH3OH, CH4N2O, IC8H18, MB, N2, C8H10, H2O, iC3H8O, and nC3H8O.
Definition at line 242 of file liquidProperties.C.
References NotImplemented.
Referenced by liquidFilmThermo::Cp(), and liquidProperties::~liquidProperties().
h()
Foam::scalar h (scalar p, scalar T) const virtual
Liquid enthalpy [J/kg] - reference to 298.15 K.
Reimplemented in IDEA, aC10H7CH3, Ar, bC10H7CH3, C10H22, C12H26, C13H28, C14H30, C16H34, C2H5OH, C2H6, C2H6O, C3H6O, C3H8, C4H10O, C6H14, C6H6, C7H16, C7H8, C8H18, C9H20, CH3OH, CH4N2O, IC8H18, MB, N2, C8H10, H2O, iC3H8O, and nC3H8O.
Definition at line 249 of file liquidProperties.C.
References NotImplemented.
Referenced by SprayParcel< ParcelType >::chi(), and liquidProperties::~liquidProperties().
Cpg()
Foam::scalar Cpg (scalar p, scalar T) const virtual
Ideal gas heat capacity [J/(kg K)].
Reimplemented in IDEA, aC10H7CH3, Ar, bC10H7CH3, C10H22, C12H26, C13H28, C14H30, C16H34, C2H5OH, C2H6, C2H6O, C3H6O, C3H8, C4H10O, C6H14, C6H6, C7H16, C7H8, C8H18, C9H20, CH3OH, CH4N2O, IC8H18, MB, N2, C8H10, H2O, iC3H8O, and nC3H8O.
Definition at line 256 of file liquidProperties.C.
References NotImplemented.
Referenced by liquidProperties::~liquidProperties().
mu()
Foam::scalar mu (scalar p, scalar T) const virtual
Liquid viscosity [Pa s].
Reimplemented in IDEA, aC10H7CH3, Ar, bC10H7CH3, C10H22, C12H26, C13H28, C14H30, C16H34, C2H5OH, C2H6, C2H6O, C3H6O, C3H8, C4H10O, C6H14, C6H6, C7H16, C7H8, C8H18, C9H20, CH3OH, CH4N2O, IC8H18, MB, N2, C8H10, H2O, iC3H8O, and nC3H8O.
Definition at line 263 of file liquidProperties.C.
References NotImplemented.
Referenced by ThermoSurfaceFilm< CloudType >::drySplashInteraction(), liquidFilmThermo::mu(), ThermoSurfaceFilm< CloudType >::wetSplashInteraction(), and liquidProperties::~liquidProperties().
mug()
Foam::scalar mug (scalar p, scalar T) const virtual
Vapour viscosity [Pa s].
Reimplemented in IDEA, aC10H7CH3, Ar, bC10H7CH3, C10H22, C12H26, C13H28, C14H30, C16H34, C2H5OH, C2H6, C2H6O, C3H6O, C3H8, C4H10O, C6H14, C6H6, C7H16, C7H8, C8H18, C9H20, CH3OH, CH4N2O, IC8H18, MB, N2, C8H10, H2O, iC3H8O, and nC3H8O.
Definition at line 270 of file liquidProperties.C.
References NotImplemented.
Referenced by liquidProperties::~liquidProperties().
K()
Foam::scalar K (scalar p, scalar T) const virtual
Liquid thermal conductivity [W/(m K)].
Reimplemented in IDEA, aC10H7CH3, Ar, bC10H7CH3, C10H22, C12H26, C13H28, C14H30, C16H34, C2H5OH, C2H6, C2H6O, C3H6O, C3H8, C4H10O, C6H14, C6H6, C7H16, C7H8, C8H18, C9H20, CH3OH, CH4N2O, IC8H18, MB, N2, C8H10, H2O, iC3H8O, and nC3H8O.
Definition at line 277 of file liquidProperties.C.
References NotImplemented.
Referenced by liquidFilmThermo::kappa(), and liquidProperties::~liquidProperties().
Kg()
Foam::scalar Kg (scalar p, scalar T) const virtual
Vapour thermal conductivity [W/(m K)].
Reimplemented in IDEA, aC10H7CH3, Ar, bC10H7CH3, C10H22, C12H26, C13H28, C14H30, C16H34, C2H5OH, C2H6, C2H6O, C3H6O, C3H8, C4H10O, C6H14, C6H6, C7H16, C7H8, C8H18, C9H20, CH3OH, CH4N2O, IC8H18, MB, N2, C8H10, H2O, iC3H8O, and nC3H8O.
Definition at line 284 of file liquidProperties.C.
References NotImplemented.
Referenced by liquidProperties::~liquidProperties().
sigma()
Foam::scalar sigma (scalar p, scalar T) const virtual
Surface tension [N/m].
Reimplemented in IDEA, aC10H7CH3, Ar, bC10H7CH3, C10H22, C12H26, C13H28, C14H30, C16H34, C2H5OH, C2H6, C2H6O, C3H6O, C3H8, C4H10O, C6H14, C6H6, C7H16, C7H8, C8H18, C9H20, CH3OH, CH4N2O, IC8H18, MB, N2, C8H10, H2O, iC3H8O, and nC3H8O.
Definition at line 291 of file liquidProperties.C.
References NotImplemented.
Referenced by ThermoSurfaceFilm< CloudType >::drySplashInteraction(), liquidFilmThermo::sigma(), ThermoSurfaceFilm< CloudType >::wetSplashInteraction(), and liquidProperties::~liquidProperties().
D() [1/2]
Foam::scalar D (scalar p, scalar T) const virtual
Vapour diffussivity [m2/s].
Reimplemented in IDEA, aC10H7CH3, Ar, bC10H7CH3, C10H22, C12H26, C13H28, C14H30, C16H34, C2H5OH, C2H6, C2H6O, C3H6O, C3H8, C4H10O, C6H14, C6H6, C7H16, C7H8, C8H18, C9H20, CH3OH, CH4N2O, IC8H18, MB, N2, C8H10, H2O, iC3H8O, and nC3H8O.
Definition at line 298 of file liquidProperties.C.
References NotImplemented.
Referenced by liquidFilmThermo::D(), and liquidProperties::~liquidProperties().
D() [2/2]
Foam::scalar D (scalar p, scalar T, scalar Wb) const virtual
Vapour diffussivity [m2/s] with specified binary pair.
Reimplemented in IDEA, aC10H7CH3, Ar, bC10H7CH3, C10H22, C12H26, C13H28, C14H30, C16H34, C2H5OH, C2H6, C2H6O, C3H6O, C3H8, C4H10O, C6H14, C6H6, C7H16, C7H8, C8H18, C9H20, CH3OH, CH4N2O, IC8H18, MB, N2, C8H10, H2O, iC3H8O, and nC3H8O.
Definition at line 305 of file liquidProperties.C.
References NotImplemented.
pvInvert()
Foam::scalar pvInvert (scalar p) const virtual
Invert the vapour pressure relationship to retrieve the.
boiling temperuture as a function of pressure
Definition at line 312 of file liquidProperties.C.
References Foam::e, Foam::endl(), Foam::nl, liquidProperties::pv(), Foam::T(), and WarningInFunction.
Referenced by SprayParcel< ParcelType >::chi(), liquidFilmThermo::Tb(), and liquidProperties::~liquidProperties().
writeData()
void writeData (Ostream & os) const virtual
Write the function coefficients.
Reimplemented in IDEA, aC10H7CH3, Ar, bC10H7CH3, C10H22, C12H26, C13H28, C14H30, C16H34, C2H5OH, C2H6, C2H6O, C3H6O, C3H8, C4H10O, C6H14, C6H6, C7H16, C7H8, C8H18, C9H20, CH3OH, CH4N2O, IC8H18, MB, N2, C8H10, H2O, iC3H8O, and nC3H8O.
Definition at line 355 of file liquidProperties.C.
References token::SPACE.
Referenced by C8H10::writeData(), H2O::writeData(), iC3H8O::writeData(), nC3H8O::writeData(), aC10H7CH3::writeData(), Ar::writeData(), IC8H18::writeData(), C13H28::writeData(), C3H6O::writeData(), CH4N2O::writeData(), CH3OH::writeData(), C9H20::writeData(), C8H18::writeData(), C2H5OH::writeData(), C7H8::writeData(), C16H34::writeData(), C6H6::writeData(), C14H30::writeData(), C4H10O::writeData(), C3H8::writeData(), bC10H7CH3::writeData(), C2H6O::writeData(), C2H6::writeData(), C7H16::writeData(), C10H22::writeData(), N2::writeData(), C6H14::writeData(), C12H26::writeData(), MB::writeData(), IDEA::writeData(), and liquidProperties::~liquidProperties().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & os, const liquidProperties & l) friend
Ostream Operator.
Definition at line 264 of file liquidProperties.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/properties/liquidProperties/liquidProperties/liquidProperties.H
src/thermophysicalModels/properties/liquidProperties/liquidProperties/liquidProperties.C
src/thermophysicalModels/properties/liquidProperties/liquidProperties/liquidPropertiesI.H