OpenFOAM: C2H5OH Class Reference
C2H5OH Class Reference
ethanol
Public Member Functions
TypeName ("C2H5OH")
Runtime type information.
C2H5OH ()
Construct null.
C2H5OH (const liquidProperties &l, const NSRDSfunc5 &density, const NSRDSfunc1 &vapourPressure, const NSRDSfunc6 &heatOfVapourisation, const NSRDSfunc0 &heatCapacity, const NSRDSfunc0 &enthalpy, const NSRDSfunc7 &idealGasHeatCapacity, const NSRDSfunc4 &secondVirialCoeff, const NSRDSfunc1 &dynamicViscosity, const NSRDSfunc2 &vapourDynamicViscosity, const NSRDSfunc0 &thermalConductivity, const NSRDSfunc2 &vapourThermalConductivity, const NSRDSfunc0 &surfaceTension, const APIdiffCoefFunc &vapourDiffussivity)
Construct from components.
C2H5OH (Istream &is)
Construct from Istream.
C2H5OH (const dictionary &dict)
Construct from dictionary.
C2H5OH (const C2H5OH &liq)
Construct copy.
virtual autoPtr< liquidProperties > clone () const
Construct and return clone.
scalar rho (scalar p, scalar T) const
Liquid density [kg/m^3].
scalar pv (scalar p, scalar T) const
Vapour pressure [Pa].
scalar hl (scalar p, scalar T) const
Heat of vapourisation [J/kg].
scalar Cp (scalar p, scalar T) const
Liquid heat capacity [J/(kg K)].
scalar h (scalar p, scalar T) const
Liquid Enthalpy [J/(kg)].
scalar Cpg (scalar p, scalar T) const
Ideal gas heat capacity [J/(kg K)].
scalar B (scalar p, scalar T) const
Second Virial Coefficient [m^3/kg].
scalar mu (scalar p, scalar T) const
Liquid viscosity [Pa s].
scalar mug (scalar p, scalar T) const
Vapour viscosity [Pa s].
scalar K (scalar p, scalar T) const
Liquid thermal conductivity [W/(m K)].
scalar Kg (scalar p, scalar T) const
Vapour thermal conductivity [W/(m K)].
scalar sigma (scalar p, scalar T) const
Surface tension [N/m].
scalar D (scalar p, scalar T) const
Vapour diffussivity [m2/s].
scalar D (scalar p, scalar T, scalar Wb) const
Vapour diffussivity [m2/s] with specified binary pair.
void writeData (Ostream &os) const
Write the function coefficients.
Public Member Functions inherited from liquidProperties
TypeName ("liquidProperties")
declareRunTimeSelectionTable (autoPtr, liquidProperties,,(),())
declareRunTimeSelectionTable (autoPtr, liquidProperties, Istream,(Istream &is),(is))
declareRunTimeSelectionTable (autoPtr, liquidProperties, dictionary,(const dictionary &dict),(dict))
liquidProperties (scalar W, scalar Tc, scalar Pc, scalar Vc, scalar Zc, scalar Tt, scalar Pt, scalar Tb, scalar dipm, scalar omega, scalar delta)
Construct from components.
liquidProperties (Istream &is)
Construct from Istream.
liquidProperties (const dictionary &dict)
Construct from dictionary.
liquidProperties (const liquidProperties &liq)
Construct copy.
virtual ~liquidProperties ()
Destructor.
scalar W () const
Molecular weight [kg/kmol].
scalar Tc () const
Critical temperature [K].
scalar Pc () const
Critical pressure [Pa].
scalar Vc () const
Critical volume [m^3/kmol].
scalar Zc () const
Critical compressibilty factor.
scalar Tt () const
Triple point temperature [K].
scalar Pt () const
Triple point pressure [Pa].
scalar Tb () const
Normal boiling temperature [K].
scalar dipm () const
Dipole moment [].
scalar omega () const
Pitzer's ascentric factor [].
scalar delta () const
Solubility parameter [(J/m^3)^(1/2)].
virtual scalar pvInvert (scalar p) const
Invert the vapour pressure relationship to retrieve the.
Friends
Ostream & operator<< (Ostream &os, const C2H5OH &l)
Ostream Operator.
Additional Inherited Members
Static Public Member Functions inherited from liquidProperties
static autoPtr< liquidProperties > New (Istream &is)
Return a pointer to a new liquidProperties created from input.
static autoPtr< liquidProperties > New (const dictionary &dict)
Return a pointer to a new liquidProperties created from dictionary.
Detailed Description
ethanol
Source files
C2H5OH.H
C2H5OH.C
Definition at line 58 of file C2H5OH.H.
Constructor & Destructor Documentation
C2H5OH() [1/5]
C2H5OH ()
Construct null.
Definition at line 41 of file C2H5OH.C.
Referenced by C2H5OH::clone().
C2H5OH() [2/5]
C2H5OH (const liquidProperties & l, const NSRDSfunc5 & density, const NSRDSfunc1 & vapourPressure, const NSRDSfunc6 & heatOfVapourisation, const NSRDSfunc0 & heatCapacity, const NSRDSfunc0 & enthalpy, const NSRDSfunc7 & idealGasHeatCapacity, const NSRDSfunc4 & secondVirialCoeff, const NSRDSfunc1 & dynamicViscosity, const NSRDSfunc2 & vapourDynamicViscosity, const NSRDSfunc0 & thermalConductivity, const NSRDSfunc2 & vapourThermalConductivity, const NSRDSfunc0 & surfaceTension, const APIdiffCoefFunc & vapourDiffussivity)
Construct from components.
Definition at line 97 of file C2H5OH.C.
C2H5OH() [3/5]
C2H5OH (Istream & is)
Construct from Istream.
Definition at line 131 of file C2H5OH.C.
C2H5OH() [4/5]
C2H5OH (const dictionary & dict)
Construct from dictionary.
Definition at line 150 of file C2H5OH.C.
C2H5OH() [5/5]
C2H5OH (const C2H5OH & liq)
Construct copy.
Definition at line 169 of file C2H5OH.C.
Member Function Documentation
TypeName()
TypeName ("C2H5OH")
Runtime type information.
clone()
virtual autoPtr<liquidProperties> clone () const inline virtual
Construct and return clone.
Reimplemented from liquidProperties.
Definition at line 119 of file C2H5OH.H.
References C2H5OH::B(), C2H5OH::C2H5OH(), C2H5OH::Cp(), C2H5OH::Cpg(), C2H5OH::D(), C2H5OH::h(), C2H5OH::hl(), C2H5OH::K(), C2H5OH::Kg(), C2H5OH::mu(), C2H5OH::mug(), p, C2H5OH::pv(), C2H5OH::rho(), C2H5OH::sigma(), and Foam::T().
rho()
Foam::scalar rho (scalar p, scalar T) const inline virtual
Liquid density [kg/m^3].
Reimplemented from liquidProperties.
Definition at line 26 of file C2H5OHI.H.
References NSRDSfunc5::f().
Referenced by C2H5OH::clone().
pv()
Foam::scalar pv (scalar p, scalar T) const inline virtual
Vapour pressure [Pa].
Reimplemented from liquidProperties.
Definition at line 32 of file C2H5OHI.H.
References NSRDSfunc1::f().
Referenced by C2H5OH::clone().
hl()
Foam::scalar hl (scalar p, scalar T) const inline virtual
Heat of vapourisation [J/kg].
Reimplemented from liquidProperties.
Definition at line 38 of file C2H5OHI.H.
References NSRDSfunc6::f().
Referenced by C2H5OH::clone().
Cp()
Foam::scalar Cp (scalar p, scalar T) const inline virtual
Liquid heat capacity [J/(kg K)].
Reimplemented from liquidProperties.
Definition at line 44 of file C2H5OHI.H.
References NSRDSfunc0::f().
Referenced by C2H5OH::clone().
h()
Foam::scalar h (scalar p, scalar T) const inline virtual
Liquid Enthalpy [J/(kg)].
Reimplemented from liquidProperties.
Definition at line 50 of file C2H5OHI.H.
References NSRDSfunc0::f().
Referenced by C2H5OH::clone().
Cpg()
Foam::scalar Cpg (scalar p, scalar T) const inline virtual
Ideal gas heat capacity [J/(kg K)].
Reimplemented from liquidProperties.
Definition at line 56 of file C2H5OHI.H.
References NSRDSfunc7::f().
Referenced by C2H5OH::clone().
B()
Foam::scalar B (scalar p, scalar T) const inline
Second Virial Coefficient [m^3/kg].
Definition at line 62 of file C2H5OHI.H.
References NSRDSfunc4::f().
Referenced by C2H5OH::clone().
mu()
Foam::scalar mu (scalar p, scalar T) const inline virtual
Liquid viscosity [Pa s].
Reimplemented from liquidProperties.
Definition at line 68 of file C2H5OHI.H.
References NSRDSfunc1::f().
Referenced by C2H5OH::clone().
mug()
Foam::scalar mug (scalar p, scalar T) const inline virtual
Vapour viscosity [Pa s].
Reimplemented from liquidProperties.
Definition at line 74 of file C2H5OHI.H.
References NSRDSfunc2::f().
Referenced by C2H5OH::clone().
K()
Foam::scalar K (scalar p, scalar T) const inline virtual
Liquid thermal conductivity [W/(m K)].
Reimplemented from liquidProperties.
Definition at line 80 of file C2H5OHI.H.
References NSRDSfunc0::f().
Referenced by C2H5OH::clone().
Kg()
Foam::scalar Kg (scalar p, scalar T) const inline virtual
Vapour thermal conductivity [W/(m K)].
Reimplemented from liquidProperties.
Definition at line 86 of file C2H5OHI.H.
References NSRDSfunc2::f().
Referenced by C2H5OH::clone().
sigma()
Foam::scalar sigma (scalar p, scalar T) const inline virtual
Surface tension [N/m].
Reimplemented from liquidProperties.
Definition at line 92 of file C2H5OHI.H.
References NSRDSfunc0::f().
Referenced by C2H5OH::clone().
D() [1/2]
Foam::scalar D (scalar p, scalar T) const inline virtual
Vapour diffussivity [m2/s].
Reimplemented from liquidProperties.
Definition at line 98 of file C2H5OHI.H.
References APIdiffCoefFunc::f().
Referenced by C2H5OH::clone().
D() [2/2]
Foam::scalar D (scalar p, scalar T, scalar Wb) const inline virtual
Vapour diffussivity [m2/s] with specified binary pair.
Reimplemented from liquidProperties.
Definition at line 104 of file C2H5OHI.H.
References APIdiffCoefFunc::f().
writeData()
void writeData (Ostream & os) const inline virtual
Write the function coefficients.
Reimplemented from liquidProperties.
Definition at line 173 of file C2H5OH.H.
References Foam::endl(), Foam::nl, APIdiffCoefFunc::writeData(), NSRDSfunc2::writeData(), NSRDSfunc5::writeData(), NSRDSfunc4::writeData(), NSRDSfunc1::writeData(), NSRDSfunc7::writeData(), NSRDSfunc0::writeData(), NSRDSfunc6::writeData(), and liquidProperties::writeData().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & os, const C2H5OH & l) friend
Ostream Operator.
Definition at line 192 of file C2H5OH.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/properties/liquidProperties/C2H5OH/C2H5OH.H
src/thermophysicalModels/properties/liquidProperties/C2H5OH/C2H5OH.C
src/thermophysicalModels/properties/liquidProperties/C2H5OH/C2H5OHI.H