OpenFOAM: absorptionEmissionModel Class Reference
absorptionEmissionModel Class Reference
Model to supply absorption and emission coefficients for radiation modelling.
Public Member Functions
TypeName ("absorptionEmissionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, absorptionEmissionModel, dictionary,(const dictionary &dict, const fvMesh &mesh),(dict, mesh))
Declare runtime constructor selection table.
absorptionEmissionModel (const dictionary &dict, const fvMesh &mesh)
Construct from components.
virtual ~absorptionEmissionModel ()
Destructor.
const fvMesh & mesh () const
Reference to the mesh.
const dictionary & dict () const
Reference to the dictionary.
virtual tmp< volScalarField > a (const label bandI=0) const
Absorption coefficient (net)
virtual tmp< volScalarField > aCont (const label bandI=0) const
Absorption coefficient for continuous phase.
virtual tmp< volScalarField > aDisp (const label bandI=0) const
Absorption coefficient for dispersed phase.
virtual tmp< volScalarField > e (const label bandI=0) const
Emission coefficient (net)
virtual tmp< volScalarField > eCont (const label bandI=0) const
Return emission coefficient for continuous phase.
virtual tmp< volScalarField > eDisp (const label bandI=0) const
Return emission coefficient for dispersed phase.
virtual tmp< volScalarField > E (const label bandI=0) const
Emission contribution (net)
virtual tmp< volScalarField > ECont (const label bandI=0) const
Emission contribution for continuous phase.
virtual tmp< volScalarField > EDisp (const label bandI=0) const
Emission contribution for dispersed phase.
virtual label nBands () const
Const access to the number of bands - defaults to 1 for grey.
virtual const Vector2D< scalar > & bands (const label n) const
Const access to the bands - defaults to Vector2D::one for grey.
virtual bool isGrey () const
Flag for whether the absorption/emission is for a grey gas.
virtual void correct (volScalarField &a, PtrList< volScalarField > &aj) const
Correct absorption coefficients.
Static Public Member Functions
static autoPtr< absorptionEmissionModel > New (const dictionary &dict, const fvMesh &mesh)
Selector.
Protected Attributes
const dictionary dict_
Radiation model dictionary.
const fvMesh & mesh_
Reference to the fvMesh.
Detailed Description
Model to supply absorption and emission coefficients for radiation modelling.
Definition at line 52 of file absorptionEmissionModel.H.
Constructor & Destructor Documentation
absorptionEmissionModel()
absorptionEmissionModel (const dictionary & dict, const fvMesh & mesh)
Construct from components.
Definition at line 42 of file absorptionEmissionModel.C.
~absorptionEmissionModel()
~absorptionEmissionModel () virtual
Destructor.
Definition at line 54 of file absorptionEmissionModel.C.
Member Function Documentation
TypeName()
TypeName ("absorptionEmissionModel")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , absorptionEmissionModel , dictionary , (const dictionary &dict, const fvMesh &mesh) , (dict, mesh))
Declare runtime constructor selection table.
New()
Foam::autoPtr< Foam::radiation::absorptionEmissionModel > New (const dictionary & dict, const fvMesh & mesh) static
Selector.
Definition at line 33 of file absorptionEmissionModelNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::Info, dictionary::lookup(), mesh, and Foam::nl.
mesh()
const fvMesh& mesh () const inline
Reference to the mesh.
Definition at line 113 of file absorptionEmissionModel.H.
References absorptionEmissionModel::mesh_.
dict()
const dictionary& dict () const inline
Reference to the dictionary.
Definition at line 119 of file absorptionEmissionModel.H.
References absorptionEmissionModel::a(), absorptionEmissionModel::aCont(), absorptionEmissionModel::aDisp(), absorptionEmissionModel::bands(), absorptionEmissionModel::correct(), absorptionEmissionModel::dict_, absorptionEmissionModel::e(), absorptionEmissionModel::E(), absorptionEmissionModel::eCont(), absorptionEmissionModel::ECont(), absorptionEmissionModel::eDisp(), absorptionEmissionModel::EDisp(), absorptionEmissionModel::isGrey(), n, and absorptionEmissionModel::nBands().
a()
Foam::tmp< Foam::volScalarField > a (const label bandI = 0) const virtual
Absorption coefficient (net)
Definition at line 61 of file absorptionEmissionModel.C.
Referenced by absorptionEmissionModel::dict(), noPyrolysis::kappaRad(), thermalBaffle::kappaRad(), and reactingOneDim::kappaRad().
aCont()
Foam::tmp< Foam::volScalarField > aCont (const label bandI = 0) const virtual
Absorption coefficient for continuous phase.
Reimplemented in wideBandAbsorptionEmission, greyMeanAbsorptionEmission, greyMeanSolidAbsorptionEmission, constantAbsorptionEmission, and binaryAbsorptionEmission.
Definition at line 68 of file absorptionEmissionModel.C.
References Foam::dimLength, Foam::dimless, IOobject::NO_READ, and IOobject::NO_WRITE.
Referenced by absorptionEmissionModel::dict().
aDisp()
Foam::tmp< Foam::volScalarField > aDisp (const label bandI = 0) const virtual
Absorption coefficient for dispersed phase.
Reimplemented in binaryAbsorptionEmission, and cloudAbsorptionEmission.
Definition at line 91 of file absorptionEmissionModel.C.
References Foam::dimLength, Foam::dimless, IOobject::NO_READ, and IOobject::NO_WRITE.
Referenced by absorptionEmissionModel::dict().
e()
Foam::tmp< Foam::volScalarField > e (const label bandI = 0) const virtual
Emission coefficient (net)
Definition at line 114 of file absorptionEmissionModel.C.
Referenced by absorptionEmissionModel::dict(), and radiationCoupledBase::emissivity().
eCont()
Foam::tmp< Foam::volScalarField > eCont (const label bandI = 0) const virtual
Return emission coefficient for continuous phase.
Reimplemented in wideBandAbsorptionEmission, greyMeanAbsorptionEmission, greyMeanSolidAbsorptionEmission, constantAbsorptionEmission, and binaryAbsorptionEmission.
Definition at line 121 of file absorptionEmissionModel.C.
References Foam::dimLength, Foam::dimless, IOobject::NO_READ, and IOobject::NO_WRITE.
Referenced by absorptionEmissionModel::dict().
eDisp()
Foam::tmp< Foam::volScalarField > eDisp (const label bandI = 0) const virtual
Return emission coefficient for dispersed phase.
Reimplemented in binaryAbsorptionEmission, and cloudAbsorptionEmission.
Definition at line 144 of file absorptionEmissionModel.C.
References Foam::dimLength, Foam::dimless, IOobject::NO_READ, and IOobject::NO_WRITE.
Referenced by absorptionEmissionModel::dict().
E()
Foam::tmp< Foam::volScalarField > E (const label bandI = 0) const virtual
Emission contribution (net)
Definition at line 167 of file absorptionEmissionModel.C.
Referenced by absorptionEmissionModel::dict().
ECont()
Foam::tmp< Foam::volScalarField > ECont (const label bandI = 0) const virtual
Emission contribution for continuous phase.
Reimplemented in wideBandAbsorptionEmission, greyMeanAbsorptionEmission, binaryAbsorptionEmission, and constantAbsorptionEmission.
Definition at line 174 of file absorptionEmissionModel.C.
References Foam::dimLength, Foam::dimMass, Foam::dimTime, IOobject::NO_READ, IOobject::NO_WRITE, and Foam::pow3().
Referenced by absorptionEmissionModel::dict().
EDisp()
Foam::tmp< Foam::volScalarField > EDisp (const label bandI = 0) const virtual
Emission contribution for dispersed phase.
Reimplemented in binaryAbsorptionEmission, and cloudAbsorptionEmission.
Definition at line 197 of file absorptionEmissionModel.C.
References Foam::dimLength, Foam::dimMass, Foam::dimTime, IOobject::NO_READ, IOobject::NO_WRITE, and Foam::pow3().
Referenced by absorptionEmissionModel::dict().
nBands()
Foam::label nBands () const virtual
Const access to the number of bands - defaults to 1 for grey.
absorption/emission
Reimplemented in wideBandAbsorptionEmission.
Definition at line 219 of file absorptionEmissionModel.C.
Referenced by absorptionEmissionModel::dict().
bands()
const Foam::Vector2D< Foam::scalar > & bands (const label n) const virtual
Const access to the bands - defaults to Vector2D::one for grey.
absorption/emission
Reimplemented in wideBandAbsorptionEmission.
Definition at line 226 of file absorptionEmissionModel.C.
Referenced by absorptionEmissionModel::dict().
isGrey()
bool isGrey () const virtual
Flag for whether the absorption/emission is for a grey gas.
Reimplemented in wideBandAbsorptionEmission, greyMeanAbsorptionEmission, greyMeanSolidAbsorptionEmission, and constantAbsorptionEmission.
Definition at line 232 of file absorptionEmissionModel.C.
References absorptionEmissionModel::correct().
Referenced by absorptionEmissionModel::dict().
correct()
void correct (volScalarField & a, PtrList< volScalarField > & aj) const virtual
Correct absorption coefficients.
Reimplemented in wideBandAbsorptionEmission.
Definition at line 239 of file absorptionEmissionModel.C.
Referenced by absorptionEmissionModel::dict(), and absorptionEmissionModel::isGrey().
Member Data Documentation
dict_
const dictionary dict_ protected
Radiation model dictionary.
Definition at line 60 of file absorptionEmissionModel.H.
Referenced by absorptionEmissionModel::dict().
mesh_
const fvMesh& mesh_ protected
Reference to the fvMesh.
Definition at line 63 of file absorptionEmissionModel.H.
Referenced by absorptionEmissionModel::mesh().
The documentation for this class was generated from the following files:
src/thermophysicalModels/radiation/submodels/absorptionEmissionModel/absorptionEmissionModel/absorptionEmissionModel.H
src/thermophysicalModels/radiation/submodels/absorptionEmissionModel/absorptionEmissionModel/absorptionEmissionModel.C
src/thermophysicalModels/radiation/submodels/absorptionEmissionModel/absorptionEmissionModel/absorptionEmissionModelNew.C