OpenFOAM: ash Class Reference
ash Class Reference
Coal ash solid properties.
Public Member Functions
TypeName ("ash")
Runtime type information.
ash ()
Construct null.
ash (const solidProperties &s)
Construct from solidProperties.
ash (Istream &is)
Construct from Istream.
ash (const dictionary &dict)
Construct from dictionary.
ash (const ash &s)
Construct copy.
virtual autoPtr< solidProperties > clone () const
Construct and return clone.
void writeData (Ostream &os) const
Write the function coefficients.
Public Member Functions inherited from solidProperties
TypeName ("solidProperties")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, solidProperties,,(),())
declareRunTimeSelectionTable (autoPtr, solidProperties, Istream,(Istream &is),(is))
declareRunTimeSelectionTable (autoPtr, solidProperties, dictionary,(const dictionary &dict),(dict))
solidProperties (scalar rho, scalar Cp, scalar K, scalar Hf, scalar emissivity)
Construct from components.
solidProperties (Istream &is)
Construct from Istream.
solidProperties (const dictionary &dict)
Construct from dictionary.
solidProperties (const solidProperties &s)
Construct copy.
virtual ~solidProperties ()
Destructor.
scalar rho () const
Density [kg/m3].
scalar Cp () const
Specific heat capacity [J/(kg.K)].
scalar K () const
Thermal conductivity [W/(m.K)].
scalar Hf () const
Heat of formation [J/kg].
scalar Hs (const scalar T) const
Sensible enthalpy - reference to Tstd [J/kg].
scalar emissivity () const
Emissivity [].
Friends
Ostream & operator<< (Ostream &os, const ash &s)
Additional Inherited Members
Static Public Member Functions inherited from solidProperties
static autoPtr< solidProperties > New (Istream &is)
Return a pointer to a new solidProperties created from input.
static autoPtr< solidProperties > New (const dictionary &dict)
Return a pointer to a new solidProperties created from dictionary.
Detailed Description
Coal ash solid properties.
Source files
ash.H
ash.C
Definition at line 57 of file ash.H.
Constructor & Destructor Documentation
ash() [1/5]
ash ()
Construct null.
Definition at line 41 of file ash.C.
References Foam::endl(), and WarningInFunction.
Referenced by ash::clone().
ash() [2/5]
ash (const solidProperties & s)
Construct from solidProperties.
Definition at line 54 of file ash.C.
ash() [3/5]
ash (Istream & is)
Construct from Istream.
Definition at line 60 of file ash.C.
ash() [4/5]
ash (const dictionary & dict)
Construct from dictionary.
Definition at line 66 of file ash.C.
ash() [5/5]
ash (const ash & s)
Construct copy.
Definition at line 72 of file ash.C.
Member Function Documentation
TypeName()
TypeName ("ash")
Runtime type information.
clone()
virtual autoPtr<solidProperties> clone () const inline virtual
Construct and return clone.
Reimplemented from solidProperties.
Definition at line 86 of file ash.H.
References ash::ash(), ash::operator<<, and ash::writeData().
writeData()
void writeData (Ostream & os) const virtual
Write the function coefficients.
Reimplemented from solidProperties.
Definition at line 80 of file ash.C.
References solidProperties::writeData().
Referenced by ash::clone(), and Foam::operator<<().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & os, const ash & s) friend
Referenced by ash::clone().
The documentation for this class was generated from the following files:
src/thermophysicalModels/properties/solidProperties/ash/ash.H
src/thermophysicalModels/properties/solidProperties/ash/ash.C