OpenFOAM: radiationCoupledBase Class Reference
radiationCoupledBase Class Reference
Common functions to emissivity. It gets supplied from lookup into a dictionary or calculated by the solidThermo:
Public Types
enum emissivityMethodType { SOLIDRADIATION, LOOKUP }
Type of supplied emissivity.
Public Member Functions
TypeName ("radiationCoupledBase")
Runtime type information.
radiationCoupledBase (const fvPatch &patch, const word &calculationMethod, const scalarField &emissivity)
Construct from patch, emissivity mode and emissivity.
radiationCoupledBase (const fvPatch &patch, const word &calculationMethod, const scalarField &emissivity, const fvPatchFieldMapper &mapper)
Construct from patch, emissivity mode and emissivity and mapper.
radiationCoupledBase (const fvPatch &patch, const dictionary &dict)
Construct from patch and dictionary.
virtual ~radiationCoupledBase ()
Destructor.
word emissivityMethod () const
Method to obtain emissivity.
scalarField emissivity () const
Calculate corresponding emissivity field.
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchScalarField &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
void write (Ostream &) const
Write.
Protected Attributes
const emissivityMethodType method_
How to get emissivity.
scalarField emissivity_
Emissivity.
Detailed Description
Common functions to emissivity. It gets supplied from lookup into a dictionary or calculated by the solidThermo:
- 'lookup' : Read the patch emissivity field from the dictionary
'solidRadiation' : Use the emissivity field mapped from the adjacent solid
Source files
radiationCoupledBase.H
radiationCoupledBase.C
Definition at line 55 of file radiationCoupledBase.H.
Member Enumeration Documentation
emissivityMethodType
enum emissivityMethodType
Type of supplied emissivity.
Enumerator
SOLIDRADIATION
LOOKUP
Definition at line 60 of file radiationCoupledBase.H.
Constructor & Destructor Documentation
radiationCoupledBase() [1/3]
radiationCoupledBase (const fvPatch & patch, const word & calculationMethod, const scalarField & emissivity)
Construct from patch, emissivity mode and emissivity.
Definition at line 63 of file radiationCoupledBase.C.
Referenced by NamedEnum< directionType, 3 >::names(), and radiationCoupledBase::radiationCoupledBase().
radiationCoupledBase() [2/3]
radiationCoupledBase (const fvPatch & patch, const word & calculationMethod, const scalarField & emissivity, const fvPatchFieldMapper & mapper)
Construct from patch, emissivity mode and emissivity and mapper.
Definition at line 76 of file radiationCoupledBase.C.
References radiationCoupledBase::radiationCoupledBase().
radiationCoupledBase() [3/3]
radiationCoupledBase (const fvPatch & patch, const dictionary & dict)
Construct from patch and dictionary.
Definition at line 90 of file radiationCoupledBase.C.
References Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, and dictionary::found().
~radiationCoupledBase()
~radiationCoupledBase () virtual
Destructor.
Definition at line 140 of file radiationCoupledBase.C.
Member Function Documentation
TypeName()
TypeName ("radiationCoupledBase")
Runtime type information.
emissivityMethod()
word emissivityMethod () const inline
Method to obtain emissivity.
Definition at line 132 of file radiationCoupledBase.H.
References radiationCoupledBase::autoMap(), radiationCoupledBase::emissivity(), radiationCoupledBase::method_, radiationCoupledBase::rmap(), and radiationCoupledBase::write().
emissivity()
Foam::scalarField emissivity () const
Calculate corresponding emissivity field.
Definition at line 146 of file radiationCoupledBase.C.
References radiationModel::absorptionEmission(), radiationCoupledBase::autoMap(), mappedPatchBase::distribute(), absorptionEmissionModel::e(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, patchIdentifier::index(), radiation(), mappedPatchBase::sampleMesh(), and mappedPatchBase::samplePolyPatch().
Referenced by viewFactor::calculate(), radiationCoupledBase::emissivityMethod(), MarshakRadiationFvPatchScalarField::updateCoeffs(), and MarshakRadiationFixedTemperatureFvPatchScalarField::updateCoeffs().
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Map (and resize as needed) from self given a mapping object.
Reimplemented in MarshakRadiationFixedTemperatureFvPatchScalarField, and MarshakRadiationFvPatchScalarField.
Definition at line 207 of file radiationCoupledBase.C.
References radiationCoupledBase::rmap().
Referenced by radiationCoupledBase::emissivity(), and radiationCoupledBase::emissivityMethod().
rmap()
void rmap (const fvPatchScalarField & ptf, const labelList & addr) virtual
Reverse map the given fvPatchField onto this fvPatchField.
Reimplemented in MarshakRadiationFixedTemperatureFvPatchScalarField, and MarshakRadiationFvPatchScalarField.
Definition at line 216 of file radiationCoupledBase.C.
References radiationCoupledBase::emissivity_, and radiationCoupledBase::rmap().
Referenced by radiationCoupledBase::autoMap(), radiationCoupledBase::emissivityMethod(), and radiationCoupledBase::rmap().
write()
void write (Ostream & os) const
Write.
Definition at line 228 of file radiationCoupledBase.C.
References token::END_STATEMENT, Foam::nl, and Ostream::writeKeyword().
Referenced by radiationCoupledBase::emissivityMethod(), wideBandDiffusiveRadiationMixedFvPatchScalarField::write(), greyDiffusiveViewFactorFixedValueFvPatchScalarField::write(), greyDiffusiveRadiationMixedFvPatchScalarField::write(), MarshakRadiationFvPatchScalarField::write(), and MarshakRadiationFixedTemperatureFvPatchScalarField::write().
Member Data Documentation
method_
const emissivityMethodType method_ protected
How to get emissivity.
Definition at line 83 of file radiationCoupledBase.H.
Referenced by radiationCoupledBase::emissivityMethod().
emissivity_
scalarField emissivity_ protected
Emissivity.
Cached locally when is read from dictionary (lookup mode)
Definition at line 87 of file radiationCoupledBase.H.
Referenced by radiationCoupledBase::rmap().
The documentation for this class was generated from the following files:
src/thermophysicalModels/radiation/derivedFvPatchFields/radiationCoupledBase/radiationCoupledBase.H
src/thermophysicalModels/radiation/derivedFvPatchFields/radiationCoupledBase/radiationCoupledBase.C