OpenFOAM: greyDiffusiveRadiationMixedFvPatchScalarField Class Reference
greyDiffusiveRadiationMixedFvPatchScalarField Class Reference
Boundary Conditions » Thermophysical boundary conditions
This boundary condition provides a grey-diffuse condition for radiation intensity, I, for use with the finite-volume discrete-ordinates model (fvDOM), in which the radiation temperature is retrieved from the temperature field boundary condition.
Public Member Functions
TypeName ("greyDiffusiveRadiation")
Runtime type information.
greyDiffusiveRadiationMixedFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
greyDiffusiveRadiationMixedFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
greyDiffusiveRadiationMixedFvPatchScalarField (const greyDiffusiveRadiationMixedFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given a.
greyDiffusiveRadiationMixedFvPatchScalarField (const greyDiffusiveRadiationMixedFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
greyDiffusiveRadiationMixedFvPatchScalarField (const greyDiffusiveRadiationMixedFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
const word & TName () const
Return the temperature field name.
word & TName ()
Return reference to the temperature field name to allow.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from radiationCoupledBase
TypeName ("radiationCoupledBase")
Runtime type information.
radiationCoupledBase (const fvPatch &patch, const word &calculationMethod, const scalarField &emissivity)
Construct from patch, emissivity mode and emissivity.
radiationCoupledBase (const fvPatch &patch, const word &calculationMethod, const scalarField &emissivity, const fvPatchFieldMapper &mapper)
Construct from patch, emissivity mode and emissivity and mapper.
radiationCoupledBase (const fvPatch &patch, const dictionary &dict)
Construct from patch and dictionary.
virtual ~radiationCoupledBase ()
Destructor.
word emissivityMethod () const
Method to obtain emissivity.
scalarField emissivity () const
Calculate corresponding emissivity field.
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchScalarField &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
void write (Ostream &) const
Write.
Additional Inherited Members
Public Types inherited from radiationCoupledBase
enum emissivityMethodType { SOLIDRADIATION, LOOKUP }
Type of supplied emissivity.
Protected Attributes inherited from radiationCoupledBase
const emissivityMethodType method_
How to get emissivity.
scalarField emissivity_
Emissivity.
Detailed Description
This boundary condition provides a grey-diffuse condition for radiation intensity, I, for use with the finite-volume discrete-ordinates model (fvDOM), in which the radiation temperature is retrieved from the temperature field boundary condition.
Usage
Property Description Required Default value
T temperature field name no T
emissivityMode emissivity mode: solidRadiation or lookup yes
Example of the boundary condition specification:
    <patchName>
    {
        type            greyDiffusiveRadiation;
        T               T;
        emissivityMode  solidRadiation;
        value           uniform 0;
    }
See also
Foam::radiationCoupledBase Foam::radiation::radiationModel Foam::radiation::fvDOM Foam::mixedFvPatchField
Source files
greyDiffusiveRadiationMixedFvPatchScalarField.H
greyDiffusiveRadiationMixedFvPatchScalarField.C
Definition at line 95 of file greyDiffusiveRadiationMixedFvPatchScalarField.H.
Constructor & Destructor Documentation
greyDiffusiveRadiationMixedFvPatchScalarField() [1/5]
greyDiffusiveRadiationMixedFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 41 of file greyDiffusiveRadiationMixedFvPatchScalarField.C.
Referenced by greyDiffusiveRadiationMixedFvPatchScalarField::clone(), and greyDiffusiveRadiationMixedFvPatchScalarField::greyDiffusiveRadiationMixedFvPatchScalarField().
greyDiffusiveRadiationMixedFvPatchScalarField() [2/5]
greyDiffusiveRadiationMixedFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 78 of file greyDiffusiveRadiationMixedFvPatchScalarField.C.
References dictionary::found(), greyDiffusiveRadiationMixedFvPatchScalarField::greyDiffusiveRadiationMixedFvPatchScalarField(), fvPatchField< Type >::operator, fvPatchField< Type >::operator=(), and fvPatch::size().
greyDiffusiveRadiationMixedFvPatchScalarField() [3/5]
greyDiffusiveRadiationMixedFvPatchScalarField (const greyDiffusiveRadiationMixedFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given a.
greyDiffusiveRadiationMixedFvPatchScalarField onto a new patch
Definition at line 58 of file greyDiffusiveRadiationMixedFvPatchScalarField.C.
References greyDiffusiveRadiationMixedFvPatchScalarField::greyDiffusiveRadiationMixedFvPatchScalarField().
greyDiffusiveRadiationMixedFvPatchScalarField() [4/5]
greyDiffusiveRadiationMixedFvPatchScalarField (const greyDiffusiveRadiationMixedFvPatchScalarField & ptf)
Construct as copy.
Definition at line 111 of file greyDiffusiveRadiationMixedFvPatchScalarField.C.
References greyDiffusiveRadiationMixedFvPatchScalarField::greyDiffusiveRadiationMixedFvPatchScalarField().
greyDiffusiveRadiationMixedFvPatchScalarField() [5/5]
greyDiffusiveRadiationMixedFvPatchScalarField (const greyDiffusiveRadiationMixedFvPatchScalarField & ptf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 128 of file greyDiffusiveRadiationMixedFvPatchScalarField.C.
References greyDiffusiveRadiationMixedFvPatchScalarField::updateCoeffs().
Member Function Documentation
TypeName()
TypeName ("greyDiffusiveRadiation")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 146 of file greyDiffusiveRadiationMixedFvPatchScalarField.H.
References greyDiffusiveRadiationMixedFvPatchScalarField::greyDiffusiveRadiationMixedFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 163 of file greyDiffusiveRadiationMixedFvPatchScalarField.H.
References greyDiffusiveRadiationMixedFvPatchScalarField::greyDiffusiveRadiationMixedFvPatchScalarField().
TName() [1/2]
const word& TName () const inline
Return the temperature field name.
Definition at line 179 of file greyDiffusiveRadiationMixedFvPatchScalarField.H.
References greyDiffusiveRadiationMixedFvPatchScalarField::updateCoeffs(), and greyDiffusiveRadiationMixedFvPatchScalarField::write().
TName() [2/2]
word& TName () inline
Return reference to the temperature field name to allow.
adjustment
Definition at line 186 of file greyDiffusiveRadiationMixedFvPatchScalarField.H.
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 147 of file greyDiffusiveRadiationMixedFvPatchScalarField.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), radiativeIntensityRay::dAve(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, UPstream::msgType(), n, Foam::name(), Foam::nl, patchi, Foam::constant::mathematical::pi(), Foam::pow4(), radiativeIntensityRay::Qem(), radiativeIntensityRay::Qin(), radiativeIntensityRay::Qr(), radiation(), Foam::constant::physicoChemical::sigma, and greyDiffusiveRadiationMixedFvPatchScalarField::write().
Referenced by greyDiffusiveRadiationMixedFvPatchScalarField::greyDiffusiveRadiationMixedFvPatchScalarField(), and greyDiffusiveRadiationMixedFvPatchScalarField::TName().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 243 of file greyDiffusiveRadiationMixedFvPatchScalarField.C.
References Foam::makePatchTypeField(), radiation(), write(), and radiationCoupledBase::write().
Referenced by greyDiffusiveRadiationMixedFvPatchScalarField::TName(), and greyDiffusiveRadiationMixedFvPatchScalarField::updateCoeffs().
The documentation for this class was generated from the following files:
src/thermophysicalModels/radiation/derivedFvPatchFields/greyDiffusiveRadiation/greyDiffusiveRadiationMixedFvPatchScalarField.H
src/thermophysicalModels/radiation/derivedFvPatchFields/greyDiffusiveRadiation/greyDiffusiveRadiationMixedFvPatchScalarField.C