OpenFOAM: C Class Reference
C Class Reference
Graphite solid properties.
Public Member Functions
TypeName ("C")
Runtime type information.
C ()
Construct null.
C (const solidProperties &s)
Construct from solidProperties.
C (Istream &is)
Construct from Istream.
C (const dictionary &dict)
Construct from dictionary.
C (const C &s)
Construct copy.
virtual autoPtr< solidProperties > clone () const
Construct and return clone.
void writeData (Ostream &os) const
Write the function coefficients.
Public Member Functions inherited from solidProperties
TypeName ("solidProperties")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, solidProperties,,(),())
declareRunTimeSelectionTable (autoPtr, solidProperties, Istream,(Istream &is),(is))
declareRunTimeSelectionTable (autoPtr, solidProperties, dictionary,(const dictionary &dict),(dict))
solidProperties (scalar rho, scalar Cp, scalar K, scalar Hf, scalar emissivity)
Construct from components.
solidProperties (Istream &is)
Construct from Istream.
solidProperties (const dictionary &dict)
Construct from dictionary.
solidProperties (const solidProperties &s)
Construct copy.
virtual ~solidProperties ()
Destructor.
scalar rho () const
Density [kg/m3].
scalar Cp () const
Specific heat capacity [J/(kg.K)].
scalar K () const
Thermal conductivity [W/(m.K)].
scalar Hf () const
Heat of formation [J/kg].
scalar Hs (const scalar T) const
Sensible enthalpy - reference to Tstd [J/kg].
scalar emissivity () const
Emissivity [].
Friends
Ostream & operator<< (Ostream &os, const C &s)
Ostream Operator.
Additional Inherited Members
Static Public Member Functions inherited from solidProperties
static autoPtr< solidProperties > New (Istream &is)
Return a pointer to a new solidProperties created from input.
static autoPtr< solidProperties > New (const dictionary &dict)
Return a pointer to a new solidProperties created from dictionary.
Detailed Description
Graphite solid properties.
Source files
C.H
C.C
Definition at line 57 of file C.H.
Constructor & Destructor Documentation
C() [1/5]
C ()
Construct null.
Definition at line 41 of file C.C.
References Foam::endl(), and WarningInFunction.
Referenced by targetCoeffTrim::calcCoeffs(), C::clone(), rotorDiskSource::constructGeometry(), rotorDiskSource::createCoordinateSystem(), MRFZone::makeAbsolute(), and MRFZone::makeRelative().
C() [2/5]
C (const solidProperties & s)
Construct from solidProperties.
Definition at line 54 of file C.C.
C() [3/5]
C (Istream & is)
Construct from Istream.
Definition at line 60 of file C.C.
C() [4/5]
C (const dictionary & dict)
Construct from dictionary.
Definition at line 66 of file C.C.
C() [5/5]
C (const C & s)
Construct copy.
Definition at line 72 of file C.C.
Member Function Documentation
TypeName()
TypeName ("C")
Runtime type information.
clone()
virtual autoPtr<solidProperties> clone () const inline virtual
Construct and return clone.
Reimplemented from solidProperties.
Definition at line 85 of file C.H.
References C::C(), C::operator<<, and C::writeData().
writeData()
void writeData (Ostream & os) const virtual
Write the function coefficients.
Reimplemented from solidProperties.
Definition at line 80 of file C.C.
References solidProperties::writeData().
Referenced by C::clone(), and Foam::operator<<().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & os, const C & s) friend
Ostream Operator.
Referenced by C::clone().
The documentation for this class was generated from the following files:
src/thermophysicalModels/properties/solidProperties/C/C.H
src/thermophysicalModels/properties/solidProperties/C/C.C