OpenFOAM: MarshakRadiationFixedTemperatureFvPatchScalarField Class Reference
MarshakRadiationFixedTemperatureFvPatchScalarField Class Reference
Boundary Conditions » Thermophysical boundary conditions
A 'mixed' boundary condition that implements a Marshak condition for the incident radiation field (usually written as G)
Public Member Functions
TypeName ("MarshakRadiationFixedTemperature")
Runtime type information.
MarshakRadiationFixedTemperatureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
MarshakRadiationFixedTemperatureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
MarshakRadiationFixedTemperatureFvPatchScalarField (const MarshakRadiationFixedTemperatureFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given MarshakRadiationFvPatchField onto a new.
MarshakRadiationFixedTemperatureFvPatchScalarField (const MarshakRadiationFixedTemperatureFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
MarshakRadiationFixedTemperatureFvPatchScalarField (const MarshakRadiationFixedTemperatureFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
const scalarField & Trad () const
Return the radiation temperature.
scalarField & Trad ()
Return reference to the radiation temperature to allow.
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchScalarField &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from radiationCoupledBase
TypeName ("radiationCoupledBase")
Runtime type information.
radiationCoupledBase (const fvPatch &patch, const word &calculationMethod, const scalarField &emissivity)
Construct from patch, emissivity mode and emissivity.
radiationCoupledBase (const fvPatch &patch, const word &calculationMethod, const scalarField &emissivity, const fvPatchFieldMapper &mapper)
Construct from patch, emissivity mode and emissivity and mapper.
radiationCoupledBase (const fvPatch &patch, const dictionary &dict)
Construct from patch and dictionary.
virtual ~radiationCoupledBase ()
Destructor.
word emissivityMethod () const
Method to obtain emissivity.
scalarField emissivity () const
Calculate corresponding emissivity field.
void write (Ostream &) const
Write.
Additional Inherited Members
Public Types inherited from radiationCoupledBase
enum emissivityMethodType { SOLIDRADIATION, LOOKUP }
Type of supplied emissivity.
Protected Attributes inherited from radiationCoupledBase
const emissivityMethodType method_
How to get emissivity.
scalarField emissivity_
Emissivity.
Detailed Description
A 'mixed' boundary condition that implements a Marshak condition for the incident radiation field (usually written as G)
The radiation temperature field across the patch is supplied by the user using the Trad entry.
Usage
Property Description Required Default value
T temperature field name no T
Example of the boundary condition specification:
    <patchName>
    {
        type            MarshakRadiationFixedTemperature;
        Trad            uniform 1000;       // radiation temperature field
        value           uniform 0;          // place holder
    }
See also
Foam::radiationCoupledBase Foam::mixedFvPatchField
Source files
MarshakRadiationFixedTemperatureFvPatchScalarField.H
MarshakRadiationFixedTemperatureFvPatchScalarField.C
Definition at line 86 of file MarshakRadiationFixedTemperatureFvPatchScalarField.H.
Constructor & Destructor Documentation
MarshakRadiationFixedTemperatureFvPatchScalarField() [1/5]
MarshakRadiationFixedTemperatureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 37 of file MarshakRadiationFixedTemperatureFvPatchScalarField.C.
Referenced by MarshakRadiationFixedTemperatureFvPatchScalarField::clone(), and MarshakRadiationFixedTemperatureFvPatchScalarField::MarshakRadiationFixedTemperatureFvPatchScalarField().
MarshakRadiationFixedTemperatureFvPatchScalarField() [2/5]
MarshakRadiationFixedTemperatureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 75 of file MarshakRadiationFixedTemperatureFvPatchScalarField.C.
References MarshakRadiationFixedTemperatureFvPatchScalarField::MarshakRadiationFixedTemperatureFvPatchScalarField(), Foam::pow4(), Foam::constant::physicoChemical::sigma, and dimensioned< Type >::value().
MarshakRadiationFixedTemperatureFvPatchScalarField() [3/5]
MarshakRadiationFixedTemperatureFvPatchScalarField (const MarshakRadiationFixedTemperatureFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given MarshakRadiationFvPatchField onto a new.
patch
Definition at line 54 of file MarshakRadiationFixedTemperatureFvPatchScalarField.C.
References MarshakRadiationFixedTemperatureFvPatchScalarField::MarshakRadiationFixedTemperatureFvPatchScalarField().
MarshakRadiationFixedTemperatureFvPatchScalarField() [4/5]
MarshakRadiationFixedTemperatureFvPatchScalarField (const MarshakRadiationFixedTemperatureFvPatchScalarField & ptf)
Construct as copy.
Definition at line 99 of file MarshakRadiationFixedTemperatureFvPatchScalarField.C.
References MarshakRadiationFixedTemperatureFvPatchScalarField::MarshakRadiationFixedTemperatureFvPatchScalarField().
MarshakRadiationFixedTemperatureFvPatchScalarField() [5/5]
MarshakRadiationFixedTemperatureFvPatchScalarField (const MarshakRadiationFixedTemperatureFvPatchScalarField & ptf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 116 of file MarshakRadiationFixedTemperatureFvPatchScalarField.C.
References MarshakRadiationFixedTemperatureFvPatchScalarField::autoMap().
Member Function Documentation
TypeName()
TypeName ("MarshakRadiationFixedTemperature")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 138 of file MarshakRadiationFixedTemperatureFvPatchScalarField.H.
References MarshakRadiationFixedTemperatureFvPatchScalarField::MarshakRadiationFixedTemperatureFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 155 of file MarshakRadiationFixedTemperatureFvPatchScalarField.H.
References MarshakRadiationFixedTemperatureFvPatchScalarField::MarshakRadiationFixedTemperatureFvPatchScalarField().
Trad() [1/2]
const scalarField& Trad () const inline
Return the radiation temperature.
Definition at line 175 of file MarshakRadiationFixedTemperatureFvPatchScalarField.H.
References MarshakRadiationFixedTemperatureFvPatchScalarField::autoMap(), MarshakRadiationFixedTemperatureFvPatchScalarField::rmap(), MarshakRadiationFixedTemperatureFvPatchScalarField::updateCoeffs(), and MarshakRadiationFixedTemperatureFvPatchScalarField::write().
Trad() [2/2]
scalarField& Trad () inline
Return reference to the radiation temperature to allow.
adjustment
Definition at line 182 of file MarshakRadiationFixedTemperatureFvPatchScalarField.H.
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Map (and resize as needed) from self given a mapping object.
Reimplemented from radiationCoupledBase.
Definition at line 135 of file MarshakRadiationFixedTemperatureFvPatchScalarField.C.
References MarshakRadiationFixedTemperatureFvPatchScalarField::rmap().
Referenced by MarshakRadiationFixedTemperatureFvPatchScalarField::MarshakRadiationFixedTemperatureFvPatchScalarField(), and MarshakRadiationFixedTemperatureFvPatchScalarField::Trad().
rmap()
void rmap (const fvPatchScalarField & ptf, const labelList & addr) virtual
Reverse map the given fvPatchField onto this fvPatchField.
Reimplemented from radiationCoupledBase.
Definition at line 146 of file MarshakRadiationFixedTemperatureFvPatchScalarField.C.
References MarshakRadiationFixedTemperatureFvPatchScalarField::rmap().
Referenced by MarshakRadiationFixedTemperatureFvPatchScalarField::autoMap(), MarshakRadiationFixedTemperatureFvPatchScalarField::rmap(), and MarshakRadiationFixedTemperatureFvPatchScalarField::Trad().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 160 of file MarshakRadiationFixedTemperatureFvPatchScalarField.C.
References radiationCoupledBase::emissivity(), UPstream::msgType(), Foam::pow4(), Foam::constant::physicoChemical::sigma, dimensioned< Type >::value(), and MarshakRadiationFixedTemperatureFvPatchScalarField::write().
Referenced by MarshakRadiationFixedTemperatureFvPatchScalarField::Trad().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 194 of file MarshakRadiationFixedTemperatureFvPatchScalarField.C.
References Foam::makePatchTypeField(), write(), radiationCoupledBase::write(), and Field< Type >::writeEntry().
Referenced by MarshakRadiationFixedTemperatureFvPatchScalarField::Trad(), and MarshakRadiationFixedTemperatureFvPatchScalarField::updateCoeffs().
The documentation for this class was generated from the following files:
src/thermophysicalModels/radiation/derivedFvPatchFields/MarshakRadiationFixedTemperature/MarshakRadiationFixedTemperatureFvPatchScalarField.H
src/thermophysicalModels/radiation/derivedFvPatchFields/MarshakRadiationFixedTemperature/MarshakRadiationFixedTemperatureFvPatchScalarField.C