OpenFOAM: MarshakRadiationFvPatchScalarField Class Reference
MarshakRadiationFvPatchScalarField Class Reference
Boundary Conditions » Thermophysical boundary conditions
A 'mixed' boundary condition that implements a Marshak condition for the incident radiation field (usually written as G)
Public Member Functions
TypeName ("MarshakRadiation")
Runtime type information.
MarshakRadiationFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
MarshakRadiationFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
MarshakRadiationFvPatchScalarField (const MarshakRadiationFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given MarshakRadiationFvPatchField onto a new.
MarshakRadiationFvPatchScalarField (const MarshakRadiationFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
MarshakRadiationFvPatchScalarField (const MarshakRadiationFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
const word & TName () const
Return the temperature field name.
word & TName ()
Return reference to the temperature field name to allow.
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchScalarField &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from radiationCoupledBase
TypeName ("radiationCoupledBase")
Runtime type information.
radiationCoupledBase (const fvPatch &patch, const word &calculationMethod, const scalarField &emissivity)
Construct from patch, emissivity mode and emissivity.
radiationCoupledBase (const fvPatch &patch, const word &calculationMethod, const scalarField &emissivity, const fvPatchFieldMapper &mapper)
Construct from patch, emissivity mode and emissivity and mapper.
radiationCoupledBase (const fvPatch &patch, const dictionary &dict)
Construct from patch and dictionary.
virtual ~radiationCoupledBase ()
Destructor.
word emissivityMethod () const
Method to obtain emissivity.
scalarField emissivity () const
Calculate corresponding emissivity field.
void write (Ostream &) const
Write.
Additional Inherited Members
Public Types inherited from radiationCoupledBase
enum emissivityMethodType { SOLIDRADIATION, LOOKUP }
Type of supplied emissivity.
Protected Attributes inherited from radiationCoupledBase
const emissivityMethodType method_
How to get emissivity.
scalarField emissivity_
Emissivity.
Detailed Description
A 'mixed' boundary condition that implements a Marshak condition for the incident radiation field (usually written as G)
The radiation temperature is retrieved from the mesh database, using a user specified temperature field name.
Usage
Property Description Required Default value
T temperature field name no T
Example of the boundary condition specification:
    <patchName>
    {
        type            MarshakRadiation;
        T               T;
        value           uniform 0;
    }
See also
Foam::radiationCoupledBase Foam::mixedFvPatchField
Source files
MarshakRadiationFvPatchScalarField.H
MarshakRadiationFvPatchScalarField.C
Definition at line 86 of file MarshakRadiationFvPatchScalarField.H.
Constructor & Destructor Documentation
MarshakRadiationFvPatchScalarField() [1/5]
MarshakRadiationFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 36 of file MarshakRadiationFvPatchScalarField.C.
Referenced by MarshakRadiationFvPatchScalarField::clone(), and MarshakRadiationFvPatchScalarField::MarshakRadiationFvPatchScalarField().
MarshakRadiationFvPatchScalarField() [2/5]
MarshakRadiationFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 72 of file MarshakRadiationFvPatchScalarField.C.
References dictionary::found(), MarshakRadiationFvPatchScalarField::MarshakRadiationFvPatchScalarField(), scalarField(), and fvPatch::size().
MarshakRadiationFvPatchScalarField() [3/5]
MarshakRadiationFvPatchScalarField (const MarshakRadiationFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given MarshakRadiationFvPatchField onto a new.
patch
Definition at line 52 of file MarshakRadiationFvPatchScalarField.C.
References MarshakRadiationFvPatchScalarField::MarshakRadiationFvPatchScalarField().
MarshakRadiationFvPatchScalarField() [4/5]
MarshakRadiationFvPatchScalarField (const MarshakRadiationFvPatchScalarField & ptf)
Construct as copy.
Definition at line 101 of file MarshakRadiationFvPatchScalarField.C.
References MarshakRadiationFvPatchScalarField::MarshakRadiationFvPatchScalarField().
MarshakRadiationFvPatchScalarField() [5/5]
MarshakRadiationFvPatchScalarField (const MarshakRadiationFvPatchScalarField & ptf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 117 of file MarshakRadiationFvPatchScalarField.C.
References MarshakRadiationFvPatchScalarField::autoMap().
Member Function Documentation
TypeName()
TypeName ("MarshakRadiation")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 138 of file MarshakRadiationFvPatchScalarField.H.
References MarshakRadiationFvPatchScalarField::MarshakRadiationFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 155 of file MarshakRadiationFvPatchScalarField.H.
References MarshakRadiationFvPatchScalarField::MarshakRadiationFvPatchScalarField().
TName() [1/2]
const word& TName () const inline
Return the temperature field name.
Definition at line 171 of file MarshakRadiationFvPatchScalarField.H.
References MarshakRadiationFvPatchScalarField::autoMap(), MarshakRadiationFvPatchScalarField::rmap(), MarshakRadiationFvPatchScalarField::updateCoeffs(), and MarshakRadiationFvPatchScalarField::write().
TName() [2/2]
word& TName () inline
Return reference to the temperature field name to allow.
adjustment
Definition at line 178 of file MarshakRadiationFvPatchScalarField.H.
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Map (and resize as needed) from self given a mapping object.
Reimplemented from radiationCoupledBase.
Definition at line 136 of file MarshakRadiationFvPatchScalarField.C.
References MarshakRadiationFvPatchScalarField::rmap().
Referenced by MarshakRadiationFvPatchScalarField::MarshakRadiationFvPatchScalarField(), and MarshakRadiationFvPatchScalarField::TName().
rmap()
void rmap (const fvPatchScalarField & ptf, const labelList & addr) virtual
Reverse map the given fvPatchField onto this fvPatchField.
Reimplemented from radiationCoupledBase.
Definition at line 146 of file MarshakRadiationFvPatchScalarField.C.
Referenced by MarshakRadiationFvPatchScalarField::autoMap(), and MarshakRadiationFvPatchScalarField::TName().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 156 of file MarshakRadiationFvPatchScalarField.C.
References radiationCoupledBase::emissivity(), UPstream::msgType(), Foam::pow4(), Foam::constant::physicoChemical::sigma, and dimensioned< Type >::value().
Referenced by MarshakRadiationFvPatchScalarField::TName().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 193 of file MarshakRadiationFvPatchScalarField.C.
References Foam::makePatchTypeField(), write(), and radiationCoupledBase::write().
Referenced by MarshakRadiationFvPatchScalarField::TName().
The documentation for this class was generated from the following files:
src/thermophysicalModels/radiation/derivedFvPatchFields/MarshakRadiation/MarshakRadiationFvPatchScalarField.H
src/thermophysicalModels/radiation/derivedFvPatchFields/MarshakRadiation/MarshakRadiationFvPatchScalarField.C