OpenFOAM: solidProperties Class Reference
solidProperties Class Reference
The thermophysical properties of a solid.
Public Member Functions
TypeName ("solidProperties")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, solidProperties,,(),())
declareRunTimeSelectionTable (autoPtr, solidProperties, Istream,(Istream &is),(is))
declareRunTimeSelectionTable (autoPtr, solidProperties, dictionary,(const dictionary &dict),(dict))
solidProperties (scalar rho, scalar Cp, scalar K, scalar Hf, scalar emissivity)
Construct from components.
solidProperties (Istream &is)
Construct from Istream.
solidProperties (const dictionary &dict)
Construct from dictionary.
solidProperties (const solidProperties &s)
Construct copy.
virtual autoPtr< solidProperties > clone () const
Construct and return clone.
virtual ~solidProperties ()
Destructor.
scalar rho () const
Density [kg/m3].
scalar Cp () const
Specific heat capacity [J/(kg.K)].
scalar K () const
Thermal conductivity [W/(m.K)].
scalar Hf () const
Heat of formation [J/kg].
scalar Hs (const scalar T) const
Sensible enthalpy - reference to Tstd [J/kg].
scalar emissivity () const
Emissivity [].
virtual void writeData (Ostream &os) const
Write the solidProperties properties.
Static Public Member Functions
static autoPtr< solidProperties > New (Istream &is)
Return a pointer to a new solidProperties created from input.
static autoPtr< solidProperties > New (const dictionary &dict)
Return a pointer to a new solidProperties created from dictionary.
Friends
Ostream & operator<< (Ostream &os, const solidProperties &s)
Detailed Description
The thermophysical properties of a solid.
Source files
solidProperties.H
solidProperties.C
Definition at line 60 of file solidProperties.H.
Constructor & Destructor Documentation
solidProperties() [1/4]
solidProperties (scalar rho, scalar Cp, scalar K, scalar Hf, scalar emissivity)
Construct from components.
Definition at line 41 of file solidProperties.C.
Referenced by solidProperties::clone(), and solidProperties::New().
solidProperties() [2/4]
solidProperties (Istream & is)
Construct from Istream.
Definition at line 57 of file solidProperties.C.
solidProperties() [3/4]
solidProperties (const dictionary & dict)
Construct from dictionary.
Definition at line 67 of file solidProperties.C.
solidProperties() [4/4]
solidProperties (const solidProperties & s)
Construct copy.
Definition at line 77 of file solidProperties.C.
~solidProperties()
virtual ~solidProperties () inline virtual
Destructor.
Definition at line 155 of file solidProperties.H.
References solidProperties::Cp(), solidProperties::emissivity(), solidProperties::Hf(), solidProperties::Hs(), solidProperties::K(), solidProperties::operator<<, solidProperties::rho(), Foam::T(), and solidProperties::writeData().
Member Function Documentation
TypeName()
TypeName ("solidProperties")
Runtime type information.
declareRunTimeSelectionTable() [1/3]
declareRunTimeSelectionTable (autoPtr , solidProperties , () , ())
declareRunTimeSelectionTable() [2/3]
declareRunTimeSelectionTable (autoPtr , solidProperties , Istream , (Istream &is) , (is))
declareRunTimeSelectionTable() [3/3]
declareRunTimeSelectionTable (autoPtr , solidProperties , dictionary , (const dictionary &dict) , (dict))
clone()
virtual autoPtr<solidProperties> clone () const inline virtual
Construct and return clone.
Reimplemented in ash, CaCO3, and C.
Definition at line 139 of file solidProperties.H.
References solidProperties::New(), and solidProperties::solidProperties().
New() [1/2]
Foam::autoPtr< Foam::solidProperties > New (Istream & is) static
Return a pointer to a new solidProperties created from input.
Definition at line 31 of file solidPropertiesNew.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, InfoInFunction, Foam::nl, and solidProperties::solidProperties().
Referenced by solidProperties::clone(), and solidMixtureProperties::solidMixtureProperties().
New() [2/2]
Foam::autoPtr< Foam::solidProperties > New (const dictionary & dict) static
Return a pointer to a new solidProperties created from dictionary.
Definition at line 75 of file solidPropertiesNew.C.
References dictionaryName::dictName(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, InfoInFunction, dictionary::lookup(), Foam::nl, solidProperties::solidProperties(), and dictionary::subDict().
rho()
Foam::scalar rho () const inline
Density [kg/m3].
Definition at line 30 of file solidPropertiesI.H.
Referenced by solidProperties::~solidProperties().
Cp()
Foam::scalar Cp () const inline
Specific heat capacity [J/(kg.K)].
Definition at line 36 of file solidPropertiesI.H.
Referenced by solidProperties::~solidProperties().
K()
Foam::scalar K () const inline
Thermal conductivity [W/(m.K)].
Definition at line 42 of file solidPropertiesI.H.
Referenced by solidProperties::~solidProperties().
Hf()
Foam::scalar Hf () const inline
Heat of formation [J/kg].
Definition at line 48 of file solidPropertiesI.H.
Referenced by solidProperties::~solidProperties().
Hs()
Foam::scalar Hs (const scalar T) const inline
Sensible enthalpy - reference to Tstd [J/kg].
Definition at line 54 of file solidPropertiesI.H.
References Foam::constant::standard::Tstd.
Referenced by solidProperties::~solidProperties().
emissivity()
Foam::scalar emissivity () const inline
Emissivity [].
Definition at line 60 of file solidPropertiesI.H.
Referenced by solidProperties::~solidProperties().
writeData()
void writeData (Ostream & os) const virtual
Write the solidProperties properties.
Reimplemented in ash, CaCO3, and C.
Definition at line 89 of file solidProperties.C.
References token::SPACE.
Referenced by Foam::operator<<(), C::writeData(), ash::writeData(), CaCO3::writeData(), and solidProperties::~solidProperties().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & os, const solidProperties & s) friend
Referenced by solidProperties::~solidProperties().
The documentation for this class was generated from the following files:
src/thermophysicalModels/properties/solidProperties/solidProperties/solidProperties.H
src/thermophysicalModels/properties/solidProperties/solidProperties/solidProperties.C
src/thermophysicalModels/properties/solidProperties/solidProperties/solidPropertiesI.H
src/thermophysicalModels/properties/solidProperties/solidProperties/solidPropertiesNew.C