OpenFOAM: greyMeanAbsorptionEmission Class Reference
greyMeanAbsorptionEmission Class Reference
greyMeanAbsorptionEmission radiation absorption and emission coefficients for continuous phase
Public Member Functions
TypeName ("greyMeanAbsorptionEmission")
Runtime type information.
greyMeanAbsorptionEmission (const dictionary &dict, const fvMesh &mesh)
Construct from components.
virtual ~greyMeanAbsorptionEmission ()
Destructor.
tmp< volScalarField > aCont (const label bandI=0) const
Absorption coefficient for continuous phase.
tmp< volScalarField > eCont (const label bandI=0) const
Emission coefficient for continuous phase.
tmp< volScalarField > ECont (const label bandI=0) const
Emission contribution for continuous phase.
bool isGrey () const
Flag for whether the absorption/emission is for a grey gas.
Public Member Functions inherited from absorptionEmissionModel
TypeName ("absorptionEmissionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, absorptionEmissionModel, dictionary,(const dictionary &dict, const fvMesh &mesh),(dict, mesh))
Declare runtime constructor selection table.
absorptionEmissionModel (const dictionary &dict, const fvMesh &mesh)
Construct from components.
virtual ~absorptionEmissionModel ()
Destructor.
const fvMesh & mesh () const
Reference to the mesh.
const dictionary & dict () const
Reference to the dictionary.
virtual tmp< volScalarField > a (const label bandI=0) const
Absorption coefficient (net)
virtual tmp< volScalarField > aDisp (const label bandI=0) const
Absorption coefficient for dispersed phase.
virtual tmp< volScalarField > e (const label bandI=0) const
Emission coefficient (net)
virtual tmp< volScalarField > eDisp (const label bandI=0) const
Return emission coefficient for dispersed phase.
virtual tmp< volScalarField > E (const label bandI=0) const
Emission contribution (net)
virtual tmp< volScalarField > EDisp (const label bandI=0) const
Emission contribution for dispersed phase.
virtual label nBands () const
Const access to the number of bands - defaults to 1 for grey.
virtual const Vector2D< scalar > & bands (const label n) const
Const access to the bands - defaults to Vector2D::one for grey.
virtual void correct (volScalarField &a, PtrList< volScalarField > &aj) const
Correct absorption coefficients.
Public Attributes
absorptionCoeffs coeffs_ [nSpecies_]
Static Public Attributes
static const int nSpecies_ = 5
Additional Inherited Members
Static Public Member Functions inherited from absorptionEmissionModel
static autoPtr< absorptionEmissionModel > New (const dictionary &dict, const fvMesh &mesh)
Selector.
Protected Attributes inherited from absorptionEmissionModel
const dictionary dict_
Radiation model dictionary.
const fvMesh & mesh_
Reference to the fvMesh.
Detailed Description
greyMeanAbsorptionEmission radiation absorption and emission coefficients for continuous phase
The coefficients for the species in the Look up table have to be specified for use in moles x P [atm], i.e. (k[i] = species[i]*p*9.869231e-6).
The coefficients for CO and soot or any other added are multiplied by the respective mass fraction being solved
All the species in the dictionary need either to be in the look-up table or being solved. Conversely, all the species solved do not need to be included in the calculation of the absorption coefficient
The names of the species in the absorption dictionary must match exactly the name in the look-up table or the name of the field being solved
The look-up table ("speciesTable") file should be in constant
i.e. dictionary
    LookUpTableFileName     "speciesTable";
    EhrrCoeff       0.0;
    CO2
    {
        Tcommon     300.;   // Common Temp
        invTemp     true;   // Is the polynomial using inverse temperature?
        Tlow        300.;   // Low Temp
        Thigh       2500.;  // High Temp
        loTcoeffs           // coeffs for T < Tcommon
        (
            0               //  a0            +
            0               //  a1*T          +
            0               //  a2*T^(+/-)2   +
            0               //  a3*T^(+/-)3   +
            0               //  a4*T^(+/-)4   +
            0               //  a5*T^(+/-)5   +
        );
        hiTcoeffs           // coeffs for T > Tcommon
        (
            18.741
            -121.31e3
            273.5e6
            -194.05e9
            56.31e12
            -5.8169e15
        );
    }
Source files
greyMeanAbsorptionEmission.H
greyMeanAbsorptionEmission.C
Definition at line 104 of file greyMeanAbsorptionEmission.H.
Constructor & Destructor Documentation
greyMeanAbsorptionEmission()
greyMeanAbsorptionEmission (const dictionary & dict, const fvMesh & mesh)
Construct from components.
Definition at line 53 of file greyMeanAbsorptionEmission.C.
References Foam::abort(), TimePaths::constant(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAllConstIter(), objectRegistry::foundObject(), Foam::Info, objectRegistry::lookupObject(), mesh, Foam::name(), Foam::nl, dictionary::subDict(), fvMesh::time(), and Y.
~greyMeanAbsorptionEmission()
~greyMeanAbsorptionEmission () virtual
Destructor.
Definition at line 182 of file greyMeanAbsorptionEmission.C.
Member Function Documentation
TypeName()
TypeName ("greyMeanAbsorptionEmission")
Runtime type information.
aCont()
Foam::tmp< Foam::volScalarField > aCont (const label bandI = 0) const virtual
Absorption coefficient for continuous phase.
Reimplemented from absorptionEmissionModel.
Definition at line 189 of file greyMeanAbsorptionEmission.C.
References Foam::constant::physicoChemical::b, Foam::dimLength, Foam::dimless, forAll, forAllConstIter(), mesh, n, Foam::name(), IOobject::NO_READ, IOobject::NO_WRITE, p, Foam::paToAtm(), tmp< T >::ref(), s(), basicMultiComponentMixture::species(), Foam::T(), timeName, basicSpecieMixture::W(), and basicMultiComponentMixture::Y().
eCont()
Foam::tmp< Foam::volScalarField > eCont (const label bandI = 0) const virtual
Emission coefficient for continuous phase.
Reimplemented from absorptionEmissionModel.
Definition at line 270 of file greyMeanAbsorptionEmission.C.
ECont()
Foam::tmp< Foam::volScalarField > ECont (const label bandI = 0) const virtual
Emission contribution for continuous phase.
Reimplemented from absorptionEmissionModel.
Definition at line 277 of file greyMeanAbsorptionEmission.C.
References Foam::dimEnergy, DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimLength, Foam::dimMass, Foam::dimTime, Foam::dimVolume, dQ, Foam::endl(), Foam::name(), IOobject::NO_READ, IOobject::NO_WRITE, Foam::pow3(), tmp< T >::ref(), and WarningInFunction.
isGrey()
bool isGrey () const inline virtual
Flag for whether the absorption/emission is for a grey gas.
Reimplemented from absorptionEmissionModel.
Definition at line 185 of file greyMeanAbsorptionEmission.H.
Member Data Documentation
nSpecies_
const int nSpecies_ = 5 static
Definition at line 113 of file greyMeanAbsorptionEmission.H.
coeffs_
absorptionCoeffs coeffs_[nSpecies_]
Definition at line 116 of file greyMeanAbsorptionEmission.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/radiation/submodels/absorptionEmissionModel/greyMeanAbsorptionEmission/greyMeanAbsorptionEmission.H
src/thermophysicalModels/radiation/submodels/absorptionEmissionModel/greyMeanAbsorptionEmission/greyMeanAbsorptionEmission.C