OpenFOAM: fvDOM Class Reference
fvDOM Class Reference
Finite Volume Discrete Ordinates Method. Solves the RTE equation for n directions in a participating media, not including scatter.
Public Member Functions
TypeName ("fvDOM")
Runtime type information.
fvDOM (const volScalarField &T)
Construct from components.
fvDOM (const dictionary &dict, const volScalarField &T)
Construct from components.
virtual ~fvDOM ()
Destructor.
void calculate ()
Solve radiation equation(s)
bool read ()
Read radiation properties dictionary.
void updateG ()
Update G and calculate total heat flux on boundary.
void setRayIdLambdaId (const word &name, label &rayId, label &lambdaId) const
Set the rayId and lambdaId from by decomposing an intensity.
virtual tmp< volScalarField > Rp () const
Source term component (for power of T^4)
virtual tmp< volScalarField::Internal > Ru () const
Source term component (constant)
const radiativeIntensityRay & IRay (const label rayI) const
Ray intensity for rayI.
const volScalarField & IRayLambda (const label rayI, const label lambdaI) const
Ray intensity for rayI and lambda bandwidth.
label nTheta () const
Number of angles in theta.
label nPhi () const
Number of angles in phi.
label nRay () const
Number of rays.
label nLambda () const
Number of wavelengths.
const volScalarField & a () const
Const access to total absorption coefficient.
const volScalarField & aLambda (const label lambdaI) const
Const access to wavelength total absorption coefficient.
const volScalarField & G () const
Const access to incident radiation field.
const volScalarField & Qr () const
Const access to total radiative heat flux field.
const volScalarField & Qin () const
Const access to incident radiative heat flux field.
const volScalarField & Qem () const
Const access to emitted radiative heat flux field.
const blackBodyEmission & blackBody () const
Const access to black body.
scalar omegaMax () const
Return omegaMax.
Public Member Functions inherited from radiationModel
TypeName ("radiationModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, radiationModel, T,(const volScalarField &T),(T))
declareRunTimeSelectionTable (autoPtr, radiationModel, dictionary,(const dictionary &dict, const volScalarField &T),(dict, T))
radiationModel (const volScalarField &T)
Null constructor.
radiationModel (const word &type, const volScalarField &T)
Construct from components.
radiationModel (const word &type, const dictionary &dict, const volScalarField &T)
Construct from components.
virtual ~radiationModel ()
Destructor.
virtual void correct ()
Main update/correction routine.
const Switch radiation () const
Radiation model on/off flag.
virtual tmp< fvScalarMatrix > Sh (fluidThermo &thermo) const
Energy source term.
virtual tmp< fvScalarMatrix > ST (const dimensionedScalar &rhoCp, volScalarField &T) const
Temperature source term.
const absorptionEmissionModel & absorptionEmission () const
Access to absorptionEmission model.
const sootModel & soot () const
Access to soot Model.
Public Member Functions inherited from IOdictionary
TypeName ("dictionary")
IOdictionary (const IOobject &)
Construct given an IOobject.
IOdictionary (const IOobject &, const dictionary &)
Construct given an IOobject and dictionary.
IOdictionary (const IOobject &, Istream &)
Construct given an IOobject and Istream.
virtual ~IOdictionary ()
Destructor.
const word & name () const
Name function is needed to disambiguate those inherited.
bool readData (Istream &)
ReadData function required for regIOobject read operation.
bool writeData (Ostream &) const
WriteData function required for regIOobject write operation.
void operator= (const IOdictionary &)
Assignment of other IOdictionary's entries to this IOdictionary.
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, transferring registry registration to copy.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Construct as copy with new name, transfering registry registration.
regIOobject (const IOobject &, const regIOobject &)
Construct as copy with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
virtual void rename (const word &newName)
Rename.
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType) const
Write using given format, version and compression.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Public Member Functions inherited from dictionary
ClassName ("dictionary")
dictionary ()
Construct top-level dictionary null.
dictionary (const fileName &name)
Construct top-level empty dictionary with given name.
dictionary (const fileName &name, const dictionary &parentDict, Istream &)
Construct given the entry name, parent dictionary and Istream,.
dictionary (Istream &)
Construct top-level dictionary from Istream,.
dictionary (Istream &, const bool keepHeader)
Construct top-level dictionary from Istream,.
dictionary (const dictionary &parentDict, const dictionary &)
Construct as copy given the parent dictionary.
dictionary (const dictionary &)
Construct top-level dictionary as copy.
dictionary (const dictionary *)
Construct top-level dictionary as copy from pointer to dictionary.
dictionary (const dictionary &parentDict, const Xfer< dictionary > &)
Construct by transferring parameter contents given parent dictionary.
dictionary (const Xfer< dictionary > &)
Construct top-level dictionary by transferring parameter contents.
autoPtr< dictionary > clone () const
Construct and return clone.
virtual ~dictionary ()
Destructor.
const dictionary & parent () const
Return the parent dictionary.
const dictionary & topDict () const
Return the top of the tree.
label startLineNumber () const
Return line number of first token in dictionary.
label endLineNumber () const
Return line number of last token in dictionary.
SHA1Digest digest () const
Return the SHA1 digest of the dictionary contents.
tokenList tokens () const
Return the dictionary as a list of tokens.
bool found (const word &, bool recursive=false, bool patternMatch=true) const
Search dictionary for given keyword.
const entry * lookupEntryPtr (const word &, bool recursive, bool patternMatch) const
Find and return an entry data stream pointer if present.
entry * lookupEntryPtr (const word &, bool recursive, bool patternMatch)
Find and return an entry data stream pointer for manipulation.
const entry & lookupEntry (const word &, bool recursive, bool patternMatch) const
Find and return an entry data stream if present otherwise error.
ITstream & lookup (const word &, bool recursive=false, bool patternMatch=true) const
Find and return an entry data stream.
template<class T >
T lookupOrDefault (const word &, const T &, bool recursive=false, bool patternMatch=true) const
Find and return a T,.
template<class T >
T lookupOrAddDefault (const word &, const T &, bool recursive=false, bool patternMatch=true)
Find and return a T, if not found return the given.
template<class T >
bool readIfPresent (const word &, T &, bool recursive=false, bool patternMatch=true) const
Find an entry if present, and assign to T.
const entry * lookupScopedEntryPtr (const word &, bool recursive, bool patternMatch) const
Find and return an entry data stream pointer if present.
bool isDict (const word &) const
Check if entry is a sub-dictionary.
const dictionary * subDictPtr (const word &) const
Find and return a sub-dictionary pointer if present.
const dictionary & subDict (const word &) const
Find and return a sub-dictionary.
dictionary & subDict (const word &)
Find and return a sub-dictionary for manipulation.
dictionary subOrEmptyDict (const word &, const bool mustRead=false) const
Find and return a sub-dictionary as a copy, or.
wordList toc () const
Return the table of contents.
wordList sortedToc () const
Return the sorted table of contents.
List< keyType > keys (bool patterns=false) const
Return the list of available keys or patterns.
bool substituteKeyword (const word &keyword)
Substitute the given keyword prepended by '$' with the.
bool substituteScopedKeyword (const word &keyword)
Substitute the given scoped keyword prepended by '$' with the.
bool add (entry *, bool mergeEntry=false)
Add a new entry.
void add (const entry &, bool mergeEntry=false)
Add an entry.
void add (const keyType &, const word &, bool overwrite=false)
Add a word entry.
void add (const keyType &, const string &, bool overwrite=false)
Add a string entry.
void add (const keyType &, const label, bool overwrite=false)
Add a label entry.
void add (const keyType &, const scalar, bool overwrite=false)
Add a scalar entry.
void add (const keyType &, const dictionary &, bool mergeEntry=false)
Add a dictionary entry.
template<class T >
void add (const keyType &, const T &, bool overwrite=false)
Add a T entry.
void set (entry *)
Assign a new entry, overwrite any existing entry.
void set (const entry &)
Assign a new entry, overwrite any existing entry.
void set (const keyType &, const dictionary &)
Assign a dictionary entry, overwrite any existing entry.
template<class T >
void set (const keyType &, const T &)
Assign a T entry, overwrite any existing entry.
bool remove (const word &)
Remove an entry specified by keyword.
bool changeKeyword (const keyType &oldKeyword, const keyType &newKeyword, bool forceOverwrite=false)
Change the keyword for an entry,.
bool merge (const dictionary &)
Merge entries from the given dictionary.
void clear ()
Clear the dictionary.
void transfer (dictionary &)
Transfer the contents of the argument and annul the argument.
Xfer< dictionary > xfer ()
Transfer contents to the Xfer container.
bool read (Istream &)
Read dictionary from Istream.
bool read (Istream &, const bool keepHeader)
Read dictionary from Istream, optionally keeping the header.
void write (Ostream &, const bool subDict=true) const
Write dictionary, normally with sub-dictionary formatting.
ITstream & operator[] (const word &) const
Find and return entry.
void operator= (const dictionary &)
void operator+= (const dictionary &)
Include entries from the given dictionary.
void operator|= (const dictionary &)
Conditionally include entries from the given dictionary.
void operator<<= (const dictionary &)
Unconditionally include entries from the given dictionary.
Public Member Functions inherited from dictionaryName
dictionaryName ()
Construct dictionaryName null.
dictionaryName (const fileName &name)
Construct dictionaryName as copy of the given fileName.
const fileName & name () const
Return the dictionary name.
fileName & name ()
Return the dictionary name.
const word dictName () const
Return the local dictionary name (final part of scoped name)
Public Member Functions inherited from ILList< LListBase, T >
ILList ()
Null construct.
ILList (T *a)
Construct given initial T.
ILList (Istream &)
Construct from Istream.
ILList (const ILList< LListBase, T > &)
Construct as copy.
template<class CloneArg >
ILList (const ILList< LListBase, T > &lst, const CloneArg &cloneArg)
Copy constructor with additional argument for clone.
template<class INew >
ILList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
~ILList ()
Destructor.
bool eraseHead ()
Remove the head element specified from the list and delete it.
bool erase (T *p)
Remove the specified element from the list and delete it.
void clear ()
Clear the contents of the list.
void transfer (ILList< LListBase, T > &)
Transfer the contents of the argument into this List.
void operator= (const ILList< LListBase, T > &)
Assignment operator.
Public Member Functions inherited from UILList< LListBase, T >
UILList ()
Null construct.
UILList (T *a)
Construct given initial T.
UILList (const UILList< LListBase, T > &)
Construct as copy.
T * first ()
Return the first entry.
const T * first () const
Return the first entry.
T * last ()
Return the last entry.
const T * last () const
Return the last entry.
T * removeHead ()
Remove and return head.
T * remove (T *p)
Remove and return element.
T * remove (iterator &it)
Remove and return specified by iterator.
void operator= (const UILList< LListBase, T > &)
iterator begin ()
const iterator & end ()
const_iterator cbegin () const
const const_iterator & cend () const
const_iterator begin () const
const const_iterator & end () const
const_reverse_iterator crbegin () const
const const_reverse_iterator & crend () const
const_reverse_iterator rbegin () const
const const_reverse_iterator & rend () const
bool operator== (const UILList< LListBase, T > &) const
Equality operation on ULists of the same type.
bool operator!= (const UILList< LListBase, T > &) const
The opposite of the equality operation. Takes linear time.
Additional Inherited Members
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Public Types inherited from UILList< LListBase, T >
typedef T value_type
Type of values the DLList contains.
typedef T & reference
Type that can be used for storing into DLList::value_type.
typedef const T & const_reference
Type that can be used for storing into constant.
typedef label size_type
The type that can represent the size of a DLList.
typedef LListBase::iterator LListBase_iterator
typedef LListBase::const_iterator LListBase_const_iterator
Static Public Member Functions inherited from radiationModel
static autoPtr< radiationModel > New (const volScalarField &T)
Return a reference to the selected radiation model.
static autoPtr< radiationModel > New (const dictionary &dict, const volScalarField &T)
Return a reference to the selected radiation model.
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Static Public Member Functions inherited from dictionary
static autoPtr< dictionary > New (Istream &)
Construct top-level dictionary on freestore from Istream.
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Static Public Attributes inherited from dictionary
static const dictionary null
Null dictionary.
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Protected Attributes inherited from radiationModel
const fvMesh & mesh_
Reference to the mesh database.
const Time & time_
Reference to the time database.
const volScalarField & T_
Reference to the temperature field.
Switch radiation_
Radiation model on/off flag.
dictionary coeffs_
Radiation model dictionary.
label solverFreq_
Radiation solver frequency - number flow solver iterations per.
bool firstIter_
Flag to enable radiation model to be evaluated on first iteration.
autoPtr< absorptionEmissionModel > absorptionEmission_
Absorption/emission model.
autoPtr< scatterModel > scatter_
Scatter model.
autoPtr< sootModel > soot_
Soot model.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
Finite Volume Discrete Ordinates Method. Solves the RTE equation for n directions in a participating media, not including scatter.
Available absorption models: constantAbsorptionEmission greyMeanAbsoprtionEmission wideBandAbsorptionEmission
i.e. dictionary
    fvDOMCoeffs
    {
        nPhi        4;          // azimuthal angles in PI/2 on X-Y.
                                //(from Y to X)
        nTheta      0;          // polar angles in PI (from Z to X-Y plane)
        convergence 1e-3;       // convergence criteria for radiation
                                //iteration
        maxIter     4;          // maximum number of iterations
    }
    solverFreq   1; // Number of flow iterations per radiation iteration
The total number of solid angles is 4*nPhi*nTheta.
In 1D the direction of the rays is X (nPhi and nTheta are ignored) In 2D the direction of the rays is on X-Y plane (only nPhi is considered) In 3D (nPhi and nTheta are considered)
Source files
fvDOM.H
fvDOM.C
Definition at line 80 of file fvDOM.H.
Constructor & Destructor Documentation
fvDOM() [1/2]
fvDOM (const volScalarField & T)
Construct from components.
Definition at line 209 of file fvDOM.C.
fvDOM() [2/2]
fvDOM (const dictionary & dict, const volScalarField & T)
Construct from components.
Definition at line 293 of file fvDOM.C.
~fvDOM()
~fvDOM () virtual
Destructor.
Definition at line 381 of file fvDOM.C.
Member Function Documentation
TypeName()
TypeName ("fvDOM")
Runtime type information.
calculate()
void calculate () virtual
Solve radiation equation(s)
Implements radiationModel.
Definition at line 404 of file fvDOM.C.
References radiationModel::absorptionEmission_, Foam::endl(), forAll, Foam::Info, Foam::max(), and fvDOM::updateG().
read()
bool read () virtual
Read radiation properties dictionary.
Implements radiationModel.
Definition at line 387 of file fvDOM.C.
References radiationModel::coeffs_, radiationModel::read(), and dictionary::readIfPresent().
updateG()
void updateG ()
Update G and calculate total heat flux on boundary.
Definition at line 490 of file fvDOM.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), Foam::dimMass, Foam::dimTime, forAll, Foam::pow3(), and fvDOM::setRayIdLambdaId().
Referenced by fvDOM::calculate().
setRayIdLambdaId()
void setRayIdLambdaId (const word & name, label & rayId, label & lambdaId) const
Set the rayId and lambdaId from by decomposing an intensity.
field name
Definition at line 509 of file fvDOM.C.
References Foam::readLabel().
Referenced by fvDOM::updateG().
Rp()
Foam::tmp< Foam::volScalarField > Rp () const virtual
Source term component (for power of T^4)
Implements radiationModel.
Definition at line 441 of file fvDOM.C.
References radiationModel::absorptionEmission_, radiationModel::mesh_, IOobject::NO_READ, IOobject::NO_WRITE, Foam::constant::physicoChemical::sigma, fvMesh::time(), and Time::timeName().
Ru()
Foam::tmp< Foam::DimensionedField< Foam::scalar, Foam::volMesh > > Ru () const virtual
Source term component (constant)
Implements radiationModel.
Definition at line 464 of file fvDOM.C.
References fvDOM::a(), radiationModel::absorptionEmission_, blackBodyEmission::correct(), and fvDOM::G().
IRay()
const Foam::radiation::radiativeIntensityRay & IRay (const label rayI) const inline
Ray intensity for rayI.
Definition at line 28 of file fvDOM.H.
IRayLambda()
const Foam::volScalarField & IRayLambda (const label rayI, const label lambdaI) const inline
Ray intensity for rayI and lambda bandwidth.
Definition at line 36 of file fvDOM.H.
nTheta()
Foam::label nTheta () const inline
Number of angles in theta.
Definition at line 45 of file fvDOM.H.
nPhi()
Foam::label nPhi () const inline
Number of angles in phi.
Definition at line 51 of file fvDOM.H.
nRay()
Foam::label nRay () const inline
Number of rays.
Definition at line 57 of file fvDOM.H.
nLambda()
Foam::label nLambda () const inline
Number of wavelengths.
Definition at line 63 of file fvDOM.H.
a()
const Foam::volScalarField & a () const inline
Const access to total absorption coefficient.
Definition at line 69 of file fvDOM.H.
References radiation().
Referenced by fvDOM::Ru().
aLambda()
const Foam::volScalarField & aLambda (const label lambdaI) const inline
Const access to wavelength total absorption coefficient.
Definition at line 76 of file fvDOM.H.
G()
const Foam::volScalarField & G () const inline
Const access to incident radiation field.
Definition at line 84 of file fvDOM.H.
Referenced by fvDOM::Ru().
Qr()
const Foam::volScalarField & Qr () const inline
Const access to total radiative heat flux field.
Definition at line 90 of file fvDOM.H.
Qin()
const Foam::volScalarField & Qin () const inline
Const access to incident radiative heat flux field.
Definition at line 95 of file fvDOM.H.
Qem()
const Foam::volScalarField & Qem () const inline
Const access to emitted radiative heat flux field.
Definition at line 101 of file fvDOM.H.
blackBody()
const Foam::radiation::blackBodyEmission & blackBody () const inline
Const access to black body.
Definition at line 108 of file fvDOM.H.
omegaMax()
Foam::scalar omegaMax () const inline
Return omegaMax.
Definition at line 114 of file fvDOM.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/radiation/radiationModels/fvDOM/fvDOM/fvDOM.H
src/thermophysicalModels/radiation/radiationModels/fvDOM/fvDOM/fvDOM.C
src/thermophysicalModels/radiation/radiationModels/fvDOM/fvDOM/fvDOMI.H