OpenFOAM: wideBandAbsorptionEmission Class Reference
wideBandAbsorptionEmission Class Reference
wideBandAbsorptionEmission radiation absorption and emission coefficients for continuous phase.
Public Member Functions
TypeName ("wideBandAbsorptionEmission")
Runtime type information.
wideBandAbsorptionEmission (const dictionary &dict, const fvMesh &mesh)
Construct from components.
virtual ~wideBandAbsorptionEmission ()
Destructor.
tmp< volScalarField > aCont (const label bandI=0) const
Absorption coefficient for continuous phase.
tmp< volScalarField > eCont (const label bandI=0) const
Emission coefficient for continuous phase.
tmp< volScalarField > ECont (const label bandI=0) const
Emission contribution for continuous phase.
bool isGrey () const
Flag for whether the absorption/emission is for a grey gas.
label nBands () const
Number of bands.
const Vector2D< scalar > & bands (const label i) const
Lower and upper limit of band i.
void correct (volScalarField &a_, PtrList< volScalarField > &aLambda) const
Correct rays.
Public Member Functions inherited from absorptionEmissionModel
TypeName ("absorptionEmissionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, absorptionEmissionModel, dictionary,(const dictionary &dict, const fvMesh &mesh),(dict, mesh))
Declare runtime constructor selection table.
absorptionEmissionModel (const dictionary &dict, const fvMesh &mesh)
Construct from components.
virtual ~absorptionEmissionModel ()
Destructor.
const fvMesh & mesh () const
Reference to the mesh.
const dictionary & dict () const
Reference to the dictionary.
virtual tmp< volScalarField > a (const label bandI=0) const
Absorption coefficient (net)
virtual tmp< volScalarField > aDisp (const label bandI=0) const
Absorption coefficient for dispersed phase.
virtual tmp< volScalarField > e (const label bandI=0) const
Emission coefficient (net)
virtual tmp< volScalarField > eDisp (const label bandI=0) const
Return emission coefficient for dispersed phase.
virtual tmp< volScalarField > E (const label bandI=0) const
Emission contribution (net)
virtual tmp< volScalarField > EDisp (const label bandI=0) const
Emission contribution for dispersed phase.
Public Attributes
FixedList< FixedList< absorptionCoeffs, nSpecies_ >, maxBands_ > coeffs_
Absorption coefficients.
Static Public Attributes
static const int nSpecies_ = 5
Maximum number of species considered for absorptivity.
static const int maxBands_ = 10
Maximum number of bands.
Additional Inherited Members
Static Public Member Functions inherited from absorptionEmissionModel
static autoPtr< absorptionEmissionModel > New (const dictionary &dict, const fvMesh &mesh)
Selector.
Protected Attributes inherited from absorptionEmissionModel
const dictionary dict_
Radiation model dictionary.
const fvMesh & mesh_
Reference to the fvMesh.
Detailed Description
wideBandAbsorptionEmission radiation absorption and emission coefficients for continuous phase.
All the bands should have the same number of species and have to be entered in the same order.
There is no check of continuity of the bands. They should not ovelap or have gaps.
The emission constant proportionality is specified per band (EhrrCoeff).
The coefficients for the species in the lookup table have to be specified for use in moles x P [atm].i.e. (k[i] = species[i]*p*9.869231e-6).
The coefficients for CO and soot or any other added are multiplied by the respective mass fraction being solved.
The look Up table file should be in the constant directory.
band dictionary:
    band0
    {
        bandLimits (1.0e-6 2.63e-6);
        EhrrCoeff       0.0;
        species
        {
            CH4
            {
                Tcommon         300.;
                Tlow            300.;
                Thigh           2500.;
                invTemp         false;
                loTcoeffs (0 0 0 0 0 0) ;
                hiTcoeffs (.1 0 0 0 0 0);
            }
            CO2
            {
                Tcommon         300.;
                Tlow            300.;
                Thigh           2500.;
                invTemp         false;
                loTcoeffs (0 0 0 0 0 0) ;
                hiTcoeffs (.1 0 0 0 0 0);
            }
            H2O
            {
                Tcommon         300.;
                Tlow            300.;
                Thigh           2500.;
                invTemp         false;
                loTcoeffs (0 0 0 0 0 0) ;
                hiTcoeffs (.1 0 0 0 0 0);
            }
            Ysoot
            {
                Tcommon         300.;
                Tlow            300.;
                Thigh           2500.;
                invTemp         false;
                loTcoeffs (0 0 0 0 0 0) ;
                hiTcoeffs (.1 0 0 0 0 0);
            }
        }
    }
Source files
wideBandAbsorptionEmission.H
wideBandAbsorptionEmission.C
Definition at line 121 of file wideBandAbsorptionEmission.H.
Constructor & Destructor Documentation
wideBandAbsorptionEmission()
wideBandAbsorptionEmission (const dictionary & dict, const fvMesh & mesh)
Construct from components.
Definition at line 50 of file wideBandAbsorptionEmission.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAllConstIter(), objectRegistry::foundObject(), Foam::Info, dictionary::lookup(), objectRegistry::lookupObject(), Foam::nl, dictionary::subDict(), and Y.
~wideBandAbsorptionEmission()
~wideBandAbsorptionEmission () virtual
Destructor.
Definition at line 148 of file wideBandAbsorptionEmission.C.
Member Function Documentation
TypeName()
TypeName ("wideBandAbsorptionEmission")
Runtime type information.
aCont()
Foam::tmp< Foam::volScalarField > aCont (const label bandI = 0) const virtual
Absorption coefficient for continuous phase.
Reimplemented from absorptionEmissionModel.
Definition at line 155 of file wideBandAbsorptionEmission.C.
References Foam::constant::physicoChemical::b, Foam::dimLength, Foam::dimless, forAll, mesh, n, IOobject::NO_READ, IOobject::NO_WRITE, p, tmp< T >::ref(), List< T >::size(), Foam::T(), and timeName.
eCont()
Foam::tmp< Foam::volScalarField > eCont (const label bandI = 0) const virtual
Emission coefficient for continuous phase.
Reimplemented from absorptionEmissionModel.
Definition at line 226 of file wideBandAbsorptionEmission.C.
ECont()
Foam::tmp< Foam::volScalarField > ECont (const label bandI = 0) const virtual
Emission contribution for continuous phase.
Reimplemented from absorptionEmissionModel.
Definition at line 233 of file wideBandAbsorptionEmission.C.
References wideBandAbsorptionEmission::correct(), Foam::dimEnergy, DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimLength, Foam::dimMass, Foam::dimTime, Foam::dimVolume, dQ, Foam::endl(), mesh, IOobject::NO_READ, IOobject::NO_WRITE, Foam::pow3(), GeometricField< Type, PatchField, GeoMesh >::primitiveField(), tmp< T >::ref(), timeName, and WarningInFunction.
isGrey()
bool isGrey () const inline virtual
Flag for whether the absorption/emission is for a grey gas.
Reimplemented from absorptionEmissionModel.
Definition at line 212 of file wideBandAbsorptionEmission.H.
nBands()
label nBands () const inline virtual
Number of bands.
Reimplemented from absorptionEmissionModel.
Definition at line 218 of file wideBandAbsorptionEmission.H.
bands()
const Vector2D<scalar>& bands (const label i) const inline virtual
Lower and upper limit of band i.
Reimplemented from absorptionEmissionModel.
Definition at line 224 of file wideBandAbsorptionEmission.H.
References wideBandAbsorptionEmission::correct().
correct()
void correct (volScalarField & a_, PtrList< volScalarField > & aLambda) const virtual
Correct rays.
Reimplemented from absorptionEmissionModel.
Definition at line 285 of file wideBandAbsorptionEmission.C.
References Foam::dimLength, Foam::dimless, and GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef().
Referenced by wideBandAbsorptionEmission::bands(), and wideBandAbsorptionEmission::ECont().
Member Data Documentation
nSpecies_
const int nSpecies_ = 5 static
Maximum number of species considered for absorptivity.
Definition at line 130 of file wideBandAbsorptionEmission.H.
maxBands_
const int maxBands_ = 10 static
Maximum number of bands.
Definition at line 133 of file wideBandAbsorptionEmission.H.
coeffs_
FixedList<FixedList<absorptionCoeffs, nSpecies_>, maxBands_> coeffs_
Absorption coefficients.
Definition at line 136 of file wideBandAbsorptionEmission.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/radiation/submodels/absorptionEmissionModel/wideBandAbsorptionEmission/wideBandAbsorptionEmission.H
src/thermophysicalModels/radiation/submodels/absorptionEmissionModel/wideBandAbsorptionEmission/wideBandAbsorptionEmission.C