OpenFOAM: chemkinReader Class Reference
chemkinReader Class Reference
Foam::chemkinReader.
Public Types
enum phase { solid, liquid, gas }
Public Types inherited from chemistryReader< gasHThermoPhysics >
typedef gasHThermoPhysics thermoType
The type of thermo package the reader was instantiated for.
Public Member Functions
TypeName ("chemkinReader")
Runtime type information.
chemkinReader (speciesTable &species, const fileName &CHEMKINFileName, const fileName &transportFileName, const fileName &thermoFileName=fileName::null, const bool newFormat=false)
Construct from CHEMKIN III file name.
chemkinReader (const dictionary &thermoDict, speciesTable &species)
Construct by getting the CHEMKIN III file name from dictionary.
virtual ~chemkinReader ()
Destructor.
const wordList & elementNames () const
List of elements.
const HashTable< label > & elementIndices () const
Element indices.
const HashTable< scalar > & isotopeAtomicWts () const
Isotope molecular weights.
const speciesTable & species () const
Table of species.
const speciesCompositionTable & specieComposition () const
Table of species composition.
const HashTable< phase > & speciePhase () const
Specie phase.
const HashPtrTable< gasHThermoPhysics > & speciesThermo () const
Table of the thermodynamic data given in the CHEMKIN file.
const ReactionList< gasHThermoPhysics > & reactions () const
List of the reactions.
Public Member Functions inherited from chemistryReader< gasHThermoPhysics >
chemistryReader ()
Construct null.
TypeName ("chemistryReader")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, chemistryReader, dictionary,(const dictionary &thermoDict, speciesTable &species),(thermoDict, species))
virtual ~chemistryReader ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from chemistryReader< gasHThermoPhysics >
static autoPtr< chemistryReader > New (const dictionary &thermoDict, speciesTable &species)
Select constructed from dictionary.
Detailed Description
Foam::chemkinReader.
Source files
chemkinReader.H
chemkinReader.C
chemkinLexer.C
Definition at line 61 of file chemkinReader.H.
Member Enumeration Documentation
phase
enum phase
Enumerator
solid
liquid
gas
Definition at line 71 of file chemkinReader.H.
Constructor & Destructor Documentation
chemkinReader() [1/2]
chemkinReader (speciesTable & species, const fileName & CHEMKINFileName, const fileName & transportFileName, const fileName & thermoFileName = fileName::null, const bool newFormat = false)
Construct from CHEMKIN III file name.
Definition at line 831 of file chemkinReader.C.
References Foam::read().
chemkinReader() [2/2]
chemkinReader (const dictionary & thermoDict, speciesTable & species)
Construct by getting the CHEMKIN III file name from dictionary.
Definition at line 851 of file chemkinReader.C.
References Foam::endl(), Foam::stringOps::expand(), dictionary::found(), Foam::Info, fileName::isAbsolute(), dictionary::lookup(), dictionaryName::name(), fileName::null, fileName::path(), and Foam::read().
~chemkinReader()
virtual ~chemkinReader () inline virtual
Destructor.
Definition at line 313 of file chemkinReader.H.
Member Function Documentation
TypeName()
TypeName ("chemkinReader")
Runtime type information.
elementNames()
const wordList& elementNames () const inline
List of elements.
Definition at line 320 of file chemkinReader.H.
elementIndices()
const HashTable<label>& elementIndices () const inline
Element indices.
Definition at line 326 of file chemkinReader.H.
isotopeAtomicWts()
const HashTable<scalar>& isotopeAtomicWts () const inline
Isotope molecular weights.
Definition at line 332 of file chemkinReader.H.
species()
const speciesTable& species () const inline virtual
Table of species.
Implements chemistryReader< gasHThermoPhysics >.
Definition at line 338 of file chemkinReader.H.
specieComposition()
const speciesCompositionTable& specieComposition () const inline virtual
Table of species composition.
Implements chemistryReader< gasHThermoPhysics >.
Definition at line 344 of file chemkinReader.H.
speciePhase()
const HashTable<phase>& speciePhase () const inline
Specie phase.
Definition at line 350 of file chemkinReader.H.
speciesThermo()
const HashPtrTable<gasHThermoPhysics>& speciesThermo () const inline virtual
Table of the thermodynamic data given in the CHEMKIN file.
Implements chemistryReader< gasHThermoPhysics >.
Definition at line 356 of file chemkinReader.H.
reactions()
const ReactionList<gasHThermoPhysics>& reactions () const inline virtual
List of the reactions.
Implements chemistryReader< gasHThermoPhysics >.
Definition at line 362 of file chemkinReader.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/reactionThermo/chemistryReaders/chemkinReader/chemkinReader.H
src/thermophysicalModels/reactionThermo/chemistryReaders/chemkinReader/chemkinReader.C