OpenFOAM: fixedUnburntEnthalpyFvPatchScalarField Class Reference
fixedUnburntEnthalpyFvPatchScalarField Class Reference
Fixed boundary condition for unburnt.
Public Member Functions
TypeName ("fixedUnburntEnthalpy")
Runtime type information.
fixedUnburntEnthalpyFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
fixedUnburntEnthalpyFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
fixedUnburntEnthalpyFvPatchScalarField (const fixedUnburntEnthalpyFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given fixedUnburntEnthalpyFvPatchScalarField.
fixedUnburntEnthalpyFvPatchScalarField (const fixedUnburntEnthalpyFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
fixedUnburntEnthalpyFvPatchScalarField (const fixedUnburntEnthalpyFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
Detailed Description
Fixed boundary condition for unburnt.
Source files
fixedUnburntEnthalpyFvPatchScalarField.H
fixedUnburntEnthalpyFvPatchScalarField.C
Definition at line 48 of file fixedUnburntEnthalpyFvPatchScalarField.H.
Constructor & Destructor Documentation
fixedUnburntEnthalpyFvPatchScalarField() [1/5]
fixedUnburntEnthalpyFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 37 of file fixedUnburntEnthalpyFvPatchScalarField.C.
Referenced by fixedUnburntEnthalpyFvPatchScalarField::clone(), and fixedUnburntEnthalpyFvPatchScalarField::fixedUnburntEnthalpyFvPatchScalarField().
fixedUnburntEnthalpyFvPatchScalarField() [2/5]
fixedUnburntEnthalpyFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 61 of file fixedUnburntEnthalpyFvPatchScalarField.C.
References fixedUnburntEnthalpyFvPatchScalarField::fixedUnburntEnthalpyFvPatchScalarField().
fixedUnburntEnthalpyFvPatchScalarField() [3/5]
fixedUnburntEnthalpyFvPatchScalarField (const fixedUnburntEnthalpyFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given fixedUnburntEnthalpyFvPatchScalarField.
onto a new patch
Definition at line 48 of file fixedUnburntEnthalpyFvPatchScalarField.C.
References fixedUnburntEnthalpyFvPatchScalarField::fixedUnburntEnthalpyFvPatchScalarField().
fixedUnburntEnthalpyFvPatchScalarField() [4/5]
fixedUnburntEnthalpyFvPatchScalarField (const fixedUnburntEnthalpyFvPatchScalarField & tppsf)
Construct as copy.
Definition at line 73 of file fixedUnburntEnthalpyFvPatchScalarField.C.
References fixedUnburntEnthalpyFvPatchScalarField::fixedUnburntEnthalpyFvPatchScalarField().
fixedUnburntEnthalpyFvPatchScalarField() [5/5]
fixedUnburntEnthalpyFvPatchScalarField (const fixedUnburntEnthalpyFvPatchScalarField & tppsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 83 of file fixedUnburntEnthalpyFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("fixedUnburntEnthalpy")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 93 of file fixedUnburntEnthalpyFvPatchScalarField.H.
References fixedUnburntEnthalpyFvPatchScalarField::fixedUnburntEnthalpyFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 110 of file fixedUnburntEnthalpyFvPatchScalarField.H.
References fixedUnburntEnthalpyFvPatchScalarField::fixedUnburntEnthalpyFvPatchScalarField(), and fixedUnburntEnthalpyFvPatchScalarField::updateCoeffs().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 94 of file fixedUnburntEnthalpyFvPatchScalarField.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), dictionaryName::dictName(), fvPatchField< Type >::evaluate(), psiuReactionThermo::heu(), Foam::makePatchTypeField(), Foam::operator==(), basicThermo::p(), patchi, and psiuReactionThermo::Tu().
Referenced by fixedUnburntEnthalpyFvPatchScalarField::clone().
The documentation for this class was generated from the following files:
src/thermophysicalModels/reactionThermo/derivedFvPatchFields/fixedUnburntEnthalpy/fixedUnburntEnthalpyFvPatchScalarField.H
src/thermophysicalModels/reactionThermo/derivedFvPatchFields/fixedUnburntEnthalpy/fixedUnburntEnthalpyFvPatchScalarField.C