OpenFOAM: basicMultiComponentMixture Class Reference
basicMultiComponentMixture Class Reference
Multi-component mixture.
Public Types
typedef basicMultiComponentMixture basicMixtureType
The base class of the mixture.
Public Member Functions
TypeName ("basicMultiComponentMixture")
Run time type information.
basicMultiComponentMixture (const dictionary &, const wordList &specieNames, const fvMesh &, const word &)
Construct from dictionary, species names, mesh and phase name.
virtual ~basicMultiComponentMixture ()
Destructor.
const speciesTable & species () const
Return the table of species.
bool contains (const word &specieName) const
Does the mixture include this specie?
bool active (label speciei) const
Return true for active species.
const List< bool > & active () const
Return the bool list of active species.
void setActive (label speciei)
Set speciei active.
void setInactive (label speciei)
Set speciei inactive.
PtrList< volScalarField > & Y ()
Return the mass-fraction fields.
const PtrList< volScalarField > & Y () const
Return the const mass-fraction fields.
volScalarField & Y (const label i)
Return the mass-fraction field for a specie given by index.
const volScalarField & Y (const label i) const
Return the const mass-fraction field for a specie given by index.
volScalarField & Y (const word &specieName)
Return the mass-fraction field for a specie given by name.
const volScalarField & Y (const word &specieName) const
Return the const mass-fraction field for a specie given by name.
Protected Attributes
speciesTable species_
Table of specie names.
List< bool > active_
List of specie active flags.
PtrList< volScalarField > Y_
Species mass fractions.
Detailed Description
Multi-component mixture.
Provides a list of mass fraction fields and helper functions to query mixture composition.
Source files
basicMultiComponentMixture.H
basicMultiComponentMixture.C
Definition at line 54 of file basicMultiComponentMixture.H.
Member Typedef Documentation
basicMixtureType
typedef basicMultiComponentMixture basicMixtureType
The base class of the mixture.
Definition at line 78 of file basicMultiComponentMixture.H.
Constructor & Destructor Documentation
basicMultiComponentMixture()
basicMultiComponentMixture (const dictionary & thermoDict, const wordList & specieNames, const fvMesh & mesh, const word & phaseName)
Construct from dictionary, species names, mesh and phase name.
Definition at line 38 of file basicMultiComponentMixture.C.
References IOobject::AUTO_WRITE, TimePaths::constant(), Foam::exists(), forAll, IOobject::groupName(), mesh, IOobject::MUST_READ, IOobject::NO_READ, IOobject::NO_WRITE, Time::path(), fvMesh::time(), Time::timeName(), and tmp< T >::valid().
~basicMultiComponentMixture()
virtual ~basicMultiComponentMixture () inline virtual
Destructor.
Definition at line 94 of file basicMultiComponentMixture.H.
References basicMultiComponentMixture::active(), basicMultiComponentMixture::contains(), basicMultiComponentMixture::setActive(), basicMultiComponentMixture::setInactive(), basicMultiComponentMixture::species(), and basicMultiComponentMixture::Y().
Member Function Documentation
TypeName()
TypeName ("basicMultiComponentMixture")
Run time type information.
species()
const Foam::speciesTable & species () const inline
Return the table of species.
Definition at line 27 of file basicMultiComponentMixtureI.H.
References basicMultiComponentMixture::contains(), and basicMultiComponentMixture::species_.
Referenced by greyMeanAbsorptionEmission::aCont(), SLGThermo::carrierId(), ReactingParcel< ParcelType >::correctSurfaceValues(), ReactingCloud< Foam::DSMCCloud >::ReactingCloud(), SLGThermo::SLGThermo(), TDACChemistryModel< CompType, ThermoType >::TDACChemistryModel(), thermoSingleLayer::thermoSingleLayer(), and basicMultiComponentMixture::~basicMultiComponentMixture().
contains()
bool contains (const word & specieName) const inline
Does the mixture include this specie?
Definition at line 34 of file basicMultiComponentMixtureI.H.
References hashedWordList::contains(), and basicMultiComponentMixture::species_.
Referenced by basicMultiComponentMixture::species(), and basicMultiComponentMixture::~basicMultiComponentMixture().
active() [1/2]
bool active (label speciei) const inline
Return true for active species.
Definition at line 42 of file basicMultiComponentMixtureI.H.
References basicMultiComponentMixture::active_.
Referenced by TDACChemistryModel< CompType, ThermoType >::solve().
active() [2/2]
const Foam::List< bool > & active () const inline
Return the bool list of active species.
Definition at line 48 of file basicMultiComponentMixtureI.H.
References basicMultiComponentMixture::active_.
Referenced by basicMultiComponentMixture::~basicMultiComponentMixture().
setActive()
void setActive (label speciei) inline
Set speciei active.
Definition at line 54 of file basicMultiComponentMixtureI.H.
References basicMultiComponentMixture::active_.
Referenced by TDACChemistryModel< CompType, ThermoType >::solve(), and basicMultiComponentMixture::~basicMultiComponentMixture().
setInactive()
void setInactive (label speciei) inline
Set speciei inactive.
Definition at line 60 of file basicMultiComponentMixtureI.H.
References basicMultiComponentMixture::active_.
Referenced by TDACChemistryModel< CompType, ThermoType >::TDACChemistryModel(), and basicMultiComponentMixture::~basicMultiComponentMixture().
Y() [1/6]
Foam::PtrList< Foam::volScalarField > & Y () inline
Return the mass-fraction fields.
Definition at line 67 of file basicMultiComponentMixtureI.H.
References basicMultiComponentMixture::Y_.
Referenced by greyMeanAbsorptionEmission::aCont(), COxidationDiffusionLimitedRate< CloudType >::calculate(), COxidationKineticDiffusionLimitedRate< CloudType >::calculate(), COxidationHurtMitchell< CloudType >::calculate(), COxidationIntrinsicRate< CloudType >::calculate(), COxidationMurphyShaddix< CloudType >::calculate(), ReactingParcel< ParcelType >::correctSurfaceValues(), basicSpecieMixture::W(), basicMultiComponentMixture::Y(), and basicMultiComponentMixture::~basicMultiComponentMixture().
Y() [2/6]
const Foam::PtrList< Foam::volScalarField > & Y () const inline
Return the const mass-fraction fields.
Definition at line 74 of file basicMultiComponentMixtureI.H.
References basicMultiComponentMixture::Y_.
Y() [3/6]
Foam::volScalarField & Y (const label i) inline
Return the mass-fraction field for a specie given by index.
Definition at line 80 of file basicMultiComponentMixtureI.H.
References basicMultiComponentMixture::Y(), and basicMultiComponentMixture::Y_.
Y() [4/6]
const Foam::volScalarField & Y (const label i) const inline
Return the const mass-fraction field for a specie given by index.
Definition at line 87 of file basicMultiComponentMixtureI.H.
References basicMultiComponentMixture::Y(), and basicMultiComponentMixture::Y_.
Y() [5/6]
Foam::volScalarField & Y (const word & specieName) inline
Return the mass-fraction field for a specie given by name.
Definition at line 96 of file basicMultiComponentMixtureI.H.
References basicMultiComponentMixture::species_, basicMultiComponentMixture::Y(), and basicMultiComponentMixture::Y_.
Y() [6/6]
const Foam::volScalarField & Y (const word & specieName) const inline
Return the const mass-fraction field for a specie given by name.
Definition at line 105 of file basicMultiComponentMixtureI.H.
References basicMultiComponentMixture::species_, and basicMultiComponentMixture::Y_.
Member Data Documentation
species_
speciesTable species_ protected
Table of specie names.
Definition at line 62 of file basicMultiComponentMixture.H.
Referenced by basicMultiComponentMixture::contains(), basicMultiComponentMixture::species(), and basicMultiComponentMixture::Y().
active_
List<bool> active_ protected
List of specie active flags.
Definition at line 65 of file basicMultiComponentMixture.H.
Referenced by basicMultiComponentMixture::active(), basicMultiComponentMixture::setActive(), and basicMultiComponentMixture::setInactive().
Y_
PtrList<volScalarField> Y_ protected
Species mass fractions.
Definition at line 68 of file basicMultiComponentMixture.H.
Referenced by basicMultiComponentMixture::Y().
The documentation for this class was generated from the following files:
src/thermophysicalModels/reactionThermo/mixtures/basicMultiComponentMixture/basicMultiComponentMixture.H
src/thermophysicalModels/reactionThermo/mixtures/basicMultiComponentMixture/basicMultiComponentMixture.C
src/thermophysicalModels/reactionThermo/mixtures/basicMultiComponentMixture/basicMultiComponentMixtureI.H