OpenFOAM: mixedUnburntEnthalpyFvPatchScalarField Class Reference
mixedUnburntEnthalpyFvPatchScalarField Class Reference
Mixed boundary condition for unburnt.
Public Member Functions
TypeName ("mixedUnburntEnthalpy")
Runtime type information.
mixedUnburntEnthalpyFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
mixedUnburntEnthalpyFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
mixedUnburntEnthalpyFvPatchScalarField (const mixedUnburntEnthalpyFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given mixedUnburntEnthalpyFvPatchScalarField.
mixedUnburntEnthalpyFvPatchScalarField (const mixedUnburntEnthalpyFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
mixedUnburntEnthalpyFvPatchScalarField (const mixedUnburntEnthalpyFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
Detailed Description
Mixed boundary condition for unburnt.
Source files
mixedUnburntEnthalpyFvPatchScalarField.H
mixedUnburntEnthalpyFvPatchScalarField.C
Definition at line 48 of file mixedUnburntEnthalpyFvPatchScalarField.H.
Constructor & Destructor Documentation
mixedUnburntEnthalpyFvPatchScalarField() [1/5]
mixedUnburntEnthalpyFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 36 of file mixedUnburntEnthalpyFvPatchScalarField.C.
Referenced by mixedUnburntEnthalpyFvPatchScalarField::clone(), and mixedUnburntEnthalpyFvPatchScalarField::mixedUnburntEnthalpyFvPatchScalarField().
mixedUnburntEnthalpyFvPatchScalarField() [2/5]
mixedUnburntEnthalpyFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 64 of file mixedUnburntEnthalpyFvPatchScalarField.C.
References mixedUnburntEnthalpyFvPatchScalarField::mixedUnburntEnthalpyFvPatchScalarField().
mixedUnburntEnthalpyFvPatchScalarField() [3/5]
mixedUnburntEnthalpyFvPatchScalarField (const mixedUnburntEnthalpyFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given mixedUnburntEnthalpyFvPatchScalarField.
onto a new patch
Definition at line 51 of file mixedUnburntEnthalpyFvPatchScalarField.C.
References mixedUnburntEnthalpyFvPatchScalarField::mixedUnburntEnthalpyFvPatchScalarField().
mixedUnburntEnthalpyFvPatchScalarField() [4/5]
mixedUnburntEnthalpyFvPatchScalarField (const mixedUnburntEnthalpyFvPatchScalarField & tppsf)
Construct as copy.
Definition at line 76 of file mixedUnburntEnthalpyFvPatchScalarField.C.
References mixedUnburntEnthalpyFvPatchScalarField::mixedUnburntEnthalpyFvPatchScalarField().
mixedUnburntEnthalpyFvPatchScalarField() [5/5]
mixedUnburntEnthalpyFvPatchScalarField (const mixedUnburntEnthalpyFvPatchScalarField & tppsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 86 of file mixedUnburntEnthalpyFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("mixedUnburntEnthalpy")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 93 of file mixedUnburntEnthalpyFvPatchScalarField.H.
References mixedUnburntEnthalpyFvPatchScalarField::mixedUnburntEnthalpyFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 110 of file mixedUnburntEnthalpyFvPatchScalarField.H.
References mixedUnburntEnthalpyFvPatchScalarField::mixedUnburntEnthalpyFvPatchScalarField(), and mixedUnburntEnthalpyFvPatchScalarField::updateCoeffs().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 97 of file mixedUnburntEnthalpyFvPatchScalarField.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), basicThermo::Cp(), dictionaryName::dictName(), psiuReactionThermo::heu(), Foam::makePatchTypeField(), basicThermo::p(), patchi, and psiuReactionThermo::Tu().
Referenced by mixedUnburntEnthalpyFvPatchScalarField::clone().
The documentation for this class was generated from the following files:
src/thermophysicalModels/reactionThermo/derivedFvPatchFields/mixedUnburntEnthalpy/mixedUnburntEnthalpyFvPatchScalarField.H
src/thermophysicalModels/reactionThermo/derivedFvPatchFields/mixedUnburntEnthalpy/mixedUnburntEnthalpyFvPatchScalarField.C