OpenFOAM: mixtureFractionSoot< ThermoType > Class Template Reference
mixtureFractionSoot< ThermoType > Class Template Reference
This soot model is purely an state model. The ammount of soot produced is determined by a single step chemistry as :
Public Member Functions
TypeName ("mixtureFractionSoot")
Runtime type information.
mixtureFractionSoot (const dictionary &dict, const fvMesh &mesh, const word &modelType)
Construct from components.
virtual ~mixtureFractionSoot ()
Destructor.
virtual void correct ()
Main update/correction routine.
const volScalarField & soot () const
Return Ysoot.
Public Member Functions inherited from sootModel
TypeName ("sootModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, sootModel, dictionary,(const dictionary &dict, const fvMesh &mesh, const word &modelType),(dict, mesh, modelType))
Declare runtime constructor selection table.
sootModel (const dictionary &dict, const fvMesh &mesh, const word &modelType)
Construct from components.
virtual ~sootModel ()
Destructor.
const fvMesh & mesh () const
Reference to the mesh.
const dictionary & dict () const
Reference to the dictionary.
Additional Inherited Members
Static Public Member Functions inherited from sootModel
static autoPtr< sootModel > New (const dictionary &dict, const fvMesh &mesh)
Selector.
Protected Attributes inherited from sootModel
const dictionary dict_
Radiation model dictionary.
const fvMesh & mesh_
Reference to the fvMesh.
Detailed Description
template<class ThermoType>
class Foam::radiation::mixtureFractionSoot< ThermoType >
This soot model is purely an state model. The ammount of soot produced is determined by a single step chemistry as :
nuf Fuel + nuOx Ox = nuP P + nuSoot soot
nuSoot is prescribed by the user.
The single step chemistry used is read from the combustion. The soot is not considered into the thermodynamics of the system and it is not considered as an extra specie in the solver.
The spacial distribution is given by the normalization of the first product on the rhs of the reaction by default or it can be added as input.
The input dictionary reads like in the radiationProperties dictionary:
sootModel mixtureFractionSoot<gasHThermoPhysics>;
mixtureFractionSootCoeffs { nuSoot 0.015; Wsoot 12; mappingField P; }
Source files
mixtureFractionSoot.H
mixtureFractionSoot.C
Definition at line 79 of file mixtureFractionSoot.H.
Constructor & Destructor Documentation
mixtureFractionSoot()
mixtureFractionSoot (const dictionary & dict, const fvMesh & mesh, const word & modelType)
Construct from components.
Definition at line 66 of file mixtureFractionSoot.C.
References forAll, Foam::Info, Foam::mag(), Foam::nl, reaction(), and Reaction< ReactionThermo >::rhs().
~mixtureFractionSoot()
~mixtureFractionSoot () virtual
Destructor.
Definition at line 143 of file mixtureFractionSoot.C.
Member Function Documentation
TypeName()
TypeName ("mixtureFractionSoot< ThermoType >")
Runtime type information.
correct()
void correct () virtual
Main update/correction routine.
Implements sootModel.
Definition at line 150 of file mixtureFractionSoot.C.
soot()
const volScalarField& soot () const inline virtual
Return Ysoot.
Implements sootModel.
Definition at line 155 of file mixtureFractionSoot.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/radiation/submodels/sootModel/mixtureFractionSoot/mixtureFractionSoot.H
src/thermophysicalModels/radiation/submodels/sootModel/mixtureFractionSoot/mixtureFractionSoot.C