OpenFOAM: gradientUnburntEnthalpyFvPatchScalarField Class Reference
gradientUnburntEnthalpyFvPatchScalarField Class Reference
gradient boundary condition for unburnt
Public Member Functions
TypeName ("gradientUnburntEnthalpy")
Runtime type information.
gradientUnburntEnthalpyFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
gradientUnburntEnthalpyFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
gradientUnburntEnthalpyFvPatchScalarField (const gradientUnburntEnthalpyFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given gradientUnburntEnthalpyFvPatchScalarField.
gradientUnburntEnthalpyFvPatchScalarField (const gradientUnburntEnthalpyFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
gradientUnburntEnthalpyFvPatchScalarField (const gradientUnburntEnthalpyFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
Detailed Description
gradient boundary condition for unburnt
Source files
gradientUnburntEnthalpyFvPatchScalarField.H
gradientUnburntEnthalpyFvPatchScalarField.C
Definition at line 48 of file gradientUnburntEnthalpyFvPatchScalarField.H.
Constructor & Destructor Documentation
gradientUnburntEnthalpyFvPatchScalarField() [1/5]
gradientUnburntEnthalpyFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 36 of file gradientUnburntEnthalpyFvPatchScalarField.C.
Referenced by gradientUnburntEnthalpyFvPatchScalarField::clone(), and gradientUnburntEnthalpyFvPatchScalarField::gradientUnburntEnthalpyFvPatchScalarField().
gradientUnburntEnthalpyFvPatchScalarField() [2/5]
gradientUnburntEnthalpyFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 60 of file gradientUnburntEnthalpyFvPatchScalarField.C.
References gradientUnburntEnthalpyFvPatchScalarField::gradientUnburntEnthalpyFvPatchScalarField().
gradientUnburntEnthalpyFvPatchScalarField() [3/5]
gradientUnburntEnthalpyFvPatchScalarField (const gradientUnburntEnthalpyFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given gradientUnburntEnthalpyFvPatchScalarField.
onto a new patch
Definition at line 47 of file gradientUnburntEnthalpyFvPatchScalarField.C.
References gradientUnburntEnthalpyFvPatchScalarField::gradientUnburntEnthalpyFvPatchScalarField().
gradientUnburntEnthalpyFvPatchScalarField() [4/5]
gradientUnburntEnthalpyFvPatchScalarField (const gradientUnburntEnthalpyFvPatchScalarField & tppsf)
Construct as copy.
Definition at line 72 of file gradientUnburntEnthalpyFvPatchScalarField.C.
References gradientUnburntEnthalpyFvPatchScalarField::gradientUnburntEnthalpyFvPatchScalarField().
gradientUnburntEnthalpyFvPatchScalarField() [5/5]
gradientUnburntEnthalpyFvPatchScalarField (const gradientUnburntEnthalpyFvPatchScalarField & tppsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 82 of file gradientUnburntEnthalpyFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("gradientUnburntEnthalpy")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 93 of file gradientUnburntEnthalpyFvPatchScalarField.H.
References gradientUnburntEnthalpyFvPatchScalarField::gradientUnburntEnthalpyFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 110 of file gradientUnburntEnthalpyFvPatchScalarField.H.
References gradientUnburntEnthalpyFvPatchScalarField::gradientUnburntEnthalpyFvPatchScalarField(), and gradientUnburntEnthalpyFvPatchScalarField::updateCoeffs().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 93 of file gradientUnburntEnthalpyFvPatchScalarField.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), basicThermo::Cp(), dictionaryName::dictName(), fvPatchField< Type >::evaluate(), psiuReactionThermo::heu(), Foam::makePatchTypeField(), basicThermo::p(), patchi, fvPatchField< Type >::snGrad(), and psiuReactionThermo::Tu().
Referenced by gradientUnburntEnthalpyFvPatchScalarField::clone().
The documentation for this class was generated from the following files:
src/thermophysicalModels/reactionThermo/derivedFvPatchFields/gradientUnburntEnthalpy/gradientUnburntEnthalpyFvPatchScalarField.H
src/thermophysicalModels/reactionThermo/derivedFvPatchFields/gradientUnburntEnthalpy/gradientUnburntEnthalpyFvPatchScalarField.C