OpenFOAM: chemistryReader< ThermoType > Class Template Reference
chemistryReader< ThermoType > Class Template Reference abstract
Abstract class for reading chemistry.
Public Types
typedef ThermoType thermoType
The type of thermo package the reader was instantiated for.
Public Member Functions
TypeName ("chemistryReader")
Runtime type information.
chemistryReader ()
Construct null.
declareRunTimeSelectionTable (autoPtr, chemistryReader, dictionary,(const dictionary &thermoDict, speciesTable &species),(thermoDict, species))
virtual ~chemistryReader ()
Destructor.
virtual const speciesTable & species () const =0
Return access to the list of species.
virtual const speciesCompositionTable & specieComposition () const =0
Table of species composition.
virtual const HashPtrTable< ThermoType > & speciesThermo () const =0
Return access to the thermo packages.
virtual const ReactionList< ThermoType > & reactions () const =0
Return access to the list of reactions.
Static Public Member Functions
static autoPtr< chemistryReader > New (const dictionary &thermoDict, speciesTable &species)
Select constructed from dictionary.
Detailed Description
template<class ThermoType>
class Foam::chemistryReader< ThermoType >
Abstract class for reading chemistry.
Source files
chemistryReader.H
chemistryReader.C
Definition at line 56 of file chemistryReader.H.
Member Typedef Documentation
thermoType
typedef ThermoType thermoType
The type of thermo package the reader was instantiated for.
Definition at line 73 of file chemistryReader.H.
Constructor & Destructor Documentation
chemistryReader()
chemistryReader () inline
Construct null.
Definition at line 79 of file chemistryReader.H.
~chemistryReader()
virtual ~chemistryReader () inline virtual
Destructor.
Definition at line 109 of file chemistryReader.H.
Member Function Documentation
TypeName()
TypeName ("chemistryReader< ThermoType >")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , chemistryReader< ThermoType > , dictionary , (const dictionary &thermoDict, speciesTable &species) , (thermoDict, species))
Referenced by chemistryReader< gasHThermoPhysics >::chemistryReader().
New()
Foam::autoPtr< Foam::chemistryReader< ThermoType > > New (const dictionary & thermoDict, speciesTable & species) static
Select constructed from dictionary.
Definition at line 33 of file chemistryReader.C.
Referenced by chemistryReader< gasHThermoPhysics >::chemistryReader().
species()
virtual const speciesTable& species () const pure virtual
Return access to the list of species.
Implemented in chemkinReader, and foamChemistryReader< ThermoType >.
Referenced by chemistryReader< gasHThermoPhysics >::chemistryReader(), and chemistryReader< gasHThermoPhysics >::~chemistryReader().
specieComposition()
virtual const speciesCompositionTable& specieComposition () const pure virtual
Table of species composition.
Implemented in chemkinReader, and foamChemistryReader< ThermoType >.
Referenced by chemistryReader< gasHThermoPhysics >::~chemistryReader().
speciesThermo()
virtual const HashPtrTable<ThermoType>& speciesThermo () const pure virtual
Return access to the thermo packages.
Implemented in chemkinReader, and foamChemistryReader< ThermoType >.
Referenced by chemistryReader< gasHThermoPhysics >::~chemistryReader().
reactions()
virtual const ReactionList<ThermoType>& reactions () const pure virtual
Return access to the list of reactions.
Implemented in chemkinReader, and foamChemistryReader< ThermoType >.
Referenced by chemistryReader< gasHThermoPhysics >::~chemistryReader().
The documentation for this class was generated from the following files:
src/thermophysicalModels/reactionThermo/chemistryReaders/chemistryReader/chemistryReader.H
src/thermophysicalModels/reactionThermo/chemistryReaders/chemistryReader/chemistryReader.C