OpenFOAM: sootModel Class Reference
sootModel Class Reference abstract
Base class for soor models.
Public Member Functions
TypeName ("sootModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, sootModel, dictionary,(const dictionary &dict, const fvMesh &mesh, const word &modelType),(dict, mesh, modelType))
Declare runtime constructor selection table.
sootModel (const dictionary &dict, const fvMesh &mesh, const word &modelType)
Construct from components.
virtual ~sootModel ()
Destructor.
const fvMesh & mesh () const
Reference to the mesh.
const dictionary & dict () const
Reference to the dictionary.
virtual void correct ()=0
Main update/correction routine.
virtual const volScalarField & soot () const =0
Return const reference to soot.
Static Public Member Functions
static autoPtr< sootModel > New (const dictionary &dict, const fvMesh &mesh)
Selector.
Protected Attributes
const dictionary dict_
Radiation model dictionary.
const fvMesh & mesh_
Reference to the fvMesh.
Detailed Description
Base class for soor models.
Definition at line 53 of file sootModel.H.
Constructor & Destructor Documentation
sootModel()
sootModel (const dictionary & dict, const fvMesh & mesh, const word & modelType)
Construct from components.
Definition at line 42 of file sootModel.C.
~sootModel()
~sootModel () virtual
Destructor.
Definition at line 55 of file sootModel.C.
Member Function Documentation
TypeName()
TypeName ("sootModel")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , sootModel , dictionary , (const dictionary &dict, const fvMesh &mesh, const word &modelType) , (dict, mesh, modelType))
Declare runtime constructor selection table.
New()
Foam::autoPtr< Foam::radiation::sootModel > New (const dictionary & dict, const fvMesh & mesh) static
Selector.
Definition at line 33 of file sootModelNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, dictionary::found(), Foam::Info, dictionary::lookup(), mesh, and Foam::nl.
mesh()
const fvMesh& mesh () const inline
Reference to the mesh.
Definition at line 116 of file sootModel.H.
References sootModel::mesh_.
dict()
const dictionary& dict () const inline
Reference to the dictionary.
Definition at line 122 of file sootModel.H.
References sootModel::correct(), sootModel::dict_, and sootModel::soot().
correct()
virtual void correct () pure virtual
Main update/correction routine.
Implemented in mixtureFractionSoot< ThermoType >, and noSoot.
Referenced by sootModel::dict().
soot()
virtual const volScalarField& soot () const pure virtual
Return const reference to soot.
Implemented in mixtureFractionSoot< ThermoType >, and noSoot.
Referenced by sootModel::dict().
Member Data Documentation
dict_
const dictionary dict_ protected
Radiation model dictionary.
Definition at line 61 of file sootModel.H.
Referenced by sootModel::dict().
mesh_
const fvMesh& mesh_ protected
Reference to the fvMesh.
Definition at line 64 of file sootModel.H.
Referenced by sootModel::mesh().
The documentation for this class was generated from the following files:
src/thermophysicalModels/radiation/submodels/sootModel/sootModel/sootModel.H
src/thermophysicalModels/radiation/submodels/sootModel/sootModel/sootModel.C
src/thermophysicalModels/radiation/submodels/sootModel/sootModel/sootModelNew.C