OpenFOAM: solidArrheniusReactionRate Class Reference
solidArrheniusReactionRate Class Reference
Arrhenius reaction rate for solids.
Public Member Functions
solidArrheniusReactionRate (const scalar A, const scalar Ta, const scalar Tcrit)
Construct from components.
solidArrheniusReactionRate (const speciesTable &species, Istream &is)
Construct from Istream.
solidArrheniusReactionRate (const speciesTable &species, const dictionary &dict)
Construct from dictionary.
virtual ~solidArrheniusReactionRate ()
Destructor.
scalar operator() (const scalar p, const scalar T, const scalarField &c) const
void write (Ostream &os) const
Write to stream.
Static Public Member Functions
static word type ()
Return the type name.
Friends
Ostream & operator<< (Ostream &, const solidArrheniusReactionRate &)
Detailed Description
Arrhenius reaction rate for solids.
Source files
solidArrheniusReactionRate.H
solidArrheniusReactionRateI.H
Definition at line 56 of file solidArrheniusReactionRate.H.
Constructor & Destructor Documentation
solidArrheniusReactionRate() [1/3]
solidArrheniusReactionRate (const scalar A, const scalar Ta, const scalar Tcrit) inline
Construct from components.
Definition at line 29 of file solidArrheniusReactionRateI.H.
Referenced by solidArrheniusReactionRate::solidArrheniusReactionRate().
solidArrheniusReactionRate() [2/3]
solidArrheniusReactionRate (const speciesTable & species, Istream & is) inline
Construct from Istream.
Definition at line 43 of file solidArrheniusReactionRateI.H.
References solidArrheniusReactionRate::solidArrheniusReactionRate().
solidArrheniusReactionRate() [3/3]
solidArrheniusReactionRate (const speciesTable & species, const dictionary & dict) inline
Construct from dictionary.
Definition at line 55 of file solidArrheniusReactionRateI.H.
~solidArrheniusReactionRate()
virtual ~solidArrheniusReactionRate () inline virtual
Destructor.
Definition at line 93 of file solidArrheniusReactionRate.H.
Member Function Documentation
type()
static word type () inline static
Return the type name.
Definition at line 100 of file solidArrheniusReactionRate.H.
References Foam::constant::universal::c, p, Foam::T(), and solidArrheniusReactionRate::write().
operator()()
Foam::scalar operator() (const scalar p, const scalar T, const scalarField & c) const inline
Definition at line 69 of file solidArrheniusReactionRateI.H.
References Foam::exp().
write()
void write (Ostream & os) const inline
Write to stream.
Definition at line 90 of file solidArrheniusReactionRateI.H.
References token::END_STATEMENT, Foam::nl, and Ostream::writeKeyword().
Referenced by solidArrheniusReactionRate::type().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const solidArrheniusReactionRate &) friend
The documentation for this class was generated from the following files:
src/thermophysicalModels/solidSpecie/reaction/reactionRate/solidArrheniusReactionRate/solidArrheniusReactionRate.H
src/thermophysicalModels/solidSpecie/reaction/reactionRate/solidArrheniusReactionRate/solidArrheniusReactionRateI.H