OpenFOAM: SLGThermo Class Reference
SLGThermo Class Reference
Thermo package for (S)olids (L)iquids and (G)ases Takes reference to thermo package, and provides:
Public Member Functions
TypeName ("SLGThermo")
Runtime type information.
SLGThermo (const fvMesh &mesh, fluidThermo &thermo)
Construct from mesh.
virtual ~SLGThermo ()
Destructor.
const fluidThermo & thermo () const
Return reference to the thermo database.
const basicSpecieMixture & carrier () const
Return reference to the gaseous components.
const liquidMixtureProperties & liquids () const
Return reference to the global (additional) liquids.
const solidMixtureProperties & solids () const
Return reference to the global (additional) solids.
label carrierId (const word &cmptName, bool allowNotFound=false) const
Index of carrier component.
label liquidId (const word &cmptName, bool allowNotFound=false) const
Index of liquid component.
label solidId (const word &cmptName, bool allowNotFound=false) const
Index of solid component.
bool hasMultiComponentCarrier () const
Thermo database has multi-component carrier flag.
bool hasLiquids () const
Thermo database has liquid components flag.
bool hasSolids () const
Thermo database has solid components flag.
bool writeData (Foam::Ostream &) const
Pure virtual writaData function.
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, transferring registry registration to copy.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Construct as copy with new name, transfering registry registration.
regIOobject (const IOobject &, const regIOobject &)
Construct as copy with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
virtual void rename (const word &newName)
Rename.
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool readData (Istream &)
Virtual readData function.
virtual bool read ()
Read object.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType) const
Write using given format, version and compression.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Additional Inherited Members
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
Thermo package for (S)olids (L)iquids and (G)ases Takes reference to thermo package, and provides:
- carrier : components of thermo - access to elemental properties
liquids : liquid components - access to elemental properties
solids : solid components - access to elemental properties
If thermo is not a multi-component thermo package, carrier is nullptr. Similarly, if no liquids or solids are specified, their respective pointers will also be nullptr.
Registered to the mesh so that it can be looked-up
Source files
SLGThermo.H
SLGThermo.C
Definition at line 62 of file SLGThermo.H.
Constructor & Destructor Documentation
SLGThermo()
SLGThermo (const fvMesh & mesh, fluidThermo & thermo)
Construct from mesh.
Definition at line 38 of file SLGThermo.C.
References Foam::endl(), dictionary::found(), Foam::Info, solidMixtureProperties::New(), liquidMixtureProperties::New(), List< T >::size(), basicMultiComponentMixture::species(), dictionary::subDict(), and SLGThermo::thermo().
~SLGThermo()
~SLGThermo () virtual
Destructor.
Definition at line 96 of file SLGThermo.C.
Member Function Documentation
TypeName()
TypeName ("SLGThermo")
Runtime type information.
thermo()
const Foam::fluidThermo & thermo () const
Return reference to the thermo database.
Definition at line 102 of file SLGThermo.C.
Referenced by SLGThermo::SLGThermo().
carrier()
const Foam::basicSpecieMixture & carrier () const
Return reference to the gaseous components.
Definition at line 108 of file SLGThermo.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Referenced by COxidationDiffusionLimitedRate< CloudType >::calculate(), COxidationKineticDiffusionLimitedRate< CloudType >::calculate(), COxidationHurtMitchell< CloudType >::calculate(), COxidationIntrinsicRate< CloudType >::calculate(), COxidationMurphyShaddix< CloudType >::calculate(), SLGThermo::carrierId(), ReactingParcel< ParcelType >::correctSurfaceValues(), ReactingCloud< Foam::DSMCCloud >::ReactingCloud(), and thermoSingleLayer::thermoSingleLayer().
liquids()
const Foam::liquidMixtureProperties & liquids () const
Return reference to the global (additional) liquids.
Definition at line 121 of file SLGThermo.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Referenced by liquidFilmThermo::initLiquid(), and SLGThermo::liquidId().
solids()
const Foam::solidMixtureProperties & solids () const
Return reference to the global (additional) solids.
Definition at line 134 of file SLGThermo.C.
References Foam::abort(), SLGThermo::carrierId(), Foam::FatalError, and FatalErrorInFunction.
Referenced by COxidationDiffusionLimitedRate< CloudType >::calculate(), COxidationKineticDiffusionLimitedRate< CloudType >::calculate(), COxidationHurtMitchell< CloudType >::calculate(), COxidationIntrinsicRate< CloudType >::calculate(), COxidationMurphyShaddix< CloudType >::calculate(), and SLGThermo::solidId().
carrierId()
Foam::label carrierId (const word & cmptName, bool allowNotFound = false) const
Index of carrier component.
Definition at line 148 of file SLGThermo.C.
References SLGThermo::carrier(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, SLGThermo::liquidId(), Foam::nl, and basicMultiComponentMixture::species().
Referenced by SLGThermo::solids(), and thermoSingleLayer::Srho().
liquidId()
Foam::label liquidId (const word & cmptName, bool allowNotFound = false) const
Index of liquid component.
Definition at line 174 of file SLGThermo.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, SLGThermo::liquids(), Foam::nl, and SLGThermo::solidId().
Referenced by SLGThermo::carrierId(), and liquidFilmThermo::initLiquid().
solidId()
Foam::label solidId (const word & cmptName, bool allowNotFound = false) const
Index of solid component.
Definition at line 199 of file SLGThermo.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::nl, and SLGThermo::solids().
Referenced by SLGThermo::liquidId().
hasMultiComponentCarrier()
bool hasMultiComponentCarrier () const
Thermo database has multi-component carrier flag.
Definition at line 223 of file SLGThermo.C.
Referenced by thermoSingleLayer::thermoSingleLayer().
hasLiquids()
bool hasLiquids () const
Thermo database has liquid components flag.
Definition at line 229 of file SLGThermo.C.
hasSolids()
bool hasSolids () const
Thermo database has solid components flag.
Definition at line 235 of file SLGThermo.C.
writeData()
bool writeData (Foam::Ostream &) const inline virtual
Pure virtual writaData function.
Must be defined in derived types
Implements regIOobject.
Definition at line 151 of file SLGThermo.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/SLGThermo/SLGThermo/SLGThermo.H
src/thermophysicalModels/SLGThermo/SLGThermo/SLGThermo.C