OpenFOAM: heheuPsiThermo< BasicPsiThermo, MixtureType > Class Template Reference
heheuPsiThermo< BasicPsiThermo, MixtureType > Class Template Reference
Public Member Functions
TypeName ("heheuPsiThermo")
Runtime type information.
heheuPsiThermo (const fvMesh &, const word &phaseName)
Construct from mesh and phase name.
virtual ~heheuPsiThermo ()
Destructor.
virtual void correct ()
Update properties.
virtual volScalarField & heu ()
Unburnt gas enthalpy [J/kg].
virtual const volScalarField & heu () const
Unburnt gas enthalpy [J/kg].
virtual const volScalarField & Tu () const
Unburnt gas temperature [K].
virtual tmp< scalarField > heu (const scalarField &p, const scalarField &T, const labelList &cells) const
Unburnt gas enthalpy for cell-set [J/kg].
virtual tmp< scalarField > heu (const scalarField &p, const scalarField &T, const label patchi) const
Unburnt gas enthalpy for patch [J/kg].
virtual tmp< volScalarField > Tb () const
Burnt gas temperature [K].
virtual tmp< volScalarField > psiu () const
Unburnt gas compressibility [s^2/m^2].
virtual tmp< volScalarField > psib () const
Burnt gas compressibility [s^2/m^2].
virtual tmp< volScalarField > muu () const
Dynamic viscosity of unburnt gas [kg/ms].
virtual tmp< volScalarField > mub () const
Dynamic viscosity of burnt gas [kg/ms].
Public Member Functions inherited from heThermo< BasicPsiThermo, MixtureType >
heThermo (const fvMesh &, const word &phaseName)
Construct from mesh.
heThermo (const fvMesh &, const dictionary &, const word &phaseName)
Construct from mesh and dictionary.
virtual ~heThermo ()
Destructor.
virtual MixtureType::basicMixtureType & composition ()
Return the compostion of the mixture.
virtual const MixtureType::basicMixtureType & composition () const
Return the compostion of the mixture.
virtual bool incompressible () const
Return true if the equation of state is incompressible.
virtual bool isochoric () const
Return true if the equation of state is isochoric.
virtual volScalarField & he ()
Enthalpy/Internal energy [J/kg].
virtual const volScalarField & he () const
Enthalpy/Internal energy [J/kg].
virtual tmp< volScalarField > he (const volScalarField &p, const volScalarField &T) const
Enthalpy/Internal energy.
virtual tmp< scalarField > he (const scalarField &p, const scalarField &T, const labelList &cells) const
Enthalpy/Internal energy for cell-set [J/kg].
virtual tmp< scalarField > he (const scalarField &p, const scalarField &T, const label patchi) const
Enthalpy/Internal energy for patch [J/kg].
virtual tmp< volScalarField > hc () const
Chemical enthalpy [J/kg].
virtual tmp< scalarField > THE (const scalarField &he, const scalarField &p, const scalarField &T0, const labelList &cells) const
Temperature from enthalpy/internal energy for cell-set.
virtual tmp< scalarField > THE (const scalarField &he, const scalarField &p, const scalarField &T0, const label patchi) const
Temperature from enthalpy/internal energy for patch.
virtual tmp< scalarField > Cp (const scalarField &p, const scalarField &T, const label patchi) const
Heat capacity at constant pressure for patch [J/kg/K].
virtual tmp< volScalarField > Cp () const
Heat capacity at constant pressure [J/kg/K].
virtual tmp< scalarField > Cv (const scalarField &p, const scalarField &T, const label patchi) const
Heat capacity at constant volume for patch [J/kg/K].
virtual tmp< volScalarField > Cv () const
Heat capacity at constant volume [J/kg/K].
virtual tmp< volScalarField > gamma () const
Gamma = Cp/Cv [].
virtual tmp< scalarField > gamma (const scalarField &p, const scalarField &T, const label patchi) const
Gamma = Cp/Cv for patch [].
virtual tmp< scalarField > Cpv (const scalarField &p, const scalarField &T, const label patchi) const
Heat capacity at constant pressure/volume for patch [J/kg/K].
virtual tmp< volScalarField > Cpv () const
Heat capacity at constant pressure/volume [J/kg/K].
virtual tmp< volScalarField > CpByCpv () const
Heat capacity ratio [].
virtual tmp< scalarField > CpByCpv (const scalarField &p, const scalarField &T, const label patchi) const
Heat capacity ratio for patch [].
virtual tmp< volScalarField > kappa () const
Thermal diffusivity for temperature of mixture [J/m/s/K].
virtual tmp< scalarField > kappa (const label patchi) const
Thermal diffusivity for temperature.
virtual tmp< volScalarField > kappaEff (const volScalarField &) const
Effective thermal diffusivity for temperature.
virtual tmp< scalarField > kappaEff (const scalarField &alphat, const label patchi) const
Effective thermal diffusivity for temperature.
virtual tmp< volScalarField > alphaEff (const volScalarField &alphat) const
Effective thermal diffusivity of mixture [kg/m/s].
virtual tmp< scalarField > alphaEff (const scalarField &alphat, const label patchi) const
Effective thermal diffusivity of mixture for patch [kg/m/s].
virtual bool read ()
Read thermophysical properties dictionary.
Additional Inherited Members
Protected Member Functions inherited from heThermo< BasicPsiThermo, MixtureType >
void heBoundaryCorrection (volScalarField &he)
Correct the enthalpy/internal energy field boundaries.
Protected Attributes inherited from heThermo< BasicPsiThermo, MixtureType >
volScalarField he_
Energy field.
Detailed Description
template<class BasicPsiThermo, class MixtureType>
class Foam::heheuPsiThermo< BasicPsiThermo, MixtureType >
Definition at line 49 of file heheuPsiThermo.H.
Constructor & Destructor Documentation
heheuPsiThermo()
heheuPsiThermo (const fvMesh & mesh, const word & phaseName)
Construct from mesh and phase name.
Definition at line 145 of file heheuPsiThermo.C.
References forAll, and patchi.
~heheuPsiThermo()
~heheuPsiThermo () virtual
Destructor.
Definition at line 220 of file heheuPsiThermo.C.
Member Function Documentation
TypeName()
TypeName ("heheuPsiThermo< BasicPsiThermo, MixtureType >")
Runtime type information.
correct()
void correct () virtual
Update properties.
Definition at line 227 of file heheuPsiThermo.C.
References Foam::endl(), heheuPsiThermo< BasicPsiThermo, MixtureType >::heu(), Foam::Info, and InfoInFunction.
heu() [1/4]
virtual volScalarField& heu () inline virtual
Unburnt gas enthalpy [J/kg].
Non-const access allowed for transport equations
Definition at line 99 of file heheuPsiThermo.H.
Referenced by heheuPsiThermo< BasicPsiThermo, MixtureType >::correct(), heheuPsiThermo< BasicPsiThermo, MixtureType >::heu(), and heheuPsiThermo< BasicPsiThermo, MixtureType >::Tu().
heu() [2/4]
virtual const volScalarField& heu () const inline virtual
Unburnt gas enthalpy [J/kg].
Definition at line 105 of file heheuPsiThermo.H.
Tu()
virtual const volScalarField& Tu () const inline virtual
Unburnt gas temperature [K].
Definition at line 111 of file heheuPsiThermo.H.
References cells, heheuPsiThermo< BasicPsiThermo, MixtureType >::heu(), heheuPsiThermo< BasicPsiThermo, MixtureType >::mub(), heheuPsiThermo< BasicPsiThermo, MixtureType >::muu(), p, patchi, heheuPsiThermo< BasicPsiThermo, MixtureType >::psib(), heheuPsiThermo< BasicPsiThermo, MixtureType >::psiu(), Foam::T(), and heheuPsiThermo< BasicPsiThermo, MixtureType >::Tb().
heu() [3/4]
Foam::tmp< Foam::scalarField > heu (const scalarField & p, const scalarField & T, const labelList & cells) const virtual
Unburnt gas enthalpy for cell-set [J/kg].
Definition at line 249 of file heheuPsiThermo.C.
References forAll, heheuPsiThermo< BasicPsiThermo, MixtureType >::heu(), tmp< T >::ref(), scalarField(), and List< T >::size().
heu() [4/4]
Foam::tmp< Foam::scalarField > heu (const scalarField & p, const scalarField & T, const label patchi) const virtual
Unburnt gas enthalpy for patch [J/kg].
Definition at line 270 of file heheuPsiThermo.C.
References forAll, tmp< T >::ref(), scalarField(), and List< T >::size().
Tb()
Foam::tmp< Foam::volScalarField > Tb () const virtual
Burnt gas temperature [K].
Definition at line 291 of file heheuPsiThermo.C.
References forAll, patchi, and GeometricField< Type, PatchField, GeoMesh >::ref().
Referenced by heheuPsiThermo< BasicPsiThermo, MixtureType >::Tu().
psiu()
Foam::tmp< Foam::volScalarField > psiu () const virtual
Unburnt gas compressibility [s^2/m^2].
Definition at line 350 of file heheuPsiThermo.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), forAll, patchi, GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef(), and tmp< T >::ref().
Referenced by heheuPsiThermo< BasicPsiThermo, MixtureType >::Tu().
psib()
Foam::tmp< Foam::volScalarField > psib () const virtual
Burnt gas compressibility [s^2/m^2].
Definition at line 404 of file heheuPsiThermo.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), forAll, patchi, GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef(), and tmp< T >::ref().
Referenced by heheuPsiThermo< BasicPsiThermo, MixtureType >::Tu().
muu()
Foam::tmp< Foam::volScalarField > muu () const virtual
Dynamic viscosity of unburnt gas [kg/ms].
Definition at line 459 of file heheuPsiThermo.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), forAll, patchi, GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef(), and tmp< T >::ref().
Referenced by heheuPsiThermo< BasicPsiThermo, MixtureType >::Tu().
mub()
Foam::tmp< Foam::volScalarField > mub () const virtual
Dynamic viscosity of burnt gas [kg/ms].
Definition at line 517 of file heheuPsiThermo.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), forAll, patchi, GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef(), and tmp< T >::ref().
Referenced by heheuPsiThermo< BasicPsiThermo, MixtureType >::Tu().
The documentation for this class was generated from the following files:
src/thermophysicalModels/reactionThermo/psiuReactionThermo/heheuPsiThermo.H
src/thermophysicalModels/reactionThermo/psiuReactionThermo/heheuPsiThermo.C