OpenFOAM: exponentialSolidTransport< Thermo > Class Template Reference
exponentialSolidTransport< Thermo > Class Template Reference
Exponential properties for solid heat transport Templated into a given thermodynamics package.
Public Member Functions
exponentialSolidTransport (const word &, const exponentialSolidTransport &)
Construct as named copy.
exponentialSolidTransport (const dictionary &)
Construct from dictionary.
scalar kappa (const scalar p, const scalar T) const
Thermal conductivity [W/mK].
vector Kappa (const scalar p, const scalar T) const
Thermal conductivity [W/mK].
scalar mu (const scalar p, const scalar T) const
Dynamic viscosity [kg/ms].
scalar alphah (const scalar p, const scalar T) const
Thermal diffusivity of enthalpy [kg/ms].
void write (Ostream &os) const
Write to Ostream.
void operator= (const exponentialSolidTransport &)
void operator+= (const exponentialSolidTransport &)
void operator-= (const exponentialSolidTransport &)
Static Public Member Functions
static autoPtr< exponentialSolidTransport > New (const dictionary &dict)
static word typeName ()
Return the instantiated type name.
Static Public Attributes
static const bool isotropic = true
Is the thermal conductivity isotropic.
Friends
exponentialSolidTransport operator* (const scalar, const exponentialSolidTransport &)
Ostream & operator (Ostream &, const exponentialSolidTransport &)
Detailed Description
template<class Thermo>
class Foam::exponentialSolidTransport< Thermo >
Exponential properties for solid heat transport Templated into a given thermodynamics package.
Source files
exponentialSolidTransport.H
exponentialSolidTransportI.H
exponentialSolidTransport.C
Definition at line 44 of file exponentialSolidTransport.H.
Constructor & Destructor Documentation
exponentialSolidTransport() [1/2]
exponentialSolidTransport (const word & name, const exponentialSolidTransport< Thermo > & ct) inline
Construct as named copy.
Definition at line 46 of file exponentialSolidTransportI.H.
References exponentialSolidTransport< Thermo >::New().
exponentialSolidTransport() [2/2]
exponentialSolidTransport (const dictionary & dict)
Construct from dictionary.
Definition at line 33 of file exponentialSolidTransport.C.
References dictionary::add(), dict, dictionaryName::dictName(), Foam::indent(), dictionary::lookup(), readScalar, dictionary::subDict(), Foam::tab, and write().
Member Function Documentation
New()
Foam::autoPtr< Foam::exponentialSolidTransport< Thermo > > New (const dictionary & dict) inline static
Definition at line 61 of file exponentialSolidTransportI.H.
References dict, and exponentialSolidTransport< Thermo >::kappa().
Referenced by exponentialSolidTransport< Thermo >::exponentialSolidTransport().
typeName()
static word typeName () inline static
Return the instantiated type name.
Definition at line 118 of file exponentialSolidTransport.H.
kappa()
Foam::scalar kappa (const scalar p, const scalar T) const inline
Thermal conductivity [W/mK].
Definition at line 75 of file exponentialSolidTransportI.H.
References exponentialSolidTransport< Thermo >::Kappa(), and Foam::pow().
Referenced by exponentialSolidTransport< Thermo >::alphah(), exponentialSolidTransport< Thermo >::Kappa(), and exponentialSolidTransport< Thermo >::New().
Kappa()
Foam::vector Kappa (const scalar p, const scalar T) const inline
Thermal conductivity [W/mK].
Definition at line 85 of file exponentialSolidTransportI.H.
References exponentialSolidTransport< Thermo >::kappa(), exponentialSolidTransport< Thermo >::mu(), and Foam::pow().
Referenced by exponentialSolidTransport< Thermo >::kappa().
mu()
Foam::scalar mu (const scalar p, const scalar T) const inline
Dynamic viscosity [kg/ms].
Definition at line 96 of file exponentialSolidTransportI.H.
References exponentialSolidTransport< Thermo >::alphah(), and NotImplemented.
Referenced by exponentialSolidTransport< Thermo >::Kappa().
alphah()
Foam::scalar alphah (const scalar p, const scalar T) const inline
Thermal diffusivity of enthalpy [kg/ms].
Definition at line 105 of file exponentialSolidTransportI.H.
References exponentialSolidTransport< Thermo >::kappa().
Referenced by exponentialSolidTransport< Thermo >::mu().
write()
void write (Ostream & os) const
Write to Ostream.
operator=()
void operator= (const exponentialSolidTransport< Thermo > &) inline
Definition at line 115 of file exponentialSolidTransportI.H.
operator+=()
void operator+= (const exponentialSolidTransport< Thermo > &) inline
Definition at line 127 of file exponentialSolidTransportI.H.
operator-=()
void operator-= (const exponentialSolidTransport< Thermo > &) inline
Definition at line 144 of file exponentialSolidTransportI.H.
References s().
Friends And Related Function Documentation
operator*
exponentialSolidTransport operator* (const scalar , const exponentialSolidTransport< Thermo > &) friend
operator
Ostream& operator (Ostream & , const exponentialSolidTransport< Thermo > &) friend
Member Data Documentation
isotropic
const bool isotropic = true static
Is the thermal conductivity isotropic.
Definition at line 124 of file exponentialSolidTransport.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/solidSpecie/transport/exponential/exponentialSolidTransport.H
src/thermophysicalModels/solidSpecie/transport/exponential/exponentialSolidTransport.C
src/thermophysicalModels/solidSpecie/transport/exponential/exponentialSolidTransportI.H