OpenFOAM: icoPolynomial< Specie, PolySize > Class Template Reference
icoPolynomial< Specie, PolySize > Class Template Reference
Incompressible, polynomial form of equation of state, using a polynomial function for density.
Public Member Functions
icoPolynomial (const Specie &sp, const Polynomial< PolySize > &rhoPoly)
Construct from components.
icoPolynomial (Istream &)
Construct from Istream.
icoPolynomial (const dictionary &dict)
Construct from dictionary.
icoPolynomial (const icoPolynomial &)
Construct as copy.
icoPolynomial (const word &name, const icoPolynomial &)
Construct as named copy.
autoPtr< icoPolynomial > clone () const
Construct and return a clone.
scalar rho (scalar p, scalar T) const
Return density [kg/m^3].
scalar h (const scalar p, const scalar T) const
Return enthalpy departure [J/kmol].
scalar cp (scalar p, scalar T) const
Return cp departure [J/(kmol K].
scalar s (const scalar p, const scalar T) const
Return entropy [J/(kmol K)].
scalar psi (scalar p, scalar T) const
Return compressibility rho/p [s^2/m^2].
scalar Z (scalar p, scalar T) const
Return compression factor [].
scalar cpMcv (scalar p, scalar T) const
Return (cp - cv) [J/(kmol K].
void write (Ostream &os) const
Write to Ostream.
void operator= (const icoPolynomial &)
void operator+= (const icoPolynomial &)
void operator-= (const icoPolynomial &)
void operator*= (const scalar)
Static Public Member Functions
static autoPtr< icoPolynomial > New (Istream &is)
static autoPtr< icoPolynomial > New (const dictionary &dict)
static word typeName ()
Return the instantiated type name.
Static Public Attributes
static const bool incompressible = true
Is the equation of state is incompressible i.e. rho != f(p)
static const bool isochoric = false
Is the equation of state is isochoric i.e. rho = const.
Friends
icoPolynomial operator+ (const icoPolynomial &, const icoPolynomial &)
icoPolynomial operator- (const icoPolynomial &, const icoPolynomial &)
icoPolynomial operator* (const scalar s, const icoPolynomial &)
icoPolynomial operator== (const icoPolynomial &, const icoPolynomial &)
Ostream & operator (Ostream &, const icoPolynomial &)
Detailed Description
template<class Specie, int PolySize = 8>
class Foam::icoPolynomial< Specie, PolySize >
Incompressible, polynomial form of equation of state, using a polynomial function for density.
Source files
icoPolynomial.H
icoPolynomialI.H
icoPolynomial.C
Definition at line 50 of file icoPolynomial.H.
Constructor & Destructor Documentation
icoPolynomial() [1/5]
icoPolynomial (const Specie & sp, const Polynomial< PolySize > & rhoPoly) inline
Construct from components.
Definition at line 32 of file icoPolynomialI.H.
References Foam::name().
icoPolynomial() [2/5]
icoPolynomial (Istream & is)
Construct from Istream.
Definition at line 37 of file icoPolynomial.C.
icoPolynomial() [3/5]
icoPolynomial (const dictionary & dict)
Construct from dictionary.
Definition at line 47 of file icoPolynomial.C.
icoPolynomial() [4/5]
icoPolynomial (const icoPolynomial< Specie, PolySize > &) inline
Construct as copy.
icoPolynomial() [5/5]
icoPolynomial (const word & name, const icoPolynomial< Specie, PolySize > &) inline
Construct as named copy.
Member Function Documentation
clone()
Foam::autoPtr< Foam::icoPolynomial< Specie, PolySize > > clone () const inline
Construct and return a clone.
Definition at line 69 of file icoPolynomialI.H.
New() [1/2]
Foam::autoPtr< Foam::icoPolynomial< Specie, PolySize > > New (Istream & is) inline static
Definition at line 80 of file icoPolynomialI.H.
New() [2/2]
Foam::autoPtr< Foam::icoPolynomial< Specie, PolySize > > New (const dictionary & dict) inline static
Definition at line 91 of file icoPolynomialI.H.
References dict, and icoPolynomial< Specie, PolySize >::rho().
typeName()
static word typeName () inline static
Return the instantiated type name.
Definition at line 140 of file icoPolynomial.H.
rho()
Foam::scalar rho (scalar p, scalar T) const inline
Return density [kg/m^3].
Definition at line 104 of file icoPolynomialI.H.
References icoPolynomial< Specie, PolySize >::h().
Referenced by icoPolynomial< Specie, PolySize >::New().
h()
Foam::scalar h (const scalar p, const scalar T) const inline
Return enthalpy departure [J/kmol].
Definition at line 115 of file icoPolynomialI.H.
References icoPolynomial< Specie, PolySize >::cp().
Referenced by icoPolynomial< Specie, PolySize >::rho().
cp()
Foam::scalar cp (scalar p, scalar T) const inline
Return cp departure [J/(kmol K].
Definition at line 126 of file icoPolynomialI.H.
References icoPolynomial< Specie, PolySize >::s().
Referenced by icoPolynomial< Specie, PolySize >::h().
s()
Foam::scalar s (const scalar p, const scalar T) const inline
Return entropy [J/(kmol K)].
Definition at line 137 of file icoPolynomialI.H.
References icoPolynomial< Specie, PolySize >::psi().
Referenced by icoPolynomial< Specie, PolySize >::cp().
psi()
Foam::scalar psi (scalar p, scalar T) const inline
Return compressibility rho/p [s^2/m^2].
Definition at line 148 of file icoPolynomialI.H.
References icoPolynomial< Specie, PolySize >::Z().
Referenced by icoPolynomial< Specie, PolySize >::s().
Z()
Foam::scalar Z (scalar p, scalar T) const inline
Return compression factor [].
Definition at line 159 of file icoPolynomialI.H.
References icoPolynomial< Specie, PolySize >::cpMcv().
Referenced by icoPolynomial< Specie, PolySize >::psi().
cpMcv()
Foam::scalar cpMcv (scalar p, scalar T) const inline
Return (cp - cv) [J/(kmol K].
Definition at line 170 of file icoPolynomialI.H.
References Foam::sqr().
Referenced by icoPolynomial< Specie, PolySize >::Z().
write()
void write (Ostream & os) const
Write to Ostream.
Definition at line 65 of file icoPolynomial.C.
References dictionary::add(), dict, dictionaryName::dictName(), Foam::indent(), Foam::name(), and write().
operator=()
void operator= (const icoPolynomial< Specie, PolySize > &) inline
Definition at line 183 of file icoPolynomialI.H.
operator+=()
void operator+= (const icoPolynomial< Specie, PolySize > &) inline
Definition at line 195 of file icoPolynomialI.H.
operator-=()
void operator-= (const icoPolynomial< Specie, PolySize > &) inline
Definition at line 212 of file icoPolynomialI.H.
operator*=()
void operator*= (const scalar s) inline
Definition at line 228 of file icoPolynomialI.H.
References s().
Friends And Related Function Documentation
operator+
icoPolynomial operator+ (const icoPolynomial< Specie, PolySize > & , const icoPolynomial< Specie, PolySize > &) friend
operator-
icoPolynomial operator- (const icoPolynomial< Specie, PolySize > & , const icoPolynomial< Specie, PolySize > &) friend
operator*
icoPolynomial operator* (const scalar s, const icoPolynomial< Specie, PolySize > &) friend
operator==
icoPolynomial operator== (const icoPolynomial< Specie, PolySize > & , const icoPolynomial< Specie, PolySize > &) friend
operator
Ostream& operator (Ostream & , const icoPolynomial< Specie, PolySize > &) friend
Member Data Documentation
incompressible
const bool incompressible = true static
Is the equation of state is incompressible i.e. rho != f(p)
Definition at line 149 of file icoPolynomial.H.
isochoric
const bool isochoric = false static
Is the equation of state is isochoric i.e. rho = const.
Definition at line 152 of file icoPolynomial.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/equationOfState/icoPolynomial/icoPolynomial.H
src/thermophysicalModels/specie/equationOfState/icoPolynomial/icoPolynomial.C
src/thermophysicalModels/specie/equationOfState/icoPolynomial/icoPolynomialI.H