OpenFOAM: pyrolysisChemistryModel< CompType, SolidThermo, GasThermo > Class Template Reference
pyrolysisChemistryModel< CompType, SolidThermo, GasThermo > Class Template Reference
Pyrolysis chemistry model. It includes gas phase in the solid reaction.
Public Member Functions
TypeName ("pyrolysis")
Runtime type information.
pyrolysisChemistryModel (const fvMesh &mesh, const word &phaseName)
Construct from mesh and phase name.
virtual ~pyrolysisChemistryModel ()
Destructor.
const PtrList< GasThermo > & gasThermo () const
Thermodynamic data of gases.
const speciesTable & gasTable () const
Gases table.
label nSpecie () const
The number of solids.
label nGases () const
The number of solids.
virtual scalarField omega (const scalarField &c, const scalar T, const scalar p, const bool updateC0=false) const
dc/dt = omega, rate of change in concentration, for each species
virtual scalar omega (const Reaction< SolidThermo > &r, const scalarField &c, const scalar T, const scalar p, scalar &pf, scalar &cf, label &lRef, scalar &pr, scalar &cr, label &rRef) const
Return the reaction rate for reaction r.
virtual scalar omegaI (label iReaction, const scalarField &c, const scalar T, const scalar p, scalar &pf, scalar &cf, label &lRef, scalar &pr, scalar &cr, label &rRef) const
Return the reaction rate for iReaction.
virtual void calculate ()
Calculates the reaction rates.
const volScalarField::Internal & RRg (const label i) const
Return const access to the chemical source terms for gases.
tmp< volScalarField::Internal > RRg () const
Return total gas source term.
virtual tmp< volScalarField > gasHs (const volScalarField &p, const volScalarField &T, const label i) const
Return sensible enthalpy for gas i [J/Kg].
virtual scalar solve (const scalar deltaT)
Solve the reaction system for the given time step.
virtual label nEqns () const
Number of ODE's to solve.
virtual void derivatives (const scalar t, const scalarField &c, scalarField &dcdt) const
Calculate the derivatives in dydx.
virtual void jacobian (const scalar t, const scalarField &c, scalarField &dcdt, scalarSquareMatrix &dfdc) const
Calculate the Jacobian of the system.
virtual void solve (scalarField &c, scalar &T, scalar &p, scalar &deltaT, scalar &subDeltaT) const
Public Member Functions inherited from solidChemistryModel< CompType, SolidThermo >
TypeName ("solidChemistryModel")
Runtime type information.
solidChemistryModel (const fvMesh &mesh, const word &phaseName)
Construct from mesh and phase name.
virtual ~solidChemistryModel ()
Destructor.
const PtrList< Reaction< SolidThermo > > & reactions () const
The reactions.
label nReaction () const
The number of reactions.
const volScalarField::Internal & RRs (const label i) const
Return const access to the chemical source terms for solids.
tmp< volScalarField::Internal > RRs () const
Return total solid source term.
virtual scalar solve (const scalarField &deltaT)
Solve the reaction system for the given time step.
virtual tmp< volScalarField > tc () const
Return the chemical time scale.
virtual tmp< volScalarField > Sh () const
Return source for enthalpy equation [kg/m/s3].
virtual tmp< volScalarField > dQ () const
Return the heat release, i.e. enthalpy/sec [m2/s3].
Public Member Functions inherited from ODESystem
ODESystem ()
Construct null.
virtual ~ODESystem ()
Destructor.
Protected Member Functions
PtrList< volScalarField::Internal > & RRg ()
Write access to source terms for gases.
Protected Member Functions inherited from solidChemistryModel< CompType, SolidThermo >
PtrList< volScalarField::Internal > & RRs ()
Write access to source terms for solids.
void setCellReacting (const label celli, const bool active)
Set reacting status of cell, celli.
Protected Attributes
speciesTable pyrolisisGases_
List of gas species present in reaction system.
PtrList< GasThermo > gasThermo_
Thermodynamic data of gases.
label nGases_
Number of gas species.
label nSpecie_
Number of components being solved by ODE.
PtrList< volScalarField::Internal > RRg_
List of reaction rate per gas [kg/m3/s].
Protected Attributes inherited from solidChemistryModel< CompType, SolidThermo >
PtrList< volScalarField > & Ys_
Reference to solid mass fractions.
const PtrList< Reaction< SolidThermo > > & reactions_
Reactions.
const PtrList< SolidThermo > & solidThermo_
Thermodynamic data of solids.
label nSolids_
Number of solid components.
label nReaction_
Number of solid reactions.
PtrList< volScalarField::Internal > RRs_
List of reaction rate per solid [kg/m3/s].
List< bool > reactingCells_
List of active reacting cells.
Detailed Description
template<class CompType, class SolidThermo, class GasThermo>
class Foam::pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >
Pyrolysis chemistry model. It includes gas phase in the solid reaction.
Source files
pyrolysisChemistryModel.H
pyrolysisChemistryModelI.H
pyrolysisChemistryModel.C
Definition at line 56 of file pyrolysisChemistryModel.H.
Constructor & Destructor Documentation
pyrolysisChemistryModel()
pyrolysisChemistryModel (const fvMesh & mesh, const word & phaseName)
Construct from mesh and phase name.
Definition at line 35 of file pyrolysisChemistryModel.C.
References dictName(), Foam::dimMass, Foam::dimTime, Foam::dimVolume, forAll, Foam::indent(), Foam::Info, Foam::max(), mesh, Foam::name(), Foam::nl, solidThermo::rho(), and pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::~pyrolysisChemistryModel().
~pyrolysisChemistryModel()
~pyrolysisChemistryModel () virtual
Destructor.
Definition at line 172 of file pyrolysisChemistryModel.C.
References pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::omega().
Referenced by pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::pyrolysisChemistryModel().
Member Function Documentation
RRg() [1/3]
Foam::PtrList< Foam::DimensionedField< Foam::scalar, Foam::volMesh > > & RRg () inline protected
Write access to source terms for gases.
Definition at line 33 of file pyrolysisChemistryModelI.H.
References pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::gasThermo().
Referenced by pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::nSpecie(), and pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::RRg().
TypeName()
TypeName ("pyrolysis")
Runtime type information.
gasThermo()
const Foam::PtrList< GasThermo > & gasThermo () const inline
Thermodynamic data of gases.
Definition at line 42 of file pyrolysisChemistryModelI.H.
References pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::gasTable().
Referenced by pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::RRg().
gasTable()
const Foam::speciesTable & gasTable () const inline
Gases table.
Definition at line 51 of file pyrolysisChemistryModelI.H.
References pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::nSpecie().
Referenced by pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::gasThermo().
nSpecie()
Foam::label nSpecie () const inline
The number of solids.
Definition at line 60 of file pyrolysisChemistryModelI.H.
References pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::RRg().
Referenced by pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::gasTable().
nGases()
label nGases () const inline
The number of solids.
omega() [1/2]
Foam::scalarField omega (const scalarField & c, const scalar T, const scalar p, const bool updateC0 = false) const virtual
dc/dt = omega, rate of change in concentration, for each species
Implements solidChemistryModel< CompType, SolidThermo >.
Definition at line 181 of file pyrolysisChemistryModel.C.
References forAll, g, Reaction< ReactionThermo >::grhs(), Reaction< ReactionThermo >::lhs(), R, Reaction< ReactionThermo >::rhs(), and s().
Referenced by pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::~pyrolysisChemistryModel().
omega() [2/2]
Foam::scalar omega (const Reaction< SolidThermo > & r, const scalarField & c, const scalar T, const scalar p, scalar & pf, scalar & cf, label & lRef, scalar & pr, scalar & cr, label & rRef) const virtual
Return the reaction rate for reaction r.
NOTE: Currently does not calculate reference specie and characteristic times (pf, cf,l Ref, etc.)
Implements solidChemistryModel< CompType, SolidThermo >.
Definition at line 237 of file pyrolysisChemistryModel.C.
References Foam::constant::physicoChemical::c1, Foam::exp(), Reaction< ReactionThermo >::kf(), Reaction< ReactionThermo >::lhs(), Foam::max(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::omegaI(), Foam::pow(), and s().
omegaI()
Foam::scalar omegaI (label iReaction, const scalarField & c, const scalar T, const scalar p, scalar & pf, scalar & cf, label & lRef, scalar & pr, scalar & cr, label & rRef) const virtual
Return the reaction rate for iReaction.
NOTE: Currently does not calculate reference specie and characteristic times (pf, cf,l Ref, etc.)
Implements solidChemistryModel< CompType, SolidThermo >.
Definition at line 280 of file pyrolysisChemistryModel.C.
References pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::derivatives().
Referenced by pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::omega().
calculate()
void calculate () virtual
Calculates the reaction rates.
Implements solidChemistryModel< CompType, SolidThermo >.
Definition at line 450 of file pyrolysisChemistryModel.C.
References Foam::constant::universal::c, delta, forAll, mesh, basicThermo::p(), Foam::constant::mathematical::pi(), rho, pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::solve(), basicThermo::T(), and timeName.
Referenced by pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::nEqns().
RRg() [2/3]
const Foam::DimensionedField< Foam::scalar, Foam::volMesh > & RRg (const label i) const inline
Return const access to the chemical source terms for gases.
Definition at line 69 of file pyrolysisChemistryModelI.H.
References pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::RRg().
RRg() [3/3]
Foam::tmp< Foam::DimensionedField< Foam::scalar, Foam::volMesh > > RRg () const inline
Return total gas source term.
Definition at line 80 of file pyrolysisChemistryModelI.H.
References Foam::dimMass, Foam::dimTime, Foam::dimVolume, mesh, tmp< T >::ref(), and timeName.
gasHs()
Foam::tmp< Foam::volScalarField > gasHs (const volScalarField & p, const volScalarField & T, const label i) const virtual
Return sensible enthalpy for gas i [J/Kg].
Definition at line 616 of file pyrolysisChemistryModel.C.
References Foam::dimEnergy, Foam::dimMass, forAll, tmp< T >::ref(), and pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::solve().
Referenced by pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::solve().
solve() [1/2]
Foam::scalar solve (const scalar deltaT) virtual
Solve the reaction system for the given time step.
and return the characteristic time
Implements solidChemistryModel< CompType, SolidThermo >.
Definition at line 518 of file pyrolysisChemistryModel.C.
References Foam::constant::universal::c, delta, forAll, pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::gasHs(), mesh, Foam::min(), basicThermo::p(), Foam::constant::mathematical::pi(), rho, solve(), basicThermo::T(), and timeName.
Referenced by pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::calculate(), and pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::gasHs().
nEqns()
Foam::label nEqns () const virtual
Number of ODE's to solve.
Implements solidChemistryModel< CompType, SolidThermo >.
Definition at line 441 of file pyrolysisChemistryModel.C.
References pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::calculate().
Referenced by pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::jacobian().
derivatives()
void derivatives (const scalar x, const scalarField & y, scalarField & dydx) const virtual
Calculate the derivatives in dydx.
Implements solidChemistryModel< CompType, SolidThermo >.
Definition at line 303 of file pyrolysisChemistryModel.C.
References pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::jacobian(), Foam::mag(), and Foam::min().
Referenced by pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::omegaI().
jacobian()
void jacobian (const scalar x, const scalarField & y, scalarField & dfdx, scalarSquareMatrix & dfdy) const virtual
Calculate the Jacobian of the system.
Need by the stiff-system solvers
Implements solidChemistryModel< CompType, SolidThermo >.
Definition at line 345 of file pyrolysisChemistryModel.C.
References Foam::constant::physicoChemical::c2, delta, Foam::endl(), Foam::exp(), forAll, Foam::Info, Reaction< ReactionThermo >::kf(), Reaction< ReactionThermo >::lhs(), Foam::max(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::nEqns(), Foam::pow(), and Reaction< ReactionThermo >::rhs().
Referenced by pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::derivatives().
solve() [2/2]
void solve (scalarField & c, scalar & T, scalar & p, scalar & deltaT, scalar & subDeltaT) const virtual
Implements solidChemistryModel< CompType, SolidThermo >.
Definition at line 655 of file pyrolysisChemistryModel.C.
References NotImplemented.
Member Data Documentation
pyrolisisGases_
speciesTable pyrolisisGases_ protected
List of gas species present in reaction system.
Definition at line 69 of file pyrolysisChemistryModel.H.
gasThermo_
PtrList<GasThermo> gasThermo_ protected
Thermodynamic data of gases.
Definition at line 72 of file pyrolysisChemistryModel.H.
nGases_
label nGases_ protected
Number of gas species.
Definition at line 75 of file pyrolysisChemistryModel.H.
nSpecie_
label nSpecie_ protected
Number of components being solved by ODE.
Definition at line 78 of file pyrolysisChemistryModel.H.
RRg_
PtrList<volScalarField::Internal> RRg_ protected
List of reaction rate per gas [kg/m3/s].
Definition at line 81 of file pyrolysisChemistryModel.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/solidChemistryModel/pyrolysisChemistryModel/pyrolysisChemistryModel.H
src/thermophysicalModels/solidChemistryModel/pyrolysisChemistryModel/pyrolysisChemistryModel.C
src/thermophysicalModels/solidChemistryModel/pyrolysisChemistryModel/pyrolysisChemistryModelI.H