OpenFOAM: veryInhomogeneousMixture< ThermoType > Class Template Reference
veryInhomogeneousMixture< ThermoType > Class Template Reference
Foam::veryInhomogeneousMixture.
Public Types
typedef ThermoType thermoType
The type of thermodynamics this mixture is instantiated for.
Public Types inherited from basicCombustionMixture
typedef basicCombustionMixture basicMixtureType
The base class of the mixture.
Public Types inherited from basicSpecieMixture
typedef basicSpecieMixture basicMixtureType
The base class of the mixture.
Public Types inherited from basicMultiComponentMixture
typedef basicMultiComponentMixture basicMixtureType
The base class of the mixture.
Public Member Functions
veryInhomogeneousMixture (const dictionary &, const fvMesh &, const word &)
Construct from dictionary, mesh and phase name.
virtual ~veryInhomogeneousMixture ()
Destructor.
const dimensionedScalar & stoicRatio () const
const ThermoType & mixture (const scalar, const scalar) const
const ThermoType & cellMixture (const label celli) const
const ThermoType & patchFaceMixture (const label patchi, const label facei) const
const ThermoType & cellReactants (const label celli) const
const ThermoType & patchFaceReactants (const label patchi, const label facei) const
const ThermoType & cellProducts (const label celli) const
const ThermoType & patchFaceProducts (const label patchi, const label facei) const
void read (const dictionary &)
Read dictionary.
const ThermoType & getLocalThermo (const label speciei) const
Return thermo based on index.
Public Member Functions inherited from basicCombustionMixture
TypeName ("basicCombustionMixture")
Run time type information.
basicCombustionMixture (const dictionary &, const wordList &specieNames, const fvMesh &, const word &)
Construct from dictionary, specie names, mesh and phase name.
virtual ~basicCombustionMixture ()
Destructor.
scalar fres (const scalar ft, const scalar stoicRatio) const
tmp< volScalarField > fres (const volScalarField &ft, const dimensionedScalar &stoicRatio) const
Public Member Functions inherited from basicSpecieMixture
TypeName ("basicSpecieMixture")
Run time type information.
basicSpecieMixture (const dictionary &, const wordList &specieNames, const fvMesh &, const word &)
Construct from dictionary, species names, mesh and phase name.
virtual ~basicSpecieMixture ()
Destructor.
virtual scalar nMoles (const label speciei) const =0
Number of moles of the given specie [].
virtual scalar W (const label speciei) const =0
Molecular weight of the given specie [kg/kmol].
tmp< volScalarField > W () const
Molecular weight of the mixture [kg/kmol].
virtual scalar Cp (const label speciei, const scalar p, const scalar T) const =0
Heat capacity at constant pressure [J/(kg K)].
virtual scalar Cv (const label speciei, const scalar p, const scalar T) const =0
Heat capacity at constant volume [J/(kg K)].
virtual scalar Ha (const label speciei, const scalar p, const scalar T) const =0
Absolute enthalpy [J/kg].
virtual scalar Hs (const label speciei, const scalar p, const scalar T) const =0
Sensible enthalpy [J/kg].
virtual scalar Hc (const label speciei) const =0
Chemical enthalpy [J/kg].
virtual scalar S (const label speciei, const scalar p, const scalar T) const =0
Entropy [J/(kg K)].
virtual scalar Es (const label speciei, const scalar p, const scalar T) const =0
Sensible internal energy [J/kg].
virtual scalar G (const label speciei, const scalar p, const scalar T) const =0
Gibbs free energy [J/kg].
virtual scalar A (const label speciei, const scalar p, const scalar T) const =0
Helmholtz free energy [J/kg].
virtual scalar mu (const label speciei, const scalar p, const scalar T) const =0
Dynamic viscosity [kg/m/s].
virtual scalar kappa (const label speciei, const scalar p, const scalar T) const =0
Thermal conductivity [W/m/K].
virtual scalar alphah (const label speciei, const scalar p, const scalar T) const =0
Thermal diffusivity of enthalpy [kg/m/s].
virtual scalar rho (const label speciei, const scalar p, const scalar T) const =0
Density [kg/m3].
Public Member Functions inherited from basicMultiComponentMixture
TypeName ("basicMultiComponentMixture")
Run time type information.
basicMultiComponentMixture (const dictionary &, const wordList &specieNames, const fvMesh &, const word &)
Construct from dictionary, species names, mesh and phase name.
virtual ~basicMultiComponentMixture ()
Destructor.
const speciesTable & species () const
Return the table of species.
bool contains (const word &specieName) const
Does the mixture include this specie?
bool active (label speciei) const
Return true for active species.
const List< bool > & active () const
Return the bool list of active species.
void setActive (label speciei)
Set speciei active.
void setInactive (label speciei)
Set speciei inactive.
PtrList< volScalarField > & Y ()
Return the mass-fraction fields.
const PtrList< volScalarField > & Y () const
Return the const mass-fraction fields.
volScalarField & Y (const label i)
Return the mass-fraction field for a specie given by index.
const volScalarField & Y (const label i) const
Return the const mass-fraction field for a specie given by index.
volScalarField & Y (const word &specieName)
Return the mass-fraction field for a specie given by name.
const volScalarField & Y (const word &specieName) const
Return the const mass-fraction field for a specie given by name.
Additional Inherited Members
Protected Attributes inherited from basicMultiComponentMixture
speciesTable species_
Table of specie names.
List< bool > active_
List of specie active flags.
PtrList< volScalarField > Y_
Species mass fractions.
Detailed Description
template<class ThermoType>
class Foam::veryInhomogeneousMixture< ThermoType >
Foam::veryInhomogeneousMixture.
Source files
veryInhomogeneousMixture.H
veryInhomogeneousMixture.C
Definition at line 49 of file veryInhomogeneousMixture.H.
Member Typedef Documentation
thermoType
typedef ThermoType thermoType
The type of thermodynamics this mixture is instantiated for.
Definition at line 82 of file veryInhomogeneousMixture.H.
Constructor & Destructor Documentation
veryInhomogeneousMixture()
veryInhomogeneousMixture (const dictionary & thermoDict, const fvMesh & mesh, const word & phaseName)
Construct from dictionary, mesh and phase name.
Definition at line 44 of file veryInhomogeneousMixture.C.
References veryInhomogeneousMixture< ThermoType >::mixture().
~veryInhomogeneousMixture()
virtual ~veryInhomogeneousMixture () inline virtual
Destructor.
Definition at line 97 of file veryInhomogeneousMixture.H.
Member Function Documentation
stoicRatio()
const dimensionedScalar& stoicRatio () const inline
Definition at line 103 of file veryInhomogeneousMixture.H.
References veryInhomogeneousMixture< ThermoType >::mixture().
Referenced by veryInhomogeneousMixture< ThermoType >::cellProducts(), and veryInhomogeneousMixture< ThermoType >::patchFaceProducts().
mixture()
const ThermoType & mixture (const scalar ft, const scalar fu) const
Definition at line 76 of file veryInhomogeneousMixture.C.
References veryInhomogeneousMixture< ThermoType >::read().
Referenced by veryInhomogeneousMixture< ThermoType >::cellMixture(), veryInhomogeneousMixture< ThermoType >::cellProducts(), veryInhomogeneousMixture< ThermoType >::cellReactants(), veryInhomogeneousMixture< ThermoType >::patchFaceMixture(), veryInhomogeneousMixture< ThermoType >::patchFaceProducts(), veryInhomogeneousMixture< ThermoType >::patchFaceReactants(), veryInhomogeneousMixture< ThermoType >::stoicRatio(), and veryInhomogeneousMixture< ThermoType >::veryInhomogeneousMixture().
cellMixture()
const ThermoType& cellMixture (const label celli) const inline
Definition at line 110 of file veryInhomogeneousMixture.H.
References veryInhomogeneousMixture< ThermoType >::mixture(), and veryInhomogeneousMixture< ThermoType >::patchFaceMixture().
patchFaceMixture()
const ThermoType& patchFaceMixture (const label patchi, const label facei) const inline
Definition at line 116 of file veryInhomogeneousMixture.H.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), veryInhomogeneousMixture< ThermoType >::mixture(), and patchi.
Referenced by veryInhomogeneousMixture< ThermoType >::cellMixture().
cellReactants()
const ThermoType& cellReactants (const label celli) const inline
Definition at line 128 of file veryInhomogeneousMixture.H.
References veryInhomogeneousMixture< ThermoType >::mixture(), and veryInhomogeneousMixture< ThermoType >::patchFaceReactants().
patchFaceReactants()
const ThermoType& patchFaceReactants (const label patchi, const label facei) const inline
Definition at line 134 of file veryInhomogeneousMixture.H.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), veryInhomogeneousMixture< ThermoType >::mixture(), and patchi.
Referenced by veryInhomogeneousMixture< ThermoType >::cellReactants().
cellProducts()
const ThermoType& cellProducts (const label celli) const inline
Definition at line 146 of file veryInhomogeneousMixture.H.
References basicCombustionMixture::fres(), veryInhomogeneousMixture< ThermoType >::mixture(), veryInhomogeneousMixture< ThermoType >::patchFaceProducts(), and veryInhomogeneousMixture< ThermoType >::stoicRatio().
patchFaceProducts()
const ThermoType& patchFaceProducts (const label patchi, const label facei) const inline
Definition at line 153 of file veryInhomogeneousMixture.H.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), basicCombustionMixture::fres(), veryInhomogeneousMixture< ThermoType >::getLocalThermo(), veryInhomogeneousMixture< ThermoType >::mixture(), patchi, veryInhomogeneousMixture< ThermoType >::read(), and veryInhomogeneousMixture< ThermoType >::stoicRatio().
Referenced by veryInhomogeneousMixture< ThermoType >::cellProducts().
read()
void read (const dictionary & thermoDict)
Read dictionary.
Definition at line 101 of file veryInhomogeneousMixture.C.
References veryInhomogeneousMixture< ThermoType >::getLocalThermo(), and dictionary::subDict().
Referenced by veryInhomogeneousMixture< ThermoType >::mixture(), and veryInhomogeneousMixture< ThermoType >::patchFaceProducts().
getLocalThermo()
const ThermoType & getLocalThermo (const label speciei) const
Return thermo based on index.
Definition at line 113 of file veryInhomogeneousMixture.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Referenced by veryInhomogeneousMixture< ThermoType >::patchFaceProducts(), and veryInhomogeneousMixture< ThermoType >::read().
The documentation for this class was generated from the following files:
src/thermophysicalModels/reactionThermo/mixtures/veryInhomogeneousMixture/veryInhomogeneousMixture.H
src/thermophysicalModels/reactionThermo/mixtures/veryInhomogeneousMixture/veryInhomogeneousMixture.C