OpenFOAM: constAnIsoSolidTransport< Thermo > Class Template Reference
constAnIsoSolidTransport< Thermo > Class Template Reference
Constant properties Transport package. Templated into a given Thermodynamics package (needed for thermal conductivity).
Public Member Functions
constAnIsoSolidTransport (const word &, const constAnIsoSolidTransport &)
Construct as named copy.
constAnIsoSolidTransport (const dictionary &)
Construct from dictionary.
scalar kappa (const scalar p, const scalar T) const
Isotropic thermal conductivity [W/mK].
vector Kappa (const scalar p, const scalar T) const
Un-isotropic thermal conductivity [W/mK].
scalar mu (const scalar p, const scalar T) const
Dynamic viscosity [kg/ms].
vector alphah (const scalar p, const scalar T) const
Thermal diffusivity of enthalpy [kg/ms].
void write (Ostream &os) const
Write to Ostream.
void operator= (const constAnIsoSolidTransport &)
void operator+= (const constAnIsoSolidTransport &)
void operator-= (const constAnIsoSolidTransport &)
Static Public Member Functions
static autoPtr< constAnIsoSolidTransport > New (const dictionary &dict)
static word typeName ()
Return the instantiated type name.
Static Public Attributes
static const bool isotropic = false
Is the thermal conductivity isotropic.
Friends
constAnIsoSolidTransport operator* (const scalar, const constAnIsoSolidTransport &)
Ostream & operator (Ostream &, const constAnIsoSolidTransport &)
Detailed Description
template<class Thermo>
class Foam::constAnIsoSolidTransport< Thermo >
Constant properties Transport package. Templated into a given Thermodynamics package (needed for thermal conductivity).
Source files
constAnIsoSolidTransport.H
constAnIsoSolidTransportI.H
constAnIsoSolidTransport.C
Definition at line 46 of file constAnIsoSolidTransport.H.
Constructor & Destructor Documentation
constAnIsoSolidTransport() [1/2]
constAnIsoSolidTransport (const word & name, const constAnIsoSolidTransport< Thermo > & ct) inline
Construct as named copy.
Definition at line 42 of file constAnIsoSolidTransportI.H.
References constAnIsoSolidTransport< Thermo >::New().
constAnIsoSolidTransport() [2/2]
constAnIsoSolidTransport (const dictionary & dict)
Construct from dictionary.
Definition at line 33 of file constAnIsoSolidTransport.C.
References dictionary::add(), dict, dictionaryName::dictName(), Foam::indent(), Foam::tab, and write().
Member Function Documentation
New()
Foam::autoPtr< Foam::constAnIsoSolidTransport< Thermo > > New (const dictionary & dict) inline static
Definition at line 55 of file constAnIsoSolidTransportI.H.
References dict, and constAnIsoSolidTransport< Thermo >::kappa().
Referenced by constAnIsoSolidTransport< Thermo >::constAnIsoSolidTransport().
typeName()
static word typeName () inline static
Return the instantiated type name.
Definition at line 108 of file constAnIsoSolidTransport.H.
kappa()
Foam::scalar kappa (const scalar p, const scalar T) const inline
Isotropic thermal conductivity [W/mK].
Definition at line 69 of file constAnIsoSolidTransportI.H.
References constAnIsoSolidTransport< Thermo >::Kappa(), and Foam::mag().
Referenced by constAnIsoSolidTransport< Thermo >::New().
Kappa()
Foam::vector Kappa (const scalar p, const scalar T) const inline
Un-isotropic thermal conductivity [W/mK].
Definition at line 76 of file constAnIsoSolidTransportI.H.
References constAnIsoSolidTransport< Thermo >::mu().
Referenced by constAnIsoSolidTransport< Thermo >::kappa().
mu()
Foam::scalar mu (const scalar p, const scalar T) const inline
Dynamic viscosity [kg/ms].
Definition at line 84 of file constAnIsoSolidTransportI.H.
References constAnIsoSolidTransport< Thermo >::alphah(), and NotImplemented.
Referenced by constAnIsoSolidTransport< Thermo >::Kappa().
alphah()
Foam::vector alphah (const scalar p, const scalar T) const inline
Thermal diffusivity of enthalpy [kg/ms].
Definition at line 93 of file constAnIsoSolidTransportI.H.
Referenced by constAnIsoSolidTransport< Thermo >::mu().
write()
void write (Ostream & os) const
Write to Ostream.
operator=()
void operator= (const constAnIsoSolidTransport< Thermo > &) inline
Definition at line 102 of file constAnIsoSolidTransportI.H.
operator+=()
void operator+= (const constAnIsoSolidTransport< Thermo > &) inline
Definition at line 112 of file constAnIsoSolidTransportI.H.
operator-=()
void operator-= (const constAnIsoSolidTransport< Thermo > &) inline
Definition at line 127 of file constAnIsoSolidTransportI.H.
References s().
Friends And Related Function Documentation
operator*
constAnIsoSolidTransport operator* (const scalar , const constAnIsoSolidTransport< Thermo > &) friend
operator
Ostream& operator (Ostream & , const constAnIsoSolidTransport< Thermo > &) friend
Member Data Documentation
isotropic
const bool isotropic = false static
Is the thermal conductivity isotropic.
Definition at line 114 of file constAnIsoSolidTransport.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/solidSpecie/transport/const/constAnIsoSolidTransport.H
src/thermophysicalModels/solidSpecie/transport/const/constAnIsoSolidTransport.C
src/thermophysicalModels/solidSpecie/transport/const/constAnIsoSolidTransportI.H