OpenFOAM: incompressiblePerfectGas< Specie > Class Template Reference
incompressiblePerfectGas< Specie > Class Template Reference
Incompressible gas equation of state using a constant reference pressure in the perfect gas equation of state rather than the local pressure so that the density only varies with temperature and composition.
Public Member Functions
incompressiblePerfectGas (const Specie &sp, const scalar pRef)
Construct from components.
incompressiblePerfectGas (const incompressiblePerfectGas &sp)
Construct from incompressiblePerfectGas.
incompressiblePerfectGas (Istream &)
Construct from Istream.
incompressiblePerfectGas (const dictionary &dict)
Construct from dictionary.
incompressiblePerfectGas (const word &name, const incompressiblePerfectGas &)
Construct as named copy.
autoPtr< incompressiblePerfectGas > clone () const
Construct and return a clone.
scalar rho (scalar p, scalar T) const
Return density [kg/m^3].
scalar h (const scalar p, const scalar T) const
Return enthalpy departure [J/kmol].
scalar cp (scalar p, scalar T) const
Return cp departure [J/(kmol K].
scalar s (const scalar p, const scalar T) const
Return entropy [J/(kmol K)].
scalar psi (scalar p, scalar T) const
Return compressibility rho/p [s^2/m^2].
scalar Z (scalar p, scalar T) const
Return compression factor [].
scalar cpMcv (scalar p, scalar T) const
Return (cp - cv) [J/(kmol K].
void write (Ostream &os) const
Write to Ostream.
void operator= (const incompressiblePerfectGas &)
void operator+= (const incompressiblePerfectGas &)
void operator-= (const incompressiblePerfectGas &)
void operator*= (const scalar)
Static Public Member Functions
static autoPtr< incompressiblePerfectGas > New (Istream &is)
static autoPtr< incompressiblePerfectGas > New (const dictionary &dict)
static word typeName ()
Return the instantiated type name.
Static Public Attributes
static const bool incompressible = true
Is the equation of state is incompressible i.e. rho != f(p)
static const bool isochoric = false
Is the equation of state is isochoric i.e. rho = const.
Friends
incompressiblePerfectGas operator+ (const incompressiblePerfectGas &, const incompressiblePerfectGas &)
incompressiblePerfectGas operator- (const incompressiblePerfectGas &, const incompressiblePerfectGas &)
incompressiblePerfectGas operator* (const scalar s, const incompressiblePerfectGas &)
incompressiblePerfectGas operator== (const incompressiblePerfectGas &, const incompressiblePerfectGas &)
Ostream & operator (Ostream &, const incompressiblePerfectGas &)
Detailed Description
template<class Specie>
class Foam::incompressiblePerfectGas< Specie >
Incompressible gas equation of state using a constant reference pressure in the perfect gas equation of state rather than the local pressure so that the density only varies with temperature and composition.
Source files
incompressiblePerfectGas.H
incompressiblePerfectGasI.H
incompressiblePerfectGas.C
Definition at line 49 of file incompressiblePerfectGas.H.
Constructor & Destructor Documentation
incompressiblePerfectGas() [1/5]
incompressiblePerfectGas (const Specie & sp, const scalar pRef) inline
Construct from components.
Definition at line 33 of file incompressiblePerfectGasI.H.
Referenced by incompressiblePerfectGas< Specie >::incompressiblePerfectGas().
incompressiblePerfectGas() [2/5]
incompressiblePerfectGas (const incompressiblePerfectGas< Specie > & sp) inline
Construct from incompressiblePerfectGas.
Definition at line 44 of file incompressiblePerfectGasI.H.
References incompressiblePerfectGas< Specie >::incompressiblePerfectGas(), and Foam::name().
incompressiblePerfectGas() [3/5]
incompressiblePerfectGas (Istream & is)
Construct from Istream.
Definition at line 32 of file incompressiblePerfectGas.C.
References IOstream::check(), and incompressiblePerfectGas< Specie >::incompressiblePerfectGas().
incompressiblePerfectGas() [4/5]
incompressiblePerfectGas (const dictionary & dict)
Construct from dictionary.
Definition at line 47 of file incompressiblePerfectGas.C.
incompressiblePerfectGas() [5/5]
incompressiblePerfectGas (const word & name, const incompressiblePerfectGas< Specie > &) inline
Construct as named copy.
Member Function Documentation
clone()
Foam::autoPtr< Foam::incompressiblePerfectGas< Specie > > clone () const inline
Construct and return a clone.
Definition at line 67 of file incompressiblePerfectGasI.H.
References incompressiblePerfectGas< Specie >::New().
New() [1/2]
Foam::autoPtr< Foam::incompressiblePerfectGas< Specie > > New (Istream & is) inline static
Definition at line 79 of file incompressiblePerfectGasI.H.
Referenced by incompressiblePerfectGas< Specie >::clone().
New() [2/2]
Foam::autoPtr< Foam::incompressiblePerfectGas< Specie > > New (const dictionary & dict) inline static
Definition at line 93 of file incompressiblePerfectGasI.H.
References dict, and incompressiblePerfectGas< Specie >::rho().
typeName()
static word typeName () inline static
Return the instantiated type name.
Definition at line 141 of file incompressiblePerfectGas.H.
rho()
Foam::scalar rho (scalar p, scalar T) const inline
Return density [kg/m^3].
Definition at line 108 of file incompressiblePerfectGasI.H.
References incompressiblePerfectGas< Specie >::h(), R, and T.
Referenced by incompressiblePerfectGas< Specie >::New().
h()
Foam::scalar h (const scalar p, const scalar T) const inline
Return enthalpy departure [J/kmol].
Definition at line 119 of file incompressiblePerfectGasI.H.
References incompressiblePerfectGas< Specie >::cp().
Referenced by incompressiblePerfectGas< Specie >::rho().
cp()
Foam::scalar cp (scalar p, scalar T) const inline
Return cp departure [J/(kmol K].
Definition at line 130 of file incompressiblePerfectGasI.H.
References incompressiblePerfectGas< Specie >::s().
Referenced by incompressiblePerfectGas< Specie >::h().
s()
Foam::scalar s (const scalar p, const scalar T) const inline
Return entropy [J/(kmol K)].
Definition at line 141 of file incompressiblePerfectGasI.H.
References incompressiblePerfectGas< Specie >::psi().
Referenced by incompressiblePerfectGas< Specie >::cp().
psi()
Foam::scalar psi (scalar p, scalar T) const inline
Return compressibility rho/p [s^2/m^2].
Definition at line 152 of file incompressiblePerfectGasI.H.
References incompressiblePerfectGas< Specie >::Z().
Referenced by incompressiblePerfectGas< Specie >::s().
Z()
Foam::scalar Z (scalar p, scalar T) const inline
Return compression factor [].
Definition at line 163 of file incompressiblePerfectGasI.H.
References incompressiblePerfectGas< Specie >::cpMcv().
Referenced by incompressiblePerfectGas< Specie >::psi().
cpMcv()
Foam::scalar cpMcv (scalar p, scalar T) const inline
Return (cp - cv) [J/(kmol K].
Definition at line 174 of file incompressiblePerfectGasI.H.
References Foam::constant::thermodynamic::RR.
Referenced by incompressiblePerfectGas< Specie >::Z().
write()
void write (Ostream & os) const
Write to Ostream.
Definition at line 59 of file incompressiblePerfectGas.C.
References dictionary::add(), dict, dictionaryName::dictName(), Foam::indent(), token::SPACE, and write().
operator=()
void operator= (const incompressiblePerfectGas< Specie > &) inline
Definition at line 187 of file incompressiblePerfectGasI.H.
operator+=()
void operator+= (const incompressiblePerfectGas< Specie > &) inline
Definition at line 198 of file incompressiblePerfectGasI.H.
operator-=()
void operator-= (const incompressiblePerfectGas< Specie > &) inline
Definition at line 213 of file incompressiblePerfectGasI.H.
operator*=()
void operator*= (const scalar s) inline
Definition at line 223 of file incompressiblePerfectGasI.H.
References s().
Friends And Related Function Documentation
operator+
incompressiblePerfectGas operator+ (const incompressiblePerfectGas< Specie > & , const incompressiblePerfectGas< Specie > &) friend
operator-
incompressiblePerfectGas operator- (const incompressiblePerfectGas< Specie > & , const incompressiblePerfectGas< Specie > &) friend
operator*
incompressiblePerfectGas operator* (const scalar s, const incompressiblePerfectGas< Specie > &) friend
operator==
incompressiblePerfectGas operator== (const incompressiblePerfectGas< Specie > & , const incompressiblePerfectGas< Specie > &) friend
operator
Ostream& operator (Ostream & , const incompressiblePerfectGas< Specie > &) friend
Member Data Documentation
incompressible
const bool incompressible = true static
Is the equation of state is incompressible i.e. rho != f(p)
Definition at line 152 of file incompressiblePerfectGas.H.
isochoric
const bool isochoric = false static
Is the equation of state is isochoric i.e. rho = const.
Definition at line 155 of file incompressiblePerfectGas.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/equationOfState/incompressiblePerfectGas/incompressiblePerfectGas.H
src/thermophysicalModels/specie/equationOfState/incompressiblePerfectGas/incompressiblePerfectGas.C
src/thermophysicalModels/specie/equationOfState/incompressiblePerfectGas/incompressiblePerfectGasI.H