OpenFOAM: SpecieMixture< MixtureType > Class Template Reference
SpecieMixture< MixtureType > Class Template Reference abstract
Foam::SpecieMixture.
Public Member Functions
SpecieMixture (const dictionary &, const fvMesh &, const word &phaseName)
Construct from dictionary, mesh and phase name.
virtual ~SpecieMixture ()
Destructor.
virtual scalar nMoles (const label speciei) const
Number of moles of the given specie [].
virtual scalar W (const label speciei) const
Molecular weight of the given specie [kg/kmol].
virtual scalar Cp (const label speciei, const scalar p, const scalar T) const
Heat capacity at constant pressure [J/(kg K)].
virtual scalar Cv (const label speciei, const scalar p, const scalar T) const
Heat capacity at constant volume [J/(kg K)].
virtual scalar Ha (const label speciei, const scalar p, const scalar T) const
Absolute enthalpy [J/kg].
virtual scalar Hs (const label speciei, const scalar p, const scalar T) const
Sensible enthalpy [J/kg].
virtual scalar Hc (const label speciei) const
Chemical enthalpy [J/kg].
virtual scalar S (const label speciei, const scalar p, const scalar T) const
Entropy [J/(kg K)].
virtual scalar Es (const label speciei, const scalar p, const scalar T) const
Sensible internal energy [J/kg].
virtual scalar G (const label speciei, const scalar p, const scalar T) const
Gibbs free energy [J/kg].
virtual scalar A (const label speciei, const scalar p, const scalar T) const
Helmholtz free energy [J/kg].
virtual scalar mu (const label speciei, const scalar p, const scalar T) const
Dynamic viscosity [kg/m/s].
virtual scalar kappa (const label speciei, const scalar p, const scalar T) const
Thermal conductivity [W/m/K].
virtual scalar alphah (const label speciei, const scalar p, const scalar T) const
Thermal diffusivity of enthalpy [kg/m/s].
virtual scalar rho (const label speciei, const scalar p, const scalar T) const
Density [kg/m3].
virtual tmp< scalarField > Cp (const scalarField &p, const scalarField &T, const label patchi) const =0
Heat capacity at constant pressure for patch [J/kg/K].
virtual tmp< volScalarField > Cp () const =0
Heat capacity at constant pressure for patch [J/kg/K].
virtual tmp< scalarField > Cv (const scalarField &p, const scalarField &T, const label patchi) const =0
Heat capacity at constant volume for patch [J/kg/K].
virtual tmp< volScalarField > Cv () const =0
Heat capacity at constant volume [J/kg/K].
virtual tmp< scalarField > kappa (const label patchi) const =0
Thermal diffusivity for temperature.
virtual tmp< volScalarField > kappa () const =0
Thermal diffusivity for temperature of mixture [J/m/s/K].
Detailed Description
template<class MixtureType>
class Foam::SpecieMixture< MixtureType >
Foam::SpecieMixture.
Source files
SpecieMixture.H
SpecieMixture.C
Definition at line 55 of file SpecieMixture.H.
Constructor & Destructor Documentation
SpecieMixture()
SpecieMixture (const dictionary & thermoDict, const fvMesh & mesh, const word & phaseName)
Construct from dictionary, mesh and phase name.
Definition at line 34 of file SpecieMixture.C.
References SpecieMixture< MixtureType >::nMoles().
~SpecieMixture()
virtual ~SpecieMixture () inline virtual
Destructor.
Definition at line 69 of file SpecieMixture.H.
References SpecieMixture< MixtureType >::A(), SpecieMixture< MixtureType >::alphah(), SpecieMixture< MixtureType >::Cp(), SpecieMixture< MixtureType >::Cv(), SpecieMixture< MixtureType >::Es(), SpecieMixture< MixtureType >::G(), SpecieMixture< MixtureType >::Ha(), SpecieMixture< MixtureType >::Hc(), SpecieMixture< MixtureType >::Hs(), SpecieMixture< MixtureType >::kappa(), SpecieMixture< MixtureType >::mu(), SpecieMixture< MixtureType >::nMoles(), p, patchi, SpecieMixture< MixtureType >::rho(), SpecieMixture< MixtureType >::S(), Foam::T(), and SpecieMixture< MixtureType >::W().
Member Function Documentation
nMoles()
Foam::scalar nMoles (const label speciei) const virtual
Number of moles of the given specie [].
Definition at line 53 of file SpecieMixture.C.
References SpecieMixture< MixtureType >::W().
Referenced by SpecieMixture< MixtureType >::SpecieMixture(), and SpecieMixture< MixtureType >::~SpecieMixture().
W()
Foam::scalar W (const label speciei) const virtual
Molecular weight of the given specie [kg/kmol].
Definition at line 63 of file SpecieMixture.C.
References SpecieMixture< MixtureType >::Cp().
Referenced by SpecieMixture< MixtureType >::nMoles(), and SpecieMixture< MixtureType >::~SpecieMixture().
Cp() [1/3]
Foam::scalar Cp (const label speciei, const scalar p, const scalar T) const virtual
Heat capacity at constant pressure [J/(kg K)].
Definition at line 73 of file SpecieMixture.C.
References SpecieMixture< MixtureType >::Cv().
Cv() [1/3]
Foam::scalar Cv (const label speciei, const scalar p, const scalar T) const virtual
Heat capacity at constant volume [J/(kg K)].
Definition at line 85 of file SpecieMixture.C.
References SpecieMixture< MixtureType >::Ha().
Ha()
Foam::scalar Ha (const label speciei, const scalar p, const scalar T) const virtual
Absolute enthalpy [J/kg].
Definition at line 97 of file SpecieMixture.C.
References SpecieMixture< MixtureType >::Hs().
Referenced by SpecieMixture< MixtureType >::Cv(), and SpecieMixture< MixtureType >::~SpecieMixture().
Hs()
Foam::scalar Hs (const label speciei, const scalar p, const scalar T) const virtual
Sensible enthalpy [J/kg].
Definition at line 109 of file SpecieMixture.C.
References SpecieMixture< MixtureType >::Hc().
Referenced by SpecieMixture< MixtureType >::Ha(), and SpecieMixture< MixtureType >::~SpecieMixture().
Hc()
Foam::scalar Hc (const label speciei) const virtual
Chemical enthalpy [J/kg].
Definition at line 121 of file SpecieMixture.C.
References SpecieMixture< MixtureType >::S().
Referenced by SpecieMixture< MixtureType >::Hs(), and SpecieMixture< MixtureType >::~SpecieMixture().
S()
Foam::scalar S (const label speciei, const scalar p, const scalar T) const virtual
Entropy [J/(kg K)].
Definition at line 131 of file SpecieMixture.C.
References SpecieMixture< MixtureType >::Es().
Referenced by SpecieMixture< MixtureType >::Hc(), and SpecieMixture< MixtureType >::~SpecieMixture().
Es()
Foam::scalar Es (const label speciei, const scalar p, const scalar T) const virtual
Sensible internal energy [J/kg].
Definition at line 143 of file SpecieMixture.C.
References SpecieMixture< MixtureType >::G().
Referenced by SpecieMixture< MixtureType >::S(), and SpecieMixture< MixtureType >::~SpecieMixture().
G()
Foam::scalar G (const label speciei, const scalar p, const scalar T) const virtual
Gibbs free energy [J/kg].
Definition at line 155 of file SpecieMixture.C.
References SpecieMixture< MixtureType >::A().
Referenced by SpecieMixture< MixtureType >::Es(), and SpecieMixture< MixtureType >::~SpecieMixture().
A()
Foam::scalar A (const label speciei, const scalar p, const scalar T) const virtual
Helmholtz free energy [J/kg].
Definition at line 167 of file SpecieMixture.C.
References SpecieMixture< MixtureType >::mu().
Referenced by SpecieMixture< MixtureType >::G(), and SpecieMixture< MixtureType >::~SpecieMixture().
mu()
Foam::scalar mu (const label speciei, const scalar p, const scalar T) const virtual
Dynamic viscosity [kg/m/s].
Definition at line 179 of file SpecieMixture.C.
References SpecieMixture< MixtureType >::kappa().
Referenced by SpecieMixture< MixtureType >::A(), and SpecieMixture< MixtureType >::~SpecieMixture().
kappa() [1/3]
Foam::scalar kappa (const label speciei, const scalar p, const scalar T) const virtual
Thermal conductivity [W/m/K].
Definition at line 191 of file SpecieMixture.C.
References SpecieMixture< MixtureType >::alphah().
alphah()
Foam::scalar alphah (const label speciei, const scalar p, const scalar T) const virtual
Thermal diffusivity of enthalpy [kg/m/s].
Definition at line 203 of file SpecieMixture.C.
References SpecieMixture< MixtureType >::rho().
Referenced by SpecieMixture< MixtureType >::kappa(), and SpecieMixture< MixtureType >::~SpecieMixture().
rho()
Foam::scalar rho (const label speciei, const scalar p, const scalar T) const virtual
Density [kg/m3].
Definition at line 215 of file SpecieMixture.C.
Referenced by SpecieMixture< MixtureType >::alphah(), and SpecieMixture< MixtureType >::~SpecieMixture().
Cp() [2/3]
virtual tmp<scalarField> Cp (const scalarField & p, const scalarField & T, const label patchi) const pure virtual
Heat capacity at constant pressure for patch [J/kg/K].
Cp() [3/3]
virtual tmp<volScalarField> Cp () const pure virtual
Heat capacity at constant pressure for patch [J/kg/K].
Referenced by SpecieMixture< MixtureType >::W(), and SpecieMixture< MixtureType >::~SpecieMixture().
Cv() [2/3]
virtual tmp<scalarField> Cv (const scalarField & p, const scalarField & T, const label patchi) const pure virtual
Heat capacity at constant volume for patch [J/kg/K].
Cv() [3/3]
virtual tmp<volScalarField> Cv () const pure virtual
Heat capacity at constant volume [J/kg/K].
Referenced by SpecieMixture< MixtureType >::Cp(), and SpecieMixture< MixtureType >::~SpecieMixture().
kappa() [2/3]
virtual tmp<scalarField> kappa (const label patchi) const pure virtual
Thermal diffusivity for temperature.
of mixture for patch [J/m/s/K]
kappa() [3/3]
virtual tmp<volScalarField> kappa () const pure virtual
Thermal diffusivity for temperature of mixture [J/m/s/K].
Referenced by SpecieMixture< MixtureType >::mu(), and SpecieMixture< MixtureType >::~SpecieMixture().
The documentation for this class was generated from the following files:
src/thermophysicalModels/reactionThermo/mixtures/SpecieMixture/SpecieMixture.H
src/thermophysicalModels/reactionThermo/mixtures/SpecieMixture/SpecieMixture.C