OpenFOAM: solidReaction< ReactionThermo > Class Template Reference
solidReaction< ReactionThermo > Class Template Reference
Read solid reactions of the type S1 = S2 + G1.
Public Member Functions
TypeName ("SolidReaction")
Runtime type information.
solidReaction (const Reaction< ReactionThermo > &reaction, const speciesTable &pyrolisisGases, const List< specieCoeffs > &glhs, const List< specieCoeffs > &grhs)
Construct from components.
solidReaction (const solidReaction< ReactionThermo > &, const speciesTable &pyrolisisGases)
Construct as copy given new speciesTable.
solidReaction (const speciesTable &pyrolisisGases, const HashPtrTable< ReactionThermo > &thermoDatabase, Istream &is)
Construct from Istream.
solidReaction (const speciesTable &species, const HashPtrTable< ReactionThermo > &thermoDatabase, const dictionary &dict)
Construct from dictionary.
virtual autoPtr< Reaction< ReactionThermo > > clone () const
Construct and return a clone.
virtual autoPtr< Reaction< ReactionThermo > > clone (const speciesTable &species) const
Construct and return a clone with new speciesTable.
virtual ~solidReaction ()
Destructor.
virtual const List< specieCoeffs > & grhs () const
virtual const List< specieCoeffs > & glhs () const
virtual const speciesTable & gasSpecies () const
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from Reaction< ReactionThermo >
TypeName ("Reaction")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, Reaction, Istream,(const speciesTable &species, const HashPtrTable< ReactionThermo > &thermoDatabase, Istream &is),(species, thermoDatabase, is))
declareRunTimeSelectionTable (autoPtr, Reaction, dictionary,(const speciesTable &species, const HashPtrTable< ReactionThermo > &thermoDatabase, const dictionary &dict),(species, thermoDatabase, dict))
Reaction (const speciesTable &species, const List< specieCoeffs > &lhs, const List< specieCoeffs > &rhs, const HashPtrTable< ReactionThermo > &thermoDatabase)
Construct from components.
Reaction (const Reaction< ReactionThermo > &, const speciesTable &species)
Construct as copy given new speciesTable.
Reaction (const speciesTable &species, const HashPtrTable< ReactionThermo > &thermoDatabase, Istream &is)
Construct from Istream.
Reaction (const speciesTable &species, const HashPtrTable< ReactionThermo > &thermoDatabase, const dictionary &dict)
Construct from dictionary.
virtual ~Reaction ()
Destructor.
word & name ()
const word & name () const
const List< specieCoeffs > & lhs () const
const List< specieCoeffs > & rhs () const
const speciesTable & species () const
void setLRhs (Istream &, const speciesTable &, List< specieCoeffs > &lhs, List< specieCoeffs > &rhs)
Construct the left- and right-hand-side reaction coefficients.
virtual scalar kf (const scalar p, const scalar T, const scalarField &c) const
Forward rate constant.
virtual scalar kr (const scalar kfwd, const scalar p, const scalar T, const scalarField &c) const
Reverse rate constant from the given forward rate constant.
virtual scalar kr (const scalar p, const scalar T, const scalarField &c) const
Reverse rate constant.
Friends
Ostream & operator (Ostream &, const solidReaction< ReactionThermo > &)
Additional Inherited Members
Static Public Member Functions inherited from Reaction< ReactionThermo >
static autoPtr< Reaction< ReactionThermo > > New (const speciesTable &species, const HashPtrTable< ReactionThermo > &thermoDatabase, Istream &is)
Return a pointer to new patchField created on freestore from input.
static autoPtr< Reaction< ReactionThermo > > New (const speciesTable &species, const HashPtrTable< ReactionThermo > &thermoDatabase, const dictionary &dict)
Return a pointer to new patchField created on freestore from dict.
Static Public Attributes inherited from Reaction< ReactionThermo >
static label nUnNamedReactions = 0
Number of un-named reactions.
Protected Member Functions inherited from Reaction< ReactionThermo >
void reactionStrLeft (OStringStream &reaction) const
Return string representation of the left of the reaction.
void reactionStrRight (OStringStream &reaction) const
Return string representation of the right of the reaction.
Detailed Description
template<class ReactionThermo>
class Foam::solidReaction< ReactionThermo >
Read solid reactions of the type S1 = S2 + G1.
Source files
solidReaction.H
solidReactionI.H
solidReaction.C
Definition at line 49 of file solidReaction.H.
Constructor & Destructor Documentation
solidReaction() [1/4]
solidReaction (const Reaction< ReactionThermo > & reaction, const speciesTable & pyrolisisGases, const List< specieCoeffs > & glhs, const List< specieCoeffs > & grhs)
Construct from components.
Definition at line 34 of file solidReaction.C.
Referenced by solidReaction< ReactionThermo >::solidReaction().
solidReaction() [2/4]
solidReaction (const solidReaction< ReactionThermo > & r, const speciesTable & pyrolisisGases)
Construct as copy given new speciesTable.
Definition at line 50 of file solidReaction.C.
References solidReaction< ReactionThermo >::solidReaction().
solidReaction() [3/4]
solidReaction (const speciesTable & pyrolisisGases, const HashPtrTable< ReactionThermo > & thermoDatabase, Istream & is)
Construct from Istream.
Definition at line 64 of file solidReaction.C.
References NotImplemented, and solidReaction< ReactionThermo >::solidReaction().
solidReaction() [4/4]
solidReaction (const speciesTable & species, const HashPtrTable< ReactionThermo > & thermoDatabase, const dictionary & dict)
Construct from dictionary.
Definition at line 81 of file solidReaction.C.
References dictionary::lookup().
~solidReaction()
virtual ~solidReaction () inline virtual
Destructor.
Definition at line 163 of file solidReaction.H.
References solidReaction< ReactionThermo >::gasSpecies(), solidReaction< ReactionThermo >::glhs(), solidReaction< ReactionThermo >::grhs(), and solidReaction< ReactionThermo >::write().
Member Function Documentation
TypeName()
TypeName ("SolidReaction")
Runtime type information.
clone() [1/2]
virtual autoPtr<Reaction<ReactionThermo> > clone () const inline virtual
Construct and return a clone.
Reimplemented from Reaction< ReactionThermo >.
Definition at line 141 of file solidReaction.H.
clone() [2/2]
virtual autoPtr<Reaction<ReactionThermo> > clone (const speciesTable & species) const inline virtual
Construct and return a clone with new speciesTable.
Reimplemented from Reaction< ReactionThermo >.
Definition at line 151 of file solidReaction.H.
References Reaction< ReactionThermo >::species().
grhs()
const Foam::List< typename Foam::Reaction< ReactionThermo >::specieCoeffs > & grhs () const virtual
Reimplemented from Reaction< ReactionThermo >.
Definition at line 114 of file solidReaction.C.
References solidReaction< ReactionThermo >::gasSpecies().
Referenced by solidReaction< ReactionThermo >::~solidReaction().
glhs()
const Foam::List< typename Foam::solidReaction< ReactionThermo >::specieCoeffs > & glhs () const virtual
Reimplemented from Reaction< ReactionThermo >.
Definition at line 106 of file solidReaction.C.
Referenced by solidReaction< ReactionThermo >::~solidReaction().
gasSpecies()
const Foam::speciesTable & gasSpecies () const virtual
Reimplemented from Reaction< ReactionThermo >.
Definition at line 122 of file solidReaction.C.
Referenced by solidReaction< ReactionThermo >::grhs(), and solidReaction< ReactionThermo >::~solidReaction().
write()
void write (Ostream & os) const virtual
Write.
Reimplemented from Reaction< ReactionThermo >.
Definition at line 129 of file solidReaction.C.
References Foam::mag(), Foam::nl, reaction(), List< T >::size(), OStringStream::str(), and Ostream::writeKeyword().
Referenced by solidReaction< ReactionThermo >::~solidReaction().
Friends And Related Function Documentation
operator
Ostream& operator (Ostream & , const solidReaction< ReactionThermo > &) friend
The documentation for this class was generated from the following files:
src/thermophysicalModels/solidSpecie/reaction/Reactions/solidReaction/solidReaction.H
src/thermophysicalModels/solidSpecie/reaction/Reactions/solidReaction/solidReaction.C