OpenFOAM: Boussinesq< Specie > Class Template Reference
Boussinesq< Specie > Class Template Reference
Incompressible gas equation of state using the Boussinesq approximation for the density as a function of temperature only:
Public Member Functions
Boussinesq (const Specie &sp, const scalar rho0, const scalar T0, const scalar beta)
Construct from components.
Boussinesq (const Boussinesq &sp)
Construct from Boussinesq.
Boussinesq (Istream &)
Construct from Istream.
Boussinesq (const dictionary &dict)
Construct from dictionary.
Boussinesq (const word &name, const Boussinesq &)
Construct as named copy.
autoPtr< Boussinesq > clone () const
Construct and return a clone.
scalar rho (scalar p, scalar T) const
Return density [kg/m^3].
scalar h (const scalar p, const scalar T) const
Return enthalpy departure [J/kmol].
scalar cp (scalar p, scalar T) const
Return cp departure [J/(kmol K].
scalar s (const scalar p, const scalar T) const
Return entropy [J/(kmol K)].
scalar psi (scalar p, scalar T) const
Return compressibility rho/p [s^2/m^2].
scalar Z (scalar p, scalar T) const
Return compression factor [].
scalar cpMcv (scalar p, scalar T) const
Return (cp - cv) [J/(kmol K].
void write (Ostream &os) const
Write to Ostream.
void operator= (const Boussinesq &)
void operator+= (const Boussinesq &)
void operator-= (const Boussinesq &)
void operator*= (const scalar)
Static Public Member Functions
static autoPtr< Boussinesq > New (Istream &is)
static autoPtr< Boussinesq > New (const dictionary &dict)
static word typeName ()
Return the instantiated type name.
Static Public Attributes
static const bool incompressible = true
Is the equation of state is incompressible i.e. rho != f(p)
static const bool isochoric = false
Is the equation of state is isochoric i.e. rho = const.
Friends
Boussinesq operator+ (const Boussinesq &, const Boussinesq &)
Boussinesq operator- (const Boussinesq &, const Boussinesq &)
Boussinesq operator* (const scalar s, const Boussinesq &)
Boussinesq operator== (const Boussinesq &, const Boussinesq &)
Ostream & operator (Ostream &, const Boussinesq &)
Detailed Description
template<class Specie>
class Foam::Boussinesq< Specie >
Incompressible gas equation of state using the Boussinesq approximation for the density as a function of temperature only:
    rho = rho0*(1 - beta*(T - T0))
Source files
Boussinesq.H
BoussinesqI.H
Boussinesq.C
Definition at line 52 of file Boussinesq.H.
Constructor & Destructor Documentation
Boussinesq() [1/5]
Boussinesq (const Specie & sp, const scalar rho0, const scalar T0, const scalar beta) inline
Construct from components.
Definition at line 33 of file BoussinesqI.H.
Referenced by Boussinesq< Specie >::Boussinesq().
Boussinesq() [2/5]
Boussinesq (const Boussinesq< Specie > & sp) inline
Construct from Boussinesq.
Definition at line 46 of file BoussinesqI.H.
References Boussinesq< Specie >::Boussinesq(), and Foam::name().
Boussinesq() [3/5]
Boussinesq (Istream & is)
Construct from Istream.
Definition at line 32 of file Boussinesq.C.
References Boussinesq< Specie >::Boussinesq(), and IOstream::check().
Boussinesq() [4/5]
Boussinesq (const dictionary & dict)
Construct from dictionary.
Definition at line 49 of file Boussinesq.C.
Boussinesq() [5/5]
Boussinesq (const word & name, const Boussinesq< Specie > &) inline
Construct as named copy.
Member Function Documentation
clone()
Foam::autoPtr< Foam::Boussinesq< Specie > > clone () const inline
Construct and return a clone.
Definition at line 73 of file BoussinesqI.H.
References Boussinesq< Specie >::New().
New() [1/2]
Foam::autoPtr< Foam::Boussinesq< Specie > > New (Istream & is) inline static
Definition at line 85 of file BoussinesqI.H.
Referenced by Boussinesq< Specie >::clone().
New() [2/2]
Foam::autoPtr< Foam::Boussinesq< Specie > > New (const dictionary & dict) inline static
Definition at line 99 of file BoussinesqI.H.
References dict, and Boussinesq< Specie >::rho().
typeName()
static word typeName () inline static
Return the instantiated type name.
Definition at line 156 of file Boussinesq.H.
rho()
Foam::scalar rho (scalar p, scalar T) const inline
Return density [kg/m^3].
Definition at line 114 of file BoussinesqI.H.
Referenced by Boussinesq< Specie >::New().
h()
Foam::scalar h (const scalar p, const scalar T) const inline
Return enthalpy departure [J/kmol].
Definition at line 124 of file BoussinesqI.H.
cp()
Foam::scalar cp (scalar p, scalar T) const inline
Return cp departure [J/(kmol K].
Definition at line 131 of file BoussinesqI.H.
References Boussinesq< Specie >::s().
s()
Foam::scalar s (const scalar p, const scalar T) const inline
Return entropy [J/(kmol K)].
Definition at line 139 of file BoussinesqI.H.
References Boussinesq< Specie >::psi().
Referenced by Boussinesq< Specie >::cp().
psi()
Foam::scalar psi (scalar p, scalar T) const inline
Return compressibility rho/p [s^2/m^2].
Definition at line 150 of file BoussinesqI.H.
References Boussinesq< Specie >::Z().
Referenced by Boussinesq< Specie >::s().
Z()
Foam::scalar Z (scalar p, scalar T) const inline
Return compression factor [].
Definition at line 161 of file BoussinesqI.H.
References Boussinesq< Specie >::cpMcv().
Referenced by Boussinesq< Specie >::psi().
cpMcv()
Foam::scalar cpMcv (scalar p, scalar T) const inline
Return (cp - cv) [J/(kmol K].
Definition at line 172 of file BoussinesqI.H.
References Foam::constant::thermodynamic::RR.
Referenced by Boussinesq< Specie >::Z().
write()
void write (Ostream & os) const
Write to Ostream.
Definition at line 63 of file Boussinesq.C.
References dictionary::add(), Foam::constant::physicoChemical::b, dict, dictionaryName::dictName(), Foam::indent(), token::SPACE, and write().
operator=()
void operator= (const Boussinesq< Specie > &) inline
Definition at line 185 of file BoussinesqI.H.
operator+=()
void operator+= (const Boussinesq< Specie > &) inline
Definition at line 199 of file BoussinesqI.H.
operator-=()
void operator-= (const Boussinesq< Specie > &) inline
Definition at line 216 of file BoussinesqI.H.
operator*=()
void operator*= (const scalar s) inline
Definition at line 228 of file BoussinesqI.H.
References Foam::constant::physicoChemical::b, and s().
Friends And Related Function Documentation
operator+
Boussinesq operator+ (const Boussinesq< Specie > & , const Boussinesq< Specie > &) friend
operator-
Boussinesq operator- (const Boussinesq< Specie > & , const Boussinesq< Specie > &) friend
operator*
Boussinesq operator* (const scalar s, const Boussinesq< Specie > &) friend
operator==
Boussinesq operator== (const Boussinesq< Specie > & , const Boussinesq< Specie > &) friend
operator
Ostream& operator (Ostream & , const Boussinesq< Specie > &) friend
Member Data Documentation
incompressible
const bool incompressible = true static
Is the equation of state is incompressible i.e. rho != f(p)
Definition at line 167 of file Boussinesq.H.
isochoric
const bool isochoric = false static
Is the equation of state is isochoric i.e. rho = const.
Definition at line 170 of file Boussinesq.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/equationOfState/Boussinesq/Boussinesq.H
src/thermophysicalModels/specie/equationOfState/Boussinesq/Boussinesq.C
src/thermophysicalModels/specie/equationOfState/Boussinesq/BoussinesqI.H