OpenFOAM: solidChemistryModel< CompType, SolidThermo > Class Template Reference
solidChemistryModel< CompType, SolidThermo > Class Template Reference abstract
Extends base solid chemistry model by adding a thermo package, and ODE functions. Introduces chemistry equation system and evaluation of chemical source terms.
Public Member Functions
TypeName ("solidChemistryModel")
Runtime type information.
solidChemistryModel (const fvMesh &mesh, const word &phaseName)
Construct from mesh and phase name.
virtual ~solidChemistryModel ()
Destructor.
const PtrList< Reaction< SolidThermo > > & reactions () const
The reactions.
label nReaction () const
The number of reactions.
virtual scalarField omega (const scalarField &c, const scalar T, const scalar p, const bool updateC0=false) const =0
dc/dt = omega, rate of change in concentration, for each species
virtual scalar omega (const Reaction< SolidThermo > &r, const scalarField &c, const scalar T, const scalar p, scalar &pf, scalar &cf, label &lRef, scalar &pr, scalar &cr, label &rRef) const =0
Return the reaction rate for reaction r and the reference.
virtual scalar omegaI (label iReaction, const scalarField &c, const scalar T, const scalar p, scalar &pf, scalar &cf, label &lRef, scalar &pr, scalar &cr, label &rRef) const =0
Return the reaction rate for iReaction and the reference.
virtual void calculate ()=0
Calculates the reaction rates.
const volScalarField::Internal & RRs (const label i) const
Return const access to the chemical source terms for solids.
tmp< volScalarField::Internal > RRs () const
Return total solid source term.
virtual scalar solve (const scalar deltaT)=0
Solve the reaction system for the given time step.
virtual scalar solve (const scalarField &deltaT)
Solve the reaction system for the given time step.
virtual tmp< volScalarField > tc () const
Return the chemical time scale.
virtual tmp< volScalarField > Sh () const
Return source for enthalpy equation [kg/m/s3].
virtual tmp< volScalarField > dQ () const
Return the heat release, i.e. enthalpy/sec [m2/s3].
virtual label nEqns () const =0
Number of ODE's to solve.
virtual void derivatives (const scalar t, const scalarField &c, scalarField &dcdt) const =0
Calculate the derivatives in dydx.
virtual void jacobian (const scalar t, const scalarField &c, scalarField &dcdt, scalarSquareMatrix &dfdc) const =0
Calculate the Jacobian of the system.
virtual void solve (scalarField &c, scalar &T, scalar &p, scalar &deltaT, scalar &subDeltaT) const =0
Public Member Functions inherited from ODESystem
ODESystem ()
Construct null.
virtual ~ODESystem ()
Destructor.
Protected Member Functions
PtrList< volScalarField::Internal > & RRs ()
Write access to source terms for solids.
void setCellReacting (const label celli, const bool active)
Set reacting status of cell, celli.
Protected Attributes
PtrList< volScalarField > & Ys_
Reference to solid mass fractions.
const PtrList< Reaction< SolidThermo > > & reactions_
Reactions.
const PtrList< SolidThermo > & solidThermo_
Thermodynamic data of solids.
label nSolids_
Number of solid components.
label nReaction_
Number of solid reactions.
PtrList< volScalarField::Internal > RRs_
List of reaction rate per solid [kg/m3/s].
List< bool > reactingCells_
List of active reacting cells.
Detailed Description
template<class CompType, class SolidThermo>
class Foam::solidChemistryModel< CompType, SolidThermo >
Extends base solid chemistry model by adding a thermo package, and ODE functions. Introduces chemistry equation system and evaluation of chemical source terms.
Source files
solidChemistryModel.H
solidChemistryModelI.H
solidChemistryModel.C
Definition at line 59 of file solidChemistryModel.H.
Constructor & Destructor Documentation
solidChemistryModel()
solidChemistryModel (const fvMesh & mesh, const word & phaseName)
Construct from mesh and phase name.
Definition at line 34 of file solidChemistryModel.C.
References Foam::dimMass, Foam::dimTime, Foam::dimVolume, forAll, mesh, Foam::name(), fvMesh::time(), Time::timeName(), and solidChemistryModel< CompType, SolidThermo >::~solidChemistryModel().
~solidChemistryModel()
~solidChemistryModel () virtual
Destructor.
Definition at line 89 of file solidChemistryModel.C.
References solidChemistryModel< CompType, SolidThermo >::solve().
Referenced by solidChemistryModel< CompType, SolidThermo >::solidChemistryModel().
Member Function Documentation
RRs() [1/3]
Foam::PtrList< Foam::DimensionedField< Foam::scalar, Foam::volMesh > > & RRs () inline protected
Write access to source terms for solids.
Definition at line 32 of file solidChemistryModelI.H.
Referenced by solidChemistryModel< CompType, SolidThermo >::nReaction().
setCellReacting()
void setCellReacting (const label celli, const bool active) protected
Set reacting status of cell, celli.
Definition at line 189 of file solidChemistryModel.C.
Referenced by solidChemistryModel< CompType, SolidThermo >::dQ().
TypeName()
TypeName ("solidChemistryModel< CompType, SolidThermo >")
Runtime type information.
reactions()
const Foam::PtrList< Foam::Reaction< SolidThermo > > & reactions () const inline
The reactions.
Definition at line 39 of file solidChemistryModelI.H.
References solidChemistryModel< CompType, SolidThermo >::nReaction().
nReaction()
Foam::label nReaction () const inline
The number of reactions.
Definition at line 48 of file solidChemistryModelI.H.
References solidChemistryModel< CompType, SolidThermo >::RRs().
Referenced by solidChemistryModel< CompType, SolidThermo >::reactions().
omega() [1/2]
virtual scalarField omega (const scalarField & c, const scalar T, const scalar p, const bool updateC0 = false) const pure virtual
dc/dt = omega, rate of change in concentration, for each species
Implemented in pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >.
omega() [2/2]
virtual scalar omega (const Reaction< SolidThermo > & r, const scalarField & c, const scalar T, const scalar p, scalar & pf, scalar & cf, label & lRef, scalar & pr, scalar & cr, label & rRef) const pure virtual
Return the reaction rate for reaction r and the reference.
species and charateristic times
Implemented in pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >.
omegaI()
virtual scalar omegaI (label iReaction, const scalarField & c, const scalar T, const scalar p, scalar & pf, scalar & cf, label & lRef, scalar & pr, scalar & cr, label & rRef) const pure virtual
Return the reaction rate for iReaction and the reference.
species and charateristic times
Implemented in pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >.
calculate()
virtual void calculate () pure virtual
Calculates the reaction rates.
Implemented in pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >.
RRs() [2/3]
const Foam::DimensionedField< Foam::scalar, Foam::volMesh > & RRs (const label i) const inline
Return const access to the chemical source terms for solids.
Definition at line 57 of file solidChemistryModelI.H.
RRs() [3/3]
Foam::tmp< Foam::DimensionedField< Foam::scalar, Foam::volMesh > > RRs () const inline
Return total solid source term.
Definition at line 67 of file solidChemistryModelI.H.
References Foam::dimMass, Foam::dimTime, Foam::dimVolume, mesh, tmp< T >::ref(), and timeName.
solve() [1/3]
virtual scalar solve (const scalar deltaT) pure virtual
Solve the reaction system for the given time step.
and return the characteristic time
Implemented in pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >.
Referenced by solidChemistryModel< CompType, SolidThermo >::~solidChemistryModel().
solve() [2/3]
Foam::scalar solve (const scalarField & deltaT) virtual
Solve the reaction system for the given time step.
and return the characteristic time
Definition at line 97 of file solidChemistryModel.C.
References NotImplemented.
tc()
Foam::tmp< Foam::volScalarField > tc () const virtual
Return the chemical time scale.
Definition at line 108 of file solidChemistryModel.C.
References NotImplemented.
Sh()
Foam::tmp< Foam::volScalarField > Sh () const virtual
Return source for enthalpy equation [kg/m/s3].
Definition at line 117 of file solidChemistryModel.C.
References Foam::dimEnergy, Foam::dimTime, Foam::dimVolume, forAll, tmp< T >::ref(), and Sh.
dQ()
Foam::tmp< Foam::volScalarField > dQ () const virtual
Return the heat release, i.e. enthalpy/sec [m2/s3].
Definition at line 157 of file solidChemistryModel.C.
References Foam::dimEnergy, Foam::dimTime, dQ, tmp< T >::ref(), GeometricField< Type, PatchField, GeoMesh >::ref(), solidChemistryModel< CompType, SolidThermo >::setCellReacting(), and Sh.
nEqns()
virtual label nEqns () const pure virtual
Number of ODE's to solve.
Implements ODESystem.
Implemented in pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >.
derivatives()
virtual void derivatives (const scalar x, const scalarField & y, scalarField & dydx) const pure virtual
Calculate the derivatives in dydx.
Implements ODESystem.
Implemented in pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >.
jacobian()
virtual void jacobian (const scalar x, const scalarField & y, scalarField & dfdx, scalarSquareMatrix & dfdy) const pure virtual
Calculate the Jacobian of the system.
Need by the stiff-system solvers
Implements ODESystem.
Implemented in pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >.
solve() [3/3]
virtual void solve (scalarField & c, scalar & T, scalar & p, scalar & deltaT, scalar & subDeltaT) const pure virtual
Implemented in pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >.
Member Data Documentation
Ys_
PtrList<volScalarField>& Ys_ protected
Reference to solid mass fractions.
Definition at line 76 of file solidChemistryModel.H.
reactions_
const PtrList<Reaction<SolidThermo> >& reactions_ protected
Reactions.
Definition at line 79 of file solidChemistryModel.H.
solidThermo_
const PtrList<SolidThermo>& solidThermo_ protected
Thermodynamic data of solids.
Definition at line 82 of file solidChemistryModel.H.
nSolids_
label nSolids_ protected
Number of solid components.
Definition at line 85 of file solidChemistryModel.H.
nReaction_
label nReaction_ protected
Number of solid reactions.
Definition at line 88 of file solidChemistryModel.H.
RRs_
PtrList<volScalarField::Internal> RRs_ protected
List of reaction rate per solid [kg/m3/s].
Definition at line 91 of file solidChemistryModel.H.
reactingCells_
List<bool> reactingCells_ protected
List of active reacting cells.
Definition at line 94 of file solidChemistryModel.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/solidChemistryModel/solidChemistryModel/solidChemistryModel.H
src/thermophysicalModels/solidChemistryModel/solidChemistryModel/solidChemistryModel.C
src/thermophysicalModels/solidChemistryModel/solidChemistryModel/solidChemistryModelI.H