OpenFOAM: ChemicallyActivatedReactionRate< ReactionRate, ChemicallyActivationFunction > Class Template Reference
ChemicallyActivatedReactionRate< ReactionRate, ChemicallyActivationFunction > Class Template Reference
General class for handling chemically-activated bimolecular reactions.
Public Member Functions
ChemicallyActivatedReactionRate (const ReactionRate &k0, const ReactionRate &kInf, const ChemicallyActivationFunction &F, const thirdBodyEfficiencies &tbes)
Construct from components.
ChemicallyActivatedReactionRate (const speciesTable &species, Istream &is)
Construct from Istream.
ChemicallyActivatedReactionRate (const speciesTable &species, const dictionary &dict)
Construct from dictionary.
scalar operator() (const scalar p, const scalar T, const scalarField &c) const
void write (Ostream &os) const
Write to stream.
Static Public Member Functions
static word type ()
Return the type name.
Friends
Ostream & operator (Ostream &, const ChemicallyActivatedReactionRate< ReactionRate, ChemicallyActivationFunction > &)
Detailed Description
template<class ReactionRate, class ChemicallyActivationFunction>
class Foam::ChemicallyActivatedReactionRate< ReactionRate, ChemicallyActivationFunction >
General class for handling chemically-activated bimolecular reactions.
Source files
ChemicallyActivatedReactionRate.H
ChemicallyActivatedReactionRateI.H
Definition at line 47 of file ChemicallyActivatedReactionRate.H.
Constructor & Destructor Documentation
ChemicallyActivatedReactionRate() [1/3]
ChemicallyActivatedReactionRate (const ReactionRate & k0, const ReactionRate & kInf, const ChemicallyActivationFunction & F, const thirdBodyEfficiencies & tbes) inline
Construct from components.
Definition at line 34 of file ChemicallyActivatedReactionRateI.H.
ChemicallyActivatedReactionRate() [2/3]
ChemicallyActivatedReactionRate (const speciesTable & species, Istream & is) inline
Construct from Istream.
Definition at line 54 of file ChemicallyActivatedReactionRateI.H.
References Istream::readEnd().
ChemicallyActivatedReactionRate() [3/3]
ChemicallyActivatedReactionRate (const speciesTable & species, const dictionary & dict) inline
Construct from dictionary.
Definition at line 74 of file ChemicallyActivatedReactionRateI.H.
Member Function Documentation
type()
static word type () inline static
Return the type name.
Definition at line 104 of file ChemicallyActivatedReactionRate.H.
References Foam::constant::universal::c, ChemicallyActivatedReactionRate< ReactionRate, ChemicallyActivationFunction >::operator, p, Foam::T(), Foam::type(), and ChemicallyActivatedReactionRate< ReactionRate, ChemicallyActivationFunction >::write().
operator()()
Foam::scalar operator() (const scalar p, const scalar T, const scalarField & c) const inline
Definition at line 94 of file ChemicallyActivatedReactionRateI.H.
References Foam::constant::universal::c, and Pr().
write()
void write (Ostream & os) const inline
Write to stream.
Definition at line 114 of file ChemicallyActivatedReactionRateI.H.
Referenced by ChemicallyActivatedReactionRate< ReactionRate, ChemicallyActivationFunction >::type().
Friends And Related Function Documentation
operator
Ostream& operator (Ostream & , const ChemicallyActivatedReactionRate< ReactionRate, ChemicallyActivationFunction > &) friend
Referenced by ChemicallyActivatedReactionRate< ReactionRate, ChemicallyActivationFunction >::type().
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/reaction/reactionRate/ChemicallyActivatedReactionRate/ChemicallyActivatedReactionRate.H
src/thermophysicalModels/specie/reaction/reactionRate/ChemicallyActivatedReactionRate/ChemicallyActivatedReactionRateI.H