OpenFOAM: JanevReactionRate Class Reference
JanevReactionRate Class Reference
Janev, Langer, Evans and Post reaction rate.
Public Member Functions
JanevReactionRate (const scalar A, const scalar beta, const scalar Ta, const FixedList< scalar, nb_ > b)
Construct from components.
JanevReactionRate (const speciesTable &species, Istream &is)
Construct from Istream.
JanevReactionRate (const speciesTable &species, const dictionary &dict)
Construct from dictionary.
scalar operator() (const scalar p, const scalar T, const scalarField &c) const
void write (Ostream &os) const
Write to stream.
Static Public Member Functions
static word type ()
Return the type name.
Friends
Ostream & operator<< (Ostream &, const JanevReactionRate &)
Detailed Description
Janev, Langer, Evans and Post reaction rate.
Source files
JanevReactionRate.H
JanevReactionRateI.H
Definition at line 57 of file JanevReactionRate.H.
Constructor & Destructor Documentation
JanevReactionRate() [1/3]
JanevReactionRate (const scalar A, const scalar beta, const scalar Ta, const FixedList< scalar, nb_ > b) inline
Construct from components.
Definition at line 29 of file JanevReactionRateI.H.
Referenced by JanevReactionRate::JanevReactionRate().
JanevReactionRate() [2/3]
JanevReactionRate (const speciesTable & species, Istream & is) inline
Construct from Istream.
Definition at line 44 of file JanevReactionRateI.H.
References JanevReactionRate::JanevReactionRate(), and Istream::readEnd().
JanevReactionRate() [3/3]
JanevReactionRate (const speciesTable & species, const dictionary & dict) inline
Construct from dictionary.
Definition at line 59 of file JanevReactionRateI.H.
Member Function Documentation
type()
static word type () inline static
Return the type name.
Definition at line 100 of file JanevReactionRate.H.
References Foam::constant::universal::c, p, Foam::T(), and JanevReactionRate::write().
operator()()
Foam::scalar operator() (const scalar p, const scalar T, const scalarField & c) const inline
Definition at line 74 of file JanevReactionRateI.H.
References Foam::exp(), Foam::log(), Foam::mag(), n, Foam::pow(), and T.
write()
void write (Ostream & os) const inline
Write to stream.
Definition at line 107 of file JanevReactionRateI.H.
References Foam::nl, and Ostream::writeKeyword().
Referenced by JanevReactionRate::type().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const JanevReactionRate &) friend
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/reaction/reactionRate/JanevReactionRate/JanevReactionRate.H
src/thermophysicalModels/specie/reaction/reactionRate/JanevReactionRate/JanevReactionRateI.H