OpenFOAM: rhoConst< Specie > Class Template Reference
rhoConst< Specie > Class Template Reference
RhoConst (rho = const) of state.
Public Member Functions
rhoConst (const Specie &sp, const scalar rho)
Construct from components.
rhoConst (Istream &)
Construct from Istream.
rhoConst (const dictionary &dict)
Construct from dictionary.
rhoConst (const word &name, const rhoConst &)
Construct as named copy.
autoPtr< rhoConst > clone () const
Construct and return a clone.
scalar rho (scalar p, scalar T) const
Return density [kg/m^3].
scalar h (const scalar p, const scalar T) const
Return enthalpy departure [J/kmol].
scalar cp (scalar p, scalar T) const
Return cp departure [J/(kmol K].
scalar s (const scalar p, const scalar T) const
Return entropy [J/(kmol K)].
scalar psi (scalar p, scalar T) const
Return compressibility rho/p [s^2/m^2].
scalar Z (scalar p, scalar T) const
Return compression factor [].
scalar cpMcv (scalar p, scalar T) const
Return (cp - cv) [J/(kmol K].
void write (Ostream &os) const
Write to Ostream.
void operator+= (const rhoConst &)
void operator-= (const rhoConst &)
void operator*= (const scalar)
Static Public Member Functions
static autoPtr< rhoConst > New (Istream &is)
static word typeName ()
Return the instantiated type name.
Static Public Attributes
static const bool incompressible = true
Is the equation of state is incompressible i.e. rho != f(p)
static const bool isochoric = true
Is the equation of state is isochoric i.e. rho = const.
Friends
rhoConst operator+ (const rhoConst &, const rhoConst &)
rhoConst operator- (const rhoConst &, const rhoConst &)
rhoConst operator* (const scalar s, const rhoConst &)
rhoConst operator== (const rhoConst &, const rhoConst &)
Ostream & operator (Ostream &, const rhoConst &)
Detailed Description
template<class Specie>
class Foam::rhoConst< Specie >
RhoConst (rho = const) of state.
Source files
rhoConst.H
rhoConstI.H
rhoConst.C
Definition at line 47 of file rhoConst.H.
Constructor & Destructor Documentation
rhoConst() [1/4]
rhoConst (const Specie & sp, const scalar rho) inline
Construct from components.
Definition at line 32 of file rhoConstI.H.
References Foam::name().
rhoConst() [2/4]
rhoConst (Istream & is)
Construct from Istream.
Definition at line 32 of file rhoConst.C.
References IOstream::check().
rhoConst() [3/4]
rhoConst (const dictionary & dict)
Construct from dictionary.
Definition at line 42 of file rhoConst.C.
rhoConst() [4/4]
rhoConst (const word & name, const rhoConst< Specie > &) inline
Construct as named copy.
Member Function Documentation
clone()
Foam::autoPtr< Foam::rhoConst< Specie > > clone () const inline
Construct and return a clone.
Definition at line 58 of file rhoConstI.H.
New()
Foam::autoPtr< Foam::rhoConst< Specie > > New (Istream & is) inline static
Definition at line 66 of file rhoConstI.H.
typeName()
static word typeName () inline static
Return the instantiated type name.
Definition at line 126 of file rhoConst.H.
rho()
Foam::scalar rho (scalar p, scalar T) const inline
Return density [kg/m^3].
Definition at line 75 of file rhoConstI.H.
h()
Foam::scalar h (const scalar p, const scalar T) const inline
Return enthalpy departure [J/kmol].
Definition at line 82 of file rhoConstI.H.
cp()
Foam::scalar cp (scalar p, scalar T) const inline
Return cp departure [J/(kmol K].
Definition at line 89 of file rhoConstI.H.
s()
Foam::scalar s (const scalar p, const scalar T) const inline
Return entropy [J/(kmol K)].
Definition at line 96 of file rhoConstI.H.
psi()
Foam::scalar psi (scalar p, scalar T) const inline
Return compressibility rho/p [s^2/m^2].
Definition at line 103 of file rhoConstI.H.
Z()
Foam::scalar Z (scalar p, scalar T) const inline
Return compression factor [].
Definition at line 110 of file rhoConstI.H.
cpMcv()
Foam::scalar cpMcv (scalar p, scalar T) const inline
Return (cp - cv) [J/(kmol K].
Definition at line 117 of file rhoConstI.H.
write()
void write (Ostream & os) const
Write to Ostream.
Definition at line 52 of file rhoConst.C.
References dictionary::add(), dict, dictionaryName::dictName(), Foam::indent(), token::SPACE, and write().
operator+=()
void operator+= (const rhoConst< Specie > &) inline
Definition at line 126 of file rhoConstI.H.
operator-=()
void operator-= (const rhoConst< Specie > &) inline
Definition at line 140 of file rhoConstI.H.
operator*=()
void operator*= (const scalar s) inline
Definition at line 154 of file rhoConstI.H.
References s().
Friends And Related Function Documentation
operator+
rhoConst operator+ (const rhoConst< Specie > & , const rhoConst< Specie > &) friend
operator-
rhoConst operator- (const rhoConst< Specie > & , const rhoConst< Specie > &) friend
operator*
rhoConst operator* (const scalar s, const rhoConst< Specie > &) friend
operator==
rhoConst operator== (const rhoConst< Specie > & , const rhoConst< Specie > &) friend
operator
Ostream& operator (Ostream & , const rhoConst< Specie > &) friend
Member Data Documentation
incompressible
const bool incompressible = true static
Is the equation of state is incompressible i.e. rho != f(p)
Definition at line 135 of file rhoConst.H.
isochoric
const bool isochoric = true static
Is the equation of state is isochoric i.e. rho = const.
Definition at line 138 of file rhoConst.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/equationOfState/rhoConst/rhoConst.H
src/thermophysicalModels/specie/equationOfState/rhoConst/rhoConst.C
src/thermophysicalModels/specie/equationOfState/rhoConst/rhoConstI.H