OpenFOAM: NonEquilibriumReversibleReaction< ReactionType, ReactionThermo, ReactionRate > Class Template Reference
NonEquilibriumReversibleReaction< ReactionType, ReactionThermo, ReactionRate > Class Template Reference
Simple extension of Reaction to handle reversible reactions using equilibrium thermodynamics.
Public Member Functions
TypeName ("nonEquilibriumReversible")
Runtime type information.
NonEquilibriumReversibleReaction (const ReactionType< ReactionThermo > &reaction, const ReactionRate &forwardReactionRate, const ReactionRate &reverseReactionRate)
Construct from components.
NonEquilibriumReversibleReaction (const NonEquilibriumReversibleReaction< ReactionType, ReactionThermo, ReactionRate > &, const speciesTable &species)
Construct as copy given new speciesTable.
NonEquilibriumReversibleReaction (const speciesTable &species, const HashPtrTable< ReactionThermo > &thermoDatabase, Istream &is)
Construct from Istream.
NonEquilibriumReversibleReaction (const speciesTable &species, const HashPtrTable< ReactionThermo > &thermoDatabase, const dictionary &dict)
Construct from dictionary.
virtual autoPtr< ReactionType< ReactionThermo > > clone () const
Construct and return a clone.
virtual autoPtr< ReactionType< ReactionThermo > > clone (const speciesTable &species) const
Construct and return a clone with new speciesTable.
virtual ~NonEquilibriumReversibleReaction ()
Destructor.
virtual scalar kf (const scalar p, const scalar T, const scalarField &c) const
Forward rate constant.
virtual scalar kr (const scalar kfwd, const scalar p, const scalar T, const scalarField &c) const
Reverse rate constant from the given formard rate constant.
virtual scalar kr (const scalar p, const scalar T, const scalarField &c) const
Reverse rate constant.
virtual void write (Ostream &) const
Write.
Detailed Description
template<template< class > class ReactionType, class ReactionThermo, class ReactionRate>
class Foam::NonEquilibriumReversibleReaction< ReactionType, ReactionThermo, ReactionRate >
Simple extension of Reaction to handle reversible reactions using equilibrium thermodynamics.
Source files
NonEquilibriumReversibleReaction.H
NonEquilibriumReversibleReaction.C
Definition at line 55 of file NonEquilibriumReversibleReaction.H.
Constructor & Destructor Documentation
NonEquilibriumReversibleReaction() [1/4]
NonEquilibriumReversibleReaction (const ReactionType< ReactionThermo > & reaction, const ReactionRate & forwardReactionRate, const ReactionRate & reverseReactionRate)
Construct from components.
Definition at line 43 of file NonEquilibriumReversibleReaction.C.
NonEquilibriumReversibleReaction() [2/4]
NonEquilibriumReversibleReaction (const NonEquilibriumReversibleReaction< ReactionType, ReactionThermo, ReactionRate > & nerr, const speciesTable & species)
Construct as copy given new speciesTable.
Definition at line 119 of file NonEquilibriumReversibleReaction.C.
NonEquilibriumReversibleReaction() [3/4]
NonEquilibriumReversibleReaction (const speciesTable & species, const HashPtrTable< ReactionThermo > & thermoDatabase, Istream & is)
Construct from Istream.
Definition at line 69 of file NonEquilibriumReversibleReaction.C.
NonEquilibriumReversibleReaction() [4/4]
NonEquilibriumReversibleReaction (const speciesTable & species, const HashPtrTable< ReactionThermo > & thermoDatabase, const dictionary & dict)
Construct from dictionary.
Definition at line 94 of file NonEquilibriumReversibleReaction.C.
~NonEquilibriumReversibleReaction()
virtual ~NonEquilibriumReversibleReaction () inline virtual
Destructor.
Definition at line 141 of file NonEquilibriumReversibleReaction.H.
References Foam::constant::universal::c, NonEquilibriumReversibleReaction< ReactionType, ReactionThermo, ReactionRate >::kf(), NonEquilibriumReversibleReaction< ReactionType, ReactionThermo, ReactionRate >::kr(), p, Foam::T(), and NonEquilibriumReversibleReaction< ReactionType, ReactionThermo, ReactionRate >::write().
Member Function Documentation
TypeName()
TypeName ("nonEquilibriumReversible")
Runtime type information.
clone() [1/2]
virtual autoPtr<ReactionType<ReactionThermo> > clone () const inline virtual
Construct and return a clone.
Definition at line 116 of file NonEquilibriumReversibleReaction.H.
clone() [2/2]
virtual autoPtr<ReactionType<ReactionThermo> > clone (const speciesTable & species) const inline virtual
Construct and return a clone with new speciesTable.
Definition at line 127 of file NonEquilibriumReversibleReaction.H.
kf()
Foam::scalar kf (const scalar p, const scalar T, const scalarField & c) const virtual
Forward rate constant.
Definition at line 150 of file NonEquilibriumReversibleReaction.C.
Referenced by NonEquilibriumReversibleReaction< ReactionType, ReactionThermo, ReactionRate >::~NonEquilibriumReversibleReaction().
kr() [1/2]
Foam::scalar kr (const scalar kfwd, const scalar p, const scalar T, const scalarField & c) const virtual
Reverse rate constant from the given formard rate constant.
Definition at line 173 of file NonEquilibriumReversibleReaction.C.
Referenced by NonEquilibriumReversibleReaction< ReactionType, ReactionThermo, ReactionRate >::~NonEquilibriumReversibleReaction().
kr() [2/2]
Foam::scalar kr (const scalar p, const scalar T, const scalarField & c) const virtual
Reverse rate constant.
Note this evaluates the forward rate constant and divides by the equilibrium constant
Definition at line 197 of file NonEquilibriumReversibleReaction.C.
References write().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 219 of file NonEquilibriumReversibleReaction.C.
References Foam::decrIndent(), Foam::incrIndent(), Foam::indent(), Foam::nl, write(), and Ostream::write().
Referenced by NonEquilibriumReversibleReaction< ReactionType, ReactionThermo, ReactionRate >::~NonEquilibriumReversibleReaction().
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/reaction/Reactions/NonEquilibriumReversibleReaction/NonEquilibriumReversibleReaction.H
src/thermophysicalModels/specie/reaction/Reactions/NonEquilibriumReversibleReaction/NonEquilibriumReversibleReaction.C