OpenFOAM: FallOffReactionRate< ReactionRate, FallOffFunction > Class Template Reference
FallOffReactionRate< ReactionRate, FallOffFunction > Class Template Reference
General class for handling unimolecular/recombination fall-off reactions.
Public Member Functions
FallOffReactionRate (const ReactionRate &k0, const ReactionRate &kInf, const FallOffFunction &F, const thirdBodyEfficiencies &tbes)
Construct from components.
FallOffReactionRate (const speciesTable &species, Istream &is)
Construct from Istream.
FallOffReactionRate (const speciesTable &species, const dictionary &dict)
Construct from dictionary.
scalar operator() (const scalar p, const scalar T, const scalarField &c) const
void write (Ostream &os) const
Write to stream.
Static Public Member Functions
static word type ()
Return the type name.
Friends
Ostream & operator (Ostream &, const FallOffReactionRate< ReactionRate, FallOffFunction > &)
Detailed Description
template<class ReactionRate, class FallOffFunction>
class Foam::FallOffReactionRate< ReactionRate, FallOffFunction >
General class for handling unimolecular/recombination fall-off reactions.
Source files
FallOffReactionRate.H
FallOffReactionRateI.H
Definition at line 47 of file FallOffReactionRate.H.
Constructor & Destructor Documentation
FallOffReactionRate() [1/3]
FallOffReactionRate (const ReactionRate & k0, const ReactionRate & kInf, const FallOffFunction & F, const thirdBodyEfficiencies & tbes) inline
Construct from components.
Definition at line 31 of file FallOffReactionRateI.H.
Referenced by FallOffReactionRate< ReactionRate, FallOffFunction >::FallOffReactionRate().
FallOffReactionRate() [2/3]
FallOffReactionRate (const speciesTable & species, Istream & is) inline
Construct from Istream.
Definition at line 48 of file FallOffReactionRateI.H.
References FallOffReactionRate< ReactionRate, FallOffFunction >::FallOffReactionRate(), and Istream::readEnd().
FallOffReactionRate() [3/3]
FallOffReactionRate (const speciesTable & species, const dictionary & dict) inline
Construct from dictionary.
Definition at line 65 of file FallOffReactionRateI.H.
References FallOffReactionRate< ReactionRate, FallOffFunction >::operator.
Member Function Documentation
type()
static word type () inline static
Return the type name.
Definition at line 103 of file FallOffReactionRate.H.
References Foam::constant::universal::c, FallOffReactionRate< ReactionRate, FallOffFunction >::operator, p, Foam::T(), Foam::type(), and FallOffReactionRate< ReactionRate, FallOffFunction >::write().
operator()()
Foam::scalar operator() (const scalar p, const scalar T, const scalarField & c) const inline
Definition at line 82 of file FallOffReactionRateI.H.
References Foam::constant::universal::c, Pr(), and FallOffReactionRate< ReactionRate, FallOffFunction >::write().
write()
void write (Ostream & os) const inline
Write to stream.
Definition at line 99 of file FallOffReactionRateI.H.
References Foam::decrIndent(), Foam::incrIndent(), Foam::indent(), Foam::nl, and Ostream::write().
Referenced by FallOffReactionRate< ReactionRate, FallOffFunction >::operator()(), and FallOffReactionRate< ReactionRate, FallOffFunction >::type().
Friends And Related Function Documentation
operator
Ostream& operator (Ostream & , const FallOffReactionRate< ReactionRate, FallOffFunction > &) friend
Referenced by FallOffReactionRate< ReactionRate, FallOffFunction >::FallOffReactionRate(), and FallOffReactionRate< ReactionRate, FallOffFunction >::type().
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/reaction/reactionRate/FallOffReactionRate/FallOffReactionRate.H
src/thermophysicalModels/specie/reaction/reactionRate/FallOffReactionRate/FallOffReactionRateI.H