OpenFOAM: ReversibleReaction< ReactionType, ReactionThermo, ReactionRate > Class Template Reference
ReversibleReaction< ReactionType, ReactionThermo, ReactionRate > Class Template Reference
Simple extension of Reaction to handle reversible reactions using equilibrium thermodynamics.
Public Member Functions
TypeName ("reversible")
Runtime type information.
ReversibleReaction (const ReactionType< ReactionThermo > &reaction, const ReactionRate &k)
Construct from components.
ReversibleReaction (const ReversibleReaction< ReactionType, ReactionThermo, ReactionRate > &, const speciesTable &species)
Construct as copy given new speciesTable.
ReversibleReaction (const speciesTable &species, const HashPtrTable< ReactionThermo > &thermoDatabase, Istream &is)
Construct from Istream.
ReversibleReaction (const speciesTable &species, const HashPtrTable< ReactionThermo > &thermoDatabase, const dictionary &dict)
Construct from dictionary.
virtual autoPtr< ReactionType< ReactionThermo > > clone () const
Construct and return a clone.
virtual autoPtr< ReactionType< ReactionThermo > > clone (const speciesTable &species) const
Construct and return a clone with new speciesTable.
virtual ~ReversibleReaction ()
Destructor.
virtual scalar kf (const scalar p, const scalar T, const scalarField &c) const
Forward rate constant.
virtual scalar kr (const scalar kfwd, const scalar p, const scalar T, const scalarField &c) const
Reverse rate constant from the given formard rate constant.
virtual scalar kr (const scalar p, const scalar T, const scalarField &c) const
Reverse rate constant.
virtual void write (Ostream &) const
Write.
Detailed Description
template<template< class > class ReactionType, class ReactionThermo, class ReactionRate>
class Foam::ReversibleReaction< ReactionType, ReactionThermo, ReactionRate >
Simple extension of Reaction to handle reversible reactions using equilibrium thermodynamics.
Source files
ReversibleReaction.H
ReversibleReaction.C
Definition at line 55 of file ReversibleReaction.H.
Constructor & Destructor Documentation
ReversibleReaction() [1/4]
ReversibleReaction (const ReactionType< ReactionThermo > & reaction, const ReactionRate & k)
Construct from components.
Definition at line 38 of file ReversibleReaction.C.
Referenced by ReversibleReaction< ReactionType, ReactionThermo, ReactionRate >::ReversibleReaction().
ReversibleReaction() [2/4]
ReversibleReaction (const ReversibleReaction< ReactionType, ReactionThermo, ReactionRate > & rr, const speciesTable & species)
Construct as copy given new speciesTable.
Definition at line 94 of file ReversibleReaction.C.
ReversibleReaction() [3/4]
ReversibleReaction (const speciesTable & species, const HashPtrTable< ReactionThermo > & thermoDatabase, Istream & is)
Construct from Istream.
Definition at line 56 of file ReversibleReaction.C.
References ReversibleReaction< ReactionType, ReactionThermo, ReactionRate >::ReversibleReaction().
ReversibleReaction() [4/4]
ReversibleReaction (const speciesTable & species, const HashPtrTable< ReactionThermo > & thermoDatabase, const dictionary & dict)
Construct from dictionary.
Definition at line 75 of file ReversibleReaction.C.
References ReversibleReaction< ReactionType, ReactionThermo, ReactionRate >::ReversibleReaction().
~ReversibleReaction()
virtual ~ReversibleReaction () inline virtual
Destructor.
Definition at line 154 of file ReversibleReaction.H.
References Foam::constant::universal::c, ReversibleReaction< ReactionType, ReactionThermo, ReactionRate >::kf(), ReversibleReaction< ReactionType, ReactionThermo, ReactionRate >::kr(), p, Foam::T(), and ReversibleReaction< ReactionType, ReactionThermo, ReactionRate >::write().
Member Function Documentation
TypeName()
TypeName ("reversible")
Runtime type information.
clone() [1/2]
virtual autoPtr<ReactionType<ReactionThermo> > clone () const inline virtual
Construct and return a clone.
Definition at line 122 of file ReversibleReaction.H.
clone() [2/2]
virtual autoPtr<ReactionType<ReactionThermo> > clone (const speciesTable & species) const inline virtual
Construct and return a clone with new speciesTable.
Definition at line 137 of file ReversibleReaction.H.
kf()
Foam::scalar kf (const scalar p, const scalar T, const scalarField & c) const virtual
Forward rate constant.
Definition at line 118 of file ReversibleReaction.C.
Referenced by ReversibleReaction< ReactionType, ReactionThermo, ReactionRate >::~ReversibleReaction().
kr() [1/2]
Foam::scalar kr (const scalar kfwd, const scalar p, const scalar T, const scalarField & c) const virtual
Reverse rate constant from the given formard rate constant.
Definition at line 140 of file ReversibleReaction.C.
References Foam::mag().
Referenced by ReversibleReaction< ReactionType, ReactionThermo, ReactionRate >::~ReversibleReaction().
kr() [2/2]
Foam::scalar kr (const scalar p, const scalar T, const scalarField & c) const virtual
Reverse rate constant.
Note this evaluates the forward rate constant and divides by the equilibrium constant
Definition at line 172 of file ReversibleReaction.C.
References write().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 194 of file ReversibleReaction.C.
References write().
Referenced by ReversibleReaction< ReactionType, ReactionThermo, ReactionRate >::~ReversibleReaction().
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/reaction/Reactions/ReversibleReaction/ReversibleReaction.H
src/thermophysicalModels/specie/reaction/Reactions/ReversibleReaction/ReversibleReaction.C