OpenFOAM: PengRobinsonGas< Specie > Class Template Reference
PengRobinsonGas< Specie > Class Template Reference
PengRobinsonGas gas equation of state.
Public Member Functions
PengRobinsonGas (const Specie &sp, const scalar &Tc, const scalar &Vc, const scalar &Zc, const scalar &Pc, const scalar &omega)
Construct from components.
PengRobinsonGas (Istream &)
Construct from Istream.
PengRobinsonGas (const dictionary &dict)
Construct from dictionary.
PengRobinsonGas (const word &name, const PengRobinsonGas &)
Construct as named copy.
autoPtr< PengRobinsonGas > clone () const
Construct and return a clone.
scalar rho (scalar p, scalar T) const
Return density [kg/m^3].
scalar h (const scalar p, const scalar T) const
Return enthalpy departure [J/kmol].
scalar cp (scalar p, scalar T) const
Return cp departure [J/(kmol K].
scalar s (const scalar p, const scalar T) const
Return entropy [J/(kmol K)].
scalar psi (scalar p, scalar T) const
Return compressibility rho/p [s^2/m^2].
scalar Z (scalar p, scalar T) const
Return compression factor [-].
scalar cpMcv (scalar p, scalar T) const
Return (cp - cv) [J/(kmol K].
void write (Ostream &os) const
Write to Ostream.
void operator+= (const PengRobinsonGas &)
void operator-= (const PengRobinsonGas &)
void operator*= (const scalar)
Static Public Member Functions
static autoPtr< PengRobinsonGas > New (Istream &is)
static autoPtr< PengRobinsonGas > New (const dictionary &dict)
static word typeName ()
Return the instantiated type name.
Static Public Attributes
static const bool incompressible = false
Is the equation of state is incompressible i.e. rho != f(p)
static const bool isochoric = false
Is the equation of state is isochoric i.e. rho = const.
Friends
PengRobinsonGas operator+ (const PengRobinsonGas &, const PengRobinsonGas &)
PengRobinsonGas operator- (const PengRobinsonGas &, const PengRobinsonGas &)
PengRobinsonGas operator* (const scalar s, const PengRobinsonGas &)
PengRobinsonGas operator== (const PengRobinsonGas &, const PengRobinsonGas &)
Ostream & operator (Ostream &, const PengRobinsonGas &)
Detailed Description
template<class Specie>
class Foam::PengRobinsonGas< Specie >
PengRobinsonGas gas equation of state.
Source files
PengRobinsonGas.H
PengRobinsonGasI.H
PengRobinsonGas.C
Definition at line 47 of file PengRobinsonGas.H.
Constructor & Destructor Documentation
PengRobinsonGas() [1/4]
PengRobinsonGas (const Specie & sp, const scalar & Tc, const scalar & Vc, const scalar & Zc, const scalar & Pc, const scalar & omega) inline
Construct from components.
Definition at line 33 of file PengRobinsonGasI.H.
Referenced by PengRobinsonGas< Specie >::PengRobinsonGas().
PengRobinsonGas() [2/4]
PengRobinsonGas (Istream & is)
Construct from Istream.
Definition at line 32 of file PengRobinsonGas.C.
References IOstream::check(), and PengRobinsonGas< Specie >::PengRobinsonGas().
PengRobinsonGas() [3/4]
PengRobinsonGas (const dictionary & dict)
Construct from dictionary.
Definition at line 47 of file PengRobinsonGas.C.
References Foam::constant::thermodynamic::RR.
PengRobinsonGas() [4/4]
PengRobinsonGas (const word & name, const PengRobinsonGas< Specie > & pg) inline
Construct as named copy.
Definition at line 55 of file PengRobinsonGasI.H.
Member Function Documentation
clone()
Foam::autoPtr< Foam::PengRobinsonGas< Specie > > clone () const inline
Construct and return a clone.
Definition at line 71 of file PengRobinsonGasI.H.
References PengRobinsonGas< Specie >::New().
New() [1/2]
Foam::autoPtr< Foam::PengRobinsonGas< Specie > > New (Istream & is) inline static
Definition at line 83 of file PengRobinsonGasI.H.
Referenced by PengRobinsonGas< Specie >::clone().
New() [2/2]
Foam::autoPtr< Foam::PengRobinsonGas< Specie > > New (const dictionary & dict) inline static
Definition at line 94 of file PengRobinsonGasI.H.
References dict, and PengRobinsonGas< Specie >::rho().
typeName()
static word typeName () inline static
Return the instantiated type name.
Definition at line 153 of file PengRobinsonGas.H.
rho()
Foam::scalar rho (scalar p, scalar T) const inline
Return density [kg/m^3].
Definition at line 109 of file PengRobinsonGasI.H.
References R, and T.
Referenced by PengRobinsonGas< Specie >::New().
h()
Foam::scalar h (const scalar p, const scalar T) const inline
Return enthalpy departure [J/kmol].
Definition at line 120 of file PengRobinsonGasI.H.
References Foam::constant::atomic::alpha, Foam::constant::electromagnetic::kappa, Foam::log(), Pr(), Foam::constant::thermodynamic::RR, Foam::sqr(), and Foam::sqrt().
cp()
Foam::scalar cp (scalar p, scalar T) const inline
Return cp departure [J/(kmol K].
Definition at line 141 of file PengRobinsonGasI.H.
References Foam::constant::atomic::alpha, Foam::constant::physicoChemical::b, Foam::constant::electromagnetic::kappa, Foam::log(), M, N, Foam::pow3(), Foam::constant::thermodynamic::RR, PengRobinsonGas< Specie >::s(), Foam::sqr(), Foam::sqrt(), and T.
s()
Foam::scalar s (const scalar p, const scalar T) const inline
Return entropy [J/(kmol K)].
Definition at line 171 of file PengRobinsonGasI.H.
References Foam::constant::electromagnetic::kappa, Foam::log(), Pr(), PengRobinsonGas< Specie >::psi(), Foam::constant::standard::Pstd, Foam::constant::thermodynamic::RR, Foam::sqr(), and Foam::sqrt().
Referenced by PengRobinsonGas< Specie >::cp().
psi()
Foam::scalar psi (scalar p, scalar T) const inline
Return compressibility rho/p [s^2/m^2].
Definition at line 196 of file PengRobinsonGasI.H.
References R, T, and PengRobinsonGas< Specie >::Z().
Referenced by PengRobinsonGas< Specie >::s().
Z()
Foam::scalar Z (scalar p, scalar T) const inline
Return compression factor [-].
Definition at line 209 of file PengRobinsonGasI.H.
References Foam::constant::atomic::a0, Foam::acos(), Foam::constant::atomic::alpha, Foam::constant::physicoChemical::b, Foam::cos(), PengRobinsonGas< Specie >::cpMcv(), Foam::constant::electromagnetic::kappa, Foam::mag(), Foam::max(), Foam::constant::mathematical::pi(), Foam::pow(), Foam::pow3(), Foam::constant::thermodynamic::RR, Foam::sqr(), Foam::sqrt(), and T.
Referenced by PengRobinsonGas< Specie >::psi().
cpMcv()
Foam::scalar cpMcv (scalar p, scalar T) const inline
Return (cp - cv) [J/(kmol K].
Definition at line 269 of file PengRobinsonGasI.H.
References Foam::constant::atomic::alpha, Foam::constant::physicoChemical::b, Foam::constant::electromagnetic::kappa, M, N, Foam::constant::thermodynamic::RR, Foam::sqr(), Foam::sqrt(), and T.
Referenced by PengRobinsonGas< Specie >::Z().
write()
void write (Ostream & os) const
Write to Ostream.
Definition at line 66 of file PengRobinsonGas.C.
References token::SPACE, and write().
operator+=()
void operator+= (const PengRobinsonGas< Specie > &) inline
Definition at line 297 of file PengRobinsonGasI.H.
References Foam::constant::thermodynamic::RR.
operator-=()
void operator-= (const PengRobinsonGas< Specie > &) inline
Definition at line 317 of file PengRobinsonGasI.H.
References Foam::constant::thermodynamic::RR.
operator*=()
void operator*= (const scalar s) inline
Definition at line 337 of file PengRobinsonGasI.H.
References Foam::constant::thermodynamic::RR, and s().
Friends And Related Function Documentation
operator+
PengRobinsonGas operator+ (const PengRobinsonGas< Specie > & , const PengRobinsonGas< Specie > &) friend
operator-
PengRobinsonGas operator- (const PengRobinsonGas< Specie > & , const PengRobinsonGas< Specie > &) friend
operator*
PengRobinsonGas operator* (const scalar s, const PengRobinsonGas< Specie > &) friend
operator==
PengRobinsonGas operator== (const PengRobinsonGas< Specie > & , const PengRobinsonGas< Specie > &) friend
operator
Ostream& operator (Ostream & , const PengRobinsonGas< Specie > &) friend
Member Data Documentation
incompressible
const bool incompressible = false static
Is the equation of state is incompressible i.e. rho != f(p)
Definition at line 162 of file PengRobinsonGas.H.
isochoric
const bool isochoric = false static
Is the equation of state is isochoric i.e. rho = const.
Definition at line 165 of file PengRobinsonGas.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/equationOfState/PengRobinsonGas/PengRobinsonGas.H
src/thermophysicalModels/specie/equationOfState/PengRobinsonGas/PengRobinsonGas.C
src/thermophysicalModels/specie/equationOfState/PengRobinsonGas/PengRobinsonGasI.H