OpenFOAM: IrreversibleReaction< ReactionType, ReactionThermo, ReactionRate > Class Template Reference
IrreversibleReaction< ReactionType, ReactionThermo, ReactionRate > Class Template Reference
Simple extension of Reaction to handle reversible reactions using equilibrium thermodynamics.
Public Member Functions
TypeName ("irreversible")
Runtime type information.
IrreversibleReaction (const ReactionType< ReactionThermo > &reaction, const ReactionRate &reactionRate)
Construct from components.
IrreversibleReaction (const IrreversibleReaction< ReactionType, ReactionThermo, ReactionRate > &, const speciesTable &species)
Construct as copy given new speciesTable.
IrreversibleReaction (const speciesTable &species, const HashPtrTable< ReactionThermo > &thermoDatabase, Istream &is)
Construct from Istream.
IrreversibleReaction (const speciesTable &species, const HashPtrTable< ReactionThermo > &thermoDatabase, const dictionary &dict)
Construct from dictionary.
virtual autoPtr< Reaction< ReactionThermo > > clone () const
Construct and return a clone.
virtual autoPtr< Reaction< ReactionThermo > > clone (const speciesTable &species) const
Construct and return a clone with new speciesTable.
virtual ~IrreversibleReaction ()
Destructor.
virtual scalar kf (const scalar p, const scalar T, const scalarField &c) const
Forward rate constant.
virtual void write (Ostream &) const
Write.
Detailed Description
template<template< class > class ReactionType, class ReactionThermo, class ReactionRate>
class Foam::IrreversibleReaction< ReactionType, ReactionThermo, ReactionRate >
Simple extension of Reaction to handle reversible reactions using equilibrium thermodynamics.
Source files
IrreversibleReaction.H
IrreversibleReaction.C
Definition at line 55 of file IrreversibleReaction.H.
Constructor & Destructor Documentation
IrreversibleReaction() [1/4]
IrreversibleReaction (const ReactionType< ReactionThermo > & reaction, const ReactionRate & reactionRate)
Construct from components.
Definition at line 38 of file IrreversibleReaction.C.
Referenced by IrreversibleReaction< ReactionType, ReactionThermo, ReactionRate >::IrreversibleReaction().
IrreversibleReaction() [2/4]
IrreversibleReaction (const IrreversibleReaction< ReactionType, ReactionThermo, ReactionRate > & irr, const speciesTable & species)
Construct as copy given new speciesTable.
Definition at line 94 of file IrreversibleReaction.C.
IrreversibleReaction() [3/4]
IrreversibleReaction (const speciesTable & species, const HashPtrTable< ReactionThermo > & thermoDatabase, Istream & is)
Construct from Istream.
Definition at line 56 of file IrreversibleReaction.C.
References IrreversibleReaction< ReactionType, ReactionThermo, ReactionRate >::IrreversibleReaction().
IrreversibleReaction() [4/4]
IrreversibleReaction (const speciesTable & species, const HashPtrTable< ReactionThermo > & thermoDatabase, const dictionary & dict)
Construct from dictionary.
Definition at line 75 of file IrreversibleReaction.C.
References IrreversibleReaction< ReactionType, ReactionThermo, ReactionRate >::IrreversibleReaction().
~IrreversibleReaction()
virtual ~IrreversibleReaction () inline virtual
Destructor.
Definition at line 158 of file IrreversibleReaction.H.
References Foam::constant::universal::c, IrreversibleReaction< ReactionType, ReactionThermo, ReactionRate >::kf(), p, Foam::T(), and IrreversibleReaction< ReactionType, ReactionThermo, ReactionRate >::write().
Member Function Documentation
TypeName()
TypeName ("irreversible")
Runtime type information.
clone() [1/2]
virtual autoPtr<Reaction<ReactionThermo> > clone () const inline virtual
Construct and return a clone.
Definition at line 122 of file IrreversibleReaction.H.
clone() [2/2]
virtual autoPtr<Reaction<ReactionThermo> > clone (const speciesTable & species) const inline virtual
Construct and return a clone with new speciesTable.
Definition at line 137 of file IrreversibleReaction.H.
kf()
Foam::scalar kf (const scalar p, const scalar T, const scalarField & c) const virtual
Forward rate constant.
Definition at line 118 of file IrreversibleReaction.C.
References IrreversibleReaction< ReactionType, ReactionThermo, ReactionRate >::write().
Referenced by IrreversibleReaction< ReactionType, ReactionThermo, ReactionRate >::~IrreversibleReaction().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 136 of file IrreversibleReaction.C.
References write().
Referenced by IrreversibleReaction< ReactionType, ReactionThermo, ReactionRate >::kf(), and IrreversibleReaction< ReactionType, ReactionThermo, ReactionRate >::~IrreversibleReaction().
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/reaction/Reactions/IrreversibleReaction/IrreversibleReaction.H
src/thermophysicalModels/specie/reaction/Reactions/IrreversibleReaction/IrreversibleReaction.C