OpenFOAM: perfectGas< Specie > Class Template Reference
perfectGas< Specie > Class Template Reference
Perfect gas equation of state.
Public Member Functions
perfectGas (const Specie &sp)
Construct from components.
perfectGas (Istream &)
Construct from Istream.
perfectGas (const dictionary &dict)
Construct from dictionary.
perfectGas (const word &name, const perfectGas &)
Construct as named copy.
autoPtr< perfectGas > clone () const
Construct and return a clone.
scalar rho (scalar p, scalar T) const
Return density [kg/m^3].
scalar h (const scalar p, const scalar T) const
Return enthalpy departure [J/kmol].
scalar cp (scalar p, scalar T) const
Return cp departure [J/(kmol K].
scalar s (const scalar p, const scalar T) const
Return entropy [J/(kmol K)].
scalar psi (scalar p, scalar T) const
Return compressibility rho/p [s^2/m^2].
scalar Z (scalar p, scalar T) const
Return compression factor [].
scalar cpMcv (scalar p, scalar T) const
Return (cp - cv) [J/(kmol K].
void write (Ostream &os) const
Write to Ostream.
void operator+= (const perfectGas &)
void operator-= (const perfectGas &)
void operator*= (const scalar)
Static Public Member Functions
static autoPtr< perfectGas > New (Istream &is)
static autoPtr< perfectGas > New (const dictionary &dict)
static word typeName ()
Return the instantiated type name.
Static Public Attributes
static const bool incompressible = false
Is the equation of state is incompressible i.e. rho != f(p)
static const bool isochoric = false
Is the equation of state is isochoric i.e. rho = const.
Friends
perfectGas operator+ (const perfectGas &, const perfectGas &)
perfectGas operator- (const perfectGas &, const perfectGas &)
perfectGas operator* (const scalar s, const perfectGas &)
perfectGas operator== (const perfectGas &, const perfectGas &)
Ostream & operator (Ostream &, const perfectGas &)
Detailed Description
template<class Specie>
class Foam::perfectGas< Specie >
Perfect gas equation of state.
Source files
perfectGas.H
perfectGasI.H
perfectGas.C
Definition at line 47 of file perfectGas.H.
Constructor & Destructor Documentation
perfectGas() [1/4]
perfectGas (const Specie & sp) inline
Construct from components.
Definition at line 31 of file perfectGasI.H.
References Foam::name().
perfectGas() [2/4]
perfectGas (Istream & is)
Construct from Istream.
Definition at line 32 of file perfectGas.C.
References IOstream::check().
perfectGas() [3/4]
perfectGas (const dictionary & dict)
Construct from dictionary.
Definition at line 41 of file perfectGas.C.
perfectGas() [4/4]
perfectGas (const word & name, const perfectGas< Specie > &) inline
Construct as named copy.
Member Function Documentation
clone()
Foam::autoPtr< Foam::perfectGas< Specie > > clone () const inline
Construct and return a clone.
Definition at line 52 of file perfectGasI.H.
New() [1/2]
Foam::autoPtr< Foam::perfectGas< Specie > > New (Istream & is) inline static
Definition at line 60 of file perfectGasI.H.
New() [2/2]
Foam::autoPtr< Foam::perfectGas< Specie > > New (const dictionary & dict) inline static
Definition at line 68 of file perfectGasI.H.
References dict.
typeName()
static word typeName () inline static
Return the instantiated type name.
Definition at line 124 of file perfectGas.H.
rho()
Foam::scalar rho (scalar p, scalar T) const inline
Return density [kg/m^3].
Definition at line 79 of file perfectGasI.H.
References R, and Foam::T().
h()
Foam::scalar h (const scalar p, const scalar T) const inline
Return enthalpy departure [J/kmol].
Definition at line 86 of file perfectGasI.H.
cp()
Foam::scalar cp (scalar p, scalar T) const inline
Return cp departure [J/(kmol K].
Definition at line 93 of file perfectGasI.H.
s()
Foam::scalar s (const scalar p, const scalar T) const inline
Return entropy [J/(kmol K)].
Definition at line 100 of file perfectGasI.H.
References Foam::log(), Foam::constant::standard::Pstd, and Foam::constant::thermodynamic::RR.
Referenced by perfectGas< Specie >::operator*=().
psi()
Foam::scalar psi (scalar p, scalar T) const inline
Return compressibility rho/p [s^2/m^2].
Definition at line 107 of file perfectGasI.H.
References R, and Foam::T().
Z()
Foam::scalar Z (scalar p, scalar T) const inline
Return compression factor [].
Definition at line 114 of file perfectGasI.H.
cpMcv()
Foam::scalar cpMcv (scalar p, scalar T) const inline
Return (cp - cv) [J/(kmol K].
Definition at line 121 of file perfectGasI.H.
References Foam::constant::thermodynamic::RR.
write()
void write (Ostream & os) const
Write to Ostream.
Definition at line 50 of file perfectGas.C.
References IOstream::check(), and write().
operator+=()
void operator+= (const perfectGas< Specie > &) inline
Definition at line 130 of file perfectGasI.H.
operator-=()
void operator-= (const perfectGas< Specie > &) inline
Definition at line 137 of file perfectGasI.H.
operator*=()
void operator*= (const scalar s) inline
Definition at line 144 of file perfectGasI.H.
References perfectGas< Specie >::s().
Friends And Related Function Documentation
operator+
perfectGas operator+ (const perfectGas< Specie > & , const perfectGas< Specie > &) friend
operator-
perfectGas operator- (const perfectGas< Specie > & , const perfectGas< Specie > &) friend
operator*
perfectGas operator* (const scalar s, const perfectGas< Specie > &) friend
operator==
perfectGas operator== (const perfectGas< Specie > & , const perfectGas< Specie > &) friend
operator
Ostream& operator (Ostream & , const perfectGas< Specie > &) friend
Member Data Documentation
incompressible
const bool incompressible = false static
Is the equation of state is incompressible i.e. rho != f(p)
Definition at line 133 of file perfectGas.H.
isochoric
const bool isochoric = false static
Is the equation of state is isochoric i.e. rho = const.
Definition at line 136 of file perfectGas.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/equationOfState/perfectGas/perfectGas.H
src/thermophysicalModels/specie/equationOfState/perfectGas/perfectGas.C
src/thermophysicalModels/specie/equationOfState/perfectGas/perfectGasI.H