OpenFOAM: perfectFluid< Specie > Class Template Reference
perfectFluid< Specie > Class Template Reference
Perfect gas equation of state.
Public Member Functions
perfectFluid (const Specie &sp, const scalar R, const scalar rho0)
Construct from components.
perfectFluid (Istream &)
Construct from Istream.
perfectFluid (const dictionary &dict)
Construct from dictionary.
perfectFluid (const word &name, const perfectFluid &)
Construct as named copy.
autoPtr< perfectFluid > clone () const
Construct and return a clone.
scalar R () const
Return fluid constant [J/(kg K)].
scalar rho (scalar p, scalar T) const
Return density [kg/m^3].
scalar h (const scalar p, const scalar T) const
Return enthalpy departure [J/kmol].
scalar cp (scalar p, scalar T) const
Return cp departure [J/(kmol K].
scalar s (const scalar p, const scalar T) const
Return entropy [J/(kmol K)].
scalar psi (scalar p, scalar T) const
Return compressibility rho/p [s^2/m^2].
scalar Z (scalar p, scalar T) const
Return compression factor [].
scalar cpMcv (scalar p, scalar T) const
Return (cp - cv) [J/(kmol K].
void write (Ostream &os) const
Write to Ostream.
void operator+= (const perfectFluid &)
void operator-= (const perfectFluid &)
void operator*= (const scalar)
Static Public Member Functions
static autoPtr< perfectFluid > New (Istream &is)
static autoPtr< perfectFluid > New (const dictionary &dict)
static word typeName ()
Return the instantiated type name.
Static Public Attributes
static const bool incompressible = false
Is the equation of state is incompressible i.e. rho != f(p)
static const bool isochoric = false
Is the equation of state is isochoric i.e. rho = const.
Friends
perfectFluid operator+ (const perfectFluid &, const perfectFluid &)
perfectFluid operator- (const perfectFluid &, const perfectFluid &)
perfectFluid operator* (const scalar s, const perfectFluid &)
perfectFluid operator== (const perfectFluid &, const perfectFluid &)
Ostream & operator (Ostream &, const perfectFluid &)
Detailed Description
template<class Specie>
class Foam::perfectFluid< Specie >
Perfect gas equation of state.
Source files
perfectFluid.H
perfectFluidI.H
perfectFluid.C
Definition at line 47 of file perfectFluid.H.
Constructor & Destructor Documentation
perfectFluid() [1/4]
perfectFluid (const Specie & sp, const scalar R, const scalar rho0) inline
Construct from components.
Definition at line 33 of file perfectFluidI.H.
References Foam::name().
perfectFluid() [2/4]
perfectFluid (Istream & is)
Construct from Istream.
Definition at line 32 of file perfectFluid.C.
References IOstream::check().
perfectFluid() [3/4]
perfectFluid (const dictionary & dict)
Construct from dictionary.
Definition at line 43 of file perfectFluid.C.
perfectFluid() [4/4]
perfectFluid (const word & name, const perfectFluid< Specie > &) inline
Construct as named copy.
Member Function Documentation
clone()
Foam::autoPtr< Foam::perfectFluid< Specie > > clone () const inline
Construct and return a clone.
Definition at line 62 of file perfectFluidI.H.
New() [1/2]
Foam::autoPtr< Foam::perfectFluid< Specie > > New (Istream & is) inline static
Definition at line 70 of file perfectFluidI.H.
New() [2/2]
Foam::autoPtr< Foam::perfectFluid< Specie > > New (const dictionary & dict) inline static
Definition at line 79 of file perfectFluidI.H.
References dict.
typeName()
static word typeName () inline static
Return the instantiated type name.
Definition at line 137 of file perfectFluid.H.
R()
Foam::scalar R () const inline
Return fluid constant [J/(kg K)].
Definition at line 90 of file perfectFluidI.H.
rho()
Foam::scalar rho (scalar p, scalar T) const inline
Return density [kg/m^3].
Definition at line 97 of file perfectFluidI.H.
References R, and T.
h()
Foam::scalar h (const scalar p, const scalar T) const inline
Return enthalpy departure [J/kmol].
Definition at line 104 of file perfectFluidI.H.
cp()
Foam::scalar cp (scalar p, scalar T) const inline
Return cp departure [J/(kmol K].
Definition at line 111 of file perfectFluidI.H.
s()
Foam::scalar s (const scalar p, const scalar T) const inline
Return entropy [J/(kmol K)].
Definition at line 118 of file perfectFluidI.H.
References Foam::log(), Foam::constant::standard::Pstd, and Foam::constant::thermodynamic::RR.
psi()
Foam::scalar psi (scalar p, scalar T) const inline
Return compressibility rho/p [s^2/m^2].
Definition at line 125 of file perfectFluidI.H.
References R, and T.
Z()
Foam::scalar Z (scalar p, scalar T) const inline
Return compression factor [].
Definition at line 132 of file perfectFluidI.H.
cpMcv()
Foam::scalar cpMcv (scalar p, scalar T) const inline
Return (cp - cv) [J/(kmol K].
Definition at line 139 of file perfectFluidI.H.
write()
void write (Ostream & os) const
Write to Ostream.
Definition at line 54 of file perfectFluid.C.
References dictionary::add(), dict, dictionaryName::dictName(), Foam::indent(), token::SPACE, and write().
operator+=()
void operator+= (const perfectFluid< Specie > &) inline
Definition at line 149 of file perfectFluidI.H.
operator-=()
void operator-= (const perfectFluid< Specie > &) inline
Definition at line 167 of file perfectFluidI.H.
operator*=()
void operator*= (const scalar s) inline
Definition at line 184 of file perfectFluidI.H.
References s().
Friends And Related Function Documentation
operator+
perfectFluid operator+ (const perfectFluid< Specie > & , const perfectFluid< Specie > &) friend
operator-
perfectFluid operator- (const perfectFluid< Specie > & , const perfectFluid< Specie > &) friend
operator*
perfectFluid operator* (const scalar s, const perfectFluid< Specie > &) friend
operator==
perfectFluid operator== (const perfectFluid< Specie > & , const perfectFluid< Specie > &) friend
operator
Ostream& operator (Ostream & , const perfectFluid< Specie > &) friend
Member Data Documentation
incompressible
const bool incompressible = false static
Is the equation of state is incompressible i.e. rho != f(p)
Definition at line 146 of file perfectFluid.H.
isochoric
const bool isochoric = false static
Is the equation of state is isochoric i.e. rho = const.
Definition at line 149 of file perfectFluid.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/equationOfState/perfectFluid/perfectFluid.H
src/thermophysicalModels/specie/equationOfState/perfectFluid/perfectFluid.C
src/thermophysicalModels/specie/equationOfState/perfectFluid/perfectFluidI.H