OpenFOAM: Reaction< ReactionThermo > Class Template Reference
Reaction< ReactionThermo > Class Template Reference
Simple extension of ReactionThermo to handle reaction kinetics in addition to the equilibrium thermodynamics already handled.
Classes
class iNew
Class used for the read-construction of PtrLists of reaction.
struct specieCoeffs
Class to hold the specie index and its coefficients in the.
Public Member Functions
TypeName ("Reaction")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, Reaction, Istream,(const speciesTable &species, const HashPtrTable< ReactionThermo > &thermoDatabase, Istream &is),(species, thermoDatabase, is))
declareRunTimeSelectionTable (autoPtr, Reaction, dictionary,(const speciesTable &species, const HashPtrTable< ReactionThermo > &thermoDatabase, const dictionary &dict),(species, thermoDatabase, dict))
Reaction (const speciesTable &species, const List< specieCoeffs > &lhs, const List< specieCoeffs > &rhs, const HashPtrTable< ReactionThermo > &thermoDatabase)
Construct from components.
Reaction (const Reaction< ReactionThermo > &, const speciesTable &species)
Construct as copy given new speciesTable.
Reaction (const speciesTable &species, const HashPtrTable< ReactionThermo > &thermoDatabase, Istream &is)
Construct from Istream.
Reaction (const speciesTable &species, const HashPtrTable< ReactionThermo > &thermoDatabase, const dictionary &dict)
Construct from dictionary.
virtual autoPtr< Reaction< ReactionThermo > > clone () const
Construct and return a clone.
virtual autoPtr< Reaction< ReactionThermo > > clone (const speciesTable &species) const
Construct and return a clone with new speciesTable.
virtual ~Reaction ()
Destructor.
word & name ()
const word & name () const
const List< specieCoeffs > & lhs () const
const List< specieCoeffs > & rhs () const
virtual const List< specieCoeffs > & grhs () const
virtual const List< specieCoeffs > & glhs () const
const speciesTable & species () const
virtual const speciesTable & gasSpecies () const
void setLRhs (Istream &, const speciesTable &, List< specieCoeffs > &lhs, List< specieCoeffs > &rhs)
Construct the left- and right-hand-side reaction coefficients.
virtual scalar kf (const scalar p, const scalar T, const scalarField &c) const
Forward rate constant.
virtual scalar kr (const scalar kfwd, const scalar p, const scalar T, const scalarField &c) const
Reverse rate constant from the given forward rate constant.
virtual scalar kr (const scalar p, const scalar T, const scalarField &c) const
Reverse rate constant.
virtual void write (Ostream &) const
Write.
Static Public Member Functions
static autoPtr< Reaction< ReactionThermo > > New (const speciesTable &species, const HashPtrTable< ReactionThermo > &thermoDatabase, Istream &is)
Return a pointer to new patchField created on freestore from input.
static autoPtr< Reaction< ReactionThermo > > New (const speciesTable &species, const HashPtrTable< ReactionThermo > &thermoDatabase, const dictionary &dict)
Return a pointer to new patchField created on freestore from dict.
Static Public Attributes
static label nUnNamedReactions = 0
Number of un-named reactions.
Protected Member Functions
void reactionStrLeft (OStringStream &reaction) const
Return string representation of the left of the reaction.
void reactionStrRight (OStringStream &reaction) const
Return string representation of the right of the reaction.
Friends
Ostream & operator (Ostream &, const Reaction< ReactionThermo > &)
Detailed Description
template<class ReactionThermo>
class Foam::Reaction< ReactionThermo >
Simple extension of ReactionThermo to handle reaction kinetics in addition to the equilibrium thermodynamics already handled.
Source files
Reaction.H
ReactionI.H
Reaction.C
Definition at line 53 of file Reaction.H.
Constructor & Destructor Documentation
Reaction() [1/4]
Reaction (const speciesTable & species, const List< specieCoeffs > & lhs, const List< specieCoeffs > & rhs, const HashPtrTable< ReactionThermo > & thermoDatabase)
Construct from components.
Definition at line 145 of file Reaction.C.
Referenced by Reaction< ReactionThermo >::iNew::operator()(), Reaction< ReactionThermo >::Reaction(), Reaction< ReactionThermo >::reactionStrRight(), and Reaction< ReactionThermo >::setLRhs().
Reaction() [2/4]
Reaction (const Reaction< ReactionThermo > & r, const speciesTable & species)
Construct as copy given new speciesTable.
Definition at line 164 of file Reaction.C.
References Reaction< ReactionThermo >::specieCoeffs::specieCoeffs().
Reaction() [3/4]
Reaction (const speciesTable & species, const HashPtrTable< ReactionThermo > & thermoDatabase, Istream & is)
Construct from Istream.
Definition at line 317 of file Reaction.C.
References Reaction< ReactionThermo >::Reaction().
Reaction() [4/4]
Reaction (const speciesTable & species, const HashPtrTable< ReactionThermo > & thermoDatabase, const dictionary & dict)
Construct from dictionary.
Definition at line 334 of file Reaction.C.
References dictionary::lookup(), and Reaction< ReactionThermo >::New().
~Reaction()
virtual ~Reaction () inline virtual
Destructor.
Definition at line 295 of file Reaction.H.
References Foam::constant::universal::c, Reaction< ReactionThermo >::gasSpecies(), Reaction< ReactionThermo >::glhs(), Reaction< ReactionThermo >::grhs(), Reaction< ReactionThermo >::kf(), Reaction< ReactionThermo >::kr(), Reaction< ReactionThermo >::lhs(), Reaction< ReactionThermo >::name(), p, Reaction< ReactionThermo >::rhs(), Reaction< ReactionThermo >::setLRhs(), Reaction< ReactionThermo >::species(), Foam::T(), and Reaction< ReactionThermo >::write().
Member Function Documentation
reactionStrLeft()
void reactionStrLeft (OStringStream & reaction) const protected
Return string representation of the left of the reaction.
Definition at line 38 of file Reaction.C.
References Foam::mag(), and Reaction< ReactionThermo >::reactionStrRight().
reactionStrRight()
void reactionStrRight (OStringStream & reaction) const protected
Return string representation of the right of the reaction.
Definition at line 63 of file Reaction.C.
References forAll, Foam::mag(), Reaction< ReactionThermo >::Reaction(), and OStringStream::str().
Referenced by Reaction< ReactionThermo >::reactionStrLeft().
TypeName()
TypeName ("Reaction< ReactionThermo >")
Runtime type information.
declareRunTimeSelectionTable() [1/2]
declareRunTimeSelectionTable (autoPtr , Reaction< ReactionThermo > , Istream , (const speciesTable &species, const HashPtrTable< ReactionThermo > &thermoDatabase, Istream &is) , (species, thermoDatabase, is))
declareRunTimeSelectionTable() [2/2]
declareRunTimeSelectionTable (autoPtr , Reaction< ReactionThermo > , dictionary , (const speciesTable &species, const HashPtrTable< ReactionThermo > &thermoDatabase, const dictionary &dict) , (species, thermoDatabase, dict))
clone() [1/2]
virtual autoPtr<Reaction<ReactionThermo> > clone () const inline virtual
Construct and return a clone.
Reimplemented in solidReaction< ReactionThermo >.
Definition at line 254 of file Reaction.H.
clone() [2/2]
virtual autoPtr<Reaction<ReactionThermo> > clone (const speciesTable & species) const inline virtual
Construct and return a clone with new speciesTable.
Reimplemented in solidReaction< ReactionThermo >.
Definition at line 264 of file Reaction.H.
References Reaction< ReactionThermo >::New(), and Reaction< ReactionThermo >::species().
New() [1/2]
Foam::autoPtr< Foam::Reaction< ReactionThermo > > New (const speciesTable & species, const HashPtrTable< ReactionThermo > & thermoDatabase, Istream & is) static
Return a pointer to new patchField created on freestore from input.
Definition at line 360 of file Reaction.C.
References IOstream::eof(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, and Foam::nl.
Referenced by Reaction< ReactionThermo >::clone(), Reaction< ReactionThermo >::iNew::operator()(), and Reaction< ReactionThermo >::Reaction().
New() [2/2]
Foam::autoPtr< Foam::Reaction< ReactionThermo > > New (const speciesTable & species, const HashPtrTable< ReactionThermo > & thermoDatabase, const dictionary & dict) static
Return a pointer to new patchField created on freestore from dict.
Definition at line 404 of file Reaction.C.
References dict, Foam::exit(), Foam::FatalError, FatalErrorInFunction, dictionary::lookup(), and Foam::nl.
name() [1/2]
word & name () inline
Definition at line 36 of file ReactionI.H.
Referenced by ReactionList< Foam::sutherlandTransport >::write(), and Reaction< ReactionThermo >::~Reaction().
name() [2/2]
const word & name () const inline
Definition at line 43 of file ReactionI.H.
lhs()
const List< typename Reaction< ReactionThermo >::specieCoeffs > & lhs () const inline
Definition at line 51 of file ReactionI.H.
Referenced by singleStepReactingMixture< ThermoType >::calculateqFuel(), singleStepReactingMixture< ThermoType >::fresCorrect(), TDACChemistryModel< CompType, ThermoType >::jacobian(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::jacobian(), chemistryModel< CompType, ThermoType >::jacobian(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::omega(), chemistryModel< CompType, ThermoType >::omega(), TDACChemistryModel< CompType, ThermoType >::omega(), Reaction< ReactionThermo >::iNew::operator()(), EFA< CompType, ThermoType >::reduceMechanism(), PFA< CompType, ThermoType >::reduceMechanism(), DRG< CompType, ThermoType >::reduceMechanism(), DAC< CompType, ThermoType >::reduceMechanism(), DRGEP< CompType, ThermoType >::reduceMechanism(), EulerImplicit< ChemistryModel >::updateRRInReactionI(), and Reaction< ReactionThermo >::~Reaction().
rhs()
const List< typename Reaction< ReactionThermo >::specieCoeffs > & rhs () const inline
Definition at line 59 of file ReactionI.H.
Referenced by singleStepReactingMixture< ThermoType >::calculateMaxProducts(), singleStepReactingMixture< ThermoType >::calculateqFuel(), singleStepReactingMixture< ThermoType >::fresCorrect(), TDACChemistryModel< CompType, ThermoType >::jacobian(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::jacobian(), chemistryModel< CompType, ThermoType >::jacobian(), mixtureFractionSoot< ThermoType >::mixtureFractionSoot(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::omega(), chemistryModel< CompType, ThermoType >::omega(), TDACChemistryModel< CompType, ThermoType >::omega(), Reaction< ReactionThermo >::iNew::operator()(), EFA< CompType, ThermoType >::reduceMechanism(), PFA< CompType, ThermoType >::reduceMechanism(), DRG< CompType, ThermoType >::reduceMechanism(), DAC< CompType, ThermoType >::reduceMechanism(), DRGEP< CompType, ThermoType >::reduceMechanism(), chemistryModel< CompType, ThermoType >::tc(), EulerImplicit< ChemistryModel >::updateRRInReactionI(), and Reaction< ReactionThermo >::~Reaction().
grhs()
const Foam::List< typename Foam::Reaction< ReactionThermo >::specieCoeffs > & grhs () const virtual
Reimplemented in solidReaction< ReactionThermo >.
Definition at line 506 of file Reaction.C.
References NotImplemented.
Referenced by pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::omega(), and Reaction< ReactionThermo >::~Reaction().
glhs()
const Foam::List< typename Foam::Reaction< ReactionThermo >::specieCoeffs > & glhs () const virtual
Reimplemented in solidReaction< ReactionThermo >.
Definition at line 497 of file Reaction.C.
References NotImplemented.
Referenced by Reaction< ReactionThermo >::~Reaction().
species()
const Foam::speciesTable & species () const
Definition at line 481 of file Reaction.C.
Referenced by solidReaction< ReactionThermo >::clone(), Reaction< ReactionThermo >::clone(), Reaction< ReactionThermo >::specieCoeffs::specieCoeffs(), and Reaction< ReactionThermo >::~Reaction().
gasSpecies()
const Foam::speciesTable & gasSpecies () const virtual
Reimplemented in solidReaction< ReactionThermo >.
Definition at line 488 of file Reaction.C.
References NotImplemented.
Referenced by Reaction< ReactionThermo >::~Reaction().
setLRhs()
void setLRhs (Istream & is, const speciesTable & species, List< specieCoeffs > & lhs, List< specieCoeffs > & rhs)
Construct the left- and right-hand-side reaction coefficients.
Definition at line 234 of file Reaction.C.
References DynamicList< T, SizeInc, SizeMult, SizeDiv >::append(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::clear(), UList< T >::empty(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, IOstream::good(), token::isPunctuation(), UList< T >::last(), Istream::putBack(), Reaction< ReactionThermo >::Reaction(), DynamicList< T, SizeInc, SizeMult, SizeDiv >::remove(), and DynamicList< T, SizeInc, SizeMult, SizeDiv >::shrink().
Referenced by Reaction< ReactionThermo >::specieCoeffs::specieCoeffs(), and Reaction< ReactionThermo >::~Reaction().
kf()
Foam::scalar kf (const scalar p, const scalar T, const scalarField & c) const virtual
Forward rate constant.
Definition at line 445 of file Reaction.C.
References Reaction< ReactionThermo >::kr().
Referenced by TDACChemistryModel< CompType, ThermoType >::jacobian(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::jacobian(), chemistryModel< CompType, ThermoType >::jacobian(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::omega(), chemistryModel< CompType, ThermoType >::omega(), TDACChemistryModel< CompType, ThermoType >::omega(), Reaction< ReactionThermo >::write(), and Reaction< ReactionThermo >::~Reaction().
kr() [1/2]
Foam::scalar kr (const scalar kfwd, const scalar p, const scalar T, const scalarField & c) const virtual
Reverse rate constant from the given forward rate constant.
Definition at line 457 of file Reaction.C.
Referenced by TDACChemistryModel< CompType, ThermoType >::jacobian(), chemistryModel< CompType, ThermoType >::jacobian(), Reaction< ReactionThermo >::kf(), chemistryModel< CompType, ThermoType >::omega(), TDACChemistryModel< CompType, ThermoType >::omega(), and Reaction< ReactionThermo >::~Reaction().
kr() [2/2]
Foam::scalar kr (const scalar p, const scalar T, const scalarField & c) const virtual
Reverse rate constant.
Note this evaluates the forward rate constant and divides by the equilibrium constant
Definition at line 470 of file Reaction.C.
write()
void write (Ostream & os) const virtual
Write.
Reimplemented in solidReaction< ReactionThermo >.
Definition at line 435 of file Reaction.C.
References Reaction< ReactionThermo >::kf(), Foam::nl, reaction(), and Ostream::writeKeyword().
Referenced by ReactionList< Foam::sutherlandTransport >::write(), and Reaction< ReactionThermo >::~Reaction().
Friends And Related Function Documentation
operator
Ostream& operator (Ostream & , const Reaction< ReactionThermo > &) friend
Member Data Documentation
nUnNamedReactions
Foam::label nUnNamedReactions = 0 static
Number of un-named reactions.
Definition at line 84 of file Reaction.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/reaction/Reactions/Reaction/Reaction.H
src/thermophysicalModels/specie/reaction/Reactions/Reaction/Reaction.C
src/thermophysicalModels/specie/reaction/Reactions/Reaction/ReactionI.H