OpenFOAM: thirdBodyArrheniusReactionRate Class Reference
thirdBodyArrheniusReactionRate Class Reference
Arrhenius reaction rate enhanced by third-body interation.
Public Member Functions
thirdBodyArrheniusReactionRate (const scalar A, const scalar beta, const scalar Ta, const thirdBodyEfficiencies &tbes)
Construct from components.
thirdBodyArrheniusReactionRate (const speciesTable &species, Istream &is)
Construct from Istream.
thirdBodyArrheniusReactionRate (const speciesTable &species, const dictionary &dict)
Construct from dictionary.
scalar operator() (const scalar p, const scalar T, const scalarField &c) const
void write (Ostream &os) const
Write to stream.
Static Public Member Functions
static word type ()
Return the type name.
Friends
Ostream & operator<< (Ostream &, const thirdBodyArrheniusReactionRate &)
Detailed Description
Arrhenius reaction rate enhanced by third-body interation.
Source files
thirdBodyArrheniusReactionRate.H
thirdBodyArrheniusReactionRateI.H
Definition at line 56 of file thirdBodyArrheniusReactionRate.H.
Constructor & Destructor Documentation
thirdBodyArrheniusReactionRate() [1/3]
thirdBodyArrheniusReactionRate (const scalar A, const scalar beta, const scalar Ta, const thirdBodyEfficiencies & tbes) inline
Construct from components.
Definition at line 29 of file thirdBodyArrheniusReactionRateI.H.
Referenced by thirdBodyArrheniusReactionRate::thirdBodyArrheniusReactionRate().
thirdBodyArrheniusReactionRate() [2/3]
thirdBodyArrheniusReactionRate (const speciesTable & species, Istream & is) inline
Construct from Istream.
Definition at line 42 of file thirdBodyArrheniusReactionRateI.H.
References Istream::readEnd(), and thirdBodyArrheniusReactionRate::thirdBodyArrheniusReactionRate().
thirdBodyArrheniusReactionRate() [3/3]
thirdBodyArrheniusReactionRate (const speciesTable & species, const dictionary & dict) inline
Construct from dictionary.
Definition at line 59 of file thirdBodyArrheniusReactionRateI.H.
Member Function Documentation
type()
static word type () inline static
Return the type name.
Definition at line 96 of file thirdBodyArrheniusReactionRate.H.
References Foam::constant::universal::c, p, Foam::T(), and thirdBodyArrheniusReactionRate::write().
operator()()
Foam::scalar operator() (const scalar p, const scalar T, const scalarField & c) const inline
Definition at line 76 of file thirdBodyArrheniusReactionRateI.H.
References Foam::constant::universal::c.
write()
void write (Ostream & os) const inline
Write to stream.
Definition at line 88 of file thirdBodyArrheniusReactionRateI.H.
References thirdBodyEfficiencies::write(), and ArrheniusReactionRate::write().
Referenced by thirdBodyArrheniusReactionRate::type().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const thirdBodyArrheniusReactionRate &) friend
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/reaction/reactionRate/thirdBodyArrheniusReactionRate/thirdBodyArrheniusReactionRate.H
src/thermophysicalModels/specie/reaction/reactionRate/thirdBodyArrheniusReactionRate/thirdBodyArrheniusReactionRateI.H