OpenFOAM: Reaction< ReactionThermo >::specieCoeffs Struct Reference
Reaction< ReactionThermo >::specieCoeffs Struct Reference
Class to hold the specie index and its coefficients in the.
Public Member Functions
specieCoeffs ()
specieCoeffs (const speciesTable &species, Istream &is)
bool operator== (const specieCoeffs &sc) const
bool operator!= (const specieCoeffs &sc) const
Public Attributes
label index
scalar stoichCoeff
scalar exponent
Friends
Ostream & operator<< (Ostream &os, const specieCoeffs &sc)
Detailed Description
template<class ReactionThermo>
struct Foam::Reaction< ReactionThermo >::specieCoeffs
Class to hold the specie index and its coefficients in the.
reaction rate expression
Definition at line 91 of file Reaction.H.
Constructor & Destructor Documentation
specieCoeffs() [1/2]
specieCoeffs () inline
Definition at line 97 of file Reaction.H.
References Reaction< ReactionThermo >::species().
Referenced by Reaction< ReactionThermo >::Reaction().
specieCoeffs() [2/2]
specieCoeffs (const speciesTable & species, Istream & is)
Definition at line 179 of file Reaction.C.
References hashedWordList::contains(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, token::info(), token::isNumber(), token::isWord(), token::number(), Reaction< ReactionThermo >::setLRhs(), and token::wordToken().
Member Function Documentation
operator==()
bool operator== (const specieCoeffs & sc) const inline
Definition at line 106 of file Reaction.H.
References Reaction< ReactionThermo >::specieCoeffs::index.
operator!=()
bool operator!= (const specieCoeffs & sc) const inline
Definition at line 111 of file Reaction.H.
References Reaction< ReactionThermo >::specieCoeffs::index.
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & os, const specieCoeffs & sc) friend
Definition at line 116 of file Reaction.H.
Member Data Documentation
index
label index
Definition at line 93 of file Reaction.H.
Referenced by Reaction< ReactionThermo >::specieCoeffs::operator!=(), and Reaction< ReactionThermo >::specieCoeffs::operator==().
stoichCoeff
scalar stoichCoeff
Definition at line 94 of file Reaction.H.
exponent
scalar exponent
Definition at line 95 of file Reaction.H.
The documentation for this struct was generated from the following files:
src/thermophysicalModels/specie/reaction/Reactions/Reaction/Reaction.H
src/thermophysicalModels/specie/reaction/Reactions/Reaction/Reaction.C