OpenFOAM: NSRDSfunc6 Class Reference
NSRDSfunc6 Class Reference
NSRDS function number 106.
Public Member Functions
TypeName ("NSRDSfunc6")
Runtime type information.
NSRDSfunc6 (const scalar Tc, const scalar a, const scalar b, const scalar c, const scalar d, const scalar e)
Construct from components.
NSRDSfunc6 (Istream &is)
Construct from Istream.
NSRDSfunc6 (const dictionary &dict)
Construct from dictionary.
scalar f (scalar, scalar T) const
Evaluate the function and return the result.
void writeData (Ostream &os) const
Write the function coefficients.
Public Member Functions inherited from thermophysicalFunction
TypeName ("thermophysicalFunction")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, thermophysicalFunction, Istream,(Istream &is),(is))
declareRunTimeSelectionTable (autoPtr, thermophysicalFunction, dictionary,(const dictionary &dict),(dict))
thermophysicalFunction ()
Construct null.
virtual ~thermophysicalFunction ()
Destructor.
Friends
Ostream & operator<< (Ostream &os, const NSRDSfunc6 &f)
Additional Inherited Members
Static Public Member Functions inherited from thermophysicalFunction
static autoPtr< thermophysicalFunction > New (Istream &is)
Return pointer to new thermophysicalFunction created from input.
static autoPtr< thermophysicalFunction > New (const dictionary &dict)
Return pointer to new thermophysicalFunction created from dict.
Detailed Description
NSRDS function number 106.
Source:
                  NSRDS - AICHE
             Data Compilation Tables
                of Properties of
                 Pure Compounds
    Design Institute for Physical Property Data
      American Institute of Chemical Engineers
              345 East 47th Street
            New York, New York 10017
     National Standard Reference Data System
     American Institute of Chemical Engineers
      T.E. Daubert       -       R.P. Danner
        Department of Chemical Engineering
        The Pennsylvania State University
            University Park, PA 16802
Definition at line 67 of file NSRDSfunc6.H.
Constructor & Destructor Documentation
NSRDSfunc6() [1/3]
NSRDSfunc6 (const scalar Tc, const scalar a, const scalar b, const scalar c, const scalar d, const scalar e)
Construct from components.
Definition at line 41 of file NSRDSfunc6.C.
NSRDSfunc6() [2/3]
NSRDSfunc6 (Istream & is)
Construct from Istream.
Definition at line 59 of file NSRDSfunc6.C.
NSRDSfunc6() [3/3]
NSRDSfunc6 (const dictionary & dict)
Construct from dictionary.
Definition at line 70 of file NSRDSfunc6.C.
Member Function Documentation
TypeName()
TypeName ("NSRDSfunc6")
Runtime type information.
f()
scalar f (scalar , scalar T) const inline virtual
Evaluate the function and return the result.
Implements thermophysicalFunction.
Definition at line 106 of file NSRDSfunc6.H.
References Foam::pow().
Referenced by iC3H8O::hl(), nC3H8O::hl(), H2O::hl(), C8H10::hl(), bC10H7CH3::hl(), C2H5OH::hl(), C7H16::hl(), C7H8::hl(), C12H26::hl(), C2H6::hl(), C8H18::hl(), aC10H7CH3::hl(), C2H6O::hl(), C9H20::hl(), CH3OH::hl(), C13H28::hl(), CH4N2O::hl(), C3H6O::hl(), Ar::hl(), C14H30::hl(), C3H8::hl(), IC8H18::hl(), C4H10O::hl(), MB::hl(), N2::hl(), C10H22::hl(), C6H14::hl(), C16H34::hl(), C6H6::hl(), IDEA::hl(), C8H10::sigma(), H2O::sigma(), C2H6::sigma(), C8H18::sigma(), C12H26::sigma(), aC10H7CH3::sigma(), CH4N2O::sigma(), C3H6O::sigma(), C13H28::sigma(), C3H8::sigma(), IC8H18::sigma(), MB::sigma(), C9H20::sigma(), C16H34::sigma(), C10H22::sigma(), Ar::sigma(), C7H8::sigma(), CH3OH::sigma(), C2H6O::sigma(), C4H10O::sigma(), bC10H7CH3::sigma(), C6H6::sigma(), C7H16::sigma(), C14H30::sigma(), N2::sigma(), C6H14::sigma(), and IDEA::sigma().
writeData()
void writeData (Ostream & os) const inline virtual
Write the function coefficients.
Implements thermophysicalFunction.
Definition at line 113 of file NSRDSfunc6.H.
References token::SPACE.
Referenced by C8H10::writeData(), H2O::writeData(), iC3H8O::writeData(), nC3H8O::writeData(), aC10H7CH3::writeData(), IC8H18::writeData(), C13H28::writeData(), C3H6O::writeData(), CH4N2O::writeData(), CH3OH::writeData(), C9H20::writeData(), C8H18::writeData(), C2H5OH::writeData(), C7H8::writeData(), C7H16::writeData(), Ar::writeData(), C14H30::writeData(), C4H10O::writeData(), C3H8::writeData(), bC10H7CH3::writeData(), C2H6O::writeData(), C2H6::writeData(), C10H22::writeData(), C16H34::writeData(), N2::writeData(), C6H14::writeData(), C12H26::writeData(), C6H6::writeData(), MB::writeData(), and IDEA::writeData().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & os, const NSRDSfunc6 & f) friend
Definition at line 126 of file NSRDSfunc6.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/thermophysicalFunctions/NSRDSfunctions/NSRDSfunc6/NSRDSfunc6.H
src/thermophysicalModels/thermophysicalFunctions/NSRDSfunctions/NSRDSfunc6/NSRDSfunc6.C