OpenFOAM: eConstThermo< EquationOfState > Class Template Reference
eConstThermo< EquationOfState > Class Template Reference
Constant properties thermodynamics package templated on an equation of state.
Public Member Functions
eConstThermo (Istream &)
Construct from Istream.
eConstThermo (const dictionary &dict)
Construct from dictionary.
eConstThermo (const word &, const eConstThermo &)
Construct as named copy.
autoPtr< eConstThermo > clone () const
Construct and return a clone.
scalar limit (const scalar T) const
Limit the temperature to be in the range Tlow_ to Thigh_.
scalar cp (const scalar p, const scalar T) const
Heat capacity at constant pressure [J/(kmol K)].
scalar ha (const scalar p, const scalar T) const
Absolute Enthalpy [J/kmol].
scalar hs (const scalar p, const scalar T) const
Sensible Enthalpy [J/kmol].
scalar hc () const
Chemical enthalpy [J/kmol].
scalar s (const scalar p, const scalar T) const
Entropy [J/(kmol K)].
void write (Ostream &os) const
Write to Ostream.
void operator+= (const eConstThermo &)
void operator-= (const eConstThermo &)
Static Public Member Functions
static autoPtr< eConstThermo > New (Istream &is)
static autoPtr< eConstThermo > New (const dictionary &dict)
static word typeName ()
Return the instantiated type name.
Friends
eConstThermo operator+ (const eConstThermo &, const eConstThermo &)
eConstThermo operator- (const eConstThermo &, const eConstThermo &)
eConstThermo operator* (const scalar, const eConstThermo &)
eConstThermo operator== (const eConstThermo &, const eConstThermo &)
Ostream & operator (Ostream &, const eConstThermo &)
Detailed Description
template<class EquationOfState>
class Foam::eConstThermo< EquationOfState >
Constant properties thermodynamics package templated on an equation of state.
Source files
eConstThermo.H
eConstThermoI.H
eConstThermo.C
Definition at line 48 of file eConstThermo.H.
Constructor & Destructor Documentation
eConstThermo() [1/3]
eConstThermo (Istream & is)
Construct from Istream.
Definition at line 32 of file eConstThermo.C.
References IOstream::check().
eConstThermo() [2/3]
eConstThermo (const dictionary & dict)
Construct from dictionary.
Definition at line 46 of file eConstThermo.C.
eConstThermo() [3/3]
eConstThermo (const word & , const eConstThermo< EquationOfState > &) inline
Construct as named copy.
Member Function Documentation
clone()
Foam::autoPtr< Foam::eConstThermo< EquationOfState > > clone () const inline
Construct and return a clone.
Definition at line 59 of file eConstThermoI.H.
New() [1/2]
Foam::autoPtr< Foam::eConstThermo< EquationOfState > > New (Istream & is) inline static
Definition at line 70 of file eConstThermoI.H.
New() [2/2]
Foam::autoPtr< Foam::eConstThermo< EquationOfState > > New (const dictionary & dict) inline static
Definition at line 81 of file eConstThermoI.H.
References dict, and eConstThermo< EquationOfState >::limit().
typeName()
static word typeName () inline static
Return the instantiated type name.
Definition at line 143 of file eConstThermo.H.
References eConstThermo< EquationOfState >::cp(), eConstThermo< EquationOfState >::ha(), eConstThermo< EquationOfState >::hc(), eConstThermo< EquationOfState >::hs(), eConstThermo< EquationOfState >::limit(), eConstThermo< EquationOfState >::operator+=(), eConstThermo< EquationOfState >::operator-=(), p, eConstThermo< EquationOfState >::s(), Foam::T(), and eConstThermo< EquationOfState >::write().
limit()
Foam::scalar limit (const scalar T) const inline
Limit the temperature to be in the range Tlow_ to Thigh_.
Definition at line 94 of file eConstThermoI.H.
References eConstThermo< EquationOfState >::cp(), and Foam::T().
Referenced by eConstThermo< EquationOfState >::New(), and eConstThermo< EquationOfState >::typeName().
cp()
Foam::scalar cp (const scalar p, const scalar T) const inline
Heat capacity at constant pressure [J/(kmol K)].
Definition at line 104 of file eConstThermoI.H.
References cp, and eConstThermo< EquationOfState >::ha().
Referenced by eConstThermo< EquationOfState >::ha(), eConstThermo< EquationOfState >::hs(), eConstThermo< EquationOfState >::limit(), eConstThermo< EquationOfState >::s(), and eConstThermo< EquationOfState >::typeName().
ha()
Foam::scalar ha (const scalar p, const scalar T) const inline
Absolute Enthalpy [J/kmol].
Definition at line 115 of file eConstThermoI.H.
References eConstThermo< EquationOfState >::cp(), h, and eConstThermo< EquationOfState >::hs().
Referenced by eConstThermo< EquationOfState >::cp(), and eConstThermo< EquationOfState >::typeName().
hs()
Foam::scalar hs (const scalar p, const scalar T) const inline
Sensible Enthalpy [J/kmol].
Definition at line 126 of file eConstThermoI.H.
References eConstThermo< EquationOfState >::cp(), and h.
Referenced by eConstThermo< EquationOfState >::ha(), and eConstThermo< EquationOfState >::typeName().
hc()
Foam::scalar hc () const inline
Chemical enthalpy [J/kmol].
Definition at line 136 of file eConstThermoI.H.
References eConstThermo< EquationOfState >::s().
Referenced by eConstThermo< EquationOfState >::typeName().
s()
Foam::scalar s (const scalar p, const scalar T) const inline
Entropy [J/(kmol K)].
Definition at line 144 of file eConstThermoI.H.
References eConstThermo< EquationOfState >::cp(), Foam::log(), s(), and Foam::constant::standard::Tstd.
Referenced by eConstThermo< EquationOfState >::hc(), eConstThermo< EquationOfState >::operator-=(), and eConstThermo< EquationOfState >::typeName().
write()
void write (Ostream & os) const
Write to Ostream.
Definition at line 60 of file eConstThermo.C.
References dictionary::add(), dict, dictionaryName::dictName(), Foam::indent(), Foam::tab, and write().
Referenced by eConstThermo< EquationOfState >::typeName().
operator+=()
void operator+= (const eConstThermo< EquationOfState > &) inline
Definition at line 157 of file eConstThermoI.H.
Referenced by eConstThermo< EquationOfState >::typeName().
operator-=()
void operator-= (const eConstThermo< EquationOfState > &) inline
Definition at line 175 of file eConstThermoI.H.
References eConstThermo< EquationOfState >::s().
Referenced by eConstThermo< EquationOfState >::typeName().
Friends And Related Function Documentation
operator+
eConstThermo operator+ (const eConstThermo< EquationOfState > & , const eConstThermo< EquationOfState > &) friend
operator-
eConstThermo operator- (const eConstThermo< EquationOfState > & , const eConstThermo< EquationOfState > &) friend
operator*
eConstThermo operator* (const scalar , const eConstThermo< EquationOfState > &) friend
operator==
eConstThermo operator== (const eConstThermo< EquationOfState > & , const eConstThermo< EquationOfState > &) friend
operator
Ostream& operator (Ostream & , const eConstThermo< EquationOfState > &) friend
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/thermo/eConst/eConstThermo.H
src/thermophysicalModels/specie/thermo/eConst/eConstThermo.C
src/thermophysicalModels/specie/thermo/eConst/eConstThermoI.H