OpenFOAM: sutherlandTransport< Thermo > Class Template Reference
sutherlandTransport< Thermo > Class Template Reference
Transport package using Sutherland's formula.
Public Member Functions
sutherlandTransport (const Thermo &t, const scalar As, const scalar Ts)
Construct from components.
sutherlandTransport (const Thermo &t, const scalar mu1, const scalar T1, const scalar mu2, const scalar T2)
Construct from two viscosities.
sutherlandTransport (const word &, const sutherlandTransport &)
Construct as named copy.
sutherlandTransport (Istream &)
Construct from Istream.
sutherlandTransport (const dictionary &dict)
Construct from dictionary.
sutherlandTransport (const Thermo &t, const dictionary &dict)
Construct from base thermo and dictionary.
autoPtr< sutherlandTransport > clone () const
Construct and return a clone.
scalar mu (const scalar p, const scalar T) const
Dynamic viscosity [kg/ms].
scalar kappa (const scalar p, const scalar T) const
Thermal conductivity [W/mK].
scalar alphah (const scalar p, const scalar T) const
Thermal diffusivity of enthalpy [kg/ms].
void write (Ostream &os) const
Write to Ostream.
void operator= (const sutherlandTransport &)
void operator+= (const sutherlandTransport &)
void operator-= (const sutherlandTransport &)
void operator*= (const scalar)
Static Public Member Functions
static autoPtr< sutherlandTransport > New (Istream &is)
static autoPtr< sutherlandTransport > New (const dictionary &dict)
static word typeName ()
Return the instantiated type name.
Friends
sutherlandTransport operator+ (const sutherlandTransport &, const sutherlandTransport &)
sutherlandTransport operator- (const sutherlandTransport &, const sutherlandTransport &)
sutherlandTransport operator* (const scalar, const sutherlandTransport &)
sutherlandTransport operator== (const sutherlandTransport &, const sutherlandTransport &)
Ostream & operator (Ostream &, const sutherlandTransport &)
Detailed Description
template<class Thermo>
class Foam::sutherlandTransport< Thermo >
Transport package using Sutherland's formula.
Templated into a given thermodynamics package (needed for thermal conductivity).
Dynamic viscosity [kg/m.s]
Source files
sutherlandTransport.H
sutherlandTransportI.H
sutherlandTransport.C
Definition at line 53 of file sutherlandTransport.H.
Constructor & Destructor Documentation
sutherlandTransport() [1/6]
sutherlandTransport (const Thermo & t, const scalar As, const scalar Ts) inline
Construct from components.
Definition at line 51 of file sutherlandTransportI.H.
Referenced by sutherlandTransport< Thermo >::sutherlandTransport().
sutherlandTransport() [2/6]
sutherlandTransport (const Thermo & t, const scalar mu1, const scalar T1, const scalar mu2, const scalar T2) inline
Construct from two viscosities.
Definition at line 65 of file sutherlandTransportI.H.
References sutherlandTransport< Thermo >::sutherlandTransport().
sutherlandTransport() [3/6]
sutherlandTransport (const word & name, const sutherlandTransport< Thermo > & st) inline
Construct as named copy.
Definition at line 79 of file sutherlandTransportI.H.
sutherlandTransport() [4/6]
sutherlandTransport (Istream & is)
Construct from Istream.
Definition at line 45 of file sutherlandTransport.C.
References IOstream::check().
sutherlandTransport() [5/6]
sutherlandTransport (const dictionary & dict)
Construct from dictionary.
Definition at line 56 of file sutherlandTransport.C.
References sutherlandTransport< Thermo >::sutherlandTransport().
sutherlandTransport() [6/6]
sutherlandTransport (const Thermo & t, const dictionary & dict)
Construct from base thermo and dictionary.
Definition at line 66 of file sutherlandTransport.C.
Member Function Documentation
clone()
Foam::autoPtr< Foam::sutherlandTransport< Thermo > > clone () const inline
Construct and return a clone.
Definition at line 92 of file sutherlandTransportI.H.
References sutherlandTransport< Thermo >::New().
New() [1/2]
Foam::autoPtr< Foam::sutherlandTransport< Thermo > > New (Istream & is) inline static
Definition at line 104 of file sutherlandTransportI.H.
Referenced by sutherlandTransport< Thermo >::clone().
New() [2/2]
Foam::autoPtr< Foam::sutherlandTransport< Thermo > > New (const dictionary & dict) inline static
Definition at line 118 of file sutherlandTransportI.H.
References dict, and sutherlandTransport< Thermo >::mu().
typeName()
static word typeName () inline static
Return the instantiated type name.
Definition at line 165 of file sutherlandTransport.H.
References sutherlandTransport< Thermo >::alphah(), sutherlandTransport< Thermo >::kappa(), sutherlandTransport< Thermo >::mu(), sutherlandTransport< Thermo >::operator*=(), sutherlandTransport< Thermo >::operator+=(), sutherlandTransport< Thermo >::operator-=(), sutherlandTransport< Thermo >::operator=(), p, Foam::T(), and sutherlandTransport< Thermo >::write().
mu()
Foam::scalar mu (const scalar p, const scalar T) const inline
Dynamic viscosity [kg/ms].
Definition at line 133 of file sutherlandTransportI.H.
References sutherlandTransport< Thermo >::kappa(), Foam::sqrt(), and T.
Referenced by sutherlandTransport< Thermo >::New(), and sutherlandTransport< Thermo >::typeName().
kappa()
Foam::scalar kappa (const scalar p, const scalar T) const inline
Thermal conductivity [W/mK].
Definition at line 144 of file sutherlandTransportI.H.
References sutherlandTransport< Thermo >::alphah(), Foam::constant::physicoChemical::mu, and R.
Referenced by sutherlandTransport< Thermo >::mu(), and sutherlandTransport< Thermo >::typeName().
alphah()
Foam::scalar alphah (const scalar p, const scalar T) const inline
Thermal diffusivity of enthalpy [kg/ms].
Definition at line 155 of file sutherlandTransportI.H.
References Foam::constant::electromagnetic::kappa.
Referenced by sutherlandTransport< Thermo >::kappa(), and sutherlandTransport< Thermo >::typeName().
write()
void write (Ostream & os) const
Write to Ostream.
Definition at line 80 of file sutherlandTransport.C.
References dictionary::add(), token::BEGIN_BLOCK, Foam::decrIndent(), dict, dictionaryName::dictName(), token::END_BLOCK, Foam::endl(), Foam::incrIndent(), Foam::indent(), specie::name(), Foam::nl, Foam::tab, and write().
Referenced by sutherlandTransport< Thermo >::typeName().
operator=()
void operator= (const sutherlandTransport< Thermo > &) inline
Definition at line 169 of file sutherlandTransportI.H.
Referenced by sutherlandTransport< Thermo >::typeName().
operator+=()
void operator+= (const sutherlandTransport< Thermo > &) inline
Definition at line 182 of file sutherlandTransportI.H.
Referenced by sutherlandTransport< Thermo >::typeName().
operator-=()
void operator-= (const sutherlandTransport< Thermo > &) inline
Definition at line 200 of file sutherlandTransportI.H.
Referenced by sutherlandTransport< Thermo >::typeName().
operator*=()
void operator*= (const scalar s) inline
Definition at line 218 of file sutherlandTransportI.H.
References s().
Referenced by sutherlandTransport< Thermo >::typeName().
Friends And Related Function Documentation
operator+
sutherlandTransport operator+ (const sutherlandTransport< Thermo > & , const sutherlandTransport< Thermo > &) friend
operator-
sutherlandTransport operator- (const sutherlandTransport< Thermo > & , const sutherlandTransport< Thermo > &) friend
operator*
sutherlandTransport operator* (const scalar , const sutherlandTransport< Thermo > &) friend
operator==
sutherlandTransport operator== (const sutherlandTransport< Thermo > & , const sutherlandTransport< Thermo > &) friend
operator
Ostream& operator (Ostream & , const sutherlandTransport< Thermo > &) friend
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/transport/sutherland/sutherlandTransport.H
src/thermophysicalModels/specie/transport/sutherland/sutherlandTransport.C
src/thermophysicalModels/specie/transport/sutherland/sutherlandTransportI.H