OpenFOAM: hPowerThermo< EquationOfState > Class Template Reference
hPowerThermo< EquationOfState > Class Template Reference
Power-function based thermodynamics package templated on EquationOfState.
Public Member Functions
hPowerThermo (Istream &)
Construct from Istream.
hPowerThermo (const dictionary &)
Construct from dictionary.
hPowerThermo (const word &, const hPowerThermo &)
Construct as a named copy.
autoPtr< hPowerThermo > clone () const
Construct and return a clone.
scalar limit (const scalar T) const
Limit the temperature to be in the range Tlow_ to Thigh_.
scalar cp (const scalar p, const scalar T) const
Heat capacity at constant pressure [J/(kg K)].
scalar ha (const scalar p, const scalar T) const
Absolute enthalpy [J/kmol].
scalar hs (const scalar p, const scalar T) const
Sensible enthalpy [J/kg].
scalar hc () const
Chemical enthalpy [J/kg].
scalar s (const scalar p, const scalar T) const
Entropy [J/(kmol K)].
void operator+= (const hPowerThermo &)
void operator-= (const hPowerThermo &)
Static Public Member Functions
static autoPtr< hPowerThermo > New (Istream &is)
Selector from Istream.
static autoPtr< hPowerThermo > New (const dictionary &dict)
Selector from dictionary.
static word typeName ()
Return the instantiated type name.
Friends
hPowerThermo operator+ (const hPowerThermo &, const hPowerThermo &)
hPowerThermo operator- (const hPowerThermo &, const hPowerThermo &)
hPowerThermo operator* (const scalar, const hPowerThermo &)
hPowerThermo operator== (const hPowerThermo &, const hPowerThermo &)
Ostream & operator (Ostream &, const hPowerThermo &)
Detailed Description
template<class EquationOfState>
class Foam::hPowerThermo< EquationOfState >
Power-function based thermodynamics package templated on EquationOfState.
In this thermodynamics package the heat capacity is a simple power of temperature:
Cp(T) = c0*(T/Tref)^n0;
which is particularly suitable for solids.
Source files
hPowerThermo.H
hPowerThermoI.H
hPowerThermo.C
Definition at line 54 of file hPowerThermo.H.
Constructor & Destructor Documentation
hPowerThermo() [1/3]
hPowerThermo (Istream & is)
Construct from Istream.
Definition at line 32 of file hPowerThermo.C.
References IOstream::check().
hPowerThermo() [2/3]
hPowerThermo (const dictionary & dict)
Construct from dictionary.
Definition at line 48 of file hPowerThermo.C.
References IOstream::check(), Foam::endl(), Foam::nl, and Foam::tab.
hPowerThermo() [3/3]
hPowerThermo (const word & name, const hPowerThermo< EquationOfState > & jt) inline
Construct as a named copy.
Definition at line 49 of file hPowerThermoI.H.
Member Function Documentation
clone()
Foam::autoPtr< Foam::hPowerThermo< EquationOfState > > clone () const inline
Construct and return a clone.
Definition at line 84 of file hPowerThermoI.H.
New() [1/2]
Foam::autoPtr< Foam::hPowerThermo< EquationOfState > > New (Istream & is) inline static
Selector from Istream.
Definition at line 95 of file hPowerThermoI.H.
New() [2/2]
Foam::autoPtr< Foam::hPowerThermo< EquationOfState > > New (const dictionary & dict) inline static
Selector from dictionary.
Definition at line 106 of file hPowerThermoI.H.
References dict, and hPowerThermo< EquationOfState >::limit().
typeName()
static word typeName () inline static
Return the instantiated type name.
Definition at line 157 of file hPowerThermo.H.
References hPowerThermo< EquationOfState >::cp(), hPowerThermo< EquationOfState >::ha(), hPowerThermo< EquationOfState >::hc(), hPowerThermo< EquationOfState >::hs(), hPowerThermo< EquationOfState >::limit(), hPowerThermo< EquationOfState >::operator+=(), hPowerThermo< EquationOfState >::operator-=(), p, hPowerThermo< EquationOfState >::s(), and Foam::T().
limit()
Foam::scalar limit (const scalar T) const inline
Limit the temperature to be in the range Tlow_ to Thigh_.
Definition at line 119 of file hPowerThermoI.H.
References hPowerThermo< EquationOfState >::cp(), and T.
Referenced by hPowerThermo< EquationOfState >::New(), and hPowerThermo< EquationOfState >::typeName().
cp()
Foam::scalar cp (const scalar p, const scalar T) const inline
Heat capacity at constant pressure [J/(kg K)].
Definition at line 129 of file hPowerThermoI.H.
References cp, hPowerThermo< EquationOfState >::ha(), and Foam::pow().
Referenced by hPowerThermo< EquationOfState >::limit(), and hPowerThermo< EquationOfState >::typeName().
ha()
Foam::scalar ha (const scalar p, const scalar T) const inline
Absolute enthalpy [J/kmol].
Definition at line 139 of file hPowerThermoI.H.
References hPowerThermo< EquationOfState >::hs().
Referenced by hPowerThermo< EquationOfState >::cp(), and hPowerThermo< EquationOfState >::typeName().
hs()
Foam::scalar hs (const scalar p, const scalar T) const inline
Sensible enthalpy [J/kg].
Definition at line 149 of file hPowerThermoI.H.
References h, Foam::pow(), and Foam::constant::standard::Tstd.
Referenced by hPowerThermo< EquationOfState >::ha(), and hPowerThermo< EquationOfState >::typeName().
hc()
Foam::scalar hc () const inline
Chemical enthalpy [J/kg].
Definition at line 160 of file hPowerThermoI.H.
References hPowerThermo< EquationOfState >::s().
Referenced by hPowerThermo< EquationOfState >::typeName().
s()
Foam::scalar s (const scalar p, const scalar T) const inline
Entropy [J/(kmol K)].
Definition at line 168 of file hPowerThermoI.H.
References Foam::pow(), s(), and Foam::constant::standard::Tstd.
Referenced by hPowerThermo< EquationOfState >::hc(), and hPowerThermo< EquationOfState >::typeName().
operator+=()
void operator+= (const hPowerThermo< EquationOfState > &) inline
Definition at line 182 of file hPowerThermoI.H.
Referenced by hPowerThermo< EquationOfState >::typeName().
operator-=()
void operator-= (const hPowerThermo< EquationOfState > &) inline
Definition at line 201 of file hPowerThermoI.H.
References s().
Referenced by hPowerThermo< EquationOfState >::typeName().
Friends And Related Function Documentation
operator+
hPowerThermo operator+ (const hPowerThermo< EquationOfState > & , const hPowerThermo< EquationOfState > &) friend
operator-
hPowerThermo operator- (const hPowerThermo< EquationOfState > & , const hPowerThermo< EquationOfState > &) friend
operator*
hPowerThermo operator* (const scalar , const hPowerThermo< EquationOfState > &) friend
operator==
hPowerThermo operator== (const hPowerThermo< EquationOfState > & , const hPowerThermo< EquationOfState > &) friend
operator
Ostream& operator (Ostream & , const hPowerThermo< EquationOfState > &) friend
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/thermo/hPower/hPowerThermo.H
src/thermophysicalModels/specie/thermo/hPower/hPowerThermo.C
src/thermophysicalModels/specie/thermo/hPower/hPowerThermoI.H