OpenFOAM: logPolynomialTransport< Thermo, PolySize > Class Template Reference
logPolynomialTransport< Thermo, PolySize > Class Template Reference
Transport package using polynomial functions of ln(T) for mu and kappa:
Public Member Functions
logPolynomialTransport (const logPolynomialTransport &)
Construct copy.
logPolynomialTransport (const word &, const logPolynomialTransport &)
Construct as named copy.
logPolynomialTransport (Istream &is)
Construct from Istream.
logPolynomialTransport (const dictionary &dict)
Construct from dictionary.
autoPtr< logPolynomialTransport > clone () const
Construct and return a clone.
scalar mu (const scalar p, const scalar T) const
Dynamic viscosity [kg/ms].
scalar kappa (const scalar p, const scalar T) const
Thermal conductivity [W/mK].
scalar alphah (const scalar p, const scalar T) const
Thermal diffusivity of enthalpy [kg/ms].
void write (Ostream &os) const
Write to Ostream.
void operator= (const logPolynomialTransport &)
void operator+= (const logPolynomialTransport &)
void operator-= (const logPolynomialTransport &)
void operator*= (const scalar)
Static Public Member Functions
static autoPtr< logPolynomialTransport > New (Istream &is)
static autoPtr< logPolynomialTransport > New (const dictionary &dict)
static word typeName ()
Return the instantiated type name.
Friends
logPolynomialTransport operator+ (const logPolynomialTransport &, const logPolynomialTransport &)
logPolynomialTransport operator- (const logPolynomialTransport &, const logPolynomialTransport &)
logPolynomialTransport operator* (const scalar, const logPolynomialTransport &)
logPolynomialTransport operator== (const logPolynomialTransport &, const logPolynomialTransport &)
Ostream & operator (Ostream &, const logPolynomialTransport &)
Detailed Description
template<class Thermo, int PolySize = 8>
class Foam::logPolynomialTransport< Thermo, PolySize >
Transport package using polynomial functions of ln(T) for mu and kappa:
ln(mu) = sum_i=1^N(a[i] * ln(T)^(i-1)) ln(kappa) = sum_i=1^N(b[i] * ln(T)^(i-1))
Source files
logPolynomialTransport.H
logPolynomialTransportI.H
logPolynomialTransport.C
Definition at line 50 of file logPolynomialTransport.H.
Constructor & Destructor Documentation
logPolynomialTransport() [1/4]
logPolynomialTransport (const logPolynomialTransport< Thermo, PolySize > & pt) inline
Construct copy.
Definition at line 32 of file logPolynomialTransportI.H.
logPolynomialTransport() [2/4]
logPolynomialTransport (const word & name, const logPolynomialTransport< Thermo, PolySize > & pt) inline
Construct as named copy.
Definition at line 58 of file logPolynomialTransportI.H.
logPolynomialTransport() [3/4]
logPolynomialTransport (Istream & is)
Construct from Istream.
Definition at line 33 of file logPolynomialTransport.C.
logPolynomialTransport() [4/4]
logPolynomialTransport (const dictionary & dict)
Construct from dictionary.
Definition at line 48 of file logPolynomialTransport.C.
Member Function Documentation
clone()
Foam::autoPtr< Foam::logPolynomialTransport< Thermo, PolySize > > clone () const inline
Construct and return a clone.
Definition at line 71 of file logPolynomialTransportI.H.
New() [1/2]
Foam::autoPtr< Foam::logPolynomialTransport< Thermo, PolySize > > New (Istream & is) inline static
Definition at line 82 of file logPolynomialTransportI.H.
New() [2/2]
Foam::autoPtr< Foam::logPolynomialTransport< Thermo, PolySize > > New (const dictionary & dict) inline static
Definition at line 93 of file logPolynomialTransportI.H.
References dict, and logPolynomialTransport< Thermo, PolySize >::mu().
typeName()
static word typeName () inline static
Return the instantiated type name.
Definition at line 155 of file logPolynomialTransport.H.
References logPolynomialTransport< Thermo, PolySize >::alphah(), logPolynomialTransport< Thermo, PolySize >::kappa(), logPolynomialTransport< Thermo, PolySize >::mu(), logPolynomialTransport< Thermo, PolySize >::operator*=(), logPolynomialTransport< Thermo, PolySize >::operator+=(), logPolynomialTransport< Thermo, PolySize >::operator-=(), logPolynomialTransport< Thermo, PolySize >::operator=(), p, Foam::T(), and logPolynomialTransport< Thermo, PolySize >::write().
mu()
Foam::scalar mu (const scalar p, const scalar T) const inline
Dynamic viscosity [kg/ms].
Definition at line 106 of file logPolynomialTransportI.H.
References Foam::exp(), logPolynomialTransport< Thermo, PolySize >::kappa(), and Foam::log().
Referenced by logPolynomialTransport< Thermo, PolySize >::New(), and logPolynomialTransport< Thermo, PolySize >::typeName().
kappa()
Foam::scalar kappa (const scalar p, const scalar T) const inline
Thermal conductivity [W/mK].
Definition at line 117 of file logPolynomialTransportI.H.
References logPolynomialTransport< Thermo, PolySize >::alphah(), Foam::exp(), and Foam::log().
Referenced by logPolynomialTransport< Thermo, PolySize >::mu(), and logPolynomialTransport< Thermo, PolySize >::typeName().
alphah()
Foam::scalar alphah (const scalar p, const scalar T) const inline
Thermal diffusivity of enthalpy [kg/ms].
Definition at line 128 of file logPolynomialTransportI.H.
References Foam::constant::electromagnetic::kappa.
Referenced by logPolynomialTransport< Thermo, PolySize >::kappa(), and logPolynomialTransport< Thermo, PolySize >::typeName().
write()
void write (Ostream & os) const
Write to Ostream.
Definition at line 76 of file logPolynomialTransport.C.
References dictionary::add(), Foam::decrIndent(), dict, dictionaryName::dictName(), Foam::endl(), Foam::incrIndent(), Foam::indent(), Foam::name(), Foam::nl, Foam::tab, and write().
Referenced by logPolynomialTransport< Thermo, PolySize >::typeName().
operator=()
void operator= (const logPolynomialTransport< Thermo, PolySize > &) inline
Definition at line 140 of file logPolynomialTransportI.H.
Referenced by logPolynomialTransport< Thermo, PolySize >::typeName().
operator+=()
void operator+= (const logPolynomialTransport< Thermo, PolySize > &) inline
Definition at line 153 of file logPolynomialTransportI.H.
Referenced by logPolynomialTransport< Thermo, PolySize >::typeName().
operator-=()
void operator-= (const logPolynomialTransport< Thermo, PolySize > &) inline
Definition at line 171 of file logPolynomialTransportI.H.
Referenced by logPolynomialTransport< Thermo, PolySize >::typeName().
operator*=()
void operator*= (const scalar s) inline
Definition at line 189 of file logPolynomialTransportI.H.
References s().
Referenced by logPolynomialTransport< Thermo, PolySize >::typeName().
Friends And Related Function Documentation
operator+
logPolynomialTransport operator+ (const logPolynomialTransport< Thermo, PolySize > & , const logPolynomialTransport< Thermo, PolySize > &) friend
operator-
logPolynomialTransport operator- (const logPolynomialTransport< Thermo, PolySize > & , const logPolynomialTransport< Thermo, PolySize > &) friend
operator*
logPolynomialTransport operator* (const scalar , const logPolynomialTransport< Thermo, PolySize > &) friend
operator==
logPolynomialTransport operator== (const logPolynomialTransport< Thermo, PolySize > & , const logPolynomialTransport< Thermo, PolySize > &) friend
operator
Ostream& operator (Ostream & , const logPolynomialTransport< Thermo, PolySize > &) friend
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/transport/logPolynomial/logPolynomialTransport.H
src/thermophysicalModels/specie/transport/logPolynomial/logPolynomialTransport.C
src/thermophysicalModels/specie/transport/logPolynomial/logPolynomialTransportI.H