OpenFOAM: NSRDSfunc5 Class Reference
NSRDSfunc5 Class Reference
NSRDS function number 105.
Public Member Functions
TypeName ("NSRDSfunc5")
Runtime type information.
NSRDSfunc5 (const scalar a, const scalar b, const scalar c, const scalar d)
Construct from components.
NSRDSfunc5 (Istream &is)
Construct from Istream.
NSRDSfunc5 (const dictionary &dict)
Construct from dictionary.
scalar f (scalar, scalar T) const
Evaluate the function and return the result.
void writeData (Ostream &os) const
Write the function coefficients.
Public Member Functions inherited from thermophysicalFunction
TypeName ("thermophysicalFunction")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, thermophysicalFunction, Istream,(Istream &is),(is))
declareRunTimeSelectionTable (autoPtr, thermophysicalFunction, dictionary,(const dictionary &dict),(dict))
thermophysicalFunction ()
Construct null.
virtual ~thermophysicalFunction ()
Destructor.
Friends
Ostream & operator<< (Ostream &os, const NSRDSfunc5 &f)
Additional Inherited Members
Static Public Member Functions inherited from thermophysicalFunction
static autoPtr< thermophysicalFunction > New (Istream &is)
Return pointer to new thermophysicalFunction created from input.
static autoPtr< thermophysicalFunction > New (const dictionary &dict)
Return pointer to new thermophysicalFunction created from dict.
Detailed Description
NSRDS function number 105.
Source:
                  NSRDS - AICHE
             Data Compilation Tables
                of Properties of
                 Pure Compounds
    Design Institute for Physical Property Data
      American Institute of Chemical Engineers
              345 East 47th Street
            New York, New York 10017
     National Standard Reference Data System
     American Institute of Chemical Engineers
      T.E. Daubert       -       R.P. Danner
        Department of Chemical Engineering
        The Pennsylvania State University
            University Park, PA 16802
Definition at line 67 of file NSRDSfunc5.H.
Constructor & Destructor Documentation
NSRDSfunc5() [1/3]
NSRDSfunc5 (const scalar a, const scalar b, const scalar c, const scalar d)
Construct from components.
Definition at line 41 of file NSRDSfunc5.C.
NSRDSfunc5() [2/3]
NSRDSfunc5 (Istream & is)
Construct from Istream.
Definition at line 55 of file NSRDSfunc5.C.
NSRDSfunc5() [3/3]
NSRDSfunc5 (const dictionary & dict)
Construct from dictionary.
Definition at line 64 of file NSRDSfunc5.C.
Member Function Documentation
TypeName()
TypeName ("NSRDSfunc5")
Runtime type information.
f()
scalar f (scalar , scalar T) const inline virtual
Evaluate the function and return the result.
Implements thermophysicalFunction.
Definition at line 104 of file NSRDSfunc5.H.
References Foam::pow().
Referenced by iC3H8O::rho(), nC3H8O::rho(), H2O::rho(), C8H10::rho(), N2::rho(), IC8H18::rho(), C3H6O::rho(), C2H6O::rho(), CH3OH::rho(), C9H20::rho(), C8H18::rho(), C2H5OH::rho(), C7H8::rho(), C7H16::rho(), Ar::rho(), C6H14::rho(), C14H30::rho(), C3H8::rho(), C13H28::rho(), C12H26::rho(), C2H6::rho(), C10H22::rho(), C16H34::rho(), C4H10O::rho(), bC10H7CH3::rho(), aC10H7CH3::rho(), C6H6::rho(), MB::rho(), and IDEA::rho().
writeData()
void writeData (Ostream & os) const inline virtual
Write the function coefficients.
Implements thermophysicalFunction.
Definition at line 110 of file NSRDSfunc5.H.
References token::SPACE.
Referenced by C8H10::writeData(), H2O::writeData(), iC3H8O::writeData(), nC3H8O::writeData(), C4H10O::writeData(), IC8H18::writeData(), C3H6O::writeData(), C2H6O::writeData(), CH3OH::writeData(), C9H20::writeData(), C8H18::writeData(), C2H5OH::writeData(), C7H8::writeData(), C7H16::writeData(), Ar::writeData(), C6H14::writeData(), C14H30::writeData(), C3H8::writeData(), C13H28::writeData(), C12H26::writeData(), C2H6::writeData(), C10H22::writeData(), C16H34::writeData(), N2::writeData(), bC10H7CH3::writeData(), aC10H7CH3::writeData(), C6H6::writeData(), MB::writeData(), and IDEA::writeData().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & os, const NSRDSfunc5 & f) friend
Definition at line 121 of file NSRDSfunc5.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/thermophysicalFunctions/NSRDSfunctions/NSRDSfunc5/NSRDSfunc5.H
src/thermophysicalModels/thermophysicalFunctions/NSRDSfunctions/NSRDSfunc5/NSRDSfunc5.C