OpenFOAM: absoluteInternalEnergy< Thermo > Class Template Reference
absoluteInternalEnergy< Thermo > Class Template Reference
Thermodynamics mapping class to expose the absolute internal energy function as the standard internal energy function e(T).
Public Member Functions
absoluteInternalEnergy ()
Construct.
scalar he (const Thermo &thermo, const scalar p, const scalar T) const
scalar cpv (const Thermo &thermo, const scalar p, const scalar T) const
scalar cpBycpv (const Thermo &thermo, const scalar p, const scalar T) const
cp/cv []
scalar HE (const Thermo &thermo, const scalar p, const scalar T) const
scalar THE (const Thermo &thermo, const scalar e, const scalar p, const scalar T0) const
Temperature from absolute internal energy.
Static Public Member Functions
static word typeName ()
Return the instantiated type name.
static word name ()
Detailed Description
template<class Thermo>
class Foam::absoluteInternalEnergy< Thermo >
Thermodynamics mapping class to expose the absolute internal energy function as the standard internal energy function e(T).
Definition at line 45 of file absoluteInternalEnergy.H.
Constructor & Destructor Documentation
absoluteInternalEnergy()
absoluteInternalEnergy () inline
Construct.
Definition at line 53 of file absoluteInternalEnergy.H.
Member Function Documentation
typeName()
static word typeName () inline static
Return the instantiated type name.
Definition at line 60 of file absoluteInternalEnergy.H.
name()
static word name () inline static
Definition at line 67 of file absoluteInternalEnergy.H.
References absoluteInternalEnergy< Thermo >::he().
he()
scalar he (const Thermo & thermo, const scalar p, const scalar T) const inline
Definition at line 74 of file absoluteInternalEnergy.H.
References absoluteInternalEnergy< Thermo >::cpv().
Referenced by absoluteInternalEnergy< Thermo >::name().
cpv()
scalar cpv (const Thermo & thermo, const scalar p, const scalar T) const inline
Definition at line 85 of file absoluteInternalEnergy.H.
References absoluteInternalEnergy< Thermo >::cpBycpv().
Referenced by absoluteInternalEnergy< Thermo >::he().
cpBycpv()
scalar cpBycpv (const Thermo & thermo, const scalar p, const scalar T) const inline
cp/cv []
Definition at line 96 of file absoluteInternalEnergy.H.
References absoluteInternalEnergy< Thermo >::HE().
Referenced by absoluteInternalEnergy< Thermo >::cpv().
HE()
scalar HE (const Thermo & thermo, const scalar p, const scalar T) const inline
Definition at line 107 of file absoluteInternalEnergy.H.
References absoluteInternalEnergy< Thermo >::THE().
Referenced by absoluteInternalEnergy< Thermo >::cpBycpv().
THE()
scalar THE (const Thermo & thermo, const scalar e, const scalar p, const scalar T0) const inline
Temperature from absolute internal energy.
given an initial temperature T0
Definition at line 119 of file absoluteInternalEnergy.H.
Referenced by absoluteInternalEnergy< Thermo >::HE().
The documentation for this class was generated from the following file:
src/thermophysicalModels/specie/thermo/absoluteInternalEnergy/absoluteInternalEnergy.H