OpenFOAM: hConstThermo< EquationOfState > Class Template Reference
hConstThermo< EquationOfState > Class Template Reference
Constant properties thermodynamics package templated into the EquationOfState.
Public Member Functions
hConstThermo (Istream &)
Construct from Istream.
hConstThermo (const dictionary &dict)
Construct from dictionary.
hConstThermo (const word &, const hConstThermo &)
Construct as named copy.
autoPtr< hConstThermo > clone () const
Construct and return a clone.
scalar limit (const scalar T) const
Limit the temperature to be in the range Tlow_ to Thigh_.
scalar cp (const scalar p, const scalar T) const
Heat capacity at constant pressure [J/(kmol K)].
scalar ha (const scalar p, const scalar T) const
Absolute Enthalpy [J/kmol].
scalar hs (const scalar p, const scalar T) const
Sensible enthalpy [J/kmol].
scalar hc () const
Chemical enthalpy [J/kmol].
scalar s (const scalar p, const scalar T) const
Entropy [J/(kmol K)].
void write (Ostream &os) const
Write to Ostream.
void operator+= (const hConstThermo &)
void operator-= (const hConstThermo &)
Static Public Member Functions
static autoPtr< hConstThermo > New (Istream &is)
Selector from Istream.
static autoPtr< hConstThermo > New (const dictionary &dict)
Selector from dictionary.
static word typeName ()
Return the instantiated type name.
Friends
hConstThermo operator+ (const hConstThermo &, const hConstThermo &)
hConstThermo operator- (const hConstThermo &, const hConstThermo &)
hConstThermo operator* (const scalar, const hConstThermo &)
hConstThermo operator== (const hConstThermo &, const hConstThermo &)
Ostream & operator (Ostream &, const hConstThermo &)
Detailed Description
template<class EquationOfState>
class Foam::hConstThermo< EquationOfState >
Constant properties thermodynamics package templated into the EquationOfState.
Source files
hConstThermo.H
hConstThermoI.H
hConstThermo.C
Definition at line 46 of file hConstThermo.H.
Constructor & Destructor Documentation
hConstThermo() [1/3]
hConstThermo (Istream & is)
Construct from Istream.
Definition at line 32 of file hConstThermo.C.
References IOstream::check().
hConstThermo() [2/3]
hConstThermo (const dictionary & dict)
Construct from dictionary.
Definition at line 46 of file hConstThermo.C.
hConstThermo() [3/3]
hConstThermo (const word & name, const hConstThermo< EquationOfState > & ct) inline
Construct as named copy.
Definition at line 46 of file hConstThermoI.H.
Member Function Documentation
clone()
Foam::autoPtr< Foam::hConstThermo< EquationOfState > > clone () const inline
Construct and return a clone.
Definition at line 59 of file hConstThermoI.H.
New() [1/2]
Foam::autoPtr< Foam::hConstThermo< EquationOfState > > New (Istream & is) inline static
Selector from Istream.
Definition at line 70 of file hConstThermoI.H.
New() [2/2]
Foam::autoPtr< Foam::hConstThermo< EquationOfState > > New (const dictionary & dict) inline static
Selector from dictionary.
Definition at line 81 of file hConstThermoI.H.
References dict, and hConstThermo< EquationOfState >::limit().
typeName()
static word typeName () inline static
Return the instantiated type name.
Definition at line 136 of file hConstThermo.H.
References hConstThermo< EquationOfState >::cp(), hConstThermo< EquationOfState >::ha(), hConstThermo< EquationOfState >::hc(), hConstThermo< EquationOfState >::hs(), hConstThermo< EquationOfState >::limit(), hConstThermo< EquationOfState >::operator+=(), hConstThermo< EquationOfState >::operator-=(), p, hConstThermo< EquationOfState >::s(), Foam::T(), and hConstThermo< EquationOfState >::write().
limit()
Foam::scalar limit (const scalar T) const inline
Limit the temperature to be in the range Tlow_ to Thigh_.
Definition at line 94 of file hConstThermoI.H.
References hConstThermo< EquationOfState >::cp(), and Foam::T().
Referenced by hConstThermo< EquationOfState >::New(), and hConstThermo< EquationOfState >::typeName().
cp()
Foam::scalar cp (const scalar p, const scalar T) const inline
Heat capacity at constant pressure [J/(kmol K)].
Definition at line 104 of file hConstThermoI.H.
References cp, and hConstThermo< EquationOfState >::ha().
Referenced by hConstThermo< EquationOfState >::limit(), and hConstThermo< EquationOfState >::typeName().
ha()
Foam::scalar ha (const scalar p, const scalar T) const inline
Absolute Enthalpy [J/kmol].
Definition at line 115 of file hConstThermoI.H.
References h, and hConstThermo< EquationOfState >::hs().
Referenced by hConstThermo< EquationOfState >::cp(), and hConstThermo< EquationOfState >::typeName().
hs()
Foam::scalar hs (const scalar p, const scalar T) const inline
Sensible enthalpy [J/kmol].
Definition at line 125 of file hConstThermoI.H.
References h.
Referenced by hConstThermo< EquationOfState >::ha(), and hConstThermo< EquationOfState >::typeName().
hc()
Foam::scalar hc () const inline
Chemical enthalpy [J/kmol].
Definition at line 134 of file hConstThermoI.H.
References hConstThermo< EquationOfState >::s().
Referenced by hConstThermo< EquationOfState >::typeName().
s()
Foam::scalar s (const scalar p, const scalar T) const inline
Entropy [J/(kmol K)].
Definition at line 142 of file hConstThermoI.H.
References Foam::log(), s(), and Foam::constant::standard::Tstd.
Referenced by hConstThermo< EquationOfState >::hc(), hConstThermo< EquationOfState >::operator-=(), and hConstThermo< EquationOfState >::typeName().
write()
void write (Ostream & os) const
Write to Ostream.
Definition at line 60 of file hConstThermo.C.
References dictionary::add(), dict, dictionaryName::dictName(), Foam::indent(), Foam::tab, and write().
Referenced by hConstThermo< EquationOfState >::typeName().
operator+=()
void operator+= (const hConstThermo< EquationOfState > &) inline
Definition at line 154 of file hConstThermoI.H.
Referenced by hConstThermo< EquationOfState >::typeName().
operator-=()
void operator-= (const hConstThermo< EquationOfState > &) inline
Definition at line 172 of file hConstThermoI.H.
References hConstThermo< EquationOfState >::s().
Referenced by hConstThermo< EquationOfState >::typeName().
Friends And Related Function Documentation
operator+
hConstThermo operator+ (const hConstThermo< EquationOfState > & , const hConstThermo< EquationOfState > &) friend
operator-
hConstThermo operator- (const hConstThermo< EquationOfState > & , const hConstThermo< EquationOfState > &) friend
operator*
hConstThermo operator* (const scalar , const hConstThermo< EquationOfState > &) friend
operator==
hConstThermo operator== (const hConstThermo< EquationOfState > & , const hConstThermo< EquationOfState > &) friend
operator
Ostream& operator (Ostream & , const hConstThermo< EquationOfState > &) friend
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/thermo/hConst/hConstThermo.H
src/thermophysicalModels/specie/thermo/hConst/hConstThermo.C
src/thermophysicalModels/specie/thermo/hConst/hConstThermoI.H