OpenFOAM: janafThermo< EquationOfState > Class Template Reference
janafThermo< EquationOfState > Class Template Reference
JANAF tables based thermodynamics package templated into the equation of state.
Public Types
typedef FixedList< scalar, nCoeffs_ > coeffArray
Public Member Functions
janafThermo (const EquationOfState &st, const scalar Tlow, const scalar Thigh, const scalar Tcommon, const coeffArray &highCpCoeffs, const coeffArray &lowCpCoeffs)
Construct from components.
janafThermo (Istream &)
Construct from Istream.
janafThermo (const dictionary &dict)
Construct from dictionary.
janafThermo (const word &, const janafThermo &)
Construct as a named copy.
scalar limit (const scalar T) const
Limit the temperature to be in the range Tlow_ to Thigh_.
scalar Tlow () const
Return const access to the low temperature limit.
scalar Thigh () const
Return const access to the high temperature limit.
scalar Tcommon () const
Return const access to the common temperature.
const coeffArray & highCpCoeffs () const
Return const access to the high temperature poly coefficients.
const coeffArray & lowCpCoeffs () const
Return const access to the low temperature poly coefficients.
scalar cp (const scalar p, const scalar T) const
Heat capacity at constant pressure [J/(kmol K)].
scalar ha (const scalar p, const scalar T) const
Absolute Enthalpy [J/kmol].
scalar hs (const scalar p, const scalar T) const
Sensible enthalpy [J/kmol].
scalar hc () const
Chemical enthalpy [J/kmol].
scalar s (const scalar p, const scalar T) const
Entropy [J/(kmol K)].
void write (Ostream &os) const
Write to Ostream.
void operator+= (const janafThermo &)
void operator-= (const janafThermo &)
Static Public Member Functions
static word typeName ()
Return the instantiated type name.
Static Public Attributes
static const int nCoeffs_ = 7
Friends
janafThermo operator+ (const janafThermo &, const janafThermo &)
janafThermo operator- (const janafThermo &, const janafThermo &)
janafThermo operator* (const scalar, const janafThermo &)
janafThermo operator== (const janafThermo &, const janafThermo &)
Ostream & operator (Ostream &, const janafThermo &)
Detailed Description
template<class EquationOfState>
class Foam::janafThermo< EquationOfState >
JANAF tables based thermodynamics package templated into the equation of state.
Source files
janafThermo.H
janafThermoI.H
janafThermo.C
Definition at line 49 of file janafThermo.H.
Member Typedef Documentation
coeffArray
typedef FixedList<scalar, nCoeffs_> coeffArray
Definition at line 102 of file janafThermo.H.
Constructor & Destructor Documentation
janafThermo() [1/4]
janafThermo (const EquationOfState & st, const scalar Tlow, const scalar Thigh, const scalar Tcommon, const coeffArray & highCpCoeffs, const coeffArray & lowCpCoeffs) inline
Construct from components.
janafThermo() [2/4]
janafThermo (Istream & is)
Construct from Istream.
Definition at line 60 of file janafThermo.C.
References IOstream::check(), and forAll.
janafThermo() [3/4]
janafThermo (const dictionary & dict)
Construct from dictionary.
Definition at line 85 of file janafThermo.C.
janafThermo() [4/4]
janafThermo (const word & name, const janafThermo< EquationOfState > & jt) inline
Construct as a named copy.
Definition at line 77 of file janafThermoI.H.
References janafThermo< EquationOfState >::limit(), and janafThermo< EquationOfState >::nCoeffs_.
Member Function Documentation
typeName()
static word typeName () inline static
Return the instantiated type name.
Definition at line 153 of file janafThermo.H.
References janafThermo< EquationOfState >::cp(), janafThermo< EquationOfState >::ha(), janafThermo< EquationOfState >::hc(), janafThermo< EquationOfState >::highCpCoeffs(), janafThermo< EquationOfState >::hs(), janafThermo< EquationOfState >::limit(), janafThermo< EquationOfState >::lowCpCoeffs(), janafThermo< EquationOfState >::operator+=(), janafThermo< EquationOfState >::operator-=(), p, janafThermo< EquationOfState >::s(), Foam::T(), janafThermo< EquationOfState >::Tcommon(), janafThermo< EquationOfState >::Thigh(), janafThermo< EquationOfState >::Tlow(), and janafThermo< EquationOfState >::write().
limit()
Foam::scalar limit (const scalar T) const inline
Limit the temperature to be in the range Tlow_ to Thigh_.
Definition at line 99 of file janafThermoI.H.
References Foam::endl(), Foam::max(), Foam::min(), Foam::T(), and WarningInFunction.
Referenced by janafThermo< EquationOfState >::janafThermo(), and janafThermo< EquationOfState >::typeName().
Tlow()
Foam::scalar Tlow () const inline
Return const access to the low temperature limit.
Definition at line 121 of file janafThermoI.H.
Referenced by janafThermo< EquationOfState >::typeName().
Thigh()
Foam::scalar Thigh () const inline
Return const access to the high temperature limit.
Definition at line 128 of file janafThermoI.H.
Referenced by janafThermo< EquationOfState >::typeName().
Tcommon()
Foam::scalar Tcommon () const inline
Return const access to the common temperature.
Definition at line 135 of file janafThermoI.H.
Referenced by janafThermo< EquationOfState >::typeName().
highCpCoeffs()
const Foam::janafThermo< EquationOfState >::coeffArray & highCpCoeffs () const inline
Return const access to the high temperature poly coefficients.
Definition at line 143 of file janafThermoI.H.
Referenced by janafThermo< EquationOfState >::operator-=(), and janafThermo< EquationOfState >::typeName().
lowCpCoeffs()
const Foam::janafThermo< EquationOfState >::coeffArray & lowCpCoeffs () const inline
Return const access to the low temperature poly coefficients.
Definition at line 151 of file janafThermoI.H.
References janafThermo< EquationOfState >::cp().
Referenced by janafThermo< EquationOfState >::operator-=(), and janafThermo< EquationOfState >::typeName().
cp()
Foam::scalar cp (const scalar p, const scalar T) const inline
Heat capacity at constant pressure [J/(kmol K)].
Definition at line 159 of file janafThermoI.H.
References cp, janafThermo< EquationOfState >::ha(), and Foam::constant::thermodynamic::RR.
Referenced by janafThermo< EquationOfState >::lowCpCoeffs(), and janafThermo< EquationOfState >::typeName().
ha()
Foam::scalar ha (const scalar p, const scalar T) const inline
Absolute Enthalpy [J/kmol].
Definition at line 173 of file janafThermoI.H.
References h, janafThermo< EquationOfState >::hs(), and Foam::constant::thermodynamic::RR.
Referenced by janafThermo< EquationOfState >::cp(), janafThermo< EquationOfState >::hs(), and janafThermo< EquationOfState >::typeName().
hs()
Foam::scalar hs (const scalar p, const scalar T) const inline
Sensible enthalpy [J/kmol].
Definition at line 190 of file janafThermoI.H.
References janafThermo< EquationOfState >::ha(), and janafThermo< EquationOfState >::hc().
Referenced by janafThermo< EquationOfState >::ha(), and janafThermo< EquationOfState >::typeName().
hc()
Foam::scalar hc () const inline
Chemical enthalpy [J/kmol].
Definition at line 200 of file janafThermoI.H.
References Foam::constant::thermodynamic::RR, janafThermo< EquationOfState >::s(), and Foam::constant::standard::Tstd.
Referenced by janafThermo< EquationOfState >::hs(), and janafThermo< EquationOfState >::typeName().
s()
Foam::scalar s (const scalar p, const scalar T) const inline
Entropy [J/(kmol K)].
Definition at line 215 of file janafThermoI.H.
References Foam::log(), Foam::constant::thermodynamic::RR, and s().
Referenced by janafThermo< EquationOfState >::hc(), janafThermo< EquationOfState >::operator-=(), and janafThermo< EquationOfState >::typeName().
write()
void write (Ostream & os) const
Write to Ostream.
Definition at line 101 of file janafThermo.C.
References dictionary::add(), IOstream::check(), dict, dictionaryName::dictName(), Foam::endl(), forAll, Foam::indent(), Foam::nl, Foam::tab, and write().
Referenced by janafThermo< EquationOfState >::typeName().
operator+=()
void operator+= (const janafThermo< EquationOfState > &) inline
Definition at line 235 of file janafThermoI.H.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::max(), Foam::min(), Foam::name(), and Foam::notEqual().
Referenced by janafThermo< EquationOfState >::typeName().
operator-=()
void operator-= (const janafThermo< EquationOfState > &) inline
Definition at line 279 of file janafThermoI.H.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, janafThermo< EquationOfState >::highCpCoeffs(), janafThermo< EquationOfState >::lowCpCoeffs(), Foam::max(), Foam::min(), Foam::name(), Foam::notEqual(), and janafThermo< EquationOfState >::s().
Referenced by janafThermo< EquationOfState >::typeName().
Friends And Related Function Documentation
operator+
janafThermo operator+ (const janafThermo< EquationOfState > & , const janafThermo< EquationOfState > &) friend
operator-
janafThermo operator- (const janafThermo< EquationOfState > & , const janafThermo< EquationOfState > &) friend
operator*
janafThermo operator* (const scalar , const janafThermo< EquationOfState > &) friend
operator==
janafThermo operator== (const janafThermo< EquationOfState > & , const janafThermo< EquationOfState > &) friend
operator
Ostream& operator (Ostream & , const janafThermo< EquationOfState > &) friend
Member Data Documentation
nCoeffs_
const int nCoeffs_ = 7 static
Definition at line 101 of file janafThermo.H.
Referenced by janafThermo< EquationOfState >::janafThermo().
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/thermo/janaf/janafThermo.H
src/thermophysicalModels/specie/thermo/janaf/janafThermo.C
src/thermophysicalModels/specie/thermo/janaf/janafThermoI.H