OpenFOAM: thermo< Thermo, Type > Class Template Reference
thermo< Thermo, Type > Class Template Reference
Public Types
typedef thermo< Thermo, Type > thermoType
The thermodynamics of the individual species'.
Public Member Functions
thermo (const Thermo &sp)
Construct from components.
thermo (Istream &)
Construct from Istream.
thermo (const dictionary &dict)
Construct from dictionary.
thermo (const word &name, const thermo &)
Construct as named copy.
scalar he (const scalar p, const scalar T) const
Enthalpy/Internal energy [J/kmol].
scalar cv (const scalar p, const scalar T) const
Heat capacity at constant volume [J/(kmol K)].
scalar cpv (const scalar p, const scalar T) const
Heat capacity at constant pressure/volume [J/(kmol K)].
scalar gamma (const scalar p, const scalar T) const
Gamma = cp/cv [].
scalar cpBycpv (const scalar p, const scalar T) const
Ratio of heat capacity at constant pressure to that at.
scalar es (const scalar p, const scalar T) const
Sensible internal energy [J/kmol].
scalar ea (const scalar p, const scalar T) const
Absolute internal energy [J/kmol].
scalar g (const scalar p, const scalar T) const
Gibbs free energy [J/kmol].
scalar a (const scalar p, const scalar T) const
Helmholtz free energy [J/kmol].
scalar Cp (const scalar p, const scalar T) const
Heat capacity at constant pressure [J/(kg K)].
scalar Cv (const scalar p, const scalar T) const
Heat capacity at constant volume [J/(kg K)].
scalar Cpv (const scalar p, const scalar T) const
Heat capacity at constant pressure/volume [J/(kg K)].
scalar HE (const scalar p, const scalar T) const
Enthalpy/Internal energy [J/kg].
scalar Hs (const scalar p, const scalar T) const
Sensible enthalpy [J/kg].
scalar Hc () const
Chemical enthalpy [J/kg].
scalar Ha (const scalar p, const scalar T) const
Absolute Enthalpy [J/kg].
scalar S (const scalar p, const scalar T) const
Entropy [J/(kg K)].
scalar E (const scalar p, const scalar T) const
Internal energy [J/kg].
scalar Es (const scalar p, const scalar T) const
Sensible internal energy [J/kg].
scalar Ea (const scalar p, const scalar T) const
Absolute internal energy [J/kg].
scalar G (const scalar p, const scalar T) const
Gibbs free energy [J/kg].
scalar A (const scalar p, const scalar T) const
Helmholtz free energy [J/kg].
scalar K (const scalar p, const scalar T) const
Equilibrium constant [] i.t.o fugacities.
scalar Kp (const scalar p, const scalar T) const
Equilibrium constant [] i.t.o. partial pressures.
scalar Kc (const scalar p, const scalar T) const
Equilibrium constant i.t.o. molar concentration.
scalar Kx (const scalar p, const scalar T) const
Equilibrium constant [] i.t.o. mole-fractions.
scalar Kn (const scalar p, const scalar T, const scalar n) const
Equilibrium constant [] i.t.o. number of moles.
scalar THE (const scalar H, const scalar p, const scalar T0) const
Temperature from enthalpy or internal energy.
scalar THs (const scalar Hs, const scalar p, const scalar T0) const
Temperature from sensible enthalpy given an initial T0.
scalar THa (const scalar H, const scalar p, const scalar T0) const
Temperature from absolute enthalpy.
scalar TEs (const scalar E, const scalar p, const scalar T0) const
Temperature from sensible internal energy.
scalar TEa (const scalar E, const scalar p, const scalar T0) const
Temperature from absolute internal energy.
void write (Ostream &os) const
Write to Ostream.
void operator+= (const thermo &)
void operator-= (const thermo &)
void operator*= (const scalar)
Static Public Member Functions
static word typeName ()
Return the instantiated type name.
static word heName ()
Name of Enthalpy/Internal energy.
Friends
thermo operator+ (const thermo &, const thermo &)
thermo operator- (const thermo &, const thermo &)
thermo operator* (const scalar s, const thermo &)
thermo operator== (const thermo &, const thermo &)
Ostream & operator (Ostream &, const thermo &)
Detailed Description
template<class Thermo, template< class > class Type>
class Foam::species::thermo< Thermo, Type >
Definition at line 52 of file thermo.H.
Member Typedef Documentation
thermoType
typedef thermo<Thermo, Type> thermoType
The thermodynamics of the individual species'.
Definition at line 128 of file thermo.H.
Constructor & Destructor Documentation
thermo() [1/4]
thermo (const Thermo & sp) inline
Construct from components.
Definition at line 32 of file thermoI.H.
References Foam::abort(), f(), Foam::constant::physicoChemical::F, Foam::FatalError, FatalErrorInFunction, Foam::MULES::limit(), Foam::mag(), and p.
thermo() [2/4]
thermo (Istream & is)
Construct from Istream.
Definition at line 41 of file thermo.C.
References IOstream::check().
thermo() [3/4]
thermo (const dictionary & dict)
Construct from dictionary.
Definition at line 50 of file thermo.C.
thermo() [4/4]
thermo (const word & name, const thermo< Thermo, Type > & st) inline
Construct as named copy.
Definition at line 81 of file thermoI.H.
Member Function Documentation
typeName()
static word typeName () inline static
Return the instantiated type name.
Definition at line 149 of file thermo.H.
References g, Foam::constant::universal::G, he, n, s(), Foam::T(), and write().
heName()
Foam::word heName () inline static
Name of Enthalpy/Internal energy.
Definition at line 94 of file thermoI.H.
References Foam::name().
he()
Foam::scalar he (const scalar p, const scalar T) const inline
Enthalpy/Internal energy [J/kmol].
Definition at line 102 of file thermoI.H.
References he.
cv()
Foam::scalar cv (const scalar p, const scalar T) const inline
Heat capacity at constant volume [J/(kmol K)].
Definition at line 110 of file thermoI.H.
References cp.
cpv()
Foam::scalar cpv (const scalar p, const scalar T) const inline
Heat capacity at constant pressure/volume [J/(kmol K)].
Definition at line 118 of file thermoI.H.
gamma()
Foam::scalar gamma (const scalar p, const scalar T) const inline
Gamma = cp/cv [].
Definition at line 126 of file thermoI.H.
References cp, and thermo< Thermo, Type >::cpBycpv().
cpBycpv()
Foam::scalar cpBycpv (const scalar p, const scalar T) const inline
Ratio of heat capacity at constant pressure to that at.
constant pressure/volume []
Definition at line 136 of file thermoI.H.
Referenced by thermo< Thermo, Type >::gamma().
es()
Foam::scalar es (const scalar p, const scalar T) const inline
Sensible internal energy [J/kmol].
Definition at line 147 of file thermoI.H.
References rho.
ea()
Foam::scalar ea (const scalar p, const scalar T) const inline
Absolute internal energy [J/kmol].
Definition at line 155 of file thermoI.H.
References rho.
g()
Foam::scalar g (const scalar p, const scalar T) const inline
Gibbs free energy [J/kmol].
Definition at line 163 of file thermoI.H.
References s().
a()
Foam::scalar a (const scalar p, const scalar T) const inline
Helmholtz free energy [J/kmol].
Definition at line 171 of file thermoI.H.
References s().
Cp()
Foam::scalar Cp (const scalar p, const scalar T) const inline
Heat capacity at constant pressure [J/(kg K)].
Definition at line 187 of file thermoI.H.
References cp.
Cv()
Foam::scalar Cv (const scalar p, const scalar T) const inline
Heat capacity at constant volume [J/(kg K)].
Definition at line 195 of file thermoI.H.
Cpv()
Foam::scalar Cpv (const scalar p, const scalar T) const inline
Heat capacity at constant pressure/volume [J/(kg K)].
Definition at line 179 of file thermoI.H.
HE()
Foam::scalar HE (const scalar p, const scalar T) const inline
Enthalpy/Internal energy [J/kg].
Definition at line 203 of file thermoI.H.
Hs()
Foam::scalar Hs (const scalar p, const scalar T) const inline
Sensible enthalpy [J/kg].
Definition at line 211 of file thermoI.H.
Hc()
Foam::scalar Hc () const inline
Chemical enthalpy [J/kg].
Definition at line 219 of file thermoI.H.
Ha()
Foam::scalar Ha (const scalar p, const scalar T) const inline
Absolute Enthalpy [J/kg].
Definition at line 227 of file thermoI.H.
S()
Foam::scalar S (const scalar p, const scalar T) const inline
Entropy [J/(kg K)].
Definition at line 235 of file thermoI.H.
References s().
E()
Foam::scalar E (const scalar p, const scalar T) const inline
Internal energy [J/kg].
Definition at line 243 of file thermoI.H.
References Foam::constant::electromagnetic::e.
Es()
Foam::scalar Es (const scalar p, const scalar T) const inline
Sensible internal energy [J/kg].
Definition at line 251 of file thermoI.H.
Ea()
Foam::scalar Ea (const scalar p, const scalar T) const inline
Absolute internal energy [J/kg].
Definition at line 258 of file thermoI.H.
G()
Foam::scalar G (const scalar p, const scalar T) const inline
Gibbs free energy [J/kg].
Definition at line 266 of file thermoI.H.
References g.
A()
Foam::scalar A (const scalar p, const scalar T) const inline
Helmholtz free energy [J/kg].
Definition at line 274 of file thermoI.H.
K()
Foam::scalar K (const scalar p, const scalar T) const inline
Equilibrium constant [] i.t.o fugacities.
= PIi(fi/Pstd)^nui
Definition at line 282 of file thermoI.H.
References Foam::exp(), g, Foam::constant::standard::Pstd, Foam::constant::thermodynamic::RR, and T.
Kp()
Foam::scalar Kp (const scalar p, const scalar T) const inline
Equilibrium constant [] i.t.o. partial pressures.
= PIi(pi/Pstd)^nui For low pressures (where the gas mixture is near perfect) Kp = K
Definition at line 299 of file thermoI.H.
Kc()
Foam::scalar Kc (const scalar p, const scalar T) const inline
Equilibrium constant i.t.o. molar concentration.
= PIi(ci/cstd)^nui For low pressures (where the gas mixture is near perfect) Kc = Kp(pstd/(RR*T))^nu
Definition at line 307 of file thermoI.H.
References Foam::equal(), thermo< Thermo, Type >::Kx(), Foam::pow(), Foam::constant::standard::Pstd, and Foam::constant::thermodynamic::RR.
Kx()
Foam::scalar Kx (const scalar p, const scalar T) const inline
Equilibrium constant [] i.t.o. mole-fractions.
For low pressures (where the gas mixture is near perfect) Kx = Kp(pstd/p)^nui
Definition at line 322 of file thermoI.H.
References Foam::equal(), thermo< Thermo, Type >::Kn(), Foam::pow(), and Foam::constant::standard::Pstd.
Referenced by thermo< Thermo, Type >::Kc().
Kn()
Foam::scalar Kn (const scalar p, const scalar T, const scalar n) const inline
Equilibrium constant [] i.t.o. number of moles.
For low pressures (where the gas mixture is near perfect) Kn = Kp(n*pstd/p)^nui where n = number of moles in mixture
Definition at line 340 of file thermoI.H.
References Foam::equal(), Foam::pow(), Foam::constant::standard::Pstd, and thermo< Thermo, Type >::THE().
Referenced by thermo< Thermo, Type >::Kx().
THE()
Foam::scalar THE (const scalar H, const scalar p, const scalar T0) const inline
Temperature from enthalpy or internal energy.
given an initial temperature T0
Definition at line 359 of file thermoI.H.
References thermo< Thermo, Type >::THs().
Referenced by thermo< Thermo, Type >::Kn().
THs()
Foam::scalar THs (const scalar Hs, const scalar p, const scalar T0) const inline
Temperature from sensible enthalpy given an initial T0.
Definition at line 371 of file thermoI.H.
References T, and thermo< Thermo, Type >::THa().
Referenced by thermo< Thermo, Type >::THE().
THa()
Foam::scalar THa (const scalar H, const scalar p, const scalar T0) const inline
Temperature from absolute enthalpy.
given an initial temperature T0
Definition at line 391 of file thermoI.H.
References T, and thermo< Thermo, Type >::TEs().
Referenced by thermo< Thermo, Type >::THs().
TEs()
Foam::scalar TEs (const scalar E, const scalar p, const scalar T0) const inline
Temperature from sensible internal energy.
given an initial temperature T0
Definition at line 411 of file thermoI.H.
References T, and thermo< Thermo, Type >::TEa().
Referenced by thermo< Thermo, Type >::THa().
TEa()
Foam::scalar TEa (const scalar E, const scalar p, const scalar T0) const inline
Temperature from absolute internal energy.
given an initial temperature T0
Definition at line 431 of file thermoI.H.
References T.
Referenced by thermo< Thermo, Type >::TEs().
write()
void write (Ostream & os) const
Write to Ostream.
Definition at line 59 of file thermo.C.
References IOstream::check(), and write().
operator+=()
void operator+= (const thermo< Thermo, Type > &) inline
Definition at line 453 of file thermoI.H.
operator-=()
void operator-= (const thermo< Thermo, Type > &) inline
Definition at line 463 of file thermoI.H.
operator*=()
void operator*= (const scalar s) inline
Definition at line 472 of file thermoI.H.
References s().
Friends And Related Function Documentation
operator+
thermo operator+ (const thermo< Thermo, Type > & , const thermo< Thermo, Type > &) friend
operator-
thermo operator- (const thermo< Thermo, Type > & , const thermo< Thermo, Type > &) friend
operator*
thermo operator* (const scalar s, const thermo< Thermo, Type > &) friend
operator==
thermo operator== (const thermo< Thermo, Type > & , const thermo< Thermo, Type > &) friend
operator
Ostream& operator (Ostream & , const thermo< Thermo, Type > &) friend
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/thermo/thermo/thermo.H
src/thermophysicalModels/specie/thermo/thermo/thermo.C
src/thermophysicalModels/specie/thermo/thermo/thermoI.H