OpenFOAM: specieElement Class Reference
specieElement Class Reference
Public Member Functions
specieElement ()
Construct null.
specieElement (const word &name, const label nAtoms)
Construct from components.
specieElement (Istream &)
Construct from Istream.
const word & name () const
Return the name of the element.
word & name ()
Return non-const access to the name of the element.
label nAtoms () const
Return the number of atoms of this element in the specie.
label & nAtoms ()
Return non-const access to the number of atoms of this element.
bool operator== (const specieElement &) const
Equality comparison.
bool operator!= (const specieElement &) const
Inequality comparison.
Friends
Ostream & operator<< (Ostream &, const specieElement &)
Detailed Description
Source files
specieElement.H
specieElementI.H
Definition at line 52 of file specieElement.H.
Constructor & Destructor Documentation
specieElement() [1/3]
specieElement () inline
Construct null.
Definition at line 30 of file specieElementI.H.
specieElement() [2/3]
specieElement (const word & name, const label nAtoms) inline
Construct from components.
Definition at line 34 of file specieElementI.H.
specieElement() [3/3]
specieElement (Istream & is) inline
Construct from Istream.
Definition at line 41 of file specieElementI.H.
Member Function Documentation
name() [1/2]
const Foam::word & name () const inline
Return the name of the element.
Definition at line 50 of file specieElementI.H.
Referenced by DAC< CompType, ThermoType >::DAC(), DRGEP< CompType, ThermoType >::DRGEP(), EFA< CompType, ThermoType >::EFA(), and Foam::operator<<().
name() [2/2]
Foam::word & name () inline
Return non-const access to the name of the element.
Definition at line 56 of file specieElementI.H.
nAtoms() [1/2]
Foam::label nAtoms () const inline
Return the number of atoms of this element in the specie.
Definition at line 62 of file specieElementI.H.
Referenced by DAC< CompType, ThermoType >::DAC(), DRGEP< CompType, ThermoType >::DRGEP(), EFA< CompType, ThermoType >::EFA(), and Foam::operator<<().
nAtoms() [2/2]
Foam::label & nAtoms () inline
Return non-const access to the number of atoms of this element.
in the specie
Definition at line 68 of file specieElementI.H.
operator==()
bool operator== (const specieElement & se) const inline
Equality comparison.
Definition at line 76 of file specieElementI.H.
Referenced by specieElement::operator!=().
operator!=()
bool operator!= (const specieElement & se) const inline
Inequality comparison.
Definition at line 86 of file specieElementI.H.
References specieElement::operator==().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & , const specieElement &) friend
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/specieElement/specieElement.H
src/thermophysicalModels/specie/specieElement/specieElementI.H