OpenFOAM: interfaceProperties Class Reference
interfaceProperties Class Reference
Contains the interface properties.
Public Member Functions
interfaceProperties (const volScalarField &alpha1, const volVectorField &U, const IOdictionary &)
Construct from volume fraction field gamma and IOdictionary.
scalar cAlpha () const
const dimensionedScalar & deltaN () const
const surfaceScalarField & nHatf () const
const volScalarField & K () const
const dimensionedScalar & sigma () const
tmp< volScalarField > sigmaK () const
tmp< surfaceScalarField > surfaceTensionForce () const
tmp< volScalarField > nearInterface () const
Indicator of the proximity of the interface.
void correct ()
bool read ()
Read transportProperties dictionary.
Static Public Attributes
static const scalar convertToRad
Conversion factor for degrees into radians.
Detailed Description
Contains the interface properties.
Properties to aid interFoam:
Correct the alpha boundary condition for dynamic contact angle.
Calculate interface curvature.
Source files
interfaceProperties.H
interfaceProperties.C
Definition at line 54 of file interfaceProperties.H.
Constructor & Destructor Documentation
interfaceProperties()
interfaceProperties (const volScalarField & alpha1, const volVectorField & U, const IOdictionary & dict)
Construct from volume fraction field gamma and IOdictionary.
Definition at line 156 of file interfaceProperties.C.
Member Function Documentation
cAlpha()
scalar cAlpha () const inline
Definition at line 114 of file interfaceProperties.H.
deltaN()
const dimensionedScalar& deltaN () const inline
Definition at line 119 of file interfaceProperties.H.
nHatf()
const surfaceScalarField& nHatf () const inline
Definition at line 124 of file interfaceProperties.H.
K()
const volScalarField& K () const inline
Definition at line 129 of file interfaceProperties.H.
sigma()
const dimensionedScalar& sigma () const inline
Definition at line 134 of file interfaceProperties.H.
sigmaK()
tmp<volScalarField> sigmaK () const inline
Definition at line 139 of file interfaceProperties.H.
References interfaceProperties::nearInterface(), and interfaceProperties::surfaceTensionForce().
Referenced by interfaceProperties::surfaceTensionForce().
surfaceTensionForce()
Foam::tmp< Foam::surfaceScalarField > surfaceTensionForce () const
Definition at line 212 of file interfaceProperties.C.
References Foam::fvc::interpolate(), interfaceProperties::sigmaK(), and Foam::fvc::snGrad().
Referenced by interfaceProperties::sigmaK().
nearInterface()
Foam::tmp< Foam::volScalarField > nearInterface () const
Indicator of the proximity of the interface.
Field values are 1 near and 0 away for the interface.
Definition at line 219 of file interfaceProperties.C.
References Foam::pos().
Referenced by interfaceProperties::sigmaK().
correct()
void correct () inline
Definition at line 150 of file interfaceProperties.H.
References interfaceProperties::read().
Referenced by immiscibleIncompressibleTwoPhaseMixture::correct().
read()
bool read ()
Read transportProperties dictionary.
Definition at line 225 of file interfaceProperties.C.
References lookup(), dictionary::lookup(), DimensionedField< Type, GeoMesh >::mesh(), and IOobject::name().
Referenced by interfaceProperties::correct(), and immiscibleIncompressibleTwoPhaseMixture::read().
Member Data Documentation
convertToRad
const Foam::scalar convertToRad static
Initial value:
=
    Foam::constant::mathematical::pi/180.0
Conversion factor for degrees into radians.
Definition at line 98 of file interfaceProperties.H.
The documentation for this class was generated from the following files:
src/transportModels/interfaceProperties/interfaceProperties.H
src/transportModels/interfaceProperties/interfaceProperties.C