OpenFOAM: thermophysicalFunction Class Reference
thermophysicalFunction Class Reference abstract
Abstract base class for thermo-physical functions.
Public Member Functions
TypeName ("thermophysicalFunction")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, thermophysicalFunction, Istream,(Istream &is),(is))
declareRunTimeSelectionTable (autoPtr, thermophysicalFunction, dictionary,(const dictionary &dict),(dict))
thermophysicalFunction ()
Construct null.
virtual ~thermophysicalFunction ()
Destructor.
virtual scalar f (scalar p, scalar T) const =0
Evaluate the function and return the result.
virtual void writeData (Ostream &os) const =0
Write the function coefficients.
Static Public Member Functions
static autoPtr< thermophysicalFunction > New (Istream &is)
Return pointer to new thermophysicalFunction created from input.
static autoPtr< thermophysicalFunction > New (const dictionary &dict)
Return pointer to new thermophysicalFunction created from dict.
Friends
Ostream & operator<< (Ostream &os, const thermophysicalFunction &f)
Detailed Description
Abstract base class for thermo-physical functions.
Definition at line 50 of file thermophysicalFunction.H.
Constructor & Destructor Documentation
thermophysicalFunction()
thermophysicalFunction () inline
Construct null.
Definition at line 83 of file thermophysicalFunction.H.
References thermophysicalFunction::New().
~thermophysicalFunction()
virtual ~thermophysicalFunction () inline virtual
Destructor.
Definition at line 94 of file thermophysicalFunction.H.
References thermophysicalFunction::f(), p, Foam::T(), and thermophysicalFunction::writeData().
Member Function Documentation
TypeName()
TypeName ("thermophysicalFunction")
Runtime type information.
declareRunTimeSelectionTable() [1/2]
declareRunTimeSelectionTable (autoPtr , thermophysicalFunction , Istream , (Istream &is) , (is))
declareRunTimeSelectionTable() [2/2]
declareRunTimeSelectionTable (autoPtr , thermophysicalFunction , dictionary , (const dictionary &dict) , (dict))
New() [1/2]
Foam::autoPtr< Foam::thermophysicalFunction > New (Istream & is) static
Return pointer to new thermophysicalFunction created from input.
Definition at line 42 of file thermophysicalFunction.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, InfoInFunction, and Foam::nl.
Referenced by thermophysicalFunction::thermophysicalFunction().
New() [2/2]
Foam::autoPtr< Foam::thermophysicalFunction > New (const dictionary & dict) static
Return pointer to new thermophysicalFunction created from dict.
Definition at line 74 of file thermophysicalFunction.C.
References Foam::abort(), dict, Foam::endl(), Foam::FatalError, FatalErrorInFunction, InfoInFunction, dictionary::lookup(), and Foam::nl.
f()
virtual scalar f (scalar p, scalar T) const pure virtual
Evaluate the function and return the result.
Implemented in NSRDSfunc0, NSRDSfunc6, NSRDSfunc1, NSRDSfunc14, NSRDSfunc4, NSRDSfunc7, NSRDSfunc2, NSRDSfunc3, NSRDSfunc5, and APIdiffCoefFunc.
Referenced by thermophysicalFunction::~thermophysicalFunction().
writeData()
virtual void writeData (Ostream & os) const pure virtual
Write the function coefficients.
Implemented in NSRDSfunc14, NSRDSfunc6, NSRDSfunc0, NSRDSfunc1, NSRDSfunc4, NSRDSfunc7, NSRDSfunc2, NSRDSfunc3, NSRDSfunc5, and APIdiffCoefFunc.
Referenced by thermophysicalFunction::~thermophysicalFunction().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & os, const thermophysicalFunction & f) friend
Definition at line 109 of file thermophysicalFunction.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/thermophysicalFunctions/thermophysicalFunction/thermophysicalFunction.H
src/thermophysicalModels/thermophysicalFunctions/thermophysicalFunction/thermophysicalFunction.C