OpenFOAM: constantAlphaContactAngleFvPatchScalarField Class Reference
constantAlphaContactAngleFvPatchScalarField Class Reference
A constant alphaContactAngle scalar boundary condition.
Public Member Functions
TypeName ("constantAlphaContactAngle")
Runtime type information.
constantAlphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
constantAlphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
constantAlphaContactAngleFvPatchScalarField (const constantAlphaContactAngleFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
constantAlphaContactAngleFvPatchScalarField (const constantAlphaContactAngleFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
constantAlphaContactAngleFvPatchScalarField (const constantAlphaContactAngleFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual tmp< scalarField > theta (const fvPatchVectorField &Up, const fvsPatchVectorField &nHat) const
Return the equilibrium contact-angle.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from alphaContactAngleFvPatchScalarField
TypeName ("alphaContactAngle")
Runtime type information.
alphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
alphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given alphaContactAngleFvPatchScalarField.
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &)
Construct as copy.
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual void evaluate (const Pstream::commsTypes commsType=Pstream::blocking)
Evaluate the patch field.
TypeName ("alphaContactAngle")
Runtime type information.
alphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
alphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given alphaContactAngleFvPatchScalarField.
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
const thetaPropsTable & thetaProps () const
Return the contact angle properties.
TypeName ("alphaContactAngle")
Runtime type information.
alphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
alphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given alphaContactAngleFvPatchScalarField.
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
const thetaPropsTable & thetaProps () const
Return the contact angle properties.
TypeName ("alphaContactAngle")
Runtime type information.
alphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
alphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given alphaContactAngleFvPatchScalarField.
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
const thetaPropsTable & thetaProps () const
Return the contact angle properties.
TypeName ("alphaContactAngle")
Runtime type information.
alphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
alphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given alphaContactAngleFvPatchScalarField.
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
const thetaPropsTable & thetaProps () const
Return the contact angle properties.
Additional Inherited Members
Public Types inherited from alphaContactAngleFvPatchScalarField
enum limitControls { lcNone, lcGradient, lcZeroGradient, lcAlpha }
Alpha limit options.
typedef HashTable< interfaceThetaProps, multiphaseMixtureThermo::interfacePair, multiphaseMixtureThermo::interfacePair::hash > thetaPropsTable
typedef HashTable< interfaceThetaProps, multiphaseSystem::interfacePair, multiphaseSystem::interfacePair::symmHash > thetaPropsTable
typedef HashTable< interfaceThetaProps, multiphaseMixture::interfacePair, multiphaseMixture::interfacePair::hash > thetaPropsTable
typedef HashTable< interfaceThetaProps, phasePairKey, phasePairKey::hash > thetaPropsTable
Public Attributes inherited from alphaContactAngleFvPatchScalarField
limitControls limit_
Static Public Attributes inherited from alphaContactAngleFvPatchScalarField
static const NamedEnum< limitControls, 4 > limitControlNames_
Detailed Description
A constant alphaContactAngle scalar boundary condition.
See also
Foam::alphaContactAngleFvPatchScalarField Foam::temperatureDependentAlphaContactAngleFvPatchScalarField
Source files
constantAlphaContactAngleFvPatchScalarField.H
constantAlphaContactAngleFvPatchScalarField.C
Definition at line 52 of file constantAlphaContactAngleFvPatchScalarField.H.
Constructor & Destructor Documentation
constantAlphaContactAngleFvPatchScalarField() [1/5]
constantAlphaContactAngleFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 35 of file constantAlphaContactAngleFvPatchScalarField.C.
Referenced by constantAlphaContactAngleFvPatchScalarField::clone(), and constantAlphaContactAngleFvPatchScalarField::constantAlphaContactAngleFvPatchScalarField().
constantAlphaContactAngleFvPatchScalarField() [2/5]
constantAlphaContactAngleFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 47 of file constantAlphaContactAngleFvPatchScalarField.C.
References constantAlphaContactAngleFvPatchScalarField::constantAlphaContactAngleFvPatchScalarField().
constantAlphaContactAngleFvPatchScalarField() [3/5]
constantAlphaContactAngleFvPatchScalarField (const constantAlphaContactAngleFvPatchScalarField & gcpsf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
constantAlphaContactAngleFvPatchScalarField onto a new patch
Definition at line 62 of file constantAlphaContactAngleFvPatchScalarField.C.
References constantAlphaContactAngleFvPatchScalarField::constantAlphaContactAngleFvPatchScalarField().
constantAlphaContactAngleFvPatchScalarField() [4/5]
constantAlphaContactAngleFvPatchScalarField (const constantAlphaContactAngleFvPatchScalarField & gcpsf)
Construct as copy.
Definition at line 76 of file constantAlphaContactAngleFvPatchScalarField.C.
References constantAlphaContactAngleFvPatchScalarField::constantAlphaContactAngleFvPatchScalarField().
constantAlphaContactAngleFvPatchScalarField() [5/5]
constantAlphaContactAngleFvPatchScalarField (const constantAlphaContactAngleFvPatchScalarField & gcpsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 87 of file constantAlphaContactAngleFvPatchScalarField.C.
References constantAlphaContactAngleFvPatchScalarField::theta().
Member Function Documentation
TypeName()
TypeName ("constantAlphaContactAngle")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Reimplemented from alphaContactAngleFvPatchScalarField.
Definition at line 103 of file constantAlphaContactAngleFvPatchScalarField.H.
References constantAlphaContactAngleFvPatchScalarField::constantAlphaContactAngleFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Reimplemented from alphaContactAngleFvPatchScalarField.
Definition at line 120 of file constantAlphaContactAngleFvPatchScalarField.H.
References constantAlphaContactAngleFvPatchScalarField::constantAlphaContactAngleFvPatchScalarField(), constantAlphaContactAngleFvPatchScalarField::theta(), and constantAlphaContactAngleFvPatchScalarField::write().
theta()
Foam::tmp< Foam::scalarField > theta (const fvPatchVectorField & Up, const fvsPatchVectorField & nHat) const virtual
Return the equilibrium contact-angle.
Implements alphaContactAngleFvPatchScalarField.
Definition at line 101 of file constantAlphaContactAngleFvPatchScalarField.C.
References scalarField(), and constantAlphaContactAngleFvPatchScalarField::write().
Referenced by constantAlphaContactAngleFvPatchScalarField::clone(), and constantAlphaContactAngleFvPatchScalarField::constantAlphaContactAngleFvPatchScalarField().
write()
void write (Ostream & os) const virtual
Write.
Reimplemented from alphaContactAngleFvPatchScalarField.
Definition at line 111 of file constantAlphaContactAngleFvPatchScalarField.C.
References Foam::makePatchTypeField(), Foam::nl, write(), and Ostream::writeKeyword().
Referenced by constantAlphaContactAngleFvPatchScalarField::clone(), and constantAlphaContactAngleFvPatchScalarField::theta().
The documentation for this class was generated from the following files:
src/transportModels/twoPhaseProperties/alphaContactAngle/constantAlphaContactAngle/constantAlphaContactAngleFvPatchScalarField.H
src/transportModels/twoPhaseProperties/alphaContactAngle/constantAlphaContactAngle/constantAlphaContactAngleFvPatchScalarField.C