OpenFOAM: alphaContactAngleFvPatchScalarField Class Reference
alphaContactAngleFvPatchScalarField Class Reference abstract
Boundary Conditions » Wall boundary ConditionsBoundary Conditions » | Generic boundary Conditions
Abstract base class for alphaContactAngle boundary conditions.
Classes
class interfaceThetaProps
Public Types
enum limitControls { lcNone, lcGradient, lcZeroGradient, lcAlpha }
Alpha limit options.
typedef HashTable< interfaceThetaProps, multiphaseMixtureThermo::interfacePair, multiphaseMixtureThermo::interfacePair::hash > thetaPropsTable
typedef HashTable< interfaceThetaProps, multiphaseSystem::interfacePair, multiphaseSystem::interfacePair::symmHash > thetaPropsTable
typedef HashTable< interfaceThetaProps, multiphaseMixture::interfacePair, multiphaseMixture::interfacePair::hash > thetaPropsTable
typedef HashTable< interfaceThetaProps, phasePairKey, phasePairKey::hash > thetaPropsTable
Public Member Functions
TypeName ("alphaContactAngle")
Runtime type information.
alphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
alphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given alphaContactAngleFvPatchScalarField.
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &)
Construct as copy.
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< scalarField > theta (const fvPatchVectorField &Up, const fvsPatchVectorField &nHat) const =0
Return the contact angle.
virtual void evaluate (const Pstream::commsTypes commsType=Pstream::blocking)
Evaluate the patch field.
virtual void write (Ostream &) const
Write.
TypeName ("alphaContactAngle")
Runtime type information.
alphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
alphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given alphaContactAngleFvPatchScalarField.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
const thetaPropsTable & thetaProps () const
Return the contact angle properties.
virtual void write (Ostream &) const
Write.
TypeName ("alphaContactAngle")
Runtime type information.
alphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
alphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given alphaContactAngleFvPatchScalarField.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
const thetaPropsTable & thetaProps () const
Return the contact angle properties.
virtual void write (Ostream &) const
Write.
TypeName ("alphaContactAngle")
Runtime type information.
alphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
alphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given alphaContactAngleFvPatchScalarField.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
const thetaPropsTable & thetaProps () const
Return the contact angle properties.
virtual void write (Ostream &) const
Write.
TypeName ("alphaContactAngle")
Runtime type information.
alphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
alphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given alphaContactAngleFvPatchScalarField.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
const thetaPropsTable & thetaProps () const
Return the contact angle properties.
virtual void write (Ostream &) const
Write.
Public Attributes
limitControls limit_
Static Public Attributes
static const NamedEnum< limitControls, 4 > limitControlNames_
Detailed Description
Abstract base class for alphaContactAngle boundary conditions.
Contact-angle boundary condition for multi-phase interface-capturing simulations. Used in conjuction with multiphaseSystem.
Contact-angle boundary condition for multi-phase interface-capturing simulations. Used in conjuction with multiphaseMixture.
Derived classes must implement the theta() fuction which returns the wall contact angle field.
The essential entry "limit" controls the gradient of alpha1 on the wall:
none - Calculate the gradient from the contact-angle without limiter
gradient - Limit the wall-gradient such that alpha1 remains bounded on the wall
alpha - Bound the calculated alpha1 on the wall
zeroGradient - Set the gradient of alpha1 to 0 on the wall, i.e. reproduce previous behaviour, the pressure BCs can be left as before.
Note that if any of the first three options are used the boundary condition on p_rgh must set to guarantee that the flux is corrected to be zero at the wall e.g.:
<patchName>
{
    type            alphaContactAngle;
    limit           none;
}
Source files
alphaContactAngleFvPatchScalarField.H
alphaContactAngleFvPatchScalarField.C
Source files
alphaContactAngleFvPatchScalarField.H
alphaContactAngleFvPatchScalarField.C
Source files
alphaContactAngleFvPatchScalarField.H
alphaContactAngleFvPatchScalarField.C
Source files
alphaContactAngleFvPatchScalarField.H
alphaContactAngleFvPatchScalarField.C
Source files
alphaContactAngleFvPatchScalarField.H
alphaContactAngleFvPatchScalarField.C
Definition at line 75 of file alphaContactAngleFvPatchScalarField.H.
Member Typedef Documentation
thetaPropsTable [1/4]
typedef HashTable< interfaceThetaProps, multiphaseMixtureThermo::interfacePair, multiphaseMixtureThermo::interfacePair::hash > thetaPropsTable
Definition at line 121 of file alphaContactAngleFvPatchScalarField.H.
thetaPropsTable [2/4]
typedef HashTable< interfaceThetaProps, multiphaseSystem::interfacePair, multiphaseSystem::interfacePair::symmHash > thetaPropsTable
Definition at line 121 of file alphaContactAngleFvPatchScalarField.H.
thetaPropsTable [3/4]
typedef HashTable< interfaceThetaProps, multiphaseMixture::interfacePair, multiphaseMixture::interfacePair::hash > thetaPropsTable
Definition at line 121 of file alphaContactAngleFvPatchScalarField.H.
thetaPropsTable [4/4]
typedef HashTable< interfaceThetaProps, phasePairKey, phasePairKey::hash > thetaPropsTable
Definition at line 121 of file alphaContactAngleFvPatchScalarField.H.
Member Enumeration Documentation
limitControls
enum limitControls
Alpha limit options.
Enumerator
lcNone
lcGradient
lcZeroGradient
lcAlpha
Definition at line 86 of file alphaContactAngleFvPatchScalarField.H.
Constructor & Destructor Documentation
alphaContactAngleFvPatchScalarField() [1/21]
alphaContactAngleFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 62 of file alphaContactAngleFvPatchScalarField.C.
Referenced by alphaContactAngleFvPatchScalarField::alphaContactAngleFvPatchScalarField(), alphaContactAngleFvPatchScalarField::clone(), and NamedEnum< directionType, 3 >::names().
alphaContactAngleFvPatchScalarField() [2/21]
alphaContactAngleFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 73 of file alphaContactAngleFvPatchScalarField.C.
References alphaContactAngleFvPatchScalarField::alphaContactAngleFvPatchScalarField(), dictionary::found(), fvPatchField< Type >::operator=(), and fvPatch::size().
alphaContactAngleFvPatchScalarField() [3/21]
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField & acpsf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given alphaContactAngleFvPatchScalarField.
onto a new patch
Definition at line 97 of file alphaContactAngleFvPatchScalarField.C.
References alphaContactAngleFvPatchScalarField::alphaContactAngleFvPatchScalarField().
alphaContactAngleFvPatchScalarField() [4/21]
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField & acpsf)
Construct as copy.
Definition at line 110 of file alphaContactAngleFvPatchScalarField.C.
References alphaContactAngleFvPatchScalarField::alphaContactAngleFvPatchScalarField().
alphaContactAngleFvPatchScalarField() [5/21]
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField & acpsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 120 of file alphaContactAngleFvPatchScalarField.C.
References alphaContactAngleFvPatchScalarField::evaluate().
alphaContactAngleFvPatchScalarField() [6/21]
alphaContactAngleFvPatchScalarField (const fvPatch & , const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
alphaContactAngleFvPatchScalarField() [7/21]
alphaContactAngleFvPatchScalarField (const fvPatch & , const DimensionedField< scalar, volMesh > & , const dictionary &)
Construct from patch, internal field and dictionary.
alphaContactAngleFvPatchScalarField() [8/21]
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField & , const fvPatch & , const DimensionedField< scalar, volMesh > & , const fvPatchFieldMapper &)
Construct by mapping given alphaContactAngleFvPatchScalarField.
onto a new patch
alphaContactAngleFvPatchScalarField() [9/21]
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField & , const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
alphaContactAngleFvPatchScalarField() [10/21]
alphaContactAngleFvPatchScalarField (const fvPatch & , const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
alphaContactAngleFvPatchScalarField() [11/21]
alphaContactAngleFvPatchScalarField (const fvPatch & , const DimensionedField< scalar, volMesh > & , const dictionary &)
Construct from patch, internal field and dictionary.
alphaContactAngleFvPatchScalarField() [12/21]
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField & , const fvPatch & , const DimensionedField< scalar, volMesh > & , const fvPatchFieldMapper &)
Construct by mapping given alphaContactAngleFvPatchScalarField.
onto a new patch
alphaContactAngleFvPatchScalarField() [13/21]
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField & , const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
alphaContactAngleFvPatchScalarField() [14/21]
alphaContactAngleFvPatchScalarField (const fvPatch & , const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
alphaContactAngleFvPatchScalarField() [15/21]
alphaContactAngleFvPatchScalarField (const fvPatch & , const DimensionedField< scalar, volMesh > & , const dictionary &)
Construct from patch, internal field and dictionary.
alphaContactAngleFvPatchScalarField() [16/21]
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField & , const fvPatch & , const DimensionedField< scalar, volMesh > & , const fvPatchFieldMapper &)
Construct by mapping given alphaContactAngleFvPatchScalarField.
onto a new patch
alphaContactAngleFvPatchScalarField() [17/21]
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField & , const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
alphaContactAngleFvPatchScalarField() [18/21]
alphaContactAngleFvPatchScalarField (const fvPatch & , const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
alphaContactAngleFvPatchScalarField() [19/21]
alphaContactAngleFvPatchScalarField (const fvPatch & , const DimensionedField< scalar, volMesh > & , const dictionary &)
Construct from patch, internal field and dictionary.
alphaContactAngleFvPatchScalarField() [20/21]
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField & , const fvPatch & , const DimensionedField< scalar, volMesh > & , const fvPatchFieldMapper &)
Construct by mapping given alphaContactAngleFvPatchScalarField.
onto a new patch
alphaContactAngleFvPatchScalarField() [21/21]
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField & , const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
Member Function Documentation
TypeName() [1/5]
TypeName ("alphaContactAngle")
Runtime type information.
theta()
virtual tmp<scalarField> theta (const fvPatchVectorField & Up, const fvsPatchVectorField & nHat) const pure virtual
Return the contact angle.
Implemented in temperatureDependentAlphaContactAngleFvPatchScalarField, dynamicAlphaContactAngleFvPatchScalarField, constantAlphaContactAngleFvPatchScalarField, and timeVaryingAlphaContactAngleFvPatchScalarField.
evaluate()
void evaluate (const Pstream::commsTypes commsType = Pstream::blocking) virtual
Evaluate the patch field.
Definition at line 133 of file alphaContactAngleFvPatchScalarField.C.
References Foam::max(), Foam::min(), Field< scalar >::operator=(), and alphaContactAngleFvPatchScalarField::write().
Referenced by alphaContactAngleFvPatchScalarField::alphaContactAngleFvPatchScalarField().
write() [1/5]
void write (Ostream & os) const virtual
Write.
Reimplemented in temperatureDependentAlphaContactAngleFvPatchScalarField, dynamicAlphaContactAngleFvPatchScalarField, constantAlphaContactAngleFvPatchScalarField, and timeVaryingAlphaContactAngleFvPatchScalarField.
Definition at line 164 of file alphaContactAngleFvPatchScalarField.C.
References token::END_STATEMENT, Foam::nl, write(), and Ostream::writeKeyword().
Referenced by alphaContactAngleFvPatchScalarField::evaluate(), alphaContactAngleFvPatchScalarField::thetaProps(), and dynamicAlphaContactAngleFvPatchScalarField::write().
TypeName() [2/5]
TypeName ("alphaContactAngle")
Runtime type information.
clone() [1/8]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Reimplemented in temperatureDependentAlphaContactAngleFvPatchScalarField, dynamicAlphaContactAngleFvPatchScalarField, constantAlphaContactAngleFvPatchScalarField, and timeVaryingAlphaContactAngleFvPatchScalarField.
Definition at line 165 of file alphaContactAngleFvPatchScalarField.H.
References alphaContactAngleFvPatchScalarField::alphaContactAngleFvPatchScalarField().
Referenced by alphaContactAngleFvPatchScalarField::clone().
clone() [2/8]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Reimplemented in temperatureDependentAlphaContactAngleFvPatchScalarField, dynamicAlphaContactAngleFvPatchScalarField, constantAlphaContactAngleFvPatchScalarField, and timeVaryingAlphaContactAngleFvPatchScalarField.
Definition at line 182 of file alphaContactAngleFvPatchScalarField.H.
References alphaContactAngleFvPatchScalarField::alphaContactAngleFvPatchScalarField().
thetaProps() [1/4]
const thetaPropsTable& thetaProps () const inline
Return the contact angle properties.
Definition at line 196 of file alphaContactAngleFvPatchScalarField.H.
References alphaContactAngleFvPatchScalarField::write().
write() [2/5]
virtual void write (Ostream &) const virtual
Write.
Reimplemented in temperatureDependentAlphaContactAngleFvPatchScalarField, dynamicAlphaContactAngleFvPatchScalarField, constantAlphaContactAngleFvPatchScalarField, and timeVaryingAlphaContactAngleFvPatchScalarField.
TypeName() [3/5]
TypeName ("alphaContactAngle")
Runtime type information.
clone() [3/8]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Reimplemented in temperatureDependentAlphaContactAngleFvPatchScalarField, dynamicAlphaContactAngleFvPatchScalarField, constantAlphaContactAngleFvPatchScalarField, and timeVaryingAlphaContactAngleFvPatchScalarField.
Definition at line 165 of file alphaContactAngleFvPatchScalarField.H.
References alphaContactAngleFvPatchScalarField::alphaContactAngleFvPatchScalarField(), and alphaContactAngleFvPatchScalarField::clone().
clone() [4/8]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Reimplemented in temperatureDependentAlphaContactAngleFvPatchScalarField, dynamicAlphaContactAngleFvPatchScalarField, constantAlphaContactAngleFvPatchScalarField, and timeVaryingAlphaContactAngleFvPatchScalarField.
Definition at line 182 of file alphaContactAngleFvPatchScalarField.H.
References alphaContactAngleFvPatchScalarField::alphaContactAngleFvPatchScalarField().
thetaProps() [2/4]
const thetaPropsTable& thetaProps () const inline
Return the contact angle properties.
Definition at line 196 of file alphaContactAngleFvPatchScalarField.H.
References alphaContactAngleFvPatchScalarField::write().
write() [3/5]
virtual void write (Ostream &) const virtual
Write.
Reimplemented in temperatureDependentAlphaContactAngleFvPatchScalarField, dynamicAlphaContactAngleFvPatchScalarField, constantAlphaContactAngleFvPatchScalarField, and timeVaryingAlphaContactAngleFvPatchScalarField.
TypeName() [4/5]
TypeName ("alphaContactAngle")
Runtime type information.
clone() [5/8]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Reimplemented in temperatureDependentAlphaContactAngleFvPatchScalarField, dynamicAlphaContactAngleFvPatchScalarField, constantAlphaContactAngleFvPatchScalarField, and timeVaryingAlphaContactAngleFvPatchScalarField.
Definition at line 165 of file alphaContactAngleFvPatchScalarField.H.
References alphaContactAngleFvPatchScalarField::alphaContactAngleFvPatchScalarField(), and alphaContactAngleFvPatchScalarField::clone().
clone() [6/8]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Reimplemented in temperatureDependentAlphaContactAngleFvPatchScalarField, dynamicAlphaContactAngleFvPatchScalarField, constantAlphaContactAngleFvPatchScalarField, and timeVaryingAlphaContactAngleFvPatchScalarField.
Definition at line 182 of file alphaContactAngleFvPatchScalarField.H.
References alphaContactAngleFvPatchScalarField::alphaContactAngleFvPatchScalarField().
thetaProps() [3/4]
const thetaPropsTable& thetaProps () const inline
Return the contact angle properties.
Definition at line 196 of file alphaContactAngleFvPatchScalarField.H.
References alphaContactAngleFvPatchScalarField::write().
write() [4/5]
virtual void write (Ostream &) const virtual
Write.
Reimplemented in temperatureDependentAlphaContactAngleFvPatchScalarField, dynamicAlphaContactAngleFvPatchScalarField, constantAlphaContactAngleFvPatchScalarField, and timeVaryingAlphaContactAngleFvPatchScalarField.
TypeName() [5/5]
TypeName ("alphaContactAngle")
Runtime type information.
clone() [7/8]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Reimplemented in temperatureDependentAlphaContactAngleFvPatchScalarField, dynamicAlphaContactAngleFvPatchScalarField, constantAlphaContactAngleFvPatchScalarField, and timeVaryingAlphaContactAngleFvPatchScalarField.
Definition at line 165 of file alphaContactAngleFvPatchScalarField.H.
References alphaContactAngleFvPatchScalarField::alphaContactAngleFvPatchScalarField(), and alphaContactAngleFvPatchScalarField::clone().
clone() [8/8]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Reimplemented in temperatureDependentAlphaContactAngleFvPatchScalarField, dynamicAlphaContactAngleFvPatchScalarField, constantAlphaContactAngleFvPatchScalarField, and timeVaryingAlphaContactAngleFvPatchScalarField.
Definition at line 182 of file alphaContactAngleFvPatchScalarField.H.
References alphaContactAngleFvPatchScalarField::alphaContactAngleFvPatchScalarField().
thetaProps() [4/4]
const thetaPropsTable& thetaProps () const inline
Return the contact angle properties.
Definition at line 196 of file alphaContactAngleFvPatchScalarField.H.
References alphaContactAngleFvPatchScalarField::write().
write() [5/5]
virtual void write (Ostream &) const virtual
Write.
Reimplemented in temperatureDependentAlphaContactAngleFvPatchScalarField, dynamicAlphaContactAngleFvPatchScalarField, constantAlphaContactAngleFvPatchScalarField, and timeVaryingAlphaContactAngleFvPatchScalarField.
Member Data Documentation
limitControlNames_
const Foam::NamedEnum< Foam::alphaContactAngleFvPatchScalarField::limitControls, 4 > limitControlNames_ static
Definition at line 94 of file alphaContactAngleFvPatchScalarField.H.
Referenced by NamedEnum< directionType, 3 >::names().
limit_
limitControls limit_
Definition at line 95 of file alphaContactAngleFvPatchScalarField.H.
The documentation for this class was generated from the following files:
src/transportModels/twoPhaseProperties/alphaContactAngle/alphaContactAngle/alphaContactAngleFvPatchScalarField.H
src/transportModels/twoPhaseProperties/alphaContactAngle/alphaContactAngle/alphaContactAngleFvPatchScalarField.C