OpenFOAM: viscosityModel Class Reference
viscosityModel Class Reference abstract
An abstract base class for incompressible viscosityModels.
Public Member Functions
TypeName ("viscosityModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, viscosityModel, dictionary,(const word &name, const dictionary &viscosityProperties, const volVectorField &U, const surfaceScalarField &phi),(name, viscosityProperties, U, phi))
viscosityModel (const word &name, const dictionary &viscosityProperties, const volVectorField &U, const surfaceScalarField &phi)
Construct from components.
virtual ~viscosityModel ()
Destructor.
const dictionary & viscosityProperties () const
Return the phase transport properties dictionary.
tmp< volScalarField > strainRate () const
Return the strain rate.
virtual tmp< volScalarField > nu () const =0
Return the laminar viscosity.
virtual tmp< scalarField > nu (const label patchi) const =0
Return the laminar viscosity for patch.
virtual void correct ()=0
Correct the laminar viscosity.
virtual bool read (const dictionary &viscosityProperties)=0
Read transportProperties dictionary.
Static Public Member Functions
static autoPtr< viscosityModel > New (const word &name, const dictionary &viscosityProperties, const volVectorField &U, const surfaceScalarField &phi)
Return a reference to the selected viscosity model.
Protected Member Functions
viscosityModel (const viscosityModel &)
Disallow copy construct.
void operator= (const viscosityModel &)
Disallow default bitwise assignment.
Protected Attributes
word name_
dictionary viscosityProperties_
const volVectorField & U_
const surfaceScalarField & phi_
Detailed Description
An abstract base class for incompressible viscosityModels.
The strain rate is defined by:
mag(symm(grad(U)))
Source files
viscosityModel.H
viscosityModel.C
viscosityModelNew.C
Source files
viscosityModel.H
viscosityModel.C
Source files
viscosityModel.H
viscosityModel.C
Definition at line 64 of file viscosityModel.H.
Constructor & Destructor Documentation
viscosityModel() [1/2]
viscosityModel (const viscosityModel &) protected
Disallow copy construct.
viscosityModel() [2/2]
viscosityModel (const word & name, const dictionary & viscosityProperties, const volVectorField & U, const surfaceScalarField & phi)
Construct from components.
Definition at line 42 of file viscosityModel.C.
~viscosityModel()
virtual ~viscosityModel () inline virtual
Destructor.
Definition at line 135 of file viscosityModel.H.
Member Function Documentation
operator=()
void operator= (const viscosityModel &) protected
Disallow default bitwise assignment.
TypeName()
TypeName ("viscosityModel")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , viscosityModel , dictionary , (const word &name, const dictionary &viscosityProperties, const volVectorField &U, const surfaceScalarField &phi) , (name, viscosityProperties, U, phi))
New()
Foam::autoPtr< Foam::viscosityModel > New (const word & name, const dictionary & viscosityProperties, const volVectorField & U, const surfaceScalarField & phi) static
Return a reference to the selected viscosity model.
Definition at line 33 of file viscosityModelNew.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::Info, dictionary::lookup(), Foam::name(), Foam::nl, phi, and U.
viscosityProperties()
const dictionary& viscosityProperties () const inline
Return the phase transport properties dictionary.
Definition at line 142 of file viscosityModel.H.
References viscosityModel::correct(), viscosityModel::nu(), patchi, viscosityModel::read(), viscosityModel::strainRate(), and viscosityModel::viscosityProperties_.
strainRate()
Foam::tmp< Foam::volScalarField > strainRate () const
Return the strain rate.
Definition at line 58 of file viscosityModel.C.
References Foam::fvc::grad(), Foam::mag(), Foam::sqrt(), and Foam::symm().
Referenced by viscosityModel::viscosityProperties().
nu() [1/2]
virtual tmp<volScalarField> nu () const pure virtual
Return the laminar viscosity.
Implemented in Casson, BirdCarreau, HerschelBulkley, powerLaw, CrossPowerLaw, and Newtonian.
Referenced by viscosityModel::viscosityProperties().
nu() [2/2]
virtual tmp<scalarField> nu (const label patchi) const pure virtual
Return the laminar viscosity for patch.
Implemented in Casson, BirdCarreau, HerschelBulkley, powerLaw, CrossPowerLaw, and Newtonian.
correct()
virtual void correct () pure virtual
Correct the laminar viscosity.
Implemented in Casson, BirdCarreau, HerschelBulkley, powerLaw, CrossPowerLaw, and Newtonian.
Referenced by viscosityModel::viscosityProperties().
read()
bool read (const dictionary & viscosityProperties) pure virtual
Read transportProperties dictionary.
Implemented in Casson, BirdCarreau, HerschelBulkley, powerLaw, CrossPowerLaw, and Newtonian.
Definition at line 64 of file viscosityModel.C.
Referenced by Newtonian::read(), CrossPowerLaw::read(), powerLaw::read(), HerschelBulkley::read(), BirdCarreau::read(), Casson::read(), and viscosityModel::viscosityProperties().
Member Data Documentation
name_
word name_ protected
Definition at line 71 of file viscosityModel.H.
viscosityProperties_
dictionary viscosityProperties_ protected
Definition at line 72 of file viscosityModel.H.
Referenced by viscosityModel::viscosityProperties().
U_
const volVectorField& U_ protected
Definition at line 74 of file viscosityModel.H.
phi_
const surfaceScalarField& phi_ protected
Definition at line 75 of file viscosityModel.H.
The documentation for this class was generated from the following files:
src/transportModels/incompressible/viscosityModels/viscosityModel/viscosityModel.H
src/transportModels/incompressible/viscosityModels/viscosityModel/viscosityModel.C
src/transportModels/incompressible/viscosityModels/viscosityModel/viscosityModelNew.C