OpenFOAM: temperatureDependentAlphaContactAngleFvPatchScalarField Class Reference
temperatureDependentAlphaContactAngleFvPatchScalarField Class Reference
Temperature-dependent constant alphaContactAngle scalar boundary condition.
Public Member Functions
TypeName ("temperatureDependentAlphaContactAngle")
Runtime type information.
temperatureDependentAlphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
temperatureDependentAlphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
temperatureDependentAlphaContactAngleFvPatchScalarField (const temperatureDependentAlphaContactAngleFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
temperatureDependentAlphaContactAngleFvPatchScalarField (const temperatureDependentAlphaContactAngleFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
temperatureDependentAlphaContactAngleFvPatchScalarField (const temperatureDependentAlphaContactAngleFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual tmp< scalarField > theta (const fvPatchVectorField &Up, const fvsPatchVectorField &nHat) const
Return the equilibrium contact-angle.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from alphaContactAngleFvPatchScalarField
TypeName ("alphaContactAngle")
Runtime type information.
alphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
alphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given alphaContactAngleFvPatchScalarField.
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &)
Construct as copy.
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual void evaluate (const Pstream::commsTypes commsType=Pstream::blocking)
Evaluate the patch field.
TypeName ("alphaContactAngle")
Runtime type information.
alphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
alphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given alphaContactAngleFvPatchScalarField.
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
const thetaPropsTable & thetaProps () const
Return the contact angle properties.
TypeName ("alphaContactAngle")
Runtime type information.
alphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
alphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given alphaContactAngleFvPatchScalarField.
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
const thetaPropsTable & thetaProps () const
Return the contact angle properties.
TypeName ("alphaContactAngle")
Runtime type information.
alphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
alphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given alphaContactAngleFvPatchScalarField.
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
const thetaPropsTable & thetaProps () const
Return the contact angle properties.
TypeName ("alphaContactAngle")
Runtime type information.
alphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
alphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given alphaContactAngleFvPatchScalarField.
alphaContactAngleFvPatchScalarField (const alphaContactAngleFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
const thetaPropsTable & thetaProps () const
Return the contact angle properties.
Additional Inherited Members
Public Types inherited from alphaContactAngleFvPatchScalarField
enum limitControls { lcNone, lcGradient, lcZeroGradient, lcAlpha }
Alpha limit options.
typedef HashTable< interfaceThetaProps, multiphaseMixtureThermo::interfacePair, multiphaseMixtureThermo::interfacePair::hash > thetaPropsTable
typedef HashTable< interfaceThetaProps, multiphaseSystem::interfacePair, multiphaseSystem::interfacePair::symmHash > thetaPropsTable
typedef HashTable< interfaceThetaProps, multiphaseMixture::interfacePair, multiphaseMixture::interfacePair::hash > thetaPropsTable
typedef HashTable< interfaceThetaProps, phasePairKey, phasePairKey::hash > thetaPropsTable
Public Attributes inherited from alphaContactAngleFvPatchScalarField
limitControls limit_
Static Public Attributes inherited from alphaContactAngleFvPatchScalarField
static const NamedEnum< limitControls, 4 > limitControlNames_
Detailed Description
Temperature-dependent constant alphaContactAngle scalar boundary condition.
Usage
Property Description Required Default value
T Temperature field name no T
theta0 Contact angle data yes
Example of the boundary condition specification:
    <patchName>
    {
        type            temperatureDependentAlphaContactAngle;
        theta0          constant 60;
    }
See also
Foam::alphaContactAngleFvPatchScalarField Foam::constantAlphaContactAngleFvPatchScalarField
Source files
temperatureDependentAlphaContactAngleFvPatchScalarField.H
temperatureDependentAlphaContactAngleFvPatchScalarField.C
Definition at line 84 of file temperatureDependentAlphaContactAngleFvPatchScalarField.H.
Constructor & Destructor Documentation
temperatureDependentAlphaContactAngleFvPatchScalarField() [1/5]
temperatureDependentAlphaContactAngleFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 35 of file temperatureDependentAlphaContactAngleFvPatchScalarField.C.
Referenced by temperatureDependentAlphaContactAngleFvPatchScalarField::clone(), and temperatureDependentAlphaContactAngleFvPatchScalarField::temperatureDependentAlphaContactAngleFvPatchScalarField().
temperatureDependentAlphaContactAngleFvPatchScalarField() [2/5]
temperatureDependentAlphaContactAngleFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 48 of file temperatureDependentAlphaContactAngleFvPatchScalarField.C.
References temperatureDependentAlphaContactAngleFvPatchScalarField::temperatureDependentAlphaContactAngleFvPatchScalarField().
temperatureDependentAlphaContactAngleFvPatchScalarField() [3/5]
temperatureDependentAlphaContactAngleFvPatchScalarField (const temperatureDependentAlphaContactAngleFvPatchScalarField & psf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
temperatureDependentAlphaContactAngleFvPatchScalarField onto a new patch
Definition at line 64 of file temperatureDependentAlphaContactAngleFvPatchScalarField.C.
References temperatureDependentAlphaContactAngleFvPatchScalarField::temperatureDependentAlphaContactAngleFvPatchScalarField().
temperatureDependentAlphaContactAngleFvPatchScalarField() [4/5]
temperatureDependentAlphaContactAngleFvPatchScalarField (const temperatureDependentAlphaContactAngleFvPatchScalarField & psf)
Construct as copy.
Definition at line 79 of file temperatureDependentAlphaContactAngleFvPatchScalarField.C.
References temperatureDependentAlphaContactAngleFvPatchScalarField::temperatureDependentAlphaContactAngleFvPatchScalarField().
temperatureDependentAlphaContactAngleFvPatchScalarField() [5/5]
temperatureDependentAlphaContactAngleFvPatchScalarField (const temperatureDependentAlphaContactAngleFvPatchScalarField & psf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 91 of file temperatureDependentAlphaContactAngleFvPatchScalarField.C.
References temperatureDependentAlphaContactAngleFvPatchScalarField::theta().
Member Function Documentation
TypeName()
TypeName ("temperatureDependentAlphaContactAngle")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Reimplemented from alphaContactAngleFvPatchScalarField.
Definition at line 138 of file temperatureDependentAlphaContactAngleFvPatchScalarField.H.
References temperatureDependentAlphaContactAngleFvPatchScalarField::temperatureDependentAlphaContactAngleFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Reimplemented from alphaContactAngleFvPatchScalarField.
Definition at line 158 of file temperatureDependentAlphaContactAngleFvPatchScalarField.H.
References temperatureDependentAlphaContactAngleFvPatchScalarField::temperatureDependentAlphaContactAngleFvPatchScalarField(), temperatureDependentAlphaContactAngleFvPatchScalarField::theta(), and temperatureDependentAlphaContactAngleFvPatchScalarField::write().
theta()
Foam::tmp< Foam::scalarField > theta (const fvPatchVectorField & Up, const fvsPatchVectorField & nHat) const virtual
Return the equilibrium contact-angle.
Implements alphaContactAngleFvPatchScalarField.
Definition at line 106 of file temperatureDependentAlphaContactAngleFvPatchScalarField.C.
References temperatureDependentAlphaContactAngleFvPatchScalarField::write().
Referenced by temperatureDependentAlphaContactAngleFvPatchScalarField::clone(), and temperatureDependentAlphaContactAngleFvPatchScalarField::temperatureDependentAlphaContactAngleFvPatchScalarField().
write()
void write (Ostream & os) const virtual
Write.
Reimplemented from alphaContactAngleFvPatchScalarField.
Definition at line 119 of file temperatureDependentAlphaContactAngleFvPatchScalarField.C.
References Foam::makePatchTypeField(), and write().
Referenced by temperatureDependentAlphaContactAngleFvPatchScalarField::clone(), and temperatureDependentAlphaContactAngleFvPatchScalarField::theta().
The documentation for this class was generated from the following files:
src/transportModels/twoPhaseProperties/alphaContactAngle/temperatureDependentAlphaContactAngle/temperatureDependentAlphaContactAngleFvPatchScalarField.H
src/transportModels/twoPhaseProperties/alphaContactAngle/temperatureDependentAlphaContactAngle/temperatureDependentAlphaContactAngleFvPatchScalarField.C