OpenFOAM: EddyDiffusivity< BasicTurbulenceModel > Class Template Reference
EddyDiffusivity< BasicTurbulenceModel > Class Template Reference
Templated abstract base class for single-phase compressible turbulence models.
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
EddyDiffusivity (const word &type, const alphaField &alpha, const volScalarField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &trasport, const word &propertiesName)
Construct.
virtual ~EddyDiffusivity ()
Destructor.
virtual bool read ()
Re-read model coefficients if they have changed.
virtual tmp< volScalarField > alphat () const
Return the turbulent thermal diffusivity for enthalpy [kg/m/s].
virtual tmp< scalarField > alphat (const label patchi) const
Return the turbulent thermal diffusivity for enthalpy for a patch.
virtual tmp< volScalarField > kappaEff () const
Return the effective turbulent thermal diffusivity for temperature.
virtual tmp< scalarField > kappaEff (const label patchi) const
Return the effective turbulent thermal diffusivity for temperature.
virtual tmp< volScalarField > alphaEff () const
Return the effective turbulent thermal diffusivity for enthalpy.
virtual tmp< scalarField > alphaEff (const label patchi) const
Return the effective turbulent thermal diffusivity for enthalpy.
virtual void correctEnergyTransport ()
Correct the turbulence thermal diffusivity for energy transport.
Protected Member Functions
virtual void correctNut ()
Protected Attributes
dimensionedScalar Prt_
volScalarField alphat_
Detailed Description
template<class BasicTurbulenceModel>
class Foam::EddyDiffusivity< BasicTurbulenceModel >
Templated abstract base class for single-phase compressible turbulence models.
Source files
EddyDiffusivity.H
EddyDiffusivity.C
Definition at line 48 of file EddyDiffusivity.H.
Member Typedef Documentation
alphaField
typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 73 of file EddyDiffusivity.H.
rhoField
typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 74 of file EddyDiffusivity.H.
transportModel
typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 75 of file EddyDiffusivity.H.
Constructor & Destructor Documentation
EddyDiffusivity()
EddyDiffusivity (const word & type, const alphaField & alpha, const volScalarField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & trasport, const word & propertiesName)
Construct.
Definition at line 50 of file EddyDiffusivity.C.
Referenced by EddyDiffusivity< compressible::turbulenceModel >::correctNut().
~EddyDiffusivity()
virtual ~EddyDiffusivity () inline virtual
Destructor.
Definition at line 95 of file EddyDiffusivity.H.
Member Function Documentation
correctNut()
void correctNut () protected virtual
Reimplemented in kEpsilon< EddyDiffusivity< compressible::turbulenceModel > >, eddyViscosity< RASModel< EddyDiffusivity< ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > > > > >, eddyViscosity< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >, and eddyViscosity< RASModel< EddyDiffusivity< compressible::turbulenceModel > > >.
Definition at line 31 of file EddyDiffusivity.C.
read()
bool read () virtual
Re-read model coefficients if they have changed.
Reimplemented in kineticTheoryModel, kineticTheoryModel, RASModel< EddyDiffusivity< ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > > > >, RASModel< EddyDiffusivity< compressible::turbulenceModel > >, RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > >, kEpsilon< EddyDiffusivity< compressible::turbulenceModel > >, phasePressureModel, phasePressureModel, PDRkEpsilon, eddyViscosity< RASModel< EddyDiffusivity< ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > > > > >, eddyViscosity< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >, eddyViscosity< RASModel< EddyDiffusivity< compressible::turbulenceModel > > >, linearViscousStress< RASModel< EddyDiffusivity< ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > > > > >, linearViscousStress< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >, and linearViscousStress< RASModel< EddyDiffusivity< compressible::turbulenceModel > > >.
Definition at line 94 of file EddyDiffusivity.C.
Referenced by EddyDiffusivity< compressible::turbulenceModel >::~EddyDiffusivity().
alphat() [1/2]
virtual tmp<volScalarField> alphat () const inline virtual
Return the turbulent thermal diffusivity for enthalpy [kg/m/s].
Definition at line 105 of file EddyDiffusivity.H.
Referenced by EddyDiffusivity< compressible::turbulenceModel >::alphat().
alphat() [2/2]
virtual tmp<scalarField> alphat (const label patchi) const inline virtual
Return the turbulent thermal diffusivity for enthalpy for a patch.
[kg/m/s]
Definition at line 112 of file EddyDiffusivity.H.
kappaEff() [1/2]
virtual tmp<volScalarField> kappaEff () const inline virtual
Return the effective turbulent thermal diffusivity for temperature.
[J/m/s/K]
Definition at line 119 of file EddyDiffusivity.H.
Referenced by EddyDiffusivity< compressible::turbulenceModel >::alphat().
kappaEff() [2/2]
virtual tmp<scalarField> kappaEff (const label patchi) const inline virtual
Return the effective turbulent thermal diffusivity for temperature.
[J/m/s/K]
Definition at line 126 of file EddyDiffusivity.H.
alphaEff() [1/2]
virtual tmp<volScalarField> alphaEff () const inline virtual
Return the effective turbulent thermal diffusivity for enthalpy.
[kg/m/s]
Definition at line 133 of file EddyDiffusivity.H.
Referenced by EddyDiffusivity< compressible::turbulenceModel >::alphat().
alphaEff() [2/2]
virtual tmp<scalarField> alphaEff (const label patchi) const inline virtual
Return the effective turbulent thermal diffusivity for enthalpy.
for a patch [kg/m/s]
Definition at line 140 of file EddyDiffusivity.H.
correctEnergyTransport()
void correctEnergyTransport () virtual
Correct the turbulence thermal diffusivity for energy transport.
Definition at line 110 of file EddyDiffusivity.C.
Referenced by EddyDiffusivity< compressible::turbulenceModel >::alphat().
Member Data Documentation
Prt_
dimensionedScalar Prt_ protected
Definition at line 59 of file EddyDiffusivity.H.
alphat_
volScalarField alphat_ protected
Definition at line 63 of file EddyDiffusivity.H.
Referenced by EddyDiffusivity< compressible::turbulenceModel >::alphat().
The documentation for this class was generated from the following files:
src/TurbulenceModels/compressible/EddyDiffusivity/EddyDiffusivity.H
src/TurbulenceModels/compressible/EddyDiffusivity/EddyDiffusivity.C