OpenFOAM: geometricSurfacePatch Class Reference
geometricSurfacePatch Class Reference
The geometricSurfacePatch is like patchIdentifier but for surfaces. Holds type, name and index.
Public Member Functions
ClassName ("geometricSurfacePatch")
Runtime type information.
geometricSurfacePatch ()
Construct null.
geometricSurfacePatch (const word &geometricType, const word &name, const label index)
Construct from components.
geometricSurfacePatch (Istream &, const label index)
Construct from Istream.
geometricSurfacePatch (const word &name, const dictionary &dict, const label index)
Construct from dictionary.
const word & name () const
Return name.
word & name ()
Return name.
const word & geometricType () const
Return the type of the patch.
word & geometricType ()
Return the type of the patch.
label index () const
Return the index of this patch in the boundaryMesh.
label & index ()
Return the index of this patch in the boundaryMesh.
void write (Ostream &) const
Write.
void writeDict (Ostream &) const
Write dictionary.
bool operator!= (const geometricSurfacePatch &) const
bool operator== (const geometricSurfacePatch &) const
compare.
Friends
Ostream & operator<< (Ostream &, const geometricSurfacePatch &)
Istream & operator>> (Istream &, geometricSurfacePatch &)
Detailed Description
The geometricSurfacePatch is like patchIdentifier but for surfaces. Holds type, name and index.
Source files
geometricSurfacePatch.H
geometricSurfacePatch.C
Definition at line 53 of file geometricSurfacePatch.H.
Constructor & Destructor Documentation
geometricSurfacePatch() [1/4]
geometricSurfacePatch ()
Construct null.
Definition at line 41 of file geometricSurfacePatch.C.
Referenced by geometricSurfacePatch::geometricSurfacePatch().
geometricSurfacePatch() [2/4]
geometricSurfacePatch (const word & geometricType, const word & name, const label index)
Construct from components.
Definition at line 51 of file geometricSurfacePatch.C.
geometricSurfacePatch() [3/4]
geometricSurfacePatch (Istream & is, const label index)
Construct from Istream.
Definition at line 70 of file geometricSurfacePatch.C.
References geometricSurfacePatch::geometricSurfacePatch().
geometricSurfacePatch() [4/4]
geometricSurfacePatch (const word & name, const dictionary & dict, const label index)
Construct from dictionary.
Definition at line 85 of file geometricSurfacePatch.C.
Member Function Documentation
ClassName()
ClassName ("geometricSurfacePatch")
Runtime type information.
name() [1/2]
const word& name () const inline
Return name.
Definition at line 100 of file geometricSurfacePatch.H.
Referenced by triSurface::checkEdges(), geometricSurfacePatch::operator==(), boundaryMesh::readTriSurface(), and surfacePatch::writeDict().
name() [2/2]
word& name () inline
Return name.
Definition at line 106 of file geometricSurfacePatch.H.
geometricType() [1/2]
const word& geometricType () const inline
Return the type of the patch.
Definition at line 112 of file geometricSurfacePatch.H.
Referenced by triSurface::checkEdges(), surfacePatch::operator==(), geometricSurfacePatch::operator==(), and boundaryMesh::readTriSurface().
geometricType() [2/2]
word& geometricType () inline
Return the type of the patch.
Definition at line 118 of file geometricSurfacePatch.H.
index() [1/2]
label index () const inline
Return the index of this patch in the boundaryMesh.
Definition at line 124 of file geometricSurfacePatch.H.
Referenced by triSurface::checkEdges().
index() [2/2]
label& index () inline
Return the index of this patch in the boundaryMesh.
Definition at line 130 of file geometricSurfacePatch.H.
References geometricSurfacePatch::operator!=(), geometricSurfacePatch::operator<<, geometricSurfacePatch::operator==(), geometricSurfacePatch::operator>>, geometricSurfacePatch::write(), and geometricSurfacePatch::writeDict().
write()
void write (Ostream & os) const
Write.
Definition at line 105 of file geometricSurfacePatch.C.
References Foam::nl.
Referenced by geometricSurfacePatch::index(), and Foam::operator<<().
writeDict()
void writeDict (Ostream & os) const
Write dictionary.
Definition at line 112 of file geometricSurfacePatch.C.
References Foam::nl.
Referenced by geometricSurfacePatch::index(), and surfacePatch::writeDict().
operator!=()
bool operator!= (const geometricSurfacePatch & p) const
Definition at line 120 of file geometricSurfacePatch.C.
References p.
Referenced by geometricSurfacePatch::index().
operator==()
bool operator== (const geometricSurfacePatch & p) const
compare.
Definition at line 127 of file geometricSurfacePatch.C.
References geometricSurfacePatch::geometricType(), and geometricSurfacePatch::name().
Referenced by geometricSurfacePatch::index().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & os, const geometricSurfacePatch & gp) friend
Definition at line 148 of file geometricSurfacePatch.C.
Referenced by geometricSurfacePatch::index().
operator>>
Istream& operator>> (Istream & is, geometricSurfacePatch & gp) friend
Definition at line 140 of file geometricSurfacePatch.C.
Referenced by geometricSurfacePatch::index().
The documentation for this class was generated from the following files:
src/triSurface/triSurface/geometricSurfacePatch/geometricSurfacePatch.H
src/triSurface/triSurface/geometricSurfacePatch/geometricSurfacePatch.C