OpenFOAM: buoyantKEpsilon< BasicTurbulenceModel > Class Template Reference
buoyantKEpsilon< BasicTurbulenceModel > Class Template Reference
Turbulence » RAS turbulence
Additional buoyancy generation/dissipation term applied to the k and epsilon equations of the standard k-epsilon model.
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from kEpsilon< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
typedef RASModel< BasicTurbulenceModel > ::alphaField alphaField
typedef RASModel< BasicTurbulenceModel > ::rhoField rhoField
typedef RASModel< BasicTurbulenceModel > ::transportModel transportModel
Public Types inherited from linearViscousStress< RASModel< BasicTurbulenceModel > >
typedef RASModel< BasicTurbulenceModel > ::alphaField alphaField
typedef RASModel< BasicTurbulenceModel > ::rhoField rhoField
typedef RASModel< BasicTurbulenceModel > ::transportModel transportModel
Public Types inherited from RASModel< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("buoyantKEpsilon")
Runtime type information.
buoyantKEpsilon (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
Construct from components.
virtual ~buoyantKEpsilon ()
Destructor.
virtual bool read ()
Re-read model coefficients if they have changed.
Public Member Functions inherited from kEpsilon< BasicTurbulenceModel >
TypeName ("kEpsilon")
Runtime type information.
kEpsilon (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
Construct from components.
virtual ~kEpsilon ()
Destructor.
tmp< volScalarField > DkEff () const
Return the effective diffusivity for k.
tmp< volScalarField > DepsilonEff () const
Return the effective diffusivity for epsilon.
virtual tmp< volScalarField > k () const
Return the turbulence kinetic energy.
virtual tmp< volScalarField > epsilon () const
Return the turbulence kinetic energy dissipation rate.
virtual void correct ()
Solve the turbulence equations and correct the turbulence viscosity.
Public Member Functions inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~eddyViscosity ()
Destructor.
volScalarField & evNut ()
Return non-const access to the turbulence viscosity.
virtual tmp< volScalarField > nut () const
Return the turbulence viscosity.
virtual tmp< scalarField > nut (const label patchi) const
Return the turbulence viscosity on patch.
virtual tmp< volSymmTensorField > R () const
Return the Reynolds stress tensor.
virtual void validate ()
Validate the turbulence fields after construction.
Public Member Functions inherited from linearViscousStress< RASModel< BasicTurbulenceModel > >
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~linearViscousStress ()
Destructor.
virtual tmp< volSymmTensorField > devRhoReff () const
Return the effective stress tensor.
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
Return the source term for the momentum equation.
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Return the source term for the momentum equation.
Public Member Functions inherited from RASModel< BasicTurbulenceModel >
TypeName ("RAS")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, RASModel, dictionary,(const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName),(alpha, rho, U, alphaRhoPhi, phi, transport, propertiesName))
RASModel (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~RASModel ()
Destructor.
const dimensionedScalar & kMin () const
Return the lower allowable limit for k (default: SMALL)
const dimensionedScalar & epsilonMin () const
Return the lower allowable limit for epsilon (default: SMALL)
const dimensionedScalar & omegaMin () const
Return the lower allowable limit for omega (default: SMALL)
dimensionedScalar & kMin ()
Allow kMin to be changed.
dimensionedScalar & epsilonMin ()
Allow epsilonMin to be changed.
dimensionedScalar & omegaMin ()
Allow omegaMin to be changed.
virtual const dictionary & coeffDict () const
Const access to the coefficients dictionary.
virtual tmp< volScalarField > nuEff () const
Return the effective viscosity.
virtual tmp< scalarField > nuEff (const label patchi) const
Return the effective viscosity on patch.
Protected Member Functions
tmp< volScalarField > Gcoef () const
virtual tmp< fvScalarMatrix > kSource () const
virtual tmp< fvScalarMatrix > epsilonSource () const
Protected Member Functions inherited from kEpsilon< BasicTurbulenceModel >
virtual void correctNut ()
Protected Member Functions inherited from RASModel< BasicTurbulenceModel >
virtual void printCoeffs (const word &type)
Print model coefficients.
Protected Attributes
dimensionedScalar Cg_
Protected Attributes inherited from kEpsilon< BasicTurbulenceModel >
dimensionedScalar Cmu_
dimensionedScalar C1_
dimensionedScalar C2_
dimensionedScalar C3_
dimensionedScalar sigmak_
dimensionedScalar sigmaEps_
volScalarField k_
volScalarField epsilon_
Protected Attributes inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
volScalarField nut_
Protected Attributes inherited from RASModel< BasicTurbulenceModel >
dictionary RASDict_
RAS coefficients dictionary.
Switch turbulence_
Turbulence on/off flag.
Switch printCoeffs_
Flag to print the model coeffs at run-time.
dictionary coeffDict_
Model coefficients dictionary.
dimensionedScalar kMin_
Lower limit of k.
dimensionedScalar epsilonMin_
Lower limit of epsilon.
dimensionedScalar omegaMin_
Lower limit for omega.
Additional Inherited Members
Static Public Member Functions inherited from RASModel< BasicTurbulenceModel >
static autoPtr< RASModel > New (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Return a reference to the selected RAS model.
Detailed Description
template<class BasicTurbulenceModel>
class Foam::RASModels::buoyantKEpsilon< BasicTurbulenceModel >
Additional buoyancy generation/dissipation term applied to the k and epsilon equations of the standard k-epsilon model.
Reference:
    Henkes, R.A.W.M., Van Der Vlugt, F.F. & Hoogendoorn, C.J. (1991).
    Natural Convection Flow in a Square Cavity Calculated with
    Low-Reynolds-Number Turbulence Models.
    Int. J. Heat Mass Transfer, 34, 1543-1557.
This implementation is based on the density rather than temperature gradient extending the applicability to systems in which the density gradient may be generated by variation of composition rather than temperature. Further, the 1/Prt coefficient is replaced by Cg to provide more general control of model.
The default model coefficients are
    buoyantKEpsilonCoeffs
    {
        Cg              1.0;
    }
See also
Foam::RASModels::kEpsilon
Source files
buoyantKEpsilon.H
buoyantKEpsilon.C
Definition at line 80 of file buoyantKEpsilon.H.
Member Typedef Documentation
alphaField
typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 109 of file buoyantKEpsilon.H.
rhoField
typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 110 of file buoyantKEpsilon.H.
transportModel
typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 111 of file buoyantKEpsilon.H.
Constructor & Destructor Documentation
buoyantKEpsilon()
buoyantKEpsilon (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Construct from components.
Definition at line 42 of file buoyantKEpsilon.C.
~buoyantKEpsilon()
virtual ~buoyantKEpsilon () inline virtual
Destructor.
Definition at line 135 of file buoyantKEpsilon.H.
References buoyantKEpsilon< BasicTurbulenceModel >::read().
Member Function Documentation
Gcoef()
tmp< volScalarField > Gcoef () const protected
Definition at line 102 of file buoyantKEpsilon.C.
References g, and Foam::fvc::grad().
kSource()
tmp< fvScalarMatrix > kSource () const protected virtual
Reimplemented from kEpsilon< BasicTurbulenceModel >.
Definition at line 116 of file buoyantKEpsilon.C.
References g, kEpsilon< BasicTurbulenceModel >::kSource(), Foam::mag(), Foam::fvm::SuSp(), and dimensioned< Type >::value().
epsilonSource()
tmp< fvScalarMatrix > epsilonSource () const protected virtual
Reimplemented from kEpsilon< BasicTurbulenceModel >.
Definition at line 135 of file buoyantKEpsilon.C.
References Foam::dimVelocity, kEpsilon< BasicTurbulenceModel >::epsilonSource(), g, Foam::mag(), Foam::fvm::SuSp(), Foam::tanh(), and dimensioned< Type >::value().
TypeName()
TypeName ("buoyantKEpsilon< BasicTurbulenceModel >")
Runtime type information.
read()
bool read () virtual
Re-read model coefficients if they have changed.
Reimplemented from kEpsilon< BasicTurbulenceModel >.
Definition at line 85 of file buoyantKEpsilon.C.
Referenced by buoyantKEpsilon< BasicTurbulenceModel >::~buoyantKEpsilon().
Member Data Documentation
Cg_
dimensionedScalar Cg_ protected
Definition at line 97 of file buoyantKEpsilon.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/compressible/RAS/buoyantKEpsilon/buoyantKEpsilon.H
src/TurbulenceModels/compressible/RAS/buoyantKEpsilon/buoyantKEpsilon.C