OpenFOAM: ThermalDiffusivity< BasicTurbulenceModel > Class Template Reference
ThermalDiffusivity< BasicTurbulenceModel > Class Template Reference
Templated wrapper class to provide compressible turbulence models thermal diffusivity based thermal transport.
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef volScalarField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
ThermalDiffusivity (const word &type, const alphaField &alpha, const volScalarField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &trasport, const word &propertiesName)
Construct.
virtual ~ThermalDiffusivity ()
Destructor.
virtual tmp< volScalarField > kappa () const
Return the thermal diffusivity for temperature [J/m/s/K].
virtual tmp< scalarField > kappa (const label patchi) const
Return the laminar thermal diffusivity for temperature on patch.
virtual tmp< volScalarField > alpha () const
Return the laminar thermal diffusivity for enthalpy [kg/m/s].
virtual tmp< scalarField > alpha (const label patchi) const
Return the laminar thermal diffusivity for enthalpy on patch.
virtual tmp< volScalarField > alphat () const
Return the turbulent thermal diffusivity for enthalpy [kg/m/s].
virtual tmp< scalarField > alphat (const label patchi) const
Return the turbulent thermal diffusivity for enthalpy for a patch.
virtual tmp< volScalarField > kappaEff () const
Return the effective turbulent thermal diffusivity for temperature.
virtual tmp< scalarField > kappaEff (const label patchi) const
Return the effective turbulent thermal diffusivity for temperature.
virtual tmp< volScalarField > alphaEff () const
Return the effective turbulent thermal diffusivity for enthalpy.
virtual tmp< scalarField > alphaEff (const label patchi) const
Return the effective turbulent thermal diffusivity for enthalpy.
Static Public Member Functions
static autoPtr< ThermalDiffusivity > New (const alphaField &alpha, const volScalarField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &trasportModel, const word &propertiesName=turbulenceModel::propertiesName)
Return a reference to the selected turbulence model.
static autoPtr< ThermalDiffusivity > New (const volScalarField &rho, const volVectorField &U, const surfaceScalarField &phi, const transportModel &trasportModel, const word &propertiesName=turbulenceModel::propertiesName)
Return a reference to the selected turbulence model.
Detailed Description
template<class BasicTurbulenceModel>
class Foam::ThermalDiffusivity< BasicTurbulenceModel >
Templated wrapper class to provide compressible turbulence models thermal diffusivity based thermal transport.
Source files
ThermalDiffusivity.H
ThermalDiffusivity.C
Definition at line 48 of file ThermalDiffusivity.H.
Member Typedef Documentation
alphaField
typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 55 of file ThermalDiffusivity.H.
rhoField
typedef volScalarField rhoField
Definition at line 56 of file ThermalDiffusivity.H.
transportModel
typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 57 of file ThermalDiffusivity.H.
Constructor & Destructor Documentation
ThermalDiffusivity()
ThermalDiffusivity (const word & type, const alphaField & alpha, const volScalarField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & trasport, const word & propertiesName)
Construct.
Definition at line 32 of file ThermalDiffusivity.C.
~ThermalDiffusivity()
virtual ~ThermalDiffusivity () inline virtual
Destructor.
Definition at line 103 of file ThermalDiffusivity.H.
Member Function Documentation
New() [1/2]
Foam::autoPtr< Foam::ThermalDiffusivity< BasicTurbulenceModel > > New (const alphaField & alpha, const volScalarField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & trasportModel, const word & propertiesName = turbulenceModel::propertiesName) static
Return a reference to the selected turbulence model.
Definition at line 62 of file ThermalDiffusivity.C.
Referenced by ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > >::New(), and ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > >::ThermalDiffusivity().
New() [2/2]
Foam::autoPtr< Foam::ThermalDiffusivity< BasicTurbulenceModel > > New (const volScalarField & rho, const volVectorField & U, const surfaceScalarField & phi, const transportModel & trasportModel, const word & propertiesName = turbulenceModel::propertiesName) static
Return a reference to the selected turbulence model.
Definition at line 92 of file ThermalDiffusivity.C.
kappa() [1/2]
virtual tmp<volScalarField> kappa () const inline virtual
Return the thermal diffusivity for temperature [J/m/s/K].
Definition at line 110 of file ThermalDiffusivity.H.
Referenced by ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > >::alpha(), and ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > >::kappa().
kappa() [2/2]
virtual tmp<scalarField> kappa (const label patchi) const inline virtual
Return the laminar thermal diffusivity for temperature on patch.
[J/m/s/K]
Definition at line 117 of file ThermalDiffusivity.H.
alpha() [1/2]
virtual tmp<volScalarField> alpha () const inline virtual
Return the laminar thermal diffusivity for enthalpy [kg/m/s].
Definition at line 123 of file ThermalDiffusivity.H.
Referenced by ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > >::alpha(), alphatFilmWallFunctionFvPatchScalarField::updateCoeffs(), and alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs().
alpha() [2/2]
virtual tmp<scalarField> alpha (const label patchi) const inline virtual
Return the laminar thermal diffusivity for enthalpy on patch.
[kg/m/s]
Definition at line 130 of file ThermalDiffusivity.H.
alphat() [1/2]
Foam::tmp< Foam::volScalarField > alphat () const virtual
Return the turbulent thermal diffusivity for enthalpy [kg/m/s].
Reimplemented in EddyDiffusivity< ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > > >, EddyDiffusivity< phaseCompressibleTurbulenceModel >, and EddyDiffusivity< compressible::turbulenceModel >.
Definition at line 119 of file ThermalDiffusivity.C.
Referenced by ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > >::alpha(), ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > >::alphat(), and turbulenceFields::execute().
alphat() [2/2]
Foam::tmp< Foam::scalarField > alphat (const label patchi) const virtual
Return the turbulent thermal diffusivity for enthalpy for a patch.
[kg/m/s]
Reimplemented in EddyDiffusivity< ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > > >, EddyDiffusivity< phaseCompressibleTurbulenceModel >, and EddyDiffusivity< compressible::turbulenceModel >.
Definition at line 143 of file ThermalDiffusivity.C.
kappaEff() [1/2]
virtual tmp<volScalarField> kappaEff () const inline virtual
Return the effective turbulent thermal diffusivity for temperature.
[J/m/s/K]
Reimplemented in EddyDiffusivity< ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > > >, EddyDiffusivity< phaseCompressibleTurbulenceModel >, and EddyDiffusivity< compressible::turbulenceModel >.
Definition at line 144 of file ThermalDiffusivity.H.
Referenced by ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > >::alpha(), NamedEnum< directionType, 3 >::names(), wallHeatTransferFvPatchScalarField::updateCoeffs(), and thermalBaffle1DFvPatchScalarField< solidType >::updateCoeffs().
kappaEff() [2/2]
virtual tmp<scalarField> kappaEff (const label patchi) const inline virtual
Return the effective turbulent thermal diffusivity for temperature.
[J/m/s/K]
Reimplemented in EddyDiffusivity< ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > > >, EddyDiffusivity< phaseCompressibleTurbulenceModel >, and EddyDiffusivity< compressible::turbulenceModel >.
Definition at line 151 of file ThermalDiffusivity.H.
alphaEff() [1/2]
virtual tmp<volScalarField> alphaEff () const inline virtual
Return the effective turbulent thermal diffusivity for enthalpy.
[kg/m/s]
Reimplemented in EddyDiffusivity< ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > > >, EddyDiffusivity< phaseCompressibleTurbulenceModel >, and EddyDiffusivity< compressible::turbulenceModel >.
Definition at line 158 of file ThermalDiffusivity.H.
Referenced by ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > >::alpha(), wallHeatFlux::calcHeatFlux(), turbulenceFields::execute(), convectiveHeatTransferFvPatchScalarField::updateCoeffs(), and alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs().
alphaEff() [2/2]
virtual tmp<scalarField> alphaEff (const label patchi) const inline virtual
Return the effective turbulent thermal diffusivity for enthalpy.
for a patch [kg/m/s]
Reimplemented in EddyDiffusivity< ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > > >, EddyDiffusivity< phaseCompressibleTurbulenceModel >, and EddyDiffusivity< compressible::turbulenceModel >.
Definition at line 165 of file ThermalDiffusivity.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/compressible/ThermalDiffusivity/ThermalDiffusivity.H
src/TurbulenceModels/compressible/ThermalDiffusivity/ThermalDiffusivity.C