OpenFOAM: convectiveHeatTransferFvPatchScalarField Class Reference
convectiveHeatTransferFvPatchScalarField Class Reference
This boundary condition provides a convective heat transfer coefficient condition.
Public Member Functions
TypeName ("convectiveHeatTransfer")
Runtime type information.
convectiveHeatTransferFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
convectiveHeatTransferFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
convectiveHeatTransferFvPatchScalarField (const convectiveHeatTransferFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
convectiveHeatTransferFvPatchScalarField (const convectiveHeatTransferFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
convectiveHeatTransferFvPatchScalarField (const convectiveHeatTransferFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Protected Attributes
const scalar L_
L Length scale [m].
Detailed Description
This boundary condition provides a convective heat transfer coefficient condition.
if Re > 500000
else
where
= patch convective heat transfer coefficient
= Reynolds number
= Prandtl number
= thermal conductivity
= length scale
Usage
Property Description Required Default value
L Length scale [m] yes
Example of the boundary condition specification:
    <patchName>
    {
        type            convectiveHeatTransfer;
        L               0.1;
    }
See also
Foam::fixedValueFvPatchField
Source files
convectiveHeatTransferFvPatchScalarField.H
convectiveHeatTransferFvPatchScalarField.C
Definition at line 121 of file convectiveHeatTransferFvPatchScalarField.H.
Constructor & Destructor Documentation
convectiveHeatTransferFvPatchScalarField() [1/5]
convectiveHeatTransferFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 42 of file convectiveHeatTransferFvPatchScalarField.C.
Referenced by convectiveHeatTransferFvPatchScalarField::clone(), and convectiveHeatTransferFvPatchScalarField::convectiveHeatTransferFvPatchScalarField().
convectiveHeatTransferFvPatchScalarField() [2/5]
convectiveHeatTransferFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 68 of file convectiveHeatTransferFvPatchScalarField.C.
References convectiveHeatTransferFvPatchScalarField::convectiveHeatTransferFvPatchScalarField().
convectiveHeatTransferFvPatchScalarField() [3/5]
convectiveHeatTransferFvPatchScalarField (const convectiveHeatTransferFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
convectiveHeatTransferFvPatchScalarField onto a new patch
Definition at line 54 of file convectiveHeatTransferFvPatchScalarField.C.
References convectiveHeatTransferFvPatchScalarField::convectiveHeatTransferFvPatchScalarField().
convectiveHeatTransferFvPatchScalarField() [4/5]
convectiveHeatTransferFvPatchScalarField (const convectiveHeatTransferFvPatchScalarField & htcpsf)
Construct as copy.
Definition at line 81 of file convectiveHeatTransferFvPatchScalarField.C.
References convectiveHeatTransferFvPatchScalarField::convectiveHeatTransferFvPatchScalarField().
convectiveHeatTransferFvPatchScalarField() [5/5]
convectiveHeatTransferFvPatchScalarField (const convectiveHeatTransferFvPatchScalarField & htcpsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 92 of file convectiveHeatTransferFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("convectiveHeatTransfer")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 174 of file convectiveHeatTransferFvPatchScalarField.H.
References convectiveHeatTransferFvPatchScalarField::convectiveHeatTransferFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 191 of file convectiveHeatTransferFvPatchScalarField.H.
References convectiveHeatTransferFvPatchScalarField::convectiveHeatTransferFvPatchScalarField(), convectiveHeatTransferFvPatchScalarField::updateCoeffs(), and convectiveHeatTransferFvPatchScalarField::write().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 104 of file convectiveHeatTransferFvPatchScalarField.C.
References ThermalDiffusivity< BasicTurbulenceModel >::alphaEff(), Foam::cbrt(), forAll, Foam::constant::atomic::group, IOobject::groupName(), convectiveHeatTransferFvPatchScalarField::L_, Foam::mag(), patchi, Foam::pow(), Pr(), Foam::Re(), and Foam::sqrt().
Referenced by convectiveHeatTransferFvPatchScalarField::clone().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 161 of file convectiveHeatTransferFvPatchScalarField.C.
References token::END_STATEMENT, convectiveHeatTransferFvPatchScalarField::L_, Foam::compressible::makePatchTypeField(), Foam::nl, fvPatchField< Type >::write(), and Ostream::writeKeyword().
Referenced by convectiveHeatTransferFvPatchScalarField::clone().
Member Data Documentation
L_
const scalar L_ protected
L Length scale [m].
Definition at line 130 of file convectiveHeatTransferFvPatchScalarField.H.
Referenced by convectiveHeatTransferFvPatchScalarField::updateCoeffs(), and convectiveHeatTransferFvPatchScalarField::write().
The documentation for this class was generated from the following files:
src/TurbulenceModels/compressible/turbulentFluidThermoModels/derivedFvPatchFields/convectiveHeatTransfer/convectiveHeatTransferFvPatchScalarField.H
src/TurbulenceModels/compressible/turbulentFluidThermoModels/derivedFvPatchFields/convectiveHeatTransfer/convectiveHeatTransferFvPatchScalarField.C