OpenFOAM: alphatPhaseChangeWallFunctionFvPatchScalarField Class Reference
alphatPhaseChangeWallFunctionFvPatchScalarField Class Reference abstract
Compressible turbulence » Compressible Turbulence BCs » Compressible turbulence wall functions
Abstract base-class for all alphatWallFunctions supporting phase-change.
Public Member Functions
TypeName ("compressible::alphatPhaseChangeWallFunction")
Runtime type information.
alphatPhaseChangeWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
alphatPhaseChangeWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
alphatPhaseChangeWallFunctionFvPatchScalarField (const alphatPhaseChangeWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
alphatPhaseChangeWallFunctionFvPatchScalarField (const alphatPhaseChangeWallFunctionFvPatchScalarField &)
Construct as copy.
alphatPhaseChangeWallFunctionFvPatchScalarField (const alphatPhaseChangeWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
const scalarField & dmdt () const
Return the rate of phase-change.
const scalarField & mDotL () const
Return the enthelpy source due to phase-change.
virtual void updateCoeffs ()=0
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Protected Attributes
scalarField dmdt_
Rate of phase-change.
scalarField mDotL_
Latent heat of the phase-change.
Detailed Description
Abstract base-class for all alphatWallFunctions supporting phase-change.
See also
Foam::fixedValueFvPatchScalarField Foam::alphatWallFunctionFvPatchScalarField
Source files
alphatPhaseChangeWallFunctionFvPatchScalarField.H
alphatPhaseChangeWallFunctionFvPatchScalarField.C
Definition at line 57 of file alphatPhaseChangeWallFunctionFvPatchScalarField.H.
Constructor & Destructor Documentation
alphatPhaseChangeWallFunctionFvPatchScalarField() [1/5]
alphatPhaseChangeWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 46 of file alphatPhaseChangeWallFunctionFvPatchScalarField.C.
Referenced by alphatPhaseChangeWallFunctionFvPatchScalarField::alphatPhaseChangeWallFunctionFvPatchScalarField().
alphatPhaseChangeWallFunctionFvPatchScalarField() [2/5]
alphatPhaseChangeWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 59 of file alphatPhaseChangeWallFunctionFvPatchScalarField.C.
References alphatPhaseChangeWallFunctionFvPatchScalarField::alphatPhaseChangeWallFunctionFvPatchScalarField(), dictionary::found(), and fvPatch::size().
alphatPhaseChangeWallFunctionFvPatchScalarField() [3/5]
alphatPhaseChangeWallFunctionFvPatchScalarField (const alphatPhaseChangeWallFunctionFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
alphatPhaseChangeWallFunctionFvPatchScalarField onto a new patch
Definition at line 83 of file alphatPhaseChangeWallFunctionFvPatchScalarField.C.
References alphatPhaseChangeWallFunctionFvPatchScalarField::alphatPhaseChangeWallFunctionFvPatchScalarField().
alphatPhaseChangeWallFunctionFvPatchScalarField() [4/5]
alphatPhaseChangeWallFunctionFvPatchScalarField (const alphatPhaseChangeWallFunctionFvPatchScalarField & awfpsf)
Construct as copy.
Definition at line 98 of file alphatPhaseChangeWallFunctionFvPatchScalarField.C.
References alphatPhaseChangeWallFunctionFvPatchScalarField::alphatPhaseChangeWallFunctionFvPatchScalarField().
alphatPhaseChangeWallFunctionFvPatchScalarField() [5/5]
alphatPhaseChangeWallFunctionFvPatchScalarField (const alphatPhaseChangeWallFunctionFvPatchScalarField & awfpsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 110 of file alphatPhaseChangeWallFunctionFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("compressible::alphatPhaseChangeWallFunction")
Runtime type information.
dmdt()
const scalarField& dmdt () const inline
Return the rate of phase-change.
Definition at line 123 of file alphatPhaseChangeWallFunctionFvPatchScalarField.H.
References alphatPhaseChangeWallFunctionFvPatchScalarField::dmdt_.
mDotL()
const scalarField& mDotL () const inline
Return the enthelpy source due to phase-change.
Definition at line 129 of file alphatPhaseChangeWallFunctionFvPatchScalarField.H.
References alphatPhaseChangeWallFunctionFvPatchScalarField::mDotL_, alphatPhaseChangeWallFunctionFvPatchScalarField::updateCoeffs(), and alphatPhaseChangeWallFunctionFvPatchScalarField::write().
updateCoeffs()
virtual void updateCoeffs () pure virtual
Update the coefficients associated with the patch field.
Implemented in alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField, alphatWallBoilingWallFunctionFvPatchScalarField, and alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField.
Referenced by alphatPhaseChangeWallFunctionFvPatchScalarField::mDotL().
write()
void write (Ostream & os) const virtual
Write.
Reimplemented in alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField, alphatWallBoilingWallFunctionFvPatchScalarField, and alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField.
Definition at line 123 of file alphatPhaseChangeWallFunctionFvPatchScalarField.C.
References alphatPhaseChangeWallFunctionFvPatchScalarField::dmdt_, alphatPhaseChangeWallFunctionFvPatchScalarField::mDotL_, fvPatchField< Type >::write(), and Field< Type >::writeEntry().
Referenced by alphatPhaseChangeWallFunctionFvPatchScalarField::mDotL().
Member Data Documentation
dmdt_
scalarField dmdt_ protected
Rate of phase-change.
Definition at line 66 of file alphatPhaseChangeWallFunctionFvPatchScalarField.H.
Referenced by alphatPhaseChangeWallFunctionFvPatchScalarField::dmdt(), and alphatPhaseChangeWallFunctionFvPatchScalarField::write().
mDotL_
scalarField mDotL_ protected
Latent heat of the phase-change.
Definition at line 69 of file alphatPhaseChangeWallFunctionFvPatchScalarField.H.
Referenced by alphatPhaseChangeWallFunctionFvPatchScalarField::mDotL(), and alphatPhaseChangeWallFunctionFvPatchScalarField::write().
The documentation for this class was generated from the following files:
src/TurbulenceModels/compressible/turbulentFluidThermoModels/derivedFvPatchFields/wallFunctions/alphatWallFunctions/alphatPhaseChangeWallFunction/alphatPhaseChangeWallFunctionFvPatchScalarField.H
src/TurbulenceModels/compressible/turbulentFluidThermoModels/derivedFvPatchFields/wallFunctions/alphatWallFunctions/alphatPhaseChangeWallFunction/alphatPhaseChangeWallFunctionFvPatchScalarField.C