OpenFOAM: qZeta Class Reference
qZeta Class Reference
Gibson and Dafa'Alla's q-zeta two-equation low-Re turbulence model for incompressible flows.
Public Member Functions
TypeName ("qZeta")
Runtime type information.
qZeta (const geometricOneField &alpha, const geometricOneField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
Construct from components.
virtual ~qZeta ()
Destructor.
virtual bool read ()
Read RASProperties dictionary.
const dimensionedScalar & qMin () const
Return the lower allowable limit for q (default: SMALL)
const dimensionedScalar & zetaMin () const
Return the lower allowable limit for zeta (default: SMALL)
dimensionedScalar & qMin ()
Allow qMin to be changed.
dimensionedScalar & zetaMin ()
Allow zetaMin to be changed.
tmp< volScalarField > DqEff () const
Return the effective diffusivity for q.
tmp< volScalarField > DzetaEff () const
Return the effective diffusivity for epsilon.
virtual tmp< volScalarField > k () const
Return the turbulence kinetic energy.
virtual tmp< volScalarField > epsilon () const
Return the turbulence kinetic energy dissipation rate.
virtual const volScalarField & q () const
virtual const volScalarField & zeta () const
virtual void correct ()
Solve the turbulence equations and correct the turbulence viscosity.
Public Member Functions inherited from eddyViscosity< incompressible::RASModel >
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~eddyViscosity ()
Destructor.
volScalarField & evNut ()
Return non-const access to the turbulence viscosity.
virtual tmp< volScalarField > nut () const
Return the turbulence viscosity.
virtual tmp< scalarField > nut (const label patchi) const
Return the turbulence viscosity on patch.
virtual tmp< volSymmTensorField > R () const
Return the Reynolds stress tensor.
virtual void validate ()
Validate the turbulence fields after construction.
Public Member Functions inherited from linearViscousStress< incompressible::RASModel >
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~linearViscousStress ()
Destructor.
virtual tmp< volSymmTensorField > devRhoReff () const
Return the effective stress tensor.
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
Return the source term for the momentum equation.
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Return the source term for the momentum equation.
Protected Member Functions
tmp< volScalarField > fMu () const
tmp< volScalarField > f2 () const
virtual void correctNut ()
Protected Attributes
dimensionedScalar Cmu_
dimensionedScalar C1_
dimensionedScalar C2_
dimensionedScalar sigmaZeta_
Switch anisotropic_
dimensionedScalar qMin_
Lower limit of q.
dimensionedScalar zetaMin_
Lower limit of zeta.
volScalarField k_
volScalarField epsilon_
volScalarField q_
volScalarField zeta_
Protected Attributes inherited from eddyViscosity< incompressible::RASModel >
volScalarField nut_
Additional Inherited Members
Public Types inherited from eddyViscosity< incompressible::RASModel >
typedef incompressible::RASModel ::alphaField alphaField
typedef incompressible::RASModel ::rhoField rhoField
typedef incompressible::RASModel ::transportModel transportModel
Public Types inherited from linearViscousStress< incompressible::RASModel >
typedef incompressible::RASModel ::alphaField alphaField
typedef incompressible::RASModel ::rhoField rhoField
typedef incompressible::RASModel ::transportModel transportModel
Detailed Description
Gibson and Dafa'Alla's q-zeta two-equation low-Re turbulence model for incompressible flows.
This turbulence model is described in:
    Dafa'Alla, A.A., Juntasaro, E. & Gibson, M.M. (1996).
    Calculation of oscillating boundary layers with the
    q-zeta turbulence model.
    Engineering Turbulence Modelling and Experiments 3:
    Proceedings of the Third International Symposium,
    Crete, Greece, May 27-29, 141.
which is a development of the original q-zeta model described in:
    Gibson, M. M., & Dafa'Alla, A. A. (1995).
    Two-equation model for turbulent wall flow.
    AIAA journal, 33(8), 1514-1518.
Source files
qZeta.H
qZeta.C
Definition at line 73 of file qZeta.H.
Constructor & Destructor Documentation
qZeta()
qZeta (const geometricOneField & alpha, const geometricOneField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Construct from components.
Definition at line 80 of file qZeta.C.
References Foam::bound(), qZeta::zeta_, and qZeta::zetaMin_.
Referenced by qZeta::correctNut().
~qZeta()
virtual ~qZeta () inline virtual
Destructor.
Definition at line 134 of file qZeta.H.
References qZeta::read().
Member Function Documentation
fMu()
tmp< volScalarField > fMu () const protected
Definition at line 46 of file qZeta.C.
References qZeta::anisotropic_, Foam::exp(), qZeta::k_, nu, Foam::pow3(), qZeta::q_, Foam::sqr(), and qZeta::zeta_.
Referenced by qZeta::correctNut().
f2()
tmp< volScalarField > f2 () const protected
Definition at line 63 of file qZeta.C.
References Foam::exp(), qZeta::k_, nu, qZeta::q_, Foam::sqr(), and qZeta::zeta_.
Referenced by qZeta::correct().
correctNut()
void correctNut () protected virtual
Implements eddyViscosity< incompressible::RASModel >.
Definition at line 70 of file qZeta.C.
References qZeta::Cmu_, GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), qZeta::epsilon_, qZeta::fMu(), qZeta::k_, eddyViscosity< incompressible::RASModel >::nut_, qZeta::qZeta(), and Foam::sqr().
Referenced by qZeta::correct().
TypeName()
TypeName ("qZeta")
Runtime type information.
read()
bool read () virtual
Read RASProperties dictionary.
Implements eddyViscosity< incompressible::RASModel >.
Definition at line 217 of file qZeta.C.
References qZeta::anisotropic_, qZeta::C1_, qZeta::C2_, qZeta::Cmu_, qZeta::qMin_, Switch::readIfPresent(), dimensioned< Type >::readIfPresent(), qZeta::sigmaZeta_, and qZeta::zetaMin_.
Referenced by qZeta::~qZeta().
qMin() [1/2]
const dimensionedScalar& qMin () const inline
Return the lower allowable limit for q (default: SMALL)
Definition at line 144 of file qZeta.H.
References qZeta::qMin_.
zetaMin() [1/2]
const dimensionedScalar& zetaMin () const inline
Return the lower allowable limit for zeta (default: SMALL)
Definition at line 150 of file qZeta.H.
References qZeta::zetaMin_.
qMin() [2/2]
dimensionedScalar& qMin () inline
Allow qMin to be changed.
Definition at line 156 of file qZeta.H.
References qZeta::qMin_.
zetaMin() [2/2]
dimensionedScalar& zetaMin () inline
Allow zetaMin to be changed.
Definition at line 162 of file qZeta.H.
References qZeta::zetaMin_.
DqEff()
tmp<volScalarField> DqEff () const inline
Return the effective diffusivity for q.
Definition at line 168 of file qZeta.H.
References nu, and eddyViscosity< incompressible::RASModel >::nut_.
Referenced by qZeta::correct().
DzetaEff()
tmp<volScalarField> DzetaEff () const inline
Return the effective diffusivity for epsilon.
Definition at line 177 of file qZeta.H.
References nu, and eddyViscosity< incompressible::RASModel >::nut_.
Referenced by qZeta::correct().
k()
virtual tmp<volScalarField> k () const inline virtual
Return the turbulence kinetic energy.
Implements eddyViscosity< incompressible::RASModel >.
Definition at line 186 of file qZeta.H.
References qZeta::k_.
epsilon()
virtual tmp<volScalarField> epsilon () const inline virtual
Return the turbulence kinetic energy dissipation rate.
Definition at line 192 of file qZeta.H.
References qZeta::epsilon_.
q()
virtual const volScalarField& q () const inline virtual
Definition at line 197 of file qZeta.H.
References qZeta::q_.
zeta()
virtual const volScalarField& zeta () const inline virtual
Definition at line 202 of file qZeta.H.
References qZeta::correct(), and qZeta::zeta_.
correct()
void correct () virtual
Solve the turbulence equations and correct the turbulence viscosity.
Implements eddyViscosity< incompressible::RASModel >.
Definition at line 239 of file qZeta.C.
References Foam::bound(), qZeta::C1_, qZeta::C2_, eddyViscosity< BasicTurbulenceModel >::correct(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), qZeta::correctNut(), Foam::fvm::ddt(), Foam::fvm::div(), qZeta::DqEff(), qZeta::DzetaEff(), qZeta::epsilon_, qZeta::f2(), Foam::constant::universal::G, Foam::fvc::grad(), qZeta::k_, Foam::fvm::laplacian(), Foam::magSqr(), Foam::fvc::magSqrGradGrad(), nu, eddyViscosity< incompressible::RASModel >::nut_, qZeta::q_, qZeta::qMin_, tmp< T >::ref(), Foam::solve(), Foam::fvm::Sp(), Foam::sqr(), Foam::fvm::SuSp(), Foam::symm(), qZeta::zeta_, and qZeta::zetaMin_.
Referenced by qZeta::zeta().
Member Data Documentation
Cmu_
dimensionedScalar Cmu_ protected
Definition at line 84 of file qZeta.H.
Referenced by qZeta::correctNut(), and qZeta::read().
C1_
dimensionedScalar C1_ protected
Definition at line 85 of file qZeta.H.
Referenced by qZeta::correct(), and qZeta::read().
C2_
dimensionedScalar C2_ protected
Definition at line 86 of file qZeta.H.
Referenced by qZeta::correct(), and qZeta::read().
sigmaZeta_
dimensionedScalar sigmaZeta_ protected
Definition at line 87 of file qZeta.H.
Referenced by qZeta::read().
anisotropic_
Switch anisotropic_ protected
Definition at line 88 of file qZeta.H.
Referenced by qZeta::fMu(), and qZeta::read().
qMin_
dimensionedScalar qMin_ protected
Lower limit of q.
Definition at line 91 of file qZeta.H.
Referenced by qZeta::correct(), qZeta::qMin(), and qZeta::read().
zetaMin_
dimensionedScalar zetaMin_ protected
Lower limit of zeta.
Definition at line 94 of file qZeta.H.
Referenced by qZeta::correct(), qZeta::qZeta(), qZeta::read(), and qZeta::zetaMin().
k_
volScalarField k_ protected
Definition at line 98 of file qZeta.H.
Referenced by qZeta::correct(), qZeta::correctNut(), qZeta::f2(), qZeta::fMu(), and qZeta::k().
epsilon_
volScalarField epsilon_ protected
Definition at line 99 of file qZeta.H.
Referenced by qZeta::correct(), qZeta::correctNut(), and qZeta::epsilon().
q_
volScalarField q_ protected
Definition at line 101 of file qZeta.H.
Referenced by qZeta::correct(), qZeta::f2(), qZeta::fMu(), and qZeta::q().
zeta_
volScalarField zeta_ protected
Definition at line 102 of file qZeta.H.
Referenced by qZeta::correct(), qZeta::f2(), qZeta::fMu(), qZeta::qZeta(), and qZeta::zeta().
The documentation for this class was generated from the following files:
src/TurbulenceModels/incompressible/turbulentTransportModels/RAS/qZeta/qZeta.H
src/TurbulenceModels/incompressible/turbulentTransportModels/RAS/qZeta/qZeta.C