OpenFOAM: thermalBaffle1DFvPatchScalarField< solidType > Class Template Reference
thermalBaffle1DFvPatchScalarField< solidType > Class Template Reference
Boundary Conditions » Thermophysical boundary conditions
This BC solves a steady 1D thermal baffle.
Public Member Functions
TypeName ("compressible::thermalBaffle1D")
Runtime type information.
thermalBaffle1DFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
thermalBaffle1DFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
thermalBaffle1DFvPatchScalarField (const thermalBaffle1DFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
thermalBaffle1DFvPatchScalarField (const thermalBaffle1DFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
thermalBaffle1DFvPatchScalarField (const thermalBaffle1DFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchScalarField &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from mappedPatchBase
TypeName ("mappedPatchBase")
Runtime type information.
mappedPatchBase (const polyPatch &)
Construct from patch.
mappedPatchBase (const polyPatch &pp, const word &sampleRegion, const sampleMode sampleMode, const word &samplePatch, const vectorField &offsets)
Construct with offsetMode=non-uniform.
mappedPatchBase (const polyPatch &pp, const word &sampleRegion, const sampleMode sampleMode, const word &samplePatch, const vector &offset)
Construct from offsetMode=uniform.
mappedPatchBase (const polyPatch &pp, const word &sampleRegion, const sampleMode sampleMode, const word &samplePatch, const scalar distance)
Construct from offsetMode=normal and distance.
mappedPatchBase (const polyPatch &, const dictionary &)
Construct from dictionary.
mappedPatchBase (const polyPatch &, const sampleMode, const dictionary &)
Construct from dictionary and (collocated) sample mode.
mappedPatchBase (const polyPatch &, const mappedPatchBase &)
Construct as copy, resetting patch.
mappedPatchBase (const polyPatch &, const mappedPatchBase &, const labelUList &mapAddressing)
Construct as copy, resetting patch, map original data.
virtual ~mappedPatchBase ()
Destructor.
void clearOut ()
const sampleMode & mode () const
What to sample.
const word & sampleRegion () const
Region to sample.
const word & samplePatch () const
Patch (only if NEARESTPATCHFACE)
const word & coupleGroup () const
PatchGroup (only if NEARESTPATCHFACE)
label sampleSize () const
Return size of mapped mesh/patch/boundary.
const vector & offset () const
Offset vector (from patch faces to destination mesh objects)
const vectorField & offsets () const
Offset vector (from patch faces to destination mesh objects)
bool sameRegion () const
Cached sampleRegion != mesh.name()
const mapDistribute & map () const
Return reference to the parallel distribution map.
const AMIPatchToPatchInterpolation & AMI (const bool forceUpdate=false) const
Return reference to the AMI interpolator.
const autoPtr< Foam::searchableSurface > & surfPtr () const
Return a pointer to the AMI projection surface.
const polyMesh & sampleMesh () const
Get the region mesh.
const polyPatch & samplePolyPatch () const
Get the patch on the region.
tmp< pointField > samplePoints () const
Get the sample points.
template<class Type >
void distribute (List< Type > &lst) const
Wrapper around map/interpolate data distribution.
template<class Type , class CombineOp >
void distribute (List< Type > &lst, const CombineOp &cop) const
Wrapper around map/interpolate data distribution with operation.
template<class Type >
void reverseDistribute (List< Type > &lst) const
Wrapper around map/interpolate data distribution.
template<class Type , class CombineOp >
void reverseDistribute (List< Type > &lst, const CombineOp &cop) const
Wrapper around map/interpolate data distribution with operation.
Additional Inherited Members
Public Types inherited from mappedPatchBase
enum sampleMode {
NEARESTCELL, NEARESTPATCHFACE, NEARESTPATCHFACEAMI, NEARESTPATCHPOINT,
NEARESTFACE, NEARESTONLYCELL
}
Mesh items to sample.
enum offsetMode { UNIFORM, NONUNIFORM, NORMAL }
How to project face centres.
typedef Tuple2< pointIndexHit, Tuple2< scalar, label > > nearInfo
Helper class for finding nearest.
Static Public Member Functions inherited from mappedPatchBase
static pointIndexHit facePoint (const polyMesh &, const label facei, const polyMesh::cellDecomposition)
Get a point on the face given a face decomposition method:
Static Public Attributes inherited from mappedPatchBase
static const NamedEnum< sampleMode, 6 > sampleModeNames_
static const NamedEnum< offsetMode, 3 > offsetModeNames_
Protected Member Functions inherited from mappedPatchBase
tmp< pointField > facePoints (const polyPatch &) const
Get the points from face-centre-decomposition face centres.
void collectSamples (const pointField &facePoints, pointField &, labelList &patchFaceProcs, labelList &patchFaces, pointField &patchFc) const
Collect single list of samples and originating processor+face.
void findSamples (const sampleMode mode, const pointField &, labelList &sampleProcs, labelList &sampleIndices, pointField &sampleLocations) const
Find cells/faces containing samples.
tmp< pointField > samplePoints (const pointField &) const
Get the sample points given the face points.
void calcMapping () const
Calculate mapping.
void calcAMI () const
Calculate AMI interpolator.
Static Protected Member Functions inherited from mappedPatchBase
static tmp< pointField > readListOrField (const word &keyword, const dictionary &dict, const label size)
Helper to read field or non-uniform list from dictionary.
Protected Attributes inherited from mappedPatchBase
const polyPatch & patch_
Patch to sample.
word sampleRegion_
Region to sample.
const sampleMode mode_
What to sample.
word samplePatch_
Patch (if in sampleMode NEARESTPATCH*)
const coupleGroupIdentifier coupleGroup_
PatchGroup (if in sampleMode NEARESTPATCH*)
offsetMode offsetMode_
How to obtain samples.
vector offset_
Offset vector (uniform)
vectorField offsets_
Offset vector (nonuniform)
scalar distance_
Offset distance (normal)
bool sameRegion_
Same region.
autoPtr< mapDistribute > mapPtr_
Communication schedule:
autoPtr< AMIPatchToPatchInterpolation > AMIPtr_
Pointer to AMI interpolator.
const bool AMIReverse_
Flag to indicate that slave patch should be reversed for AMI.
autoPtr< searchableSurface > surfPtr_
Pointer to projection surface employed by AMI interpolator.
dictionary surfDict_
Dictionary storing projection surface description.
Detailed Description
template<class solidType>
class Foam::compressible::thermalBaffle1DFvPatchScalarField< solidType >
This BC solves a steady 1D thermal baffle.
The solid properties are specify as dictionary. Optionaly radiative heat flux (Qr) can be incorporated into the balance. Some under-relaxation might be needed on Qr. Baffle and solid properties need to be specified on the master side of the baffle.
Usage
Example of the boundary condition specification using constant solid thermo :
<masterPatchName>
{
    type   compressible::thermalBaffle1D<hConstSolidThermoPhysics>;
    samplePatch     <slavePatchName>;
    thickness       uniform 0.005;  // thickness [m]
    Qs              uniform 100;    // heat flux [W/m2]
    Qr              none;
    relaxation      1;
    // Solid thermo
    specie
    {
        nMoles          1;
        molWeight       20;
    }
    transport
    {
        kappa           1;
    }
    thermodynamics
    {
        Hf              0;
        Cp              10;
    }
    equationOfState
    {
        rho             10;
    }
    value               uniform 300;
}
<slavePatchName>
{
    type   compressible::thermalBaffle1D<hConstSolidThermoPhysics>;
    samplePatch     <masterPatchName>;
    Qr              none;
    relaxation      1;
}
Source files
thermalBaffle1DFvPatchScalarField.H
thermalBaffle1DFvPatchScalarField.C
Definition at line 110 of file thermalBaffle1DFvPatchScalarField.H.
Constructor & Destructor Documentation
thermalBaffle1DFvPatchScalarField() [1/5]
thermalBaffle1DFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 44 of file thermalBaffle1DFvPatchScalarField.C.
Referenced by thermalBaffle1DFvPatchScalarField< solidType >::clone(), and thermalBaffle1DFvPatchScalarField< solidType >::thermalBaffle1DFvPatchScalarField().
thermalBaffle1DFvPatchScalarField() [2/5]
thermalBaffle1DFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 90 of file thermalBaffle1DFvPatchScalarField.C.
References dictionary::found(), fvPatchField< Type >::operator=(), fvPatch::size(), and thermalBaffle1DFvPatchScalarField< solidType >::thermalBaffle1DFvPatchScalarField().
thermalBaffle1DFvPatchScalarField() [3/5]
thermalBaffle1DFvPatchScalarField (const thermalBaffle1DFvPatchScalarField< solidType > & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
thermalBaffle1DFvPatchScalarField onto a new patch
Definition at line 66 of file thermalBaffle1DFvPatchScalarField.C.
References thermalBaffle1DFvPatchScalarField< solidType >::thermalBaffle1DFvPatchScalarField().
thermalBaffle1DFvPatchScalarField() [4/5]
thermalBaffle1DFvPatchScalarField (const thermalBaffle1DFvPatchScalarField< solidType > & ptf)
Construct as copy.
Definition at line 146 of file thermalBaffle1DFvPatchScalarField.C.
References thermalBaffle1DFvPatchScalarField< solidType >::thermalBaffle1DFvPatchScalarField().
thermalBaffle1DFvPatchScalarField() [5/5]
thermalBaffle1DFvPatchScalarField (const thermalBaffle1DFvPatchScalarField< solidType > & ptf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 167 of file thermalBaffle1DFvPatchScalarField.C.
References thermalBaffle1DFvPatchScalarField< solidType >::autoMap(), fvPatch::boundaryMesh(), mapDistribute::distribute(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, mappedPatchBase::map(), patchi, and tmp< T >::ref().
Member Function Documentation
TypeName()
TypeName ("compressible::thermalBaffle1D")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 200 of file thermalBaffle1DFvPatchScalarField.H.
References thermalBaffle1DFvPatchScalarField< solidType >::thermalBaffle1DFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 217 of file thermalBaffle1DFvPatchScalarField.H.
References thermalBaffle1DFvPatchScalarField< solidType >::autoMap(), thermalBaffle1DFvPatchScalarField< solidType >::rmap(), thermalBaffle1DFvPatchScalarField< solidType >::thermalBaffle1DFvPatchScalarField(), thermalBaffle1DFvPatchScalarField< solidType >::updateCoeffs(), and thermalBaffle1DFvPatchScalarField< solidType >::write().
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Map (and resize as needed) from self given a mapping object.
Definition at line 297 of file thermalBaffle1DFvPatchScalarField.C.
References thermalBaffle1DFvPatchScalarField< solidType >::rmap().
Referenced by thermalBaffle1DFvPatchScalarField< solidType >::clone(), and thermalBaffle1DFvPatchScalarField< solidType >::thermalBaffle1DFvPatchScalarField().
rmap()
void rmap (const fvPatchScalarField & ptf, const labelList & addr) virtual
Reverse map the given fvPatchField onto this fvPatchField.
Definition at line 313 of file thermalBaffle1DFvPatchScalarField.C.
References thermalBaffle1DFvPatchScalarField< solidType >::rmap().
Referenced by thermalBaffle1DFvPatchScalarField< solidType >::autoMap(), thermalBaffle1DFvPatchScalarField< solidType >::clone(), and thermalBaffle1DFvPatchScalarField< solidType >::rmap().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 332 of file thermalBaffle1DFvPatchScalarField.C.
References Foam::constant::atomic::alpha, fvPatch::boundaryMesh(), mapDistribute::distribute(), Foam::endl(), forAll, Foam::gAverage(), Foam::gMax(), Foam::gMin(), Foam::Info, ThermalDiffusivity< BasicTurbulenceModel >::kappaEff(), mappedPatchBase::map(), UPstream::msgType(), fvPatch::name(), patchi, turbulenceModel::propertiesName, and Foam::fvc::snGrad().
Referenced by thermalBaffle1DFvPatchScalarField< solidType >::clone().
write()
void write (Ostream & os) const virtual
Write.
Reimplemented from mappedPatchBase.
Definition at line 425 of file thermalBaffle1DFvPatchScalarField.C.
References token::END_STATEMENT, Foam::nl, write(), mappedPatchBase::write(), and Ostream::writeKeyword().
Referenced by thermalBaffle1DFvPatchScalarField< solidType >::clone().
The documentation for this class was generated from the following files:
src/TurbulenceModels/compressible/turbulentFluidThermoModels/derivedFvPatchFields/thermalBaffle1D/thermalBaffle1DFvPatchScalarField.H
src/TurbulenceModels/compressible/turbulentFluidThermoModels/derivedFvPatchFields/thermalBaffle1D/thermalBaffle1DFvPatchScalarField.C