OpenFOAM: alphatWallFunctionFvPatchScalarField Class Reference
alphatWallFunctionFvPatchScalarField Class Reference
Compressible turbulence » Compressible Turbulence BCs » Compressible turbulence wall functions
This boundary condition provides a turbulent thermal diffusivity conditon when using wall functions.
Public Member Functions
TypeName ("compressible::alphatWallFunction")
Runtime type information.
alphatWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
alphatWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
alphatWallFunctionFvPatchScalarField (const alphatWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
alphatWallFunctionFvPatchScalarField (const alphatWallFunctionFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
alphatWallFunctionFvPatchScalarField (const alphatWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Detailed Description
This boundary condition provides a turbulent thermal diffusivity conditon when using wall functions.
- replicates OpenFOAM v1.5 (and earlier) behaviour
The turbulent thermal diffusivity calculated using:
where
= turblence thermal diffusivity
= turblence viscosity
= turblent Prandtl number
Usage
Property Description Required Default value
nut turbulence viscosity field name no nut
Prt turbulent Prandtl number no 0.85
Example of the boundary condition specification:
    <patchName>
    {
        type            alphatWallFunction;
        nut             nut;
        Prt             0.85;
        value           uniform 0; // optional value entry
    }
See also
Foam::fixedValueFvPatchField
Source files
alphatWallFunctionFvPatchScalarField.H
alphatWallFunctionFvPatchScalarField.C
Definition at line 117 of file alphatWallFunctionFvPatchScalarField.H.
Constructor & Destructor Documentation
alphatWallFunctionFvPatchScalarField() [1/5]
alphatWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 42 of file alphatWallFunctionFvPatchScalarField.C.
Referenced by alphatWallFunctionFvPatchScalarField::alphatWallFunctionFvPatchScalarField(), and alphatWallFunctionFvPatchScalarField::clone().
alphatWallFunctionFvPatchScalarField() [2/5]
alphatWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 66 of file alphatWallFunctionFvPatchScalarField.C.
References alphatWallFunctionFvPatchScalarField::alphatWallFunctionFvPatchScalarField().
alphatWallFunctionFvPatchScalarField() [3/5]
alphatWallFunctionFvPatchScalarField (const alphatWallFunctionFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
alphatWallFunctionFvPatchScalarField onto a new patch
Definition at line 53 of file alphatWallFunctionFvPatchScalarField.C.
References alphatWallFunctionFvPatchScalarField::alphatWallFunctionFvPatchScalarField().
alphatWallFunctionFvPatchScalarField() [4/5]
alphatWallFunctionFvPatchScalarField (const alphatWallFunctionFvPatchScalarField & awfpsf)
Construct as copy.
Definition at line 78 of file alphatWallFunctionFvPatchScalarField.C.
References alphatWallFunctionFvPatchScalarField::alphatWallFunctionFvPatchScalarField().
alphatWallFunctionFvPatchScalarField() [5/5]
alphatWallFunctionFvPatchScalarField (const alphatWallFunctionFvPatchScalarField & awfpsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 88 of file alphatWallFunctionFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("compressible::alphatWallFunction")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 168 of file alphatWallFunctionFvPatchScalarField.H.
References alphatWallFunctionFvPatchScalarField::alphatWallFunctionFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 185 of file alphatWallFunctionFvPatchScalarField.H.
References alphatWallFunctionFvPatchScalarField::alphatWallFunctionFvPatchScalarField(), alphatWallFunctionFvPatchScalarField::updateCoeffs(), and alphatWallFunctionFvPatchScalarField::write().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 100 of file alphatWallFunctionFvPatchScalarField.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), Foam::constant::atomic::group, IOobject::groupName(), turbulenceModel::nut(), Foam::operator==(), patchi, turbulenceModel::propertiesName, and compressibleTurbulenceModel::rho().
Referenced by alphatWallFunctionFvPatchScalarField::clone().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 129 of file alphatWallFunctionFvPatchScalarField.C.
References token::END_STATEMENT, Foam::compressible::makePatchTypeField(), Foam::nl, fvPatchField< Type >::write(), and Ostream::writeKeyword().
Referenced by alphatWallFunctionFvPatchScalarField::clone().
The documentation for this class was generated from the following files:
src/TurbulenceModels/compressible/turbulentFluidThermoModels/derivedFvPatchFields/wallFunctions/alphatWallFunctions/alphatWallFunction/alphatWallFunctionFvPatchScalarField.H
src/TurbulenceModels/compressible/turbulentFluidThermoModels/derivedFvPatchFields/wallFunctions/alphatWallFunctions/alphatWallFunction/alphatWallFunctionFvPatchScalarField.C