OpenFOAM: alphatJayatillekeWallFunctionFvPatchScalarField Class Reference
alphatJayatillekeWallFunctionFvPatchScalarField Class Reference
Incompressible turbulence » Incompressible Turbulence BCs » Incompressible turbulence wall functions
This boundary condition provides a kinematic turbulent thermal conductivity for using wall functions, using the Jayatilleke 'P' function.
Public Member Functions
TypeName ("alphatJayatillekeWallFunction")
Runtime type information.
alphatJayatillekeWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
alphatJayatillekeWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
alphatJayatillekeWallFunctionFvPatchScalarField (const alphatJayatillekeWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
alphatJayatillekeWallFunctionFvPatchScalarField (const alphatJayatillekeWallFunctionFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
alphatJayatillekeWallFunctionFvPatchScalarField (const alphatJayatillekeWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Protected Member Functions
virtual void checkType ()
Check the type of the patch.
scalar Psmooth (const scalar Prat) const
`P' function
scalar yPlusTherm (const scalar P, const scalar Prat) const
Calculate y+ at the edge of the thermal laminar sublayer.
Protected Attributes
scalar Prt_
Turbulent Prandtl number.
scalar Cmu_
Cmu coefficient.
scalar kappa_
Von Karman constant.
scalar E_
E coefficient.
Static Protected Attributes
static scalar tolerance_ = 0.01
static label maxIters_ = 10
Detailed Description
This boundary condition provides a kinematic turbulent thermal conductivity for using wall functions, using the Jayatilleke 'P' function.
Usage
Property Description Required Default value
Prt turbulent Prandtl number no 0.85
Cmu model coefficient no 0.09
kappa Von Karman constant no 0.41
E model coefficient no 9.8
Example of the boundary condition specification:
    <patchName>
    {
        type            alphatJayatillekeWallFunction;
    }
Note
The units of kinematic turbulent thermal conductivity are [m2/s]
See also
Foam::fixedValueFvPatchField
Source files
alphatJayatillekeWallFunctionFvPatchScalarField.H
alphatJayatillekeWallFunctionFvPatchScalarField.C
Definition at line 102 of file alphatJayatillekeWallFunctionFvPatchScalarField.H.
Constructor & Destructor Documentation
alphatJayatillekeWallFunctionFvPatchScalarField() [1/5]
alphatJayatillekeWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 106 of file alphatJayatillekeWallFunctionFvPatchScalarField.C.
References alphatJayatillekeWallFunctionFvPatchScalarField::checkType().
Referenced by alphatJayatillekeWallFunctionFvPatchScalarField::alphatJayatillekeWallFunctionFvPatchScalarField(), alphatJayatillekeWallFunctionFvPatchScalarField::clone(), and alphatJayatillekeWallFunctionFvPatchScalarField::yPlusTherm().
alphatJayatillekeWallFunctionFvPatchScalarField() [2/5]
alphatJayatillekeWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 142 of file alphatJayatillekeWallFunctionFvPatchScalarField.C.
References alphatJayatillekeWallFunctionFvPatchScalarField::alphatJayatillekeWallFunctionFvPatchScalarField(), and alphatJayatillekeWallFunctionFvPatchScalarField::checkType().
alphatJayatillekeWallFunctionFvPatchScalarField() [3/5]
alphatJayatillekeWallFunctionFvPatchScalarField (const alphatJayatillekeWallFunctionFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
alphatJayatillekeWallFunctionFvPatchScalarField onto a new patch
Definition at line 123 of file alphatJayatillekeWallFunctionFvPatchScalarField.C.
References alphatJayatillekeWallFunctionFvPatchScalarField::alphatJayatillekeWallFunctionFvPatchScalarField(), and alphatJayatillekeWallFunctionFvPatchScalarField::checkType().
alphatJayatillekeWallFunctionFvPatchScalarField() [4/5]
alphatJayatillekeWallFunctionFvPatchScalarField (const alphatJayatillekeWallFunctionFvPatchScalarField & wfpsf)
Construct as copy.
Definition at line 160 of file alphatJayatillekeWallFunctionFvPatchScalarField.C.
References alphatJayatillekeWallFunctionFvPatchScalarField::alphatJayatillekeWallFunctionFvPatchScalarField(), and alphatJayatillekeWallFunctionFvPatchScalarField::checkType().
alphatJayatillekeWallFunctionFvPatchScalarField() [5/5]
alphatJayatillekeWallFunctionFvPatchScalarField (const alphatJayatillekeWallFunctionFvPatchScalarField & wfpsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 176 of file alphatJayatillekeWallFunctionFvPatchScalarField.C.
References alphatJayatillekeWallFunctionFvPatchScalarField::checkType().
Member Function Documentation
checkType()
void checkType () protected virtual
Check the type of the patch.
Definition at line 47 of file alphatJayatillekeWallFunctionFvPatchScalarField.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, Foam::nl, and alphatJayatillekeWallFunctionFvPatchScalarField::Psmooth().
Referenced by alphatJayatillekeWallFunctionFvPatchScalarField::alphatJayatillekeWallFunctionFvPatchScalarField().
Psmooth()
scalar Psmooth (const scalar Prat) const protected
`P' function
Definition at line 62 of file alphatJayatillekeWallFunctionFvPatchScalarField.C.
References Foam::exp(), Foam::pow(), and alphatJayatillekeWallFunctionFvPatchScalarField::yPlusTherm().
Referenced by alphatJayatillekeWallFunctionFvPatchScalarField::checkType(), and alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs().
yPlusTherm()
scalar yPlusTherm (const scalar P, const scalar Prat) const protected
Calculate y+ at the edge of the thermal laminar sublayer.
Definition at line 71 of file alphatJayatillekeWallFunctionFvPatchScalarField.C.
References alphatJayatillekeWallFunctionFvPatchScalarField::alphatJayatillekeWallFunctionFvPatchScalarField(), alphatJayatillekeWallFunctionFvPatchScalarField::E_, f(), alphatJayatillekeWallFunctionFvPatchScalarField::kappa_, Foam::log(), Foam::mag(), alphatJayatillekeWallFunctionFvPatchScalarField::maxIters_, and alphatJayatillekeWallFunctionFvPatchScalarField::tolerance_.
Referenced by alphatJayatillekeWallFunctionFvPatchScalarField::Psmooth(), and alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs().
TypeName()
TypeName ("alphatJayatillekeWallFunction")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 186 of file alphatJayatillekeWallFunctionFvPatchScalarField.H.
References alphatJayatillekeWallFunctionFvPatchScalarField::alphatJayatillekeWallFunctionFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 203 of file alphatJayatillekeWallFunctionFvPatchScalarField.H.
References alphatJayatillekeWallFunctionFvPatchScalarField::alphatJayatillekeWallFunctionFvPatchScalarField(), alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs(), and alphatJayatillekeWallFunctionFvPatchScalarField::write().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 193 of file alphatJayatillekeWallFunctionFvPatchScalarField.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), alphatJayatillekeWallFunctionFvPatchScalarField::Cmu_, Foam::dimless, alphatJayatillekeWallFunctionFvPatchScalarField::E_, forAll, Foam::constant::atomic::group, IOobject::groupName(), k, turbulenceModel::k(), alphatJayatillekeWallFunctionFvPatchScalarField::kappa_, Foam::log(), dictionary::lookup(), Foam::max(), TurbulenceModel< Alpha, Rho, BasicTurbulenceModel, TransportModel >::nu(), nu, patchi, Foam::pow(), Pr(), turbulenceModel::propertiesName, alphatJayatillekeWallFunctionFvPatchScalarField::Prt_, alphatJayatillekeWallFunctionFvPatchScalarField::Psmooth(), Foam::sqrt(), fvPatchField< Type >::updateCoeffs(), y, turbulenceModel::y(), yPlus, and alphatJayatillekeWallFunctionFvPatchScalarField::yPlusTherm().
Referenced by alphatJayatillekeWallFunctionFvPatchScalarField::clone().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 268 of file alphatJayatillekeWallFunctionFvPatchScalarField.C.
References alphatJayatillekeWallFunctionFvPatchScalarField::Cmu_, alphatJayatillekeWallFunctionFvPatchScalarField::E_, token::END_STATEMENT, alphatJayatillekeWallFunctionFvPatchScalarField::kappa_, Foam::incompressible::makePatchTypeField(), Foam::nl, alphatJayatillekeWallFunctionFvPatchScalarField::Prt_, fvPatchField< Type >::write(), and Ostream::writeKeyword().
Referenced by alphatJayatillekeWallFunctionFvPatchScalarField::clone().
Member Data Documentation
Prt_
scalar Prt_ protected
Turbulent Prandtl number.
Definition at line 111 of file alphatJayatillekeWallFunctionFvPatchScalarField.H.
Referenced by alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs(), and alphatJayatillekeWallFunctionFvPatchScalarField::write().
Cmu_
scalar Cmu_ protected
Cmu coefficient.
Definition at line 114 of file alphatJayatillekeWallFunctionFvPatchScalarField.H.
Referenced by alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs(), and alphatJayatillekeWallFunctionFvPatchScalarField::write().
kappa_
scalar kappa_ protected
Von Karman constant.
Definition at line 117 of file alphatJayatillekeWallFunctionFvPatchScalarField.H.
Referenced by alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs(), alphatJayatillekeWallFunctionFvPatchScalarField::write(), and alphatJayatillekeWallFunctionFvPatchScalarField::yPlusTherm().
E_
scalar E_ protected
E coefficient.
Definition at line 120 of file alphatJayatillekeWallFunctionFvPatchScalarField.H.
Referenced by alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs(), alphatJayatillekeWallFunctionFvPatchScalarField::write(), and alphatJayatillekeWallFunctionFvPatchScalarField::yPlusTherm().
tolerance_
scalar tolerance_ = 0.01 static protected
Definition at line 125 of file alphatJayatillekeWallFunctionFvPatchScalarField.H.
Referenced by alphatJayatillekeWallFunctionFvPatchScalarField::yPlusTherm().
maxIters_
label maxIters_ = 10 static protected
Definition at line 126 of file alphatJayatillekeWallFunctionFvPatchScalarField.H.
Referenced by alphatJayatillekeWallFunctionFvPatchScalarField::yPlusTherm().
The documentation for this class was generated from the following files:
src/TurbulenceModels/incompressible/turbulentTransportModels/derivedFvPatchFields/wallFunctions/alphatWallFunctions/alphatJayatillekeWallFunction/alphatJayatillekeWallFunctionFvPatchScalarField.H
src/TurbulenceModels/incompressible/turbulentTransportModels/derivedFvPatchFields/wallFunctions/alphatWallFunctions/alphatJayatillekeWallFunction/alphatJayatillekeWallFunctionFvPatchScalarField.C