OpenFOAM: temperatureCoupledBase Class Reference
temperatureCoupledBase Class Reference
Common functions used in temperature coupled boundaries.
Public Types
enum KMethodType { mtFluidThermo, mtSolidThermo, mtDirectionalSolidThermo, mtLookup }
Type of supplied Kappa.
Public Member Functions
temperatureCoupledBase (const fvPatch &patch, const word &calculationMethod, const word &kappaName, const word &alphaAniName)
Construct from patch and K name.
temperatureCoupledBase (const fvPatch &patch, const dictionary &dict)
Construct from patch and dictionary.
temperatureCoupledBase (const fvPatch &patch, const temperatureCoupledBase &base)
Construct from patch and temperatureCoupledBase.
word KMethod () const
Method to obtain K.
const word & kappaName () const
Name of thermal conductivity field.
tmp< scalarField > kappa (const scalarField &Tp) const
Given patch temperature calculate corresponding K field.
void write (Ostream &) const
Write.
Protected Attributes
const fvPatch & patch_
Underlying patch.
const KMethodType method_
How to get K.
const word kappaName_
Name of thermal conductivity field (if looked up from database)
const word alphaAniName_
Name of the non-Isotropic alpha (default: Anialpha)
Static Protected Attributes
static const NamedEnum< KMethodType, 4 > KMethodTypeNames_
Detailed Description
Common functions used in temperature coupled boundaries.
The thermal conductivity kappa may be obtained by the following methods:
'lookup' : lookup volScalarField (or volSymmTensorField) with name defined by 'kappa'
'fluidThermo' : use fluidThermo and default compressible::turbulenceModel to calculate kappa
'solidThermo' : use solidThermo kappa()
'directionalSolidThermo': uses look up for volSymmTensorField for transformed kappa vector. Field name definable in 'alphaAni', named 'Anialpha' in solid solver by default
Keywords provided by this class:
Property Description Required Default value
kappaMethod Thermal conductivity method yes
kappa Name of thermal conductivity field no none
alphaAni Name of the non-isotropic alpha no Anialpha
Usage
nonIsotropicWall
{
    ...
    kappaMethod     directionalSolidThermo;
    kappa           none;
    alphaAni        Anialpha;
    ...
}
Source files
temperatureCoupledBase.H
temperatureCoupledBase.C
Definition at line 100 of file temperatureCoupledBase.H.
Member Enumeration Documentation
KMethodType
enum KMethodType
Type of supplied Kappa.
Enumerator
mtFluidThermo
mtSolidThermo
mtDirectionalSolidThermo
mtLookup
Definition at line 107 of file temperatureCoupledBase.H.
Constructor & Destructor Documentation
temperatureCoupledBase() [1/3]
temperatureCoupledBase (const fvPatch & patch, const word & calculationMethod, const word & kappaName, const word & alphaAniName)
Construct from patch and K name.
Definition at line 58 of file temperatureCoupledBase.C.
Referenced by NamedEnum< directionType, 3 >::names(), and temperatureCoupledBase::temperatureCoupledBase().
temperatureCoupledBase() [2/3]
temperatureCoupledBase (const fvPatch & patch, const dictionary & dict)
Construct from patch and dictionary.
Definition at line 73 of file temperatureCoupledBase.C.
References temperatureCoupledBase::temperatureCoupledBase().
temperatureCoupledBase() [3/3]
temperatureCoupledBase (const fvPatch & patch, const temperatureCoupledBase & base)
Construct from patch and temperatureCoupledBase.
Definition at line 86 of file temperatureCoupledBase.C.
References temperatureCoupledBase::kappa().
Member Function Documentation
KMethod()
word KMethod () const inline
Method to obtain K.
Definition at line 166 of file temperatureCoupledBase.H.
References temperatureCoupledBase::method_.
kappaName()
const word& kappaName () const inline
Name of thermal conductivity field.
Definition at line 172 of file temperatureCoupledBase.H.
References temperatureCoupledBase::kappa(), temperatureCoupledBase::kappaName_, and temperatureCoupledBase::write().
kappa()
Foam::tmp< Foam::scalarField > kappa (const scalarField & Tp) const
Given patch temperature calculate corresponding K field.
Definition at line 101 of file temperatureCoupledBase.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), polyMesh::boundaryMesh(), basicThermo::Cp(), dictionaryName::dictName(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, objectRegistry::foundObject(), Foam::constant::electromagnetic::kappa, basicThermo::kappa(), objectRegistry::lookupObject(), mesh, polyBoundaryMesh::mesh(), n, fvMesh::name(), Foam::nl, basicThermo::p(), patchi, and turbulenceModel::propertiesName.
Referenced by temperatureCoupledBase::kappaName(), temperatureCoupledBase::temperatureCoupledBase(), turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::updateCoeffs(), filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::updateCoeffs(), turbulentTemperatureRadCoupledMixedFvPatchScalarField::updateCoeffs(), and turbulentHeatFluxTemperatureFvPatchScalarField::updateCoeffs().
write()
void write (Ostream & os) const
Write.
Definition at line 225 of file temperatureCoupledBase.C.
References token::END_STATEMENT, Foam::nl, and Ostream::writeKeyword().
Referenced by temperatureCoupledBase::kappaName(), turbulentTemperatureCoupledBaffleMixedFvPatchScalarField::write(), filmPyrolysisRadiativeCoupledMixedFvPatchScalarField::write(), turbulentTemperatureRadCoupledMixedFvPatchScalarField::write(), turbulentHeatFluxTemperatureFvPatchScalarField::write(), and externalWallHeatFluxTemperatureFvPatchScalarField::write().
Member Data Documentation
KMethodTypeNames_
const Foam::NamedEnum< Foam::temperatureCoupledBase::KMethodType, 4 > KMethodTypeNames_ static protected
Definition at line 120 of file temperatureCoupledBase.H.
Referenced by NamedEnum< directionType, 3 >::names().
patch_
const fvPatch& patch_ protected
Underlying patch.
Definition at line 123 of file temperatureCoupledBase.H.
method_
const KMethodType method_ protected
How to get K.
Definition at line 126 of file temperatureCoupledBase.H.
Referenced by temperatureCoupledBase::KMethod().
kappaName_
const word kappaName_ protected
Name of thermal conductivity field (if looked up from database)
Definition at line 129 of file temperatureCoupledBase.H.
Referenced by temperatureCoupledBase::kappaName().
alphaAniName_
const word alphaAniName_ protected
Name of the non-Isotropic alpha (default: Anialpha)
Definition at line 132 of file temperatureCoupledBase.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/compressible/turbulentFluidThermoModels/derivedFvPatchFields/temperatureCoupledBase/temperatureCoupledBase.H
src/TurbulenceModels/compressible/turbulentFluidThermoModels/derivedFvPatchFields/temperatureCoupledBase/temperatureCoupledBase.C