OpenFOAM: LamBremhorstKE Class Reference
LamBremhorstKE Class Reference
Lam and Bremhorst low-Reynolds number k-epsilon turbulence model for incompressible flows.
Public Member Functions
TypeName ("LamBremhorstKE")
Runtime type information.
LamBremhorstKE (const geometricOneField &alpha, const geometricOneField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
Construct from components.
virtual ~LamBremhorstKE ()
Destructor.
virtual bool read ()
Read RASProperties dictionary.
tmp< volScalarField > DkEff () const
Return the effective diffusivity for k.
tmp< volScalarField > DepsilonEff () const
Return the effective diffusivity for epsilon.
virtual tmp< volScalarField > k () const
Return the turbulence kinetic energy.
virtual tmp< volScalarField > epsilon () const
Return the turbulence kinetic energy dissipation rate.
virtual void correct ()
Solve the turbulence equations and correct the turbulence viscosity.
Public Member Functions inherited from eddyViscosity< incompressible::RASModel >
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~eddyViscosity ()
Destructor.
volScalarField & evNut ()
Return non-const access to the turbulence viscosity.
virtual tmp< volScalarField > nut () const
Return the turbulence viscosity.
virtual tmp< scalarField > nut (const label patchi) const
Return the turbulence viscosity on patch.
virtual tmp< volSymmTensorField > R () const
Return the Reynolds stress tensor.
virtual void validate ()
Validate the turbulence fields after construction.
Public Member Functions inherited from linearViscousStress< incompressible::RASModel >
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~linearViscousStress ()
Destructor.
virtual tmp< volSymmTensorField > devRhoReff () const
Return the effective stress tensor.
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
Return the source term for the momentum equation.
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Return the source term for the momentum equation.
Protected Member Functions
virtual void correctNut ()
Protected Attributes
dimensionedScalar Cmu_
dimensionedScalar Ceps1_
dimensionedScalar Ceps2_
dimensionedScalar sigmaEps_
volScalarField k_
volScalarField epsilon_
const volScalarField & y_
Wall distance.
Protected Attributes inherited from eddyViscosity< incompressible::RASModel >
volScalarField nut_
Additional Inherited Members
Public Types inherited from eddyViscosity< incompressible::RASModel >
typedef incompressible::RASModel ::alphaField alphaField
typedef incompressible::RASModel ::rhoField rhoField
typedef incompressible::RASModel ::transportModel transportModel
Public Types inherited from linearViscousStress< incompressible::RASModel >
typedef incompressible::RASModel ::alphaField alphaField
typedef incompressible::RASModel ::rhoField rhoField
typedef incompressible::RASModel ::transportModel transportModel
Detailed Description
Lam and Bremhorst low-Reynolds number k-epsilon turbulence model for incompressible flows.
This turbulence model is described in:
    Lam, C. K. G., & Bremhorst, K. (1981).
    A modified form of the k-ε model for predicting wall turbulence.
    Journal of Fluids Engineering, 103(3), 456-460.
Source files
LamBremhorstKE.H
LamBremhorstKE.C
Definition at line 64 of file LamBremhorstKE.H.
Constructor & Destructor Documentation
LamBremhorstKE()
LamBremhorstKE (const geometricOneField & alpha, const geometricOneField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Construct from components.
Definition at line 90 of file LamBremhorstKE.C.
References Foam::bound(), LamBremhorstKE::epsilon_, and LamBremhorstKE::k_.
~LamBremhorstKE()
virtual ~LamBremhorstKE () inline virtual
Destructor.
Definition at line 127 of file LamBremhorstKE.H.
References LamBremhorstKE::read().
Member Function Documentation
correctNut()
void correctNut () protected virtual
Implements eddyViscosity< incompressible::RASModel >.
Definition at line 81 of file LamBremhorstKE.C.
Referenced by LamBremhorstKE::correct().
TypeName()
TypeName ("LamBremhorstKE")
Runtime type information.
read()
bool read () virtual
Read RASProperties dictionary.
Implements eddyViscosity< incompressible::RASModel >.
Definition at line 190 of file LamBremhorstKE.C.
References LamBremhorstKE::Ceps1_, LamBremhorstKE::Ceps2_, LamBremhorstKE::Cmu_, dimensioned< Type >::readIfPresent(), and LamBremhorstKE::sigmaEps_.
Referenced by LamBremhorstKE::~LamBremhorstKE().
DkEff()
tmp<volScalarField> DkEff () const inline
Return the effective diffusivity for k.
Definition at line 137 of file LamBremhorstKE.H.
References nu, and eddyViscosity< incompressible::RASModel >::nut_.
Referenced by LamBremhorstKE::correct().
DepsilonEff()
tmp<volScalarField> DepsilonEff () const inline
Return the effective diffusivity for epsilon.
Definition at line 146 of file LamBremhorstKE.H.
References nu, and eddyViscosity< incompressible::RASModel >::nut_.
Referenced by LamBremhorstKE::correct().
k()
virtual tmp<volScalarField> k () const inline virtual
Return the turbulence kinetic energy.
Implements eddyViscosity< incompressible::RASModel >.
Definition at line 155 of file LamBremhorstKE.H.
References LamBremhorstKE::k_.
epsilon()
virtual tmp<volScalarField> epsilon () const inline virtual
Return the turbulence kinetic energy dissipation rate.
Definition at line 161 of file LamBremhorstKE.H.
References LamBremhorstKE::correct(), and LamBremhorstKE::epsilon_.
correct()
void correct () virtual
Solve the turbulence equations and correct the turbulence viscosity.
Implements eddyViscosity< incompressible::RASModel >.
Definition at line 208 of file LamBremhorstKE.C.
References Foam::bound(), GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), LamBremhorstKE::Ceps1_, LamBremhorstKE::Ceps2_, tmp< T >::clear(), eddyViscosity< BasicTurbulenceModel >::correct(), LamBremhorstKE::correctNut(), Foam::fvm::ddt(), LamBremhorstKE::DepsilonEff(), Foam::fvm::div(), LamBremhorstKE::DkEff(), LamBremhorstKE::epsilon_, Foam::constant::universal::G, Foam::fvc::grad(), LamBremhorstKE::k_, Foam::fvm::laplacian(), eddyViscosity< incompressible::RASModel >::nut_, tmp< T >::ref(), Foam::solve(), Foam::fvm::Sp(), and Foam::twoSymm().
Referenced by LamBremhorstKE::epsilon().
Member Data Documentation
Cmu_
dimensionedScalar Cmu_ protected
Definition at line 85 of file LamBremhorstKE.H.
Referenced by LamBremhorstKE::read().
Ceps1_
dimensionedScalar Ceps1_ protected
Definition at line 86 of file LamBremhorstKE.H.
Referenced by LamBremhorstKE::correct(), and LamBremhorstKE::read().
Ceps2_
dimensionedScalar Ceps2_ protected
Definition at line 87 of file LamBremhorstKE.H.
Referenced by LamBremhorstKE::correct(), and LamBremhorstKE::read().
sigmaEps_
dimensionedScalar sigmaEps_ protected
Definition at line 88 of file LamBremhorstKE.H.
Referenced by LamBremhorstKE::read().
k_
volScalarField k_ protected
Definition at line 90 of file LamBremhorstKE.H.
Referenced by LamBremhorstKE::correct(), LamBremhorstKE::k(), and LamBremhorstKE::LamBremhorstKE().
epsilon_
volScalarField epsilon_ protected
Definition at line 91 of file LamBremhorstKE.H.
Referenced by LamBremhorstKE::correct(), LamBremhorstKE::epsilon(), and LamBremhorstKE::LamBremhorstKE().
y_
const volScalarField& y_ protected
Wall distance.
Note: different to wall distance in parent RASModel which is for near-wall cells only
Definition at line 96 of file LamBremhorstKE.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/incompressible/turbulentTransportModels/RAS/LamBremhorstKE/LamBremhorstKE.H
src/TurbulenceModels/incompressible/turbulentTransportModels/RAS/LamBremhorstKE/LamBremhorstKE.C