OpenFOAM: LienLeschziner Class Reference
LienLeschziner Class Reference
Lien and Leschziner low-Reynolds number k-epsilon turbulence model for incompressible flows.
Public Member Functions
TypeName ("LienLeschziner")
LienLeschziner (const geometricOneField &alpha, const geometricOneField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
Construct from components.
virtual ~LienLeschziner ()
Destructor.
virtual bool read ()
Read RASProperties dictionary.
tmp< volScalarField > DkEff () const
Return the effective diffusivity for k.
tmp< volScalarField > DepsilonEff () const
Return the effective diffusivity for epsilon.
virtual tmp< volScalarField > k () const
Return the turbulence kinetic energy.
virtual tmp< volScalarField > epsilon () const
Return the turbulence kinetic energy dissipation rate.
virtual void correct ()
Solve the turbulence equations and correct the turbulence viscosity.
Public Member Functions inherited from eddyViscosity< incompressible::RASModel >
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~eddyViscosity ()
Destructor.
volScalarField & evNut ()
Return non-const access to the turbulence viscosity.
virtual tmp< volScalarField > nut () const
Return the turbulence viscosity.
virtual tmp< scalarField > nut (const label patchi) const
Return the turbulence viscosity on patch.
virtual tmp< volSymmTensorField > R () const
Return the Reynolds stress tensor.
virtual void validate ()
Validate the turbulence fields after construction.
Public Member Functions inherited from linearViscousStress< incompressible::RASModel >
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~linearViscousStress ()
Destructor.
virtual tmp< volSymmTensorField > devRhoReff () const
Return the effective stress tensor.
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
Return the source term for the momentum equation.
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Return the source term for the momentum equation.
Protected Member Functions
tmp< volScalarField > fMu () const
tmp< volScalarField > f2 () const
tmp< volScalarField > E (const volScalarField &f2) const
virtual void correctNut ()
Protected Attributes
dimensionedScalar Ceps1_
dimensionedScalar Ceps2_
dimensionedScalar sigmak_
dimensionedScalar sigmaEps_
dimensionedScalar Cmu_
dimensionedScalar kappa_
dimensionedScalar Anu_
dimensionedScalar Aeps_
dimensionedScalar AE_
volScalarField k_
volScalarField epsilon_
const volScalarField & y_
Wall distance.
Protected Attributes inherited from eddyViscosity< incompressible::RASModel >
volScalarField nut_
Additional Inherited Members
Public Types inherited from eddyViscosity< incompressible::RASModel >
typedef incompressible::RASModel ::alphaField alphaField
typedef incompressible::RASModel ::rhoField rhoField
typedef incompressible::RASModel ::transportModel transportModel
Public Types inherited from linearViscousStress< incompressible::RASModel >
typedef incompressible::RASModel ::alphaField alphaField
typedef incompressible::RASModel ::rhoField rhoField
typedef incompressible::RASModel ::transportModel transportModel
Detailed Description
Lien and Leschziner low-Reynolds number k-epsilon turbulence model for incompressible flows.
This turbulence model is described in:
    Lien, F. S., & Leschziner, M. A. (1993).
    A pressure-velocity solution strategy for compressible flow
    and its application to shock/boundary-layer interaction
    using second-moment turbulence closure.
    Journal of fluids engineering, 115(4), 717-725.
Implemented according to the specification in: Apsley: Turbulence Models 2002
In addition to the low-Reynolds number damping functions support for wall-functions is also included to allow for low- and high-Reynolds number operation.
Source files
LienLeschziner.H
LienLeschziner.C
Definition at line 75 of file LienLeschziner.H.
Constructor & Destructor Documentation
LienLeschziner()
LienLeschziner (const geometricOneField & alpha, const geometricOneField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Construct from components.
Definition at line 89 of file LienLeschziner.C.
References Foam::bound(), LienLeschziner::epsilon_, and LienLeschziner::k_.
Referenced by LienLeschziner::correctNut().
~LienLeschziner()
virtual ~LienLeschziner () inline virtual
Destructor.
Definition at line 140 of file LienLeschziner.H.
References LienLeschziner::read().
Member Function Documentation
fMu()
tmp< volScalarField > fMu () const protected
Definition at line 47 of file LienLeschziner.C.
References LienLeschziner::Aeps_, LienLeschziner::Anu_, Foam::exp(), LienLeschziner::k_, nu, Foam::sqrt(), and LienLeschziner::y_.
Referenced by LienLeschziner::correctNut().
f2()
tmp< volScalarField > f2 () const protected
Definition at line 57 of file LienLeschziner.C.
References LienLeschziner::epsilon_, Foam::exp(), LienLeschziner::k_, nu, and Foam::sqr().
Referenced by LienLeschziner::correct().
E()
tmp< volScalarField > E (const volScalarField & f2) const protected
Definition at line 65 of file LienLeschziner.C.
References LienLeschziner::AE_, LienLeschziner::Aeps_, LienLeschziner::Ceps2_, LienLeschziner::Cmu_, LienLeschziner::epsilon_, Foam::exp(), LienLeschziner::k_, LienLeschziner::kappa_, nu, Foam::pow(), Foam::sqr(), Foam::sqrt(), and LienLeschziner::y_.
Referenced by LienLeschziner::correct().
correctNut()
void correctNut () protected virtual
Implements eddyViscosity< incompressible::RASModel >.
Definition at line 79 of file LienLeschziner.C.
References LienLeschziner::Cmu_, GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), LienLeschziner::epsilon_, LienLeschziner::fMu(), LienLeschziner::k_, LienLeschziner::LienLeschziner(), eddyViscosity< incompressible::RASModel >::nut_, and Foam::sqr().
Referenced by LienLeschziner::correct().
TypeName()
TypeName ("LienLeschziner")
read()
bool read () virtual
Read RASProperties dictionary.
Implements eddyViscosity< incompressible::RASModel >.
Definition at line 234 of file LienLeschziner.C.
References LienLeschziner::AE_, LienLeschziner::Aeps_, LienLeschziner::Anu_, LienLeschziner::Ceps1_, LienLeschziner::Ceps2_, LienLeschziner::Cmu_, LienLeschziner::kappa_, dimensioned< Type >::readIfPresent(), LienLeschziner::sigmaEps_, and LienLeschziner::sigmak_.
Referenced by LienLeschziner::~LienLeschziner().
DkEff()
tmp<volScalarField> DkEff () const inline
Return the effective diffusivity for k.
Definition at line 150 of file LienLeschziner.H.
References nu, and eddyViscosity< incompressible::RASModel >::nut_.
Referenced by LienLeschziner::correct().
DepsilonEff()
tmp<volScalarField> DepsilonEff () const inline
Return the effective diffusivity for epsilon.
Definition at line 159 of file LienLeschziner.H.
References nu, and eddyViscosity< incompressible::RASModel >::nut_.
Referenced by LienLeschziner::correct().
k()
virtual tmp<volScalarField> k () const inline virtual
Return the turbulence kinetic energy.
Implements eddyViscosity< incompressible::RASModel >.
Definition at line 168 of file LienLeschziner.H.
References LienLeschziner::k_.
epsilon()
virtual tmp<volScalarField> epsilon () const inline virtual
Return the turbulence kinetic energy dissipation rate.
Definition at line 174 of file LienLeschziner.H.
References LienLeschziner::correct(), and LienLeschziner::epsilon_.
correct()
void correct () virtual
Solve the turbulence equations and correct the turbulence viscosity.
Implements eddyViscosity< incompressible::RASModel >.
Definition at line 257 of file LienLeschziner.C.
References Foam::bound(), GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), LienLeschziner::Ceps1_, LienLeschziner::Ceps2_, tmp< T >::clear(), eddyViscosity< BasicTurbulenceModel >::correct(), LienLeschziner::correctNut(), Foam::fvm::ddt(), LienLeschziner::DepsilonEff(), Foam::fvm::div(), LienLeschziner::DkEff(), LienLeschziner::E(), LienLeschziner::epsilon_, LienLeschziner::f2(), Foam::constant::universal::G, Foam::fvc::grad(), LienLeschziner::k_, Foam::fvm::laplacian(), eddyViscosity< incompressible::RASModel >::nut_, tmp< T >::ref(), Foam::solve(), Foam::fvm::Sp(), and Foam::twoSymm().
Referenced by LienLeschziner::epsilon().
Member Data Documentation
Ceps1_
dimensionedScalar Ceps1_ protected
Definition at line 86 of file LienLeschziner.H.
Referenced by LienLeschziner::correct(), and LienLeschziner::read().
Ceps2_
dimensionedScalar Ceps2_ protected
Definition at line 87 of file LienLeschziner.H.
Referenced by LienLeschziner::correct(), LienLeschziner::E(), and LienLeschziner::read().
sigmak_
dimensionedScalar sigmak_ protected
Definition at line 88 of file LienLeschziner.H.
Referenced by LienLeschziner::read().
sigmaEps_
dimensionedScalar sigmaEps_ protected
Definition at line 89 of file LienLeschziner.H.
Referenced by LienLeschziner::read().
Cmu_
dimensionedScalar Cmu_ protected
Definition at line 91 of file LienLeschziner.H.
Referenced by LienLeschziner::correctNut(), LienLeschziner::E(), and LienLeschziner::read().
kappa_
dimensionedScalar kappa_ protected
Definition at line 92 of file LienLeschziner.H.
Referenced by LienLeschziner::E(), and LienLeschziner::read().
Anu_
dimensionedScalar Anu_ protected
Definition at line 94 of file LienLeschziner.H.
Referenced by LienLeschziner::fMu(), and LienLeschziner::read().
Aeps_
dimensionedScalar Aeps_ protected
Definition at line 95 of file LienLeschziner.H.
Referenced by LienLeschziner::E(), LienLeschziner::fMu(), and LienLeschziner::read().
AE_
dimensionedScalar AE_ protected
Definition at line 96 of file LienLeschziner.H.
Referenced by LienLeschziner::E(), and LienLeschziner::read().
k_
volScalarField k_ protected
Definition at line 101 of file LienLeschziner.H.
Referenced by LienLeschziner::correct(), LienLeschziner::correctNut(), LienLeschziner::E(), LienLeschziner::f2(), LienLeschziner::fMu(), LienLeschziner::k(), and LienLeschziner::LienLeschziner().
epsilon_
volScalarField epsilon_ protected
Definition at line 102 of file LienLeschziner.H.
Referenced by LienLeschziner::correct(), LienLeschziner::correctNut(), LienLeschziner::E(), LienLeschziner::epsilon(), LienLeschziner::f2(), and LienLeschziner::LienLeschziner().
y_
const volScalarField& y_ protected
Wall distance.
Note: different to wall distance in parent RASModel which is for near-wall cells only
Definition at line 107 of file LienLeschziner.H.
Referenced by LienLeschziner::E(), and LienLeschziner::fMu().
The documentation for this class was generated from the following files:
src/TurbulenceModels/incompressible/turbulentTransportModels/RAS/LienLeschziner/LienLeschziner.H
src/TurbulenceModels/incompressible/turbulentTransportModels/RAS/LienLeschziner/LienLeschziner.C