OpenFOAM: wallHeatTransferFvPatchScalarField Class Reference
wallHeatTransferFvPatchScalarField Class Reference
Boundary Conditions » Thermophysical boundary conditionsBoundary Conditions » | Wall boundary Conditions
This boundary condition provides an enthalpy condition for wall heat transfer.
Public Member Functions
TypeName ("wallHeatTransfer")
Runtime type information.
wallHeatTransferFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
wallHeatTransferFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
wallHeatTransferFvPatchScalarField (const wallHeatTransferFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given wallHeatTransferFvPatchScalarField.
wallHeatTransferFvPatchScalarField (const wallHeatTransferFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
wallHeatTransferFvPatchScalarField (const wallHeatTransferFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
const scalarField & Tinf () const
Return Tinf.
scalarField & Tinf ()
Return reference to Tinf to allow adjustment.
const scalarField & alphaWall () const
Return alphaWall.
scalarField & alphaWall ()
Return reference to alphaWall to allow adjustment.
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchScalarField &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Detailed Description
This boundary condition provides an enthalpy condition for wall heat transfer.
Usage
Property Description Required Default value
Tinf wall temperature yes
alphaWall thermal diffusivity yes
Example of the boundary condition specification:
    <patchName>
    {
        type            wallHeatTransfer;
        Tinf            uniform 500;
        alphaWall       uniform 1;
    }
Source files
wallHeatTransferFvPatchScalarField.H
wallHeatTransferFvPatchScalarField.C
Definition at line 84 of file wallHeatTransferFvPatchScalarField.H.
Constructor & Destructor Documentation
wallHeatTransferFvPatchScalarField() [1/5]
wallHeatTransferFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 34 of file wallHeatTransferFvPatchScalarField.C.
Referenced by wallHeatTransferFvPatchScalarField::clone(), and wallHeatTransferFvPatchScalarField::wallHeatTransferFvPatchScalarField().
wallHeatTransferFvPatchScalarField() [2/5]
wallHeatTransferFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 64 of file wallHeatTransferFvPatchScalarField.C.
References dictionary::found(), scalarField(), fvPatch::size(), and wallHeatTransferFvPatchScalarField::wallHeatTransferFvPatchScalarField().
wallHeatTransferFvPatchScalarField() [3/5]
wallHeatTransferFvPatchScalarField (const wallHeatTransferFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given wallHeatTransferFvPatchScalarField.
onto a new patch
Definition at line 50 of file wallHeatTransferFvPatchScalarField.C.
References wallHeatTransferFvPatchScalarField::wallHeatTransferFvPatchScalarField().
wallHeatTransferFvPatchScalarField() [4/5]
wallHeatTransferFvPatchScalarField (const wallHeatTransferFvPatchScalarField & tppsf)
Construct as copy.
Definition at line 93 of file wallHeatTransferFvPatchScalarField.C.
References wallHeatTransferFvPatchScalarField::wallHeatTransferFvPatchScalarField().
wallHeatTransferFvPatchScalarField() [5/5]
wallHeatTransferFvPatchScalarField (const wallHeatTransferFvPatchScalarField & tppsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 104 of file wallHeatTransferFvPatchScalarField.C.
References wallHeatTransferFvPatchScalarField::autoMap().
Member Function Documentation
TypeName()
TypeName ("wallHeatTransfer")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 137 of file wallHeatTransferFvPatchScalarField.H.
References wallHeatTransferFvPatchScalarField::wallHeatTransferFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 154 of file wallHeatTransferFvPatchScalarField.H.
References wallHeatTransferFvPatchScalarField::wallHeatTransferFvPatchScalarField().
Tinf() [1/2]
const scalarField& Tinf () const inline
Return Tinf.
Definition at line 170 of file wallHeatTransferFvPatchScalarField.H.
Tinf() [2/2]
scalarField& Tinf () inline
Return reference to Tinf to allow adjustment.
Definition at line 176 of file wallHeatTransferFvPatchScalarField.H.
alphaWall() [1/2]
const scalarField& alphaWall () const inline
Return alphaWall.
Definition at line 182 of file wallHeatTransferFvPatchScalarField.H.
alphaWall() [2/2]
scalarField& alphaWall () inline
Return reference to alphaWall to allow adjustment.
Definition at line 188 of file wallHeatTransferFvPatchScalarField.H.
References wallHeatTransferFvPatchScalarField::autoMap(), wallHeatTransferFvPatchScalarField::rmap(), wallHeatTransferFvPatchScalarField::updateCoeffs(), and wallHeatTransferFvPatchScalarField::write().
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Map (and resize as needed) from self given a mapping object.
Definition at line 118 of file wallHeatTransferFvPatchScalarField.C.
References wallHeatTransferFvPatchScalarField::rmap().
Referenced by wallHeatTransferFvPatchScalarField::alphaWall(), and wallHeatTransferFvPatchScalarField::wallHeatTransferFvPatchScalarField().
rmap()
void rmap (const fvPatchScalarField & ptf, const labelList & addr) virtual
Reverse map the given fvPatchField onto this fvPatchField.
Definition at line 129 of file wallHeatTransferFvPatchScalarField.C.
References wallHeatTransferFvPatchScalarField::rmap().
Referenced by wallHeatTransferFvPatchScalarField::alphaWall(), wallHeatTransferFvPatchScalarField::autoMap(), and wallHeatTransferFvPatchScalarField::rmap().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 144 of file wallHeatTransferFvPatchScalarField.C.
References Foam::constant::atomic::group, IOobject::groupName(), ThermalDiffusivity< BasicTurbulenceModel >::kappaEff(), patchi, and turbulenceModel::propertiesName.
Referenced by wallHeatTransferFvPatchScalarField::alphaWall().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 174 of file wallHeatTransferFvPatchScalarField.C.
References Foam::makePatchTypeField(), fvPatchField< Type >::write(), and Field< Type >::writeEntry().
Referenced by wallHeatTransferFvPatchScalarField::alphaWall().
The documentation for this class was generated from the following files:
src/TurbulenceModels/compressible/turbulentFluidThermoModels/derivedFvPatchFields/wallHeatTransfer/wallHeatTransferFvPatchScalarField.H
src/TurbulenceModels/compressible/turbulentFluidThermoModels/derivedFvPatchFields/wallHeatTransfer/wallHeatTransferFvPatchScalarField.C