OpenFOAM: Maxwell< BasicTurbulenceModel > Class Template Reference
Maxwell< BasicTurbulenceModel > Class Template Reference
Turbulence » laminar transport model
Maxwell model for viscoelasticity using the upper-convected time derivative of the stress tensor. See http://en.wikipedia.org/wiki/Upper-convected_Maxwell_model.
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from laminarModel< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("Maxwell")
Runtime type information.
Maxwell (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
Construct from components.
virtual ~Maxwell ()
Destructor.
virtual bool read ()
Read model coefficients if they have changed.
virtual tmp< volSymmTensorField > R () const
Return the Reynolds stress tensor.
virtual tmp< volSymmTensorField > devRhoReff () const
Return the effective stress tensor.
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
Return the source term for the momentum equation.
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Return the source term for the momentum equation.
virtual void correct ()
Solve the turbulence equations and correct eddy-Viscosity and.
Public Member Functions inherited from laminarModel< BasicTurbulenceModel >
TypeName ("laminar")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, laminarModel, dictionary,(const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName),(alpha, rho, U, alphaRhoPhi, phi, transport, propertiesName))
laminarModel (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~laminarModel ()
Destructor.
virtual const dictionary & coeffDict () const
Const access to the coefficients dictionary.
virtual tmp< volScalarField > nut () const
Return the turbulence viscosity, i.e. 0 for laminar flow.
virtual tmp< scalarField > nut (const label patchi) const
Return the turbulence viscosity on patch.
virtual tmp< volScalarField > nuEff () const
Return the effective viscosity, i.e. the laminar viscosity.
virtual tmp< scalarField > nuEff (const label patchi) const
Return the effective viscosity on patch.
virtual tmp< volScalarField > k () const
Return the turbulence kinetic energy, i.e. 0 for laminar flow.
virtual tmp< volScalarField > epsilon () const
Return the turbulence kinetic energy dissipation rate,.
Protected Member Functions
tmp< volScalarField > nu0 () const
Return the turbulence viscosity.
Protected Member Functions inherited from laminarModel< BasicTurbulenceModel >
virtual void printCoeffs (const word &type)
Print model coefficients.
Protected Attributes
dimensionedScalar nuM_
dimensionedScalar lambda_
volSymmTensorField sigma_
Protected Attributes inherited from laminarModel< BasicTurbulenceModel >
dictionary laminarDict_
laminar coefficients dictionary
Switch printCoeffs_
Flag to print the model coeffs at run-time.
dictionary coeffDict_
Model coefficients dictionary.
Additional Inherited Members
Static Public Member Functions inherited from laminarModel< BasicTurbulenceModel >
static autoPtr< laminarModel > New (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Return a reference to the selected laminar model.
Detailed Description
template<class BasicTurbulenceModel>
class Foam::laminarModels::Maxwell< BasicTurbulenceModel >
Maxwell model for viscoelasticity using the upper-convected time derivative of the stress tensor. See http://en.wikipedia.org/wiki/Upper-convected_Maxwell_model.
The model includes an additional viscosity (nu) from the transport model from which it is instantiated, which makes it equivalent to the Oldroyd-B model for the case of an incompressible transport model (where nu is non-zero). See https://en.wikipedia.org/wiki/Oldroyd-B_model
Reference:
    Amoreira, L. J., & Oliveira, P. J. (2010).
    Comparison of different formulations for the numerical calculation
    of unsteady incompressible viscoelastic fluid flow.
    Adv. Appl. Math. Mech, 4, 483-502.
Source files
Maxwell.H
Maxwell.C
Definition at line 70 of file Maxwell.H.
Member Typedef Documentation
alphaField
typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 101 of file Maxwell.H.
rhoField
typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 102 of file Maxwell.H.
transportModel
typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 103 of file Maxwell.H.
Constructor & Destructor Documentation
Maxwell()
Maxwell (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Construct from components.
Definition at line 40 of file Maxwell.C.
~Maxwell()
virtual ~Maxwell () inline virtual
Destructor.
Definition at line 127 of file Maxwell.H.
References Maxwell< BasicTurbulenceModel >::correct(), Maxwell< BasicTurbulenceModel >::devRhoReff(), Maxwell< BasicTurbulenceModel >::divDevRhoReff(), Maxwell< BasicTurbulenceModel >::R(), Maxwell< BasicTurbulenceModel >::read(), rho, and U.
Member Function Documentation
nu0()
tmp<volScalarField> nu0 () const inline protected
Return the turbulence viscosity.
Definition at line 93 of file Maxwell.H.
References nu, and Maxwell< BasicTurbulenceModel >::nuM_.
TypeName()
TypeName ("Maxwell< BasicTurbulenceModel >")
Runtime type information.
read()
bool read () virtual
Read model coefficients if they have changed.
Reimplemented from laminarModel< BasicTurbulenceModel >.
Definition at line 106 of file Maxwell.C.
Referenced by Maxwell< BasicTurbulenceModel >::~Maxwell().
R()
tmp< Foam::volSymmTensorField > R () const virtual
Return the Reynolds stress tensor.
Reimplemented from laminarModel< BasicTurbulenceModel >.
Definition at line 123 of file Maxwell.C.
Referenced by Maxwell< BasicTurbulenceModel >::~Maxwell().
devRhoReff()
tmp< Foam::volSymmTensorField > devRhoReff () const virtual
Return the effective stress tensor.
Definition at line 130 of file Maxwell.C.
References Foam::dev(), Maxwell< BasicTurbulenceModel >::divDevRhoReff(), Foam::fvc::grad(), IOobject::groupName(), IOobject::NO_READ, IOobject::NO_WRITE, nu, and Foam::twoSymm().
Referenced by Maxwell< BasicTurbulenceModel >::~Maxwell().
divDevRhoReff() [1/2]
tmp< Foam::fvVectorMatrix > divDevRhoReff (volVectorField & U) const virtual
Return the source term for the momentum equation.
Definition at line 155 of file Maxwell.C.
References Foam::dev2(), Foam::fvc::div(), Foam::fvc::grad(), Foam::fvm::laplacian(), nu, and Foam::T().
Referenced by Maxwell< BasicTurbulenceModel >::devRhoReff(), and Maxwell< BasicTurbulenceModel >::~Maxwell().
divDevRhoReff() [2/2]
tmp< Foam::fvVectorMatrix > divDevRhoReff (const volScalarField & rho, volVectorField & U) const virtual
Return the source term for the momentum equation.
Definition at line 175 of file Maxwell.C.
References Foam::dev2(), Foam::fvc::div(), Foam::fvc::grad(), Foam::fvm::laplacian(), nu, and Foam::T().
correct()
void correct () virtual
Solve the turbulence equations and correct eddy-Viscosity and.
related properties
Reimplemented from laminarModel< BasicTurbulenceModel >.
Definition at line 194 of file Maxwell.C.
References optionList::constrain(), laminarModel< BasicTurbulenceModel >::correct(), optionList::correct(), Foam::fvm::ddt(), Foam::fvm::div(), fvOptions, Foam::fvc::grad(), options::New(), tmp< T >::ref(), Foam::constant::physicoChemical::sigma, Foam::solve(), Foam::fvm::Sp(), and Foam::twoSymm().
Referenced by Maxwell< BasicTurbulenceModel >::~Maxwell().
Member Data Documentation
nuM_
dimensionedScalar nuM_ protected
Definition at line 81 of file Maxwell.H.
Referenced by Maxwell< BasicTurbulenceModel >::nu0().
lambda_
dimensionedScalar lambda_ protected
Definition at line 82 of file Maxwell.H.
sigma_
volSymmTensorField sigma_ protected
Definition at line 87 of file Maxwell.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/laminar/Maxwell/Maxwell.H
src/TurbulenceModels/turbulenceModels/laminar/Maxwell/Maxwell.C