OpenFOAM: laminarModel< BasicTurbulenceModel > Class Template Reference
laminarModel< BasicTurbulenceModel > Class Template Reference
Templated abstract base class for laminar transport models.
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("laminar")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, laminarModel, dictionary,(const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName),(alpha, rho, U, alphaRhoPhi, phi, transport, propertiesName))
laminarModel (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~laminarModel ()
Destructor.
virtual bool read ()
Read model coefficients if they have changed.
virtual const dictionary & coeffDict () const
Const access to the coefficients dictionary.
virtual tmp< volScalarField > nut () const
Return the turbulence viscosity, i.e. 0 for laminar flow.
virtual tmp< scalarField > nut (const label patchi) const
Return the turbulence viscosity on patch.
virtual tmp< volScalarField > nuEff () const
Return the effective viscosity, i.e. the laminar viscosity.
virtual tmp< scalarField > nuEff (const label patchi) const
Return the effective viscosity on patch.
virtual tmp< volScalarField > k () const
Return the turbulence kinetic energy, i.e. 0 for laminar flow.
virtual tmp< volScalarField > epsilon () const
Return the turbulence kinetic energy dissipation rate,.
virtual tmp< volSymmTensorField > R () const
Return the Reynolds stress tensor, i.e. 0 for laminar flow.
virtual void correct ()
Correct the laminar transport.
Static Public Member Functions
static autoPtr< laminarModel > New (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Return a reference to the selected laminar model.
Protected Member Functions
virtual void printCoeffs (const word &type)
Print model coefficients.
Protected Attributes
dictionary laminarDict_
laminar coefficients dictionary
Switch printCoeffs_
Flag to print the model coeffs at run-time.
dictionary coeffDict_
Model coefficients dictionary.
Detailed Description
template<class BasicTurbulenceModel>
class Foam::laminarModel< BasicTurbulenceModel >
Templated abstract base class for laminar transport models.
Source files
laminarModel.H
laminarModel.C
Definition at line 49 of file laminarModel.H.
Member Typedef Documentation
alphaField
typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 87 of file laminarModel.H.
rhoField
typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 88 of file laminarModel.H.
transportModel
typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 89 of file laminarModel.H.
Constructor & Destructor Documentation
laminarModel()
laminarModel (const word & type, const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName)
Construct from components.
Definition at line 45 of file laminarModel.C.
References laminarModel< BasicTurbulenceModel >::New().
~laminarModel()
virtual ~laminarModel () inline virtual
Destructor.
Definition at line 148 of file laminarModel.H.
References laminarModel< BasicTurbulenceModel >::read().
Member Function Documentation
printCoeffs()
void printCoeffs (const word & type) protected virtual
Print model coefficients.
Definition at line 32 of file laminarModel.C.
References Foam::endl(), and Foam::Info.
TypeName()
TypeName ("laminar")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , laminarModel< BasicTurbulenceModel > , dictionary , (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName) , (alpha, rho, U, alphaRhoPhi, phi, transport, propertiesName))
New()
Foam::autoPtr< Foam::laminarModel< BasicTurbulenceModel > > New (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName) static
Return a reference to the selected laminar model.
Definition at line 83 of file laminarModel.C.
References Foam::constant::atomic::alpha, TimePaths::constant(), IOobject::db(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, dictionary::found(), IOobject::group(), Foam::Info, dictionary::lookup(), Foam::nl, phi, rho, dictionary::subDict(), IOobject::time(), and U.
Referenced by laminarModel< BasicTurbulenceModel >::laminarModel().
read()
bool read () virtual
Read model coefficients if they have changed.
Reimplemented in Maxwell< BasicTurbulenceModel >, Stokes< BasicTurbulenceModel >, and linearViscousStress< laminarModel< BasicTurbulenceModel > >.
Definition at line 167 of file laminarModel.C.
References Foam::read(), and dictionary::subDictPtr().
Referenced by laminarModel< BasicTurbulenceModel >::~laminarModel().
coeffDict()
virtual const dictionary& coeffDict () const inline virtual
Const access to the coefficients dictionary.
Reimplemented in Stokes< BasicTurbulenceModel >.
Definition at line 161 of file laminarModel.H.
References laminarModel< BasicTurbulenceModel >::coeffDict_, laminarModel< BasicTurbulenceModel >::correct(), laminarModel< BasicTurbulenceModel >::epsilon(), laminarModel< BasicTurbulenceModel >::k(), laminarModel< BasicTurbulenceModel >::nuEff(), laminarModel< BasicTurbulenceModel >::nut(), patchi, and laminarModel< BasicTurbulenceModel >::R().
nut() [1/2]
Foam::tmp< Foam::volScalarField > nut () const virtual
Return the turbulence viscosity, i.e. 0 for laminar flow.
Reimplemented in Stokes< BasicTurbulenceModel >.
Definition at line 193 of file laminarModel.C.
References Foam::dimViscosity.
Referenced by laminarModel< BasicTurbulenceModel >::coeffDict().
nut() [2/2]
Foam::tmp< Foam::scalarField > nut (const label patchi) const virtual
Return the turbulence viscosity on patch.
Reimplemented in Stokes< BasicTurbulenceModel >.
Definition at line 218 of file laminarModel.C.
References patchi, and scalarField().
nuEff() [1/2]
Foam::tmp< Foam::volScalarField > nuEff () const virtual
Return the effective viscosity, i.e. the laminar viscosity.
Reimplemented in Stokes< BasicTurbulenceModel >.
Definition at line 231 of file laminarModel.C.
References nu.
Referenced by laminarModel< BasicTurbulenceModel >::coeffDict().
nuEff() [2/2]
Foam::tmp< Foam::scalarField > nuEff (const label patchi) const virtual
Return the effective viscosity on patch.
Reimplemented in Stokes< BasicTurbulenceModel >.
Definition at line 246 of file laminarModel.C.
References nu.
k()
Foam::tmp< Foam::volScalarField > k () const virtual
Return the turbulence kinetic energy, i.e. 0 for laminar flow.
Reimplemented in Stokes< BasicTurbulenceModel >.
Definition at line 256 of file laminarModel.C.
References Foam::sqr().
Referenced by laminarModel< BasicTurbulenceModel >::coeffDict().
epsilon()
Foam::tmp< Foam::volScalarField > epsilon () const virtual
Return the turbulence kinetic energy dissipation rate,.
i.e. 0 for laminar flow
Reimplemented in Stokes< BasicTurbulenceModel >.
Definition at line 280 of file laminarModel.C.
References Foam::dimTime, and Foam::sqr().
Referenced by laminarModel< BasicTurbulenceModel >::coeffDict().
R()
Foam::tmp< Foam::volSymmTensorField > R () const virtual
Return the Reynolds stress tensor, i.e. 0 for laminar flow.
Reimplemented in Maxwell< BasicTurbulenceModel >, and Stokes< BasicTurbulenceModel >.
Definition at line 307 of file laminarModel.C.
References Foam::sqr(), and Foam::Zero.
Referenced by laminarModel< BasicTurbulenceModel >::coeffDict().
correct()
void correct () virtual
Correct the laminar transport.
Reimplemented in Maxwell< BasicTurbulenceModel >, Stokes< BasicTurbulenceModel >, and linearViscousStress< laminarModel< BasicTurbulenceModel > >.
Definition at line 333 of file laminarModel.C.
References correct.
Referenced by laminarModel< BasicTurbulenceModel >::coeffDict(), Stokes< BasicTurbulenceModel >::correct(), and Maxwell< BasicTurbulenceModel >::correct().
Member Data Documentation
laminarDict_
dictionary laminarDict_ protected
laminar coefficients dictionary
Definition at line 59 of file laminarModel.H.
printCoeffs_
Switch printCoeffs_ protected
Flag to print the model coeffs at run-time.
Definition at line 62 of file laminarModel.H.
coeffDict_
dictionary coeffDict_ protected
Model coefficients dictionary.
Definition at line 65 of file laminarModel.H.
Referenced by laminarModel< BasicTurbulenceModel >::coeffDict().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/laminar/laminarModel/laminarModel.H
src/TurbulenceModels/turbulenceModels/laminar/laminarModel/laminarModel.C