OpenFOAM: eddyViscosity< BasicTurbulenceModel > Class Template Reference
eddyViscosity< BasicTurbulenceModel > Class Template Reference abstract
Turbulence
Eddy viscosity turbulence model base class.
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from linearViscousStress< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~eddyViscosity ()
Destructor.
virtual bool read ()=0
Re-read model coefficients if they have changed.
volScalarField & evNut ()
Return non-const access to the turbulence viscosity.
virtual tmp< volScalarField > nut () const
Return the turbulence viscosity.
virtual tmp< scalarField > nut (const label patchi) const
Return the turbulence viscosity on patch.
virtual tmp< volScalarField > k () const =0
Return the turbulence kinetic energy.
virtual tmp< volSymmTensorField > R () const
Return the Reynolds stress tensor.
virtual void validate ()
Validate the turbulence fields after construction.
virtual void correct ()=0
Solve the turbulence equations and correct the turbulence viscosity.
Public Member Functions inherited from linearViscousStress< BasicTurbulenceModel >
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~linearViscousStress ()
Destructor.
virtual tmp< volSymmTensorField > devRhoReff () const
Return the effective stress tensor.
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
Return the source term for the momentum equation.
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Return the source term for the momentum equation.
Protected Member Functions
virtual void correctNut ()=0
Protected Attributes
volScalarField nut_
Detailed Description
template<class BasicTurbulenceModel>
class Foam::eddyViscosity< BasicTurbulenceModel >
Eddy viscosity turbulence model base class.
Source files
eddyViscosity.H
eddyViscosity.C
Definition at line 52 of file eddyViscosity.H.
Member Typedef Documentation
alphaField
typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 73 of file eddyViscosity.H.
rhoField
typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 74 of file eddyViscosity.H.
transportModel
typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 75 of file eddyViscosity.H.
Constructor & Destructor Documentation
eddyViscosity()
eddyViscosity (const word & modelName, const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName)
Construct from components.
Definition at line 34 of file eddyViscosity.C.
~eddyViscosity()
virtual ~eddyViscosity () inline virtual
Destructor.
Definition at line 95 of file eddyViscosity.H.
Member Function Documentation
correctNut()
virtual void correctNut () protected pure virtual
Implemented in kOmegaSST< eddyViscosity< RASModel< BasicTurbulenceModel > >, BasicTurbulenceModel >, kkLOmega, v2f< BasicTurbulenceModel >, kOmegaSSTSato< BasicTurbulenceModel >, SpalartAllmarasDES< BasicTurbulenceModel >, SpalartAllmaras< BasicTurbulenceModel >, mixtureKEpsilon< BasicTurbulenceModel >, dynamicKEqn< BasicTurbulenceModel >, LienCubicKE, realizableKE< BasicTurbulenceModel >, LaunderSharmaKE< BasicTurbulenceModel >, RNGkEpsilon< BasicTurbulenceModel >, kEpsilon< BasicTurbulenceModel >, kEpsilon< EddyDiffusivity< compressible::turbulenceModel > >, LaheyKEpsilon< BasicTurbulenceModel >, LienLeschziner, NicenoKEqn< BasicTurbulenceModel >, Smagorinsky< BasicTurbulenceModel >, SmagorinskyZhang< BasicTurbulenceModel >, qZeta, continuousGasKEpsilon< BasicTurbulenceModel >, WALE< BasicTurbulenceModel >, LamBremhorstKE, kEqn< BasicTurbulenceModel >, kOmega< BasicTurbulenceModel >, ShihQuadraticKE, and dynamicLagrangian< BasicTurbulenceModel >.
read()
bool read () pure virtual
Re-read model coefficients if they have changed.
Implements linearViscousStress< BasicTurbulenceModel >.
Implemented in kOmegaSST< eddyViscosity< RASModel< BasicTurbulenceModel > >, BasicTurbulenceModel >, kOmegaSSTLM< BasicTurbulenceModel >, kkLOmega, mixtureKEpsilon< BasicTurbulenceModel >, v2f< BasicTurbulenceModel >, kOmegaSSTSato< BasicTurbulenceModel >, SpalartAllmarasDES< BasicTurbulenceModel >, SpalartAllmaras< BasicTurbulenceModel >, kineticTheoryModel, kineticTheoryModel, kOmegaSSTSAS< BasicTurbulenceModel >, dynamicKEqn< BasicTurbulenceModel >, LaunderSharmaKE< BasicTurbulenceModel >, realizableKE< BasicTurbulenceModel >, RNGkEpsilon< BasicTurbulenceModel >, LienCubicKE, LaheyKEpsilon< BasicTurbulenceModel >, kEpsilon< BasicTurbulenceModel >, kEpsilon< EddyDiffusivity< compressible::turbulenceModel > >, NicenoKEqn< BasicTurbulenceModel >, Smagorinsky< BasicTurbulenceModel >, SpalartAllmarasIDDES< BasicTurbulenceModel >, SmagorinskyZhang< BasicTurbulenceModel >, continuousGasKEpsilon< BasicTurbulenceModel >, LienLeschziner, WALE< BasicTurbulenceModel >, phasePressureModel, buoyantKEpsilon< BasicTurbulenceModel >, continuousGasKEqn< BasicTurbulenceModel >, qZeta, kEqn< BasicTurbulenceModel >, phasePressureModel, kOmega< BasicTurbulenceModel >, LamBremhorstKE, ShihQuadraticKE, dynamicLagrangian< BasicTurbulenceModel >, PDRkEpsilon, and LESeddyViscosity< BasicTurbulenceModel >.
Definition at line 75 of file eddyViscosity.C.
Referenced by eddyViscosity< RASModel< BasicTurbulenceModel > >::~eddyViscosity().
evNut()
volScalarField& evNut () inline
Return non-const access to the turbulence viscosity.
to allow modification by means other than derivation
Definition at line 106 of file eddyViscosity.H.
Referenced by eddyViscosity< RASModel< BasicTurbulenceModel > >::~eddyViscosity().
nut() [1/2]
virtual tmp<volScalarField> nut () const inline virtual
Return the turbulence viscosity.
Definition at line 112 of file eddyViscosity.H.
nut() [2/2]
virtual tmp<scalarField> nut (const label patchi) const inline virtual
Return the turbulence viscosity on patch.
Definition at line 118 of file eddyViscosity.H.
k()
virtual tmp<volScalarField> k () const pure virtual
Return the turbulence kinetic energy.
Implemented in kOmegaSST< eddyViscosity< RASModel< BasicTurbulenceModel > >, BasicTurbulenceModel >, kkLOmega, v2f< BasicTurbulenceModel >, mixtureKEpsilon< BasicTurbulenceModel >, kineticTheoryModel, kineticTheoryModel, SpalartAllmarasDES< BasicTurbulenceModel >, SpalartAllmaras< BasicTurbulenceModel >, LaunderSharmaKE< BasicTurbulenceModel >, realizableKE< BasicTurbulenceModel >, RNGkEpsilon< BasicTurbulenceModel >, kEpsilon< BasicTurbulenceModel >, kEpsilon< EddyDiffusivity< compressible::turbulenceModel > >, qZeta, LienCubicKE, dynamicKEqn< BasicTurbulenceModel >, LienLeschziner, kOmega< BasicTurbulenceModel >, phasePressureModel, LamBremhorstKE, ShihQuadraticKE, Smagorinsky< BasicTurbulenceModel >, phasePressureModel, WALE< BasicTurbulenceModel >, dynamicLagrangian< BasicTurbulenceModel >, and kEqn< BasicTurbulenceModel >.
Referenced by eddyViscosity< RASModel< BasicTurbulenceModel > >::nut().
R()
Foam::tmp< Foam::volSymmTensorField > R () const virtual
Return the Reynolds stress tensor.
Reimplemented in kineticTheoryModel, kineticTheoryModel, phasePressureModel, phasePressureModel, continuousGasKEpsilon< BasicTurbulenceModel >, nonlinearEddyViscosity< BasicTurbulenceModel >, and nonlinearEddyViscosity< incompressible::RASModel >.
Definition at line 83 of file eddyViscosity.C.
Referenced by eddyViscosity< RASModel< BasicTurbulenceModel > >::nut().
validate()
void validate () virtual
Validate the turbulence fields after construction.
Update turbulence viscosity and other derived fields as requires
Reimplemented in kkLOmega.
Definition at line 125 of file eddyViscosity.C.
Referenced by eddyViscosity< RASModel< BasicTurbulenceModel > >::nut().
correct()
void correct () pure virtual
Solve the turbulence equations and correct the turbulence viscosity.
Implements linearViscousStress< BasicTurbulenceModel >.
Implemented in kOmegaSST< eddyViscosity< RASModel< BasicTurbulenceModel > >, BasicTurbulenceModel >, kkLOmega, kOmegaSSTLM< BasicTurbulenceModel >, v2f< BasicTurbulenceModel >, mixtureKEpsilon< BasicTurbulenceModel >, kineticTheoryModel, kineticTheoryModel, qZeta, SpalartAllmarasDES< BasicTurbulenceModel >, LaunderSharmaKE< BasicTurbulenceModel >, realizableKE< BasicTurbulenceModel >, RNGkEpsilon< BasicTurbulenceModel >, kEpsilon< BasicTurbulenceModel >, kOmega< BasicTurbulenceModel >, kEpsilon< EddyDiffusivity< compressible::turbulenceModel > >, kOmegaSSTSato< BasicTurbulenceModel >, SpalartAllmaras< BasicTurbulenceModel >, LienCubicKE, dynamicKEqn< BasicTurbulenceModel >, phasePressureModel, LienLeschziner, phasePressureModel, LamBremhorstKE, ShihQuadraticKE, Smagorinsky< BasicTurbulenceModel >, LaheyKEpsilon< BasicTurbulenceModel >, kEqn< BasicTurbulenceModel >, dynamicLagrangian< BasicTurbulenceModel >, WALE< BasicTurbulenceModel >, and PDRkEpsilon.
Definition at line 132 of file eddyViscosity.C.
Referenced by LamBremhorstKE::correct(), ShihQuadraticKE::correct(), LienLeschziner::correct(), LienCubicKE::correct(), qZeta::correct(), kkLOmega::correct(), and eddyViscosity< RASModel< BasicTurbulenceModel > >::nut().
Member Data Documentation
nut_
volScalarField nut_ protected
Definition at line 63 of file eddyViscosity.H.
Referenced by eddyViscosity< RASModel< BasicTurbulenceModel > >::nut(), and eddyViscosity< RASModel< BasicTurbulenceModel > >::~eddyViscosity().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/eddyViscosity/eddyViscosity.H
src/TurbulenceModels/turbulenceModels/eddyViscosity/eddyViscosity.C