OpenFOAM: kOmegaSSTSato< BasicTurbulenceModel > Class Template Reference
kOmegaSSTSato< BasicTurbulenceModel > Class Template Reference
Turbulence » RAS turbulence
Implementation of the k-omega-SST turbulence model for dispersed bubbly flows with Sato (1981) bubble induced turbulent viscosity model.
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from kOmegaSST< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from kOmegaSST< eddyViscosity< RASModel< BasicTurbulenceModel > >, BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
typedef RASModel< BasicTurbulenceModel > ::alphaField alphaField
typedef RASModel< BasicTurbulenceModel > ::rhoField rhoField
typedef RASModel< BasicTurbulenceModel > ::transportModel transportModel
Public Types inherited from linearViscousStress< RASModel< BasicTurbulenceModel > >
typedef RASModel< BasicTurbulenceModel > ::alphaField alphaField
typedef RASModel< BasicTurbulenceModel > ::rhoField rhoField
typedef RASModel< BasicTurbulenceModel > ::transportModel transportModel
Public Types inherited from RASModel< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("kOmegaSSTSato")
Runtime type information.
kOmegaSSTSato (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
Construct from components.
virtual ~kOmegaSSTSato ()
Destructor.
virtual bool read ()
Read model coefficients if they have changed.
virtual void correct ()
Solve the turbulence equations and correct the turbulence viscosity.
Public Member Functions inherited from kOmegaSST< BasicTurbulenceModel >
TypeName ("kOmegaSST")
Runtime type information.
kOmegaSST (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
Construct from components.
virtual ~kOmegaSST ()
Destructor.
Public Member Functions inherited from kOmegaSST< eddyViscosity< RASModel< BasicTurbulenceModel > >, BasicTurbulenceModel >
kOmegaSST (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Construct from components.
tmp< volScalarField > DkEff (const volScalarField &F1) const
Return the effective diffusivity for k.
tmp< volScalarField > DomegaEff (const volScalarField &F1) const
Return the effective diffusivity for omega.
virtual tmp< volScalarField > k () const
Return the turbulence kinetic energy.
virtual tmp< volScalarField > epsilon () const
Return the turbulence kinetic energy dissipation rate.
virtual tmp< volScalarField > omega () const
Return the turbulence kinetic energy dissipation rate.
Public Member Functions inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~eddyViscosity ()
Destructor.
volScalarField & evNut ()
Return non-const access to the turbulence viscosity.
virtual tmp< volScalarField > nut () const
Return the turbulence viscosity.
virtual tmp< scalarField > nut (const label patchi) const
Return the turbulence viscosity on patch.
virtual tmp< volSymmTensorField > R () const
Return the Reynolds stress tensor.
virtual void validate ()
Validate the turbulence fields after construction.
Public Member Functions inherited from linearViscousStress< RASModel< BasicTurbulenceModel > >
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~linearViscousStress ()
Destructor.
virtual tmp< volSymmTensorField > devRhoReff () const
Return the effective stress tensor.
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
Return the source term for the momentum equation.
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Return the source term for the momentum equation.
Public Member Functions inherited from RASModel< BasicTurbulenceModel >
TypeName ("RAS")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, RASModel, dictionary,(const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName),(alpha, rho, U, alphaRhoPhi, phi, transport, propertiesName))
RASModel (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~RASModel ()
Destructor.
const dimensionedScalar & kMin () const
Return the lower allowable limit for k (default: SMALL)
const dimensionedScalar & epsilonMin () const
Return the lower allowable limit for epsilon (default: SMALL)
const dimensionedScalar & omegaMin () const
Return the lower allowable limit for omega (default: SMALL)
dimensionedScalar & kMin ()
Allow kMin to be changed.
dimensionedScalar & epsilonMin ()
Allow epsilonMin to be changed.
dimensionedScalar & omegaMin ()
Allow omegaMin to be changed.
virtual const dictionary & coeffDict () const
Const access to the coefficients dictionary.
virtual tmp< volScalarField > nuEff () const
Return the effective viscosity.
virtual tmp< scalarField > nuEff (const label patchi) const
Return the effective viscosity on patch.
Protected Member Functions
virtual void correctNut ()
Protected Member Functions inherited from kOmegaSST< eddyViscosity< RASModel< BasicTurbulenceModel > >, BasicTurbulenceModel >
virtual tmp< volScalarField > F1 (const volScalarField &CDkOmega) const
virtual tmp< volScalarField > F2 () const
virtual tmp< volScalarField > F3 () const
virtual tmp< volScalarField > F23 () const
tmp< volScalarField > blend (const volScalarField &F1, const dimensionedScalar &psi1, const dimensionedScalar &psi2) const
tmp< volScalarField::Internal > blend (const volScalarField::Internal &F1, const dimensionedScalar &psi1, const dimensionedScalar &psi2) const
tmp< volScalarField > alphaK (const volScalarField &F1) const
tmp< volScalarField > alphaOmega (const volScalarField &F1) const
tmp< volScalarField::Internal > beta (const volScalarField::Internal &F1) const
tmp< volScalarField::Internal > gamma (const volScalarField::Internal &F1) const
void correctNut (const volScalarField &S2, const volScalarField &F2)
virtual tmp< volScalarField::Internal > Pk (const volScalarField::Internal &G) const
Return k production rate.
virtual tmp< volScalarField::Internal > epsilonByk (const volScalarField::Internal &F1, const volScalarField::Internal &F2) const
Return epsilon/k which for standard RAS is betaStar*omega.
virtual tmp< fvScalarMatrix > kSource () const
virtual tmp< fvScalarMatrix > omegaSource () const
virtual tmp< fvScalarMatrix > Qsas (const volScalarField::Internal &S2, const volScalarField::Internal &gamma, const volScalarField::Internal &beta) const
Protected Member Functions inherited from RASModel< BasicTurbulenceModel >
virtual void printCoeffs (const word &type)
Print model coefficients.
Protected Attributes
dimensionedScalar Cmub_
Protected Attributes inherited from kOmegaSST< eddyViscosity< RASModel< BasicTurbulenceModel > >, BasicTurbulenceModel >
dimensionedScalar alphaK1_
dimensionedScalar alphaK2_
dimensionedScalar alphaOmega1_
dimensionedScalar alphaOmega2_
dimensionedScalar gamma1_
dimensionedScalar gamma2_
dimensionedScalar beta1_
dimensionedScalar beta2_
dimensionedScalar betaStar_
dimensionedScalar a1_
dimensionedScalar b1_
dimensionedScalar c1_
Switch F3_
const volScalarField & y_
Wall distance.
volScalarField k_
volScalarField omega_
Protected Attributes inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
volScalarField nut_
Protected Attributes inherited from RASModel< BasicTurbulenceModel >
dictionary RASDict_
RAS coefficients dictionary.
Switch turbulence_
Turbulence on/off flag.
Switch printCoeffs_
Flag to print the model coeffs at run-time.
dictionary coeffDict_
Model coefficients dictionary.
dimensionedScalar kMin_
Lower limit of k.
dimensionedScalar epsilonMin_
Lower limit of epsilon.
dimensionedScalar omegaMin_
Lower limit for omega.
Additional Inherited Members
Static Public Member Functions inherited from RASModel< BasicTurbulenceModel >
static autoPtr< RASModel > New (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Return a reference to the selected RAS model.
Detailed Description
template<class BasicTurbulenceModel>
class Foam::RASModels::kOmegaSSTSato< BasicTurbulenceModel >
Implementation of the k-omega-SST turbulence model for dispersed bubbly flows with Sato (1981) bubble induced turbulent viscosity model.
Bubble induced turbulent viscosity model described in:
    Sato, Y., Sadatomi, M.
    "Momentum and heat transfer in two-phase bubble flow - I, Theory"
    International Journal of Multiphase FLow 7, pp. 167-177, 1981.
Turbulence model described in:
    Menter, F., Esch, T.
    "Elements of Industrial Heat Transfer Prediction"
    16th Brazilian Congress of Mechanical Engineering (COBEM),
    Nov. 2001
with the addition of the optional F3 term for rough walls from
    Hellsten, A.
    "Some Improvements in Menters k-omega-SST turbulence model"
    29th AIAA Fluid Dynamics Conference,
    AIAA-98-2554,
    June 1998.
Note that this implementation is written in terms of alpha diffusion coefficients rather than the more traditional sigma (alpha = 1/sigma) so that the blending can be applied to all coefficuients in a consistent manner. The paper suggests that sigma is blended but this would not be consistent with the blending of the k-epsilon and k-omega models.
Also note that the error in the last term of equation (2) relating to sigma has been corrected.
Wall-functions are applied in this implementation by using equations (14) to specify the near-wall omega as appropriate.
The blending functions (15) and (16) are not currently used because of the uncertainty in their origin, range of applicability and that is y+ becomes sufficiently small blending u_tau in this manner clearly becomes nonsense.
The default model coefficients correspond to the following:
    kOmegaSSTCoeffs
    {
        alphaK1     0.85034;
        alphaK2     1.0;
        alphaOmega1 0.5;
        alphaOmega2 0.85616;
        Prt         1.0;    // only for compressible
        beta1       0.075;
        beta2       0.0828;
        betaStar    0.09;
        gamma1      0.5532;
        gamma2      0.4403;
        a1          0.31;
        b1          1.0;
        c1          10.0;
        F3          no;
        Cmub        0.6;
    }
Source files
kOmegaSSTSato.H
kOmegaSST.C
Source files
kOmegaSSTSato.H
kOmegaSSTSato.C
Definition at line 120 of file kOmegaSSTSato.H.
Member Typedef Documentation
alphaField
typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 162 of file kOmegaSSTSato.H.
rhoField
typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 163 of file kOmegaSSTSato.H.
transportModel
typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 164 of file kOmegaSSTSato.H.
Constructor & Destructor Documentation
kOmegaSSTSato()
kOmegaSSTSato (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Construct from components.
Definition at line 41 of file kOmegaSSTSato.C.
~kOmegaSSTSato()
virtual ~kOmegaSSTSato () inline virtual
Destructor.
Definition at line 188 of file kOmegaSSTSato.H.
References kOmegaSSTSato< BasicTurbulenceModel >::correct(), and kOmegaSSTSato< BasicTurbulenceModel >::read().
Member Function Documentation
correctNut()
void correctNut () protected virtual
Reimplemented from kOmegaSST< eddyViscosity< RASModel< BasicTurbulenceModel > >, BasicTurbulenceModel >.
Definition at line 133 of file kOmegaSSTSato.C.
References TurbulenceModel< volScalarField, volScalarField, compressibleTurbulenceModel, TransportModel >::alpha(), optionList::correct(), Foam::exp(), Foam::fvc::grad(), Foam::mag(), Foam::max(), options::New(), nu, Foam::pow(), Foam::sqr(), Foam::sqrt(), Foam::symm(), TurbulenceModel< volScalarField, volScalarField, compressibleTurbulenceModel, TransportModel >::transport(), turbulenceModel::U(), and yPlus.
TypeName()
TypeName ("kOmegaSSTSato< BasicTurbulenceModel >")
Runtime type information.
read()
bool read () virtual
Read model coefficients if they have changed.
Reimplemented from kOmegaSST< eddyViscosity< RASModel< BasicTurbulenceModel > >, BasicTurbulenceModel >.
Definition at line 86 of file kOmegaSSTSato.C.
References IOobject::db(), fluid, IOobject::groupName(), objectRegistry::lookupObject(), twoPhaseSystem::otherPhase(), and turbulenceModel::propertiesName.
Referenced by kOmegaSSTSato< BasicTurbulenceModel >::~kOmegaSSTSato().
correct()
void correct () virtual
Solve the turbulence equations and correct the turbulence viscosity.
Reimplemented from kOmegaSST< eddyViscosity< RASModel< BasicTurbulenceModel > >, BasicTurbulenceModel >.
Definition at line 162 of file kOmegaSSTSato.C.
References kOmegaSST< eddyViscosity< RASModel< BasicTurbulenceModel > >, BasicTurbulenceModel >::correct().
Referenced by kOmegaSSTSato< BasicTurbulenceModel >::~kOmegaSSTSato().
Member Data Documentation
Cmub_
dimensionedScalar Cmub_ protected
Definition at line 153 of file kOmegaSSTSato.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/phaseCompressible/RAS/kOmegaSSTSato/kOmegaSSTSato.H
src/TurbulenceModels/phaseCompressible/RAS/kOmegaSSTSato/kOmegaSSTSato.C