OpenFOAM: nutURoughWallFunctionFvPatchScalarField Class Reference
nutURoughWallFunctionFvPatchScalarField Class Reference
Turbulence » turbulence boundary conditions » wall functions
This boundary condition provides a turbulent kinematic viscosity condition when using wall functions for rough walls, based on velocity.
Public Member Functions
TypeName ("nutURoughWallFunction")
Runtime type information.
nutURoughWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
nutURoughWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
nutURoughWallFunctionFvPatchScalarField (const nutURoughWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
nutURoughWallFunctionFvPatchScalarField (const nutURoughWallFunctionFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
nutURoughWallFunctionFvPatchScalarField (const nutURoughWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
scalar roughnessHeight () const
Return the roughness height.
scalar & roughnessHeight ()
Return reference to the roughness height to allow adjustment.
scalar roughnessConstant () const
Return the roughness constant scale.
scalar & roughnessConstant ()
Return reference to the roughness constant to allow adjustment.
scalar roughnessFactor () const
Return the roughness scale factor.
scalar & roughnessFactor ()
Return reference to the roughness scale factor to allow.
virtual tmp< scalarField > yPlus () const
Calculate and return the yPlus at the boundary.
virtual void write (Ostream &os) const
Write.
Public Member Functions inherited from nutWallFunctionFvPatchScalarField
TypeName ("nutWallFunction")
Runtime type information.
nutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
nutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &)
Construct as copy.
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
scalar yPlusLam () const
Return the Y+ at the edge of the laminar sublayer.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
Additional Inherited Members
Static Public Member Functions inherited from nutWallFunctionFvPatchScalarField
static scalar yPlusLam (const scalar kappa, const scalar E)
Calculate the Y+ at the edge of the laminar sublayer.
Protected Member Functions inherited from nutWallFunctionFvPatchScalarField
virtual void checkType ()
Check the type of the patch.
virtual void writeLocalEntries (Ostream &) const
Write local wall function variables.
Protected Attributes inherited from nutWallFunctionFvPatchScalarField
scalar Cmu_
Cmu coefficient.
scalar kappa_
Von Karman constant.
scalar E_
E coefficient.
scalar yPlusLam_
Y+ at the edge of the laminar sublayer.
Detailed Description
This boundary condition provides a turbulent kinematic viscosity condition when using wall functions for rough walls, based on velocity.
Usage
Property Description Required Default value
roughnessHeight roughness height yes
roughnessConstant roughness constanr yes
roughnessFactor scaling factor yes
Example of the boundary condition specification:
    <patchName>
    {
        type            nutURoughWallFunction;
        roughnessHeight 1e-5;
        roughnessConstant 0.5;
        roughnessFactor 1;
    }
See also
Foam::nutWallFunctionFvPatchScalarField
Source files
nutURoughWallFunctionFvPatchScalarField.H
nutURoughWallFunctionFvPatchScalarField.C
Definition at line 94 of file nutURoughWallFunctionFvPatchScalarField.H.
Constructor & Destructor Documentation
nutURoughWallFunctionFvPatchScalarField() [1/5]
nutURoughWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 206 of file nutURoughWallFunctionFvPatchScalarField.C.
Referenced by nutURoughWallFunctionFvPatchScalarField::clone(), and nutURoughWallFunctionFvPatchScalarField::nutURoughWallFunctionFvPatchScalarField().
nutURoughWallFunctionFvPatchScalarField() [2/5]
nutURoughWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 234 of file nutURoughWallFunctionFvPatchScalarField.C.
References nutURoughWallFunctionFvPatchScalarField::nutURoughWallFunctionFvPatchScalarField().
nutURoughWallFunctionFvPatchScalarField() [3/5]
nutURoughWallFunctionFvPatchScalarField (const nutURoughWallFunctionFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
nutURoughWallFunctionFvPatchScalarField onto a new patch
Definition at line 219 of file nutURoughWallFunctionFvPatchScalarField.C.
References nutURoughWallFunctionFvPatchScalarField::nutURoughWallFunctionFvPatchScalarField().
nutURoughWallFunctionFvPatchScalarField() [4/5]
nutURoughWallFunctionFvPatchScalarField (const nutURoughWallFunctionFvPatchScalarField & rwfpsf)
Construct as copy.
Definition at line 248 of file nutURoughWallFunctionFvPatchScalarField.C.
References nutURoughWallFunctionFvPatchScalarField::nutURoughWallFunctionFvPatchScalarField().
nutURoughWallFunctionFvPatchScalarField() [5/5]
nutURoughWallFunctionFvPatchScalarField (const nutURoughWallFunctionFvPatchScalarField & rwfpsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 260 of file nutURoughWallFunctionFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("nutURoughWallFunction")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 162 of file nutURoughWallFunctionFvPatchScalarField.H.
References nutURoughWallFunctionFvPatchScalarField::nutURoughWallFunctionFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 179 of file nutURoughWallFunctionFvPatchScalarField.H.
References nutURoughWallFunctionFvPatchScalarField::nutURoughWallFunctionFvPatchScalarField().
roughnessHeight() [1/2]
scalar roughnessHeight () const inline
Return the roughness height.
Definition at line 195 of file nutURoughWallFunctionFvPatchScalarField.H.
roughnessHeight() [2/2]
scalar& roughnessHeight () inline
Return reference to the roughness height to allow adjustment.
Definition at line 201 of file nutURoughWallFunctionFvPatchScalarField.H.
roughnessConstant() [1/2]
scalar roughnessConstant () const inline
Return the roughness constant scale.
Definition at line 208 of file nutURoughWallFunctionFvPatchScalarField.H.
roughnessConstant() [2/2]
scalar& roughnessConstant () inline
Return reference to the roughness constant to allow adjustment.
Definition at line 214 of file nutURoughWallFunctionFvPatchScalarField.H.
roughnessFactor() [1/2]
scalar roughnessFactor () const inline
Return the roughness scale factor.
Definition at line 220 of file nutURoughWallFunctionFvPatchScalarField.H.
References nutURoughWallFunctionFvPatchScalarField::write(), and nutURoughWallFunctionFvPatchScalarField::yPlus().
roughnessFactor() [2/2]
scalar& roughnessFactor () inline
Return reference to the roughness scale factor to allow.
adjustment
Definition at line 227 of file nutURoughWallFunctionFvPatchScalarField.H.
yPlus()
tmp< scalarField > yPlus () const virtual
Calculate and return the yPlus at the boundary.
Implements nutWallFunctionFvPatchScalarField.
Definition at line 274 of file nutURoughWallFunctionFvPatchScalarField.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), Foam::constant::atomic::group, IOobject::groupName(), Foam::mag(), magUp, patchi, turbulenceModel::propertiesName, and turbulenceModel::U().
Referenced by nutURoughWallFunctionFvPatchScalarField::roughnessFactor().
write()
void write (Ostream & os) const virtual
Write.
Reimplemented from nutWallFunctionFvPatchScalarField.
Definition at line 293 of file nutURoughWallFunctionFvPatchScalarField.C.
References token::END_STATEMENT, Foam::makePatchTypeField(), Foam::nl, fvPatchField< Type >::write(), Ostream::writeKeyword(), and nutWallFunctionFvPatchScalarField::writeLocalEntries().
Referenced by nutURoughWallFunctionFvPatchScalarField::roughnessFactor().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/derivedFvPatchFields/wallFunctions/nutWallFunctions/nutURoughWallFunction/nutURoughWallFunctionFvPatchScalarField.H
src/TurbulenceModels/turbulenceModels/derivedFvPatchFields/wallFunctions/nutWallFunctions/nutURoughWallFunction/nutURoughWallFunctionFvPatchScalarField.C