OpenFOAM: nutkRoughWallFunctionFvPatchScalarField Class Reference
nutkRoughWallFunctionFvPatchScalarField Class Reference
Turbulence » turbulence boundary conditions » wall functions
This boundary condition provides a turbulent kinematic viscosity condition when using wall functions for rough walls, based on turbulence kinetic energy. The condition manipulates the E parameter to account for roughness effects.
Public Member Functions
TypeName ("nutkRoughWallFunction")
Runtime type information.
nutkRoughWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
nutkRoughWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
nutkRoughWallFunctionFvPatchScalarField (const nutkRoughWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
nutkRoughWallFunctionFvPatchScalarField (const nutkRoughWallFunctionFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
nutkRoughWallFunctionFvPatchScalarField (const nutkRoughWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
scalarField & Ks ()
scalarField & Cs ()
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchScalarField &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from nutkWallFunctionFvPatchScalarField
TypeName ("nutkWallFunction")
Runtime type information.
nutkWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
nutkWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
nutkWallFunctionFvPatchScalarField (const nutkWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
nutkWallFunctionFvPatchScalarField (const nutkWallFunctionFvPatchScalarField &)
Construct as copy.
nutkWallFunctionFvPatchScalarField (const nutkWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< scalarField > yPlus () const
Calculate and return the yPlus at the boundary.
Public Member Functions inherited from nutWallFunctionFvPatchScalarField
TypeName ("nutWallFunction")
Runtime type information.
nutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
nutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &)
Construct as copy.
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
scalar yPlusLam () const
Return the Y+ at the edge of the laminar sublayer.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
Protected Member Functions
virtual scalar fnRough (const scalar KsPlus, const scalar Cs) const
Compute the roughness function.
virtual tmp< scalarField > calcNut () const
Calculate the turbulence viscosity.
Protected Member Functions inherited from nutWallFunctionFvPatchScalarField
virtual void checkType ()
Check the type of the patch.
virtual void writeLocalEntries (Ostream &) const
Write local wall function variables.
Protected Attributes
scalarField Ks_
Roughness height.
scalarField Cs_
Roughness constant.
Protected Attributes inherited from nutWallFunctionFvPatchScalarField
scalar Cmu_
Cmu coefficient.
scalar kappa_
Von Karman constant.
scalar E_
E coefficient.
scalar yPlusLam_
Y+ at the edge of the laminar sublayer.
Additional Inherited Members
Static Public Member Functions inherited from nutWallFunctionFvPatchScalarField
static scalar yPlusLam (const scalar kappa, const scalar E)
Calculate the Y+ at the edge of the laminar sublayer.
Detailed Description
This boundary condition provides a turbulent kinematic viscosity condition when using wall functions for rough walls, based on turbulence kinetic energy. The condition manipulates the E parameter to account for roughness effects.
Parameter ranges
roughness height = sand-grain roughness (0 for smooth walls)
roughness constant = 0.5-1.0
Usage
Property Description Required Default value
Ks sand-grain roughness height yes
Cs roughness constant yes
Example of the boundary condition specification:
    <patchName>
    {
        type            nutkRoughWallFunction;
        Ks              uniform 0;
        Cs              uniform 0.5;
    }
See also
Foam::nutkRoughWallFunctionFvPatchScalarField
Source files
nutkRoughWallFunctionFvPatchScalarField.H
nutkRoughWallFunctionFvPatchScalarField.C
Definition at line 93 of file nutkRoughWallFunctionFvPatchScalarField.H.
Constructor & Destructor Documentation
nutkRoughWallFunctionFvPatchScalarField() [1/5]
nutkRoughWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 131 of file nutkRoughWallFunctionFvPatchScalarField.C.
Referenced by nutkRoughWallFunctionFvPatchScalarField::calcNut(), nutkRoughWallFunctionFvPatchScalarField::clone(), and nutkRoughWallFunctionFvPatchScalarField::nutkRoughWallFunctionFvPatchScalarField().
nutkRoughWallFunctionFvPatchScalarField() [2/5]
nutkRoughWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 157 of file nutkRoughWallFunctionFvPatchScalarField.C.
References nutkRoughWallFunctionFvPatchScalarField::nutkRoughWallFunctionFvPatchScalarField().
nutkRoughWallFunctionFvPatchScalarField() [3/5]
nutkRoughWallFunctionFvPatchScalarField (const nutkRoughWallFunctionFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
nutkRoughWallFunctionFvPatchScalarField onto a new patch
Definition at line 143 of file nutkRoughWallFunctionFvPatchScalarField.C.
References nutkRoughWallFunctionFvPatchScalarField::nutkRoughWallFunctionFvPatchScalarField().
nutkRoughWallFunctionFvPatchScalarField() [4/5]
nutkRoughWallFunctionFvPatchScalarField (const nutkRoughWallFunctionFvPatchScalarField & rwfpsf)
Construct as copy.
Definition at line 170 of file nutkRoughWallFunctionFvPatchScalarField.C.
References nutkRoughWallFunctionFvPatchScalarField::nutkRoughWallFunctionFvPatchScalarField().
nutkRoughWallFunctionFvPatchScalarField() [5/5]
nutkRoughWallFunctionFvPatchScalarField (const nutkRoughWallFunctionFvPatchScalarField & rwfpsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 181 of file nutkRoughWallFunctionFvPatchScalarField.C.
References nutkRoughWallFunctionFvPatchScalarField::autoMap().
Member Function Documentation
fnRough()
scalar fnRough (const scalar KsPlus, const scalar Cs) const protected virtual
Compute the roughness function.
Definition at line 40 of file nutkRoughWallFunctionFvPatchScalarField.C.
References Foam::log(), Foam::pow(), and Foam::sin().
Referenced by nutkRoughWallFunctionFvPatchScalarField::calcNut().
calcNut()
tmp< scalarField > calcNut () const protected virtual
Calculate the turbulence viscosity.
Reimplemented from nutkWallFunctionFvPatchScalarField.
Definition at line 62 of file nutkRoughWallFunctionFvPatchScalarField.C.
References nutWallFunctionFvPatchScalarField::Cmu_, nutkRoughWallFunctionFvPatchScalarField::Cs_, Foam::e, nutWallFunctionFvPatchScalarField::E_, Foam::endl(), nutkRoughWallFunctionFvPatchScalarField::fnRough(), forAll, Foam::constant::atomic::group, IOobject::groupName(), Foam::Info, k, turbulenceModel::k(), nutWallFunctionFvPatchScalarField::kappa_, nutkRoughWallFunctionFvPatchScalarField::Ks_, Foam::log(), Foam::max(), Foam::min(), turbulenceModel::nu(), nutkRoughWallFunctionFvPatchScalarField::nutkRoughWallFunctionFvPatchScalarField(), patchi, Foam::pow025(), turbulenceModel::propertiesName, tmp< T >::ref(), Foam::sqrt(), y, turbulenceModel::y(), and nutkWallFunctionFvPatchScalarField::yPlus().
TypeName()
TypeName ("nutkRoughWallFunction")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Reimplemented from nutkWallFunctionFvPatchScalarField.
Definition at line 158 of file nutkRoughWallFunctionFvPatchScalarField.H.
References nutkRoughWallFunctionFvPatchScalarField::nutkRoughWallFunctionFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Reimplemented from nutkWallFunctionFvPatchScalarField.
Definition at line 175 of file nutkRoughWallFunctionFvPatchScalarField.H.
References nutkRoughWallFunctionFvPatchScalarField::nutkRoughWallFunctionFvPatchScalarField().
Ks()
scalarField& Ks () inline
Definition at line 191 of file nutkRoughWallFunctionFvPatchScalarField.H.
References nutkRoughWallFunctionFvPatchScalarField::Ks_.
Cs()
scalarField& Cs () inline
Definition at line 197 of file nutkRoughWallFunctionFvPatchScalarField.H.
References nutkRoughWallFunctionFvPatchScalarField::autoMap(), nutkRoughWallFunctionFvPatchScalarField::Cs_, nutkRoughWallFunctionFvPatchScalarField::rmap(), and nutkRoughWallFunctionFvPatchScalarField::write().
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Map (and resize as needed) from self given a mapping object.
Definition at line 195 of file nutkRoughWallFunctionFvPatchScalarField.C.
References Field< Type >::autoMap(), nutkRoughWallFunctionFvPatchScalarField::Cs_, nutkRoughWallFunctionFvPatchScalarField::Ks_, and nutkRoughWallFunctionFvPatchScalarField::rmap().
Referenced by nutkRoughWallFunctionFvPatchScalarField::Cs(), and nutkRoughWallFunctionFvPatchScalarField::nutkRoughWallFunctionFvPatchScalarField().
rmap()
void rmap (const fvPatchScalarField & ptf, const labelList & addr) virtual
Reverse map the given fvPatchField onto this fvPatchField.
Definition at line 206 of file nutkRoughWallFunctionFvPatchScalarField.C.
References nutkRoughWallFunctionFvPatchScalarField::Cs_, nutkRoughWallFunctionFvPatchScalarField::Ks_, and Field< Type >::rmap().
Referenced by nutkRoughWallFunctionFvPatchScalarField::autoMap(), and nutkRoughWallFunctionFvPatchScalarField::Cs().
write()
void write (Ostream & os) const virtual
Write.
Reimplemented from nutWallFunctionFvPatchScalarField.
Definition at line 221 of file nutkRoughWallFunctionFvPatchScalarField.C.
References nutkRoughWallFunctionFvPatchScalarField::Cs_, nutkRoughWallFunctionFvPatchScalarField::Ks_, Foam::makePatchTypeField(), fvPatchField< Type >::write(), Field< Type >::writeEntry(), and nutWallFunctionFvPatchScalarField::writeLocalEntries().
Referenced by nutkRoughWallFunctionFvPatchScalarField::Cs().
Member Data Documentation
Ks_
scalarField Ks_ protected
Roughness height.
Definition at line 102 of file nutkRoughWallFunctionFvPatchScalarField.H.
Referenced by nutkRoughWallFunctionFvPatchScalarField::autoMap(), nutkRoughWallFunctionFvPatchScalarField::calcNut(), nutkRoughWallFunctionFvPatchScalarField::Ks(), nutkRoughWallFunctionFvPatchScalarField::rmap(), and nutkRoughWallFunctionFvPatchScalarField::write().
Cs_
scalarField Cs_ protected
Roughness constant.
Definition at line 105 of file nutkRoughWallFunctionFvPatchScalarField.H.
Referenced by nutkRoughWallFunctionFvPatchScalarField::autoMap(), nutkRoughWallFunctionFvPatchScalarField::calcNut(), nutkRoughWallFunctionFvPatchScalarField::Cs(), nutkRoughWallFunctionFvPatchScalarField::rmap(), and nutkRoughWallFunctionFvPatchScalarField::write().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/derivedFvPatchFields/wallFunctions/nutWallFunctions/nutkRoughWallFunction/nutkRoughWallFunctionFvPatchScalarField.H
src/TurbulenceModels/turbulenceModels/derivedFvPatchFields/wallFunctions/nutWallFunctions/nutkRoughWallFunction/nutkRoughWallFunctionFvPatchScalarField.C