OpenFOAM: fixedShearStressFvPatchVectorField Class Reference
fixedShearStressFvPatchVectorField Class Reference
Turbulence » turbulence boundary conditions
Set a constant shear stress as tau0 = -nuEff dU/dn.
Public Member Functions
TypeName ("fixedShearStress")
Runtime type information.
fixedShearStressFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
fixedShearStressFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
fixedShearStressFvPatchVectorField (const fixedShearStressFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
fixedShearStressFvPatchVectorField (const fixedShearStressFvPatchVectorField &)
Construct as copy.
virtual tmp< fvPatchVectorField > clone () const
Construct and return a clone.
fixedShearStressFvPatchVectorField (const fixedShearStressFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Detailed Description
Set a constant shear stress as tau0 = -nuEff dU/dn.
Source files
fixedShearStressFvPatchVectorField.H
fixedShearStressFvPatchVectorField.C
Definition at line 52 of file fixedShearStressFvPatchVectorField.H.
Constructor & Destructor Documentation
fixedShearStressFvPatchVectorField() [1/5]
fixedShearStressFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Construct from patch and internal field.
Definition at line 36 of file fixedShearStressFvPatchVectorField.C.
Referenced by fixedShearStressFvPatchVectorField::clone(), and fixedShearStressFvPatchVectorField::fixedShearStressFvPatchVectorField().
fixedShearStressFvPatchVectorField() [2/5]
fixedShearStressFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 47 of file fixedShearStressFvPatchVectorField.C.
References fixedShearStressFvPatchVectorField::fixedShearStressFvPatchVectorField().
fixedShearStressFvPatchVectorField() [3/5]
fixedShearStressFvPatchVectorField (const fixedShearStressFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
Definition at line 61 of file fixedShearStressFvPatchVectorField.C.
References fixedShearStressFvPatchVectorField::fixedShearStressFvPatchVectorField().
fixedShearStressFvPatchVectorField() [4/5]
fixedShearStressFvPatchVectorField (const fixedShearStressFvPatchVectorField & ptf)
Construct as copy.
Definition at line 74 of file fixedShearStressFvPatchVectorField.C.
References fixedShearStressFvPatchVectorField::fixedShearStressFvPatchVectorField().
fixedShearStressFvPatchVectorField() [5/5]
fixedShearStressFvPatchVectorField (const fixedShearStressFvPatchVectorField & ptf, const DimensionedField< vector, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 84 of file fixedShearStressFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("fixedShearStress")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchVectorField> clone () const inline virtual
Construct and return a clone.
Definition at line 101 of file fixedShearStressFvPatchVectorField.H.
References fixedShearStressFvPatchVectorField::fixedShearStressFvPatchVectorField().
clone() [2/2]
virtual tmp<fvPatchVectorField> clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 118 of file fixedShearStressFvPatchVectorField.H.
References fixedShearStressFvPatchVectorField::fixedShearStressFvPatchVectorField(), fixedShearStressFvPatchVectorField::updateCoeffs(), and fixedShearStressFvPatchVectorField::write().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 96 of file fixedShearStressFvPatchVectorField.C.
References Foam::constant::atomic::group, IOobject::groupName(), Foam::mag(), turbulenceModel::nuEff(), Foam::operator==(), and turbulenceModel::propertiesName.
Referenced by fixedShearStressFvPatchVectorField::clone().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 126 of file fixedShearStressFvPatchVectorField.C.
References token::END_STATEMENT, Foam::makePatchTypeField(), Foam::nl, write(), and Ostream::writeKeyword().
Referenced by fixedShearStressFvPatchVectorField::clone().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/derivedFvPatchFields/fixedShearStress/fixedShearStressFvPatchVectorField.H
src/TurbulenceModels/turbulenceModels/derivedFvPatchFields/fixedShearStress/fixedShearStressFvPatchVectorField.C