OpenFOAM: nutUTabulatedWallFunctionFvPatchScalarField Class Reference
nutUTabulatedWallFunctionFvPatchScalarField Class Reference
Turbulence » turbulence boundary conditions » wall functions
This boundary condition provides a turbulent kinematic viscosity condition when using wall functions. As input, the user specifies a look-up table of U+ as a function of near-wall Reynolds number. The table should be located in the $FOAM_CASE/constant directory.
Public Member Functions
TypeName ("nutTabulatedWallFunction")
Runtime type information.
nutUTabulatedWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
nutUTabulatedWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
nutUTabulatedWallFunctionFvPatchScalarField (const nutUTabulatedWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
nutUTabulatedWallFunctionFvPatchScalarField (const nutUTabulatedWallFunctionFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
nutUTabulatedWallFunctionFvPatchScalarField (const nutUTabulatedWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual tmp< scalarField > yPlus () const
Calculate and return the yPlus at the boundary.
virtual void write (Ostream &os) const
Write.
Public Member Functions inherited from nutWallFunctionFvPatchScalarField
TypeName ("nutWallFunction")
Runtime type information.
nutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
nutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &)
Construct as copy.
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
scalar yPlusLam () const
Return the Y+ at the edge of the laminar sublayer.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
Protected Member Functions
virtual tmp< scalarField > calcNut () const
Calculate the turbulence viscosity.
virtual tmp< scalarField > calcUPlus (const scalarField &Rey) const
Calculate wall u+ from table.
Protected Member Functions inherited from nutWallFunctionFvPatchScalarField
virtual void checkType ()
Check the type of the patch.
virtual void writeLocalEntries (Ostream &) const
Write local wall function variables.
Protected Attributes
word uPlusTableName_
Name of u+ table.
uniformInterpolationTable< scalar > uPlusTable_
U+ table.
Protected Attributes inherited from nutWallFunctionFvPatchScalarField
scalar Cmu_
Cmu coefficient.
scalar kappa_
Von Karman constant.
scalar E_
E coefficient.
scalar yPlusLam_
Y+ at the edge of the laminar sublayer.
Additional Inherited Members
Static Public Member Functions inherited from nutWallFunctionFvPatchScalarField
static scalar yPlusLam (const scalar kappa, const scalar E)
Calculate the Y+ at the edge of the laminar sublayer.
Detailed Description
This boundary condition provides a turbulent kinematic viscosity condition when using wall functions. As input, the user specifies a look-up table of U+ as a function of near-wall Reynolds number. The table should be located in the $FOAM_CASE/constant directory.
Usage
Property Description Required Default value
uPlusTable U+ as a function of Re table name yes
Example of the boundary condition specification:
    <patchName>
    {
        type            nutTabulatedWallFunction;
        uPlusTable      myUPlusTable;
    }
Note
The tables are not registered since the same table object may be used for more than one patch.
See also
Foam::nutWallFunctionFvPatchScalarField
Source files
nutUTabulatedWallFunctionFvPatchScalarField.H
nutUTabulatedWallFunctionFvPatchScalarField.C
Definition at line 87 of file nutUTabulatedWallFunctionFvPatchScalarField.H.
Constructor & Destructor Documentation
nutUTabulatedWallFunctionFvPatchScalarField() [1/5]
nutUTabulatedWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 90 of file nutUTabulatedWallFunctionFvPatchScalarField.C.
Referenced by nutUTabulatedWallFunctionFvPatchScalarField::calcUPlus(), nutUTabulatedWallFunctionFvPatchScalarField::clone(), and nutUTabulatedWallFunctionFvPatchScalarField::nutUTabulatedWallFunctionFvPatchScalarField().
nutUTabulatedWallFunctionFvPatchScalarField() [2/5]
nutUTabulatedWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 130 of file nutUTabulatedWallFunctionFvPatchScalarField.C.
References nutUTabulatedWallFunctionFvPatchScalarField::nutUTabulatedWallFunctionFvPatchScalarField().
nutUTabulatedWallFunctionFvPatchScalarField() [3/5]
nutUTabulatedWallFunctionFvPatchScalarField (const nutUTabulatedWallFunctionFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
nutUTabulatedWallFunctionFvPatchScalarField onto a new patch
Definition at line 115 of file nutUTabulatedWallFunctionFvPatchScalarField.C.
References nutUTabulatedWallFunctionFvPatchScalarField::nutUTabulatedWallFunctionFvPatchScalarField().
nutUTabulatedWallFunctionFvPatchScalarField() [4/5]
nutUTabulatedWallFunctionFvPatchScalarField (const nutUTabulatedWallFunctionFvPatchScalarField & wfpsf)
Construct as copy.
Definition at line 156 of file nutUTabulatedWallFunctionFvPatchScalarField.C.
References nutUTabulatedWallFunctionFvPatchScalarField::nutUTabulatedWallFunctionFvPatchScalarField().
nutUTabulatedWallFunctionFvPatchScalarField() [5/5]
nutUTabulatedWallFunctionFvPatchScalarField (const nutUTabulatedWallFunctionFvPatchScalarField & wfpsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 168 of file nutUTabulatedWallFunctionFvPatchScalarField.C.
Member Function Documentation
calcNut()
tmp< scalarField > calcNut () const protected virtual
Calculate the turbulence viscosity.
Implements nutWallFunctionFvPatchScalarField.
Definition at line 39 of file nutUTabulatedWallFunctionFvPatchScalarField.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), nutUTabulatedWallFunctionFvPatchScalarField::calcUPlus(), Foam::constant::atomic::group, IOobject::groupName(), Foam::mag(), magUp, Foam::max(), turbulenceModel::nu(), patchi, fvPatchField< Type >::patchInternalField(), turbulenceModel::propertiesName, fvPatchField< Type >::snGrad(), Foam::sqr(), turbulenceModel::U(), y, and turbulenceModel::y().
calcUPlus()
tmp< scalarField > calcUPlus (const scalarField & Rey) const protected virtual
Calculate wall u+ from table.
Definition at line 70 of file nutUTabulatedWallFunctionFvPatchScalarField.C.
References forAll, uniformInterpolationTable< Type >::interpolateLog10(), nutUTabulatedWallFunctionFvPatchScalarField::nutUTabulatedWallFunctionFvPatchScalarField(), tmp< T >::ref(), uPlus, and nutUTabulatedWallFunctionFvPatchScalarField::uPlusTable_.
Referenced by nutUTabulatedWallFunctionFvPatchScalarField::calcNut(), and nutUTabulatedWallFunctionFvPatchScalarField::yPlus().
TypeName()
TypeName ("nutTabulatedWallFunction")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 152 of file nutUTabulatedWallFunctionFvPatchScalarField.H.
References nutUTabulatedWallFunctionFvPatchScalarField::nutUTabulatedWallFunctionFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 169 of file nutUTabulatedWallFunctionFvPatchScalarField.H.
References nutUTabulatedWallFunctionFvPatchScalarField::nutUTabulatedWallFunctionFvPatchScalarField(), nutUTabulatedWallFunctionFvPatchScalarField::write(), and nutUTabulatedWallFunctionFvPatchScalarField::yPlus().
yPlus()
tmp< scalarField > yPlus () const virtual
Calculate and return the yPlus at the boundary.
Implements nutWallFunctionFvPatchScalarField.
Definition at line 181 of file nutUTabulatedWallFunctionFvPatchScalarField.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), nutUTabulatedWallFunctionFvPatchScalarField::calcUPlus(), Foam::constant::atomic::group, IOobject::groupName(), Foam::mag(), magUp, turbulenceModel::nu(), patchi, fvPatchField< Type >::patchInternalField(), turbulenceModel::propertiesName, Rey, turbulenceModel::U(), y, and turbulenceModel::y().
Referenced by nutUTabulatedWallFunctionFvPatchScalarField::clone().
write()
void write (Ostream & os) const virtual
Write.
Reimplemented from nutWallFunctionFvPatchScalarField.
Definition at line 204 of file nutUTabulatedWallFunctionFvPatchScalarField.C.
References token::END_STATEMENT, Foam::makePatchTypeField(), Foam::nl, nutUTabulatedWallFunctionFvPatchScalarField::uPlusTableName_, fvPatchField< Type >::write(), and Ostream::writeKeyword().
Referenced by nutUTabulatedWallFunctionFvPatchScalarField::clone().
Member Data Documentation
uPlusTableName_
word uPlusTableName_ protected
Name of u+ table.
Definition at line 96 of file nutUTabulatedWallFunctionFvPatchScalarField.H.
Referenced by nutUTabulatedWallFunctionFvPatchScalarField::write().
uPlusTable_
uniformInterpolationTable<scalar> uPlusTable_ protected
U+ table.
Definition at line 99 of file nutUTabulatedWallFunctionFvPatchScalarField.H.
Referenced by nutUTabulatedWallFunctionFvPatchScalarField::calcUPlus().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/derivedFvPatchFields/wallFunctions/nutWallFunctions/nutUTabulatedWallFunction/nutUTabulatedWallFunctionFvPatchScalarField.H
src/TurbulenceModels/turbulenceModels/derivedFvPatchFields/wallFunctions/nutWallFunctions/nutUTabulatedWallFunction/nutUTabulatedWallFunctionFvPatchScalarField.C