OpenFOAM: nutkAtmRoughWallFunctionFvPatchScalarField Class Reference
nutkAtmRoughWallFunctionFvPatchScalarField Class Reference
Turbulence » turbulence boundary conditions » wall functions
This boundary condition provides a turbulent kinematic viscosity for atmospheric velocity profiles. It is desinged to be used in conjunction with the atmBoundaryLayerInletVelocity boundary condition. The values are calculated using:
Public Member Functions
TypeName ("nutkAtmRoughWallFunction")
Runtime type information.
nutkAtmRoughWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
nutkAtmRoughWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
nutkAtmRoughWallFunctionFvPatchScalarField (const nutkAtmRoughWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
nutkAtmRoughWallFunctionFvPatchScalarField (const nutkAtmRoughWallFunctionFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
nutkAtmRoughWallFunctionFvPatchScalarField (const nutkAtmRoughWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
scalarField & z0 ()
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchScalarField &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from nutkWallFunctionFvPatchScalarField
TypeName ("nutkWallFunction")
Runtime type information.
nutkWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
nutkWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
nutkWallFunctionFvPatchScalarField (const nutkWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
nutkWallFunctionFvPatchScalarField (const nutkWallFunctionFvPatchScalarField &)
Construct as copy.
nutkWallFunctionFvPatchScalarField (const nutkWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< scalarField > yPlus () const
Calculate and return the yPlus at the boundary.
Public Member Functions inherited from nutWallFunctionFvPatchScalarField
TypeName ("nutWallFunction")
Runtime type information.
nutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
nutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &)
Construct as copy.
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
scalar yPlusLam () const
Return the Y+ at the edge of the laminar sublayer.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
Protected Member Functions
virtual tmp< scalarField > calcNut () const
Calculate the turbulence viscosity.
Protected Member Functions inherited from nutWallFunctionFvPatchScalarField
virtual void checkType ()
Check the type of the patch.
virtual void writeLocalEntries (Ostream &) const
Write local wall function variables.
Protected Attributes
scalarField z0_
Surface roughness length.
Protected Attributes inherited from nutWallFunctionFvPatchScalarField
scalar Cmu_
Cmu coefficient.
scalar kappa_
Von Karman constant.
scalar E_
E coefficient.
scalar yPlusLam_
Y+ at the edge of the laminar sublayer.
Additional Inherited Members
Static Public Member Functions inherited from nutWallFunctionFvPatchScalarField
static scalar yPlusLam (const scalar kappa, const scalar E)
Calculate the Y+ at the edge of the laminar sublayer.
Detailed Description
This boundary condition provides a turbulent kinematic viscosity for atmospheric velocity profiles. It is desinged to be used in conjunction with the atmBoundaryLayerInletVelocity boundary condition. The values are calculated using:
where
= frictional velocity
= Von Karman's constant
= surface roughness length
= vertical co-ordinate
Usage
Property Description Required Default value
z0 surface roughness length yes
Example of the boundary condition specification:
    <patchName>
    {
        type            nutkAtmRoughWallFunction;
        z0              uniform 0;
    }
See also
Foam::nutkWallFunctionFvPatchField
Source files
nutkAtmRoughWallFunctionFvPatchScalarField.H
nutkAtmRoughWallFunctionFvPatchScalarField.C
Definition at line 111 of file nutkAtmRoughWallFunctionFvPatchScalarField.H.
Constructor & Destructor Documentation
nutkAtmRoughWallFunctionFvPatchScalarField() [1/5]
nutkAtmRoughWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 91 of file nutkAtmRoughWallFunctionFvPatchScalarField.C.
Referenced by nutkAtmRoughWallFunctionFvPatchScalarField::calcNut(), nutkAtmRoughWallFunctionFvPatchScalarField::clone(), and nutkAtmRoughWallFunctionFvPatchScalarField::nutkAtmRoughWallFunctionFvPatchScalarField().
nutkAtmRoughWallFunctionFvPatchScalarField() [2/5]
nutkAtmRoughWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 117 of file nutkAtmRoughWallFunctionFvPatchScalarField.C.
References nutkAtmRoughWallFunctionFvPatchScalarField::nutkAtmRoughWallFunctionFvPatchScalarField().
nutkAtmRoughWallFunctionFvPatchScalarField() [3/5]
nutkAtmRoughWallFunctionFvPatchScalarField (const nutkAtmRoughWallFunctionFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
nutkAtmRoughWallFunctionFvPatchScalarField onto a new patch
Definition at line 103 of file nutkAtmRoughWallFunctionFvPatchScalarField.C.
References nutkAtmRoughWallFunctionFvPatchScalarField::nutkAtmRoughWallFunctionFvPatchScalarField().
nutkAtmRoughWallFunctionFvPatchScalarField() [4/5]
nutkAtmRoughWallFunctionFvPatchScalarField (const nutkAtmRoughWallFunctionFvPatchScalarField & rwfpsf)
Construct as copy.
Definition at line 130 of file nutkAtmRoughWallFunctionFvPatchScalarField.C.
References nutkAtmRoughWallFunctionFvPatchScalarField::nutkAtmRoughWallFunctionFvPatchScalarField().
nutkAtmRoughWallFunctionFvPatchScalarField() [5/5]
nutkAtmRoughWallFunctionFvPatchScalarField (const nutkAtmRoughWallFunctionFvPatchScalarField & rwfpsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 141 of file nutkAtmRoughWallFunctionFvPatchScalarField.C.
References nutkAtmRoughWallFunctionFvPatchScalarField::autoMap().
Member Function Documentation
calcNut()
tmp< scalarField > calcNut () const protected virtual
Calculate the turbulence viscosity.
Reimplemented from nutkWallFunctionFvPatchScalarField.
Definition at line 39 of file nutkAtmRoughWallFunctionFvPatchScalarField.C.
References nutWallFunctionFvPatchScalarField::Cmu_, Foam::e, Foam::endl(), forAll, Foam::constant::atomic::group, IOobject::groupName(), Foam::Info, k, turbulenceModel::k(), nutWallFunctionFvPatchScalarField::kappa_, Foam::log(), Foam::max(), turbulenceModel::nu(), nutkAtmRoughWallFunctionFvPatchScalarField::nutkAtmRoughWallFunctionFvPatchScalarField(), patchi, Foam::pow025(), turbulenceModel::propertiesName, tmp< T >::ref(), Foam::sqrt(), y, turbulenceModel::y(), nutkWallFunctionFvPatchScalarField::yPlus(), and nutkAtmRoughWallFunctionFvPatchScalarField::z0_.
TypeName()
TypeName ("nutkAtmRoughWallFunction")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Reimplemented from nutkWallFunctionFvPatchScalarField.
Definition at line 171 of file nutkAtmRoughWallFunctionFvPatchScalarField.H.
References nutkAtmRoughWallFunctionFvPatchScalarField::nutkAtmRoughWallFunctionFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Reimplemented from nutkWallFunctionFvPatchScalarField.
Definition at line 188 of file nutkAtmRoughWallFunctionFvPatchScalarField.H.
References nutkAtmRoughWallFunctionFvPatchScalarField::nutkAtmRoughWallFunctionFvPatchScalarField().
z0()
scalarField& z0 () inline
Definition at line 204 of file nutkAtmRoughWallFunctionFvPatchScalarField.H.
References nutkAtmRoughWallFunctionFvPatchScalarField::autoMap(), nutkAtmRoughWallFunctionFvPatchScalarField::rmap(), nutkAtmRoughWallFunctionFvPatchScalarField::write(), and nutkAtmRoughWallFunctionFvPatchScalarField::z0_.
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Map (and resize as needed) from self given a mapping object.
Definition at line 154 of file nutkAtmRoughWallFunctionFvPatchScalarField.C.
References Field< Type >::autoMap(), nutkAtmRoughWallFunctionFvPatchScalarField::rmap(), and nutkAtmRoughWallFunctionFvPatchScalarField::z0_.
Referenced by nutkAtmRoughWallFunctionFvPatchScalarField::nutkAtmRoughWallFunctionFvPatchScalarField(), and nutkAtmRoughWallFunctionFvPatchScalarField::z0().
rmap()
void rmap (const fvPatchScalarField & ptf, const labelList & addr) virtual
Reverse map the given fvPatchField onto this fvPatchField.
Definition at line 164 of file nutkAtmRoughWallFunctionFvPatchScalarField.C.
References Field< Type >::rmap(), and nutkAtmRoughWallFunctionFvPatchScalarField::z0_.
Referenced by nutkAtmRoughWallFunctionFvPatchScalarField::autoMap(), and nutkAtmRoughWallFunctionFvPatchScalarField::z0().
write()
void write (Ostream & os) const virtual
Write.
Reimplemented from nutWallFunctionFvPatchScalarField.
Definition at line 178 of file nutkAtmRoughWallFunctionFvPatchScalarField.C.
References Foam::makePatchTypeField(), fvPatchField< Type >::write(), Field< Type >::writeEntry(), nutWallFunctionFvPatchScalarField::writeLocalEntries(), and nutkAtmRoughWallFunctionFvPatchScalarField::z0_.
Referenced by nutkAtmRoughWallFunctionFvPatchScalarField::z0().
Member Data Documentation
z0_
scalarField z0_ protected
Surface roughness length.
Definition at line 120 of file nutkAtmRoughWallFunctionFvPatchScalarField.H.
Referenced by nutkAtmRoughWallFunctionFvPatchScalarField::autoMap(), nutkAtmRoughWallFunctionFvPatchScalarField::calcNut(), nutkAtmRoughWallFunctionFvPatchScalarField::rmap(), nutkAtmRoughWallFunctionFvPatchScalarField::write(), and nutkAtmRoughWallFunctionFvPatchScalarField::z0().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/derivedFvPatchFields/wallFunctions/nutWallFunctions/nutkAtmRoughWallFunction/nutkAtmRoughWallFunctionFvPatchScalarField.H
src/TurbulenceModels/turbulenceModels/derivedFvPatchFields/wallFunctions/nutWallFunctions/nutkAtmRoughWallFunction/nutkAtmRoughWallFunctionFvPatchScalarField.C