OpenFOAM: nutLowReWallFunctionFvPatchScalarField Class Reference
nutLowReWallFunctionFvPatchScalarField Class Reference
Turbulence » turbulence boundary conditions » wall functions
This boundary condition provides a turbulent kinematic viscosity condition for use with low Reynolds number models. It sets nut to zero, and provides an access function to calculate y+.
Public Member Functions
TypeName ("nutLowReWallFunction")
Runtime type information.
nutLowReWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
nutLowReWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
nutLowReWallFunctionFvPatchScalarField (const nutLowReWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
nutLowReWallFunctionFvPatchScalarField (const nutLowReWallFunctionFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
nutLowReWallFunctionFvPatchScalarField (const nutLowReWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual tmp< scalarField > yPlus () const
Calculate and return the yPlus at the boundary.
Public Member Functions inherited from nutWallFunctionFvPatchScalarField
TypeName ("nutWallFunction")
Runtime type information.
nutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
nutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &)
Construct as copy.
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
scalar yPlusLam () const
Return the Y+ at the edge of the laminar sublayer.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Protected Member Functions
virtual tmp< scalarField > calcNut () const
Calculate the turbulence viscosity.
Protected Member Functions inherited from nutWallFunctionFvPatchScalarField
virtual void checkType ()
Check the type of the patch.
virtual void writeLocalEntries (Ostream &) const
Write local wall function variables.
Additional Inherited Members
Static Public Member Functions inherited from nutWallFunctionFvPatchScalarField
static scalar yPlusLam (const scalar kappa, const scalar E)
Calculate the Y+ at the edge of the laminar sublayer.
Protected Attributes inherited from nutWallFunctionFvPatchScalarField
scalar Cmu_
Cmu coefficient.
scalar kappa_
Von Karman constant.
scalar E_
E coefficient.
scalar yPlusLam_
Y+ at the edge of the laminar sublayer.
Detailed Description
This boundary condition provides a turbulent kinematic viscosity condition for use with low Reynolds number models. It sets nut to zero, and provides an access function to calculate y+.
Usage
Example of the boundary condition specification:
<patchName>
{
    type            nutLowReWallFunction;
}
See also
Foam::nutWallFunctionFvPatchScalarField
Source files
nutLowReWallFunctionFvPatchScalarField.H
nutLowReWallFunctionFvPatchScalarField.C
Definition at line 65 of file nutLowReWallFunctionFvPatchScalarField.H.
Constructor & Destructor Documentation
nutLowReWallFunctionFvPatchScalarField() [1/5]
nutLowReWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 48 of file nutLowReWallFunctionFvPatchScalarField.C.
Referenced by nutLowReWallFunctionFvPatchScalarField::calcNut(), nutLowReWallFunctionFvPatchScalarField::clone(), and nutLowReWallFunctionFvPatchScalarField::nutLowReWallFunctionFvPatchScalarField().
nutLowReWallFunctionFvPatchScalarField() [2/5]
nutLowReWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 70 of file nutLowReWallFunctionFvPatchScalarField.C.
References nutLowReWallFunctionFvPatchScalarField::nutLowReWallFunctionFvPatchScalarField().
nutLowReWallFunctionFvPatchScalarField() [3/5]
nutLowReWallFunctionFvPatchScalarField (const nutLowReWallFunctionFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
nutLowReWallFunctionFvPatchScalarField onto a new patch
Definition at line 58 of file nutLowReWallFunctionFvPatchScalarField.C.
References nutLowReWallFunctionFvPatchScalarField::nutLowReWallFunctionFvPatchScalarField().
nutLowReWallFunctionFvPatchScalarField() [4/5]
nutLowReWallFunctionFvPatchScalarField (const nutLowReWallFunctionFvPatchScalarField & nlrwfpsf)
Construct as copy.
Definition at line 81 of file nutLowReWallFunctionFvPatchScalarField.C.
References nutLowReWallFunctionFvPatchScalarField::nutLowReWallFunctionFvPatchScalarField().
nutLowReWallFunctionFvPatchScalarField() [5/5]
nutLowReWallFunctionFvPatchScalarField (const nutLowReWallFunctionFvPatchScalarField & nlrwfpsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 90 of file nutLowReWallFunctionFvPatchScalarField.C.
Member Function Documentation
calcNut()
tmp< scalarField > calcNut () const protected virtual
Calculate the turbulence viscosity.
Implements nutWallFunctionFvPatchScalarField.
Definition at line 39 of file nutLowReWallFunctionFvPatchScalarField.C.
References nutLowReWallFunctionFvPatchScalarField::nutLowReWallFunctionFvPatchScalarField().
TypeName()
TypeName ("nutLowReWallFunction")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 118 of file nutLowReWallFunctionFvPatchScalarField.H.
References nutLowReWallFunctionFvPatchScalarField::nutLowReWallFunctionFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 135 of file nutLowReWallFunctionFvPatchScalarField.H.
References nutLowReWallFunctionFvPatchScalarField::nutLowReWallFunctionFvPatchScalarField(), and nutLowReWallFunctionFvPatchScalarField::yPlus().
yPlus()
tmp< scalarField > yPlus () const virtual
Calculate and return the yPlus at the boundary.
Implements nutWallFunctionFvPatchScalarField.
Definition at line 101 of file nutLowReWallFunctionFvPatchScalarField.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), Foam::constant::atomic::group, IOobject::groupName(), Foam::mag(), Foam::makePatchTypeField(), turbulenceModel::nu(), patchi, turbulenceModel::propertiesName, fvPatchField< Type >::snGrad(), Foam::sqrt(), turbulenceModel::U(), y, and turbulenceModel::y().
Referenced by nutLowReWallFunctionFvPatchScalarField::clone().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/derivedFvPatchFields/wallFunctions/nutWallFunctions/nutLowReWallFunction/nutLowReWallFunctionFvPatchScalarField.H
src/TurbulenceModels/turbulenceModels/derivedFvPatchFields/wallFunctions/nutWallFunctions/nutLowReWallFunction/nutLowReWallFunctionFvPatchScalarField.C