OpenFOAM: nutkWallFunctionFvPatchScalarField Class Reference
nutkWallFunctionFvPatchScalarField Class Reference
Turbulence » turbulence boundary conditions » wall functions
This boundary condition provides a turbulent kinematic viscosity condition when using wall functions, based on turbulence kinetic energy.
Public Member Functions
TypeName ("nutkWallFunction")
Runtime type information.
nutkWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
nutkWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
nutkWallFunctionFvPatchScalarField (const nutkWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
nutkWallFunctionFvPatchScalarField (const nutkWallFunctionFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
nutkWallFunctionFvPatchScalarField (const nutkWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual tmp< scalarField > yPlus () const
Calculate and return the yPlus at the boundary.
Public Member Functions inherited from nutWallFunctionFvPatchScalarField
TypeName ("nutWallFunction")
Runtime type information.
nutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
nutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &)
Construct as copy.
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
scalar yPlusLam () const
Return the Y+ at the edge of the laminar sublayer.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Protected Member Functions
virtual tmp< scalarField > calcNut () const
Calculate the turbulence viscosity.
Protected Member Functions inherited from nutWallFunctionFvPatchScalarField
virtual void checkType ()
Check the type of the patch.
virtual void writeLocalEntries (Ostream &) const
Write local wall function variables.
Additional Inherited Members
Static Public Member Functions inherited from nutWallFunctionFvPatchScalarField
static scalar yPlusLam (const scalar kappa, const scalar E)
Calculate the Y+ at the edge of the laminar sublayer.
Protected Attributes inherited from nutWallFunctionFvPatchScalarField
scalar Cmu_
Cmu coefficient.
scalar kappa_
Von Karman constant.
scalar E_
E coefficient.
scalar yPlusLam_
Y+ at the edge of the laminar sublayer.
Detailed Description
This boundary condition provides a turbulent kinematic viscosity condition when using wall functions, based on turbulence kinetic energy.
- replicates OpenFOAM v1.5 (and earlier) behaviour
Usage
Example of the boundary condition specification:
<patchName>
{
    type            nutkWallFunction;
}
See also
Foam::nutWallFunctionFvPatchScalarField
Source files
nutkWallFunctionFvPatchScalarField.H
nutkWallFunctionFvPatchScalarField.C
Definition at line 65 of file nutkWallFunctionFvPatchScalarField.H.
Constructor & Destructor Documentation
nutkWallFunctionFvPatchScalarField() [1/5]
nutkWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 83 of file nutkWallFunctionFvPatchScalarField.C.
Referenced by nutkWallFunctionFvPatchScalarField::calcNut(), nutkWallFunctionFvPatchScalarField::clone(), and nutkWallFunctionFvPatchScalarField::nutkWallFunctionFvPatchScalarField().
nutkWallFunctionFvPatchScalarField() [2/5]
nutkWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 105 of file nutkWallFunctionFvPatchScalarField.C.
References nutkWallFunctionFvPatchScalarField::nutkWallFunctionFvPatchScalarField().
nutkWallFunctionFvPatchScalarField() [3/5]
nutkWallFunctionFvPatchScalarField (const nutkWallFunctionFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
nutkWallFunctionFvPatchScalarField onto a new patch
Definition at line 93 of file nutkWallFunctionFvPatchScalarField.C.
References nutkWallFunctionFvPatchScalarField::nutkWallFunctionFvPatchScalarField().
nutkWallFunctionFvPatchScalarField() [4/5]
nutkWallFunctionFvPatchScalarField (const nutkWallFunctionFvPatchScalarField & wfpsf)
Construct as copy.
Definition at line 116 of file nutkWallFunctionFvPatchScalarField.C.
References nutkWallFunctionFvPatchScalarField::nutkWallFunctionFvPatchScalarField().
nutkWallFunctionFvPatchScalarField() [5/5]
nutkWallFunctionFvPatchScalarField (const nutkWallFunctionFvPatchScalarField & wfpsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 125 of file nutkWallFunctionFvPatchScalarField.C.
Member Function Documentation
calcNut()
tmp< scalarField > calcNut () const protected virtual
Calculate the turbulence viscosity.
Implements nutWallFunctionFvPatchScalarField.
Reimplemented in nutkAtmRoughWallFunctionFvPatchScalarField, nutkRoughWallFunctionFvPatchScalarField, and nutkFilmWallFunctionFvPatchScalarField.
Definition at line 40 of file nutkWallFunctionFvPatchScalarField.C.
References nutWallFunctionFvPatchScalarField::Cmu_, nutWallFunctionFvPatchScalarField::E_, forAll, Foam::constant::atomic::group, IOobject::groupName(), k, turbulenceModel::k(), nutWallFunctionFvPatchScalarField::kappa_, Foam::log(), turbulenceModel::nu(), nutkWallFunctionFvPatchScalarField::nutkWallFunctionFvPatchScalarField(), patchi, Foam::pow025(), turbulenceModel::propertiesName, tmp< T >::ref(), Foam::sqrt(), y, turbulenceModel::y(), nutkWallFunctionFvPatchScalarField::yPlus(), and nutWallFunctionFvPatchScalarField::yPlusLam_.
TypeName()
TypeName ("nutkWallFunction")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Reimplemented in nutkAtmRoughWallFunctionFvPatchScalarField, nutkRoughWallFunctionFvPatchScalarField, and nutkFilmWallFunctionFvPatchScalarField.
Definition at line 118 of file nutkWallFunctionFvPatchScalarField.H.
References nutkWallFunctionFvPatchScalarField::nutkWallFunctionFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Reimplemented in nutkAtmRoughWallFunctionFvPatchScalarField, nutkRoughWallFunctionFvPatchScalarField, and nutkFilmWallFunctionFvPatchScalarField.
Definition at line 135 of file nutkWallFunctionFvPatchScalarField.H.
References nutkWallFunctionFvPatchScalarField::nutkWallFunctionFvPatchScalarField(), and nutkWallFunctionFvPatchScalarField::yPlus().
yPlus()
tmp< scalarField > yPlus () const virtual
Calculate and return the yPlus at the boundary.
Implements nutWallFunctionFvPatchScalarField.
Reimplemented in nutkFilmWallFunctionFvPatchScalarField.
Definition at line 136 of file nutkWallFunctionFvPatchScalarField.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), nutWallFunctionFvPatchScalarField::Cmu_, Foam::constant::atomic::group, IOobject::groupName(), k, turbulenceModel::k(), Foam::makePatchTypeField(), turbulenceModel::nu(), patchi, Foam::pow025(), turbulenceModel::propertiesName, Foam::sqrt(), y, and turbulenceModel::y().
Referenced by nutkWallFunctionFvPatchScalarField::calcNut(), nutkRoughWallFunctionFvPatchScalarField::calcNut(), nutkAtmRoughWallFunctionFvPatchScalarField::calcNut(), and nutkWallFunctionFvPatchScalarField::clone().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/derivedFvPatchFields/wallFunctions/nutWallFunctions/nutkWallFunction/nutkWallFunctionFvPatchScalarField.H
src/TurbulenceModels/turbulenceModels/derivedFvPatchFields/wallFunctions/nutWallFunctions/nutkWallFunction/nutkWallFunctionFvPatchScalarField.C