OpenFOAM: nutUWallFunctionFvPatchScalarField Class Reference
nutUWallFunctionFvPatchScalarField Class Reference
Turbulence » turbulence boundary conditions » wall functions
This boundary condition provides a turbulent kinematic viscosity condition when using wall functions, based on velocity.
Public Member Functions
TypeName ("nutUWallFunction")
Runtime type information.
nutUWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
nutUWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
nutUWallFunctionFvPatchScalarField (const nutUWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
nutUWallFunctionFvPatchScalarField (const nutUWallFunctionFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
nutUWallFunctionFvPatchScalarField (const nutUWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual tmp< scalarField > yPlus () const
Calculate and return the yPlus at the boundary.
virtual void write (Ostream &os) const
Write.
Public Member Functions inherited from nutWallFunctionFvPatchScalarField
TypeName ("nutWallFunction")
Runtime type information.
nutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
nutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &)
Construct as copy.
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
scalar yPlusLam () const
Return the Y+ at the edge of the laminar sublayer.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
Protected Member Functions
virtual tmp< scalarField > calcYPlus (const scalarField &magUp) const
Calculate yPLus.
virtual tmp< scalarField > calcNut () const
Calculate the turbulence viscosity.
Protected Member Functions inherited from nutWallFunctionFvPatchScalarField
virtual void checkType ()
Check the type of the patch.
virtual void writeLocalEntries (Ostream &) const
Write local wall function variables.
Additional Inherited Members
Static Public Member Functions inherited from nutWallFunctionFvPatchScalarField
static scalar yPlusLam (const scalar kappa, const scalar E)
Calculate the Y+ at the edge of the laminar sublayer.
Protected Attributes inherited from nutWallFunctionFvPatchScalarField
scalar Cmu_
Cmu coefficient.
scalar kappa_
Von Karman constant.
scalar E_
E coefficient.
scalar yPlusLam_
Y+ at the edge of the laminar sublayer.
Detailed Description
This boundary condition provides a turbulent kinematic viscosity condition when using wall functions, based on velocity.
Usage
Example of the boundary condition specification:
<patchName>
{
    type            nutUWallFunction;
}
See also
Foam::nutWallFunctionFvPatchScalarField
Source files
nutUWallFunctionFvPatchScalarField.H
nutUWallFunctionFvPatchScalarField.C
Definition at line 64 of file nutUWallFunctionFvPatchScalarField.H.
Constructor & Destructor Documentation
nutUWallFunctionFvPatchScalarField() [1/5]
nutUWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 124 of file nutUWallFunctionFvPatchScalarField.C.
Referenced by nutUWallFunctionFvPatchScalarField::calcYPlus(), nutUWallFunctionFvPatchScalarField::clone(), and nutUWallFunctionFvPatchScalarField::nutUWallFunctionFvPatchScalarField().
nutUWallFunctionFvPatchScalarField() [2/5]
nutUWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 146 of file nutUWallFunctionFvPatchScalarField.C.
References nutUWallFunctionFvPatchScalarField::nutUWallFunctionFvPatchScalarField().
nutUWallFunctionFvPatchScalarField() [3/5]
nutUWallFunctionFvPatchScalarField (const nutUWallFunctionFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
nutUWallFunctionFvPatchScalarField onto a new patch
Definition at line 134 of file nutUWallFunctionFvPatchScalarField.C.
References nutUWallFunctionFvPatchScalarField::nutUWallFunctionFvPatchScalarField().
nutUWallFunctionFvPatchScalarField() [4/5]
nutUWallFunctionFvPatchScalarField (const nutUWallFunctionFvPatchScalarField & sawfpsf)
Construct as copy.
Definition at line 157 of file nutUWallFunctionFvPatchScalarField.C.
References nutUWallFunctionFvPatchScalarField::nutUWallFunctionFvPatchScalarField().
nutUWallFunctionFvPatchScalarField() [5/5]
nutUWallFunctionFvPatchScalarField (const nutUWallFunctionFvPatchScalarField & sawfpsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 166 of file nutUWallFunctionFvPatchScalarField.C.
Member Function Documentation
calcYPlus()
tmp< scalarField > calcYPlus (const scalarField & magUp) const protected virtual
Calculate yPLus.
Definition at line 76 of file nutUWallFunctionFvPatchScalarField.C.
References nutWallFunctionFvPatchScalarField::E_, forAll, Foam::constant::atomic::group, IOobject::groupName(), nutWallFunctionFvPatchScalarField::kappa_, Foam::log(), Foam::mag(), Foam::max(), turbulenceModel::nu(), nutUWallFunctionFvPatchScalarField::nutUWallFunctionFvPatchScalarField(), patchi, turbulenceModel::propertiesName, tmp< T >::ref(), y, turbulenceModel::y(), nutUWallFunctionFvPatchScalarField::yPlus(), and nutWallFunctionFvPatchScalarField::yPlusLam_.
Referenced by nutUWallFunctionFvPatchScalarField::calcNut(), and nutUWallFunctionFvPatchScalarField::yPlus().
calcNut()
tmp< scalarField > calcNut () const protected virtual
Calculate the turbulence viscosity.
Implements nutWallFunctionFvPatchScalarField.
Definition at line 39 of file nutUWallFunctionFvPatchScalarField.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), nutUWallFunctionFvPatchScalarField::calcYPlus(), nutWallFunctionFvPatchScalarField::E_, forAll, Foam::constant::atomic::group, IOobject::groupName(), nutWallFunctionFvPatchScalarField::kappa_, Foam::log(), Foam::mag(), magUp, turbulenceModel::nu(), patchi, turbulenceModel::propertiesName, tmp< T >::ref(), turbulenceModel::U(), nutUWallFunctionFvPatchScalarField::yPlus(), and nutWallFunctionFvPatchScalarField::yPlusLam_.
TypeName()
TypeName ("nutUWallFunction")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 120 of file nutUWallFunctionFvPatchScalarField.H.
References nutUWallFunctionFvPatchScalarField::nutUWallFunctionFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 137 of file nutUWallFunctionFvPatchScalarField.H.
References nutUWallFunctionFvPatchScalarField::nutUWallFunctionFvPatchScalarField(), nutUWallFunctionFvPatchScalarField::write(), and nutUWallFunctionFvPatchScalarField::yPlus().
yPlus()
tmp< scalarField > yPlus () const virtual
Calculate and return the yPlus at the boundary.
Implements nutWallFunctionFvPatchScalarField.
Definition at line 177 of file nutUWallFunctionFvPatchScalarField.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), nutUWallFunctionFvPatchScalarField::calcYPlus(), Foam::constant::atomic::group, IOobject::groupName(), Foam::mag(), magUp, patchi, turbulenceModel::propertiesName, and turbulenceModel::U().
Referenced by nutUWallFunctionFvPatchScalarField::calcNut(), nutUWallFunctionFvPatchScalarField::calcYPlus(), and nutUWallFunctionFvPatchScalarField::clone().
write()
void write (Ostream & os) const virtual
Write.
Reimplemented from nutWallFunctionFvPatchScalarField.
Definition at line 195 of file nutUWallFunctionFvPatchScalarField.C.
References Foam::makePatchTypeField(), fvPatchField< Type >::write(), and nutWallFunctionFvPatchScalarField::writeLocalEntries().
Referenced by nutUWallFunctionFvPatchScalarField::clone().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/derivedFvPatchFields/wallFunctions/nutWallFunctions/nutUWallFunction/nutUWallFunctionFvPatchScalarField.H
src/TurbulenceModels/turbulenceModels/derivedFvPatchFields/wallFunctions/nutWallFunctions/nutUWallFunction/nutUWallFunctionFvPatchScalarField.C