OpenFOAM: nutWallFunctionFvPatchScalarField Class Reference
nutWallFunctionFvPatchScalarField Class Reference abstract
Turbulence » turbulence boundary conditions » wall functions
This boundary condition provides a turbulent kinematic viscosity condition when using wall functions, based on turbulence kinetic energy.
Public Member Functions
TypeName ("nutWallFunction")
Runtime type information.
nutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
nutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &)
Construct as copy.
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
scalar yPlusLam () const
Return the Y+ at the edge of the laminar sublayer.
virtual tmp< scalarField > yPlus () const =0
Calculate and return the yPlus at the boundary.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Static Public Member Functions
static scalar yPlusLam (const scalar kappa, const scalar E)
Calculate the Y+ at the edge of the laminar sublayer.
Protected Member Functions
virtual void checkType ()
Check the type of the patch.
virtual tmp< scalarField > calcNut () const =0
Calculate the turbulence viscosity.
virtual void writeLocalEntries (Ostream &) const
Write local wall function variables.
Protected Attributes
scalar Cmu_
Cmu coefficient.
scalar kappa_
Von Karman constant.
scalar E_
E coefficient.
scalar yPlusLam_
Y+ at the edge of the laminar sublayer.
Detailed Description
This boundary condition provides a turbulent kinematic viscosity condition when using wall functions, based on turbulence kinetic energy.
- replicates OpenFOAM v1.5 (and earlier) behaviour
Usage
Property Description Required Default value
Cmu Cmu coefficient no 0.09
kappa Von Karman constant no 0.41
E E coefficient no 9.8
Examples of the boundary condition specification:
    <patchName>
    {
        type            nutWallFunction;
        value           uniform 0.0;
    }
Reference for the default model coefficients:
        H. Versteeg, W. Malalasekera
        An Introduction to Computational Fluid Dynamics: The Finite Volume
        Method, subsection "3.5.2 k-epsilon model"
See also
Foam::fixedValueFvPatchField
Source files
nutWallFunctionFvPatchScalarField.H
nutWallFunctionFvPatchScalarField.C
Definition at line 100 of file nutWallFunctionFvPatchScalarField.H.
Constructor & Destructor Documentation
nutWallFunctionFvPatchScalarField() [1/5]
nutWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 69 of file nutWallFunctionFvPatchScalarField.C.
Referenced by nutWallFunctionFvPatchScalarField::nutWallFunctionFvPatchScalarField(), and nutWallFunctionFvPatchScalarField::writeLocalEntries().
nutWallFunctionFvPatchScalarField() [2/5]
nutWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 103 of file nutWallFunctionFvPatchScalarField.C.
References nutWallFunctionFvPatchScalarField::nutWallFunctionFvPatchScalarField().
nutWallFunctionFvPatchScalarField() [3/5]
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
nutWallFunctionFvPatchScalarField onto a new patch
Definition at line 85 of file nutWallFunctionFvPatchScalarField.C.
References nutWallFunctionFvPatchScalarField::nutWallFunctionFvPatchScalarField().
nutWallFunctionFvPatchScalarField() [4/5]
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField & wfpsf)
Construct as copy.
Definition at line 120 of file nutWallFunctionFvPatchScalarField.C.
References nutWallFunctionFvPatchScalarField::nutWallFunctionFvPatchScalarField().
nutWallFunctionFvPatchScalarField() [5/5]
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField & wfpsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 135 of file nutWallFunctionFvPatchScalarField.C.
References nutWallFunctionFvPatchScalarField::yPlusLam().
Member Function Documentation
checkType()
void checkType () protected virtual
Check the type of the patch.
Definition at line 41 of file nutWallFunctionFvPatchScalarField.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, Foam::nl, and nutWallFunctionFvPatchScalarField::writeLocalEntries().
calcNut()
virtual tmp<scalarField> calcNut () const protected pure virtual
Calculate the turbulence viscosity.
Implemented in nutkAtmRoughWallFunctionFvPatchScalarField, nutkRoughWallFunctionFvPatchScalarField, nutUTabulatedWallFunctionFvPatchScalarField, nutUSpaldingWallFunctionFvPatchScalarField, nutkFilmWallFunctionFvPatchScalarField, nutUWallFunctionFvPatchScalarField, nutkWallFunctionFvPatchScalarField, and nutLowReWallFunctionFvPatchScalarField.
writeLocalEntries()
void writeLocalEntries (Ostream & os) const protected virtual
Write local wall function variables.
Definition at line 56 of file nutWallFunctionFvPatchScalarField.C.
References token::END_STATEMENT, Foam::nl, nutWallFunctionFvPatchScalarField::nutWallFunctionFvPatchScalarField(), and Ostream::writeKeyword().
Referenced by nutWallFunctionFvPatchScalarField::checkType(), nutUWallFunctionFvPatchScalarField::write(), nutkFilmWallFunctionFvPatchScalarField::write(), nutUSpaldingWallFunctionFvPatchScalarField::write(), nutkRoughWallFunctionFvPatchScalarField::write(), nutkAtmRoughWallFunctionFvPatchScalarField::write(), and nutURoughWallFunctionFvPatchScalarField::write().
TypeName()
TypeName ("nutWallFunction")
Runtime type information.
yPlusLam() [1/2]
Foam::scalar yPlusLam (const scalar kappa, const scalar E) static
Calculate the Y+ at the edge of the laminar sublayer.
Definition at line 153 of file nutWallFunctionFvPatchScalarField.C.
References Foam::constant::electromagnetic::kappa, Foam::log(), and Foam::max().
yPlusLam() [2/2]
Foam::scalar yPlusLam () const
Return the Y+ at the edge of the laminar sublayer.
Definition at line 169 of file nutWallFunctionFvPatchScalarField.C.
Referenced by nutWallFunctionFvPatchScalarField::nutWallFunctionFvPatchScalarField().
yPlus()
virtual tmp<scalarField> yPlus () const pure virtual
Calculate and return the yPlus at the boundary.
Implemented in nutURoughWallFunctionFvPatchScalarField, nutUTabulatedWallFunctionFvPatchScalarField, nutUSpaldingWallFunctionFvPatchScalarField, nutkFilmWallFunctionFvPatchScalarField, nutUWallFunctionFvPatchScalarField, nutkWallFunctionFvPatchScalarField, and nutLowReWallFunctionFvPatchScalarField.
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 175 of file nutWallFunctionFvPatchScalarField.C.
References Foam::operator==().
write()
void write (Ostream & os) const virtual
Write.
Reimplemented in nutURoughWallFunctionFvPatchScalarField, nutkAtmRoughWallFunctionFvPatchScalarField, nutkRoughWallFunctionFvPatchScalarField, nutUTabulatedWallFunctionFvPatchScalarField, nutUSpaldingWallFunctionFvPatchScalarField, nutkFilmWallFunctionFvPatchScalarField, and nutUWallFunctionFvPatchScalarField.
Definition at line 188 of file nutWallFunctionFvPatchScalarField.C.
References fvPatchField< Type >::write().
Member Data Documentation
Cmu_
scalar Cmu_ protected
Cmu coefficient.
Definition at line 109 of file nutWallFunctionFvPatchScalarField.H.
Referenced by nutkWallFunctionFvPatchScalarField::calcNut(), nutkRoughWallFunctionFvPatchScalarField::calcNut(), nutkAtmRoughWallFunctionFvPatchScalarField::calcNut(), and nutkWallFunctionFvPatchScalarField::yPlus().
kappa_
scalar kappa_ protected
Von Karman constant.
Definition at line 112 of file nutWallFunctionFvPatchScalarField.H.
Referenced by nutkWallFunctionFvPatchScalarField::calcNut(), nutUWallFunctionFvPatchScalarField::calcNut(), nutkRoughWallFunctionFvPatchScalarField::calcNut(), nutkAtmRoughWallFunctionFvPatchScalarField::calcNut(), nutUSpaldingWallFunctionFvPatchScalarField::calcUTau(), and nutUWallFunctionFvPatchScalarField::calcYPlus().
E_
scalar E_ protected
E coefficient.
Definition at line 115 of file nutWallFunctionFvPatchScalarField.H.
Referenced by nutkWallFunctionFvPatchScalarField::calcNut(), nutUWallFunctionFvPatchScalarField::calcNut(), nutkRoughWallFunctionFvPatchScalarField::calcNut(), nutUSpaldingWallFunctionFvPatchScalarField::calcUTau(), and nutUWallFunctionFvPatchScalarField::calcYPlus().
yPlusLam_
scalar yPlusLam_ protected
Y+ at the edge of the laminar sublayer.
Definition at line 118 of file nutWallFunctionFvPatchScalarField.H.
Referenced by nutkWallFunctionFvPatchScalarField::calcNut(), nutUWallFunctionFvPatchScalarField::calcNut(), and nutUWallFunctionFvPatchScalarField::calcYPlus().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/derivedFvPatchFields/wallFunctions/nutWallFunctions/nutWallFunction/nutWallFunctionFvPatchScalarField.H
src/TurbulenceModels/turbulenceModels/derivedFvPatchFields/wallFunctions/nutWallFunctions/nutWallFunction/nutWallFunctionFvPatchScalarField.C