OpenFOAM: mixtureKEpsilon< BasicTurbulenceModel > Class Template Reference
mixtureKEpsilon< BasicTurbulenceModel > Class Template Reference
Turbulence » RAS turbulence
Mixture k-epsilon turbulence model for two-phase gas-liquid systems.
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
typedef RASModel< BasicTurbulenceModel > ::alphaField alphaField
typedef RASModel< BasicTurbulenceModel > ::rhoField rhoField
typedef RASModel< BasicTurbulenceModel > ::transportModel transportModel
Public Types inherited from linearViscousStress< RASModel< BasicTurbulenceModel > >
typedef RASModel< BasicTurbulenceModel > ::alphaField alphaField
typedef RASModel< BasicTurbulenceModel > ::rhoField rhoField
typedef RASModel< BasicTurbulenceModel > ::transportModel transportModel
Public Types inherited from RASModel< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("mixtureKEpsilon")
Runtime type information.
mixtureKEpsilon (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
Construct from components.
virtual ~mixtureKEpsilon ()
Destructor.
virtual bool read ()
Re-read model coefficients if they have changed.
virtual tmp< volScalarField > k () const
Return the turbulence kinetic energy.
virtual tmp< volScalarField > epsilon () const
Return the turbulence kinetic energy dissipation rate.
virtual void correct ()
Solve the turbulence equations and correct the turbulence viscosity.
Public Member Functions inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~eddyViscosity ()
Destructor.
volScalarField & evNut ()
Return non-const access to the turbulence viscosity.
virtual tmp< volScalarField > nut () const
Return the turbulence viscosity.
virtual tmp< scalarField > nut (const label patchi) const
Return the turbulence viscosity on patch.
virtual tmp< volSymmTensorField > R () const
Return the Reynolds stress tensor.
virtual void validate ()
Validate the turbulence fields after construction.
Public Member Functions inherited from linearViscousStress< RASModel< BasicTurbulenceModel > >
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~linearViscousStress ()
Destructor.
virtual tmp< volSymmTensorField > devRhoReff () const
Return the effective stress tensor.
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
Return the source term for the momentum equation.
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Return the source term for the momentum equation.
Public Member Functions inherited from RASModel< BasicTurbulenceModel >
TypeName ("RAS")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, RASModel, dictionary,(const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName),(alpha, rho, U, alphaRhoPhi, phi, transport, propertiesName))
RASModel (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~RASModel ()
Destructor.
const dimensionedScalar & kMin () const
Return the lower allowable limit for k (default: SMALL)
const dimensionedScalar & epsilonMin () const
Return the lower allowable limit for epsilon (default: SMALL)
const dimensionedScalar & omegaMin () const
Return the lower allowable limit for omega (default: SMALL)
dimensionedScalar & kMin ()
Allow kMin to be changed.
dimensionedScalar & epsilonMin ()
Allow epsilonMin to be changed.
dimensionedScalar & omegaMin ()
Allow omegaMin to be changed.
virtual const dictionary & coeffDict () const
Const access to the coefficients dictionary.
virtual tmp< volScalarField > nuEff () const
Return the effective viscosity.
virtual tmp< scalarField > nuEff (const label patchi) const
Return the effective viscosity on patch.
Protected Member Functions
wordList epsilonBoundaryTypes (const volScalarField &epsilon) const
void correctInletOutlet (volScalarField &vsf, const volScalarField &refVsf) const
void initMixtureFields ()
virtual void correctNut ()
tmp< volScalarField > Ct2 () const
tmp< volScalarField > rholEff () const
tmp< volScalarField > rhogEff () const
tmp< volScalarField > rhom () const
tmp< volScalarField > mix (const volScalarField &fc, const volScalarField &fd) const
tmp< volScalarField > mixU (const volScalarField &fc, const volScalarField &fd) const
tmp< surfaceScalarField > mixFlux (const surfaceScalarField &fc, const surfaceScalarField &fd) const
tmp< volScalarField > bubbleG () const
virtual tmp< fvScalarMatrix > kSource () const
virtual tmp< fvScalarMatrix > epsilonSource () const
tmp< volScalarField > DkEff (const volScalarField &nutm) const
Return the effective diffusivity for k.
tmp< volScalarField > DepsilonEff (const volScalarField &nutm) const
Return the effective diffusivity for epsilon.
Protected Member Functions inherited from RASModel< BasicTurbulenceModel >
virtual void printCoeffs (const word &type)
Print model coefficients.
Protected Attributes
dimensionedScalar Cmu_
dimensionedScalar C1_
dimensionedScalar C2_
dimensionedScalar C3_
dimensionedScalar Cp_
dimensionedScalar sigmak_
dimensionedScalar sigmaEps_
volScalarField k_
volScalarField epsilon_
autoPtr< volScalarField > Ct2_
autoPtr< volScalarField > rhom_
autoPtr< volScalarField > km_
autoPtr< volScalarField > epsilonm_
Protected Attributes inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
volScalarField nut_
Protected Attributes inherited from RASModel< BasicTurbulenceModel >
dictionary RASDict_
RAS coefficients dictionary.
Switch turbulence_
Turbulence on/off flag.
Switch printCoeffs_
Flag to print the model coeffs at run-time.
dictionary coeffDict_
Model coefficients dictionary.
dimensionedScalar kMin_
Lower limit of k.
dimensionedScalar epsilonMin_
Lower limit of epsilon.
dimensionedScalar omegaMin_
Lower limit for omega.
Additional Inherited Members
Static Public Member Functions inherited from RASModel< BasicTurbulenceModel >
static autoPtr< RASModel > New (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Return a reference to the selected RAS model.
Detailed Description
template<class BasicTurbulenceModel>
class Foam::RASModels::mixtureKEpsilon< BasicTurbulenceModel >
Mixture k-epsilon turbulence model for two-phase gas-liquid systems.
The basic structure of the model is based on:
    Behzadi, A., Issa, R. I., & Rusche, H. (2004).
    Modelling of dispersed bubble and droplet flow at high phase fractions.
    Chemical Engineering Science, 59(4), 759-770.
but an effective density for the gas is used in the averaging and an alternative model for bubble-generated turbulence from:
    Lahey Jr, R. T. (2005).
    The simulation of multidimensional multiphase flows.
    Nuclear Engineering and Design, 235(10), 1043-1060.
The default model coefficients are
    mixtureKEpsilonCoeffs
    {
        Cmu         0.09;
        C1          1.44;
        C2          1.92;
        C3          C2;
        sigmak      1.0;
        sigmaEps    1.3;
    }
Source files
mixtureKEpsilon.H
mixtureKEpsilon.C
Definition at line 83 of file mixtureKEpsilon.H.
Member Typedef Documentation
alphaField
typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 199 of file mixtureKEpsilon.H.
rhoField
typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 200 of file mixtureKEpsilon.H.
transportModel
typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 201 of file mixtureKEpsilon.H.
Constructor & Destructor Documentation
mixtureKEpsilon()
mixtureKEpsilon (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Construct from components.
Definition at line 46 of file mixtureKEpsilon.C.
References Foam::bound(), and mixtureKEpsilon< BasicTurbulenceModel >::epsilonBoundaryTypes().
~mixtureKEpsilon()
virtual ~mixtureKEpsilon () inline virtual
Destructor.
Definition at line 225 of file mixtureKEpsilon.H.
References mixtureKEpsilon< BasicTurbulenceModel >::read().
Member Function Documentation
epsilonBoundaryTypes()
wordList epsilonBoundaryTypes (const volScalarField & epsilon) const protected
Definition at line 172 of file mixtureKEpsilon.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), mixtureKEpsilon< BasicTurbulenceModel >::correctInletOutlet(), forAll, and patchi.
Referenced by mixtureKEpsilon< BasicTurbulenceModel >::mixtureKEpsilon().
correctInletOutlet()
void correctInletOutlet (volScalarField & vsf, const volScalarField & refVsf) const protected
Definition at line 194 of file mixtureKEpsilon.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), forAll, and patchi.
Referenced by mixtureKEpsilon< BasicTurbulenceModel >::epsilonBoundaryTypes().
initMixtureFields()
void initMixtureFields () protected
Definition at line 221 of file mixtureKEpsilon.C.
References IOobject::AUTO_WRITE, GeometricField< Type, PatchField, GeoMesh >::boundaryField(), mixtureKEpsilon< BasicTurbulenceModel >::epsilon_, mixtureKEpsilon< BasicTurbulenceModel >::k_, and IOobject::READ_IF_PRESENT.
correctNut()
void correctNut () protected virtual
Implements eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 334 of file mixtureKEpsilon.C.
References optionList::correct(), IOobject::db(), fluid, IOobject::groupName(), objectRegistry::lookupObject(), options::New(), twoPhaseSystem::otherPhase(), turbulenceModel::propertiesName, and Foam::sqr().
Referenced by mixtureKEpsilon< BasicTurbulenceModel >::correct().
Ct2()
tmp< volScalarField > Ct2 () const protected
Definition at line 376 of file mixtureKEpsilon.C.
References beta(), twoPhaseSystem::drag(), mixtureKEpsilon< BasicTurbulenceModel >::epsilon_, Foam::exp(), fluid, dragModel::K(), mixtureKEpsilon< BasicTurbulenceModel >::k_, Foam::mag(), twoPhaseSystem::otherPhase(), Foam::sqr(), Foam::sqrt(), and U.
rholEff()
tmp< volScalarField > rholEff () const protected
Definition at line 403 of file mixtureKEpsilon.C.
References fluid, twoPhaseSystem::otherPhase(), and phaseModel::rho().
rhogEff()
tmp< volScalarField > rhogEff () const protected
Definition at line 412 of file mixtureKEpsilon.C.
References virtualMassModel::Cvm(), fluid, twoPhaseSystem::otherPhase(), phaseModel::rho(), and twoPhaseSystem::virtualMass().
rhom()
tmp< volScalarField > rhom () const protected
Definition at line 423 of file mixtureKEpsilon.C.
References alphal, and mixtureKEpsilon< BasicTurbulenceModel >::mix().
mix()
tmp< volScalarField > mix (const volScalarField & fc, const volScalarField & fd) const protected
Definition at line 434 of file mixtureKEpsilon.C.
References alphal, and mixtureKEpsilon< BasicTurbulenceModel >::mixU().
Referenced by mixtureKEpsilon< BasicTurbulenceModel >::rhom().
mixU()
tmp< volScalarField > mixU (const volScalarField & fc, const volScalarField & fd) const protected
Definition at line 448 of file mixtureKEpsilon.C.
References alphal, and mixtureKEpsilon< BasicTurbulenceModel >::mixFlux().
Referenced by mixtureKEpsilon< BasicTurbulenceModel >::mix().
mixFlux()
tmp< surfaceScalarField > mixFlux (const surfaceScalarField & fc, const surfaceScalarField & fd) const protected
Definition at line 464 of file mixtureKEpsilon.C.
References alphal, and Foam::fvc::interpolate().
Referenced by mixtureKEpsilon< BasicTurbulenceModel >::mixU().
bubbleG()
tmp< volScalarField > bubbleG () const protected
Definition at line 485 of file mixtureKEpsilon.C.
References dragModel::CdRe(), twoPhaseSystem::drag(), fluid, Foam::mag(), twoPhaseSystem::otherPhase(), Foam::pow(), Foam::pow3(), and U.
kSource()
tmp< fvScalarMatrix > kSource () const protected virtual
Definition at line 521 of file mixtureKEpsilon.C.
References Foam::fvm::Su().
epsilonSource()
tmp< fvScalarMatrix > epsilonSource () const protected virtual
Definition at line 528 of file mixtureKEpsilon.C.
References Foam::fvm::Su().
DkEff()
tmp<volScalarField> DkEff (const volScalarField & nutm) const inline protected
Return the effective diffusivity for k.
Definition at line 172 of file mixtureKEpsilon.H.
DepsilonEff()
tmp<volScalarField> DepsilonEff (const volScalarField & nutm) const inline protected
Return the effective diffusivity for epsilon.
Definition at line 185 of file mixtureKEpsilon.H.
TypeName()
TypeName ("mixtureKEpsilon< BasicTurbulenceModel >")
Runtime type information.
read()
bool read () virtual
Re-read model coefficients if they have changed.
Implements eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 312 of file mixtureKEpsilon.C.
References Foam::read().
Referenced by mixtureKEpsilon< BasicTurbulenceModel >::~mixtureKEpsilon().
k()
virtual tmp<volScalarField> k () const inline virtual
Return the turbulence kinetic energy.
Implements eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 235 of file mixtureKEpsilon.H.
References mixtureKEpsilon< BasicTurbulenceModel >::k_.
epsilon()
virtual tmp<volScalarField> epsilon () const inline virtual
Return the turbulence kinetic energy dissipation rate.
Definition at line 241 of file mixtureKEpsilon.H.
References mixtureKEpsilon< BasicTurbulenceModel >::correct(), and mixtureKEpsilon< BasicTurbulenceModel >::epsilon_.
correct()
void correct () virtual
Solve the turbulence equations and correct the turbulence viscosity.
Implements eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 535 of file mixtureKEpsilon.C.
References Foam::fvc::absolute(), alphal, Foam::bound(), GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), tmp< T >::clear(), optionList::constrain(), correct, optionList::correct(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), mixtureKEpsilon< BasicTurbulenceModel >::correctNut(), Foam::fvm::ddt(), Foam::dev(), Foam::fvm::div(), Foam::fvc::div(), mixtureKEpsilon< BasicTurbulenceModel >::epsilon_, fluid, fvOptions, Foam::fvc::grad(), mixtureKEpsilon< BasicTurbulenceModel >::k_, Foam::fvm::laplacian(), options::New(), nu, eddyViscosity< RASModel< BasicTurbulenceModel > >::nut_, twoPhaseSystem::phase1(), phi, phig(), tmp< T >::ref(), Foam::solve(), Foam::fvm::Sp(), Foam::fvm::SuSp(), and Foam::twoSymm().
Referenced by mixtureKEpsilon< BasicTurbulenceModel >::epsilon().
Member Data Documentation
Cmu_
dimensionedScalar Cmu_ protected
Definition at line 108 of file mixtureKEpsilon.H.
C1_
dimensionedScalar C1_ protected
Definition at line 109 of file mixtureKEpsilon.H.
C2_
dimensionedScalar C2_ protected
Definition at line 110 of file mixtureKEpsilon.H.
C3_
dimensionedScalar C3_ protected
Definition at line 111 of file mixtureKEpsilon.H.
Cp_
dimensionedScalar Cp_ protected
Definition at line 112 of file mixtureKEpsilon.H.
sigmak_
dimensionedScalar sigmak_ protected
Definition at line 113 of file mixtureKEpsilon.H.
sigmaEps_
dimensionedScalar sigmaEps_ protected
Definition at line 114 of file mixtureKEpsilon.H.
k_
volScalarField k_ protected
Definition at line 118 of file mixtureKEpsilon.H.
Referenced by mixtureKEpsilon< BasicTurbulenceModel >::correct(), mixtureKEpsilon< BasicTurbulenceModel >::Ct2(), mixtureKEpsilon< BasicTurbulenceModel >::initMixtureFields(), and mixtureKEpsilon< BasicTurbulenceModel >::k().
epsilon_
volScalarField epsilon_ protected
Definition at line 119 of file mixtureKEpsilon.H.
Referenced by mixtureKEpsilon< BasicTurbulenceModel >::correct(), mixtureKEpsilon< BasicTurbulenceModel >::Ct2(), mixtureKEpsilon< BasicTurbulenceModel >::epsilon(), and mixtureKEpsilon< BasicTurbulenceModel >::initMixtureFields().
Ct2_
autoPtr<volScalarField> Ct2_ protected
Definition at line 123 of file mixtureKEpsilon.H.
rhom_
autoPtr<volScalarField> rhom_ protected
Definition at line 124 of file mixtureKEpsilon.H.
km_
autoPtr<volScalarField> km_ protected
Definition at line 125 of file mixtureKEpsilon.H.
epsilonm_
autoPtr<volScalarField> epsilonm_ protected
Definition at line 126 of file mixtureKEpsilon.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/phaseCompressible/RAS/mixtureKEpsilon/mixtureKEpsilon.H
src/TurbulenceModels/phaseCompressible/RAS/mixtureKEpsilon/mixtureKEpsilon.C