OpenFOAM: LESdelta Class Reference
LESdelta Class Reference abstract
Abstract base class for LES deltas.
Public Member Functions
TypeName ("LESdelta")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, LESdelta, dictionary,(const word &name, const turbulenceModel &turbulence, const dictionary &dict),(name, turbulence, dict))
LESdelta (const word &name, const turbulenceModel &turbulence)
Construct from name, turbulenceModel and dictionary.
virtual ~LESdelta ()
Destructor.
const turbulenceModel & turbulence () const
Return turbulenceModel reference.
virtual void read (const dictionary &)=0
Read the LESdelta dictionary.
virtual void correct ()=0
virtual operator const volScalarField & () const
Static Public Member Functions
static autoPtr< LESdelta > New (const word &name, const turbulenceModel &turbulence, const dictionary &dict)
Return a reference to the selected LES delta.
static autoPtr< LESdelta > New (const word &name, const turbulenceModel &turbulence, const dictionary &dict, const dictionaryConstructorTable &)
Return a reference to the selected LES delta.
Protected Attributes
const turbulenceModel & turbulenceModel_
volScalarField delta_
Detailed Description
Abstract base class for LES deltas.
Source files
LESdelta.H
LESdelta.C
Definition at line 50 of file LESdelta.H.
Constructor & Destructor Documentation
LESdelta()
LESdelta (const word & name, const turbulenceModel & turbulence)
Construct from name, turbulenceModel and dictionary.
Definition at line 40 of file LESdelta.C.
References LESdelta::New().
~LESdelta()
virtual ~LESdelta () inline virtual
Destructor.
Definition at line 124 of file LESdelta.H.
Member Function Documentation
TypeName()
TypeName ("LESdelta")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , LESdelta , dictionary , (const word &name, const turbulenceModel &turbulence, const dictionary &dict) , (name, turbulence, dict))
New() [1/2]
Foam::autoPtr< Foam::LESdelta > New (const word & name, const turbulenceModel & turbulence, const dictionary & dict) static
Return a reference to the selected LES delta.
Definition at line 66 of file LESdelta.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::Info, dictionary::lookup(), Foam::name(), Foam::nl, and turbulence.
Referenced by LESdelta::LESdelta().
New() [2/2]
Foam::autoPtr< Foam::LESdelta > New (const word & name, const turbulenceModel & turbulence, const dictionary & dict, const dictionaryConstructorTable & additionalConstructors) static
Return a reference to the selected LES delta.
Definition at line 94 of file LESdelta.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::Info, dictionary::lookup(), Foam::name(), Foam::nl, and turbulence.
turbulence()
const turbulenceModel& turbulence () const inline
Return turbulenceModel reference.
Definition at line 131 of file LESdelta.H.
References LESdelta::correct(), LESdelta::read(), and LESdelta::turbulenceModel_.
read()
virtual void read (const dictionary &) pure virtual
Read the LESdelta dictionary.
Implemented in smoothDelta, PrandtlDelta, IDDESDelta, maxDeltaxyz, vanDriestDelta, and cubeRootVolDelta.
Referenced by LESdelta::turbulence().
correct()
virtual void correct () pure virtual
Implemented in smoothDelta, PrandtlDelta, IDDESDelta, maxDeltaxyz, vanDriestDelta, and cubeRootVolDelta.
Referenced by LESdelta::turbulence().
operator const volScalarField &()
virtual operator const volScalarField & () const inline virtual
Definition at line 145 of file LESdelta.H.
References LESdelta::delta_.
Member Data Documentation
turbulenceModel_
const turbulenceModel& turbulenceModel_ protected
Definition at line 57 of file LESdelta.H.
Referenced by LESdelta::turbulence().
delta_
volScalarField delta_ protected
Definition at line 59 of file LESdelta.H.
Referenced by LESdelta::operator const volScalarField &().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/LES/LESdeltas/LESdelta/LESdelta.H
src/TurbulenceModels/turbulenceModels/LES/LESdeltas/LESdelta/LESdelta.C