OpenFOAM: DeardorffDiffStress< BasicTurbulenceModel > Class Template Reference
DeardorffDiffStress< BasicTurbulenceModel > Class Template Reference
Turbulence » LES turbulence
Differential SGS Stress Equation Model for incompressible and compressible flows.
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from ReynoldsStress< LESModel< BasicTurbulenceModel > >
typedef LESModel< BasicTurbulenceModel > ::alphaField alphaField
typedef LESModel< BasicTurbulenceModel > ::rhoField rhoField
typedef LESModel< BasicTurbulenceModel > ::transportModel transportModel
Public Types inherited from LESModel< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("DeardorffDiffStress")
Runtime type information.
DeardorffDiffStress (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
Constructor from components.
virtual ~DeardorffDiffStress ()
Destructor.
virtual bool read ()
Read model coefficients if they have changed.
virtual tmp< volScalarField > epsilon () const
Return the turbulence kinetic energy dissipation rate.
virtual void correct ()
Correct sub-grid stress, eddy-Viscosity and related properties.
Public Member Functions inherited from ReynoldsStress< LESModel< BasicTurbulenceModel > >
ReynoldsStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~ReynoldsStress ()
Destructor.
virtual tmp< volScalarField > nut () const
Return the turbulence viscosity.
virtual tmp< scalarField > nut (const label patchi) const
Return the turbulence viscosity on patch.
virtual tmp< volScalarField > k () const
Return the turbulence kinetic energy.
virtual tmp< volSymmTensorField > R () const
Return the Reynolds stress tensor.
virtual tmp< volSymmTensorField > devRhoReff () const
Return the effective stress tensor.
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
Return the source term for the momentum equation.
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Return the source term for the momentum equation.
virtual void validate ()
Validate the turbulence fields after construction.
Public Member Functions inherited from LESModel< BasicTurbulenceModel >
TypeName ("LES")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, LESModel, dictionary,(const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName),(alpha, rho, U, alphaRhoPhi, phi, transport, propertiesName))
LESModel (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~LESModel ()
Destructor.
virtual const dictionary & coeffDict () const
Const access to the coefficients dictionary.
const dimensionedScalar & kMin () const
Return the lower allowable limit for k (default: SMALL)
dimensionedScalar & kMin ()
Allow kMin to be changed.
const volScalarField & delta () const
Access function to filter width.
virtual tmp< volScalarField > nuEff () const
Return the effective viscosity.
virtual tmp< scalarField > nuEff (const label patchi) const
Return the effective viscosity on patch.
Protected Member Functions
virtual void correctNut ()
Update the eddy-viscosity.
Protected Member Functions inherited from ReynoldsStress< LESModel< BasicTurbulenceModel > >
void boundNormalStress (volSymmTensorField &R) const
void correctWallShearStress (volSymmTensorField &R) const
Protected Member Functions inherited from LESModel< BasicTurbulenceModel >
virtual void printCoeffs (const word &type)
Print model coefficients.
Protected Attributes
dimensionedScalar Ck_
dimensionedScalar Cm_
dimensionedScalar Ce_
dimensionedScalar Cs_
Protected Attributes inherited from ReynoldsStress< LESModel< BasicTurbulenceModel > >
dimensionedScalar couplingFactor_
volSymmTensorField R_
volScalarField nut_
Protected Attributes inherited from LESModel< BasicTurbulenceModel >
dictionary LESDict_
LES coefficients dictionary.
Switch turbulence_
Turbulence on/off flag.
Switch printCoeffs_
Flag to print the model coeffs at run-time.
dictionary coeffDict_
Model coefficients dictionary.
dimensionedScalar kMin_
Lower limit of k.
dimensionedScalar epsilonMin_
Lower limit of epsilon.
dimensionedScalar omegaMin_
Lower limit for omega.
autoPtr< Foam::LESdelta > delta_
Run-time selectable delta model.
Additional Inherited Members
Static Public Member Functions inherited from LESModel< BasicTurbulenceModel >
static autoPtr< LESModel > New (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Return a reference to the selected LES model.
Detailed Description
template<class BasicTurbulenceModel>
class Foam::LESModels::DeardorffDiffStress< BasicTurbulenceModel >
Differential SGS Stress Equation Model for incompressible and compressible flows.
Reference:
    Deardorff, J. W. (1973).
    The use of subgrid transport equations in a three-dimensional model
    of atmospheric turbulence.
    Journal of Fluids Engineering, 95(3), 429-438.
This SGS model uses a full balance equation for the SGS stress tensor to simulate the behaviour of B.
This implementation is as described in the above paper except that the triple correlation model of Donaldson is replaced with the generalized gradient diffusion model of Daly and Harlow:
    Daly, B. J., & Harlow, F. H. (1970).
    Transport equations in turbulence.
    Physics of Fluids (1958-1988), 13(11), 2634-2649.
with the default value for the coefficient Cs of 0.25 from
    Launder, B. E., Reece, G. J., & Rodi, W. (1975).
    Progress in the development of a Reynolds-stress turbulence closure.
    Journal of fluid mechanics, 68(03), 537-566.
Source files
DeardorffDiffStress.H
DeardorffDiffStress.C
Definition at line 82 of file DeardorffDiffStress.H.
Member Typedef Documentation
alphaField
typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 113 of file DeardorffDiffStress.H.
rhoField
typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 114 of file DeardorffDiffStress.H.
transportModel
typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 115 of file DeardorffDiffStress.H.
Constructor & Destructor Documentation
DeardorffDiffStress()
DeardorffDiffStress (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Constructor from components.
Definition at line 53 of file DeardorffDiffStress.C.
~DeardorffDiffStress()
virtual ~DeardorffDiffStress () inline virtual
Destructor.
Definition at line 139 of file DeardorffDiffStress.H.
References DeardorffDiffStress< BasicTurbulenceModel >::correct(), DeardorffDiffStress< BasicTurbulenceModel >::epsilon(), and DeardorffDiffStress< BasicTurbulenceModel >::read().
Member Function Documentation
correctNut()
void correctNut () protected virtual
Update the eddy-viscosity.
Implements ReynoldsStress< LESModel< BasicTurbulenceModel > >.
Definition at line 39 of file DeardorffDiffStress.C.
References optionList::correct(), delta, k, options::New(), and Foam::sqrt().
TypeName()
TypeName ("DeardorffDiffStress< BasicTurbulenceModel >")
Runtime type information.
read()
bool read () virtual
Read model coefficients if they have changed.
Implements ReynoldsStress< LESModel< BasicTurbulenceModel > >.
Definition at line 124 of file DeardorffDiffStress.C.
References Foam::read().
Referenced by DeardorffDiffStress< BasicTurbulenceModel >::~DeardorffDiffStress().
epsilon()
tmp< volScalarField > epsilon () const virtual
Return the turbulence kinetic energy dissipation rate.
Definition at line 143 of file DeardorffDiffStress.C.
References delta, IOobject::groupName(), k, IOobject::NO_READ, IOobject::NO_WRITE, and Foam::sqrt().
Referenced by DeardorffDiffStress< BasicTurbulenceModel >::~DeardorffDiffStress().
correct()
void correct () virtual
Correct sub-grid stress, eddy-Viscosity and related properties.
Implements ReynoldsStress< LESModel< BasicTurbulenceModel > >.
Definition at line 166 of file DeardorffDiffStress.C.
References optionList::constrain(), correct, optionList::correct(), Foam::fvm::ddt(), delta, Foam::fvm::div(), epsilon, fvOptions, Foam::fvc::grad(), Foam::I, k, Foam::fvm::laplacian(), options::New(), nu, R, tmp< T >::ref(), Foam::fvm::Sp(), Foam::sqrt(), Foam::symm(), and Foam::twoSymm().
Referenced by DeardorffDiffStress< BasicTurbulenceModel >::~DeardorffDiffStress().
Member Data Documentation
Ck_
dimensionedScalar Ck_ protected
Definition at line 99 of file DeardorffDiffStress.H.
Cm_
dimensionedScalar Cm_ protected
Definition at line 100 of file DeardorffDiffStress.H.
Ce_
dimensionedScalar Ce_ protected
Definition at line 101 of file DeardorffDiffStress.H.
Cs_
dimensionedScalar Cs_ protected
Definition at line 102 of file DeardorffDiffStress.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/LES/DeardorffDiffStress/DeardorffDiffStress.H
src/TurbulenceModels/turbulenceModels/LES/DeardorffDiffStress/DeardorffDiffStress.C