OpenFOAM: dynamicLagrangian< BasicTurbulenceModel > Class Template Reference
dynamicLagrangian< BasicTurbulenceModel > Class Template Reference
Turbulence » LES turbulence
Dynamic SGS model with Lagrangian averaging.
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from LESeddyViscosity< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from eddyViscosity< LESModel< BasicTurbulenceModel > >
typedef LESModel< BasicTurbulenceModel > ::alphaField alphaField
typedef LESModel< BasicTurbulenceModel > ::rhoField rhoField
typedef LESModel< BasicTurbulenceModel > ::transportModel transportModel
Public Types inherited from linearViscousStress< LESModel< BasicTurbulenceModel > >
typedef LESModel< BasicTurbulenceModel > ::alphaField alphaField
typedef LESModel< BasicTurbulenceModel > ::rhoField rhoField
typedef LESModel< BasicTurbulenceModel > ::transportModel transportModel
Public Types inherited from LESModel< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("dynamicLagrangian")
Runtime type information.
dynamicLagrangian (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
Construct from components.
virtual ~dynamicLagrangian ()
Destructor.
virtual bool read ()
Read model coefficients if they have changed.
tmp< volScalarField > k (const tmp< volTensorField > &gradU) const
Return SGS kinetic energy.
virtual tmp< volScalarField > k () const
Return SGS kinetic energy.
tmp< volScalarField > DkEff () const
Return the effective diffusivity for k.
virtual void correct ()
Correct Eddy-Viscosity and related properties.
Public Member Functions inherited from LESeddyViscosity< BasicTurbulenceModel >
LESeddyViscosity (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Construct from components.
virtual ~LESeddyViscosity ()
Destructor.
virtual tmp< volScalarField > epsilon () const
Return sub-grid disipation rate.
Public Member Functions inherited from eddyViscosity< LESModel< BasicTurbulenceModel > >
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~eddyViscosity ()
Destructor.
volScalarField & evNut ()
Return non-const access to the turbulence viscosity.
virtual tmp< volScalarField > nut () const
Return the turbulence viscosity.
virtual tmp< scalarField > nut (const label patchi) const
Return the turbulence viscosity on patch.
virtual tmp< volSymmTensorField > R () const
Return the Reynolds stress tensor.
virtual void validate ()
Validate the turbulence fields after construction.
Public Member Functions inherited from linearViscousStress< LESModel< BasicTurbulenceModel > >
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~linearViscousStress ()
Destructor.
virtual tmp< volSymmTensorField > devRhoReff () const
Return the effective stress tensor.
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
Return the source term for the momentum equation.
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Return the source term for the momentum equation.
Public Member Functions inherited from LESModel< BasicTurbulenceModel >
TypeName ("LES")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, LESModel, dictionary,(const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName),(alpha, rho, U, alphaRhoPhi, phi, transport, propertiesName))
LESModel (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~LESModel ()
Destructor.
virtual const dictionary & coeffDict () const
Const access to the coefficients dictionary.
const dimensionedScalar & kMin () const
Return the lower allowable limit for k (default: SMALL)
dimensionedScalar & kMin ()
Allow kMin to be changed.
const volScalarField & delta () const
Access function to filter width.
virtual tmp< volScalarField > nuEff () const
Return the effective viscosity.
virtual tmp< scalarField > nuEff (const label patchi) const
Return the effective viscosity on patch.
Protected Member Functions
void correctNut (const tmp< volTensorField > &gradU)
Update sub-grid eddy-viscosity.
virtual void correctNut ()
Protected Member Functions inherited from LESModel< BasicTurbulenceModel >
virtual void printCoeffs (const word &type)
Print model coefficients.
Protected Attributes
volScalarField flm_
volScalarField fmm_
dimensionedScalar theta_
simpleFilter simpleFilter_
autoPtr< LESfilter > filterPtr_
LESfilter & filter_
dimensionedScalar flm0_
dimensionedScalar fmm0_
Protected Attributes inherited from LESeddyViscosity< BasicTurbulenceModel >
dimensionedScalar Ce_
Protected Attributes inherited from eddyViscosity< LESModel< BasicTurbulenceModel > >
volScalarField nut_
Protected Attributes inherited from LESModel< BasicTurbulenceModel >
dictionary LESDict_
LES coefficients dictionary.
Switch turbulence_
Turbulence on/off flag.
Switch printCoeffs_
Flag to print the model coeffs at run-time.
dictionary coeffDict_
Model coefficients dictionary.
dimensionedScalar kMin_
Lower limit of k.
dimensionedScalar epsilonMin_
Lower limit of epsilon.
dimensionedScalar omegaMin_
Lower limit for omega.
autoPtr< Foam::LESdelta > delta_
Run-time selectable delta model.
Additional Inherited Members
Static Public Member Functions inherited from LESModel< BasicTurbulenceModel >
static autoPtr< LESModel > New (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Return a reference to the selected LES model.
Detailed Description
template<class BasicTurbulenceModel>
class Foam::LESModels::dynamicLagrangian< BasicTurbulenceModel >
Dynamic SGS model with Lagrangian averaging.
Reference:
    Meneveau, C., Lund, T. S., & Cabot, W. H. (1996).
    A Lagrangian dynamic subgrid-scale model of turbulence.
    Journal of Fluid Mechanics, 319, 353-385.
Source files
dynamicLagrangian.H
dynamicLagrangian.C
Definition at line 62 of file dynamicLagrangian.H.
Member Typedef Documentation
alphaField
typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 100 of file dynamicLagrangian.H.
rhoField
typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 101 of file dynamicLagrangian.H.
transportModel
typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 102 of file dynamicLagrangian.H.
Constructor & Destructor Documentation
dynamicLagrangian()
dynamicLagrangian (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Construct from components.
Definition at line 63 of file dynamicLagrangian.C.
~dynamicLagrangian()
virtual ~dynamicLagrangian () inline virtual
Destructor.
Definition at line 125 of file dynamicLagrangian.H.
References dynamicLagrangian< BasicTurbulenceModel >::read().
Member Function Documentation
correctNut() [1/2]
void correctNut (const tmp< volTensorField > & gradU) protected
Update sub-grid eddy-viscosity.
Definition at line 40 of file dynamicLagrangian.C.
References optionList::correct(), delta, Foam::dev(), Foam::mag(), options::New(), Foam::sqr(), and Foam::symm().
correctNut() [2/2]
void correctNut () protected virtual
Implements eddyViscosity< LESModel< BasicTurbulenceModel > >.
Definition at line 53 of file dynamicLagrangian.C.
References Foam::fvc::grad().
TypeName()
TypeName ("dynamicLagrangian< BasicTurbulenceModel >")
Runtime type information.
read()
bool read () virtual
Read model coefficients if they have changed.
Reimplemented from LESeddyViscosity< BasicTurbulenceModel >.
Definition at line 137 of file dynamicLagrangian.C.
Referenced by dynamicLagrangian< BasicTurbulenceModel >::~dynamicLagrangian().
k() [1/2]
tmp<volScalarField> k (const tmp< volTensorField > & gradU) const inline
Return SGS kinetic energy.
Definition at line 135 of file dynamicLagrangian.H.
References LESeddyViscosity< BasicTurbulenceModel >::Ce_, LESModel< BasicTurbulenceModel >::delta(), Foam::dev(), Foam::magSqr(), Foam::pow(), Foam::sqr(), and Foam::symm().
k() [2/2]
virtual tmp<volScalarField> k () const inline virtual
Return SGS kinetic energy.
Implements eddyViscosity< LESModel< BasicTurbulenceModel > >.
Definition at line 144 of file dynamicLagrangian.H.
References Foam::fvc::grad().
DkEff()
tmp<volScalarField> DkEff () const inline
Return the effective diffusivity for k.
Definition at line 150 of file dynamicLagrangian.H.
References dynamicLagrangian< BasicTurbulenceModel >::correct(), nu, and eddyViscosity< LESModel< BasicTurbulenceModel > >::nut_.
correct()
void correct () virtual
Correct Eddy-Viscosity and related properties.
Implements eddyViscosity< LESModel< BasicTurbulenceModel > >.
Definition at line 154 of file dynamicLagrangian.C.
References Foam::bound(), optionList::constrain(), eddyViscosity< LESModel< BasicTurbulenceModel > >::correct(), optionList::correct(), Foam::fvm::ddt(), delta, Foam::dev(), Foam::fvm::div(), fvOptions, Foam::fvc::grad(), M, Foam::mag(), options::New(), Foam::pow(), fvMatrix< Type >::relax(), fvMatrix< Type >::solve(), Foam::fvm::Sp(), Foam::sqr(), Foam::symm(), and Uf.
Referenced by dynamicLagrangian< BasicTurbulenceModel >::DkEff().
Member Data Documentation
flm_
volScalarField flm_ protected
Definition at line 77 of file dynamicLagrangian.H.
fmm_
volScalarField fmm_ protected
Definition at line 78 of file dynamicLagrangian.H.
theta_
dimensionedScalar theta_ protected
Definition at line 80 of file dynamicLagrangian.H.
simpleFilter_
simpleFilter simpleFilter_ protected
Definition at line 82 of file dynamicLagrangian.H.
filterPtr_
autoPtr<LESfilter> filterPtr_ protected
Definition at line 83 of file dynamicLagrangian.H.
filter_
LESfilter& filter_ protected
Definition at line 84 of file dynamicLagrangian.H.
flm0_
dimensionedScalar flm0_ protected
Definition at line 86 of file dynamicLagrangian.H.
fmm0_
dimensionedScalar fmm0_ protected
Definition at line 87 of file dynamicLagrangian.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/LES/dynamicLagrangian/dynamicLagrangian.H
src/TurbulenceModels/turbulenceModels/LES/dynamicLagrangian/dynamicLagrangian.C