OpenFOAM: WALE< BasicTurbulenceModel > Class Template Reference
WALE< BasicTurbulenceModel > Class Template Reference
Turbulence » LES turbulence
The Wall-adapting local eddy-viscosity (WALE) SGS model.
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from LESeddyViscosity< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from eddyViscosity< LESModel< BasicTurbulenceModel > >
typedef LESModel< BasicTurbulenceModel > ::alphaField alphaField
typedef LESModel< BasicTurbulenceModel > ::rhoField rhoField
typedef LESModel< BasicTurbulenceModel > ::transportModel transportModel
Public Types inherited from linearViscousStress< LESModel< BasicTurbulenceModel > >
typedef LESModel< BasicTurbulenceModel > ::alphaField alphaField
typedef LESModel< BasicTurbulenceModel > ::rhoField rhoField
typedef LESModel< BasicTurbulenceModel > ::transportModel transportModel
Public Types inherited from LESModel< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("WALE")
Runtime type information.
WALE (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
Construct from components.
virtual ~WALE ()
Destructor.
virtual bool read ()
Read model coefficients if they have changed.
virtual tmp< volScalarField > k () const
Return SGS kinetic energy.
virtual tmp< volScalarField > epsilon () const
Return sub-grid disipation rate.
virtual void correct ()
Correct Eddy-Viscosity and related properties.
Public Member Functions inherited from LESeddyViscosity< BasicTurbulenceModel >
LESeddyViscosity (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Construct from components.
virtual ~LESeddyViscosity ()
Destructor.
Public Member Functions inherited from eddyViscosity< LESModel< BasicTurbulenceModel > >
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~eddyViscosity ()
Destructor.
volScalarField & evNut ()
Return non-const access to the turbulence viscosity.
virtual tmp< volScalarField > nut () const
Return the turbulence viscosity.
virtual tmp< scalarField > nut (const label patchi) const
Return the turbulence viscosity on patch.
virtual tmp< volSymmTensorField > R () const
Return the Reynolds stress tensor.
virtual void validate ()
Validate the turbulence fields after construction.
Public Member Functions inherited from linearViscousStress< LESModel< BasicTurbulenceModel > >
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~linearViscousStress ()
Destructor.
virtual tmp< volSymmTensorField > devRhoReff () const
Return the effective stress tensor.
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
Return the source term for the momentum equation.
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Return the source term for the momentum equation.
Public Member Functions inherited from LESModel< BasicTurbulenceModel >
TypeName ("LES")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, LESModel, dictionary,(const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName),(alpha, rho, U, alphaRhoPhi, phi, transport, propertiesName))
LESModel (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~LESModel ()
Destructor.
virtual const dictionary & coeffDict () const
Const access to the coefficients dictionary.
const dimensionedScalar & kMin () const
Return the lower allowable limit for k (default: SMALL)
dimensionedScalar & kMin ()
Allow kMin to be changed.
const volScalarField & delta () const
Access function to filter width.
virtual tmp< volScalarField > nuEff () const
Return the effective viscosity.
virtual tmp< scalarField > nuEff (const label patchi) const
Return the effective viscosity on patch.
Protected Member Functions
tmp< volSymmTensorField > Sd (const volTensorField &gradU) const
Return the deviatoric symmetric part of the square of the given.
tmp< volScalarField > k (const volTensorField &gradU) const
Return SGS kinetic energy.
virtual void correctNut ()
Update the SGS eddy-viscosity.
Protected Member Functions inherited from LESModel< BasicTurbulenceModel >
virtual void printCoeffs (const word &type)
Print model coefficients.
Protected Attributes
dimensionedScalar Ck_
dimensionedScalar Cw_
Protected Attributes inherited from LESeddyViscosity< BasicTurbulenceModel >
dimensionedScalar Ce_
Protected Attributes inherited from eddyViscosity< LESModel< BasicTurbulenceModel > >
volScalarField nut_
Protected Attributes inherited from LESModel< BasicTurbulenceModel >
dictionary LESDict_
LES coefficients dictionary.
Switch turbulence_
Turbulence on/off flag.
Switch printCoeffs_
Flag to print the model coeffs at run-time.
dictionary coeffDict_
Model coefficients dictionary.
dimensionedScalar kMin_
Lower limit of k.
dimensionedScalar epsilonMin_
Lower limit of epsilon.
dimensionedScalar omegaMin_
Lower limit for omega.
autoPtr< Foam::LESdelta > delta_
Run-time selectable delta model.
Additional Inherited Members
Static Public Member Functions inherited from LESModel< BasicTurbulenceModel >
static autoPtr< LESModel > New (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Return a reference to the selected LES model.
Detailed Description
template<class BasicTurbulenceModel>
class Foam::LESModels::WALE< BasicTurbulenceModel >
The Wall-adapting local eddy-viscosity (WALE) SGS model.
Reference:
    Nicoud, F., & Ducros, F. (1999).
    Subgrid-scale stress modelling based on the square of the velocity
    gradient tensor.
    Flow, Turbulence and Combustion, 62(3), 183-200.
The default model coefficients are
    WALECoeffs
    {
        Ck                  0.094;
        Ce                  1.048;e
        Cw                  0.325;
    }
See also
Foam::LESModels::Smagorinsky
Source files
WALE.H
WALE.C
Definition at line 76 of file WALE.H.
Member Typedef Documentation
alphaField
typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 111 of file WALE.H.
rhoField
typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 112 of file WALE.H.
transportModel
typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 113 of file WALE.H.
Constructor & Destructor Documentation
WALE()
WALE (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Construct from components.
Definition at line 103 of file WALE.C.
~WALE()
virtual ~WALE () inline virtual
Destructor.
Definition at line 137 of file WALE.H.
References WALE< BasicTurbulenceModel >::read().
Member Function Documentation
Sd()
tmp< volSymmTensorField > Sd (const volTensorField & gradU) const protected
Return the deviatoric symmetric part of the square of the given.
velocity gradient field
Definition at line 40 of file WALE.C.
References Foam::dev(), WALE< BasicTurbulenceModel >::k(), and Foam::symm().
k() [1/2]
tmp< volScalarField > k (const volTensorField & gradU) const protected
Return SGS kinetic energy.
calculated from the given velocity gradient
Definition at line 50 of file WALE.C.
References delta, IOobject::groupName(), Foam::magSqr(), Foam::pow(), Foam::pow3(), Foam::sqr(), and Foam::symm().
correctNut()
void correctNut () protected virtual
Update the SGS eddy-viscosity.
Implements eddyViscosity< LESModel< BasicTurbulenceModel > >.
Definition at line 89 of file WALE.C.
References optionList::correct(), delta, Foam::fvc::grad(), k, options::New(), and Foam::sqrt().
TypeName()
TypeName ("WALE< BasicTurbulenceModel >")
Runtime type information.
read()
bool read () virtual
Read model coefficients if they have changed.
Reimplemented from LESeddyViscosity< BasicTurbulenceModel >.
Definition at line 156 of file WALE.C.
Referenced by WALE< BasicTurbulenceModel >::~WALE().
k() [2/2]
virtual tmp<volScalarField> k () const inline virtual
Return SGS kinetic energy.
Implements eddyViscosity< LESModel< BasicTurbulenceModel > >.
Definition at line 147 of file WALE.H.
References WALE< BasicTurbulenceModel >::correct(), WALE< BasicTurbulenceModel >::epsilon(), and Foam::fvc::grad().
Referenced by WALE< BasicTurbulenceModel >::Sd().
epsilon()
tmp< volScalarField > epsilon () const virtual
Return sub-grid disipation rate.
Reimplemented from LESeddyViscosity< BasicTurbulenceModel >.
Definition at line 173 of file WALE.C.
References delta, Foam::fvc::grad(), IOobject::groupName(), k, IOobject::NO_READ, IOobject::NO_WRITE, and Foam::sqrt().
Referenced by WALE< BasicTurbulenceModel >::k().
correct()
void correct () virtual
Correct Eddy-Viscosity and related properties.
Implements eddyViscosity< LESModel< BasicTurbulenceModel > >.
Definition at line 196 of file WALE.C.
References eddyViscosity< LESModel< BasicTurbulenceModel > >::correct().
Referenced by WALE< BasicTurbulenceModel >::k().
Member Data Documentation
Ck_
dimensionedScalar Ck_ protected
Definition at line 91 of file WALE.H.
Cw_
dimensionedScalar Cw_ protected
Definition at line 92 of file WALE.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/LES/WALE/WALE.H
src/TurbulenceModels/turbulenceModels/LES/WALE/WALE.C