OpenFOAM: Stokes< BasicTurbulenceModel > Class Template Reference
Stokes< BasicTurbulenceModel > Class Template Reference
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from linearViscousStress< laminarModel< BasicTurbulenceModel > >
typedef laminarModel< BasicTurbulenceModel > ::alphaField alphaField
typedef laminarModel< BasicTurbulenceModel > ::rhoField rhoField
typedef laminarModel< BasicTurbulenceModel > ::transportModel transportModel
Public Types inherited from laminarModel< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("Stokes")
Runtime type information.
Stokes (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Construct from components.
virtual ~Stokes ()
Destructor.
virtual const dictionary & coeffDict () const
Const access to the coefficients dictionary.
virtual bool read ()
Read turbulenceProperties dictionary.
virtual tmp< volScalarField > nut () const
Return the turbulence viscosity, i.e. 0 for Stokes flow.
virtual tmp< scalarField > nut (const label patchi) const
Return the turbulence viscosity on patch.
virtual tmp< volScalarField > nuEff () const
Return the effective viscosity, i.e. the Stokes viscosity.
virtual tmp< scalarField > nuEff (const label patchi) const
Return the effective viscosity on patch.
virtual tmp< volScalarField > k () const
Return the turbulence kinetic energy, i.e. 0 for Stokes flow.
virtual tmp< volScalarField > epsilon () const
Return the turbulence kinetic energy dissipation rate,.
virtual tmp< volSymmTensorField > R () const
Return the Reynolds stress tensor, i.e. 0 for Stokes flow.
virtual void correct ()
Correct the Stokes viscosity.
Public Member Functions inherited from linearViscousStress< laminarModel< BasicTurbulenceModel > >
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~linearViscousStress ()
Destructor.
virtual tmp< volSymmTensorField > devRhoReff () const
Return the effective stress tensor.
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
Return the source term for the momentum equation.
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Return the source term for the momentum equation.
Public Member Functions inherited from laminarModel< BasicTurbulenceModel >
TypeName ("laminar")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, laminarModel, dictionary,(const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName),(alpha, rho, U, alphaRhoPhi, phi, transport, propertiesName))
laminarModel (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~laminarModel ()
Destructor.
Static Public Member Functions
static autoPtr< Stokes > New (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Return a reference to the selected turbulence model.
Static Public Member Functions inherited from laminarModel< BasicTurbulenceModel >
static autoPtr< laminarModel > New (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Return a reference to the selected laminar model.
Additional Inherited Members
Protected Member Functions inherited from laminarModel< BasicTurbulenceModel >
virtual void printCoeffs (const word &type)
Print model coefficients.
Protected Attributes inherited from laminarModel< BasicTurbulenceModel >
dictionary laminarDict_
laminar coefficients dictionary
Switch printCoeffs_
Flag to print the model coeffs at run-time.
dictionary coeffDict_
Model coefficients dictionary.
Detailed Description
template<class BasicTurbulenceModel>
class Foam::laminarModels::Stokes< BasicTurbulenceModel >
Definition at line 52 of file Stokes.H.
Member Typedef Documentation
alphaField
typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 59 of file Stokes.H.
rhoField
typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 60 of file Stokes.H.
transportModel
typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 61 of file Stokes.H.
Constructor & Destructor Documentation
Stokes()
Stokes (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName)
Construct from components.
Definition at line 44 of file Stokes.C.
~Stokes()
virtual ~Stokes () inline virtual
Destructor.
Definition at line 99 of file Stokes.H.
References Stokes< BasicTurbulenceModel >::coeffDict(), Stokes< BasicTurbulenceModel >::correct(), Stokes< BasicTurbulenceModel >::epsilon(), Stokes< BasicTurbulenceModel >::k(), Stokes< BasicTurbulenceModel >::nuEff(), Stokes< BasicTurbulenceModel >::nut(), patchi, Stokes< BasicTurbulenceModel >::R(), and Stokes< BasicTurbulenceModel >::read().
Member Function Documentation
TypeName()
TypeName ("Stokes< BasicTurbulenceModel >")
Runtime type information.
New()
static autoPtr<Stokes> New (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName) static
Return a reference to the selected turbulence model.
coeffDict()
const dictionary & coeffDict () const virtual
Const access to the coefficients dictionary.
Reimplemented from laminarModel< BasicTurbulenceModel >.
Definition at line 72 of file Stokes.C.
References dictionary::null.
Referenced by Stokes< BasicTurbulenceModel >::~Stokes().
read()
bool read () virtual
Read turbulenceProperties dictionary.
Implements linearViscousStress< laminarModel< BasicTurbulenceModel > >.
Definition at line 79 of file Stokes.C.
Referenced by Stokes< BasicTurbulenceModel >::~Stokes().
nut() [1/2]
tmp< volScalarField > nut () const virtual
Return the turbulence viscosity, i.e. 0 for Stokes flow.
Reimplemented from laminarModel< BasicTurbulenceModel >.
Definition at line 87 of file Stokes.C.
References Foam::dimViscosity, IOobject::groupName(), IOobject::NO_READ, and IOobject::NO_WRITE.
Referenced by Stokes< BasicTurbulenceModel >::~Stokes().
nut() [2/2]
tmp< scalarField > nut (const label patchi) const virtual
Return the turbulence viscosity on patch.
Reimplemented from laminarModel< BasicTurbulenceModel >.
Definition at line 112 of file Stokes.C.
References patchi.
nuEff() [1/2]
tmp< volScalarField > nuEff () const virtual
Return the effective viscosity, i.e. the Stokes viscosity.
Reimplemented from laminarModel< BasicTurbulenceModel >.
Definition at line 125 of file Stokes.C.
References IOobject::groupName(), and nu.
Referenced by Stokes< BasicTurbulenceModel >::~Stokes().
nuEff() [2/2]
tmp< scalarField > nuEff (const label patchi) const virtual
Return the effective viscosity on patch.
Reimplemented from laminarModel< BasicTurbulenceModel >.
Definition at line 140 of file Stokes.C.
References nu.
k()
tmp< volScalarField > k () const virtual
Return the turbulence kinetic energy, i.e. 0 for Stokes flow.
Reimplemented from laminarModel< BasicTurbulenceModel >.
Definition at line 150 of file Stokes.C.
References IOobject::groupName(), IOobject::NO_READ, IOobject::NO_WRITE, and Foam::sqr().
Referenced by Stokes< BasicTurbulenceModel >::~Stokes().
epsilon()
tmp< volScalarField > epsilon () const virtual
Return the turbulence kinetic energy dissipation rate,.
i.e. 0 for Stokes flow
Reimplemented from laminarModel< BasicTurbulenceModel >.
Definition at line 174 of file Stokes.C.
References Foam::dimTime, IOobject::groupName(), IOobject::NO_READ, IOobject::NO_WRITE, and Foam::sqr().
Referenced by Stokes< BasicTurbulenceModel >::~Stokes().
R()
tmp< volSymmTensorField > R () const virtual
Return the Reynolds stress tensor, i.e. 0 for Stokes flow.
Reimplemented from laminarModel< BasicTurbulenceModel >.
Definition at line 201 of file Stokes.C.
References IOobject::groupName(), IOobject::NO_READ, IOobject::NO_WRITE, Foam::sqr(), and Foam::Zero.
Referenced by Stokes< BasicTurbulenceModel >::~Stokes().
correct()
void correct () virtual
Correct the Stokes viscosity.
Implements linearViscousStress< laminarModel< BasicTurbulenceModel > >.
Definition at line 227 of file Stokes.C.
References laminarModel< BasicTurbulenceModel >::correct().
Referenced by Stokes< BasicTurbulenceModel >::~Stokes().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/laminar/Stokes/Stokes.H
src/TurbulenceModels/turbulenceModels/laminar/Stokes/Stokes.C