OpenFOAM: dynamicKEqn< BasicTurbulenceModel > Class Template Reference
dynamicKEqn< BasicTurbulenceModel > Class Template Reference
Turbulence » LES turbulence
Dynamic one equation eddy-viscosity model.
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from LESeddyViscosity< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from eddyViscosity< LESModel< BasicTurbulenceModel > >
typedef LESModel< BasicTurbulenceModel > ::alphaField alphaField
typedef LESModel< BasicTurbulenceModel > ::rhoField rhoField
typedef LESModel< BasicTurbulenceModel > ::transportModel transportModel
Public Types inherited from linearViscousStress< LESModel< BasicTurbulenceModel > >
typedef LESModel< BasicTurbulenceModel > ::alphaField alphaField
typedef LESModel< BasicTurbulenceModel > ::rhoField rhoField
typedef LESModel< BasicTurbulenceModel > ::transportModel transportModel
Public Types inherited from LESModel< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("dynamicKEqn")
Runtime type information.
dynamicKEqn (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
Construct from components.
virtual ~dynamicKEqn ()
Destructor.
virtual bool read ()
Read model coefficients if they have changed.
virtual tmp< volScalarField > k () const
Return SGS kinetic energy.
virtual tmp< volScalarField > epsilon () const
Return sub-grid disipation rate.
tmp< volScalarField > DkEff () const
Return the effective diffusivity for k.
virtual void correct ()
Correct Eddy-Viscosity and related properties.
Public Member Functions inherited from LESeddyViscosity< BasicTurbulenceModel >
LESeddyViscosity (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Construct from components.
virtual ~LESeddyViscosity ()
Destructor.
Public Member Functions inherited from eddyViscosity< LESModel< BasicTurbulenceModel > >
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~eddyViscosity ()
Destructor.
volScalarField & evNut ()
Return non-const access to the turbulence viscosity.
virtual tmp< volScalarField > nut () const
Return the turbulence viscosity.
virtual tmp< scalarField > nut (const label patchi) const
Return the turbulence viscosity on patch.
virtual tmp< volSymmTensorField > R () const
Return the Reynolds stress tensor.
virtual void validate ()
Validate the turbulence fields after construction.
Public Member Functions inherited from linearViscousStress< LESModel< BasicTurbulenceModel > >
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~linearViscousStress ()
Destructor.
virtual tmp< volSymmTensorField > devRhoReff () const
Return the effective stress tensor.
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
Return the source term for the momentum equation.
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Return the source term for the momentum equation.
Public Member Functions inherited from LESModel< BasicTurbulenceModel >
TypeName ("LES")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, LESModel, dictionary,(const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName),(alpha, rho, U, alphaRhoPhi, phi, transport, propertiesName))
LESModel (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~LESModel ()
Destructor.
virtual const dictionary & coeffDict () const
Const access to the coefficients dictionary.
const dimensionedScalar & kMin () const
Return the lower allowable limit for k (default: SMALL)
dimensionedScalar & kMin ()
Allow kMin to be changed.
const volScalarField & delta () const
Access function to filter width.
virtual tmp< volScalarField > nuEff () const
Return the effective viscosity.
virtual tmp< scalarField > nuEff (const label patchi) const
Return the effective viscosity on patch.
Protected Member Functions
volScalarField Ck (const volSymmTensorField &D, const volScalarField &KK) const
Calculate Ck by filtering the velocity field U.
volScalarField Ce (const volSymmTensorField &D, const volScalarField &KK) const
Calculate Ce by filtering the velocity field U.
volScalarField Ce () const
void correctNut (const volSymmTensorField &D, const volScalarField &KK)
Update sub-grid eddy-viscosity.
virtual void correctNut ()
virtual tmp< fvScalarMatrix > kSource () const
Protected Member Functions inherited from LESModel< BasicTurbulenceModel >
virtual void printCoeffs (const word &type)
Print model coefficients.
Protected Attributes
volScalarField k_
simpleFilter simpleFilter_
autoPtr< LESfilter > filterPtr_
LESfilter & filter_
Protected Attributes inherited from LESeddyViscosity< BasicTurbulenceModel >
dimensionedScalar Ce_
Protected Attributes inherited from eddyViscosity< LESModel< BasicTurbulenceModel > >
volScalarField nut_
Protected Attributes inherited from LESModel< BasicTurbulenceModel >
dictionary LESDict_
LES coefficients dictionary.
Switch turbulence_
Turbulence on/off flag.
Switch printCoeffs_
Flag to print the model coeffs at run-time.
dictionary coeffDict_
Model coefficients dictionary.
dimensionedScalar kMin_
Lower limit of k.
dimensionedScalar epsilonMin_
Lower limit of epsilon.
dimensionedScalar omegaMin_
Lower limit for omega.
autoPtr< Foam::LESdelta > delta_
Run-time selectable delta model.
Additional Inherited Members
Static Public Member Functions inherited from LESModel< BasicTurbulenceModel >
static autoPtr< LESModel > New (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Return a reference to the selected LES model.
Detailed Description
template<class BasicTurbulenceModel>
class Foam::LESModels::dynamicKEqn< BasicTurbulenceModel >
Dynamic one equation eddy-viscosity model.
Eddy viscosity SGS model using a modeled balance equation to simulate the behaviour of k in which a dynamic procedure is applied to evaluate the coefficients.
Reference:
    Kim, W and Menon, S. (1995).
    A new dynamic one-equation subgrid-scale model for
    large eddy simulation.
    In 33rd Aerospace Sciences Meeting and Exhibit, Reno, NV, 1995.
There are no default model coefficients but the filter used for KK must be supplied, e.g.
    dynamicKEqnCoeffs
    {
        filter simple;
    }
Source files
dynamicKEqn.H
dynamicKEqn.C
Definition at line 76 of file dynamicKEqn.H.
Member Typedef Documentation
alphaField
typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 135 of file dynamicKEqn.H.
rhoField
typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 136 of file dynamicKEqn.H.
transportModel
typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 137 of file dynamicKEqn.H.
Constructor & Destructor Documentation
dynamicKEqn()
dynamicKEqn (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Construct from components.
Definition at line 148 of file dynamicKEqn.C.
References Foam::bound().
~dynamicKEqn()
virtual ~dynamicKEqn () inline virtual
Destructor.
Definition at line 161 of file dynamicKEqn.H.
References dynamicKEqn< BasicTurbulenceModel >::read().
Member Function Documentation
Ck()
volScalarField Ck (const volSymmTensorField & D, const volScalarField & KK) const protected
Calculate Ck by filtering the velocity field U.
Definition at line 40 of file dynamicKEqn.C.
References dynamicKEqn< BasicTurbulenceModel >::Ce(), delta, Foam::dev(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::mag(), Foam::magSqr(), Foam::sqr(), and Foam::sqrt().
Ce() [1/2]
volScalarField Ce (const volSymmTensorField & D, const volScalarField & KK) const protected
Calculate Ce by filtering the velocity field U.
Definition at line 71 of file dynamicKEqn.C.
References delta, Foam::mag(), Foam::magSqr(), and Foam::pow().
Ce() [2/2]
volScalarField Ce () const protected
Definition at line 88 of file dynamicKEqn.C.
References dynamicKEqn< BasicTurbulenceModel >::correctNut(), Foam::dev(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::fvc::grad(), Foam::magSqr(), GeometricField< Type, PatchField, GeoMesh >::max(), and Foam::symm().
Referenced by dynamicKEqn< BasicTurbulenceModel >::Ck().
correctNut() [1/2]
void correctNut (const volSymmTensorField & D, const volScalarField & KK) protected
Update sub-grid eddy-viscosity.
Definition at line 104 of file dynamicKEqn.C.
References optionList::correct(), delta, options::New(), and Foam::sqrt().
correctNut() [2/2]
void correctNut () protected virtual
Implements eddyViscosity< LESModel< BasicTurbulenceModel > >.
Definition at line 118 of file dynamicKEqn.C.
References Foam::fvc::grad(), Foam::magSqr(), and Foam::symm().
Referenced by dynamicKEqn< BasicTurbulenceModel >::Ce().
kSource()
tmp< fvScalarMatrix > kSource () const protected virtual
Definition at line 130 of file dynamicKEqn.C.
References Foam::dimTime, and Foam::dimVolume.
TypeName()
TypeName ("dynamicKEqn< BasicTurbulenceModel >")
Runtime type information.
read()
bool read () virtual
Read model coefficients if they have changed.
Reimplemented from LESeddyViscosity< BasicTurbulenceModel >.
Definition at line 200 of file dynamicKEqn.C.
Referenced by dynamicKEqn< BasicTurbulenceModel >::~dynamicKEqn().
k()
virtual tmp<volScalarField> k () const inline virtual
Return SGS kinetic energy.
Implements eddyViscosity< LESModel< BasicTurbulenceModel > >.
Definition at line 171 of file dynamicKEqn.H.
References dynamicKEqn< BasicTurbulenceModel >::epsilon(), and dynamicKEqn< BasicTurbulenceModel >::k_.
epsilon()
tmp< volScalarField > epsilon () const virtual
Return sub-grid disipation rate.
Reimplemented from LESeddyViscosity< BasicTurbulenceModel >.
Definition at line 216 of file dynamicKEqn.C.
References delta, IOobject::groupName(), k, IOobject::NO_READ, IOobject::NO_WRITE, and Foam::sqrt().
Referenced by dynamicKEqn< BasicTurbulenceModel >::k().
DkEff()
tmp<volScalarField> DkEff () const inline
Return the effective diffusivity for k.
Definition at line 180 of file dynamicKEqn.H.
References dynamicKEqn< BasicTurbulenceModel >::correct(), nu, and eddyViscosity< LESModel< BasicTurbulenceModel > >::nut_.
correct()
void correct () virtual
Correct Eddy-Viscosity and related properties.
Implements eddyViscosity< LESModel< BasicTurbulenceModel > >.
Definition at line 237 of file dynamicKEqn.C.
References Foam::fvc::absolute(), Foam::bound(), tmp< T >::clear(), optionList::constrain(), eddyViscosity< LESModel< BasicTurbulenceModel > >::correct(), optionList::correct(), Foam::fvm::ddt(), delta, Foam::dev(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::fvm::div(), Foam::fvc::div(), divU(), fvOptions, Foam::constant::universal::G, Foam::fvc::grad(), Foam::fvm::laplacian(), Foam::magSqr(), GeometricField< Type, PatchField, GeoMesh >::max(), options::New(), nut, phi, tmp< T >::ref(), Foam::solve(), Foam::fvm::Sp(), Foam::sqrt(), Foam::fvm::SuSp(), and Foam::symm().
Referenced by dynamicKEqn< BasicTurbulenceModel >::DkEff().
Member Data Documentation
k_
volScalarField k_ protected
Definition at line 93 of file dynamicKEqn.H.
Referenced by dynamicKEqn< BasicTurbulenceModel >::k().
simpleFilter_
simpleFilter simpleFilter_ protected
Definition at line 98 of file dynamicKEqn.H.
filterPtr_
autoPtr<LESfilter> filterPtr_ protected
Definition at line 99 of file dynamicKEqn.H.
filter_
LESfilter& filter_ protected
Definition at line 100 of file dynamicKEqn.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/LES/dynamicKEqn/dynamicKEqn.H
src/TurbulenceModels/turbulenceModels/LES/dynamicKEqn/dynamicKEqn.C