OpenFOAM: smoothDelta::deltaData Class Reference
smoothDelta::deltaData Class Reference
Public member class used by mesh-wave to propagate the delta-ratio.
Public Member Functions
deltaData ()
Construct null.
deltaData (const scalar delta)
Construct from delta value.
scalar delta () const
template<class TrackingData >
bool valid (TrackingData &td) const
Check whether origin has been changed at all or.
template<class TrackingData >
bool sameGeometry (const polyMesh &, const deltaData &, const scalar, TrackingData &td) const
Check for identical geometrical data.
template<class TrackingData >
void leaveDomain (const polyMesh &, const polyPatch &, const label patchFacei, const point &faceCentre, TrackingData &td)
Convert any absolute coordinates into relative to.
template<class TrackingData >
void enterDomain (const polyMesh &, const polyPatch &, const label patchFacei, const point &faceCentre, TrackingData &td)
Reverse of leaveDomain.
template<class TrackingData >
void transform (const polyMesh &, const tensor &, TrackingData &td)
Apply rotation matrix to any coordinates.
template<class TrackingData >
bool updateCell (const polyMesh &, const label thisCelli, const label neighbourFacei, const deltaData &neighbourInfo, const scalar tol, TrackingData &td)
Influence of neighbouring face.
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFacei, const label neighbourCelli, const deltaData &neighbourInfo, const scalar tol, TrackingData &td)
Influence of neighbouring cell.
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFacei, const deltaData &neighbourInfo, const scalar tol, TrackingData &td)
Influence of different value on same face.
template<class TrackingData >
bool equal (const deltaData &, TrackingData &td) const
Same (like operator==)
bool operator== (const deltaData &) const
bool operator!= (const deltaData &) const
Friends
Ostream & operator<< (Ostream &os, const deltaData &wDist)
Istream & operator>> (Istream &is, deltaData &wDist)
Detailed Description
Public member class used by mesh-wave to propagate the delta-ratio.
Definition at line 59 of file smoothDelta.H.
Constructor & Destructor Documentation
deltaData() [1/2]
deltaData () inline
Construct null.
Definition at line 64 of file smoothDeltaDeltaDataI.H.
deltaData() [2/2]
deltaData (const scalar delta) inline
Construct from delta value.
Definition at line 70 of file smoothDeltaDeltaDataI.H.
References smoothDelta::deltaData::valid().
Member Function Documentation
delta()
scalar delta () const inline
Definition at line 92 of file smoothDelta.H.
References smoothDelta::deltaData::enterDomain(), smoothDelta::deltaData::equal(), smoothDelta::deltaData::leaveDomain(), smoothDelta::deltaData::operator!=(), smoothDelta::deltaData::operator==(), smoothDelta::deltaData::sameGeometry(), smoothDelta::deltaData::transform(), smoothDelta::deltaData::updateCell(), smoothDelta::deltaData::updateFace(), and smoothDelta::deltaData::valid().
Referenced by smoothDelta::deltaData::operator==().
valid()
bool valid (TrackingData & td) const inline
Check whether origin has been changed at all or.
still contains original (invalid) value.
Definition at line 80 of file smoothDeltaDeltaDataI.H.
References smoothDelta::deltaData::sameGeometry().
Referenced by smoothDelta::deltaData::delta(), and smoothDelta::deltaData::deltaData().
sameGeometry()
bool sameGeometry (const polyMesh & , const deltaData & , const scalar , TrackingData & td) const inline
Check for identical geometrical data.
Used for cyclics checking.
Definition at line 90 of file smoothDeltaDeltaDataI.H.
References smoothDelta::deltaData::leaveDomain().
Referenced by smoothDelta::deltaData::delta(), and smoothDelta::deltaData::valid().
leaveDomain()
void leaveDomain (const polyMesh & , const polyPatch & , const label patchFacei, const point & faceCentre, TrackingData & td) inline
Convert any absolute coordinates into relative to.
(patch)face centre
Definition at line 103 of file smoothDeltaDeltaDataI.H.
References smoothDelta::deltaData::transform().
Referenced by smoothDelta::deltaData::delta(), and smoothDelta::deltaData::sameGeometry().
enterDomain()
void enterDomain (const polyMesh & , const polyPatch & , const label patchFacei, const point & faceCentre, TrackingData & td) inline
Reverse of leaveDomain.
Definition at line 125 of file smoothDeltaDeltaDataI.H.
References smoothDelta::deltaData::updateCell().
Referenced by smoothDelta::deltaData::delta(), and smoothDelta::deltaData::transform().
transform()
void transform (const polyMesh & , const tensor & , TrackingData & td) inline
Apply rotation matrix to any coordinates.
Definition at line 115 of file smoothDeltaDeltaDataI.H.
References smoothDelta::deltaData::enterDomain().
Referenced by smoothDelta::deltaData::delta(), and smoothDelta::deltaData::leaveDomain().
updateCell()
bool updateCell (const polyMesh & , const label thisCelli, const label neighbourFacei, const deltaData & neighbourInfo, const scalar tol, TrackingData & td) inline
Influence of neighbouring face.
Definition at line 137 of file smoothDeltaDeltaDataI.H.
References smoothDelta::deltaData::updateFace().
Referenced by smoothDelta::deltaData::delta(), and smoothDelta::deltaData::enterDomain().
updateFace() [1/2]
bool updateFace (const polyMesh & , const label thisFacei, const label neighbourCelli, const deltaData & neighbourInfo, const scalar tol, TrackingData & td) inline
Influence of neighbouring cell.
Definition at line 153 of file smoothDeltaDeltaDataI.H.
Referenced by smoothDelta::deltaData::delta(), and smoothDelta::deltaData::updateCell().
updateFace() [2/2]
bool updateFace (const polyMesh & , const label thisFacei, const deltaData & neighbourInfo, const scalar tol, TrackingData & td) inline
Influence of different value on same face.
Definition at line 169 of file smoothDeltaDeltaDataI.H.
References smoothDelta::deltaData::equal().
equal()
bool equal (const deltaData & rhs, TrackingData & td) const inline
Same (like operator==)
Definition at line 184 of file smoothDeltaDeltaDataI.H.
References smoothDelta::deltaData::operator==().
Referenced by smoothDelta::deltaData::delta(), and smoothDelta::deltaData::updateFace().
operator==()
bool operator== (const deltaData & rhs) const inline
Definition at line 196 of file smoothDeltaDeltaDataI.H.
References smoothDelta::deltaData::delta().
Referenced by smoothDelta::deltaData::delta(), and smoothDelta::deltaData::equal().
operator!=()
bool operator!= (const deltaData & rhs) const inline
Definition at line 205 of file smoothDeltaDeltaDataI.H.
Referenced by smoothDelta::deltaData::delta().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & os, const deltaData & wDist) friend
Definition at line 197 of file smoothDelta.H.
operator>>
Istream& operator>> (Istream & is, deltaData & wDist) friend
Definition at line 205 of file smoothDelta.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/LES/LESdeltas/smoothDelta/smoothDelta.H
src/TurbulenceModels/turbulenceModels/LES/LESdeltas/smoothDelta/smoothDeltaDeltaDataI.H