OpenFOAM: PrandtlDelta Class Reference
PrandtlDelta Class Reference
Public Member Functions
TypeName ("Prandtl")
Runtime type information.
PrandtlDelta (const word &name, const turbulenceModel &turbulence, const dictionary &)
Construct from name, turbulenceModel and dictionary.
virtual ~PrandtlDelta ()
Destructor.
virtual void read (const dictionary &)
Read the LESdelta dictionary.
virtual void correct ()
Public Member Functions inherited from LESdelta
TypeName ("LESdelta")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, LESdelta, dictionary,(const word &name, const turbulenceModel &turbulence, const dictionary &dict),(name, turbulence, dict))
LESdelta (const word &name, const turbulenceModel &turbulence)
Construct from name, turbulenceModel and dictionary.
virtual ~LESdelta ()
Destructor.
const turbulenceModel & turbulence () const
Return turbulenceModel reference.
virtual operator const volScalarField & () const
Additional Inherited Members
Static Public Member Functions inherited from LESdelta
static autoPtr< LESdelta > New (const word &name, const turbulenceModel &turbulence, const dictionary &dict)
Return a reference to the selected LES delta.
static autoPtr< LESdelta > New (const word &name, const turbulenceModel &turbulence, const dictionary &dict, const dictionaryConstructorTable &)
Return a reference to the selected LES delta.
Protected Attributes inherited from LESdelta
const turbulenceModel & turbulenceModel_
volScalarField delta_
Detailed Description
Definition at line 74 of file PrandtlDelta.H.
Constructor & Destructor Documentation
PrandtlDelta()
PrandtlDelta (const word & name, const turbulenceModel & turbulence, const dictionary & dict)
Construct from name, turbulenceModel and dictionary.
Definition at line 57 of file PrandtlDelta.C.
~PrandtlDelta()
virtual ~PrandtlDelta () inline virtual
Destructor.
Definition at line 113 of file PrandtlDelta.H.
References PrandtlDelta::correct(), and PrandtlDelta::read().
Member Function Documentation
TypeName()
TypeName ("Prandtl")
Runtime type information.
read()
void read (const dictionary & dict) virtual
Read the LESdelta dictionary.
Implements LESdelta.
Definition at line 85 of file PrandtlDelta.C.
References dictionary::read(), dictionary::readIfPresent(), dictionary::subDict(), and Foam::type().
Referenced by PrandtlDelta::~PrandtlDelta().
correct()
void correct () virtual
Implements LESdelta.
Definition at line 96 of file PrandtlDelta.C.
Referenced by PrandtlDelta::~PrandtlDelta().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/LES/LESdeltas/PrandtlDelta/PrandtlDelta.H
src/TurbulenceModels/turbulenceModels/LES/LESdeltas/PrandtlDelta/PrandtlDelta.C