OpenFOAM: Smagorinsky< BasicTurbulenceModel > Class Template Reference
Smagorinsky< BasicTurbulenceModel > Class Template Reference
Turbulence » LES turbulence
The Smagorinsky SGS model.
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from LESeddyViscosity< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from eddyViscosity< LESModel< BasicTurbulenceModel > >
typedef LESModel< BasicTurbulenceModel > ::alphaField alphaField
typedef LESModel< BasicTurbulenceModel > ::rhoField rhoField
typedef LESModel< BasicTurbulenceModel > ::transportModel transportModel
Public Types inherited from linearViscousStress< LESModel< BasicTurbulenceModel > >
typedef LESModel< BasicTurbulenceModel > ::alphaField alphaField
typedef LESModel< BasicTurbulenceModel > ::rhoField rhoField
typedef LESModel< BasicTurbulenceModel > ::transportModel transportModel
Public Types inherited from LESModel< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("Smagorinsky")
Runtime type information.
Smagorinsky (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
Construct from components.
virtual ~Smagorinsky ()
Destructor.
virtual bool read ()
Read model coefficients if they have changed.
virtual tmp< volScalarField > k () const
Return SGS kinetic energy.
virtual tmp< volScalarField > epsilon () const
Return sub-grid disipation rate.
virtual void correct ()
Correct Eddy-Viscosity and related properties.
Public Member Functions inherited from LESeddyViscosity< BasicTurbulenceModel >
LESeddyViscosity (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Construct from components.
virtual ~LESeddyViscosity ()
Destructor.
Public Member Functions inherited from eddyViscosity< LESModel< BasicTurbulenceModel > >
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~eddyViscosity ()
Destructor.
volScalarField & evNut ()
Return non-const access to the turbulence viscosity.
virtual tmp< volScalarField > nut () const
Return the turbulence viscosity.
virtual tmp< scalarField > nut (const label patchi) const
Return the turbulence viscosity on patch.
virtual tmp< volSymmTensorField > R () const
Return the Reynolds stress tensor.
virtual void validate ()
Validate the turbulence fields after construction.
Public Member Functions inherited from linearViscousStress< LESModel< BasicTurbulenceModel > >
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~linearViscousStress ()
Destructor.
virtual tmp< volSymmTensorField > devRhoReff () const
Return the effective stress tensor.
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
Return the source term for the momentum equation.
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Return the source term for the momentum equation.
Public Member Functions inherited from LESModel< BasicTurbulenceModel >
TypeName ("LES")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, LESModel, dictionary,(const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName),(alpha, rho, U, alphaRhoPhi, phi, transport, propertiesName))
LESModel (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~LESModel ()
Destructor.
virtual const dictionary & coeffDict () const
Const access to the coefficients dictionary.
const dimensionedScalar & kMin () const
Return the lower allowable limit for k (default: SMALL)
dimensionedScalar & kMin ()
Allow kMin to be changed.
const volScalarField & delta () const
Access function to filter width.
virtual tmp< volScalarField > nuEff () const
Return the effective viscosity.
virtual tmp< scalarField > nuEff (const label patchi) const
Return the effective viscosity on patch.
Protected Member Functions
tmp< volScalarField > k (const tmp< volTensorField > &gradU) const
Return SGS kinetic energy.
virtual void correctNut ()
Update the SGS eddy viscosity.
Protected Member Functions inherited from LESModel< BasicTurbulenceModel >
virtual void printCoeffs (const word &type)
Print model coefficients.
Protected Attributes
dimensionedScalar Ck_
Protected Attributes inherited from LESeddyViscosity< BasicTurbulenceModel >
dimensionedScalar Ce_
Protected Attributes inherited from eddyViscosity< LESModel< BasicTurbulenceModel > >
volScalarField nut_
Protected Attributes inherited from LESModel< BasicTurbulenceModel >
dictionary LESDict_
LES coefficients dictionary.
Switch turbulence_
Turbulence on/off flag.
Switch printCoeffs_
Flag to print the model coeffs at run-time.
dictionary coeffDict_
Model coefficients dictionary.
dimensionedScalar kMin_
Lower limit of k.
dimensionedScalar epsilonMin_
Lower limit of epsilon.
dimensionedScalar omegaMin_
Lower limit for omega.
autoPtr< Foam::LESdelta > delta_
Run-time selectable delta model.
Additional Inherited Members
Static Public Member Functions inherited from LESModel< BasicTurbulenceModel >
static autoPtr< LESModel > New (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Return a reference to the selected LES model.
Detailed Description
template<class BasicTurbulenceModel>
class Foam::LESModels::Smagorinsky< BasicTurbulenceModel >
The Smagorinsky SGS model.
Reference:
    Smagorinsky, J. (1963).
    General circulation experiments with the primitive equations: I.
    The basic experiment*.
    Monthly weather review, 91(3), 99-164.
The form of the Smagorinsky model implemented is obtained from the k-equation model assuming local equilibrium which provides estimates of both k and epsilon separate from the sub-grid scale viscosity:
    B = 2/3*k*I - 2*nuSgs*dev(D)
where
    D = symm(grad(U));
    k from D:B + Ce*k^3/2/delta = 0
    nuSgs = Ck*sqrt(k)*delta
The default model coefficients are
    SmagorinskyCoeffs
    {
        Ck                  0.094;
        Ce                  1.048;
    }
See also
Foam::LESModels::kEqn
Source files
Smagorinsky.H
Smagorinsky.C
Definition at line 89 of file Smagorinsky.H.
Member Typedef Documentation
alphaField
typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 119 of file Smagorinsky.H.
rhoField
typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 120 of file Smagorinsky.H.
transportModel
typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 121 of file Smagorinsky.H.
Constructor & Destructor Documentation
Smagorinsky()
Smagorinsky (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Construct from components.
Definition at line 83 of file Smagorinsky.C.
~Smagorinsky()
virtual ~Smagorinsky () inline virtual
Destructor.
Definition at line 145 of file Smagorinsky.H.
References Smagorinsky< BasicTurbulenceModel >::read().
Member Function Documentation
k() [1/2]
tmp< volScalarField > k (const tmp< volTensorField > & gradU) const protected
Return SGS kinetic energy.
calculated from the given velocity gradient
Definition at line 40 of file Smagorinsky.C.
References Foam::constant::physicoChemical::b, Foam::constant::universal::c, delta, Foam::dev(), IOobject::groupName(), Foam::sqr(), Foam::sqrt(), Foam::symm(), and Foam::tr().
correctNut()
void correctNut () protected virtual
Update the SGS eddy viscosity.
Implements eddyViscosity< LESModel< BasicTurbulenceModel > >.
Reimplemented in SmagorinskyZhang< BasicTurbulenceModel >.
Definition at line 67 of file Smagorinsky.C.
References optionList::correct(), delta, Foam::fvc::grad(), k, options::New(), and Foam::sqrt().
TypeName()
TypeName ("Smagorinsky< BasicTurbulenceModel >")
Runtime type information.
read()
bool read () virtual
Read model coefficients if they have changed.
Reimplemented from LESeddyViscosity< BasicTurbulenceModel >.
Reimplemented in SmagorinskyZhang< BasicTurbulenceModel >.
Definition at line 126 of file Smagorinsky.C.
Referenced by Smagorinsky< BasicTurbulenceModel >::~Smagorinsky().
k() [2/2]
virtual tmp<volScalarField> k () const inline virtual
Return SGS kinetic energy.
Implements eddyViscosity< LESModel< BasicTurbulenceModel > >.
Definition at line 155 of file Smagorinsky.H.
References Smagorinsky< BasicTurbulenceModel >::correct(), Smagorinsky< BasicTurbulenceModel >::epsilon(), and Foam::fvc::grad().
epsilon()
tmp< volScalarField > epsilon () const virtual
Return sub-grid disipation rate.
Reimplemented from LESeddyViscosity< BasicTurbulenceModel >.
Definition at line 142 of file Smagorinsky.C.
References delta, Foam::fvc::grad(), IOobject::groupName(), k, and Foam::sqrt().
Referenced by Smagorinsky< BasicTurbulenceModel >::k().
correct()
void correct () virtual
Correct Eddy-Viscosity and related properties.
Implements eddyViscosity< LESModel< BasicTurbulenceModel > >.
Definition at line 163 of file Smagorinsky.C.
References eddyViscosity< LESModel< BasicTurbulenceModel > >::correct().
Referenced by Smagorinsky< BasicTurbulenceModel >::k().
Member Data Documentation
Ck_
dimensionedScalar Ck_ protected
Definition at line 104 of file Smagorinsky.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/LES/Smagorinsky/Smagorinsky.H
src/TurbulenceModels/turbulenceModels/LES/Smagorinsky/Smagorinsky.C