OpenFOAM: kOmegaSSTDES< BasicTurbulenceModel > Class Template Reference
kOmegaSSTDES< BasicTurbulenceModel > Class Template Reference
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from kOmegaSST< LESeddyViscosity< BasicTurbulenceModel >, BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("kOmegaSSTDES")
Runtime type information.
kOmegaSSTDES (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
Construct from components.
virtual ~kOmegaSSTDES ()
Destructor.
virtual bool read ()
Read model coefficients if they have changed.
Public Member Functions inherited from kOmegaSST< LESeddyViscosity< BasicTurbulenceModel >, BasicTurbulenceModel >
kOmegaSST (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Construct from components.
virtual ~kOmegaSST ()
Destructor.
tmp< volScalarField > DkEff (const volScalarField &F1) const
Return the effective diffusivity for k.
tmp< volScalarField > DomegaEff (const volScalarField &F1) const
Return the effective diffusivity for omega.
virtual tmp< volScalarField > k () const
Return the turbulence kinetic energy.
virtual tmp< volScalarField > epsilon () const
Return the turbulence kinetic energy dissipation rate.
virtual tmp< volScalarField > omega () const
Return the turbulence kinetic energy dissipation rate.
virtual void correct ()
Solve the turbulence equations and correct the turbulence viscosity.
Protected Member Functions
tmp< volScalarField::Internal > Lt () const
Return the turbulent length-scale.
virtual tmp< volScalarField::Internal > FDES (const volScalarField::Internal &F1, const volScalarField::Internal &F2) const
The DES dissipation-rate multiplier with options zonal filtering.
virtual tmp< volScalarField::Internal > epsilonByk (const volScalarField::Internal &F1, const volScalarField::Internal &F2) const
Return epsilon/k which for standard RAS is betaStar*omega.
Protected Member Functions inherited from kOmegaSST< LESeddyViscosity< BasicTurbulenceModel >, BasicTurbulenceModel >
virtual tmp< volScalarField > F1 (const volScalarField &CDkOmega) const
virtual tmp< volScalarField > F2 () const
virtual tmp< volScalarField > F3 () const
virtual tmp< volScalarField > F23 () const
tmp< volScalarField > blend (const volScalarField &F1, const dimensionedScalar &psi1, const dimensionedScalar &psi2) const
tmp< volScalarField::Internal > blend (const volScalarField::Internal &F1, const dimensionedScalar &psi1, const dimensionedScalar &psi2) const
tmp< volScalarField > alphaK (const volScalarField &F1) const
tmp< volScalarField > alphaOmega (const volScalarField &F1) const
tmp< volScalarField::Internal > beta (const volScalarField::Internal &F1) const
tmp< volScalarField::Internal > gamma (const volScalarField::Internal &F1) const
void correctNut (const volScalarField &S2, const volScalarField &F2)
virtual void correctNut ()
virtual tmp< volScalarField::Internal > Pk (const volScalarField::Internal &G) const
Return k production rate.
virtual tmp< volScalarField::Internal > epsilonByk (const volScalarField::Internal &F1, const volScalarField::Internal &F2) const
Return epsilon/k which for standard RAS is betaStar*omega.
virtual tmp< fvScalarMatrix > kSource () const
virtual tmp< fvScalarMatrix > omegaSource () const
virtual tmp< fvScalarMatrix > Qsas (const volScalarField::Internal &S2, const volScalarField::Internal &gamma, const volScalarField::Internal &beta) const
Protected Attributes
dimensionedScalar CDES_
DES coefficient.
direction FSST_
Zonal filter choice.
Protected Attributes inherited from kOmegaSST< LESeddyViscosity< BasicTurbulenceModel >, BasicTurbulenceModel >
dimensionedScalar alphaK1_
dimensionedScalar alphaK2_
dimensionedScalar alphaOmega1_
dimensionedScalar alphaOmega2_
dimensionedScalar gamma1_
dimensionedScalar gamma2_
dimensionedScalar beta1_
dimensionedScalar beta2_
dimensionedScalar betaStar_
dimensionedScalar a1_
dimensionedScalar b1_
dimensionedScalar c1_
Switch F3_
const volScalarField & y_
Wall distance.
volScalarField k_
volScalarField omega_
Detailed Description
template<class BasicTurbulenceModel>
class Foam::LESModels::kOmegaSSTDES< BasicTurbulenceModel >
Definition at line 74 of file kOmegaSSTDES.H.
Member Typedef Documentation
alphaField
typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 123 of file kOmegaSSTDES.H.
rhoField
typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 124 of file kOmegaSSTDES.H.
transportModel
typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 125 of file kOmegaSSTDES.H.
Constructor & Destructor Documentation
kOmegaSSTDES()
kOmegaSSTDES (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Construct from components.
Definition at line 83 of file kOmegaSSTDES.C.
Referenced by kOmegaSSTDES< BasicTurbulenceModel >::epsilonByk().
~kOmegaSSTDES()
virtual ~kOmegaSSTDES () inline virtual
Destructor.
Definition at line 149 of file kOmegaSSTDES.H.
References kOmegaSSTDES< BasicTurbulenceModel >::read().
Member Function Documentation
Lt()
tmp< volScalarField::Internal > Lt () const protected
Return the turbulent length-scale.
Definition at line 38 of file kOmegaSSTDES.C.
References kOmegaSSTDES< BasicTurbulenceModel >::FDES(), and Foam::sqrt().
FDES()
tmp< volScalarField::Internal > FDES (const volScalarField::Internal & F1, const volScalarField::Internal & F2) const protected virtual
The DES dissipation-rate multiplier with options zonal filtering.
based on either F1 or F2
Definition at line 46 of file kOmegaSSTDES.C.
References delta, kOmegaSSTDES< BasicTurbulenceModel >::epsilonByk(), Foam::exit(), F1, Foam::FatalError, FatalErrorInFunction, and Foam::max().
Referenced by kOmegaSSTDES< BasicTurbulenceModel >::Lt().
epsilonByk()
tmp< volScalarField::Internal > epsilonByk (const volScalarField::Internal & F1, const volScalarField::Internal & F2) const protected virtual
Return epsilon/k which for standard RAS is betaStar*omega.
Definition at line 70 of file kOmegaSSTDES.C.
References kOmegaSSTDES< BasicTurbulenceModel >::kOmegaSSTDES().
Referenced by kOmegaSSTDES< BasicTurbulenceModel >::FDES().
TypeName()
TypeName ("kOmegaSSTDES< BasicTurbulenceModel >")
Runtime type information.
read()
bool read () virtual
Read model coefficients if they have changed.
Reimplemented from kOmegaSST< LESeddyViscosity< BasicTurbulenceModel >, BasicTurbulenceModel >.
Definition at line 131 of file kOmegaSSTDES.C.
References Foam::read().
Referenced by kOmegaSSTDES< BasicTurbulenceModel >::~kOmegaSSTDES().
Member Data Documentation
CDES_
dimensionedScalar CDES_ protected
DES coefficient.
Definition at line 90 of file kOmegaSSTDES.H.
FSST_
direction FSST_ protected
Zonal filter choice.
0: no filtering
1: (1 - F1)
2: (1 - F2)
Definition at line 97 of file kOmegaSSTDES.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/LES/kOmegaSSTDES/kOmegaSSTDES.H
src/TurbulenceModels/turbulenceModels/LES/kOmegaSSTDES/kOmegaSSTDES.C