OpenFOAM: smoothDelta Class Reference
smoothDelta Class Reference
Classes
class deltaData
Public member class used by mesh-wave to propagate the delta-ratio.
Public Member Functions
TypeName ("smooth")
Runtime type information.
smoothDelta (const word &name, const turbulenceModel &turbulence, const dictionary &)
Construct from name, turbulenceModel and dictionary.
virtual ~smoothDelta ()
Destructor.
virtual void read (const dictionary &)
Read the LESdelta dictionary.
virtual void correct ()
Public Member Functions inherited from LESdelta
TypeName ("LESdelta")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, LESdelta, dictionary,(const word &name, const turbulenceModel &turbulence, const dictionary &dict),(name, turbulence, dict))
LESdelta (const word &name, const turbulenceModel &turbulence)
Construct from name, turbulenceModel and dictionary.
virtual ~LESdelta ()
Destructor.
const turbulenceModel & turbulence () const
Return turbulenceModel reference.
virtual operator const volScalarField & () const
Additional Inherited Members
Static Public Member Functions inherited from LESdelta
static autoPtr< LESdelta > New (const word &name, const turbulenceModel &turbulence, const dictionary &dict)
Return a reference to the selected LES delta.
static autoPtr< LESdelta > New (const word &name, const turbulenceModel &turbulence, const dictionary &dict, const dictionaryConstructorTable &)
Return a reference to the selected LES delta.
Protected Attributes inherited from LESdelta
const turbulenceModel & turbulenceModel_
volScalarField delta_
Detailed Description
Definition at line 52 of file smoothDelta.H.
Constructor & Destructor Documentation
smoothDelta()
smoothDelta (const word & name, const turbulenceModel & turbulence, const dictionary & dict)
Construct from name, turbulenceModel and dictionary.
Definition at line 143 of file smoothDelta.C.
~smoothDelta()
virtual ~smoothDelta () inline virtual
Destructor.
Definition at line 269 of file smoothDelta.H.
References smoothDelta::correct(), and smoothDelta::read().
Member Function Documentation
TypeName()
TypeName ("smooth")
Runtime type information.
read()
void read (const dictionary & dict) virtual
Read the LESdelta dictionary.
Implements LESdelta.
Definition at line 170 of file smoothDelta.C.
References dictionary::read(), dictionary::subDict(), and Foam::type().
Referenced by smoothDelta::~smoothDelta().
correct()
void correct () virtual
Implements LESdelta.
Definition at line 180 of file smoothDelta.C.
Referenced by smoothDelta::~smoothDelta().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/LES/LESdeltas/smoothDelta/smoothDelta.H
src/TurbulenceModels/turbulenceModels/LES/LESdeltas/smoothDelta/smoothDelta.C