OpenFOAM: anisotropicFilter Class Reference
anisotropicFilter Class Reference
anisotropic filter
Public Member Functions
TypeName ("anisotropic")
Runtime type information.
anisotropicFilter (const fvMesh &mesh, scalar widthCoeff)
Construct from components.
anisotropicFilter (const fvMesh &mesh, const dictionary &)
Construct from IOdictionary.
virtual ~anisotropicFilter ()
Destructor.
virtual void read (const dictionary &)
Read the LESfilter dictionary.
virtual tmp< volScalarField > operator() (const tmp< volScalarField > &) const
virtual tmp< volVectorField > operator() (const tmp< volVectorField > &) const
virtual tmp< volSymmTensorField > operator() (const tmp< volSymmTensorField > &) const
virtual tmp< volTensorField > operator() (const tmp< volTensorField > &) const
Public Member Functions inherited from LESfilter
TypeName ("LESfilter")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, LESfilter, dictionary,(const fvMesh &mesh, const dictionary &LESfilterDict),(mesh, LESfilterDict))
LESfilter (const fvMesh &mesh)
Construct from components.
virtual ~LESfilter ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
Additional Inherited Members
Static Public Member Functions inherited from LESfilter
static autoPtr< LESfilter > New (const fvMesh &, const dictionary &, const word &filterDictName="filter")
Return a reference to the selected LES filter.
Protected Member Functions inherited from LESfilter
template<class GeoFieldType >
void correctBoundaryConditions (const tmp< GeoFieldType > &tgf) const
Temporary function to ensure the coupled boundary conditions of the.
Detailed Description
anisotropic filter
Kernel                 as filter          as Test filter with ratio 2
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Box filter:            g = delta2/24  ->  g = delta2/6
Spherical box filter:  g = delta2/64  ->  g = delta2/16
Gaussian filter:       g = delta2/24  ->  g = delta2/6
Source files
anisotropicFilter.H
anisotropicFilter.C
Definition at line 56 of file anisotropicFilter.H.
Constructor & Destructor Documentation
anisotropicFilter() [1/2]
anisotropicFilter (const fvMesh & mesh, scalar widthCoeff)
Construct from components.
Definition at line 44 of file anisotropicFilter.C.
References GeometricField< Type, PatchField, GeoMesh >::component(), Foam::mag(), VectorSpace< Vector< scalar >, scalar, 3 >::nComponents, fvMesh::Sf(), Foam::sqr(), Foam::fvc::surfaceSum(), and fvMesh::V().
anisotropicFilter() [2/2]
anisotropicFilter (const fvMesh & mesh, const dictionary & bd)
Construct from IOdictionary.
Definition at line 81 of file anisotropicFilter.C.
References GeometricField< Type, PatchField, GeoMesh >::component(), Foam::mag(), VectorSpace< Vector< scalar >, scalar, 3 >::nComponents, fvMesh::Sf(), Foam::sqr(), Foam::fvc::surfaceSum(), and fvMesh::V().
~anisotropicFilter()
virtual ~anisotropicFilter () inline virtual
Destructor.
Definition at line 88 of file anisotropicFilter.H.
References anisotropicFilter::read().
Member Function Documentation
TypeName()
TypeName ("anisotropic")
Runtime type information.
read()
void read (const dictionary & bd) virtual
Read the LESfilter dictionary.
Implements LESfilter.
Definition at line 119 of file anisotropicFilter.C.
References dictionary::lookup(), dictionary::subDict(), and Foam::type().
Referenced by anisotropicFilter::~anisotropicFilter().
operator()() [1/4]
Foam::tmp< Foam::volScalarField > operator() (const tmp< volScalarField > & unFilteredField) const virtual
Implements LESfilter.
Definition at line 128 of file anisotropicFilter.C.
References tmp< T >::clear(), correctBoundaryConditions(), mesh, Foam::fvc::snGrad(), and Foam::fvc::surfaceIntegrate().
operator()() [2/4]
Foam::tmp< Foam::volVectorField > operator() (const tmp< volVectorField > & unFilteredField) const virtual
Implements LESfilter.
Definition at line 152 of file anisotropicFilter.C.
References tmp< T >::clear(), correctBoundaryConditions(), mesh, Foam::fvc::snGrad(), and Foam::fvc::surfaceIntegrate().
operator()() [3/4]
Foam::tmp< Foam::volSymmTensorField > operator() (const tmp< volSymmTensorField > & unFilteredField) const virtual
Implements LESfilter.
Definition at line 176 of file anisotropicFilter.C.
References Foam::component(), correctBoundaryConditions(), mesh, VectorSpace< Form, Cmpt, Ncmpts >::nComponents, tmp< T >::ref(), GeometricField< Type, PatchField, GeoMesh >::replace(), and timeName.
operator()() [4/4]
Foam::tmp< Foam::volTensorField > operator() (const tmp< volTensorField > & unFilteredField) const virtual
Implements LESfilter.
Definition at line 212 of file anisotropicFilter.C.
References Foam::component(), correctBoundaryConditions(), mesh, VectorSpace< Tensor< scalar >, scalar, Mrows *Ncols >::nComponents, tmp< T >::ref(), GeometricField< Type, PatchField, GeoMesh >::replace(), and timeName.
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/LES/LESfilters/anisotropicFilter/anisotropicFilter.H
src/TurbulenceModels/turbulenceModels/LES/LESfilters/anisotropicFilter/anisotropicFilter.C