OpenFOAM: laplaceFilter Class Reference
laplaceFilter Class Reference
Laplace filter for LES.
Public Member Functions
TypeName ("laplace")
Runtime type information.
laplaceFilter (const fvMesh &mesh, scalar widthCoeff)
Construct from components.
laplaceFilter (const fvMesh &mesh, const dictionary &)
Construct from IOdictionary.
virtual ~laplaceFilter ()
Destructor.
virtual void read (const dictionary &)
Read the LESfilter dictionary.
virtual tmp< volScalarField > operator() (const tmp< volScalarField > &) const
virtual tmp< volVectorField > operator() (const tmp< volVectorField > &) const
virtual tmp< volSymmTensorField > operator() (const tmp< volSymmTensorField > &) const
virtual tmp< volTensorField > operator() (const tmp< volTensorField > &) const
Public Member Functions inherited from LESfilter
TypeName ("LESfilter")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, LESfilter, dictionary,(const fvMesh &mesh, const dictionary &LESfilterDict),(mesh, LESfilterDict))
LESfilter (const fvMesh &mesh)
Construct from components.
virtual ~LESfilter ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
Additional Inherited Members
Static Public Member Functions inherited from LESfilter
static autoPtr< LESfilter > New (const fvMesh &, const dictionary &, const word &filterDictName="filter")
Return a reference to the selected LES filter.
Protected Member Functions inherited from LESfilter
template<class GeoFieldType >
void correctBoundaryConditions (const tmp< GeoFieldType > &tgf) const
Temporary function to ensure the coupled boundary conditions of the.
Detailed Description
Laplace filter for LES.
Kernel                 as filter          as Test filter with ratio 2
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Box filter:            g = delta2/24  ->  g = delta2/6
Spherical box filter:  g = delta2/64  ->  g = delta2/16
Gaussian filter:       g = delta2/24  ->  g = delta2/6
Source files
laplaceFilter.H
laplaceFilter.C
Definition at line 56 of file laplaceFilter.H.
Constructor & Destructor Documentation
laplaceFilter() [1/2]
laplaceFilter (const fvMesh & mesh, scalar widthCoeff)
Construct from components.
Definition at line 43 of file laplaceFilter.C.
References Foam::pow(), GeometricField< Type, PatchField, GeoMesh >::ref(), and fvMesh::V().
laplaceFilter() [2/2]
laplaceFilter (const fvMesh & mesh, const dictionary & bd)
Construct from IOdictionary.
Definition at line 64 of file laplaceFilter.C.
References Foam::pow(), GeometricField< Type, PatchField, GeoMesh >::ref(), and fvMesh::V().
~laplaceFilter()
virtual ~laplaceFilter () inline virtual
Destructor.
Definition at line 89 of file laplaceFilter.H.
References laplaceFilter::read().
Member Function Documentation
TypeName()
TypeName ("laplace")
Runtime type information.
read()
void read (const dictionary & bd) virtual
Read the LESfilter dictionary.
Implements LESfilter.
Definition at line 87 of file laplaceFilter.C.
References dictionary::lookup(), dictionary::subDict(), and Foam::type().
Referenced by laplaceFilter::~laplaceFilter().
operator()() [1/4]
Foam::tmp< Foam::volScalarField > operator() (const tmp< volScalarField > & unFilteredField) const virtual
Implements LESfilter.
Definition at line 96 of file laplaceFilter.C.
References LESfilter::correctBoundaryConditions(), and Foam::fvc::laplacian().
operator()() [2/4]
Foam::tmp< Foam::volVectorField > operator() (const tmp< volVectorField > & unFilteredField) const virtual
Implements LESfilter.
Definition at line 112 of file laplaceFilter.C.
References LESfilter::correctBoundaryConditions(), and Foam::fvc::laplacian().
operator()() [3/4]
Foam::tmp< Foam::volSymmTensorField > operator() (const tmp< volSymmTensorField > & unFilteredField) const virtual
Implements LESfilter.
Definition at line 128 of file laplaceFilter.C.
References LESfilter::correctBoundaryConditions(), and Foam::fvc::laplacian().
operator()() [4/4]
Foam::tmp< Foam::volTensorField > operator() (const tmp< volTensorField > & unFilteredField) const virtual
Implements LESfilter.
Definition at line 144 of file laplaceFilter.C.
References LESfilter::correctBoundaryConditions(), and Foam::fvc::laplacian().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/LES/LESfilters/laplaceFilter/laplaceFilter.H
src/TurbulenceModels/turbulenceModels/LES/LESfilters/laplaceFilter/laplaceFilter.C