OpenFOAM: LESfilter Class Reference
LESfilter Class Reference abstract
Abstract class for LES filters.
Public Member Functions
TypeName ("LESfilter")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, LESfilter, dictionary,(const fvMesh &mesh, const dictionary &LESfilterDict),(mesh, LESfilterDict))
LESfilter (const fvMesh &mesh)
Construct from components.
virtual ~LESfilter ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
virtual void read (const dictionary &)=0
Read the LESfilter dictionary.
virtual tmp< volScalarField > operator() (const tmp< volScalarField > &) const =0
virtual tmp< volVectorField > operator() (const tmp< volVectorField > &) const =0
virtual tmp< volSymmTensorField > operator() (const tmp< volSymmTensorField > &) const =0
virtual tmp< volTensorField > operator() (const tmp< volTensorField > &) const =0
Static Public Member Functions
static autoPtr< LESfilter > New (const fvMesh &, const dictionary &, const word &filterDictName="filter")
Return a reference to the selected LES filter.
Protected Member Functions
template<class GeoFieldType >
void correctBoundaryConditions (const tmp< GeoFieldType > &tgf) const
Temporary function to ensure the coupled boundary conditions of the.
Detailed Description
Abstract class for LES filters.
Source files
LESfilter.H
LESfilter.C
newFilter.C
Definition at line 54 of file LESfilter.H.
Constructor & Destructor Documentation
LESfilter()
LESfilter (const fvMesh & mesh) inline
Construct from components.
Definition at line 109 of file LESfilter.H.
References LESfilter::New().
~LESfilter()
virtual ~LESfilter () inline virtual
Destructor.
Definition at line 127 of file LESfilter.H.
Member Function Documentation
correctBoundaryConditions()
void correctBoundaryConditions (const tmp< GeoFieldType > & tgf) const inline protected
Temporary function to ensure the coupled boundary conditions of the.
field are correct for filtering.
Following the rewrite of the turbulence models to use GeometricField::InternalField for sources etc. delta() will return a GeometricField::InternalField and filters will take a tmp<GeometricField::InternalField> argument and handle the coupled BCs appropriately
Definition at line 79 of file LESfilter.H.
References LESfilter::declareRunTimeSelectionTable(), LESfilter::mesh(), and LESfilter::TypeName().
Referenced by simpleFilter::operator()(), and laplaceFilter::operator()().
TypeName()
TypeName ("LESfilter")
Runtime type information.
Referenced by LESfilter::correctBoundaryConditions().
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , LESfilter , dictionary , (const fvMesh &mesh, const dictionary &LESfilterDict) , (mesh, LESfilterDict))
Referenced by LESfilter::correctBoundaryConditions().
New()
Foam::autoPtr< Foam::LESfilter > New (const fvMesh & mesh, const dictionary & dict, const word & filterDictName = "filter") static
Return a reference to the selected LES filter.
Definition at line 41 of file LESfilter.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, dictionary::lookup(), mesh, and Foam::nl.
Referenced by LESfilter::LESfilter().
mesh()
const fvMesh& mesh () const inline
Return mesh reference.
Definition at line 134 of file LESfilter.H.
References LESfilter::read().
Referenced by LESfilter::correctBoundaryConditions(), and simpleFilter::operator()().
read()
virtual void read (const dictionary &) pure virtual
Read the LESfilter dictionary.
Implemented in laplaceFilter, anisotropicFilter, and simpleFilter.
Referenced by LESfilter::mesh().
operator()() [1/4]
virtual tmp<volScalarField> operator() (const tmp< volScalarField > &) const pure virtual
Implemented in laplaceFilter, anisotropicFilter, and simpleFilter.
operator()() [2/4]
virtual tmp<volVectorField> operator() (const tmp< volVectorField > &) const pure virtual
Implemented in laplaceFilter, anisotropicFilter, and simpleFilter.
operator()() [3/4]
virtual tmp<volSymmTensorField> operator() (const tmp< volSymmTensorField > &) const pure virtual
Implemented in laplaceFilter, anisotropicFilter, and simpleFilter.
operator()() [4/4]
virtual tmp<volTensorField> operator() (const tmp< volTensorField > &) const pure virtual
Implemented in laplaceFilter, anisotropicFilter, and simpleFilter.
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/LES/LESfilters/LESfilter/LESfilter.H
src/TurbulenceModels/turbulenceModels/LES/LESfilters/LESfilter/LESfilter.C