OpenFOAM: LaunderSharmaKE< BasicTurbulenceModel > Class Template Reference
LaunderSharmaKE< BasicTurbulenceModel > Class Template Reference
Turbulence » RAS turbulence
Launder and Sharma low-Reynolds k-epsilon turbulence model for incompressible and compressible and combusting flows including rapid distortion theory (RDT) based compression term.
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
typedef RASModel< BasicTurbulenceModel > ::alphaField alphaField
typedef RASModel< BasicTurbulenceModel > ::rhoField rhoField
typedef RASModel< BasicTurbulenceModel > ::transportModel transportModel
Public Types inherited from linearViscousStress< RASModel< BasicTurbulenceModel > >
typedef RASModel< BasicTurbulenceModel > ::alphaField alphaField
typedef RASModel< BasicTurbulenceModel > ::rhoField rhoField
typedef RASModel< BasicTurbulenceModel > ::transportModel transportModel
Public Types inherited from RASModel< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("LaunderSharmaKE")
Runtime type information.
LaunderSharmaKE (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
Construct from components.
virtual ~LaunderSharmaKE ()
Destructor.
virtual bool read ()
Re-read model coefficients if they have changed.
tmp< volScalarField > DkEff () const
Return the effective diffusivity for k.
tmp< volScalarField > DepsilonEff () const
Return the effective diffusivity for epsilon.
virtual tmp< volScalarField > k () const
Return the turbulence kinetic energy.
virtual tmp< volScalarField > epsilon () const
Return the turbulence kinetic energy dissipation rate.
virtual void correct ()
Solve the turbulence equations and correct the turbulence viscosity.
Public Member Functions inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~eddyViscosity ()
Destructor.
volScalarField & evNut ()
Return non-const access to the turbulence viscosity.
virtual tmp< volScalarField > nut () const
Return the turbulence viscosity.
virtual tmp< scalarField > nut (const label patchi) const
Return the turbulence viscosity on patch.
virtual tmp< volSymmTensorField > R () const
Return the Reynolds stress tensor.
virtual void validate ()
Validate the turbulence fields after construction.
Public Member Functions inherited from linearViscousStress< RASModel< BasicTurbulenceModel > >
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~linearViscousStress ()
Destructor.
virtual tmp< volSymmTensorField > devRhoReff () const
Return the effective stress tensor.
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
Return the source term for the momentum equation.
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Return the source term for the momentum equation.
Public Member Functions inherited from RASModel< BasicTurbulenceModel >
TypeName ("RAS")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, RASModel, dictionary,(const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName),(alpha, rho, U, alphaRhoPhi, phi, transport, propertiesName))
RASModel (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~RASModel ()
Destructor.
const dimensionedScalar & kMin () const
Return the lower allowable limit for k (default: SMALL)
const dimensionedScalar & epsilonMin () const
Return the lower allowable limit for epsilon (default: SMALL)
const dimensionedScalar & omegaMin () const
Return the lower allowable limit for omega (default: SMALL)
dimensionedScalar & kMin ()
Allow kMin to be changed.
dimensionedScalar & epsilonMin ()
Allow epsilonMin to be changed.
dimensionedScalar & omegaMin ()
Allow omegaMin to be changed.
virtual const dictionary & coeffDict () const
Const access to the coefficients dictionary.
virtual tmp< volScalarField > nuEff () const
Return the effective viscosity.
virtual tmp< scalarField > nuEff (const label patchi) const
Return the effective viscosity on patch.
Protected Member Functions
tmp< volScalarField > fMu () const
tmp< volScalarField > f2 () const
virtual void correctNut ()
virtual tmp< fvScalarMatrix > kSource () const
virtual tmp< fvScalarMatrix > epsilonSource () const
Protected Member Functions inherited from RASModel< BasicTurbulenceModel >
virtual void printCoeffs (const word &type)
Print model coefficients.
Protected Attributes
dimensionedScalar Cmu_
dimensionedScalar C1_
dimensionedScalar C2_
dimensionedScalar C3_
dimensionedScalar sigmak_
dimensionedScalar sigmaEps_
volScalarField k_
volScalarField epsilon_
Protected Attributes inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
volScalarField nut_
Protected Attributes inherited from RASModel< BasicTurbulenceModel >
dictionary RASDict_
RAS coefficients dictionary.
Switch turbulence_
Turbulence on/off flag.
Switch printCoeffs_
Flag to print the model coeffs at run-time.
dictionary coeffDict_
Model coefficients dictionary.
dimensionedScalar kMin_
Lower limit of k.
dimensionedScalar epsilonMin_
Lower limit of epsilon.
dimensionedScalar omegaMin_
Lower limit for omega.
Additional Inherited Members
Static Public Member Functions inherited from RASModel< BasicTurbulenceModel >
static autoPtr< RASModel > New (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Return a reference to the selected RAS model.
Detailed Description
template<class BasicTurbulenceModel>
class Foam::RASModels::LaunderSharmaKE< BasicTurbulenceModel >
Launder and Sharma low-Reynolds k-epsilon turbulence model for incompressible and compressible and combusting flows including rapid distortion theory (RDT) based compression term.
References:
    Launder, B. E., & Sharma, B. I. (1974).
    Application of the energy-dissipation model of turbulence to the
    calculation of flow near a spinning disc.
    Letters in heat and mass transfer, 1(2), 131-137.
    For the RDT-based compression term:
    El Tahry, S. H. (1983).
    k-epsilon equation for compressible reciprocating engine flows.
    Journal of Energy, 7(4), 345-353.
The default model coefficients are
    LaunderSharmaKECoeffs
    {
        Cmu         0.09;
        C1          1.44;
        C2          1.92;
        C3          -0.33;
        alphah      1.0;    // only for compressible
        alphahk     1.0;    // only for compressible
        alphaEps    0.76923;
    }
Source files
LaunderSharmaKE.H
LaunderSharmaKE.C
Definition at line 84 of file LaunderSharmaKE.H.
Member Typedef Documentation
alphaField
typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 127 of file LaunderSharmaKE.H.
rhoField
typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 128 of file LaunderSharmaKE.H.
transportModel
typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 129 of file LaunderSharmaKE.H.
Constructor & Destructor Documentation
LaunderSharmaKE()
LaunderSharmaKE (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Construct from components.
Definition at line 100 of file LaunderSharmaKE.C.
References Foam::bound().
~LaunderSharmaKE()
virtual ~LaunderSharmaKE () inline virtual
Destructor.
Definition at line 153 of file LaunderSharmaKE.H.
References LaunderSharmaKE< BasicTurbulenceModel >::read().
Member Function Documentation
fMu()
tmp< volScalarField > fMu () const protected
Definition at line 40 of file LaunderSharmaKE.C.
References Foam::exp(), nu, and Foam::sqr().
f2()
tmp< volScalarField > f2 () const protected
Definition at line 47 of file LaunderSharmaKE.C.
References Foam::exp(), Foam::min(), nu, and Foam::sqr().
correctNut()
void correctNut () protected virtual
Implements eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 56 of file LaunderSharmaKE.C.
References optionList::correct(), options::New(), and Foam::sqr().
kSource()
tmp< fvScalarMatrix > kSource () const protected virtual
Definition at line 67 of file LaunderSharmaKE.C.
References Foam::dimTime, and Foam::dimVolume.
epsilonSource()
tmp< fvScalarMatrix > epsilonSource () const protected virtual
Definition at line 82 of file LaunderSharmaKE.C.
References Foam::dimTime, and Foam::dimVolume.
TypeName()
TypeName ("LaunderSharmaKE< BasicTurbulenceModel >")
Runtime type information.
read()
bool read () virtual
Re-read model coefficients if they have changed.
Implements eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 217 of file LaunderSharmaKE.C.
References Foam::read().
Referenced by LaunderSharmaKE< BasicTurbulenceModel >::~LaunderSharmaKE().
DkEff()
tmp<volScalarField> DkEff () const inline
Return the effective diffusivity for k.
Definition at line 163 of file LaunderSharmaKE.H.
References nu, and eddyViscosity< RASModel< BasicTurbulenceModel > >::nut_.
DepsilonEff()
tmp<volScalarField> DepsilonEff () const inline
Return the effective diffusivity for epsilon.
Definition at line 176 of file LaunderSharmaKE.H.
References nu, and eddyViscosity< RASModel< BasicTurbulenceModel > >::nut_.
k()
virtual tmp<volScalarField> k () const inline virtual
Return the turbulence kinetic energy.
Implements eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 189 of file LaunderSharmaKE.H.
References LaunderSharmaKE< BasicTurbulenceModel >::k_.
epsilon()
virtual tmp<volScalarField> epsilon () const inline virtual
Return the turbulence kinetic energy dissipation rate.
Definition at line 195 of file LaunderSharmaKE.H.
References LaunderSharmaKE< BasicTurbulenceModel >::correct(), and LaunderSharmaKE< BasicTurbulenceModel >::epsilon_.
correct()
void correct () virtual
Solve the turbulence equations and correct the turbulence viscosity.
Implements eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 238 of file LaunderSharmaKE.C.
References Foam::fvc::absolute(), Foam::bound(), tmp< T >::clear(), optionList::constrain(), correct, optionList::correct(), Foam::fvm::ddt(), Foam::dev(), Foam::fvm::div(), Foam::fvc::div(), divU(), fvOptions, Foam::constant::universal::G, Foam::fvc::grad(), Foam::fvm::laplacian(), Foam::magSqr(), Foam::fvc::magSqrGradGrad(), options::New(), nu, nut, phi, tmp< T >::ref(), Foam::solve(), Foam::fvm::Sp(), Foam::sqrt(), Foam::fvm::SuSp(), and Foam::twoSymm().
Referenced by LaunderSharmaKE< BasicTurbulenceModel >::epsilon().
Member Data Documentation
Cmu_
dimensionedScalar Cmu_ protected
Definition at line 101 of file LaunderSharmaKE.H.
C1_
dimensionedScalar C1_ protected
Definition at line 102 of file LaunderSharmaKE.H.
C2_
dimensionedScalar C2_ protected
Definition at line 103 of file LaunderSharmaKE.H.
C3_
dimensionedScalar C3_ protected
Definition at line 104 of file LaunderSharmaKE.H.
sigmak_
dimensionedScalar sigmak_ protected
Definition at line 105 of file LaunderSharmaKE.H.
sigmaEps_
dimensionedScalar sigmaEps_ protected
Definition at line 106 of file LaunderSharmaKE.H.
k_
volScalarField k_ protected
Definition at line 111 of file LaunderSharmaKE.H.
Referenced by LaunderSharmaKE< BasicTurbulenceModel >::k().
epsilon_
volScalarField epsilon_ protected
Definition at line 112 of file LaunderSharmaKE.H.
Referenced by LaunderSharmaKE< BasicTurbulenceModel >::epsilon().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/RAS/LaunderSharmaKE/LaunderSharmaKE.H
src/TurbulenceModels/turbulenceModels/RAS/LaunderSharmaKE/LaunderSharmaKE.C