OpenFOAM: kOmegaSSTSAS< BasicTurbulenceModel > Class Template Reference
kOmegaSSTSAS< BasicTurbulenceModel > Class Template Reference
Turbulence » LES turbulence
Scale-adaptive URAS model based on the k-omega-SST RAS model.
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from kOmegaSST< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from kOmegaSST< eddyViscosity< RASModel< BasicTurbulenceModel > >, BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
typedef RASModel< BasicTurbulenceModel > ::alphaField alphaField
typedef RASModel< BasicTurbulenceModel > ::rhoField rhoField
typedef RASModel< BasicTurbulenceModel > ::transportModel transportModel
Public Types inherited from linearViscousStress< RASModel< BasicTurbulenceModel > >
typedef RASModel< BasicTurbulenceModel > ::alphaField alphaField
typedef RASModel< BasicTurbulenceModel > ::rhoField rhoField
typedef RASModel< BasicTurbulenceModel > ::transportModel transportModel
Public Types inherited from RASModel< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("kOmegaSSTSAS")
Runtime type information.
kOmegaSSTSAS (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
Construct from components.
virtual ~kOmegaSSTSAS ()
Destructor.
virtual bool read ()
Re-read model coefficients if they have changed.
const volScalarField & delta () const
Access function to filter width.
Public Member Functions inherited from kOmegaSST< BasicTurbulenceModel >
TypeName ("kOmegaSST")
Runtime type information.
kOmegaSST (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
Construct from components.
virtual ~kOmegaSST ()
Destructor.
Public Member Functions inherited from kOmegaSST< eddyViscosity< RASModel< BasicTurbulenceModel > >, BasicTurbulenceModel >
kOmegaSST (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Construct from components.
tmp< volScalarField > DkEff (const volScalarField &F1) const
Return the effective diffusivity for k.
tmp< volScalarField > DomegaEff (const volScalarField &F1) const
Return the effective diffusivity for omega.
virtual tmp< volScalarField > k () const
Return the turbulence kinetic energy.
virtual tmp< volScalarField > epsilon () const
Return the turbulence kinetic energy dissipation rate.
virtual tmp< volScalarField > omega () const
Return the turbulence kinetic energy dissipation rate.
virtual void correct ()
Solve the turbulence equations and correct the turbulence viscosity.
Public Member Functions inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~eddyViscosity ()
Destructor.
volScalarField & evNut ()
Return non-const access to the turbulence viscosity.
virtual tmp< volScalarField > nut () const
Return the turbulence viscosity.
virtual tmp< scalarField > nut (const label patchi) const
Return the turbulence viscosity on patch.
virtual tmp< volSymmTensorField > R () const
Return the Reynolds stress tensor.
virtual void validate ()
Validate the turbulence fields after construction.
Public Member Functions inherited from linearViscousStress< RASModel< BasicTurbulenceModel > >
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~linearViscousStress ()
Destructor.
virtual tmp< volSymmTensorField > devRhoReff () const
Return the effective stress tensor.
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
Return the source term for the momentum equation.
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Return the source term for the momentum equation.
Public Member Functions inherited from RASModel< BasicTurbulenceModel >
TypeName ("RAS")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, RASModel, dictionary,(const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName),(alpha, rho, U, alphaRhoPhi, phi, transport, propertiesName))
RASModel (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~RASModel ()
Destructor.
const dimensionedScalar & kMin () const
Return the lower allowable limit for k (default: SMALL)
const dimensionedScalar & epsilonMin () const
Return the lower allowable limit for epsilon (default: SMALL)
const dimensionedScalar & omegaMin () const
Return the lower allowable limit for omega (default: SMALL)
dimensionedScalar & kMin ()
Allow kMin to be changed.
dimensionedScalar & epsilonMin ()
Allow epsilonMin to be changed.
dimensionedScalar & omegaMin ()
Allow omegaMin to be changed.
virtual const dictionary & coeffDict () const
Const access to the coefficients dictionary.
virtual tmp< volScalarField > nuEff () const
Return the effective viscosity.
virtual tmp< scalarField > nuEff (const label patchi) const
Return the effective viscosity on patch.
Protected Member Functions
virtual tmp< fvScalarMatrix > Qsas (const volScalarField::Internal &S2, const volScalarField::Internal &gamma, const volScalarField::Internal &beta) const
SAS omega source.
Protected Member Functions inherited from kOmegaSST< eddyViscosity< RASModel< BasicTurbulenceModel > >, BasicTurbulenceModel >
virtual tmp< volScalarField > F1 (const volScalarField &CDkOmega) const
virtual tmp< volScalarField > F2 () const
virtual tmp< volScalarField > F3 () const
virtual tmp< volScalarField > F23 () const
tmp< volScalarField > blend (const volScalarField &F1, const dimensionedScalar &psi1, const dimensionedScalar &psi2) const
tmp< volScalarField::Internal > blend (const volScalarField::Internal &F1, const dimensionedScalar &psi1, const dimensionedScalar &psi2) const
tmp< volScalarField > alphaK (const volScalarField &F1) const
tmp< volScalarField > alphaOmega (const volScalarField &F1) const
tmp< volScalarField::Internal > beta (const volScalarField::Internal &F1) const
tmp< volScalarField::Internal > gamma (const volScalarField::Internal &F1) const
void correctNut (const volScalarField &S2, const volScalarField &F2)
virtual void correctNut ()
virtual tmp< volScalarField::Internal > Pk (const volScalarField::Internal &G) const
Return k production rate.
virtual tmp< volScalarField::Internal > epsilonByk (const volScalarField::Internal &F1, const volScalarField::Internal &F2) const
Return epsilon/k which for standard RAS is betaStar*omega.
virtual tmp< fvScalarMatrix > kSource () const
virtual tmp< fvScalarMatrix > omegaSource () const
virtual tmp< fvScalarMatrix > Qsas (const volScalarField::Internal &S2, const volScalarField::Internal &gamma, const volScalarField::Internal &beta) const
Protected Member Functions inherited from RASModel< BasicTurbulenceModel >
virtual void printCoeffs (const word &type)
Print model coefficients.
Protected Attributes
dimensionedScalar Cs_
dimensionedScalar kappa_
dimensionedScalar zeta2_
dimensionedScalar sigmaPhi_
dimensionedScalar C_
autoPtr< Foam::LESdelta > delta_
Run-time selectable delta model.
Protected Attributes inherited from kOmegaSST< eddyViscosity< RASModel< BasicTurbulenceModel > >, BasicTurbulenceModel >
dimensionedScalar alphaK1_
dimensionedScalar alphaK2_
dimensionedScalar alphaOmega1_
dimensionedScalar alphaOmega2_
dimensionedScalar gamma1_
dimensionedScalar gamma2_
dimensionedScalar beta1_
dimensionedScalar beta2_
dimensionedScalar betaStar_
dimensionedScalar a1_
dimensionedScalar b1_
dimensionedScalar c1_
Switch F3_
const volScalarField & y_
Wall distance.
volScalarField k_
volScalarField omega_
Protected Attributes inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
volScalarField nut_
Protected Attributes inherited from RASModel< BasicTurbulenceModel >
dictionary RASDict_
RAS coefficients dictionary.
Switch turbulence_
Turbulence on/off flag.
Switch printCoeffs_
Flag to print the model coeffs at run-time.
dictionary coeffDict_
Model coefficients dictionary.
dimensionedScalar kMin_
Lower limit of k.
dimensionedScalar epsilonMin_
Lower limit of epsilon.
dimensionedScalar omegaMin_
Lower limit for omega.
Additional Inherited Members
Static Public Member Functions inherited from RASModel< BasicTurbulenceModel >
static autoPtr< RASModel > New (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Return a reference to the selected RAS model.
Detailed Description
template<class BasicTurbulenceModel>
class Foam::RASModels::kOmegaSSTSAS< BasicTurbulenceModel >
Scale-adaptive URAS model based on the k-omega-SST RAS model.
References:
    Egorov, Y., & Menter F.R. (2008).
    Development and Application of SST-SAS Model in the DESIDER Project.
    Advances in Hybrid RANS-LES Modelling,
    Notes on Num. Fluid Mech. And Multidisciplinary Design,
    Volume 97, 261-270.
The model coefficients are
    kOmegaSSTSASCoeffs
    {
        // Default SST coefficients
        alphaK1     0.85;
        alphaK2     1.0;
        alphaOmega1 0.5;
        alphaOmega2 0.856;
        beta1       0.075;
        beta2       0.0828;
        betaStar    0.09;
        gamma1      5/9;
        gamma2      0.44;
        a1          0.31;
        b1          1.0;
        c1          10.0;
        F3          no;
        // Default SAS coefficients
        Cs          0.11;
        kappa       0.41;
        zeta2       3.51;
        sigmaPhi    2.0/3.0;
        C           2;
        // Delta must be specified for SAS e.g.
        delta cubeRootVol;
        cubeRootVolCoeffs
        {}
    }
Source files
kOmegaSSTSAS.H
kOmegaSSTSAS.C
Definition at line 98 of file kOmegaSSTSAS.H.
Member Typedef Documentation
alphaField
typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 141 of file kOmegaSSTSAS.H.
rhoField
typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 142 of file kOmegaSSTSAS.H.
transportModel
typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 143 of file kOmegaSSTSAS.H.
Constructor & Destructor Documentation
kOmegaSSTSAS()
kOmegaSSTSAS (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Construct from components.
Definition at line 97 of file kOmegaSSTSAS.C.
~kOmegaSSTSAS()
virtual ~kOmegaSSTSAS () inline virtual
Destructor.
Definition at line 167 of file kOmegaSSTSAS.H.
References kOmegaSSTSAS< BasicTurbulenceModel >::read().
Member Function Documentation
Qsas()
tmp< fvScalarMatrix > Qsas (const volScalarField::Internal & S2, const volScalarField::Internal & gamma, const volScalarField::Internal & beta) const protected virtual
SAS omega source.
Definition at line 39 of file kOmegaSSTSAS.C.
References delta, Foam::fvc::grad(), Foam::fvc::laplacian(), Foam::mag(), Foam::magSqr(), Foam::max(), Foam::min(), Foam::pow025(), Foam::sqr(), Foam::sqrt(), and Foam::fvm::Su().
TypeName()
TypeName ("kOmegaSSTSAS< BasicTurbulenceModel >")
Runtime type information.
read()
bool read () virtual
Re-read model coefficients if they have changed.
Reimplemented from kOmegaSST< eddyViscosity< RASModel< BasicTurbulenceModel > >, BasicTurbulenceModel >.
Definition at line 180 of file kOmegaSSTSAS.C.
Referenced by kOmegaSSTSAS< BasicTurbulenceModel >::~kOmegaSSTSAS().
delta()
const volScalarField& delta () const inline
Access function to filter width.
Definition at line 177 of file kOmegaSSTSAS.H.
References kOmegaSSTSAS< BasicTurbulenceModel >::delta_.
Member Data Documentation
Cs_
dimensionedScalar Cs_ protected
Definition at line 115 of file kOmegaSSTSAS.H.
kappa_
dimensionedScalar kappa_ protected
Definition at line 116 of file kOmegaSSTSAS.H.
zeta2_
dimensionedScalar zeta2_ protected
Definition at line 117 of file kOmegaSSTSAS.H.
sigmaPhi_
dimensionedScalar sigmaPhi_ protected
Definition at line 118 of file kOmegaSSTSAS.H.
C_
dimensionedScalar C_ protected
Definition at line 119 of file kOmegaSSTSAS.H.
delta_
autoPtr<Foam::LESdelta> delta_ protected
Run-time selectable delta model.
Definition at line 125 of file kOmegaSSTSAS.H.
Referenced by kOmegaSSTSAS< BasicTurbulenceModel >::delta().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/RAS/kOmegaSSTSAS/kOmegaSSTSAS.H
src/TurbulenceModels/turbulenceModels/RAS/kOmegaSSTSAS/kOmegaSSTSAS.C