OpenFOAM: nonlinearEddyViscosity< BasicTurbulenceModel > Class Template Reference
nonlinearEddyViscosity< BasicTurbulenceModel > Class Template Reference abstract
Turbulence
Eddy viscosity turbulence model with non-linear correction base class.
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from eddyViscosity< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from linearViscousStress< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
nonlinearEddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~nonlinearEddyViscosity ()
Destructor.
virtual tmp< volSymmTensorField > R () const
Return the Reynolds stress tensor.
virtual tmp< volSymmTensorField > devRhoReff () const
Return the effective stress tensor.
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
Return the source term for the momentum equation.
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Return the source term for the momentum equation.
Public Member Functions inherited from eddyViscosity< BasicTurbulenceModel >
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~eddyViscosity ()
Destructor.
virtual bool read ()=0
Re-read model coefficients if they have changed.
volScalarField & evNut ()
Return non-const access to the turbulence viscosity.
virtual tmp< volScalarField > nut () const
Return the turbulence viscosity.
virtual tmp< scalarField > nut (const label patchi) const
Return the turbulence viscosity on patch.
virtual tmp< volScalarField > k () const =0
Return the turbulence kinetic energy.
virtual void validate ()
Validate the turbulence fields after construction.
virtual void correct ()=0
Solve the turbulence equations and correct the turbulence viscosity.
Public Member Functions inherited from linearViscousStress< BasicTurbulenceModel >
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~linearViscousStress ()
Destructor.
Protected Member Functions
virtual void correctNonlinearStress (const volTensorField &gradU)=0
Protected Member Functions inherited from eddyViscosity< BasicTurbulenceModel >
virtual void correctNut ()=0
Protected Attributes
volSymmTensorField nonlinearStress_
Protected Attributes inherited from eddyViscosity< BasicTurbulenceModel >
volScalarField nut_
Detailed Description
template<class BasicTurbulenceModel>
class Foam::nonlinearEddyViscosity< BasicTurbulenceModel >
Eddy viscosity turbulence model with non-linear correction base class.
Source files
nonlinearEddyViscosity.H
nonlinearEddyViscosity.C
Definition at line 52 of file nonlinearEddyViscosity.H.
Member Typedef Documentation
alphaField
typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 73 of file nonlinearEddyViscosity.H.
rhoField
typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 74 of file nonlinearEddyViscosity.H.
transportModel
typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 75 of file nonlinearEddyViscosity.H.
Constructor & Destructor Documentation
nonlinearEddyViscosity()
nonlinearEddyViscosity (const word & modelName, const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName)
Construct from components.
Definition at line 34 of file nonlinearEddyViscosity.C.
~nonlinearEddyViscosity()
virtual ~nonlinearEddyViscosity () inline virtual
Destructor.
Definition at line 95 of file nonlinearEddyViscosity.H.
Member Function Documentation
correctNonlinearStress()
virtual void correctNonlinearStress (const volTensorField & gradU) protected pure virtual
Implemented in LienCubicKE, and ShihQuadraticKE.
R()
Foam::tmp< Foam::volSymmTensorField > R () const virtual
Return the Reynolds stress tensor.
Reimplemented from eddyViscosity< BasicTurbulenceModel >.
Definition at line 80 of file nonlinearEddyViscosity.C.
Referenced by nonlinearEddyViscosity< incompressible::RASModel >::~nonlinearEddyViscosity().
devRhoReff()
Foam::tmp< Foam::volSymmTensorField > devRhoReff () const virtual
Return the effective stress tensor.
Reimplemented from linearViscousStress< BasicTurbulenceModel >.
Definition at line 93 of file nonlinearEddyViscosity.C.
Referenced by nonlinearEddyViscosity< incompressible::RASModel >::~nonlinearEddyViscosity().
divDevRhoReff() [1/2]
Foam::tmp< Foam::fvVectorMatrix > divDevRhoReff (volVectorField & U) const virtual
Return the source term for the momentum equation.
Reimplemented from linearViscousStress< BasicTurbulenceModel >.
Definition at line 107 of file nonlinearEddyViscosity.C.
Referenced by nonlinearEddyViscosity< incompressible::RASModel >::devRhoReff(), nonlinearEddyViscosity< incompressible::RASModel >::divDevRhoReff(), and nonlinearEddyViscosity< incompressible::RASModel >::~nonlinearEddyViscosity().
divDevRhoReff() [2/2]
Foam::tmp< Foam::fvVectorMatrix > divDevRhoReff (const volScalarField & rho, volVectorField & U) const virtual
Return the source term for the momentum equation.
Reimplemented from linearViscousStress< BasicTurbulenceModel >.
Definition at line 122 of file nonlinearEddyViscosity.C.
Member Data Documentation
nonlinearStress_
volSymmTensorField nonlinearStress_ protected
Definition at line 63 of file nonlinearEddyViscosity.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/nonlinearEddyViscosity/nonlinearEddyViscosity.H
src/TurbulenceModels/turbulenceModels/nonlinearEddyViscosity/nonlinearEddyViscosity.C