OpenFOAM: kOmegaSSTLM< BasicTurbulenceModel > Class Template Reference
kOmegaSSTLM< BasicTurbulenceModel > Class Template Reference
Turbulence » LES turbulence
Langtry-Menter 4-equation transitional SST model based on the k-omega-SST RAS model.
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from kOmegaSST< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from kOmegaSST< eddyViscosity< RASModel< BasicTurbulenceModel > >, BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
typedef RASModel< BasicTurbulenceModel > ::alphaField alphaField
typedef RASModel< BasicTurbulenceModel > ::rhoField rhoField
typedef RASModel< BasicTurbulenceModel > ::transportModel transportModel
Public Types inherited from linearViscousStress< RASModel< BasicTurbulenceModel > >
typedef RASModel< BasicTurbulenceModel > ::alphaField alphaField
typedef RASModel< BasicTurbulenceModel > ::rhoField rhoField
typedef RASModel< BasicTurbulenceModel > ::transportModel transportModel
Public Types inherited from RASModel< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("kOmegaSSTLM")
Runtime type information.
kOmegaSSTLM (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
Construct from components.
virtual ~kOmegaSSTLM ()
Destructor.
virtual bool read ()
Re-read model coefficients if they have changed.
const volScalarField & ReThetat () const
Access function transition onset momentum-thickness Reynolds number.
const volScalarField & gammaInt () const
Access function to intermittency.
tmp< volScalarField > DReThetatEff () const
Return the effective diffusivity for transition onset.
tmp< volScalarField > DgammaIntEff () const
Return the effective diffusivity for intermittency.
virtual void correct ()
Solve the turbulence equations and correct the turbulence viscosity.
Public Member Functions inherited from kOmegaSST< BasicTurbulenceModel >
TypeName ("kOmegaSST")
Runtime type information.
kOmegaSST (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
Construct from components.
virtual ~kOmegaSST ()
Destructor.
Public Member Functions inherited from kOmegaSST< eddyViscosity< RASModel< BasicTurbulenceModel > >, BasicTurbulenceModel >
kOmegaSST (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Construct from components.
tmp< volScalarField > DkEff (const volScalarField &F1) const
Return the effective diffusivity for k.
tmp< volScalarField > DomegaEff (const volScalarField &F1) const
Return the effective diffusivity for omega.
virtual tmp< volScalarField > k () const
Return the turbulence kinetic energy.
virtual tmp< volScalarField > epsilon () const
Return the turbulence kinetic energy dissipation rate.
virtual tmp< volScalarField > omega () const
Return the turbulence kinetic energy dissipation rate.
Public Member Functions inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~eddyViscosity ()
Destructor.
volScalarField & evNut ()
Return non-const access to the turbulence viscosity.
virtual tmp< volScalarField > nut () const
Return the turbulence viscosity.
virtual tmp< scalarField > nut (const label patchi) const
Return the turbulence viscosity on patch.
virtual tmp< volSymmTensorField > R () const
Return the Reynolds stress tensor.
virtual void validate ()
Validate the turbulence fields after construction.
Public Member Functions inherited from linearViscousStress< RASModel< BasicTurbulenceModel > >
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~linearViscousStress ()
Destructor.
virtual tmp< volSymmTensorField > devRhoReff () const
Return the effective stress tensor.
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
Return the source term for the momentum equation.
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Return the source term for the momentum equation.
Public Member Functions inherited from RASModel< BasicTurbulenceModel >
TypeName ("RAS")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, RASModel, dictionary,(const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName),(alpha, rho, U, alphaRhoPhi, phi, transport, propertiesName))
RASModel (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~RASModel ()
Destructor.
const dimensionedScalar & kMin () const
Return the lower allowable limit for k (default: SMALL)
const dimensionedScalar & epsilonMin () const
Return the lower allowable limit for epsilon (default: SMALL)
const dimensionedScalar & omegaMin () const
Return the lower allowable limit for omega (default: SMALL)
dimensionedScalar & kMin ()
Allow kMin to be changed.
dimensionedScalar & epsilonMin ()
Allow epsilonMin to be changed.
dimensionedScalar & omegaMin ()
Allow omegaMin to be changed.
virtual const dictionary & coeffDict () const
Const access to the coefficients dictionary.
virtual tmp< volScalarField > nuEff () const
Return the effective viscosity.
virtual tmp< scalarField > nuEff (const label patchi) const
Return the effective viscosity on patch.
Protected Member Functions
virtual tmp< volScalarField > F1 (const volScalarField &CDkOmega) const
Modified form of the k-omega SST F1 function.
virtual tmp< volScalarField::Internal > Pk (const volScalarField::Internal &G) const
Modified form of the k-omega SST k production rate.
virtual tmp< volScalarField::Internal > epsilonByk (const volScalarField::Internal &F1, const volScalarField::Internal &F2) const
Modified form of the k-omega SST epsilon/k.
tmp< volScalarField::Internal > Fthetat (const volScalarField::Internal &Us, const volScalarField::Internal &Omega, const volScalarField::Internal &nu) const
Freestream blending-function.
tmp< volScalarField::Internal > ReThetac () const
Empirical correlation for critical Reynolds number where the.
tmp< volScalarField::Internal > Flength (const volScalarField::Internal &nu) const
Empirical correlation that controls the length of the.
tmp< volScalarField::Internal > Fonset (const volScalarField::Internal &Rev, const volScalarField::Internal &ReThetac, const volScalarField::Internal &RT) const
Transition onset location control function.
tmp< volScalarField::Internal > ReThetat0 (const volScalarField::Internal &Us, const volScalarField::Internal &dUsds, const volScalarField::Internal &nu) const
Return the transition onset momentum-thickness Reynolds number.
void correctReThetatGammaInt ()
Solve the turbulence equations and correct the turbulence viscosity.
Protected Member Functions inherited from kOmegaSST< eddyViscosity< RASModel< BasicTurbulenceModel > >, BasicTurbulenceModel >
virtual tmp< volScalarField > F2 () const
virtual tmp< volScalarField > F3 () const
virtual tmp< volScalarField > F23 () const
tmp< volScalarField > blend (const volScalarField &F1, const dimensionedScalar &psi1, const dimensionedScalar &psi2) const
tmp< volScalarField::Internal > blend (const volScalarField::Internal &F1, const dimensionedScalar &psi1, const dimensionedScalar &psi2) const
tmp< volScalarField > alphaK (const volScalarField &F1) const
tmp< volScalarField > alphaOmega (const volScalarField &F1) const
tmp< volScalarField::Internal > beta (const volScalarField::Internal &F1) const
tmp< volScalarField::Internal > gamma (const volScalarField::Internal &F1) const
void correctNut (const volScalarField &S2, const volScalarField &F2)
virtual void correctNut ()
virtual tmp< volScalarField::Internal > Pk (const volScalarField::Internal &G) const
Return k production rate.
virtual tmp< volScalarField::Internal > epsilonByk (const volScalarField::Internal &F1, const volScalarField::Internal &F2) const
Return epsilon/k which for standard RAS is betaStar*omega.
virtual tmp< fvScalarMatrix > kSource () const
virtual tmp< fvScalarMatrix > omegaSource () const
virtual tmp< fvScalarMatrix > Qsas (const volScalarField::Internal &S2, const volScalarField::Internal &gamma, const volScalarField::Internal &beta) const
Protected Member Functions inherited from RASModel< BasicTurbulenceModel >
virtual void printCoeffs (const word &type)
Print model coefficients.
Protected Attributes
dimensionedScalar ca1_
dimensionedScalar ca2_
dimensionedScalar ce1_
dimensionedScalar ce2_
dimensionedScalar cThetat_
dimensionedScalar sigmaThetat_
scalar lambdaErr_
Convergence criterion for the lambda/thetat loop.
label maxLambdaIter_
Maximum number of iterations to converge the lambda/thetat loop.
const dimensionedScalar deltaU_
Stabilization for division by the magnitude of the velocity.
volScalarField ReThetat_
Transition onset momentum-thickness Reynolds number.
volScalarField gammaInt_
Intermittency.
volScalarField::Internal gammaIntEff_
Effective intermittency.
Protected Attributes inherited from kOmegaSST< eddyViscosity< RASModel< BasicTurbulenceModel > >, BasicTurbulenceModel >
dimensionedScalar alphaK1_
dimensionedScalar alphaK2_
dimensionedScalar alphaOmega1_
dimensionedScalar alphaOmega2_
dimensionedScalar gamma1_
dimensionedScalar gamma2_
dimensionedScalar beta1_
dimensionedScalar beta2_
dimensionedScalar betaStar_
dimensionedScalar a1_
dimensionedScalar b1_
dimensionedScalar c1_
Switch F3_
const volScalarField & y_
Wall distance.
volScalarField k_
volScalarField omega_
Protected Attributes inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
volScalarField nut_
Protected Attributes inherited from RASModel< BasicTurbulenceModel >
dictionary RASDict_
RAS coefficients dictionary.
Switch turbulence_
Turbulence on/off flag.
Switch printCoeffs_
Flag to print the model coeffs at run-time.
dictionary coeffDict_
Model coefficients dictionary.
dimensionedScalar kMin_
Lower limit of k.
dimensionedScalar epsilonMin_
Lower limit of epsilon.
dimensionedScalar omegaMin_
Lower limit for omega.
Additional Inherited Members
Static Public Member Functions inherited from RASModel< BasicTurbulenceModel >
static autoPtr< RASModel > New (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Return a reference to the selected RAS model.
Detailed Description
template<class BasicTurbulenceModel>
class Foam::RASModels::kOmegaSSTLM< BasicTurbulenceModel >
Langtry-Menter 4-equation transitional SST model based on the k-omega-SST RAS model.
References:
    Langtry, R. B., & Menter, F. R. (2009).
    Correlation-based transition modeling for unstructured parallelized
    computational fluid dynamics codes.
    AIAA journal, 47(12), 2894-2906.
    Menter, F. R., Langtry, R., & Volker, S. (2006).
    Transition modelling for general purpose CFD codes.
    Flow, turbulence and combustion, 77(1-4), 277-303.
    Langtry, R. B. (2006).
    A correlation-based transition model using local variables for
    unstructured parallelized CFD codes.
    Phd. Thesis, Universitt Stuttgart.
The model coefficients are
    kOmegaSSTCoeffs
    {
        // Default SST coefficients
        alphaK1     0.85;
        alphaK2     1;
        alphaOmega1 0.5;
        alphaOmega2 0.856;
        beta1       0.075;
        beta2       0.0828;
        betaStar    0.09;
        gamma1      5/9;
        gamma2      0.44;
        a1          0.31;
        b1          1;
        c1          10;
        F3          no;
        // Default LM coefficients
        ca1         2;
        ca2         0.06;
        ce1         1;
        ce2         50;
        cThetat     0.03;
        sigmaThetat 2;
        lambdaErr   1e-6;
        maxLambdaIter 10;
    }
Source files
kOmegaSSTLM.H
kOmegaSSTLM.C
Definition at line 104 of file kOmegaSSTLM.H.
Member Typedef Documentation
alphaField
typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 212 of file kOmegaSSTLM.H.
rhoField
typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 213 of file kOmegaSSTLM.H.
transportModel
typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 214 of file kOmegaSSTLM.H.
Constructor & Destructor Documentation
kOmegaSSTLM()
kOmegaSSTLM (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Construct from components.
Definition at line 357 of file kOmegaSSTLM.C.
~kOmegaSSTLM()
virtual ~kOmegaSSTLM () inline virtual
Destructor.
Definition at line 238 of file kOmegaSSTLM.H.
References kOmegaSSTLM< BasicTurbulenceModel >::read().
Member Function Documentation
F1()
tmp< volScalarField > F1 (const volScalarField & CDkOmega) const protected virtual
Modified form of the k-omega SST F1 function.
Reimplemented from kOmegaSST< eddyViscosity< RASModel< BasicTurbulenceModel > >, BasicTurbulenceModel >.
Definition at line 39 of file kOmegaSSTLM.C.
References Foam::exp(), F3, Foam::max(), nu, kOmegaSSTLM< BasicTurbulenceModel >::Pk(), Foam::pow(), Foam::Ry(), and Foam::sqrt().
Pk()
tmp< volScalarField::Internal > Pk (const volScalarField::Internal & G) const protected virtual
Modified form of the k-omega SST k production rate.
Definition at line 52 of file kOmegaSSTLM.C.
References kOmegaSSTLM< BasicTurbulenceModel >::epsilonByk(), and kOmegaSST< eddyViscosity< RASModel< BasicTurbulenceModel > >, BasicTurbulenceModel >::Pk().
Referenced by kOmegaSSTLM< BasicTurbulenceModel >::F1().
epsilonByk()
tmp< volScalarField::Internal > epsilonByk (const volScalarField::Internal & F1, const volScalarField::Internal & F2) const protected virtual
Modified form of the k-omega SST epsilon/k.
Definition at line 62 of file kOmegaSSTLM.C.
References kOmegaSST< eddyViscosity< RASModel< BasicTurbulenceModel > >, BasicTurbulenceModel >::epsilonByk(), kOmegaSSTLM< BasicTurbulenceModel >::Fthetat(), Foam::max(), and Foam::min().
Referenced by kOmegaSSTLM< BasicTurbulenceModel >::Pk().
Fthetat()
tmp< volScalarField::Internal > Fthetat (const volScalarField::Internal & Us, const volScalarField::Internal & Omega, const volScalarField::Internal & nu) const protected
Freestream blending-function.
Definition at line 75 of file kOmegaSSTLM.C.
References delta, Foam::exp(), IOobject::groupName(), Foam::max(), Foam::min(), Foam::pow4(), Foam::sqr(), and y.
Referenced by kOmegaSSTLM< BasicTurbulenceModel >::epsilonByk().
ReThetac()
tmp< volScalarField::Internal > ReThetac () const protected
Empirical correlation for critical Reynolds number where the.
intermittency first starts to increase in the boundary layer
Definition at line 109 of file kOmegaSSTLM.C.
References Foam::dimless, kOmegaSSTLM< BasicTurbulenceModel >::Flength(), forAll, IOobject::groupName(), Foam::pow3(), Foam::pow4(), and Foam::sqr().
Flength()
tmp< volScalarField::Internal > Flength (const volScalarField::Internal & nu) const protected
Empirical correlation that controls the length of the.
transition region
Definition at line 150 of file kOmegaSSTLM.C.
References Foam::dimless, Foam::e, Foam::exp(), forAll, IOobject::groupName(), Foam::pow3(), kOmegaSSTLM< BasicTurbulenceModel >::ReThetat0(), Foam::sqr(), and y.
Referenced by kOmegaSSTLM< BasicTurbulenceModel >::ReThetac().
Fonset()
tmp< volScalarField::Internal > Fonset (const volScalarField::Internal & Rev, const volScalarField::Internal & ReThetac, const volScalarField::Internal & RT) const protected
Transition onset location control function.
Definition at line 327 of file kOmegaSSTLM.C.
References IOobject::groupName(), Foam::max(), Foam::min(), Foam::pow3(), and Foam::pow4().
Referenced by kOmegaSSTLM< BasicTurbulenceModel >::ReThetat0().
ReThetat0()
tmp< volScalarField::Internal > ReThetat0 (const volScalarField::Internal & Us, const volScalarField::Internal & dUsds, const volScalarField::Internal & nu) const protected
Return the transition onset momentum-thickness Reynolds number.
(based on freestream conditions)
Definition at line 213 of file kOmegaSSTLM.C.
References Foam::dimless, Foam::endl(), Foam::exp(), kOmegaSSTLM< BasicTurbulenceModel >::Fonset(), forAll, IOobject::groupName(), k, lambda(), Foam::mag(), Foam::max(), Foam::min(), Foam::pow(), Foam::pow3(), Foam::sqr(), Foam::sqrt(), and WarningInFunction.
Referenced by kOmegaSSTLM< BasicTurbulenceModel >::Flength().
correctReThetatGammaInt()
void correctReThetatGammaInt () protected
Solve the turbulence equations and correct the turbulence viscosity.
Definition at line 509 of file kOmegaSSTLM.C.
References Foam::constant::atomic::alpha, Foam::bound(), tmp< T >::clear(), optionList::constrain(), optionList::correct(), Foam::fvm::ddt(), Foam::fvm::div(), Foam::exp(), fvOptions, Foam::fvc::grad(), k, Foam::fvm::laplacian(), Foam::mag(), Foam::magSqr(), Foam::max(), Foam::min(), options::New(), nu, Foam::pow4(), tmp< T >::ref(), rho, Foam::skew(), Foam::solve(), Foam::fvm::Sp(), Foam::sqr(), Foam::sqrt(), Foam::symm(), U, and y.
TypeName()
TypeName ("kOmegaSSTLM< BasicTurbulenceModel >")
Runtime type information.
read()
bool read () virtual
Re-read model coefficients if they have changed.
Reimplemented from kOmegaSST< eddyViscosity< RASModel< BasicTurbulenceModel > >, BasicTurbulenceModel >.
Definition at line 486 of file kOmegaSSTLM.C.
Referenced by kOmegaSSTLM< BasicTurbulenceModel >::~kOmegaSSTLM().
ReThetat()
const volScalarField& ReThetat () const inline
Access function transition onset momentum-thickness Reynolds number.
Definition at line 248 of file kOmegaSSTLM.H.
References kOmegaSSTLM< BasicTurbulenceModel >::ReThetat_.
gammaInt()
const volScalarField& gammaInt () const inline
Access function to intermittency.
Definition at line 254 of file kOmegaSSTLM.H.
References kOmegaSSTLM< BasicTurbulenceModel >::DReThetatEff(), kOmegaSSTLM< BasicTurbulenceModel >::gammaInt_, nu, and eddyViscosity< RASModel< BasicTurbulenceModel > >::nut_.
DReThetatEff()
tmp<volScalarField> DReThetatEff () const inline
Return the effective diffusivity for transition onset.
momentum-thickness Reynolds number
Definition at line 261 of file kOmegaSSTLM.H.
Referenced by kOmegaSSTLM< BasicTurbulenceModel >::gammaInt().
DgammaIntEff()
tmp<volScalarField> DgammaIntEff () const inline
Return the effective diffusivity for intermittency.
Definition at line 274 of file kOmegaSSTLM.H.
References kOmegaSSTLM< BasicTurbulenceModel >::correct(), nu, and eddyViscosity< RASModel< BasicTurbulenceModel > >::nut_.
correct()
void correct () virtual
Solve the turbulence equations and correct the turbulence viscosity.
Reimplemented from kOmegaSST< eddyViscosity< RASModel< BasicTurbulenceModel > >, BasicTurbulenceModel >.
Definition at line 607 of file kOmegaSSTLM.C.
References kOmegaSST< eddyViscosity< RASModel< BasicTurbulenceModel > >, BasicTurbulenceModel >::correct().
Referenced by kOmegaSSTLM< BasicTurbulenceModel >::DgammaIntEff().
Member Data Documentation
ca1_
dimensionedScalar ca1_ protected
Definition at line 121 of file kOmegaSSTLM.H.
ca2_
dimensionedScalar ca2_ protected
Definition at line 122 of file kOmegaSSTLM.H.
ce1_
dimensionedScalar ce1_ protected
Definition at line 124 of file kOmegaSSTLM.H.
ce2_
dimensionedScalar ce2_ protected
Definition at line 125 of file kOmegaSSTLM.H.
cThetat_
dimensionedScalar cThetat_ protected
Definition at line 127 of file kOmegaSSTLM.H.
sigmaThetat_
dimensionedScalar sigmaThetat_ protected
Definition at line 128 of file kOmegaSSTLM.H.
lambdaErr_
scalar lambdaErr_ protected
Convergence criterion for the lambda/thetat loop.
Definition at line 131 of file kOmegaSSTLM.H.
maxLambdaIter_
label maxLambdaIter_ protected
Maximum number of iterations to converge the lambda/thetat loop.
Definition at line 134 of file kOmegaSSTLM.H.
deltaU_
const dimensionedScalar deltaU_ protected
Stabilization for division by the magnitude of the velocity.
Definition at line 137 of file kOmegaSSTLM.H.
ReThetat_
volScalarField ReThetat_ protected
Transition onset momentum-thickness Reynolds number.
Definition at line 143 of file kOmegaSSTLM.H.
Referenced by kOmegaSSTLM< BasicTurbulenceModel >::ReThetat().
gammaInt_
volScalarField gammaInt_ protected
Intermittency.
Definition at line 146 of file kOmegaSSTLM.H.
Referenced by kOmegaSSTLM< BasicTurbulenceModel >::gammaInt().
gammaIntEff_
volScalarField::Internal gammaIntEff_ protected
Effective intermittency.
Definition at line 149 of file kOmegaSSTLM.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/RAS/kOmegaSSTLM/kOmegaSSTLM.H
src/TurbulenceModels/turbulenceModels/RAS/kOmegaSSTLM/kOmegaSSTLM.C