OpenFOAM: turbulentMixingLengthDissipationRateInletFvPatchScalarField Class Reference
turbulentMixingLengthDissipationRateInletFvPatchScalarField Class Reference
Turbulence » RAS turbulence » RAS boundary conditionsBoundary Conditions » | Inlet boundary Conditions
This boundary condition provides a turbulence dissipation, (epsilon) inlet condition based on a specified mixing length. The patch values are calculated using:
Public Member Functions
TypeName ("turbulentMixingLengthDissipationRateInlet")
Runtime type information.
turbulentMixingLengthDissipationRateInletFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
turbulentMixingLengthDissipationRateInletFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
turbulentMixingLengthDissipationRateInletFvPatchScalarField (const turbulentMixingLengthDissipationRateInletFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
turbulentMixingLengthDissipationRateInletFvPatchScalarField (const turbulentMixingLengthDissipationRateInletFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
turbulentMixingLengthDissipationRateInletFvPatchScalarField (const turbulentMixingLengthDissipationRateInletFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Detailed Description
This boundary condition provides a turbulence dissipation, (epsilon) inlet condition based on a specified mixing length. The patch values are calculated using:
where
= patch epsilon values
= Model coefficient, set to 0.09
= turbulence kinetic energy
= length scale
Usage
Property Description Required Default value
mixingLength Length scale [m] yes
phi flux field name no phi
k turbulence kinetic energy field name no k
Example of the boundary condition specification:
    <patchName>
    {
        type            turbulentMixingLengthDissipationRateInlet;
        mixingLength    0.005;
        value           uniform 200;   // placeholder
    }
Note
In the event of reverse flow, a zero-gradient condition is applied
See also
Foam::inletOutletFvPatchField
Source files
turbulentMixingLengthDissipationRateInletFvPatchScalarField.H
turbulentMixingLengthDissipationRateInletFvPatchScalarField.C
Definition at line 126 of file turbulentMixingLengthDissipationRateInletFvPatchScalarField.H.
Constructor & Destructor Documentation
turbulentMixingLengthDissipationRateInletFvPatchScalarField() [1/5]
turbulentMixingLengthDissipationRateInletFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 42 of file turbulentMixingLengthDissipationRateInletFvPatchScalarField.C.
Referenced by turbulentMixingLengthDissipationRateInletFvPatchScalarField::clone(), and turbulentMixingLengthDissipationRateInletFvPatchScalarField::turbulentMixingLengthDissipationRateInletFvPatchScalarField().
turbulentMixingLengthDissipationRateInletFvPatchScalarField() [2/5]
turbulentMixingLengthDissipationRateInletFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 74 of file turbulentMixingLengthDissipationRateInletFvPatchScalarField.C.
References dictionary::lookupOrDefault(), fvPatchField< Type >::operator=(), fvPatch::size(), and turbulentMixingLengthDissipationRateInletFvPatchScalarField::turbulentMixingLengthDissipationRateInletFvPatchScalarField().
turbulentMixingLengthDissipationRateInletFvPatchScalarField() [3/5]
turbulentMixingLengthDissipationRateInletFvPatchScalarField (const turbulentMixingLengthDissipationRateInletFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
turbulentMixingLengthDissipationRateInletFvPatchScalarField onto a new patch
Definition at line 59 of file turbulentMixingLengthDissipationRateInletFvPatchScalarField.C.
References turbulentMixingLengthDissipationRateInletFvPatchScalarField::turbulentMixingLengthDissipationRateInletFvPatchScalarField().
turbulentMixingLengthDissipationRateInletFvPatchScalarField() [4/5]
turbulentMixingLengthDissipationRateInletFvPatchScalarField (const turbulentMixingLengthDissipationRateInletFvPatchScalarField & ptf)
Construct as copy.
Definition at line 96 of file turbulentMixingLengthDissipationRateInletFvPatchScalarField.C.
References turbulentMixingLengthDissipationRateInletFvPatchScalarField::turbulentMixingLengthDissipationRateInletFvPatchScalarField().
turbulentMixingLengthDissipationRateInletFvPatchScalarField() [5/5]
turbulentMixingLengthDissipationRateInletFvPatchScalarField (const turbulentMixingLengthDissipationRateInletFvPatchScalarField & ptf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 108 of file turbulentMixingLengthDissipationRateInletFvPatchScalarField.C.
Member Function Documentation
TypeName()
TypeName ("turbulentMixingLengthDissipationRateInlet")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 180 of file turbulentMixingLengthDissipationRateInletFvPatchScalarField.H.
References turbulentMixingLengthDissipationRateInletFvPatchScalarField::turbulentMixingLengthDissipationRateInletFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 200 of file turbulentMixingLengthDissipationRateInletFvPatchScalarField.H.
References turbulentMixingLengthDissipationRateInletFvPatchScalarField::turbulentMixingLengthDissipationRateInletFvPatchScalarField(), turbulentMixingLengthDissipationRateInletFvPatchScalarField::updateCoeffs(), and turbulentMixingLengthDissipationRateInletFvPatchScalarField::write().
updateCoeffs()
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 121 of file turbulentMixingLengthDissipationRateInletFvPatchScalarField.C.
References turbulenceModel::coeffDict(), Foam::constant::atomic::group, IOobject::groupName(), dictionary::lookupOrDefault(), Foam::pos(), Foam::pow(), turbulenceModel::propertiesName, Foam::sqrt(), and turbulentMixingLengthDissipationRateInletFvPatchScalarField::write().
Referenced by turbulentMixingLengthDissipationRateInletFvPatchScalarField::clone().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 157 of file turbulentMixingLengthDissipationRateInletFvPatchScalarField.C.
References token::END_STATEMENT, Foam::makePatchTypeField(), Foam::nl, fvPatchField< Type >::write(), and Ostream::writeKeyword().
Referenced by turbulentMixingLengthDissipationRateInletFvPatchScalarField::clone(), and turbulentMixingLengthDissipationRateInletFvPatchScalarField::updateCoeffs().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/RAS/derivedFvPatchFields/turbulentMixingLengthDissipationRateInlet/turbulentMixingLengthDissipationRateInletFvPatchScalarField.H
src/TurbulenceModels/turbulenceModels/RAS/derivedFvPatchFields/turbulentMixingLengthDissipationRateInlet/turbulentMixingLengthDissipationRateInletFvPatchScalarField.C