OpenFOAM: v2fBase Class Reference
v2fBase Class Reference abstract
Turbulence » RAS turbulence
Abstract base-class for v2-f models to provide BCs access to the v2 and f fields.
Public Member Functions
TypeName ("v2fBase")
Runtime type information.
v2fBase ()
virtual ~v2fBase ()
Destructor.
virtual tmp< volScalarField > v2 () const =0
Return turbulence stress normal to streamlines.
virtual tmp< volScalarField > f () const =0
Return the damping function.
Detailed Description
Abstract base-class for v2-f models to provide BCs access to the v2 and f fields.
See also
Foam::RASModels::v2f
Source files
v2fBase.H
v2fBase.C
Definition at line 57 of file v2fBase.H.
Constructor & Destructor Documentation
v2fBase()
v2fBase () inline
Definition at line 67 of file v2fBase.H.
~v2fBase()
virtual ~v2fBase () inline virtual
Destructor.
Definition at line 72 of file v2fBase.H.
References v2fBase::f(), and v2fBase::v2().
Member Function Documentation
TypeName()
TypeName ("v2fBase")
Runtime type information.
v2()
virtual tmp<volScalarField> v2 () const pure virtual
Return turbulence stress normal to streamlines.
Implemented in v2f< BasicTurbulenceModel >.
Referenced by v2fBase::~v2fBase().
f()
virtual tmp<volScalarField> f () const pure virtual
Return the damping function.
Implemented in v2f< BasicTurbulenceModel >.
Referenced by v2fBase::~v2fBase().
The documentation for this class was generated from the following file:
src/TurbulenceModels/turbulenceModels/RAS/v2f/v2fBase.H