OpenFOAM: kOmega< BasicTurbulenceModel > Class Template Reference
kOmega< BasicTurbulenceModel > Class Template Reference
Turbulence » RAS turbulence
Standard high Reynolds-number k-omega turbulence model for incompressible and compressible flows.
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
typedef RASModel< BasicTurbulenceModel > ::alphaField alphaField
typedef RASModel< BasicTurbulenceModel > ::rhoField rhoField
typedef RASModel< BasicTurbulenceModel > ::transportModel transportModel
Public Types inherited from linearViscousStress< RASModel< BasicTurbulenceModel > >
typedef RASModel< BasicTurbulenceModel > ::alphaField alphaField
typedef RASModel< BasicTurbulenceModel > ::rhoField rhoField
typedef RASModel< BasicTurbulenceModel > ::transportModel transportModel
Public Types inherited from RASModel< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("kOmega")
Runtime type information.
kOmega (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
Construct from components.
virtual ~kOmega ()
Destructor.
virtual bool read ()
Read RASProperties dictionary.
tmp< volScalarField > DkEff () const
Return the effective diffusivity for k.
tmp< volScalarField > DomegaEff () const
Return the effective diffusivity for omega.
virtual tmp< volScalarField > k () const
Return the turbulence kinetic energy.
virtual tmp< volScalarField > omega () const
Return the turbulence specific dissipation rate.
virtual tmp< volScalarField > epsilon () const
Return the turbulence kinetic energy dissipation rate.
virtual void correct ()
Solve the turbulence equations and correct the turbulence viscosity.
Public Member Functions inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~eddyViscosity ()
Destructor.
volScalarField & evNut ()
Return non-const access to the turbulence viscosity.
virtual tmp< volScalarField > nut () const
Return the turbulence viscosity.
virtual tmp< scalarField > nut (const label patchi) const
Return the turbulence viscosity on patch.
virtual tmp< volSymmTensorField > R () const
Return the Reynolds stress tensor.
virtual void validate ()
Validate the turbulence fields after construction.
Public Member Functions inherited from linearViscousStress< RASModel< BasicTurbulenceModel > >
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~linearViscousStress ()
Destructor.
virtual tmp< volSymmTensorField > devRhoReff () const
Return the effective stress tensor.
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
Return the source term for the momentum equation.
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Return the source term for the momentum equation.
Public Member Functions inherited from RASModel< BasicTurbulenceModel >
TypeName ("RAS")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, RASModel, dictionary,(const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName),(alpha, rho, U, alphaRhoPhi, phi, transport, propertiesName))
RASModel (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~RASModel ()
Destructor.
const dimensionedScalar & kMin () const
Return the lower allowable limit for k (default: SMALL)
const dimensionedScalar & epsilonMin () const
Return the lower allowable limit for epsilon (default: SMALL)
const dimensionedScalar & omegaMin () const
Return the lower allowable limit for omega (default: SMALL)
dimensionedScalar & kMin ()
Allow kMin to be changed.
dimensionedScalar & epsilonMin ()
Allow epsilonMin to be changed.
dimensionedScalar & omegaMin ()
Allow omegaMin to be changed.
virtual const dictionary & coeffDict () const
Const access to the coefficients dictionary.
virtual tmp< volScalarField > nuEff () const
Return the effective viscosity.
virtual tmp< scalarField > nuEff (const label patchi) const
Return the effective viscosity on patch.
Protected Member Functions
virtual void correctNut ()
Protected Member Functions inherited from RASModel< BasicTurbulenceModel >
virtual void printCoeffs (const word &type)
Print model coefficients.
Protected Attributes
dimensionedScalar Cmu_
dimensionedScalar beta_
dimensionedScalar gamma_
dimensionedScalar alphaK_
dimensionedScalar alphaOmega_
volScalarField k_
volScalarField omega_
Protected Attributes inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
volScalarField nut_
Protected Attributes inherited from RASModel< BasicTurbulenceModel >
dictionary RASDict_
RAS coefficients dictionary.
Switch turbulence_
Turbulence on/off flag.
Switch printCoeffs_
Flag to print the model coeffs at run-time.
dictionary coeffDict_
Model coefficients dictionary.
dimensionedScalar kMin_
Lower limit of k.
dimensionedScalar epsilonMin_
Lower limit of epsilon.
dimensionedScalar omegaMin_
Lower limit for omega.
Additional Inherited Members
Static Public Member Functions inherited from RASModel< BasicTurbulenceModel >
static autoPtr< RASModel > New (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Return a reference to the selected RAS model.
Detailed Description
template<class BasicTurbulenceModel>
class Foam::RASModels::kOmega< BasicTurbulenceModel >
Standard high Reynolds-number k-omega turbulence model for incompressible and compressible flows.
References:
    Wilcox, D. C. (1998).
    Turbulence modeling for CFD
    (Vol. 2, pp. 103-217). La Canada, CA: DCW industries.
The default model coefficients are
    kOmegaCoeffs
    {
        Cmu         0.09;  // Equivalent to betaStar
        alpha       0.52;
        beta        0.072;
        alphak      0.5;
        alphaOmega  0.5;
    }
Source files
kOmega.H
kOmega.C
Definition at line 75 of file kOmega.H.
Member Typedef Documentation
alphaField
typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 106 of file kOmega.H.
rhoField
typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 107 of file kOmega.H.
transportModel
typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 108 of file kOmega.H.
Constructor & Destructor Documentation
kOmega()
kOmega (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Construct from components.
Definition at line 54 of file kOmega.C.
References Foam::bound().
Referenced by kOmega< BasicTurbulenceModel >::correctNut().
~kOmega()
virtual ~kOmega () inline virtual
Destructor.
Definition at line 132 of file kOmega.H.
References kOmega< BasicTurbulenceModel >::read().
Member Function Documentation
correctNut()
void correctNut () protected virtual
Implements eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 40 of file kOmega.C.
References optionList::correct(), kOmega< BasicTurbulenceModel >::kOmega(), and options::New().
TypeName()
TypeName ("kOmega< BasicTurbulenceModel >")
Runtime type information.
read()
bool read () virtual
Read RASProperties dictionary.
Implements eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 161 of file kOmega.C.
References Foam::read().
Referenced by kOmega< BasicTurbulenceModel >::~kOmega().
DkEff()
tmp<volScalarField> DkEff () const inline
Return the effective diffusivity for k.
Definition at line 142 of file kOmega.H.
References nu, and eddyViscosity< RASModel< BasicTurbulenceModel > >::nut_.
DomegaEff()
tmp<volScalarField> DomegaEff () const inline
Return the effective diffusivity for omega.
Definition at line 155 of file kOmega.H.
References nu, and eddyViscosity< RASModel< BasicTurbulenceModel > >::nut_.
k()
virtual tmp<volScalarField> k () const inline virtual
Return the turbulence kinetic energy.
Implements eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 168 of file kOmega.H.
References kOmega< BasicTurbulenceModel >::k_.
omega()
virtual tmp<volScalarField> omega () const inline virtual
Return the turbulence specific dissipation rate.
Definition at line 174 of file kOmega.H.
References kOmega< BasicTurbulenceModel >::omega_.
epsilon()
virtual tmp<volScalarField> epsilon () const inline virtual
Return the turbulence kinetic energy dissipation rate.
Definition at line 180 of file kOmega.H.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), and kOmega< BasicTurbulenceModel >::correct().
correct()
void correct () virtual
Solve the turbulence equations and correct the turbulence viscosity.
Implements eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 181 of file kOmega.C.
References Foam::fvc::absolute(), Foam::bound(), tmp< T >::clear(), optionList::constrain(), correct, optionList::correct(), Foam::fvm::ddt(), Foam::dev(), Foam::fvm::div(), Foam::fvc::div(), divU(), fvOptions, Foam::constant::universal::G, Foam::fvc::grad(), Foam::fvm::laplacian(), options::New(), nut, phi, tmp< T >::ref(), Foam::solve(), Foam::fvm::Sp(), Foam::fvm::SuSp(), and Foam::twoSymm().
Referenced by kOmega< BasicTurbulenceModel >::epsilon().
Member Data Documentation
Cmu_
dimensionedScalar Cmu_ protected
Definition at line 86 of file kOmega.H.
beta_
dimensionedScalar beta_ protected
Definition at line 87 of file kOmega.H.
gamma_
dimensionedScalar gamma_ protected
Definition at line 88 of file kOmega.H.
alphaK_
dimensionedScalar alphaK_ protected
Definition at line 89 of file kOmega.H.
alphaOmega_
dimensionedScalar alphaOmega_ protected
Definition at line 90 of file kOmega.H.
k_
volScalarField k_ protected
Definition at line 95 of file kOmega.H.
Referenced by kOmega< BasicTurbulenceModel >::k().
omega_
volScalarField omega_ protected
Definition at line 96 of file kOmega.H.
Referenced by kOmega< BasicTurbulenceModel >::omega().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/RAS/kOmega/kOmega.H
src/TurbulenceModels/turbulenceModels/RAS/kOmega/kOmega.C