OpenFOAM: turbulenceModel Class Reference
turbulenceModel Class Reference abstract
Turbulence
Abstract base class for turbulence models (RAS, LES and laminar).
Public Member Functions
TypeName ("turbulenceModel")
Runtime type information.
turbulenceModel (const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const word &propertiesName)
Construct from components.
virtual ~turbulenceModel ()
Destructor.
virtual bool read ()=0
Read model coefficients if they have changed.
const Time & time () const
const fvMesh & mesh () const
virtual const dictionary & coeffDict () const =0
Const access to the coefficients dictionary.
word GName () const
Helper function to return the name of the turbulence G field.
const volVectorField & U () const
Access function to velocity field.
const surfaceScalarField & alphaRhoPhi () const
Access function to phase flux field.
virtual tmp< surfaceScalarField > phi () const
Return the volumetric flux field.
const nearWallDist & y () const
Return the near wall distances.
virtual tmp< volScalarField > nu () const =0
Return the laminar viscosity.
virtual tmp< scalarField > nu (const label patchi) const =0
Return the laminar viscosity on patch.
virtual tmp< volScalarField > nut () const =0
Return the turbulence viscosity.
virtual tmp< scalarField > nut (const label patchi) const =0
Return the turbulence viscosity on patch.
virtual tmp< volScalarField > nuEff () const =0
Return the effective viscosity.
virtual tmp< scalarField > nuEff (const label patchi) const =0
Return the effective viscosity on patch.
virtual tmp< volScalarField > mu () const =0
Return the laminar dynamic viscosity.
virtual tmp< scalarField > mu (const label patchi) const =0
Return the laminar dynamic viscosity on patch.
virtual tmp< volScalarField > mut () const =0
Return the turbulence dynamic viscosity.
virtual tmp< scalarField > mut (const label patchi) const =0
Return the turbulence dynamic viscosity on patch.
virtual tmp< volScalarField > muEff () const =0
Return the effective dynamic viscosity.
virtual tmp< scalarField > muEff (const label patchi) const =0
Return the effective dynamic viscosity on patch.
virtual tmp< volScalarField > k () const =0
Return the turbulence kinetic energy.
virtual tmp< volScalarField > epsilon () const =0
Return the turbulence kinetic energy dissipation rate.
virtual tmp< volSymmTensorField > R () const =0
Return the Reynolds stress tensor.
virtual void validate ()
Validate the turbulence fields after construction.
virtual void correct ()=0
Solve the turbulence equations and correct the turbulence viscosity.
Public Member Functions inherited from IOdictionary
TypeName ("dictionary")
IOdictionary (const IOobject &)
Construct given an IOobject.
IOdictionary (const IOobject &, const dictionary &)
Construct given an IOobject and dictionary.
IOdictionary (const IOobject &, Istream &)
Construct given an IOobject and Istream.
virtual ~IOdictionary ()
Destructor.
const word & name () const
Name function is needed to disambiguate those inherited.
bool readData (Istream &)
ReadData function required for regIOobject read operation.
bool writeData (Ostream &) const
WriteData function required for regIOobject write operation.
void operator= (const IOdictionary &)
Assignment of other IOdictionary's entries to this IOdictionary.
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, transferring registry registration to copy.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Construct as copy with new name, transfering registry registration.
regIOobject (const IOobject &, const regIOobject &)
Construct as copy with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
virtual void rename (const word &newName)
Rename.
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType) const
Write using given format, version and compression.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Public Member Functions inherited from dictionary
ClassName ("dictionary")
dictionary ()
Construct top-level dictionary null.
dictionary (const fileName &name)
Construct top-level empty dictionary with given name.
dictionary (const fileName &name, const dictionary &parentDict, Istream &)
Construct given the entry name, parent dictionary and Istream,.
dictionary (Istream &)
Construct top-level dictionary from Istream,.
dictionary (Istream &, const bool keepHeader)
Construct top-level dictionary from Istream,.
dictionary (const dictionary &parentDict, const dictionary &)
Construct as copy given the parent dictionary.
dictionary (const dictionary &)
Construct top-level dictionary as copy.
dictionary (const dictionary *)
Construct top-level dictionary as copy from pointer to dictionary.
dictionary (const dictionary &parentDict, const Xfer< dictionary > &)
Construct by transferring parameter contents given parent dictionary.
dictionary (const Xfer< dictionary > &)
Construct top-level dictionary by transferring parameter contents.
autoPtr< dictionary > clone () const
Construct and return clone.
virtual ~dictionary ()
Destructor.
const dictionary & parent () const
Return the parent dictionary.
const dictionary & topDict () const
Return the top of the tree.
label startLineNumber () const
Return line number of first token in dictionary.
label endLineNumber () const
Return line number of last token in dictionary.
SHA1Digest digest () const
Return the SHA1 digest of the dictionary contents.
tokenList tokens () const
Return the dictionary as a list of tokens.
bool found (const word &, bool recursive=false, bool patternMatch=true) const
Search dictionary for given keyword.
const entry * lookupEntryPtr (const word &, bool recursive, bool patternMatch) const
Find and return an entry data stream pointer if present.
entry * lookupEntryPtr (const word &, bool recursive, bool patternMatch)
Find and return an entry data stream pointer for manipulation.
const entry & lookupEntry (const word &, bool recursive, bool patternMatch) const
Find and return an entry data stream if present otherwise error.
ITstream & lookup (const word &, bool recursive=false, bool patternMatch=true) const
Find and return an entry data stream.
template<class T >
T lookupOrDefault (const word &, const T &, bool recursive=false, bool patternMatch=true) const
Find and return a T,.
template<class T >
T lookupOrAddDefault (const word &, const T &, bool recursive=false, bool patternMatch=true)
Find and return a T, if not found return the given.
template<class T >
bool readIfPresent (const word &, T &, bool recursive=false, bool patternMatch=true) const
Find an entry if present, and assign to T.
const entry * lookupScopedEntryPtr (const word &, bool recursive, bool patternMatch) const
Find and return an entry data stream pointer if present.
bool isDict (const word &) const
Check if entry is a sub-dictionary.
const dictionary * subDictPtr (const word &) const
Find and return a sub-dictionary pointer if present.
const dictionary & subDict (const word &) const
Find and return a sub-dictionary.
dictionary & subDict (const word &)
Find and return a sub-dictionary for manipulation.
dictionary subOrEmptyDict (const word &, const bool mustRead=false) const
Find and return a sub-dictionary as a copy, or.
wordList toc () const
Return the table of contents.
wordList sortedToc () const
Return the sorted table of contents.
List< keyType > keys (bool patterns=false) const
Return the list of available keys or patterns.
bool substituteKeyword (const word &keyword)
Substitute the given keyword prepended by '$' with the.
bool substituteScopedKeyword (const word &keyword)
Substitute the given scoped keyword prepended by '$' with the.
bool add (entry *, bool mergeEntry=false)
Add a new entry.
void add (const entry &, bool mergeEntry=false)
Add an entry.
void add (const keyType &, const word &, bool overwrite=false)
Add a word entry.
void add (const keyType &, const string &, bool overwrite=false)
Add a string entry.
void add (const keyType &, const label, bool overwrite=false)
Add a label entry.
void add (const keyType &, const scalar, bool overwrite=false)
Add a scalar entry.
void add (const keyType &, const dictionary &, bool mergeEntry=false)
Add a dictionary entry.
template<class T >
void add (const keyType &, const T &, bool overwrite=false)
Add a T entry.
void set (entry *)
Assign a new entry, overwrite any existing entry.
void set (const entry &)
Assign a new entry, overwrite any existing entry.
void set (const keyType &, const dictionary &)
Assign a dictionary entry, overwrite any existing entry.
template<class T >
void set (const keyType &, const T &)
Assign a T entry, overwrite any existing entry.
bool remove (const word &)
Remove an entry specified by keyword.
bool changeKeyword (const keyType &oldKeyword, const keyType &newKeyword, bool forceOverwrite=false)
Change the keyword for an entry,.
bool merge (const dictionary &)
Merge entries from the given dictionary.
void clear ()
Clear the dictionary.
void transfer (dictionary &)
Transfer the contents of the argument and annul the argument.
Xfer< dictionary > xfer ()
Transfer contents to the Xfer container.
bool read (Istream &)
Read dictionary from Istream.
bool read (Istream &, const bool keepHeader)
Read dictionary from Istream, optionally keeping the header.
void write (Ostream &, const bool subDict=true) const
Write dictionary, normally with sub-dictionary formatting.
ITstream & operator[] (const word &) const
Find and return entry.
void operator= (const dictionary &)
void operator+= (const dictionary &)
Include entries from the given dictionary.
void operator|= (const dictionary &)
Conditionally include entries from the given dictionary.
void operator<<= (const dictionary &)
Unconditionally include entries from the given dictionary.
Public Member Functions inherited from dictionaryName
dictionaryName ()
Construct dictionaryName null.
dictionaryName (const fileName &name)
Construct dictionaryName as copy of the given fileName.
const fileName & name () const
Return the dictionary name.
fileName & name ()
Return the dictionary name.
const word dictName () const
Return the local dictionary name (final part of scoped name)
Public Member Functions inherited from ILList< LListBase, T >
ILList ()
Null construct.
ILList (T *a)
Construct given initial T.
ILList (Istream &)
Construct from Istream.
ILList (const ILList< LListBase, T > &)
Construct as copy.
template<class CloneArg >
ILList (const ILList< LListBase, T > &lst, const CloneArg &cloneArg)
Copy constructor with additional argument for clone.
template<class INew >
ILList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
~ILList ()
Destructor.
bool eraseHead ()
Remove the head element specified from the list and delete it.
bool erase (T *p)
Remove the specified element from the list and delete it.
void clear ()
Clear the contents of the list.
void transfer (ILList< LListBase, T > &)
Transfer the contents of the argument into this List.
void operator= (const ILList< LListBase, T > &)
Assignment operator.
Public Member Functions inherited from UILList< LListBase, T >
UILList ()
Null construct.
UILList (T *a)
Construct given initial T.
UILList (const UILList< LListBase, T > &)
Construct as copy.
T * first ()
Return the first entry.
const T * first () const
Return the first entry.
T * last ()
Return the last entry.
const T * last () const
Return the last entry.
T * removeHead ()
Remove and return head.
T * remove (T *p)
Remove and return element.
T * remove (iterator &it)
Remove and return specified by iterator.
void operator= (const UILList< LListBase, T > &)
iterator begin ()
const iterator & end ()
const_iterator cbegin () const
const const_iterator & cend () const
const_iterator begin () const
const const_iterator & end () const
const_reverse_iterator crbegin () const
const const_reverse_iterator & crend () const
const_reverse_iterator rbegin () const
const const_reverse_iterator & rend () const
bool operator== (const UILList< LListBase, T > &) const
Equality operation on ULists of the same type.
bool operator!= (const UILList< LListBase, T > &) const
The opposite of the equality operation. Takes linear time.
Static Public Attributes
static const word propertiesName
Default name of the turbulence properties dictionary.
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Static Public Attributes inherited from dictionary
static const dictionary null
Null dictionary.
Protected Attributes
const Time & runTime_
const fvMesh & mesh_
const volVectorField & U_
const surfaceScalarField & alphaRhoPhi_
const surfaceScalarField & phi_
nearWallDist y_
Near wall distance boundary field.
Additional Inherited Members
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Public Types inherited from UILList< LListBase, T >
typedef T value_type
Type of values the DLList contains.
typedef T & reference
Type that can be used for storing into DLList::value_type.
typedef const T & const_reference
Type that can be used for storing into constant.
typedef label size_type
The type that can represent the size of a DLList.
typedef LListBase::iterator LListBase_iterator
typedef LListBase::const_iterator LListBase_const_iterator
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Static Public Member Functions inherited from dictionary
static autoPtr< dictionary > New (Istream &)
Construct top-level dictionary on freestore from Istream.
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
Abstract base class for turbulence models (RAS, LES and laminar).
Source files
turbulenceModel.H
turbulenceModel.C
Definition at line 60 of file turbulenceModel.H.
Constructor & Destructor Documentation
turbulenceModel()
turbulenceModel (const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const word & propertiesName)
Construct from components.
Definition at line 44 of file turbulenceModel.C.
~turbulenceModel()
virtual ~turbulenceModel () inline virtual
Destructor.
Definition at line 113 of file turbulenceModel.H.
References turbulenceModel::read().
Member Function Documentation
TypeName()
TypeName ("turbulenceModel")
Runtime type information.
read()
bool read () pure virtual
Read model coefficients if they have changed.
Reimplemented from regIOobject.
Implemented in kineticTheoryModel, kineticTheoryModel, RASModel< EddyDiffusivity< ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > > > >, RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > >, phasePressureModel, phasePressureModel, EddyDiffusivity< ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > > >, EddyDiffusivity< phaseCompressibleTurbulenceModel >, eddyViscosity< RASModel< EddyDiffusivity< ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > > > > >, eddyViscosity< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >, linearViscousStress< RASModel< EddyDiffusivity< ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > > > > >, and linearViscousStress< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >.
Definition at line 81 of file turbulenceModel.C.
References regIOobject::read().
Referenced by turbulenceModel::~turbulenceModel().
time()
const Time& time () const inline
Definition at line 122 of file turbulenceModel.H.
References turbulenceModel::runTime_.
mesh()
const fvMesh& mesh () const inline
Definition at line 127 of file turbulenceModel.H.
References turbulenceModel::coeffDict(), and turbulenceModel::mesh_.
coeffDict()
virtual const dictionary& coeffDict () const pure virtual
Const access to the coefficients dictionary.
Implemented in RASModel< EddyDiffusivity< ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > > > >, and RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > >.
Referenced by turbulenceModel::mesh(), turbulentMixingLengthDissipationRateInletFvPatchScalarField::updateCoeffs(), and turbulentMixingLengthFrequencyInletFvPatchScalarField::updateCoeffs().
GName()
word GName () const inline
Helper function to return the name of the turbulence G field.
Definition at line 136 of file turbulenceModel.H.
References Foam::type().
Referenced by epsilonWallFunctionFvPatchScalarField::updateCoeffs(), omegaWallFunctionFvPatchScalarField::updateCoeffs(), epsilonWallFunctionFvPatchScalarField::updateWeightedCoeffs(), and omegaWallFunctionFvPatchScalarField::updateWeightedCoeffs().
U()
const volVectorField& U () const inline
Access function to velocity field.
Definition at line 142 of file turbulenceModel.H.
References turbulenceModel::U_.
Referenced by NicenoKEqn< BasicTurbulenceModel >::bubbleG(), LaheyKEpsilon< BasicTurbulenceModel >::bubbleG(), nutUWallFunctionFvPatchScalarField::calcNut(), nutUSpaldingWallFunctionFvPatchScalarField::calcNut(), nutUTabulatedWallFunctionFvPatchScalarField::calcNut(), epsilonWallFunctionFvPatchScalarField::calculate(), omegaWallFunctionFvPatchScalarField::calculate(), nutUSpaldingWallFunctionFvPatchScalarField::calcUTau(), SmagorinskyZhang< BasicTurbulenceModel >::correctNut(), NicenoKEqn< BasicTurbulenceModel >::correctNut(), LaheyKEpsilon< BasicTurbulenceModel >::correctNut(), kOmegaSSTSato< BasicTurbulenceModel >::correctNut(), phasePressureModel::nuEff(), kineticTheoryModel::nuEff(), nutLowReWallFunctionFvPatchScalarField::yPlus(), nutUWallFunctionFvPatchScalarField::yPlus(), nutUSpaldingWallFunctionFvPatchScalarField::yPlus(), nutUTabulatedWallFunctionFvPatchScalarField::yPlus(), nutURoughWallFunctionFvPatchScalarField::yPlus(), IncompressibleTurbulenceModel< TransportModel >::~IncompressibleTurbulenceModel(), and PhaseIncompressibleTurbulenceModel< TransportModel >::~PhaseIncompressibleTurbulenceModel().
alphaRhoPhi()
const surfaceScalarField& alphaRhoPhi () const inline
Access function to phase flux field.
Definition at line 148 of file turbulenceModel.H.
References turbulenceModel::alphaRhoPhi_, and turbulenceModel::phi().
Referenced by combustionModel::phi().
phi()
Foam::tmp< Foam::surfaceScalarField > phi () const virtual
Return the volumetric flux field.
Reimplemented in compressibleTurbulenceModel.
Definition at line 75 of file turbulenceModel.C.
Referenced by turbulenceModel::alphaRhoPhi().
y()
const nearWallDist& y () const inline
Return the near wall distances.
Definition at line 157 of file turbulenceModel.H.
References turbulenceModel::correct(), turbulenceModel::epsilon(), turbulenceModel::k(), turbulenceModel::mu(), turbulenceModel::muEff(), turbulenceModel::mut(), turbulenceModel::nu(), turbulenceModel::nuEff(), turbulenceModel::nut(), patchi, turbulenceModel::R(), turbulenceModel::validate(), and turbulenceModel::y_.
Referenced by nutkWallFunctionFvPatchScalarField::calcNut(), nutUTabulatedWallFunctionFvPatchScalarField::calcNut(), nutkRoughWallFunctionFvPatchScalarField::calcNut(), nutkAtmRoughWallFunctionFvPatchScalarField::calcNut(), epsilonWallFunctionFvPatchScalarField::calculate(), omegaWallFunctionFvPatchScalarField::calculate(), nutUSpaldingWallFunctionFvPatchScalarField::calcUTau(), nutUWallFunctionFvPatchScalarField::calcYPlus(), fWallFunctionFvPatchScalarField::updateCoeffs(), v2WallFunctionFvPatchScalarField::updateCoeffs(), kLowReWallFunctionFvPatchScalarField::updateCoeffs(), alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs(), nutkWallFunctionFvPatchScalarField::yPlus(), nutLowReWallFunctionFvPatchScalarField::yPlus(), nutUSpaldingWallFunctionFvPatchScalarField::yPlus(), and nutUTabulatedWallFunctionFvPatchScalarField::yPlus().
nu() [1/2]
virtual tmp<volScalarField> nu () const pure virtual
Return the laminar viscosity.
Implemented in TurbulenceModel< volScalarField, volScalarField, compressibleTurbulenceModel, TransportModel >, TurbulenceModel< geometricOneField, volScalarField, compressibleTurbulenceModel, TransportModel >, TurbulenceModel< geometricOneField, geometricOneField, incompressibleTurbulenceModel, TransportModel >, and TurbulenceModel< volScalarField, geometricOneField, incompressibleTurbulenceModel, TransportModel >.
Referenced by nutkWallFunctionFvPatchScalarField::calcNut(), nutUWallFunctionFvPatchScalarField::calcNut(), nutUSpaldingWallFunctionFvPatchScalarField::calcNut(), nutUTabulatedWallFunctionFvPatchScalarField::calcNut(), nutkRoughWallFunctionFvPatchScalarField::calcNut(), nutkAtmRoughWallFunctionFvPatchScalarField::calcNut(), epsilonWallFunctionFvPatchScalarField::calculate(), omegaWallFunctionFvPatchScalarField::calculate(), nutUSpaldingWallFunctionFvPatchScalarField::calcUTau(), nutUWallFunctionFvPatchScalarField::calcYPlus(), fWallFunctionFvPatchScalarField::updateCoeffs(), v2WallFunctionFvPatchScalarField::updateCoeffs(), kLowReWallFunctionFvPatchScalarField::updateCoeffs(), porousBafflePressureFvPatchField< Type >::updateCoeffs(), turbulenceModel::y(), nutLowReWallFunctionFvPatchScalarField::yPlus(), nutkWallFunctionFvPatchScalarField::yPlus(), nutUSpaldingWallFunctionFvPatchScalarField::yPlus(), and nutUTabulatedWallFunctionFvPatchScalarField::yPlus().
nu() [2/2]
virtual tmp<scalarField> nu (const label patchi) const pure virtual
Return the laminar viscosity on patch.
Implemented in TurbulenceModel< volScalarField, volScalarField, compressibleTurbulenceModel, TransportModel >, TurbulenceModel< geometricOneField, volScalarField, compressibleTurbulenceModel, TransportModel >, TurbulenceModel< geometricOneField, geometricOneField, incompressibleTurbulenceModel, TransportModel >, and TurbulenceModel< volScalarField, geometricOneField, incompressibleTurbulenceModel, TransportModel >.
nut() [1/2]
virtual tmp<volScalarField> nut () const pure virtual
Return the turbulence viscosity.
Implemented in eddyViscosity< RASModel< EddyDiffusivity< ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > > > > >, and eddyViscosity< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >.
Referenced by epsilonWallFunctionFvPatchScalarField::calculate(), omegaWallFunctionFvPatchScalarField::calculate(), continuousGasKEpsilon< BasicTurbulenceModel >::correctNut(), turbulenceFields::execute(), CompressibleTurbulenceModel< TransportModel >::mut(), PhaseCompressibleTurbulenceModel< Foam::phaseModel >::mut(), alphatWallFunctionFvPatchScalarField::updateCoeffs(), and turbulenceModel::y().
nut() [2/2]
virtual tmp<scalarField> nut (const label patchi) const pure virtual
Return the turbulence viscosity on patch.
Implemented in eddyViscosity< RASModel< EddyDiffusivity< ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > > > > >, and eddyViscosity< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >.
nuEff() [1/2]
virtual tmp<volScalarField> nuEff () const pure virtual
Return the effective viscosity.
Implemented in RASModel< EddyDiffusivity< ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > > > >, RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > >, kineticTheoryModel, kineticTheoryModel, phasePressureModel, and phasePressureModel.
Referenced by turbulenceFields::execute(), fixedShearStressFvPatchVectorField::updateCoeffs(), and turbulenceModel::y().
nuEff() [2/2]
virtual tmp<scalarField> nuEff (const label patchi) const pure virtual
Return the effective viscosity on patch.
Implemented in RASModel< EddyDiffusivity< ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > > > >, RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > >, kineticTheoryModel, kineticTheoryModel, phasePressureModel, and phasePressureModel.
mu() [1/2]
virtual tmp<volScalarField> mu () const pure virtual
Return the laminar dynamic viscosity.
Implemented in incompressibleTurbulenceModel, PhaseCompressibleTurbulenceModel< TransportModel >, and CompressibleTurbulenceModel< TransportModel >.
Referenced by turbulenceModel::y().
mu() [2/2]
virtual tmp<scalarField> mu (const label patchi) const pure virtual
Return the laminar dynamic viscosity on patch.
Implemented in PhaseCompressibleTurbulenceModel< TransportModel >, incompressibleTurbulenceModel, and CompressibleTurbulenceModel< TransportModel >.
mut() [1/2]
virtual tmp<volScalarField> mut () const pure virtual
Return the turbulence dynamic viscosity.
Implemented in PhaseCompressibleTurbulenceModel< TransportModel >, CompressibleTurbulenceModel< TransportModel >, and incompressibleTurbulenceModel.
Referenced by turbulenceModel::y().
mut() [2/2]
virtual tmp<scalarField> mut (const label patchi) const pure virtual
Return the turbulence dynamic viscosity on patch.
Implemented in PhaseCompressibleTurbulenceModel< TransportModel >, CompressibleTurbulenceModel< TransportModel >, and incompressibleTurbulenceModel.
muEff() [1/2]
virtual tmp<volScalarField> muEff () const pure virtual
Return the effective dynamic viscosity.
Implemented in PhaseCompressibleTurbulenceModel< TransportModel >, CompressibleTurbulenceModel< TransportModel >, and incompressibleTurbulenceModel.
Referenced by turbulenceModel::y().
muEff() [2/2]
virtual tmp<scalarField> muEff (const label patchi) const pure virtual
Return the effective dynamic viscosity on patch.
Implemented in PhaseCompressibleTurbulenceModel< TransportModel >, CompressibleTurbulenceModel< TransportModel >, and incompressibleTurbulenceModel.
k()
virtual tmp<volScalarField> k () const pure virtual
Return the turbulence kinetic energy.
Implemented in kineticTheoryModel, kineticTheoryModel, phasePressureModel, phasePressureModel, eddyViscosity< RASModel< EddyDiffusivity< ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > > > > >, and eddyViscosity< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >.
Referenced by nutkWallFunctionFvPatchScalarField::calcNut(), nutkRoughWallFunctionFvPatchScalarField::calcNut(), nutkAtmRoughWallFunctionFvPatchScalarField::calcNut(), epsilonWallFunctionFvPatchScalarField::calculate(), omegaWallFunctionFvPatchScalarField::calculate(), relaxation::correct(), continuousGasKEpsilon< BasicTurbulenceModel >::correctNut(), turbulenceFields::execute(), DispersionRASModel< CloudType >::kModel(), continuousGasKEqn< BasicTurbulenceModel >::kSource(), continuousGasKEpsilon< BasicTurbulenceModel >::kSource(), NicenoKEqn< BasicTurbulenceModel >::kSource(), LaheyKEpsilon< BasicTurbulenceModel >::kSource(), continuousGasKEqn< BasicTurbulenceModel >::phaseTransferCoeff(), continuousGasKEpsilon< BasicTurbulenceModel >::phaseTransferCoeff(), NicenoKEqn< BasicTurbulenceModel >::phaseTransferCoeff(), LaheyKEpsilon< BasicTurbulenceModel >::phaseTransferCoeff(), fWallFunctionFvPatchScalarField::updateCoeffs(), v2WallFunctionFvPatchScalarField::updateCoeffs(), kLowReWallFunctionFvPatchScalarField::updateCoeffs(), alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs(), turbulenceModel::y(), and nutkWallFunctionFvPatchScalarField::yPlus().
epsilon()
virtual tmp<volScalarField> epsilon () const pure virtual
Return the turbulence kinetic energy dissipation rate.
Implemented in kineticTheoryModel, kineticTheoryModel, phasePressureModel, and phasePressureModel.
Referenced by relaxation::correct(), continuousGasKEpsilon< BasicTurbulenceModel >::correctNut(), DispersionRASModel< CloudType >::epsilonModel(), continuousGasKEpsilon< BasicTurbulenceModel >::epsilonSource(), LaheyKEpsilon< BasicTurbulenceModel >::epsilonSource(), turbulenceFields::execute(), continuousGasKEpsilon< BasicTurbulenceModel >::phaseTransferCoeff(), LaheyKEpsilon< BasicTurbulenceModel >::phaseTransferCoeff(), fWallFunctionFvPatchScalarField::updateCoeffs(), and turbulenceModel::y().
R()
virtual tmp<volSymmTensorField> R () const pure virtual
Return the Reynolds stress tensor.
Implemented in kineticTheoryModel, kineticTheoryModel, phasePressureModel, phasePressureModel, eddyViscosity< RASModel< EddyDiffusivity< ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > > > > >, and eddyViscosity< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >.
Referenced by turbulenceFields::execute(), and turbulenceModel::y().
validate()
void validate () virtual
Validate the turbulence fields after construction.
Update derived fields as required
Reimplemented in eddyViscosity< RASModel< EddyDiffusivity< ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > > > > >, and eddyViscosity< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >.
Definition at line 87 of file turbulenceModel.C.
Referenced by turbulenceModel::y().
correct()
void correct () pure virtual
Solve the turbulence equations and correct the turbulence viscosity.
Implemented in RASModel< EddyDiffusivity< ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > > > >, RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > >, kineticTheoryModel, kineticTheoryModel, phasePressureModel, phasePressureModel, eddyViscosity< RASModel< EddyDiffusivity< ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > > > > >, eddyViscosity< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >, linearViscousStress< RASModel< EddyDiffusivity< ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > > > > >, and linearViscousStress< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >.
Definition at line 91 of file turbulenceModel.C.
Referenced by turbulenceModel::y().
Member Data Documentation
runTime_
const Time& runTime_ protected
Definition at line 69 of file turbulenceModel.H.
Referenced by turbulenceModel::time().
mesh_
const fvMesh& mesh_ protected
Definition at line 70 of file turbulenceModel.H.
Referenced by turbulenceModel::mesh().
U_
const volVectorField& U_ protected
Definition at line 72 of file turbulenceModel.H.
Referenced by turbulenceModel::U().
alphaRhoPhi_
const surfaceScalarField& alphaRhoPhi_ protected
Definition at line 73 of file turbulenceModel.H.
Referenced by turbulenceModel::alphaRhoPhi().
phi_
const surfaceScalarField& phi_ protected
Definition at line 74 of file turbulenceModel.H.
y_
nearWallDist y_ protected
Near wall distance boundary field.
Definition at line 77 of file turbulenceModel.H.
Referenced by turbulenceModel::y().
propertiesName
const Foam::word propertiesName static
Default name of the turbulence properties dictionary.
Definition at line 97 of file turbulenceModel.H.
Referenced by nutkWallFunctionFvPatchScalarField::calcNut(), nutUWallFunctionFvPatchScalarField::calcNut(), nutkFilmWallFunctionFvPatchScalarField::calcNut(), nutUSpaldingWallFunctionFvPatchScalarField::calcNut(), nutUTabulatedWallFunctionFvPatchScalarField::calcNut(), nutkRoughWallFunctionFvPatchScalarField::calcNut(), nutkAtmRoughWallFunctionFvPatchScalarField::calcNut(), variableHeatTransfer::calculateHtc(), nutkFilmWallFunctionFvPatchScalarField::calcUTau(), nutUSpaldingWallFunctionFvPatchScalarField::calcUTau(), nutUWallFunctionFvPatchScalarField::calcYPlus(), mixtureKEpsilon< BasicTurbulenceModel >::correctNut(), yPlus::execute(), wallHeatFlux::execute(), wallShearStress::execute(), temperatureCoupledBase::kappa(), continuousGasKEqn< BasicTurbulenceModel >::liquidTurbulence(), continuousGasKEpsilon< BasicTurbulenceModel >::liquidTurbulence(), NamedEnum< directionType, 3 >::names(), SmagorinskyZhang< BasicTurbulenceModel >::read(), NicenoKEqn< BasicTurbulenceModel >::read(), LaheyKEpsilon< BasicTurbulenceModel >::read(), kOmegaSSTSato< BasicTurbulenceModel >::read(), externalCoupledTemperatureMixedFvPatchScalarField::transferData(), fixedShearStressFvPatchVectorField::updateCoeffs(), totalFlowRateAdvectiveDiffusiveFvPatchScalarField::updateCoeffs(), alphatWallFunctionFvPatchScalarField::updateCoeffs(), fWallFunctionFvPatchScalarField::updateCoeffs(), v2WallFunctionFvPatchScalarField::updateCoeffs(), kLowReWallFunctionFvPatchScalarField::updateCoeffs(), wallHeatTransferFvPatchScalarField::updateCoeffs(), alphatFilmWallFunctionFvPatchScalarField::updateCoeffs(), turbulentMixingLengthDissipationRateInletFvPatchScalarField::updateCoeffs(), turbulentMixingLengthFrequencyInletFvPatchScalarField::updateCoeffs(), alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs(), thermalBaffle1DFvPatchScalarField< solidType >::updateCoeffs(), porousBafflePressureFvPatchField< Type >::updateCoeffs(), epsilonWallFunctionFvPatchScalarField::updateCoeffs(), omegaWallFunctionFvPatchScalarField::updateCoeffs(), epsilonWallFunctionFvPatchScalarField::updateWeightedCoeffs(), omegaWallFunctionFvPatchScalarField::updateWeightedCoeffs(), nutkWallFunctionFvPatchScalarField::yPlus(), nutLowReWallFunctionFvPatchScalarField::yPlus(), nutUWallFunctionFvPatchScalarField::yPlus(), nutkFilmWallFunctionFvPatchScalarField::yPlus(), nutUSpaldingWallFunctionFvPatchScalarField::yPlus(), nutUTabulatedWallFunctionFvPatchScalarField::yPlus(), nutURoughWallFunctionFvPatchScalarField::yPlus(), and FSD< CombThermoType, ThermoType >::~FSD().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/turbulenceModel.H
src/TurbulenceModels/turbulenceModels/turbulenceModel.C