OpenFOAM: linearViscousStress< BasicTurbulenceModel > Class Template Reference
linearViscousStress< BasicTurbulenceModel > Class Template Reference abstract
Turbulence
Linear viscous stress turbulence model base class.
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~linearViscousStress ()
Destructor.
virtual bool read ()=0
Re-read model coefficients if they have changed.
virtual tmp< volSymmTensorField > devRhoReff () const
Return the effective stress tensor.
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
Return the source term for the momentum equation.
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Return the source term for the momentum equation.
virtual void correct ()=0
Solve the turbulence equations and correct the turbulence viscosity.
Detailed Description
template<class BasicTurbulenceModel>
class Foam::linearViscousStress< BasicTurbulenceModel >
Linear viscous stress turbulence model base class.
Source files
linearViscousStress.H
linearViscousStress.C
Definition at line 50 of file linearViscousStress.H.
Member Typedef Documentation
alphaField
typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 57 of file linearViscousStress.H.
rhoField
typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 58 of file linearViscousStress.H.
transportModel
typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 59 of file linearViscousStress.H.
Constructor & Destructor Documentation
linearViscousStress()
linearViscousStress (const word & modelName, const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName)
Construct from components.
Definition at line 34 of file linearViscousStress.C.
~linearViscousStress()
virtual ~linearViscousStress () inline virtual
Destructor.
Definition at line 79 of file linearViscousStress.H.
Member Function Documentation
read()
bool read () pure virtual
Re-read model coefficients if they have changed.
Implemented in kOmegaSST< eddyViscosity< RASModel< BasicTurbulenceModel > >, BasicTurbulenceModel >, kOmegaSSTLM< BasicTurbulenceModel >, kkLOmega, mixtureKEpsilon< BasicTurbulenceModel >, v2f< BasicTurbulenceModel >, kOmegaSSTSato< BasicTurbulenceModel >, SpalartAllmarasDES< BasicTurbulenceModel >, SpalartAllmaras< BasicTurbulenceModel >, kineticTheoryModel, kineticTheoryModel, kOmegaSSTSAS< BasicTurbulenceModel >, dynamicKEqn< BasicTurbulenceModel >, LaunderSharmaKE< BasicTurbulenceModel >, realizableKE< BasicTurbulenceModel >, RNGkEpsilon< BasicTurbulenceModel >, LienCubicKE, LaheyKEpsilon< BasicTurbulenceModel >, kEpsilon< BasicTurbulenceModel >, kEpsilon< EddyDiffusivity< compressible::turbulenceModel > >, NicenoKEqn< BasicTurbulenceModel >, Smagorinsky< BasicTurbulenceModel >, SpalartAllmarasIDDES< BasicTurbulenceModel >, SmagorinskyZhang< BasicTurbulenceModel >, continuousGasKEpsilon< BasicTurbulenceModel >, LienLeschziner, WALE< BasicTurbulenceModel >, phasePressureModel, buoyantKEpsilon< BasicTurbulenceModel >, continuousGasKEqn< BasicTurbulenceModel >, qZeta, kEqn< BasicTurbulenceModel >, phasePressureModel, kOmega< BasicTurbulenceModel >, LamBremhorstKE, ShihQuadraticKE, dynamicLagrangian< BasicTurbulenceModel >, PDRkEpsilon, Stokes< BasicTurbulenceModel >, LESeddyViscosity< BasicTurbulenceModel >, eddyViscosity< BasicTurbulenceModel >, eddyViscosity< RASModel< EddyDiffusivity< ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > > > > >, eddyViscosity< incompressible::RASModel >, eddyViscosity< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >, eddyViscosity< LESModel< BasicTurbulenceModel > >, eddyViscosity< RASModel< EddyDiffusivity< compressible::turbulenceModel > > >, and eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 62 of file linearViscousStress.C.
Referenced by linearViscousStress< RASModel< BasicTurbulenceModel > >::~linearViscousStress().
devRhoReff()
Foam::tmp< Foam::volSymmTensorField > devRhoReff () const virtual
Return the effective stress tensor.
Reimplemented in kineticTheoryModel, kineticTheoryModel, phasePressureModel, phasePressureModel, nonlinearEddyViscosity< BasicTurbulenceModel >, and nonlinearEddyViscosity< incompressible::RASModel >.
Definition at line 70 of file linearViscousStress.C.
Referenced by linearViscousStress< RASModel< BasicTurbulenceModel > >::~linearViscousStress().
divDevRhoReff() [1/2]
Foam::tmp< Foam::fvVectorMatrix > divDevRhoReff (volVectorField & U) const virtual
Return the source term for the momentum equation.
Reimplemented in kineticTheoryModel, kineticTheoryModel, phasePressureModel, phasePressureModel, nonlinearEddyViscosity< BasicTurbulenceModel >, and nonlinearEddyViscosity< incompressible::RASModel >.
Definition at line 94 of file linearViscousStress.C.
Referenced by linearViscousStress< RASModel< BasicTurbulenceModel > >::devRhoReff(), linearViscousStress< RASModel< BasicTurbulenceModel > >::divDevRhoReff(), and linearViscousStress< RASModel< BasicTurbulenceModel > >::~linearViscousStress().
divDevRhoReff() [2/2]
Foam::tmp< Foam::fvVectorMatrix > divDevRhoReff (const volScalarField & rho, volVectorField & U) const virtual
Return the source term for the momentum equation.
Reimplemented in nonlinearEddyViscosity< BasicTurbulenceModel >, and nonlinearEddyViscosity< incompressible::RASModel >.
Definition at line 109 of file linearViscousStress.C.
correct()
void correct () pure virtual
Solve the turbulence equations and correct the turbulence viscosity.
Implemented in kOmegaSST< eddyViscosity< RASModel< BasicTurbulenceModel > >, BasicTurbulenceModel >, kkLOmega, kOmegaSSTLM< BasicTurbulenceModel >, v2f< BasicTurbulenceModel >, mixtureKEpsilon< BasicTurbulenceModel >, kineticTheoryModel, kineticTheoryModel, qZeta, SpalartAllmarasDES< BasicTurbulenceModel >, LaunderSharmaKE< BasicTurbulenceModel >, realizableKE< BasicTurbulenceModel >, RNGkEpsilon< BasicTurbulenceModel >, kEpsilon< BasicTurbulenceModel >, kOmega< BasicTurbulenceModel >, kEpsilon< EddyDiffusivity< compressible::turbulenceModel > >, kOmegaSSTSato< BasicTurbulenceModel >, SpalartAllmaras< BasicTurbulenceModel >, LienCubicKE, dynamicKEqn< BasicTurbulenceModel >, phasePressureModel, LienLeschziner, phasePressureModel, LamBremhorstKE, ShihQuadraticKE, Smagorinsky< BasicTurbulenceModel >, LaheyKEpsilon< BasicTurbulenceModel >, kEqn< BasicTurbulenceModel >, dynamicLagrangian< BasicTurbulenceModel >, WALE< BasicTurbulenceModel >, eddyViscosity< BasicTurbulenceModel >, Stokes< BasicTurbulenceModel >, eddyViscosity< RASModel< EddyDiffusivity< ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > > > > >, eddyViscosity< incompressible::RASModel >, eddyViscosity< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >, eddyViscosity< LESModel< BasicTurbulenceModel > >, eddyViscosity< RASModel< EddyDiffusivity< compressible::turbulenceModel > > >, eddyViscosity< RASModel< BasicTurbulenceModel > >, and PDRkEpsilon.
Definition at line 123 of file linearViscousStress.C.
Referenced by linearViscousStress< RASModel< BasicTurbulenceModel > >::~linearViscousStress().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/linearViscousStress/linearViscousStress.H
src/TurbulenceModels/turbulenceModels/linearViscousStress/linearViscousStress.C