OpenFOAM: SSG< BasicTurbulenceModel > Class Template Reference
SSG< BasicTurbulenceModel > Class Template Reference
Turbulence » RAS turbulence
Speziale, Sarkar and Gatski Reynolds-stress turbulence model for incompressible and compressible flows.
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from ReynoldsStress< RASModel< BasicTurbulenceModel > >
typedef RASModel< BasicTurbulenceModel > ::alphaField alphaField
typedef RASModel< BasicTurbulenceModel > ::rhoField rhoField
typedef RASModel< BasicTurbulenceModel > ::transportModel transportModel
Public Types inherited from RASModel< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("SSG")
Runtime type information.
SSG (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
Construct from components.
virtual ~SSG ()
Destructor.
virtual bool read ()
Read model coefficients if they have changed.
virtual tmp< volScalarField > k () const
Return the turbulence kinetic energy.
virtual tmp< volScalarField > epsilon () const
Return the turbulence kinetic energy dissipation rate.
tmp< volSymmTensorField > DREff () const
Return the effective diffusivity for R.
tmp< volSymmTensorField > DepsilonEff () const
Return the effective diffusivity for epsilon.
virtual void correct ()
Solve the turbulence equations and correct eddy-Viscosity and.
Public Member Functions inherited from ReynoldsStress< RASModel< BasicTurbulenceModel > >
ReynoldsStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~ReynoldsStress ()
Destructor.
virtual tmp< volScalarField > nut () const
Return the turbulence viscosity.
virtual tmp< scalarField > nut (const label patchi) const
Return the turbulence viscosity on patch.
virtual tmp< volSymmTensorField > R () const
Return the Reynolds stress tensor.
virtual tmp< volSymmTensorField > devRhoReff () const
Return the effective stress tensor.
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
Return the source term for the momentum equation.
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Return the source term for the momentum equation.
virtual void validate ()
Validate the turbulence fields after construction.
Public Member Functions inherited from RASModel< BasicTurbulenceModel >
TypeName ("RAS")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, RASModel, dictionary,(const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName),(alpha, rho, U, alphaRhoPhi, phi, transport, propertiesName))
RASModel (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~RASModel ()
Destructor.
const dimensionedScalar & kMin () const
Return the lower allowable limit for k (default: SMALL)
const dimensionedScalar & epsilonMin () const
Return the lower allowable limit for epsilon (default: SMALL)
const dimensionedScalar & omegaMin () const
Return the lower allowable limit for omega (default: SMALL)
dimensionedScalar & kMin ()
Allow kMin to be changed.
dimensionedScalar & epsilonMin ()
Allow epsilonMin to be changed.
dimensionedScalar & omegaMin ()
Allow omegaMin to be changed.
virtual const dictionary & coeffDict () const
Const access to the coefficients dictionary.
virtual tmp< volScalarField > nuEff () const
Return the effective viscosity.
virtual tmp< scalarField > nuEff (const label patchi) const
Return the effective viscosity on patch.
Protected Member Functions
virtual void correctNut ()
Update the eddy-viscosity.
Protected Member Functions inherited from ReynoldsStress< RASModel< BasicTurbulenceModel > >
void boundNormalStress (volSymmTensorField &R) const
void correctWallShearStress (volSymmTensorField &R) const
Protected Member Functions inherited from RASModel< BasicTurbulenceModel >
virtual void printCoeffs (const word &type)
Print model coefficients.
Protected Attributes
dimensionedScalar Cmu_
dimensionedScalar C1_
dimensionedScalar C1s_
dimensionedScalar C2_
dimensionedScalar C3_
dimensionedScalar C3s_
dimensionedScalar C4_
dimensionedScalar C5_
dimensionedScalar Ceps1_
dimensionedScalar Ceps2_
dimensionedScalar Cs_
dimensionedScalar Ceps_
volScalarField k_
volScalarField epsilon_
Protected Attributes inherited from ReynoldsStress< RASModel< BasicTurbulenceModel > >
dimensionedScalar couplingFactor_
volSymmTensorField R_
volScalarField nut_
Protected Attributes inherited from RASModel< BasicTurbulenceModel >
dictionary RASDict_
RAS coefficients dictionary.
Switch turbulence_
Turbulence on/off flag.
Switch printCoeffs_
Flag to print the model coeffs at run-time.
dictionary coeffDict_
Model coefficients dictionary.
dimensionedScalar kMin_
Lower limit of k.
dimensionedScalar epsilonMin_
Lower limit of epsilon.
dimensionedScalar omegaMin_
Lower limit for omega.
Additional Inherited Members
Static Public Member Functions inherited from RASModel< BasicTurbulenceModel >
static autoPtr< RASModel > New (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Return a reference to the selected RAS model.
Detailed Description
template<class BasicTurbulenceModel>
class Foam::RASModels::SSG< BasicTurbulenceModel >
Speziale, Sarkar and Gatski Reynolds-stress turbulence model for incompressible and compressible flows.
Reference:
    Speziale, C. G., Sarkar, S., & Gatski, T. B. (1991).
    Modelling the pressurestrain correlation of turbulence:
    an invariant dynamical systems approach.
    Journal of Fluid Mechanics, 227, 245-272.
Including the generalized gradient diffusion model of Daly and Harlow:
    Daly, B. J., & Harlow, F. H. (1970).
    Transport equations in turbulence.
    Physics of Fluids (1958-1988), 13(11), 2634-2649.
The default model coefficients are:
    SSGCoeffs
    {
        Cmu             0.09;
        C1              3.4;
        C1s             1.8;
        C2              4.2;
        C3              0.8;
        C3s             1.3;
        C4              1.25;
        C5              0.4;
        Ceps1           1.44;
        Ceps2           1.92;
        Cs              0.25;
        Ceps            0.15;
        couplingFactor  0.0;
    }
Source files
SSG.H
SSG.C
Definition at line 95 of file SSG.H.
Member Typedef Documentation
alphaField
typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 141 of file SSG.H.
rhoField
typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 142 of file SSG.H.
transportModel
typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 143 of file SSG.H.
Constructor & Destructor Documentation
SSG()
SSG (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Construct from components.
Definition at line 54 of file SSG.C.
References Foam::bound(), and Foam::tr().
~SSG()
virtual ~SSG () inline virtual
Destructor.
Definition at line 167 of file SSG.H.
References SSG< BasicTurbulenceModel >::read().
Member Function Documentation
correctNut()
void correctNut () protected virtual
Update the eddy-viscosity.
Implements ReynoldsStress< RASModel< BasicTurbulenceModel > >.
Definition at line 40 of file SSG.C.
References optionList::correct(), options::New(), and Foam::sqr().
TypeName()
TypeName ("SSG< BasicTurbulenceModel >")
Runtime type information.
read()
bool read () virtual
Read model coefficients if they have changed.
Implements ReynoldsStress< RASModel< BasicTurbulenceModel > >.
Definition at line 226 of file SSG.C.
References Foam::read().
Referenced by SSG< BasicTurbulenceModel >::~SSG().
k()
virtual tmp<volScalarField> k () const inline virtual
Return the turbulence kinetic energy.
Reimplemented from ReynoldsStress< RASModel< BasicTurbulenceModel > >.
Definition at line 177 of file SSG.H.
References SSG< BasicTurbulenceModel >::k_.
epsilon()
virtual tmp<volScalarField> epsilon () const inline virtual
Return the turbulence kinetic energy dissipation rate.
Definition at line 183 of file SSG.H.
References SSG< BasicTurbulenceModel >::correct(), SSG< BasicTurbulenceModel >::DepsilonEff(), SSG< BasicTurbulenceModel >::DREff(), and SSG< BasicTurbulenceModel >::epsilon_.
DREff()
tmp< volSymmTensorField > DREff () const
Return the effective diffusivity for R.
Definition at line 254 of file SSG.C.
References Foam::I, and nu.
Referenced by SSG< BasicTurbulenceModel >::epsilon().
DepsilonEff()
tmp< volSymmTensorField > DepsilonEff () const
Return the effective diffusivity for epsilon.
Definition at line 268 of file SSG.C.
References Foam::I, and nu.
Referenced by SSG< BasicTurbulenceModel >::epsilon().
correct()
void correct () virtual
Solve the turbulence equations and correct eddy-Viscosity and.
related properties
Implements ReynoldsStress< RASModel< BasicTurbulenceModel > >.
Definition at line 282 of file SSG.C.
References Foam::constant::physicoChemical::b, Foam::bound(), optionList::constrain(), correct, optionList::correct(), Foam::fvm::ddt(), Foam::dev(), Foam::fvm::div(), fvPatch::faceCells(), forAll, fvOptions, Foam::constant::universal::G, Foam::fvc::grad(), Foam::I, Foam::innerSqr(), Foam::fvm::laplacian(), Foam::mag(), Foam::min(), options::New(), patches, patchi, R, tmp< T >::ref(), Foam::skew(), Foam::solve(), Foam::fvm::Sp(), Foam::symm(), Foam::tr(), and Foam::twoSymm().
Referenced by SSG< BasicTurbulenceModel >::epsilon().
Member Data Documentation
Cmu_
dimensionedScalar Cmu_ protected
Definition at line 112 of file SSG.H.
C1_
dimensionedScalar C1_ protected
Definition at line 114 of file SSG.H.
C1s_
dimensionedScalar C1s_ protected
Definition at line 115 of file SSG.H.
C2_
dimensionedScalar C2_ protected
Definition at line 116 of file SSG.H.
C3_
dimensionedScalar C3_ protected
Definition at line 117 of file SSG.H.
C3s_
dimensionedScalar C3s_ protected
Definition at line 118 of file SSG.H.
C4_
dimensionedScalar C4_ protected
Definition at line 119 of file SSG.H.
C5_
dimensionedScalar C5_ protected
Definition at line 120 of file SSG.H.
Ceps1_
dimensionedScalar Ceps1_ protected
Definition at line 122 of file SSG.H.
Ceps2_
dimensionedScalar Ceps2_ protected
Definition at line 123 of file SSG.H.
Cs_
dimensionedScalar Cs_ protected
Definition at line 124 of file SSG.H.
Ceps_
dimensionedScalar Ceps_ protected
Definition at line 125 of file SSG.H.
k_
volScalarField k_ protected
Definition at line 129 of file SSG.H.
Referenced by SSG< BasicTurbulenceModel >::k().
epsilon_
volScalarField epsilon_ protected
Definition at line 130 of file SSG.H.
Referenced by SSG< BasicTurbulenceModel >::epsilon().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/RAS/SSG/SSG.H
src/TurbulenceModels/turbulenceModels/RAS/SSG/SSG.C