OpenFOAM: v2f< BasicTurbulenceModel > Class Template Reference
v2f< BasicTurbulenceModel > Class Template Reference
Turbulence » RAS turbulence
Lien and Kalitzin's v2-f turbulence model for incompressible and compressible flows, with a limit imposed on the turbulent viscosity given by Davidson et al.
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
typedef RASModel< BasicTurbulenceModel > ::alphaField alphaField
typedef RASModel< BasicTurbulenceModel > ::rhoField rhoField
typedef RASModel< BasicTurbulenceModel > ::transportModel transportModel
Public Types inherited from linearViscousStress< RASModel< BasicTurbulenceModel > >
typedef RASModel< BasicTurbulenceModel > ::alphaField alphaField
typedef RASModel< BasicTurbulenceModel > ::rhoField rhoField
typedef RASModel< BasicTurbulenceModel > ::transportModel transportModel
Public Types inherited from RASModel< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("v2f")
Runtime type information.
v2f (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
Construct from components.
virtual ~v2f ()
Destructor.
virtual bool read ()
Read RASProperties dictionary.
tmp< volScalarField > DkEff () const
Return the effective diffusivity for k.
tmp< volScalarField > DepsilonEff () const
Return the effective diffusivity for epsilon.
virtual tmp< volScalarField > k () const
Return the turbulence kinetic energy.
virtual tmp< volScalarField > epsilon () const
Return the turbulence kinetic energy dissipation rate.
virtual tmp< volScalarField > v2 () const
Return turbulence stress normal to streamlines.
virtual tmp< volScalarField > f () const
Return the damping function.
virtual void correct ()
Solve the turbulence equations and correct the turbulence viscosity.
Public Member Functions inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~eddyViscosity ()
Destructor.
volScalarField & evNut ()
Return non-const access to the turbulence viscosity.
virtual tmp< volScalarField > nut () const
Return the turbulence viscosity.
virtual tmp< scalarField > nut (const label patchi) const
Return the turbulence viscosity on patch.
virtual tmp< volSymmTensorField > R () const
Return the Reynolds stress tensor.
virtual void validate ()
Validate the turbulence fields after construction.
Public Member Functions inherited from linearViscousStress< RASModel< BasicTurbulenceModel > >
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~linearViscousStress ()
Destructor.
virtual tmp< volSymmTensorField > devRhoReff () const
Return the effective stress tensor.
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
Return the source term for the momentum equation.
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Return the source term for the momentum equation.
Public Member Functions inherited from RASModel< BasicTurbulenceModel >
TypeName ("RAS")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, RASModel, dictionary,(const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName),(alpha, rho, U, alphaRhoPhi, phi, transport, propertiesName))
RASModel (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~RASModel ()
Destructor.
const dimensionedScalar & kMin () const
Return the lower allowable limit for k (default: SMALL)
const dimensionedScalar & epsilonMin () const
Return the lower allowable limit for epsilon (default: SMALL)
const dimensionedScalar & omegaMin () const
Return the lower allowable limit for omega (default: SMALL)
dimensionedScalar & kMin ()
Allow kMin to be changed.
dimensionedScalar & epsilonMin ()
Allow epsilonMin to be changed.
dimensionedScalar & omegaMin ()
Allow omegaMin to be changed.
virtual const dictionary & coeffDict () const
Const access to the coefficients dictionary.
virtual tmp< volScalarField > nuEff () const
Return the effective viscosity.
virtual tmp< scalarField > nuEff (const label patchi) const
Return the effective viscosity on patch.
Public Member Functions inherited from v2fBase
TypeName ("v2fBase")
Runtime type information.
v2fBase ()
virtual ~v2fBase ()
Destructor.
Protected Member Functions
virtual void correctNut ()
tmp< volScalarField > Ts () const
Return time scale, Ts.
tmp< volScalarField > Ls () const
Return length scale, Ls.
Protected Member Functions inherited from RASModel< BasicTurbulenceModel >
virtual void printCoeffs (const word &type)
Print model coefficients.
Protected Attributes
dimensionedScalar Cmu_
dimensionedScalar CmuKEps_
dimensionedScalar C1_
dimensionedScalar C2_
dimensionedScalar CL_
dimensionedScalar Ceta_
dimensionedScalar Ceps2_
dimensionedScalar Ceps3_
dimensionedScalar sigmaK_
dimensionedScalar sigmaEps_
volScalarField k_
Turbulence kinetic energy.
volScalarField epsilon_
Turbulence dissipation.
volScalarField v2_
Turbulence stress normal to streamlines.
volScalarField f_
Damping function.
dimensionedScalar v2Min_
dimensionedScalar fMin_
Protected Attributes inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
volScalarField nut_
Protected Attributes inherited from RASModel< BasicTurbulenceModel >
dictionary RASDict_
RAS coefficients dictionary.
Switch turbulence_
Turbulence on/off flag.
Switch printCoeffs_
Flag to print the model coeffs at run-time.
dictionary coeffDict_
Model coefficients dictionary.
dimensionedScalar kMin_
Lower limit of k.
dimensionedScalar epsilonMin_
Lower limit of epsilon.
dimensionedScalar omegaMin_
Lower limit for omega.
Additional Inherited Members
Static Public Member Functions inherited from RASModel< BasicTurbulenceModel >
static autoPtr< RASModel > New (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Return a reference to the selected RAS model.
Detailed Description
template<class BasicTurbulenceModel>
class Foam::RASModels::v2f< BasicTurbulenceModel >
Lien and Kalitzin's v2-f turbulence model for incompressible and compressible flows, with a limit imposed on the turbulent viscosity given by Davidson et al.
The model solves for turbulence kinetic energy k and turbulence dissipation rate epsilon, with additional equations for the turbulence stress normal to streamlines, v2, and elliptic damping function, f.
The variant implemented employs N=6, such that f=0 on walls.
Wall boundary conditions are:
k = kLowReWallFunction epsilon = epsilonWallFunction v2 = v2WallFunction f = fWallFunction
These are applicable to both low- and high-Reynolds number flows.
Inlet values can be approximated by:
v2 = 2/3 k f = zero-gradient
References:
    Lien, F. S., & Kalitzin, G. (2001).
    Computations of transonic flow with the v2f turbulence model.
    International Journal of Heat and Fluid Flow, 22(1), 53-61.
    Davidson, L., Nielsen, P., & Sveningsson, A. (2003).
    Modifications of the v2-f model for computing the flow in a
    3D wall jet.
    Turbulence, Heat and Mass Transfer, 4, 577-584
The default model coefficients are
    v2fCoeffs
    {
        Cmu         0.22;
        CmuKEps     0.09;
        C1          1.4;
        C2          0.3;
        CL          0.23;
        Ceta        70;
        Ceps2       1.9;
        Ceps3       -0.33;
        sigmaEps    1.3;
        sigmaK      1;
    }
Note
If the kLowReWallFunction is employed, a velocity variant of the turbulent viscosity wall function should be used, e.g. nutUWallFunction. Turbulence k variants (nutk...) for this case will not behave correctly.
See also
Foam::RASModels::v2fBase Foam::RASModels::kEpsilon Foam::kLowReWallFunctionFvPatchScalarField Foam::epsilonWallFunctionFvPatchScalarField Foam::v2WallFunctionFvPatchScalarField Foam::fWallFunctionFvPatchScalarField
Source files
v2f.H
v2f.C
Definition at line 120 of file v2f.H.
Member Typedef Documentation
alphaField
typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 178 of file v2f.H.
rhoField
typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 179 of file v2f.H.
transportModel
typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 180 of file v2f.H.
Constructor & Destructor Documentation
v2f()
v2f (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Construct from components.
Definition at line 70 of file v2f.C.
References Foam::bound().
Referenced by v2f< BasicTurbulenceModel >::correctNut().
~v2f()
virtual ~v2f () inline virtual
Destructor.
Definition at line 204 of file v2f.H.
References v2f< BasicTurbulenceModel >::read().
Member Function Documentation
correctNut()
void correctNut () protected virtual
Implements eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 56 of file v2f.C.
References optionList::correct(), Foam::min(), options::New(), Foam::sqr(), and v2f< BasicTurbulenceModel >::v2f().
Ts()
tmp< volScalarField > Ts () const protected
Return time scale, Ts.
Definition at line 40 of file v2f.C.
References Foam::max(), nu, and Foam::sqrt().
Ls()
tmp< volScalarField > Ls () const protected
Return length scale, Ls.
Definition at line 47 of file v2f.C.
References Foam::max(), nu, Foam::pow(), Foam::pow025(), and Foam::pow3().
TypeName()
TypeName ("v2f< BasicTurbulenceModel >")
Runtime type information.
read()
bool read () virtual
Read RASProperties dictionary.
Implements eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 251 of file v2f.C.
References Foam::read().
Referenced by v2f< BasicTurbulenceModel >::~v2f().
DkEff()
tmp<volScalarField> DkEff () const inline
Return the effective diffusivity for k.
Definition at line 214 of file v2f.H.
References nu, and eddyViscosity< RASModel< BasicTurbulenceModel > >::nut_.
DepsilonEff()
tmp<volScalarField> DepsilonEff () const inline
Return the effective diffusivity for epsilon.
Definition at line 227 of file v2f.H.
References nu, and eddyViscosity< RASModel< BasicTurbulenceModel > >::nut_.
k()
virtual tmp<volScalarField> k () const inline virtual
Return the turbulence kinetic energy.
Implements eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 240 of file v2f.H.
References v2f< BasicTurbulenceModel >::k_.
epsilon()
virtual tmp<volScalarField> epsilon () const inline virtual
Return the turbulence kinetic energy dissipation rate.
Definition at line 246 of file v2f.H.
References v2f< BasicTurbulenceModel >::epsilon_.
v2()
virtual tmp<volScalarField> v2 () const inline virtual
Return turbulence stress normal to streamlines.
Implements v2fBase.
Definition at line 252 of file v2f.H.
References v2f< BasicTurbulenceModel >::v2_.
f()
virtual tmp<volScalarField> f () const inline virtual
Return the damping function.
Implements v2fBase.
Definition at line 258 of file v2f.H.
References v2f< BasicTurbulenceModel >::correct(), and v2f< BasicTurbulenceModel >::f_.
correct()
void correct () virtual
Solve the turbulence equations and correct the turbulence viscosity.
Implements eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 276 of file v2f.C.
References Foam::fvc::absolute(), Foam::bound(), optionList::constrain(), correct, optionList::correct(), Foam::fvm::ddt(), Foam::dev(), Foam::dimless, Foam::fvm::div(), Foam::fvc::div(), divU(), fvOptions, Foam::constant::universal::G, Foam::fvc::grad(), Foam::fvm::laplacian(), Foam::magSqr(), Foam::min(), N, options::New(), nut, phi, tmp< T >::ref(), Foam::solve(), Foam::fvm::Sp(), Foam::sqr(), Foam::sqrt(), Foam::fvm::SuSp(), Foam::symm(), and Foam::type().
Referenced by v2f< BasicTurbulenceModel >::f().
Member Data Documentation
Cmu_
dimensionedScalar Cmu_ protected
Definition at line 132 of file v2f.H.
CmuKEps_
dimensionedScalar CmuKEps_ protected
Definition at line 133 of file v2f.H.
C1_
dimensionedScalar C1_ protected
Definition at line 134 of file v2f.H.
C2_
dimensionedScalar C2_ protected
Definition at line 135 of file v2f.H.
CL_
dimensionedScalar CL_ protected
Definition at line 136 of file v2f.H.
Ceta_
dimensionedScalar Ceta_ protected
Definition at line 137 of file v2f.H.
Ceps2_
dimensionedScalar Ceps2_ protected
Definition at line 138 of file v2f.H.
Ceps3_
dimensionedScalar Ceps3_ protected
Definition at line 139 of file v2f.H.
sigmaK_
dimensionedScalar sigmaK_ protected
Definition at line 140 of file v2f.H.
sigmaEps_
dimensionedScalar sigmaEps_ protected
Definition at line 141 of file v2f.H.
k_
volScalarField k_ protected
Turbulence kinetic energy.
Definition at line 147 of file v2f.H.
Referenced by v2f< BasicTurbulenceModel >::k().
epsilon_
volScalarField epsilon_ protected
Turbulence dissipation.
Definition at line 150 of file v2f.H.
Referenced by v2f< BasicTurbulenceModel >::epsilon().
v2_
volScalarField v2_ protected
Turbulence stress normal to streamlines.
Definition at line 153 of file v2f.H.
Referenced by v2f< BasicTurbulenceModel >::v2().
f_
volScalarField f_ protected
Damping function.
Definition at line 156 of file v2f.H.
Referenced by v2f< BasicTurbulenceModel >::f().
v2Min_
dimensionedScalar v2Min_ protected
Definition at line 161 of file v2f.H.
fMin_
dimensionedScalar fMin_ protected
Definition at line 162 of file v2f.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/RAS/v2f/v2f.H
src/TurbulenceModels/turbulenceModels/RAS/v2f/v2f.C