OpenFOAM: SpalartAllmaras< BasicTurbulenceModel > Class Template Reference
SpalartAllmaras< BasicTurbulenceModel > Class Template Reference
Turbulence » RAS turbulence
Spalart-Allmaras one-eqn mixing-length model for incompressible and compressible external flows.
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Types inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
typedef RASModel< BasicTurbulenceModel > ::alphaField alphaField
typedef RASModel< BasicTurbulenceModel > ::rhoField rhoField
typedef RASModel< BasicTurbulenceModel > ::transportModel transportModel
Public Types inherited from linearViscousStress< RASModel< BasicTurbulenceModel > >
typedef RASModel< BasicTurbulenceModel > ::alphaField alphaField
typedef RASModel< BasicTurbulenceModel > ::rhoField rhoField
typedef RASModel< BasicTurbulenceModel > ::transportModel transportModel
Public Types inherited from RASModel< BasicTurbulenceModel >
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("SpalartAllmaras")
Runtime type information.
SpalartAllmaras (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
Construct from components.
virtual ~SpalartAllmaras ()
Destructor.
virtual bool read ()
Read RASProperties dictionary.
tmp< volScalarField > DnuTildaEff () const
Return the effective diffusivity for nuTilda.
virtual tmp< volScalarField > k () const
Return the turbulence kinetic energy.
virtual tmp< volScalarField > epsilon () const
Return the turbulence kinetic energy dissipation rate.
virtual void correct ()
Solve the turbulence equations and correct the turbulence viscosity.
Public Member Functions inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~eddyViscosity ()
Destructor.
volScalarField & evNut ()
Return non-const access to the turbulence viscosity.
virtual tmp< volScalarField > nut () const
Return the turbulence viscosity.
virtual tmp< scalarField > nut (const label patchi) const
Return the turbulence viscosity on patch.
virtual tmp< volSymmTensorField > R () const
Return the Reynolds stress tensor.
virtual void validate ()
Validate the turbulence fields after construction.
Public Member Functions inherited from linearViscousStress< RASModel< BasicTurbulenceModel > >
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~linearViscousStress ()
Destructor.
virtual tmp< volSymmTensorField > devRhoReff () const
Return the effective stress tensor.
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
Return the source term for the momentum equation.
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Return the source term for the momentum equation.
Public Member Functions inherited from RASModel< BasicTurbulenceModel >
TypeName ("RAS")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, RASModel, dictionary,(const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName),(alpha, rho, U, alphaRhoPhi, phi, transport, propertiesName))
RASModel (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~RASModel ()
Destructor.
const dimensionedScalar & kMin () const
Return the lower allowable limit for k (default: SMALL)
const dimensionedScalar & epsilonMin () const
Return the lower allowable limit for epsilon (default: SMALL)
const dimensionedScalar & omegaMin () const
Return the lower allowable limit for omega (default: SMALL)
dimensionedScalar & kMin ()
Allow kMin to be changed.
dimensionedScalar & epsilonMin ()
Allow epsilonMin to be changed.
dimensionedScalar & omegaMin ()
Allow omegaMin to be changed.
virtual const dictionary & coeffDict () const
Const access to the coefficients dictionary.
virtual tmp< volScalarField > nuEff () const
Return the effective viscosity.
virtual tmp< scalarField > nuEff (const label patchi) const
Return the effective viscosity on patch.
Protected Member Functions
tmp< volScalarField > chi () const
tmp< volScalarField > fv1 (const volScalarField &chi) const
tmp< volScalarField > fv2 (const volScalarField &chi, const volScalarField &fv1) const
tmp< volScalarField > Stilda (const volScalarField &chi, const volScalarField &fv1) const
tmp< volScalarField > fw (const volScalarField &Stilda) const
void correctNut (const volScalarField &fv1)
virtual void correctNut ()
Protected Member Functions inherited from RASModel< BasicTurbulenceModel >
virtual void printCoeffs (const word &type)
Print model coefficients.
Protected Attributes
dimensionedScalar sigmaNut_
dimensionedScalar kappa_
dimensionedScalar Cb1_
dimensionedScalar Cb2_
dimensionedScalar Cw1_
dimensionedScalar Cw2_
dimensionedScalar Cw3_
dimensionedScalar Cv1_
dimensionedScalar Cs_
volScalarField nuTilda_
const volScalarField & y_
Wall distance.
Protected Attributes inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
volScalarField nut_
Protected Attributes inherited from RASModel< BasicTurbulenceModel >
dictionary RASDict_
RAS coefficients dictionary.
Switch turbulence_
Turbulence on/off flag.
Switch printCoeffs_
Flag to print the model coeffs at run-time.
dictionary coeffDict_
Model coefficients dictionary.
dimensionedScalar kMin_
Lower limit of k.
dimensionedScalar epsilonMin_
Lower limit of epsilon.
dimensionedScalar omegaMin_
Lower limit for omega.
Additional Inherited Members
Static Public Member Functions inherited from RASModel< BasicTurbulenceModel >
static autoPtr< RASModel > New (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Return a reference to the selected RAS model.
Detailed Description
template<class BasicTurbulenceModel>
class Foam::RASModels::SpalartAllmaras< BasicTurbulenceModel >
Spalart-Allmaras one-eqn mixing-length model for incompressible and compressible external flows.
Reference:
    Spalart, P.R., & Allmaras, S.R. (1994).
    A one-equation turbulence model for aerodynamic flows.
    La Recherche Aerospatiale, 1, 5-21.
The model is implemented without the trip-term and hence the ft2 term is not needed.
It is necessary to limit the Stilda generation term as the model generates unphysical results if this term becomes negative which occurs for complex flow. Several approaches have been proposed to limit Stilda but it is not clear which is the most appropriate. Here the limiter proposed by Spalart is implemented in which Stilda is clipped at Cs*Omega with the default value of Cs = 0.3.
The default model coefficients are
    SpalartAllmarasCoeffs
    {
        Cb1         0.1355;
        Cb2         0.622;
        Cw2         0.3;
        Cw3         2.0;
        Cv1         7.1;
        Cs          0.3;
        sigmaNut    0.66666;
        kappa       0.41;
    }
Source files
SpalartAllmaras.H
SpalartAllmaras.C
Definition at line 88 of file SpalartAllmaras.H.
Member Typedef Documentation
alphaField
typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 153 of file SpalartAllmaras.H.
rhoField
typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 154 of file SpalartAllmaras.H.
transportModel
typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 155 of file SpalartAllmaras.H.
Constructor & Destructor Documentation
SpalartAllmaras()
SpalartAllmaras (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Construct from components.
Definition at line 145 of file SpalartAllmaras.C.
~SpalartAllmaras()
virtual ~SpalartAllmaras () inline virtual
Destructor.
Definition at line 179 of file SpalartAllmaras.H.
References SpalartAllmaras< BasicTurbulenceModel >::correct(), SpalartAllmaras< BasicTurbulenceModel >::DnuTildaEff(), SpalartAllmaras< BasicTurbulenceModel >::epsilon(), SpalartAllmaras< BasicTurbulenceModel >::k(), and SpalartAllmaras< BasicTurbulenceModel >::read().
Member Function Documentation
chi()
tmp< volScalarField > chi () const protected
Definition at line 41 of file SpalartAllmaras.C.
References SpalartAllmaras< BasicTurbulenceModel >::fv1(), and nu.
fv1()
tmp< volScalarField > fv1 (const volScalarField & chi) const protected
Definition at line 49 of file SpalartAllmaras.C.
References SpalartAllmaras< BasicTurbulenceModel >::fv2(), and Foam::pow3().
Referenced by SpalartAllmaras< BasicTurbulenceModel >::chi().
fv2()
tmp< volScalarField > fv2 (const volScalarField & chi, const volScalarField & fv1) const protected
Definition at line 60 of file SpalartAllmaras.C.
References SpalartAllmaras< BasicTurbulenceModel >::Stilda().
Referenced by SpalartAllmaras< BasicTurbulenceModel >::fv1().
Stilda()
tmp< volScalarField > Stilda (const volScalarField & chi, const volScalarField & fv1) const protected
Definition at line 71 of file SpalartAllmaras.C.
References SpalartAllmaras< BasicTurbulenceModel >::fw(), Foam::fvc::grad(), Foam::mag(), Foam::max(), Foam::skew(), Foam::sqr(), and Foam::sqrt().
Referenced by SpalartAllmaras< BasicTurbulenceModel >::fv2().
fw()
tmp< volScalarField > fw (const volScalarField & Stilda) const protected
Definition at line 92 of file SpalartAllmaras.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), SpalartAllmaras< BasicTurbulenceModel >::correctNut(), DimensionedField< Type, GeoMesh >::dimensions(), g, Foam::max(), Foam::min(), Foam::pow(), Foam::pow6(), and Foam::sqr().
Referenced by SpalartAllmaras< BasicTurbulenceModel >::Stilda().
correctNut() [1/2]
void correctNut (const volScalarField & fv1) protected
Definition at line 122 of file SpalartAllmaras.C.
References optionList::correct(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), and options::New().
correctNut() [2/2]
void correctNut () protected virtual
Implements eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 135 of file SpalartAllmaras.C.
Referenced by SpalartAllmaras< BasicTurbulenceModel >::fw().
TypeName()
TypeName ("SpalartAllmaras< BasicTurbulenceModel >")
Runtime type information.
read()
bool read () virtual
Read RASProperties dictionary.
Implements eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 268 of file SpalartAllmaras.C.
References Foam::read(), dimensioned< Type >::readIfPresent(), and Foam::sqr().
Referenced by SpalartAllmaras< BasicTurbulenceModel >::~SpalartAllmaras().
DnuTildaEff()
tmp< volScalarField > DnuTildaEff () const
Return the effective diffusivity for nuTilda.
Definition at line 293 of file SpalartAllmaras.C.
References nu.
Referenced by SpalartAllmaras< BasicTurbulenceModel >::~SpalartAllmaras().
k()
tmp< volScalarField > k () const virtual
Return the turbulence kinetic energy.
Implements eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 303 of file SpalartAllmaras.C.
Referenced by SpalartAllmaras< BasicTurbulenceModel >::~SpalartAllmaras().
epsilon()
tmp< volScalarField > epsilon () const virtual
Return the turbulence kinetic energy dissipation rate.
Definition at line 323 of file SpalartAllmaras.C.
References Foam::endl(), and WarningInFunction.
Referenced by SpalartAllmaras< BasicTurbulenceModel >::~SpalartAllmaras().
correct()
void correct () virtual
Solve the turbulence equations and correct the turbulence viscosity.
Implements eddyViscosity< RASModel< BasicTurbulenceModel > >.
Definition at line 348 of file SpalartAllmaras.C.
References Foam::bound(), optionList::constrain(), correct, optionList::correct(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), Foam::fvm::ddt(), Foam::fvm::div(), fvOptions, Foam::fvc::grad(), Foam::fvm::laplacian(), Foam::magSqr(), options::New(), tmp< T >::ref(), Foam::solve(), Foam::fvm::Sp(), and Foam::sqr().
Referenced by SpalartAllmaras< BasicTurbulenceModel >::~SpalartAllmaras().
Member Data Documentation
sigmaNut_
dimensionedScalar sigmaNut_ protected
Definition at line 105 of file SpalartAllmaras.H.
kappa_
dimensionedScalar kappa_ protected
Definition at line 106 of file SpalartAllmaras.H.
Cb1_
dimensionedScalar Cb1_ protected
Definition at line 108 of file SpalartAllmaras.H.
Cb2_
dimensionedScalar Cb2_ protected
Definition at line 109 of file SpalartAllmaras.H.
Cw1_
dimensionedScalar Cw1_ protected
Definition at line 110 of file SpalartAllmaras.H.
Cw2_
dimensionedScalar Cw2_ protected
Definition at line 111 of file SpalartAllmaras.H.
Cw3_
dimensionedScalar Cw3_ protected
Definition at line 112 of file SpalartAllmaras.H.
Cv1_
dimensionedScalar Cv1_ protected
Definition at line 113 of file SpalartAllmaras.H.
Cs_
dimensionedScalar Cs_ protected
Definition at line 114 of file SpalartAllmaras.H.
nuTilda_
volScalarField nuTilda_ protected
Definition at line 119 of file SpalartAllmaras.H.
y_
const volScalarField& y_ protected
Wall distance.
Note: different to wall distance in parent RASModel which is for near-wall cells only
Definition at line 124 of file SpalartAllmaras.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/RAS/SpalartAllmaras/SpalartAllmaras.H
src/TurbulenceModels/turbulenceModels/RAS/SpalartAllmaras/SpalartAllmaras.C