OpenFOAM: atmBoundaryLayerInletVelocityFvPatchVectorField Class Reference
atmBoundaryLayerInletVelocityFvPatchVectorField Class Reference
Turbulence » RAS turbulence » RAS boundary conditionsBoundary Conditions » | Inlet boundary Conditions
This boundary condition specifies a velocity inlet profile appropriate for atmospheric boundary layers (ABL).
Public Member Functions
TypeName ("atmBoundaryLayerInletVelocity")
Runtime type information.
atmBoundaryLayerInletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
atmBoundaryLayerInletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
atmBoundaryLayerInletVelocityFvPatchVectorField (const atmBoundaryLayerInletVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
virtual tmp< fvPatchVectorField > clone () const
Construct and return a clone.
atmBoundaryLayerInletVelocityFvPatchVectorField (const atmBoundaryLayerInletVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchVectorField &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from atmBoundaryLayer
atmBoundaryLayer ()
Construct null.
atmBoundaryLayer (const vectorField &p, const dictionary &)
Construct from the coordinates field and dictionary.
atmBoundaryLayer (const atmBoundaryLayer &, const fvPatchFieldMapper &)
Construct by mapping given.
atmBoundaryLayer (const atmBoundaryLayer &)
Construct as copy.
const vector & flowDir () const
Return flow direction.
const vector & zDir () const
Return z-direction.
const scalarField & Ustar () const
Return friction velocity.
void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
void rmap (const atmBoundaryLayer &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
tmp< vectorField > U (const vectorField &p) const
Return the velocity distribution for the ATM.
tmp< scalarField > k (const vectorField &p) const
Return the turbulent kinetic energy distribution for the ATM.
tmp< scalarField > epsilon (const vectorField &p) const
Return the turbulent dissipation rate distribution for the ATM.
void write (Ostream &) const
Write.
Detailed Description
This boundary condition specifies a velocity inlet profile appropriate for atmospheric boundary layers (ABL).
See Foam::atmBoundaryLayer for details.
Example of the boundary condition specification:
ground
{
    type            atmBoundaryLayerInletVelocity;
    n               (1 0 0);
    z               (0 0 1);
    Uref            10.0;
    Zref            20.0;
    z0              uniform 0.1;
    zGround         uniform 0.0;
}
See also
Foam::atmBoundaryLayer, Foam::atmBoundaryLayerInletKFvPatchScalarField, Foam::atmBoundaryLayerInletEpsilonFvPatchScalarField
Source files
atmBoundaryLayerInletVelocityFvPatchVectorField.H
atmBoundaryLayerInletVelocityFvPatchVectorField.C
Definition at line 75 of file atmBoundaryLayerInletVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
atmBoundaryLayerInletVelocityFvPatchVectorField() [1/4]
atmBoundaryLayerInletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Construct from patch and internal field.
Definition at line 41 of file atmBoundaryLayerInletVelocityFvPatchVectorField.C.
Referenced by atmBoundaryLayerInletVelocityFvPatchVectorField::atmBoundaryLayerInletVelocityFvPatchVectorField(), and atmBoundaryLayerInletVelocityFvPatchVectorField::clone().
atmBoundaryLayerInletVelocityFvPatchVectorField() [2/4]
atmBoundaryLayerInletVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 53 of file atmBoundaryLayerInletVelocityFvPatchVectorField.C.
References atmBoundaryLayerInletVelocityFvPatchVectorField::atmBoundaryLayerInletVelocityFvPatchVectorField(), Field< vector >::operator=(), and U.
atmBoundaryLayerInletVelocityFvPatchVectorField() [3/4]
atmBoundaryLayerInletVelocityFvPatchVectorField (const atmBoundaryLayerInletVelocityFvPatchVectorField & pvf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
atmBoundaryLayerInletVelocityFvPatchVectorField onto a new patch
Definition at line 68 of file atmBoundaryLayerInletVelocityFvPatchVectorField.C.
References atmBoundaryLayerInletVelocityFvPatchVectorField::atmBoundaryLayerInletVelocityFvPatchVectorField().
atmBoundaryLayerInletVelocityFvPatchVectorField() [4/4]
atmBoundaryLayerInletVelocityFvPatchVectorField (const atmBoundaryLayerInletVelocityFvPatchVectorField & pvf, const DimensionedField< vector, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 82 of file atmBoundaryLayerInletVelocityFvPatchVectorField.C.
References atmBoundaryLayerInletVelocityFvPatchVectorField::autoMap().
Member Function Documentation
TypeName()
TypeName ("atmBoundaryLayerInletVelocity")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchVectorField> clone () const inline virtual
Construct and return a clone.
Definition at line 115 of file atmBoundaryLayerInletVelocityFvPatchVectorField.H.
References atmBoundaryLayerInletVelocityFvPatchVectorField::atmBoundaryLayerInletVelocityFvPatchVectorField().
clone() [2/2]
virtual tmp<fvPatchVectorField> clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 132 of file atmBoundaryLayerInletVelocityFvPatchVectorField.H.
References atmBoundaryLayerInletVelocityFvPatchVectorField::atmBoundaryLayerInletVelocityFvPatchVectorField(), atmBoundaryLayerInletVelocityFvPatchVectorField::autoMap(), atmBoundaryLayerInletVelocityFvPatchVectorField::rmap(), and atmBoundaryLayerInletVelocityFvPatchVectorField::write().
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Map (and resize as needed) from self given a mapping object.
Definition at line 95 of file atmBoundaryLayerInletVelocityFvPatchVectorField.C.
References atmBoundaryLayer::autoMap(), and atmBoundaryLayerInletVelocityFvPatchVectorField::rmap().
Referenced by atmBoundaryLayerInletVelocityFvPatchVectorField::atmBoundaryLayerInletVelocityFvPatchVectorField(), and atmBoundaryLayerInletVelocityFvPatchVectorField::clone().
rmap()
void rmap (const fvPatchVectorField & pvf, const labelList & addr) virtual
Reverse map the given fvPatchField onto this fvPatchField.
Definition at line 105 of file atmBoundaryLayerInletVelocityFvPatchVectorField.C.
References atmBoundaryLayer::rmap().
Referenced by atmBoundaryLayerInletVelocityFvPatchVectorField::autoMap(), and atmBoundaryLayerInletVelocityFvPatchVectorField::clone().
write()
void write (Ostream & os) const virtual
Write.
Definition at line 119 of file atmBoundaryLayerInletVelocityFvPatchVectorField.C.
References Foam::makePatchTypeField(), atmBoundaryLayer::write(), and fvPatchField< Type >::write().
Referenced by atmBoundaryLayerInletVelocityFvPatchVectorField::clone().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/RAS/derivedFvPatchFields/atmBoundaryLayerInletVelocity/atmBoundaryLayerInletVelocityFvPatchVectorField.H
src/TurbulenceModels/turbulenceModels/RAS/derivedFvPatchFields/atmBoundaryLayerInletVelocity/atmBoundaryLayerInletVelocityFvPatchVectorField.C