OpenFOAM: fileControl Class Reference
fileControl Class Reference
Public Member Functions
TypeName ("fileControl")
Runtime type information.
fileControl (const Time &runTime, const word &name, const dictionary &controlFunctionDict, const conformationSurfaces &geometryToConformTo, const scalar &defaultCellSize)
Construct from dictionary and references to conformalVoronoiMesh and.
~fileControl ()
Destructor.
virtual label maxPriority () const
virtual void cellSizeFunctionVertices (DynamicList< Foam::point > &pts, DynamicList< scalar > &sizes) const
virtual void initialVertices (pointField &pts, scalarField &sizes, triadField &alignments) const
Public Member Functions inherited from cellSizeAndAlignmentControl
TypeName ("cellSizeAndAlignmentControl")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, cellSizeAndAlignmentControl, dictionary,(const Time &runTime, const word &name, const dictionary &controlFunctionDict, const conformationSurfaces &geometryToConformTo, const scalar &defaultCellSize),(runTime, name, controlFunctionDict, geometryToConformTo, defaultCellSize))
cellSizeAndAlignmentControl (const Time &runTime, const word &name, const dictionary &controlFunctionDict, const conformationSurfaces &geometryToConformTo, const scalar &defaultCellSize)
Construct from dictionary and references to conformalVoronoiMesh and.
virtual ~cellSizeAndAlignmentControl ()
Destructor.
const word & name () const
const Switch & forceInitialPointInsertion () const
Additional Inherited Members
Static Public Member Functions inherited from cellSizeAndAlignmentControl
static autoPtr< cellSizeAndAlignmentControl > New (const Time &runTime, const word &name, const dictionary &controlFunctionDict, const conformationSurfaces &geometryToConformTo, const scalar &defaultCellSize)
Return a reference to the selected cellShapeControl.
Protected Attributes inherited from cellSizeAndAlignmentControl
const Time & runTime_
const scalar & defaultCellSize_
Switch forceInitialPointInsertion_
Detailed Description
Source files
fileControl.H
fileControl.C
Definition at line 48 of file fileControl.H.
Constructor & Destructor Documentation
fileControl()
fileControl (const Time & runTime, const word & name, const dictionary & controlFunctionDict, const conformationSurfaces & geometryToConformTo, const scalar & defaultCellSize)
Construct from dictionary and references to conformalVoronoiMesh and.
searchableSurfaces
~fileControl()
~fileControl ()
Destructor.
Member Function Documentation
TypeName()
TypeName ("fileControl")
Runtime type information.
maxPriority()
virtual label maxPriority () const inline virtual
Implements cellSizeAndAlignmentControl.
Definition at line 116 of file fileControl.H.
References fileControl::cellSizeFunctionVertices(), and fileControl::initialVertices().
cellSizeFunctionVertices()
virtual void cellSizeFunctionVertices (DynamicList< Foam::point > & pts, DynamicList< scalar > & sizes) const virtual
Implements cellSizeAndAlignmentControl.
Referenced by fileControl::maxPriority().
initialVertices()
virtual void initialVertices (pointField & pts, scalarField & sizes, triadField & alignments) const virtual
Implements cellSizeAndAlignmentControl.
Referenced by fileControl::maxPriority().
The documentation for this class was generated from the following file:
applications/utilities/mesh/generation/foamyMesh/conformalVoronoiMesh/cellShapeControl/cellSizeAndAlignmentControl/fileControl/fileControl.H