OpenFOAM: cellSizeAndAlignmentControl Class Reference
cellSizeAndAlignmentControl Class Reference abstract
Public Member Functions
TypeName ("cellSizeAndAlignmentControl")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, cellSizeAndAlignmentControl, dictionary,(const Time &runTime, const word &name, const dictionary &controlFunctionDict, const conformationSurfaces &geometryToConformTo, const scalar &defaultCellSize),(runTime, name, controlFunctionDict, geometryToConformTo, defaultCellSize))
cellSizeAndAlignmentControl (const Time &runTime, const word &name, const dictionary &controlFunctionDict, const conformationSurfaces &geometryToConformTo, const scalar &defaultCellSize)
Construct from dictionary and references to conformalVoronoiMesh and.
virtual ~cellSizeAndAlignmentControl ()
Destructor.
const word & name () const
const Switch & forceInitialPointInsertion () const
virtual label maxPriority () const =0
virtual void cellSizeFunctionVertices (DynamicList< Foam::point > &pts, DynamicList< scalar > &sizes) const =0
virtual void initialVertices (pointField &pts, scalarField &sizes, triadField &alignments) const =0
Static Public Member Functions
static autoPtr< cellSizeAndAlignmentControl > New (const Time &runTime, const word &name, const dictionary &controlFunctionDict, const conformationSurfaces &geometryToConformTo, const scalar &defaultCellSize)
Return a reference to the selected cellShapeControl.
Protected Attributes
const Time & runTime_
const scalar & defaultCellSize_
Switch forceInitialPointInsertion_
Detailed Description
Source files
cellSizeAndAlignmentControl.H
cellSizeAndAlignmentControlI.H
cellSizeAndAlignmentControl.C
Definition at line 53 of file cellSizeAndAlignmentControl.H.
Constructor & Destructor Documentation
cellSizeAndAlignmentControl()
cellSizeAndAlignmentControl (const Time & runTime, const word & name, const dictionary & controlFunctionDict, const conformationSurfaces & geometryToConformTo, const scalar & defaultCellSize)
Construct from dictionary and references to conformalVoronoiMesh and.
searchableSurfaces
~cellSizeAndAlignmentControl()
virtual ~cellSizeAndAlignmentControl () virtual
Destructor.
Member Function Documentation
TypeName()
TypeName ("cellSizeAndAlignmentControl")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , cellSizeAndAlignmentControl , dictionary , (const Time &runTime, const word &name, const dictionary &controlFunctionDict, const conformationSurfaces &geometryToConformTo, const scalar &defaultCellSize) , (runTime, name, controlFunctionDict, geometryToConformTo, defaultCellSize))
New()
static autoPtr<cellSizeAndAlignmentControl> New (const Time & runTime, const word & name, const dictionary & controlFunctionDict, const conformationSurfaces & geometryToConformTo, const scalar & defaultCellSize) static
Return a reference to the selected cellShapeControl.
name()
const word& name () const inline
Definition at line 145 of file cellSizeAndAlignmentControl.H.
forceInitialPointInsertion()
const Switch& forceInitialPointInsertion () const inline
Definition at line 150 of file cellSizeAndAlignmentControl.H.
References cellSizeAndAlignmentControl::cellSizeFunctionVertices(), cellSizeAndAlignmentControl::forceInitialPointInsertion_, cellSizeAndAlignmentControl::initialVertices(), and cellSizeAndAlignmentControl::maxPriority().
maxPriority()
virtual label maxPriority () const pure virtual
Implemented in searchableSurfaceControl, and fileControl.
Referenced by cellSizeAndAlignmentControl::forceInitialPointInsertion().
cellSizeFunctionVertices()
virtual void cellSizeFunctionVertices (DynamicList< Foam::point > & pts, DynamicList< scalar > & sizes) const pure virtual
Implemented in searchableSurfaceControl, and fileControl.
Referenced by cellSizeAndAlignmentControl::forceInitialPointInsertion().
initialVertices()
virtual void initialVertices (pointField & pts, scalarField & sizes, triadField & alignments) const pure virtual
Implemented in searchableSurfaceControl, and fileControl.
Referenced by cellSizeAndAlignmentControl::forceInitialPointInsertion().
Member Data Documentation
runTime_
const Time& runTime_ protected
Definition at line 57 of file cellSizeAndAlignmentControl.H.
defaultCellSize_
const scalar& defaultCellSize_ protected
Definition at line 59 of file cellSizeAndAlignmentControl.H.
forceInitialPointInsertion_
Switch forceInitialPointInsertion_ protected
Definition at line 61 of file cellSizeAndAlignmentControl.H.
Referenced by cellSizeAndAlignmentControl::forceInitialPointInsertion().
The documentation for this class was generated from the following file:
applications/utilities/mesh/generation/foamyMesh/conformalVoronoiMesh/cellShapeControl/cellSizeAndAlignmentControl/cellSizeAndAlignmentControl/cellSizeAndAlignmentControl.H