OpenFOAM: indexedCell< Gt, Cb > Class Template Reference
indexedCell< Gt, Cb > Class Template Reference
An indexed form of CGAL::Triangulation_cell_base_3<K> used to keep track of the Delaunay cells (tets) in the tessellation.
Classes
struct Rebind_TDS
Public Types
typedef Cb::Triangulation_data_structure Tds
typedef Cb::Vertex_handle Vertex_handle
typedef Cb::Cell_handle Cell_handle
Public Types inherited from indexedCellEnum
enum cellTypes {
ctUnassigned = INT_MIN, ctFar = INT_MIN + 1, ctInternal = INT_MIN + 2, ctSurface = INT_MIN + 3,
ctFeatureEdge = INT_MIN + 4, ctFeaturePoint = INT_MIN + 5
}
Public Member Functions
indexedCell ()
indexedCell (Vertex_handle v0, Vertex_handle v1, Vertex_handle v2, Vertex_handle v3)
indexedCell (Vertex_handle v0, Vertex_handle v1, Vertex_handle v2, Vertex_handle v3, Cell_handle n0, Cell_handle n1, Cell_handle n2, Cell_handle n3)
Foam::label & cellIndex ()
Foam::label cellIndex () const
const Foam::point dual ()
bool unassigned () const
int & filterCount ()
int filterCount () const
bool real () const
Is the Delaunay cell real, i.e. any real vertex.
bool hasFarPoint () const
Does the Delaunay cell have a far point.
bool hasReferredPoint () const
Does the Delaunay cell have a referred point.
bool hasFeaturePoint () const
Does the Delaunay cell have a feature point.
bool hasSeedPoint () const
Does the Delaunay cell have a seed point.
bool hasInternalPoint () const
bool hasBoundaryPoint () const
bool hasConstrainedPoint () const
bool parallelDualVertex () const
Does the Dual vertex form part of a processor patch.
Foam::label vertexLowestProc () const
Foam::tetCell vertexGlobalIndices (const Foam::globalIndex &globalDelaunayVertexIndices) const
Using the globalIndex object, return a list of four (sorted) global.
Foam::FixedList< Foam::label, 4 > globallyOrderedCellVertices (const Foam::globalIndex &globalDelaunayVertexIndices) const
Using the globalIndex object, return a list of four vertices with.
bool internalOrBoundaryDualVertex () const
Is the Delaunay cell part of the final dual mesh, i.e. any vertex.
bool anyInternalOrBoundaryDualVertex () const
Is the Delaunay cell real or referred (or mixed), i.e. all vertices.
bool boundaryDualVertex () const
A dual vertex on the boundary will result from a Delaunay cell with.
bool baffleSurfaceDualVertex () const
bool baffleEdgeDualVertex () const
bool featureEdgeDualVertex () const
A dual vertex on a feature edge will result from this Delaunay cell.
bool featurePointDualVertex () const
A dual vertex on a feature point will result from this Delaunay cell.
bool nearProcBoundary () const
bool potentialCoplanarCell () const
bool featurePointExternalCell () const
bool featurePointInternalCell () const
Foam::InfoProxy< indexedCell< Gt, Cb > > info () const
Return info proxy.
Friends
Foam::Ostream & Foam::operator (Foam::Ostream &, const Foam::InfoProxy< indexedCell< Gt, Cb >> &)
Additional Inherited Members
Static Public Attributes inherited from indexedCellEnum
static const Foam::NamedEnum< cellTypes, 6 > cellTypesNames_
Detailed Description
template<class Gt, class Cb = CGAL::Delaunay_triangulation_cell_base_with_circumcenter_3<Gt>>
class CGAL::indexedCell< Gt, Cb >
An indexed form of CGAL::Triangulation_cell_base_3<K> used to keep track of the Delaunay cells (tets) in the tessellation.
Source files
indexedCell.H
indexedCellI.H
indexedCell.C
Definition at line 56 of file indexedCell.H.
Member Typedef Documentation
Tds
typedef Cb::Triangulation_data_structure Tds
Definition at line 117 of file indexedCell.H.
Vertex_handle
typedef Cb::Vertex_handle Vertex_handle
Definition at line 118 of file indexedCell.H.
Cell_handle
typedef Cb::Cell_handle Cell_handle
Definition at line 119 of file indexedCell.H.
Constructor & Destructor Documentation
indexedCell() [1/3]
indexedCell () inline
Definition at line 53 of file indexedCellI.H.
Referenced by indexedCell< Gt, Cb >::indexedCell().
indexedCell() [2/3]
indexedCell (Vertex_handle v0, Vertex_handle v1, Vertex_handle v2, Vertex_handle v3) inline
Definition at line 63 of file indexedCellI.H.
References indexedCell< Gt, Cb >::indexedCell().
indexedCell() [3/3]
indexedCell (Vertex_handle v0, Vertex_handle v1, Vertex_handle v2, Vertex_handle v3, Cell_handle n0, Cell_handle n1, Cell_handle n2, Cell_handle n3) inline
Definition at line 75 of file indexedCellI.H.
Member Function Documentation
cellIndex() [1/2]
Foam::label & cellIndex () inline
Definition at line 95 of file indexedCellI.H.
cellIndex() [2/2]
Foam::label cellIndex () const inline
Definition at line 102 of file indexedCellI.H.
References indexedCell< Gt, Cb >::dual().
dual()
const Foam::point dual () inline
Definition at line 119 of file indexedCellI.H.
Referenced by indexedCell< Gt, Cb >::cellIndex().
unassigned()
bool unassigned () const inline
Definition at line 135 of file indexedCellI.H.
References indexedCellEnum::ctUnassigned.
filterCount() [1/2]
int & filterCount () inline
Definition at line 142 of file indexedCellI.H.
filterCount() [2/2]
int filterCount () const inline
Definition at line 149 of file indexedCellI.H.
real()
bool real () const inline
Is the Delaunay cell real, i.e. any real vertex.
Definition at line 156 of file indexedCellI.H.
Referenced by indexedCell< Gt, Cb >::parallelDualVertex().
hasFarPoint()
bool hasFarPoint () const inline
Does the Delaunay cell have a far point.
Definition at line 178 of file indexedCellI.H.
Referenced by indexedCell< Gt, Cb >::parallelDualVertex().
hasReferredPoint()
bool hasReferredPoint () const inline
Does the Delaunay cell have a referred point.
Definition at line 191 of file indexedCellI.H.
hasFeaturePoint()
bool hasFeaturePoint () const inline
Does the Delaunay cell have a feature point.
Definition at line 204 of file indexedCellI.H.
hasSeedPoint()
bool hasSeedPoint () const inline
Does the Delaunay cell have a seed point.
Definition at line 217 of file indexedCellI.H.
hasInternalPoint()
bool hasInternalPoint () const inline
Definition at line 230 of file indexedCellI.H.
hasBoundaryPoint()
bool hasBoundaryPoint () const inline
Definition at line 243 of file indexedCellI.H.
hasConstrainedPoint()
bool hasConstrainedPoint () const inline
Definition at line 256 of file indexedCellI.H.
parallelDualVertex()
bool parallelDualVertex () const inline
Does the Dual vertex form part of a processor patch.
Definition at line 269 of file indexedCellI.H.
References indexedCell< Gt, Cb >::hasFarPoint(), and indexedCell< Gt, Cb >::real().
vertexLowestProc()
Foam::label vertexLowestProc () const inline
Definition at line 293 of file indexedCellI.H.
References Foam::min(), and indexedCell< Gt, Cb >::vertexGlobalIndices().
vertexGlobalIndices()
Foam::tetCell vertexGlobalIndices (const Foam::globalIndex & globalDelaunayVertexIndices) const inline
Using the globalIndex object, return a list of four (sorted) global.
Delaunay vertex indices that uniquely identify this tet in parallel
Definition at line 311 of file indexedCellI.H.
References indexedCell< Gt, Cb >::globallyOrderedCellVertices(), FixedList< T, Size >::size(), and Foam::Swap().
Referenced by indexedCell< Gt, Cb >::vertexLowestProc().
globallyOrderedCellVertices()
Foam::FixedList< Foam::label, 4 > globallyOrderedCellVertices (const Foam::globalIndex & globalDelaunayVertexIndices) const inline
Using the globalIndex object, return a list of four vertices with.
so that the cell has a consistent orientation in parallel.
Definition at line 338 of file indexedCellI.H.
References Foam::identity(), FixedList< T, Size >::size(), and Foam::Swap().
Referenced by indexedCell< Gt, Cb >::vertexGlobalIndices().
internalOrBoundaryDualVertex()
bool internalOrBoundaryDualVertex () const inline
Is the Delaunay cell part of the final dual mesh, i.e. any vertex.
form part of the internal or boundary definition
Definition at line 371 of file indexedCellI.H.
anyInternalOrBoundaryDualVertex()
bool anyInternalOrBoundaryDualVertex () const inline
Is the Delaunay cell real or referred (or mixed), i.e. all vertices.
form part of the real or referred internal or boundary definition
Definition at line 384 of file indexedCellI.H.
boundaryDualVertex()
bool boundaryDualVertex () const inline
A dual vertex on the boundary will result from a Delaunay cell with.
least one Delaunay vertex outside and at least one inside
Definition at line 401 of file indexedCellI.H.
baffleSurfaceDualVertex()
bool baffleSurfaceDualVertex () const inline
Definition at line 444 of file indexedCellI.H.
baffleEdgeDualVertex()
bool baffleEdgeDualVertex () const inline
Definition at line 465 of file indexedCellI.H.
featureEdgeDualVertex()
bool featureEdgeDualVertex () const inline
A dual vertex on a feature edge will result from this Delaunay cell.
Definition at line 486 of file indexedCellI.H.
featurePointDualVertex()
bool featurePointDualVertex () const inline
A dual vertex on a feature point will result from this Delaunay cell.
Definition at line 524 of file indexedCellI.H.
nearProcBoundary()
bool nearProcBoundary () const inline
Definition at line 537 of file indexedCellI.H.
potentialCoplanarCell()
bool potentialCoplanarCell () const inline
Definition at line 550 of file indexedCellI.H.
References Foam::vectorTools::areParallel(), Foam::endl(), Foam::Pout, Foam::type(), and Foam::Zero.
featurePointExternalCell()
bool featurePointExternalCell () const inline
Definition at line 640 of file indexedCellI.H.
featurePointInternalCell()
bool featurePointInternalCell () const inline
Definition at line 702 of file indexedCellI.H.
info()
Foam::InfoProxy<indexedCell<Gt, Cb> > info () const inline
Return info proxy.
Used to print indexedCell information to a stream
Definition at line 245 of file indexedCell.H.
Friends And Related Function Documentation
Foam::operator
Foam::Ostream& Foam::operator (Foam::Ostream & , const Foam::InfoProxy< indexedCell< Gt, Cb >> &) friend
The documentation for this class was generated from the following files:
applications/utilities/mesh/generation/foamyMesh/conformalVoronoiMesh/conformalVoronoiMesh/indexedCell/indexedCell.H
applications/utilities/mesh/generation/foamyMesh/conformalVoronoiMesh/conformalVoronoiMesh/indexedCell/indexedCellI.H