OpenFOAM: cvControls Class Reference
cvControls Class Reference
Controls for the conformalVoronoiMesh mesh generator.
Public Member Functions
cvControls (const dictionary &foamyHexMeshDict)
Construct from references to conformalVoronoiMesh and dictionary.
~cvControls ()
Destructor.
const dictionary & foamyHexMeshDict () const
Return the foamyHexMeshDict.
scalar pointPairDistanceCoeff () const
Return the pointPairDistanceCoeff.
scalar mixedFeaturePointPPDistanceCoeff () const
Return the mixedFeaturePointPPDistanceCoeff.
scalar featurePointExclusionDistanceCoeff () const
Return the featurePointExclusionDistanceCoeff.
scalar featureEdgeExclusionDistanceCoeff () const
Return the featureEdgeExclusionDistanceCoeff.
Switch guardFeaturePoints () const
Switch edgeAiming () const
Switch snapFeaturePoints () const
Switch circulateEdges () const
scalar surfacePtExclusionDistanceCoeff () const
Return the surfacePtExclusionDistanceCoeff.
Switch specialiseFeaturePoints () const
Return whether to use specialised feature points.
scalar surfaceSearchDistanceCoeff () const
Return the surfaceSearchDistanceCoeff.
scalar maxSurfaceProtrusionCoeff () const
Return the maxSurfaceProtrusionCoeff.
scalar maxQuadAngle () const
Return the maxQuadAngle.
label surfaceConformationRebuildFrequency () const
Return the surfaceConformationRebuildFrequency.
scalar edgeSearchDistCoeffSqr () const
Return the edgeSearchDistCoeffSqr for conformation.
scalar surfacePtReplaceDistCoeffSqr () const
Return the surfacePtReplaceDistCoeffSqr for conformation.
label maxConformationIterations () const
Return the maxConformationIterations.
scalar iterationToInitialHitRatioLimit () const
Return the iterationToInitialHitRatioLimit.
scalar defaultCellSize () const
Return the defaultCellSize.
scalar minimumCellSize () const
Return the minimumCellSize.
Switch objOutput () const
Return the objOutput Switch.
Switch timeChecks () const
Return the timeChecks Switch.
Switch printVertexInfo () const
Return the printVertexInfo Switch.
scalar maxLoadUnbalance () const
Return the maxLoadUnbalance.
scalar cosAlignmentAcceptanceAngle () const
Return the cosAlignmentAcceptanceAngle.
scalar aspectRatio () const
Return the aspectRatio.
const vector & aspectRatioDirection () const
Return the aspectRatioDirection.
scalar insertionDistCoeff () const
Return the insertionDistCoeff.
scalar faceAreaRatioCoeff () const
Return the faceAreaRatioCoeff.
scalar cosInsertionAcceptanceAngle () const
Return the cosInsertionAcceptanceAngle.
scalar removalDistCoeff () const
Return removalDistCoeff.
Switch filterEdges () const
Filter edges at output time.
Switch filterFaces () const
Filter faces at output time.
Switch writeTetDualMesh () const
Write tetMesh at output time.
Switch writeCellShapeControlMesh () const
Write cellShapeControlMesh at output time.
Switch writeBackgroundMeshDecomposition () const
Write backgroundMeshDecomposition at output time.
Detailed Description
Controls for the conformalVoronoiMesh mesh generator.
Source files
cvControls.H
cvControls.C
Definition at line 53 of file cvControls.H.
Constructor & Destructor Documentation
cvControls()
cvControls (const dictionary & foamyHexMeshDict)
Construct from references to conformalVoronoiMesh and dictionary.
~cvControls()
~cvControls ()
Destructor.
Member Function Documentation
foamyHexMeshDict()
const Foam::dictionary & foamyHexMeshDict () const inline
Return the foamyHexMeshDict.
Definition at line 28 of file cvControlsI.H.
pointPairDistanceCoeff()
Foam::scalar pointPairDistanceCoeff () const inline
Return the pointPairDistanceCoeff.
Definition at line 34 of file cvControlsI.H.
Referenced by conformalVoronoiMesh::pointPairDistance().
mixedFeaturePointPPDistanceCoeff()
Foam::scalar mixedFeaturePointPPDistanceCoeff () const inline
Return the mixedFeaturePointPPDistanceCoeff.
Definition at line 40 of file cvControlsI.H.
Referenced by conformalVoronoiMesh::mixedFeaturePointDistance().
featurePointExclusionDistanceCoeff()
Foam::scalar featurePointExclusionDistanceCoeff () const inline
Return the featurePointExclusionDistanceCoeff.
Definition at line 46 of file cvControlsI.H.
featureEdgeExclusionDistanceCoeff()
Foam::scalar featureEdgeExclusionDistanceCoeff () const inline
Return the featureEdgeExclusionDistanceCoeff.
Definition at line 52 of file cvControlsI.H.
guardFeaturePoints()
Foam::Switch guardFeaturePoints () const inline
Definition at line 58 of file cvControlsI.H.
edgeAiming()
Foam::Switch edgeAiming () const inline
Definition at line 63 of file cvControlsI.H.
snapFeaturePoints()
Foam::Switch snapFeaturePoints () const inline
Definition at line 68 of file cvControlsI.H.
circulateEdges()
Foam::Switch circulateEdges () const inline
Definition at line 73 of file cvControlsI.H.
surfacePtExclusionDistanceCoeff()
Foam::scalar surfacePtExclusionDistanceCoeff () const inline
Return the surfacePtExclusionDistanceCoeff.
Definition at line 79 of file cvControlsI.H.
specialiseFeaturePoints()
Foam::Switch specialiseFeaturePoints () const inline
Return whether to use specialised feature points.
Definition at line 84 of file cvControlsI.H.
surfaceSearchDistanceCoeff()
Foam::scalar surfaceSearchDistanceCoeff () const inline
Return the surfaceSearchDistanceCoeff.
Definition at line 89 of file cvControlsI.H.
maxSurfaceProtrusionCoeff()
Foam::scalar maxSurfaceProtrusionCoeff () const inline
Return the maxSurfaceProtrusionCoeff.
Definition at line 95 of file cvControlsI.H.
Referenced by conformalVoronoiMesh::maxSurfaceProtrusion().
maxQuadAngle()
Foam::scalar maxQuadAngle () const inline
Return the maxQuadAngle.
Definition at line 101 of file cvControlsI.H.
surfaceConformationRebuildFrequency()
Foam::label surfaceConformationRebuildFrequency () const inline
Return the surfaceConformationRebuildFrequency.
Definition at line 107 of file cvControlsI.H.
edgeSearchDistCoeffSqr()
Foam::scalar edgeSearchDistCoeffSqr () const inline
Return the edgeSearchDistCoeffSqr for conformation.
Definition at line 113 of file cvControlsI.H.
surfacePtReplaceDistCoeffSqr()
Foam::scalar surfacePtReplaceDistCoeffSqr () const inline
Return the surfacePtReplaceDistCoeffSqr for conformation.
Definition at line 119 of file cvControlsI.H.
maxConformationIterations()
Foam::label maxConformationIterations () const inline
Return the maxConformationIterations.
Definition at line 125 of file cvControlsI.H.
iterationToInitialHitRatioLimit()
Foam::scalar iterationToInitialHitRatioLimit () const inline
Return the iterationToInitialHitRatioLimit.
Definition at line 131 of file cvControlsI.H.
defaultCellSize()
Foam::scalar defaultCellSize () const inline
Return the defaultCellSize.
Definition at line 137 of file cvControlsI.H.
minimumCellSize()
Foam::scalar minimumCellSize () const inline
Return the minimumCellSize.
Definition at line 143 of file cvControlsI.H.
objOutput()
Foam::Switch objOutput () const inline
Return the objOutput Switch.
Definition at line 149 of file cvControlsI.H.
timeChecks()
Foam::Switch timeChecks () const inline
Return the timeChecks Switch.
Definition at line 155 of file cvControlsI.H.
printVertexInfo()
Foam::Switch printVertexInfo () const inline
Return the printVertexInfo Switch.
Definition at line 161 of file cvControlsI.H.
maxLoadUnbalance()
Foam::scalar maxLoadUnbalance () const inline
Return the maxLoadUnbalance.
Definition at line 167 of file cvControlsI.H.
cosAlignmentAcceptanceAngle()
Foam::scalar cosAlignmentAcceptanceAngle () const inline
Return the cosAlignmentAcceptanceAngle.
Definition at line 173 of file cvControlsI.H.
aspectRatio()
scalar aspectRatio () const inline
Return the aspectRatio.
aspectRatioDirection()
const vector& aspectRatioDirection () const inline
Return the aspectRatioDirection.
insertionDistCoeff()
Foam::scalar insertionDistCoeff () const inline
Return the insertionDistCoeff.
Definition at line 179 of file cvControlsI.H.
faceAreaRatioCoeff()
Foam::scalar faceAreaRatioCoeff () const inline
Return the faceAreaRatioCoeff.
Definition at line 185 of file cvControlsI.H.
cosInsertionAcceptanceAngle()
Foam::scalar cosInsertionAcceptanceAngle () const inline
Return the cosInsertionAcceptanceAngle.
Definition at line 191 of file cvControlsI.H.
removalDistCoeff()
Foam::scalar removalDistCoeff () const inline
Return removalDistCoeff.
Definition at line 197 of file cvControlsI.H.
filterEdges()
Foam::Switch filterEdges () const inline
Filter edges at output time.
Definition at line 203 of file cvControlsI.H.
filterFaces()
Foam::Switch filterFaces () const inline
Filter faces at output time.
Definition at line 208 of file cvControlsI.H.
writeTetDualMesh()
Foam::Switch writeTetDualMesh () const inline
Write tetMesh at output time.
Definition at line 213 of file cvControlsI.H.
writeCellShapeControlMesh()
Foam::Switch writeCellShapeControlMesh () const inline
Write cellShapeControlMesh at output time.
Definition at line 218 of file cvControlsI.H.
writeBackgroundMeshDecomposition()
Foam::Switch writeBackgroundMeshDecomposition () const inline
Write backgroundMeshDecomposition at output time.
Definition at line 223 of file cvControlsI.H.
The documentation for this class was generated from the following files:
applications/utilities/mesh/generation/foamyMesh/conformalVoronoiMesh/cvControls/cvControls.H
applications/utilities/mesh/generation/foamyMesh/conformalVoronoiMesh/cvControls/cvControlsI.H