OpenFOAM: faceZoneSelection Class Reference
faceZoneSelection Class Reference
Select faces from faceZone.
Public Member Functions
TypeName ("faceZone")
Runtime type information.
faceZoneSelection (const word &name, const fvMesh &mesh, const dictionary &dict)
Construct from dictionary.
autoPtr< faceSelection > clone () const
Clone.
virtual ~faceZoneSelection ()
Destructor.
virtual void select (const label zoneID, labelList &, boolList &) const
Apply this selector.
Public Member Functions inherited from faceSelection
TypeName ("faceSelection")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, faceSelection, dictionary,(const word &name, const fvMesh &mesh, const dictionary &dict),(name, mesh, dict))
faceSelection (const word &name, const fvMesh &mesh, const dictionary &dict)
Construct from dictionary.
autoPtr< faceSelection > clone () const
Clone.
virtual ~faceSelection ()
Destructor.
const word & name () const
const dictionary & dict () const
Additional Inherited Members
Static Public Member Functions inherited from faceSelection
static autoPtr< faceSelection > New (const word &name, const fvMesh &mesh, const dictionary &dict)
Return a reference to the selected faceSelection.
Protected Attributes inherited from faceSelection
const word name_
Name.
const fvMesh & mesh_
Reference to mesh.
const dictionary dict_
Input dictionary.
const Switch flip_
Switch direction?
Detailed Description
Select faces from faceZone.
Source files
faceZoneSelection.H
faceZoneSelection.C
Definition at line 56 of file faceZoneSelection.H.
Constructor & Destructor Documentation
faceZoneSelection()
faceZoneSelection (const word & name, const fvMesh & mesh, const dictionary & dict)
Construct from dictionary.
~faceZoneSelection()
virtual ~faceZoneSelection () virtual
Destructor.
Referenced by faceZoneSelection::clone().
Member Function Documentation
TypeName()
TypeName ("faceZone")
Runtime type information.
clone()
autoPtr<faceSelection> clone () const inline
Clone.
Definition at line 85 of file faceZoneSelection.H.
References NotImplemented, faceZoneSelection::select(), and faceZoneSelection::~faceZoneSelection().
select()
virtual void select (const label zoneID, labelList & , boolList &) const virtual
Apply this selector.
Implements faceSelection.
Referenced by faceZoneSelection::clone().
The documentation for this class was generated from the following file:
applications/utilities/mesh/manipulation/createBaffles/faceSelection/faceZoneSelection.H