OpenFOAM: searchableSurfaceSelection Class Reference
searchableSurfaceSelection Class Reference
Selects all (internal or coupled) faces intersecting the searchableSurface.
Public Member Functions
TypeName ("searchableSurface")
Runtime type information.
searchableSurfaceSelection (const word &name, const fvMesh &mesh, const dictionary &dict)
Construct from dictionary.
autoPtr< faceSelection > clone () const
Clone.
virtual ~searchableSurfaceSelection ()
Destructor.
virtual void select (const label zoneID, labelList &, boolList &) const
Public Member Functions inherited from faceSelection
TypeName ("faceSelection")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, faceSelection, dictionary,(const word &name, const fvMesh &mesh, const dictionary &dict),(name, mesh, dict))
faceSelection (const word &name, const fvMesh &mesh, const dictionary &dict)
Construct from dictionary.
autoPtr< faceSelection > clone () const
Clone.
virtual ~faceSelection ()
Destructor.
const word & name () const
const dictionary & dict () const
Additional Inherited Members
Static Public Member Functions inherited from faceSelection
static autoPtr< faceSelection > New (const word &name, const fvMesh &mesh, const dictionary &dict)
Return a reference to the selected faceSelection.
Protected Attributes inherited from faceSelection
const word name_
Name.
const fvMesh & mesh_
Reference to mesh.
const dictionary dict_
Input dictionary.
const Switch flip_
Switch direction?
Detailed Description
Selects all (internal or coupled) faces intersecting the searchableSurface.
Source files
searchableSurfaceSelection.H
searchableSurfaceSelection.C
Definition at line 53 of file searchableSurfaceSelection.H.
Constructor & Destructor Documentation
searchableSurfaceSelection()
searchableSurfaceSelection (const word & name, const fvMesh & mesh, const dictionary & dict)
Construct from dictionary.
~searchableSurfaceSelection()
virtual ~searchableSurfaceSelection () virtual
Destructor.
Referenced by searchableSurfaceSelection::clone().
Member Function Documentation
TypeName()
TypeName ("searchableSurface")
Runtime type information.
clone()
autoPtr<faceSelection> clone () const inline
Clone.
Definition at line 78 of file searchableSurfaceSelection.H.
References NotImplemented, searchableSurfaceSelection::select(), and searchableSurfaceSelection::~searchableSurfaceSelection().
select()
virtual void select (const label zoneID, labelList & , boolList &) const virtual
Implements faceSelection.
Referenced by searchableSurfaceSelection::clone().
The documentation for this class was generated from the following file:
applications/utilities/mesh/manipulation/createBaffles/faceSelection/searchableSurfaceSelection.H