OpenFOAM: meshDualiser Class Reference
meshDualiser Class Reference
Creates dual of polyMesh. Every point becomes a cell (or multiple cells for feature points), a walk around every edge creates faces between them.
Public Member Functions
ClassName ("meshDualiser")
Runtime type information.
meshDualiser (const polyMesh &)
Construct from mesh.
const labelListList & pointToDualCells () const
From point on cell to dual cell. Either single entry or.
const labelList & pointToDualPoint () const
From point to dual point (or -1 if not feature point).
const labelList & cellToDualPoint () const
From cell to dual point (at cell centre). All cells become.
const labelList & faceToDualPoint () const
From face to dual point (at face centre; or -1 if not.
const labelList & edgeToDualPoint () const
From edge to dual point (at edge mid; or -1 if not feature.
void setRefinement (const bool splitFace, const labelList &featureFaces, const labelList &featureEdges, const labelList &singleCellFeaturePoints, const labelList &multiCellFeaturePoints, polyTopoChange &meshMod)
Insert all changes into meshMod to convert the polyMesh into.
Detailed Description
Creates dual of polyMesh. Every point becomes a cell (or multiple cells for feature points), a walk around every edge creates faces between them.
Put all points you want in the final mesh into featurePoints; all edge(mid)s you want in the final mesh into featureEdges; all face(centre)s in faceFaces.
Usually to preserve boundaries:
all boundary faces are featureFaces
all edges and points inbetween different patches are featureEdges/points.
In same way you can also preserve internal faces (e.g. faceZones)
Source files
meshDualiser.H Foam::
meshDualiser.C
Definition at line 66 of file meshDualiser.H.
Constructor & Destructor Documentation
meshDualiser()
meshDualiser (const polyMesh &)
Construct from mesh.
Member Function Documentation
ClassName()
ClassName ("meshDualiser")
Runtime type information.
pointToDualCells()
const labelListList& pointToDualCells () const inline
From point on cell to dual cell. Either single entry or.
one entry per pointCells.
Definition at line 195 of file meshDualiser.H.
pointToDualPoint()
const labelList& pointToDualPoint () const inline
From point to dual point (or -1 if not feature point).
Definition at line 201 of file meshDualiser.H.
References meshDualiser::cellToDualPoint(), meshDualiser::edgeToDualPoint(), meshDualiser::faceToDualPoint(), and meshDualiser::setRefinement().
cellToDualPoint()
const labelList& cellToDualPoint () const inline
From cell to dual point (at cell centre). All cells become.
points.
Definition at line 208 of file meshDualiser.H.
Referenced by meshDualiser::pointToDualPoint().
faceToDualPoint()
const labelList& faceToDualPoint () const inline
From face to dual point (at face centre; or -1 if not.
feature face).
Definition at line 215 of file meshDualiser.H.
Referenced by meshDualiser::pointToDualPoint().
edgeToDualPoint()
const labelList& edgeToDualPoint () const inline
From edge to dual point (at edge mid; or -1 if not feature.
edge).
Definition at line 222 of file meshDualiser.H.
Referenced by meshDualiser::pointToDualPoint().
setRefinement()
void setRefinement (const bool splitFace, const labelList & featureFaces, const labelList & featureEdges, const labelList & singleCellFeaturePoints, const labelList & multiCellFeaturePoints, polyTopoChange & meshMod)
Insert all changes into meshMod to convert the polyMesh into.
its dual. featureFaces : faces where we want a point at the face centre featureEdges : edges ,, edge mid featurePoints : points ,, point. Two variants: singleCellFeaturePoints : point becomes one dualcell. Use this for e.g. convex boundary points. multiCellFeaturePoints : one dualcell per original cell around point. Use this for e.g. concave boundary points since it prevents big concave boundary cells.
Referenced by meshDualiser::pointToDualPoint().
The documentation for this class was generated from the following file:
applications/utilities/mesh/manipulation/polyDualMesh/meshDualiser.H