OpenFOAM: surfaceMeshWriter Class Reference
surfaceMeshWriter Class Reference
Write faces with fields.
Public Member Functions
surfaceMeshWriter (const bool binary, const indirectPrimitivePatch &pp, const word &name, const fileName &)
Construct from components.
std::ofstream & os ()
template<class Type >
tmp< Field< Type > > getFaceField (const GeometricField< Type, fvsPatchField, surfaceMesh > &) const
Extract face data.
template<class Type >
void write (const UPtrList< const GeometricField< Type, fvsPatchField, surfaceMesh > > &)
Write surfaceFields.
Detailed Description
Write faces with fields.
Source files
surfaceMeshWriter.H
surfaceMeshWriter.C
surfaceMeshWriterTemplates.C
Definition at line 58 of file surfaceMeshWriter.H.
Constructor & Destructor Documentation
surfaceMeshWriter()
surfaceMeshWriter (const bool binary, const indirectPrimitivePatch & pp, const word & name, const fileName &)
Construct from components.
Member Function Documentation
os()
std::ofstream& os () inline
Definition at line 85 of file surfaceMeshWriter.H.
References surfaceMeshWriter::getFaceField(), and surfaceMeshWriter::write().
getFaceField()
tmp<Field<Type> > getFaceField (const GeometricField< Type, fvsPatchField, surfaceMesh > &) const
Extract face data.
Referenced by surfaceMeshWriter::os().
write()
void write (const UPtrList< const GeometricField< Type, fvsPatchField, surfaceMesh > > &)
Write surfaceFields.
Referenced by surfaceMeshWriter::os().
The documentation for this class was generated from the following file:
applications/utilities/postProcessing/dataConversion/foamToVTK/foamToVTK/surfaceMeshWriter.H