OpenFOAM: vtkPVFoam Class Reference
vtkPVFoam Class Reference
Provides a reader interface for OpenFOAM to VTK interaction.
Public Member Functions
ClassName ("vtkPVFoam")
Static data members.
vtkPVFoam (const char *const FileName, vtkPVFoamReader *reader)
Construct from components.
~vtkPVFoam ()
Destructor.
void updateInfo ()
Update.
void Update (vtkMultiBlockDataSet *output, vtkMultiBlockDataSet *lagrangianOutput)
void CleanUp ()
Clean any storage.
double * findTimes (int &nTimeSteps)
Allocate and return a list of selected times.
void renderPatchNames (vtkRenderer *, const bool show)
Add/remove patch names to/from the view.
int setTime (int count, const double requestTimes[])
Set the runTime to the first plausible request time,.
int timeIndex () const
The current time index.
void PrintSelf (ostream &, vtkIndent) const
Debug information.
template<class Type >
Foam::label addToSelection (vtkDataArraySelection *select, const IOobjectList &objectLst, const string &suffix)
Static Public Member Functions
static void printMemory ()
Simple memory used debugging information.
Detailed Description
Provides a reader interface for OpenFOAM to VTK interaction.
Source files
vtkPVFoam.H
vtkPVFoam.C
vtkPVFoam.H
vtkPVFoamFields.C
vtkPVFoamMesh.C
vtkPVFoamMeshLagrangian.C
vtkPVFoamTemplates.C
vtkPVFoamMeshSet.C
vtkPVFoamMeshVolume.C
vtkPVFoamMeshZone.C
vtkPVFoamFaceField.H
vtkPVFoamLagrangianFields.H
vtkPVFoamPatchField.H
vtkPVFoamPointFields.H
vtkPVFoamPoints.H
vtkPVFoamUpdateInfo.C
vtkPVFoamUpdateInfoFields.H
vtkPVFoamUtils.C
vtkPVFoamVolFields.H
vtkPVFoamAddToSelection.H
Needed by VTK: vtkDataArrayTemplateImplicit.txx
Definition at line 107 of file vtkPVFoam.H.
Constructor & Destructor Documentation
vtkPVFoam()
vtkPVFoam (const char *const FileName, vtkPVFoamReader * reader)
Construct from components.
~vtkPVFoam()
~vtkPVFoam ()
Destructor.
Member Function Documentation
ClassName()
ClassName ("vtkPVFoam")
Static data members.
updateInfo()
void updateInfo ()
Update.
Update()
void Update (vtkMultiBlockDataSet * output, vtkMultiBlockDataSet * lagrangianOutput)
CleanUp()
void CleanUp ()
Clean any storage.
findTimes()
double* findTimes (int & nTimeSteps)
Allocate and return a list of selected times.
returns the count via the parameter
renderPatchNames()
void renderPatchNames (vtkRenderer * , const bool show)
Add/remove patch names to/from the view.
setTime()
int setTime (int count, const double requestTimes[])
Set the runTime to the first plausible request time,.
returns the timeIndex sets to "constant" on error
timeIndex()
int timeIndex () const inline
The current time index.
Definition at line 709 of file vtkPVFoam.H.
References vtkPVFoam::printMemory(), and vtkPVFoam::PrintSelf().
PrintSelf()
void PrintSelf (ostream & , vtkIndent) const
Debug information.
Referenced by vtkPVFoam::timeIndex().
printMemory()
void printMemory () static
Simple memory used debugging information.
Definition at line 330 of file vtkPVFoamUtils.C.
References Foam::Info, and memInfo::valid().
Referenced by vtkPVFoam::timeIndex().
addToSelection()
Foam::label addToSelection (vtkDataArraySelection * select, const IOobjectList & objectLst, const string & suffix)
Definition at line 40 of file vtkPVFoamAddToSelection.H.
References forAll, and IOobjectList::names().
The documentation for this class was generated from the following files:
applications/utilities/postProcessing/graphics/PVReaders/PVFoamReader/vtkPVFoam/vtkPVFoam.H
applications/utilities/postProcessing/graphics/PVReaders/PVFoamReader/vtkPVFoam/vtkPVFoamAddToSelection.H
applications/utilities/postProcessing/graphics/PVReaders/PVFoamReader/vtkPVFoam/vtkPVFoamFaceField.H
applications/utilities/postProcessing/graphics/PVReaders/PVFoamReader/vtkPVFoam/vtkPVFoamLagrangianFields.H
applications/utilities/postProcessing/graphics/PVReaders/PVFoamReader/vtkPVFoam/vtkPVFoamPatchField.H
applications/utilities/postProcessing/graphics/PVReaders/PVFoamReader/vtkPVFoam/vtkPVFoamPointFields.H
applications/utilities/postProcessing/graphics/PVReaders/PVFoamReader/vtkPVFoam/vtkPVFoamUpdateInfoFields.H
applications/utilities/postProcessing/graphics/PVReaders/PVFoamReader/vtkPVFoam/vtkPVFoamUtils.C
applications/utilities/postProcessing/graphics/PVReaders/PVFoamReader/vtkPVFoam/vtkPVFoamVolFields.H