OpenFOAM: patchWriter Class Reference
patchWriter Class Reference
Write patch fields.
Public Member Functions
patchWriter (const vtkMesh &, const bool binary, const bool nearCellValue, const fileName &, const labelList &patchIDs)
Construct from components.
std::ofstream & os ()
label nPoints () const
label nFaces () const
void writePatchIDs ()
Write cellIDs.
template<class Type >
void write (const UPtrList< const GeometricField< Type, fvPatchField, volMesh >> &)
Write volFields.
template<class Type >
void write (const UPtrList< const GeometricField< Type, pointPatchField, pointMesh > > &)
Write pointFields.
template<class Type >
void write (const PrimitivePatchInterpolation< primitivePatch > &, const UPtrList< const GeometricField< Type, fvPatchField, volMesh >> &)
Interpolate and write volFields.
Detailed Description
Write patch fields.
Source files
patchWriter.H
patchWriter.C
patchWriterTemplates.C
Definition at line 59 of file patchWriter.H.
Constructor & Destructor Documentation
patchWriter()
patchWriter (const vtkMesh & , const bool binary, const bool nearCellValue, const fileName & , const labelList & patchIDs)
Construct from components.
Member Function Documentation
os()
std::ofstream& os () inline
Definition at line 94 of file patchWriter.H.
nPoints()
label nPoints () const inline
Definition at line 99 of file patchWriter.H.
nFaces()
label nFaces () const inline
Definition at line 104 of file patchWriter.H.
References patchWriter::write(), and patchWriter::writePatchIDs().
writePatchIDs()
void writePatchIDs ()
Write cellIDs.
Referenced by patchWriter::nFaces().
write() [1/3]
void write (const UPtrList< const GeometricField< Type, fvPatchField, volMesh >> &)
Write volFields.
Referenced by patchWriter::nFaces().
write() [2/3]
void write (const UPtrList< const GeometricField< Type, pointPatchField, pointMesh > > &)
Write pointFields.
write() [3/3]
void write (const PrimitivePatchInterpolation< primitivePatch > & , const UPtrList< const GeometricField< Type, fvPatchField, volMesh >> &)
Interpolate and write volFields.
The documentation for this class was generated from the following file:
applications/utilities/postProcessing/dataConversion/foamToVTK/foamToVTK/patchWriter.H