OpenFOAM: adjointOutletVelocityFvPatchVectorField Class Reference
adjointOutletVelocityFvPatchVectorField Class Reference
Public Member Functions
TypeName ("adjointOutletVelocity")
Runtime type information.
adjointOutletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
adjointOutletVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
adjointOutletVelocityFvPatchVectorField (const adjointOutletVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given adjointOutletVelocityFvPatchVectorField.
virtual tmp< fvPatchVectorField > clone () const
Construct and return a clone.
adjointOutletVelocityFvPatchVectorField (const adjointOutletVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Detailed Description
Source files
adjointOutletVelocityFvPatchVectorField.H
adjointOutletVelocityFvPatchVectorField.C
Definition at line 47 of file adjointOutletVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
adjointOutletVelocityFvPatchVectorField() [1/4]
adjointOutletVelocityFvPatchVectorField (const fvPatch & , const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
Referenced by adjointOutletVelocityFvPatchVectorField::clone().
adjointOutletVelocityFvPatchVectorField() [2/4]
adjointOutletVelocityFvPatchVectorField (const fvPatch & , const DimensionedField< vector, volMesh > & , const dictionary &)
Construct from patch, internal field and dictionary.
adjointOutletVelocityFvPatchVectorField() [3/4]
adjointOutletVelocityFvPatchVectorField (const adjointOutletVelocityFvPatchVectorField & , const fvPatch & , const DimensionedField< vector, volMesh > & , const fvPatchFieldMapper &)
Construct by mapping given adjointOutletVelocityFvPatchVectorField.
onto a new patch
adjointOutletVelocityFvPatchVectorField() [4/4]
adjointOutletVelocityFvPatchVectorField (const adjointOutletVelocityFvPatchVectorField & , const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
Member Function Documentation
TypeName()
TypeName ("adjointOutletVelocity")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchVectorField> clone () const inline virtual
Construct and return a clone.
Definition at line 86 of file adjointOutletVelocityFvPatchVectorField.H.
References adjointOutletVelocityFvPatchVectorField::adjointOutletVelocityFvPatchVectorField().
clone() [2/2]
virtual tmp<fvPatchVectorField> clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 103 of file adjointOutletVelocityFvPatchVectorField.H.
References adjointOutletVelocityFvPatchVectorField::adjointOutletVelocityFvPatchVectorField(), adjointOutletVelocityFvPatchVectorField::updateCoeffs(), and adjointOutletVelocityFvPatchVectorField::write().
updateCoeffs()
virtual void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Referenced by adjointOutletVelocityFvPatchVectorField::clone().
write()
virtual void write (Ostream &) const virtual
Write.
Referenced by adjointOutletVelocityFvPatchVectorField::clone().
The documentation for this class was generated from the following file:
applications/solvers/incompressible/adjointShapeOptimizationFoam/adjointOutletVelocity/adjointOutletVelocityFvPatchVectorField.H