OpenFOAM: adjointOutletPressureFvPatchScalarField Class Reference
adjointOutletPressureFvPatchScalarField Class Reference
Public Member Functions
TypeName ("adjointOutletPressure")
Runtime type information.
adjointOutletPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
adjointOutletPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
adjointOutletPressureFvPatchScalarField (const adjointOutletPressureFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given adjointOutletPressureFvPatchScalarField.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
adjointOutletPressureFvPatchScalarField (const adjointOutletPressureFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Detailed Description
Source files
adjointOutletPressureFvPatchScalarField.H
adjointOutletPressureFvPatchScalarField.C
Definition at line 47 of file adjointOutletPressureFvPatchScalarField.H.
Constructor & Destructor Documentation
adjointOutletPressureFvPatchScalarField() [1/4]
adjointOutletPressureFvPatchScalarField (const fvPatch & , const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
Referenced by adjointOutletPressureFvPatchScalarField::clone().
adjointOutletPressureFvPatchScalarField() [2/4]
adjointOutletPressureFvPatchScalarField (const fvPatch & , const DimensionedField< scalar, volMesh > & , const dictionary &)
Construct from patch, internal field and dictionary.
adjointOutletPressureFvPatchScalarField() [3/4]
adjointOutletPressureFvPatchScalarField (const adjointOutletPressureFvPatchScalarField & , const fvPatch & , const DimensionedField< scalar, volMesh > & , const fvPatchFieldMapper &)
Construct by mapping given adjointOutletPressureFvPatchScalarField.
onto a new patch
adjointOutletPressureFvPatchScalarField() [4/4]
adjointOutletPressureFvPatchScalarField (const adjointOutletPressureFvPatchScalarField & , const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
Member Function Documentation
TypeName()
TypeName ("adjointOutletPressure")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 86 of file adjointOutletPressureFvPatchScalarField.H.
References adjointOutletPressureFvPatchScalarField::adjointOutletPressureFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 103 of file adjointOutletPressureFvPatchScalarField.H.
References adjointOutletPressureFvPatchScalarField::adjointOutletPressureFvPatchScalarField(), adjointOutletPressureFvPatchScalarField::updateCoeffs(), and adjointOutletPressureFvPatchScalarField::write().
updateCoeffs()
virtual void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Referenced by adjointOutletPressureFvPatchScalarField::clone().
write()
virtual void write (Ostream &) const virtual
Write.
Referenced by adjointOutletPressureFvPatchScalarField::clone().
The documentation for this class was generated from the following file:
applications/solvers/incompressible/adjointShapeOptimizationFoam/adjointOutletPressure/adjointOutletPressureFvPatchScalarField.H