OpenFOAM: transport Class Reference
transport Class Reference
Simple transport model for Xi based on Gulders correlation with a linear correction function to give a plausible profile for Xi. See report TR/HGW/10 for details on the Weller two equations model. See XiModel.H for more details on flame wrinkling modelling.
Public Member Functions
TypeName ("transport")
Runtime type information.
transport (const dictionary &XiProperties, const psiuReactionThermo &thermo, const compressible::RASModel &turbulence, const volScalarField &Su, const volScalarField &rho, const volScalarField &b, const surfaceScalarField &phi)
Construct from components.
virtual ~transport ()
Destructor.
virtual tmp< volScalarField > Db () const
Return the flame diffusivity.
virtual void addXi (multivariateSurfaceInterpolationScheme< scalar >::fieldTable &fields)
Add Xi to the multivariateSurfaceInterpolationScheme table.
virtual void correct ()
Correct the flame-wrinking Xi.
virtual void correct (const fv::convectionScheme< scalar > &mvConvection)
Correct the flame-wrinking Xi using the given convection scheme.
virtual bool read (const dictionary &XiProperties)
Update properties from given dictionary.
virtual void writeFields ()
Write fields of the XiEq model.
Public Member Functions inherited from XiModel
TypeName ("XiModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, XiModel, dictionary,(const dictionary &XiProperties, const psiuReactionThermo &thermo, const compressible::RASModel &turbulence, const volScalarField &Su, const volScalarField &rho, const volScalarField &b, const surfaceScalarField &phi),(XiProperties, thermo, turbulence, Su, rho, b, phi))
XiModel (const dictionary &XiProperties, const psiuReactionThermo &thermo, const compressible::RASModel &turbulence, const volScalarField &Su, const volScalarField &rho, const volScalarField &b, const surfaceScalarField &phi)
Construct from components.
virtual ~XiModel ()
Destructor.
virtual const volScalarField & Xi () const
Return the flame-wrinking Xi.
Additional Inherited Members
Static Public Member Functions inherited from XiModel
static autoPtr< XiModel > New (const dictionary &XiProperties, const psiuReactionThermo &thermo, const compressible::RASModel &turbulence, const volScalarField &Su, const volScalarField &rho, const volScalarField &b, const surfaceScalarField &phi)
Return a reference to the selected Xi model.
Protected Attributes inherited from XiModel
dictionary XiModelCoeffs_
const psiuReactionThermo & thermo_
const compressible::RASModel & turbulence_
const volScalarField & Su_
const volScalarField & rho_
const volScalarField & b_
const surfaceScalarField & phi_
volScalarField Xi_
Flame wrinking field.
Detailed Description
Simple transport model for Xi based on Gulders correlation with a linear correction function to give a plausible profile for Xi. See report TR/HGW/10 for details on the Weller two equations model. See XiModel.H for more details on flame wrinkling modelling.
Source files
transport.H
transport.C
Definition at line 55 of file transport.H.
Constructor & Destructor Documentation
transport()
transport (const dictionary & XiProperties, const psiuReactionThermo & thermo, const compressible::RASModel & turbulence, const volScalarField & Su, const volScalarField & rho, const volScalarField & b, const surfaceScalarField & phi)
Construct from components.
~transport()
virtual ~transport () virtual
Destructor.
Member Function Documentation
TypeName()
TypeName ("transport")
Runtime type information.
Db()
virtual tmp<volScalarField> Db () const virtual
Return the flame diffusivity.
Reimplemented from XiModel.
addXi()
virtual void addXi (multivariateSurfaceInterpolationScheme< scalar >::fieldTable & fields) inline virtual
Add Xi to the multivariateSurfaceInterpolationScheme table.
Reimplemented from XiModel.
Definition at line 108 of file transport.H.
References multivariateSurfaceInterpolationScheme< Type >::fieldTable::add(), and XiModel::Xi_.
correct() [1/2]
virtual void correct () inline virtual
Correct the flame-wrinking Xi.
Implements XiModel.
Definition at line 116 of file transport.H.
References mvConvection(), NotImplemented, and transport::read().
correct() [2/2]
virtual void correct (const fv::convectionScheme< scalar > & mvConvection) virtual
Correct the flame-wrinking Xi using the given convection scheme.
Reimplemented from XiModel.
read()
virtual bool read (const dictionary & XiProperties) virtual
Update properties from given dictionary.
Implements XiModel.
Referenced by transport::correct().
writeFields()
virtual void writeFields () inline virtual
Write fields of the XiEq model.
Implements XiModel.
Definition at line 128 of file transport.H.
The documentation for this class was generated from the following file:
applications/solvers/combustion/PDRFoam/XiModels/transport/transport.H