OpenFOAM: incompressibleTwoPhaseInteractingMixture Class Reference
incompressibleTwoPhaseInteractingMixture Class Reference
A two-phase incompressible transportModel for interacting phases requiring the direct evaluation of the mixture viscosity, e.g. activated sludge or slurry.
Public Member Functions
TypeName ("incompressibleTwoPhaseInteractingMixture")
incompressibleTwoPhaseInteractingMixture (const volVectorField &U, const surfaceScalarField &phi)
Construct from components.
virtual ~incompressibleTwoPhaseInteractingMixture ()
Destructor.
const mixtureViscosityModel & muModel () const
Return const-access to the mixture viscosityModel.
const viscosityModel & nucModel () const
Return const-access to the continuous-phase viscosityModel.
const dimensionedScalar & rhod () const
Return const-access to the dispersed-phase density.
const dimensionedScalar & rhoc () const
Return const-access to continuous-phase density.
const dimensionedScalar & dd () const
Return the diameter of the dispersed-phase particles.
scalar alphaMax () const
Optional maximum phase-fraction (e.g. packing limit)
const volVectorField & U () const
Return const-access to the mixture velocity.
tmp< volScalarField > mu () const
Return the dynamic mixture viscosity.
virtual tmp< scalarField > mu (const label patchi) const
Return the dynamic mixture viscosity for patch.
virtual tmp< volScalarField > rho () const
Return the mixture density.
virtual tmp< scalarField > rho (const label patchi) const
Return the mixture density for patch.
virtual tmp< volScalarField > nu () const
Return the mixture viscosity.
virtual tmp< scalarField > nu (const label patchi) const
Return the mixture viscosity for patch.
virtual void correct ()
Correct the laminar viscosity.
virtual bool read ()
Read base transportProperties dictionary.
Public Member Functions inherited from IOdictionary
TypeName ("dictionary")
IOdictionary (const IOobject &)
Construct given an IOobject.
IOdictionary (const IOobject &, const dictionary &)
Construct given an IOobject and dictionary.
IOdictionary (const IOobject &, Istream &)
Construct given an IOobject and Istream.
virtual ~IOdictionary ()
Destructor.
const word & name () const
Name function is needed to disambiguate those inherited.
bool readData (Istream &)
ReadData function required for regIOobject read operation.
bool writeData (Ostream &) const
WriteData function required for regIOobject write operation.
void operator= (const IOdictionary &)
Assignment of other IOdictionary's entries to this IOdictionary.
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, transferring registry registration to copy.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Construct as copy with new name, transfering registry registration.
regIOobject (const IOobject &, const regIOobject &)
Construct as copy with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
virtual void rename (const word &newName)
Rename.
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType) const
Write using given format, version and compression.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Public Member Functions inherited from dictionary
ClassName ("dictionary")
dictionary ()
Construct top-level dictionary null.
dictionary (const fileName &name)
Construct top-level empty dictionary with given name.
dictionary (const fileName &name, const dictionary &parentDict, Istream &)
Construct given the entry name, parent dictionary and Istream,.
dictionary (Istream &)
Construct top-level dictionary from Istream,.
dictionary (Istream &, const bool keepHeader)
Construct top-level dictionary from Istream,.
dictionary (const dictionary &parentDict, const dictionary &)
Construct as copy given the parent dictionary.
dictionary (const dictionary &)
Construct top-level dictionary as copy.
dictionary (const dictionary *)
Construct top-level dictionary as copy from pointer to dictionary.
dictionary (const dictionary &parentDict, const Xfer< dictionary > &)
Construct by transferring parameter contents given parent dictionary.
dictionary (const Xfer< dictionary > &)
Construct top-level dictionary by transferring parameter contents.
autoPtr< dictionary > clone () const
Construct and return clone.
virtual ~dictionary ()
Destructor.
const dictionary & parent () const
Return the parent dictionary.
const dictionary & topDict () const
Return the top of the tree.
label startLineNumber () const
Return line number of first token in dictionary.
label endLineNumber () const
Return line number of last token in dictionary.
SHA1Digest digest () const
Return the SHA1 digest of the dictionary contents.
tokenList tokens () const
Return the dictionary as a list of tokens.
bool found (const word &, bool recursive=false, bool patternMatch=true) const
Search dictionary for given keyword.
const entry * lookupEntryPtr (const word &, bool recursive, bool patternMatch) const
Find and return an entry data stream pointer if present.
entry * lookupEntryPtr (const word &, bool recursive, bool patternMatch)
Find and return an entry data stream pointer for manipulation.
const entry & lookupEntry (const word &, bool recursive, bool patternMatch) const
Find and return an entry data stream if present otherwise error.
ITstream & lookup (const word &, bool recursive=false, bool patternMatch=true) const
Find and return an entry data stream.
template<class T >
T lookupOrDefault (const word &, const T &, bool recursive=false, bool patternMatch=true) const
Find and return a T,.
template<class T >
T lookupOrAddDefault (const word &, const T &, bool recursive=false, bool patternMatch=true)
Find and return a T, if not found return the given.
template<class T >
bool readIfPresent (const word &, T &, bool recursive=false, bool patternMatch=true) const
Find an entry if present, and assign to T.
const entry * lookupScopedEntryPtr (const word &, bool recursive, bool patternMatch) const
Find and return an entry data stream pointer if present.
bool isDict (const word &) const
Check if entry is a sub-dictionary.
const dictionary * subDictPtr (const word &) const
Find and return a sub-dictionary pointer if present.
const dictionary & subDict (const word &) const
Find and return a sub-dictionary.
dictionary & subDict (const word &)
Find and return a sub-dictionary for manipulation.
dictionary subOrEmptyDict (const word &, const bool mustRead=false) const
Find and return a sub-dictionary as a copy, or.
wordList toc () const
Return the table of contents.
wordList sortedToc () const
Return the sorted table of contents.
List< keyType > keys (bool patterns=false) const
Return the list of available keys or patterns.
bool substituteKeyword (const word &keyword)
Substitute the given keyword prepended by '$' with the.
bool substituteScopedKeyword (const word &keyword)
Substitute the given scoped keyword prepended by '$' with the.
bool add (entry *, bool mergeEntry=false)
Add a new entry.
void add (const entry &, bool mergeEntry=false)
Add an entry.
void add (const keyType &, const word &, bool overwrite=false)
Add a word entry.
void add (const keyType &, const string &, bool overwrite=false)
Add a string entry.
void add (const keyType &, const label, bool overwrite=false)
Add a label entry.
void add (const keyType &, const scalar, bool overwrite=false)
Add a scalar entry.
void add (const keyType &, const dictionary &, bool mergeEntry=false)
Add a dictionary entry.
template<class T >
void add (const keyType &, const T &, bool overwrite=false)
Add a T entry.
void set (entry *)
Assign a new entry, overwrite any existing entry.
void set (const entry &)
Assign a new entry, overwrite any existing entry.
void set (const keyType &, const dictionary &)
Assign a dictionary entry, overwrite any existing entry.
template<class T >
void set (const keyType &, const T &)
Assign a T entry, overwrite any existing entry.
bool remove (const word &)
Remove an entry specified by keyword.
bool changeKeyword (const keyType &oldKeyword, const keyType &newKeyword, bool forceOverwrite=false)
Change the keyword for an entry,.
bool merge (const dictionary &)
Merge entries from the given dictionary.
void clear ()
Clear the dictionary.
void transfer (dictionary &)
Transfer the contents of the argument and annul the argument.
Xfer< dictionary > xfer ()
Transfer contents to the Xfer container.
bool read (Istream &)
Read dictionary from Istream.
bool read (Istream &, const bool keepHeader)
Read dictionary from Istream, optionally keeping the header.
void write (Ostream &, const bool subDict=true) const
Write dictionary, normally with sub-dictionary formatting.
ITstream & operator[] (const word &) const
Find and return entry.
void operator= (const dictionary &)
void operator+= (const dictionary &)
Include entries from the given dictionary.
void operator|= (const dictionary &)
Conditionally include entries from the given dictionary.
void operator<<= (const dictionary &)
Unconditionally include entries from the given dictionary.
Public Member Functions inherited from dictionaryName
dictionaryName ()
Construct dictionaryName null.
dictionaryName (const fileName &name)
Construct dictionaryName as copy of the given fileName.
const fileName & name () const
Return the dictionary name.
fileName & name ()
Return the dictionary name.
const word dictName () const
Return the local dictionary name (final part of scoped name)
Public Member Functions inherited from ILList< LListBase, T >
ILList ()
Null construct.
ILList (T *a)
Construct given initial T.
ILList (Istream &)
Construct from Istream.
ILList (const ILList< LListBase, T > &)
Construct as copy.
template<class CloneArg >
ILList (const ILList< LListBase, T > &lst, const CloneArg &cloneArg)
Copy constructor with additional argument for clone.
template<class INew >
ILList (Istream &, const INew &)
Construct from Istream using given Istream constructor class.
~ILList ()
Destructor.
bool eraseHead ()
Remove the head element specified from the list and delete it.
bool erase (T *p)
Remove the specified element from the list and delete it.
void clear ()
Clear the contents of the list.
void transfer (ILList< LListBase, T > &)
Transfer the contents of the argument into this List.
void operator= (const ILList< LListBase, T > &)
Assignment operator.
Public Member Functions inherited from UILList< LListBase, T >
UILList ()
Null construct.
UILList (T *a)
Construct given initial T.
UILList (const UILList< LListBase, T > &)
Construct as copy.
T * first ()
Return the first entry.
const T * first () const
Return the first entry.
T * last ()
Return the last entry.
const T * last () const
Return the last entry.
T * removeHead ()
Remove and return head.
T * remove (T *p)
Remove and return element.
T * remove (iterator &it)
Remove and return specified by iterator.
void operator= (const UILList< LListBase, T > &)
iterator begin ()
const iterator & end ()
const_iterator cbegin () const
const const_iterator & cend () const
const_iterator begin () const
const const_iterator & end () const
const_reverse_iterator crbegin () const
const const_reverse_iterator & crend () const
const_reverse_iterator rbegin () const
const const_reverse_iterator & rend () const
bool operator== (const UILList< LListBase, T > &) const
Equality operation on ULists of the same type.
bool operator!= (const UILList< LListBase, T > &) const
The opposite of the equality operation. Takes linear time.
Public Member Functions inherited from compressibleTransportModel
TypeName ("compressibleTransportModel")
Runtime type information.
compressibleTransportModel ()
Construct from components.
virtual ~compressibleTransportModel ()
Destructor.
Public Member Functions inherited from twoPhaseMixture
twoPhaseMixture (const fvMesh &mesh, const dictionary &dict)
Construct from components.
~twoPhaseMixture ()
Destructor.
const word & phase1Name () const
const word & phase2Name () const
const volScalarField & alpha1 () const
Return the phase-fraction of phase 1.
volScalarField & alpha1 ()
Return the phase-fraction of phase 1.
const volScalarField & alpha2 () const
Return the phase-fraction of phase 2.
volScalarField & alpha2 ()
Return the phase-fraction of phase 2.
Protected Attributes
autoPtr< mixtureViscosityModel > muModel_
autoPtr< viscosityModel > nucModel_
dimensionedScalar rhod_
dimensionedScalar rhoc_
dimensionedScalar dd_
Optional diameter of the dispersed phase particles.
scalar alphaMax_
Optional maximum dispersed phase-fraction (e.g. packing limit)
const volVectorField & U_
const surfaceScalarField & phi_
volScalarField mu_
Protected Attributes inherited from twoPhaseMixture
word phase1Name_
word phase2Name_
volScalarField alpha1_
volScalarField alpha2_
Additional Inherited Members
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Public Types inherited from UILList< LListBase, T >
typedef T value_type
Type of values the DLList contains.
typedef T & reference
Type that can be used for storing into DLList::value_type.
typedef const T & const_reference
Type that can be used for storing into constant.
typedef label size_type
The type that can represent the size of a DLList.
typedef LListBase::iterator LListBase_iterator
typedef LListBase::const_iterator LListBase_const_iterator
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Static Public Member Functions inherited from dictionary
static autoPtr< dictionary > New (Istream &)
Construct top-level dictionary on freestore from Istream.
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Static Public Attributes inherited from dictionary
static const dictionary null
Null dictionary.
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
A two-phase incompressible transportModel for interacting phases requiring the direct evaluation of the mixture viscosity, e.g. activated sludge or slurry.
Source files
incompressibleTwoPhaseInteractingMixture.H
incompressibleTwoPhaseInteractingMixture.C
Definition at line 55 of file incompressibleTwoPhaseInteractingMixture.H.
Constructor & Destructor Documentation
incompressibleTwoPhaseInteractingMixture()
incompressibleTwoPhaseInteractingMixture (const volVectorField & U, const surfaceScalarField & phi)
Construct from components.
~incompressibleTwoPhaseInteractingMixture()
virtual ~incompressibleTwoPhaseInteractingMixture () inline virtual
Destructor.
Definition at line 99 of file incompressibleTwoPhaseInteractingMixture.H.
Member Function Documentation
TypeName()
TypeName ("incompressibleTwoPhaseInteractingMixture")
muModel()
const mixtureViscosityModel& muModel () const inline
Return const-access to the mixture viscosityModel.
Definition at line 106 of file incompressibleTwoPhaseInteractingMixture.H.
References incompressibleTwoPhaseInteractingMixture::muModel_.
nucModel()
const viscosityModel& nucModel () const inline
Return const-access to the continuous-phase viscosityModel.
Definition at line 112 of file incompressibleTwoPhaseInteractingMixture.H.
References incompressibleTwoPhaseInteractingMixture::nucModel_.
rhod()
const dimensionedScalar& rhod () const inline
Return const-access to the dispersed-phase density.
Definition at line 118 of file incompressibleTwoPhaseInteractingMixture.H.
References incompressibleTwoPhaseInteractingMixture::rhod_.
rhoc()
const dimensionedScalar& rhoc () const inline
Return const-access to continuous-phase density.
Definition at line 124 of file incompressibleTwoPhaseInteractingMixture.H.
References incompressibleTwoPhaseInteractingMixture::rhoc_.
dd()
const dimensionedScalar& dd () const inline
Return the diameter of the dispersed-phase particles.
Definition at line 130 of file incompressibleTwoPhaseInteractingMixture.H.
References incompressibleTwoPhaseInteractingMixture::alphaMax(), incompressibleTwoPhaseInteractingMixture::alphaMax_, and incompressibleTwoPhaseInteractingMixture::dd_.
alphaMax()
scalar alphaMax () const inline
Optional maximum phase-fraction (e.g. packing limit)
Defaults to 1
Definition at line 137 of file incompressibleTwoPhaseInteractingMixture.H.
Referenced by incompressibleTwoPhaseInteractingMixture::dd().
U()
const volVectorField& U () const inline
Return const-access to the mixture velocity.
Definition at line 143 of file incompressibleTwoPhaseInteractingMixture.H.
References incompressibleTwoPhaseInteractingMixture::U_.
mu() [1/2]
tmp<volScalarField> mu () const inline virtual
Return the dynamic mixture viscosity.
Implements compressibleTransportModel.
Definition at line 149 of file incompressibleTwoPhaseInteractingMixture.H.
References incompressibleTwoPhaseInteractingMixture::mu_.
mu() [2/2]
virtual tmp<scalarField> mu (const label patchi) const inline virtual
Return the dynamic mixture viscosity for patch.
Implements compressibleTransportModel.
Definition at line 155 of file incompressibleTwoPhaseInteractingMixture.H.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), and patchi.
rho() [1/2]
virtual tmp<volScalarField> rho () const inline virtual
Return the mixture density.
Definition at line 161 of file incompressibleTwoPhaseInteractingMixture.H.
References twoPhaseMixture::alpha1_, twoPhaseMixture::alpha2_, and incompressibleTwoPhaseInteractingMixture::rhoc_.
Referenced by incompressibleTwoPhaseInteractingMixture::nu().
rho() [2/2]
virtual tmp<scalarField> rho (const label patchi) const inline virtual
Return the mixture density for patch.
Definition at line 167 of file incompressibleTwoPhaseInteractingMixture.H.
References twoPhaseMixture::alpha1_, twoPhaseMixture::alpha2_, GeometricField< Type, PatchField, GeoMesh >::boundaryField(), patchi, and dimensioned< Type >::value().
nu() [1/2]
virtual tmp<volScalarField> nu () const inline virtual
Return the mixture viscosity.
Implements compressibleTransportModel.
Definition at line 175 of file incompressibleTwoPhaseInteractingMixture.H.
References incompressibleTwoPhaseInteractingMixture::rho().
nu() [2/2]
virtual tmp<scalarField> nu (const label patchi) const inline virtual
Return the mixture viscosity for patch.
Implements compressibleTransportModel.
Definition at line 181 of file incompressibleTwoPhaseInteractingMixture.H.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), patchi, and incompressibleTwoPhaseInteractingMixture::rho().
correct()
virtual void correct () inline virtual
Correct the laminar viscosity.
Definition at line 187 of file incompressibleTwoPhaseInteractingMixture.H.
References incompressibleTwoPhaseInteractingMixture::read().
read()
virtual bool read () virtual
Read base transportProperties dictionary.
Reimplemented from regIOobject.
Referenced by incompressibleTwoPhaseInteractingMixture::correct().
Member Data Documentation
muModel_
autoPtr<mixtureViscosityModel> muModel_ protected
Definition at line 65 of file incompressibleTwoPhaseInteractingMixture.H.
Referenced by incompressibleTwoPhaseInteractingMixture::muModel().
nucModel_
autoPtr<viscosityModel> nucModel_ protected
Definition at line 66 of file incompressibleTwoPhaseInteractingMixture.H.
Referenced by incompressibleTwoPhaseInteractingMixture::nucModel().
rhod_
dimensionedScalar rhod_ protected
Definition at line 68 of file incompressibleTwoPhaseInteractingMixture.H.
Referenced by incompressibleTwoPhaseInteractingMixture::rhod().
rhoc_
dimensionedScalar rhoc_ protected
Definition at line 69 of file incompressibleTwoPhaseInteractingMixture.H.
Referenced by incompressibleTwoPhaseInteractingMixture::rho(), and incompressibleTwoPhaseInteractingMixture::rhoc().
dd_
dimensionedScalar dd_ protected
Optional diameter of the dispersed phase particles.
Definition at line 72 of file incompressibleTwoPhaseInteractingMixture.H.
Referenced by incompressibleTwoPhaseInteractingMixture::dd().
alphaMax_
scalar alphaMax_ protected
Optional maximum dispersed phase-fraction (e.g. packing limit)
Definition at line 75 of file incompressibleTwoPhaseInteractingMixture.H.
Referenced by incompressibleTwoPhaseInteractingMixture::dd().
U_
const volVectorField& U_ protected
Definition at line 77 of file incompressibleTwoPhaseInteractingMixture.H.
Referenced by incompressibleTwoPhaseInteractingMixture::U().
phi_
const surfaceScalarField& phi_ protected
Definition at line 78 of file incompressibleTwoPhaseInteractingMixture.H.
mu_
volScalarField mu_ protected
Definition at line 80 of file incompressibleTwoPhaseInteractingMixture.H.
Referenced by incompressibleTwoPhaseInteractingMixture::mu().
The documentation for this class was generated from the following file:
applications/solvers/multiphase/driftFluxFoam/incompressibleTwoPhaseInteractingMixture/incompressibleTwoPhaseInteractingMixture.H