OpenFOAM: threePhaseInterfaceProperties Class Reference
threePhaseInterfaceProperties Class Reference
Properties to aid interFoam : 1. Correct the alpha boundary condition for dynamic contact angle. 2. Calculate interface curvature.
Public Member Functions
threePhaseInterfaceProperties (const incompressibleThreePhaseMixture &mixture)
Construct from volume fraction field alpha and IOdictionary.
scalar cAlpha () const
const dimensionedScalar & deltaN () const
const surfaceScalarField & nHatf () const
const volScalarField & K () const
tmp< volScalarField > sigma () const
tmp< volScalarField > sigmaK () const
tmp< surfaceScalarField > surfaceTensionForce () const
tmp< volScalarField > nearInterface () const
Indicator of the proximity of the interface.
void correct ()
Static Public Attributes
static const scalar convertToRad
Conversion factor for degrees into radians.
Detailed Description
Properties to aid interFoam : 1. Correct the alpha boundary condition for dynamic contact angle. 2. Calculate interface curvature.
Source files
threePhaseInterfaceProperties.H
threePhaseInterfaceProperties.C
Definition at line 51 of file threePhaseInterfaceProperties.H.
Constructor & Destructor Documentation
threePhaseInterfaceProperties()
threePhaseInterfaceProperties (const incompressibleThreePhaseMixture & mixture)
Construct from volume fraction field alpha and IOdictionary.
Member Function Documentation
cAlpha()
scalar cAlpha () const inline
Definition at line 108 of file threePhaseInterfaceProperties.H.
deltaN()
const dimensionedScalar& deltaN () const inline
Definition at line 113 of file threePhaseInterfaceProperties.H.
nHatf()
const surfaceScalarField& nHatf () const inline
Definition at line 118 of file threePhaseInterfaceProperties.H.
K()
const volScalarField& K () const inline
Definition at line 123 of file threePhaseInterfaceProperties.H.
sigma()
tmp<volScalarField> sigma () const inline
Definition at line 128 of file threePhaseInterfaceProperties.H.
References incompressibleThreePhaseMixture::alpha2(), incompressibleThreePhaseMixture::alpha3(), and Foam::max().
Referenced by threePhaseInterfaceProperties::sigmaK().
sigmaK()
tmp<volScalarField> sigmaK () const inline
Definition at line 138 of file threePhaseInterfaceProperties.H.
References threePhaseInterfaceProperties::nearInterface(), threePhaseInterfaceProperties::sigma(), and threePhaseInterfaceProperties::surfaceTensionForce().
surfaceTensionForce()
tmp<surfaceScalarField> surfaceTensionForce () const
Referenced by threePhaseInterfaceProperties::sigmaK().
nearInterface()
tmp<volScalarField> nearInterface () const
Indicator of the proximity of the interface.
Field values are 1 near and 0 away for the interface.
Referenced by threePhaseInterfaceProperties::sigmaK().
correct()
void correct () inline
Definition at line 149 of file threePhaseInterfaceProperties.H.
Referenced by immiscibleIncompressibleThreePhaseMixture::correct().
Member Data Documentation
convertToRad
const scalar convertToRad static
Conversion factor for degrees into radians.
Definition at line 94 of file threePhaseInterfaceProperties.H.
The documentation for this class was generated from the following file:
applications/solvers/multiphase/interFoam/interMixingFoam/threePhaseInterfaceProperties/threePhaseInterfaceProperties.H