OpenFOAM: phaseModel::iNew Class Reference
phaseModel::iNew Class Reference
Return a pointer to a new phaseModel created on freestore.
Public Member Functions
iNew (const volScalarField &p, const volScalarField &T)
autoPtr< phaseModel > operator() (Istream &is) const
iNew (const fvMesh &mesh)
autoPtr< phaseModel > operator() (Istream &is) const
iNew (const phaseSystem &fluid)
autoPtr< phaseModel > operator() (Istream &is) const
Detailed Description
Return a pointer to a new phaseModel created on freestore.
Return a pointer to a new phase created on freestore.
from Istream
Definition at line 83 of file phaseModel.H.
Constructor & Destructor Documentation
iNew() [1/3]
iNew (const volScalarField & p, const volScalarField & T) inline
Definition at line 91 of file phaseModel.H.
iNew() [2/3]
iNew (const fvMesh & mesh) inline
Definition at line 114 of file phaseModel.H.
iNew() [3/3]
iNew (const phaseSystem & fluid) inline
Definition at line 135 of file phaseModel.H.
Member Function Documentation
operator()() [1/3]
autoPtr<phaseModel> operator() (Istream & is) const inline
Definition at line 100 of file phaseModel.H.
References phaseModel::phaseModel().
operator()() [2/3]
autoPtr<phaseModel> operator() (Istream & is) const inline
Definition at line 121 of file phaseModel.H.
References entry::keyword(), dictionary::null, phaseModel::phaseModel(), and phaseModel::~phaseModel().
operator()() [3/3]
autoPtr<phaseModel> operator() (Istream & is) const inline
Definition at line 143 of file phaseModel.H.
References phaseModel::alpha(), phaseModel::alphaEff(), phaseModel::alphaMax(), phaseModel::alphaPhi(), phaseModel::alphaRhoPhi(), phaseModel::compressible(), phaseModel::continuityError(), phaseModel::correct(), phaseModel::correctEnergyTransport(), phaseModel::correctKinematics(), phaseModel::correctThermo(), phaseModel::correctTurbulence(), phaseModel::d(), phaseModel::DbyA(), phaseModel::divU(), phaseModel::DUDt(), phaseModel::fluid(), phaseModel::heEqn(), phaseModel::index(), phaseModel::K(), phaseModel::kappa(), phaseModel::kappaEff(), phaseModel::keyword(), phaseModel::mu(), phaseModel::name(), phaseModel::New(), phaseModel::nu(), patchi, phaseModel::phi(), phaseModel::read(), phaseModel::residualAlpha(), phaseModel::rho(), phaseModel::thermo(), phaseModel::turbulence(), phaseModel::U(), phaseModel::UEqn(), phaseModel::Y(), phaseModel::YiEqn(), and phaseModel::~phaseModel().
The documentation for this class was generated from the following file:
applications/solvers/multiphase/compressibleMultiphaseInterFoam/multiphaseMixtureThermo/phaseModel/phaseModel.H