OpenFOAM: alphaContactAngleFvPatchScalarField::interfaceThetaProps Class Reference
alphaContactAngleFvPatchScalarField::interfaceThetaProps Class Reference
Public Member Functions
interfaceThetaProps ()
interfaceThetaProps (Istream &)
scalar theta0 (bool matched=true) const
Return the equilibrium contact angle theta0.
scalar uTheta () const
Return the dynamic contact angle velocity scale.
scalar thetaA (bool matched=true) const
Return the limiting advancing contact angle.
scalar thetaR (bool matched=true) const
Return the limiting receeding contact angle.
interfaceThetaProps ()
interfaceThetaProps (Istream &)
scalar theta0 (bool matched=true) const
Return the equilibrium contact angle theta0.
scalar uTheta () const
Return the dynamic contact angle velocity scale.
scalar thetaA (bool matched=true) const
Return the limiting advancing contact angle.
scalar thetaR (bool matched=true) const
Return the limiting receeding contact angle.
interfaceThetaProps ()
interfaceThetaProps (Istream &)
scalar theta0 (bool matched=true) const
Return the equilibrium contact angle theta0.
scalar uTheta () const
Return the dynamic contact angle velocity scale.
scalar thetaA (bool matched=true) const
Return the limiting advancing contact angle.
scalar thetaR (bool matched=true) const
Return the limiting receeding contact angle.
interfaceThetaProps ()
interfaceThetaProps (Istream &)
scalar theta0 (bool matched=true) const
Return the equilibrium contact angle theta0.
scalar uTheta () const
Return the dynamic contact angle velocity scale.
scalar thetaA (bool matched=true) const
Return the limiting advancing contact angle.
scalar thetaR (bool matched=true) const
Return the limiting receeding contact angle.
Friends
Istream & operator>> (Istream &, interfaceThetaProps &)
Ostream & operator<< (Ostream &, const interfaceThetaProps &)
Istream & operator>> (Istream &, interfaceThetaProps &)
Ostream & operator<< (Ostream &, const interfaceThetaProps &)
Istream & operator>> (Istream &, interfaceThetaProps &)
Ostream & operator<< (Ostream &, const interfaceThetaProps &)
Istream & operator>> (Istream &, interfaceThetaProps &)
Ostream & operator<< (Ostream &, const interfaceThetaProps &)
Detailed Description
Definition at line 56 of file alphaContactAngleFvPatchScalarField.H.
Constructor & Destructor Documentation
interfaceThetaProps() [1/8]
interfaceThetaProps () inline
Definition at line 74 of file alphaContactAngleFvPatchScalarField.H.
Referenced by alphaContactAngleFvPatchScalarField::interfaceThetaProps::interfaceThetaProps(), and alphaContactAngleFvPatchScalarField::interfaceThetaProps::thetaR().
interfaceThetaProps() [2/8]
interfaceThetaProps (Istream &)
interfaceThetaProps() [3/8]
interfaceThetaProps () inline
Definition at line 74 of file alphaContactAngleFvPatchScalarField.H.
References alphaContactAngleFvPatchScalarField::interfaceThetaProps::interfaceThetaProps().
interfaceThetaProps() [4/8]
interfaceThetaProps (Istream &)
interfaceThetaProps() [5/8]
interfaceThetaProps () inline
Definition at line 74 of file alphaContactAngleFvPatchScalarField.H.
References alphaContactAngleFvPatchScalarField::interfaceThetaProps::interfaceThetaProps().
interfaceThetaProps() [6/8]
interfaceThetaProps (Istream &)
interfaceThetaProps() [7/8]
interfaceThetaProps () inline
Definition at line 74 of file alphaContactAngleFvPatchScalarField.H.
References alphaContactAngleFvPatchScalarField::interfaceThetaProps::interfaceThetaProps().
interfaceThetaProps() [8/8]
interfaceThetaProps (Istream &)
Member Function Documentation
theta0() [1/4]
scalar theta0 (bool matched = true) const inline
Return the equilibrium contact angle theta0.
Definition at line 83 of file alphaContactAngleFvPatchScalarField.H.
uTheta() [1/4]
scalar uTheta () const inline
Return the dynamic contact angle velocity scale.
Definition at line 90 of file alphaContactAngleFvPatchScalarField.H.
thetaA() [1/4]
scalar thetaA (bool matched = true) const inline
Return the limiting advancing contact angle.
Definition at line 96 of file alphaContactAngleFvPatchScalarField.H.
thetaR() [1/4]
scalar thetaR (bool matched = true) const inline
Return the limiting receeding contact angle.
Definition at line 103 of file alphaContactAngleFvPatchScalarField.H.
References alphaContactAngleFvPatchScalarField::interfaceThetaProps::interfaceThetaProps(), alphaContactAngleFvPatchScalarField::interfaceThetaProps::operator<<, and alphaContactAngleFvPatchScalarField::interfaceThetaProps::operator>>.
theta0() [2/4]
scalar theta0 (bool matched = true) const inline
Return the equilibrium contact angle theta0.
Definition at line 83 of file alphaContactAngleFvPatchScalarField.H.
uTheta() [2/4]
scalar uTheta () const inline
Return the dynamic contact angle velocity scale.
Definition at line 90 of file alphaContactAngleFvPatchScalarField.H.
thetaA() [2/4]
scalar thetaA (bool matched = true) const inline
Return the limiting advancing contact angle.
Definition at line 96 of file alphaContactAngleFvPatchScalarField.H.
thetaR() [2/4]
scalar thetaR (bool matched = true) const inline
Return the limiting receeding contact angle.
Definition at line 103 of file alphaContactAngleFvPatchScalarField.H.
References alphaContactAngleFvPatchScalarField::interfaceThetaProps::interfaceThetaProps(), alphaContactAngleFvPatchScalarField::interfaceThetaProps::operator<<, and alphaContactAngleFvPatchScalarField::interfaceThetaProps::operator>>.
theta0() [3/4]
scalar theta0 (bool matched = true) const inline
Return the equilibrium contact angle theta0.
Definition at line 83 of file alphaContactAngleFvPatchScalarField.H.
uTheta() [3/4]
scalar uTheta () const inline
Return the dynamic contact angle velocity scale.
Definition at line 90 of file alphaContactAngleFvPatchScalarField.H.
thetaA() [3/4]
scalar thetaA (bool matched = true) const inline
Return the limiting advancing contact angle.
Definition at line 96 of file alphaContactAngleFvPatchScalarField.H.
thetaR() [3/4]
scalar thetaR (bool matched = true) const inline
Return the limiting receeding contact angle.
Definition at line 103 of file alphaContactAngleFvPatchScalarField.H.
References alphaContactAngleFvPatchScalarField::interfaceThetaProps::interfaceThetaProps(), alphaContactAngleFvPatchScalarField::interfaceThetaProps::operator<<, and alphaContactAngleFvPatchScalarField::interfaceThetaProps::operator>>.
theta0() [4/4]
scalar theta0 (bool matched = true) const inline
Return the equilibrium contact angle theta0.
Definition at line 83 of file alphaContactAngleFvPatchScalarField.H.
uTheta() [4/4]
scalar uTheta () const inline
Return the dynamic contact angle velocity scale.
Definition at line 90 of file alphaContactAngleFvPatchScalarField.H.
thetaA() [4/4]
scalar thetaA (bool matched = true) const inline
Return the limiting advancing contact angle.
Definition at line 96 of file alphaContactAngleFvPatchScalarField.H.
thetaR() [4/4]
scalar thetaR (bool matched = true) const inline
Return the limiting receeding contact angle.
Definition at line 103 of file alphaContactAngleFvPatchScalarField.H.
References alphaContactAngleFvPatchScalarField::interfaceThetaProps::interfaceThetaProps(), alphaContactAngleFvPatchScalarField::interfaceThetaProps::operator<<, and alphaContactAngleFvPatchScalarField::interfaceThetaProps::operator>>.
Friends And Related Function Documentation
operator>> [1/4]
Istream& operator>> (Istream & , interfaceThetaProps &) friend
Referenced by alphaContactAngleFvPatchScalarField::interfaceThetaProps::thetaR().
operator<< [1/4]
Ostream& operator<< (Ostream & , const interfaceThetaProps &) friend
Referenced by alphaContactAngleFvPatchScalarField::interfaceThetaProps::thetaR().
operator>> [2/4]
Istream& operator>> (Istream & , interfaceThetaProps &) friend
operator<< [2/4]
Ostream& operator<< (Ostream & , const interfaceThetaProps &) friend
operator>> [3/4]
Istream& operator>> (Istream & , interfaceThetaProps &) friend
operator<< [3/4]
Ostream& operator<< (Ostream & , const interfaceThetaProps &) friend
operator>> [4/4]
Istream& operator>> (Istream & , interfaceThetaProps &) friend
operator<< [4/4]
Ostream& operator<< (Ostream & , const interfaceThetaProps &) friend
The documentation for this class was generated from the following file:
applications/solvers/multiphase/compressibleMultiphaseInterFoam/multiphaseMixtureThermo/alphaContactAngle/alphaContactAngleFvPatchScalarField.H