OpenFOAM: phaseModel Class Reference
phaseModel Class Reference abstract
Single incompressible phase derived from the phase-fraction. Used as part of the multiPhaseMixture for interface-capturing multi-phase simulations.
Classes
class iNew
Return a pointer to a new phaseModel created on freestore.
Public Member Functions
phaseModel (const word &phaseName, const volScalarField &p, const volScalarField &T)
Construct from components.
autoPtr< phaseModel > clone () const
Return clone.
const word & name () const
const word & keyword () const
const rhoThermo & thermo () const
Return const-access to phase rhoThermo.
rhoThermo & thermo ()
Return access to phase rhoThermo.
const volScalarField & dgdt () const
Return const-access to phase divergence.
volScalarField & dgdt ()
Return access to phase divergence.
void correct ()
Correct the laminar viscosity.
phaseModel (const word &phaseName, const dictionary &phaseDict, const fvMesh &mesh)
autoPtr< phaseModel > clone () const
Return clone.
virtual ~phaseModel ()
Destructor.
const word & name () const
const word & keyword () const
tmp< volScalarField > d () const
const dimensionedScalar & nu () const
Return the laminar viscosity.
const dimensionedScalar & kappa () const
const dimensionedScalar & Cp () const
const dimensionedScalar & rho () const
const volVectorField & U () const
volVectorField & U ()
const volVectorField & DDtU () const
volVectorField & DDtU ()
const surfaceScalarField & phi () const
surfaceScalarField & phi ()
const surfaceScalarField & alphaPhi () const
surfaceScalarField & alphaPhi ()
void correct ()
Correct the phase properties.
bool read (const dictionary &phaseDict)
Read base transportProperties dictionary.
ClassName ("phaseModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, phaseModel, phaseSystem,(const phaseSystem &fluid, const word &phaseName, const label index),(fluid, phaseName, index))
phaseModel (const phaseSystem &fluid, const word &phaseName, const label index)
autoPtr< phaseModel > clone () const
Return clone.
virtual ~phaseModel ()
Destructor.
const word & name () const
Return the name of this phase.
const word & keyword () const
Return the name of the phase for use as the keyword in PtrDictionary.
label index () const
Return the index of the phase.
const phaseSystem & fluid () const
Return the system to which this phase belongs.
const dimensionedScalar & residualAlpha () const
Return the residual phase-fraction for given phase.
scalar alphaMax () const
Return the maximum phase-fraction (e.g. packing limit)
tmp< volScalarField > d () const
Return the Sauter-mean diameter.
virtual void correct ()
Correct the phase properties.
virtual void correctKinematics ()
Correct the kinematics.
virtual void correctThermo ()
Correct the thermodynamics.
virtual void correctTurbulence ()
Correct the turbulence.
virtual void correctEnergyTransport ()
Correct the energy transport e.g. alphat.
virtual tmp< fvVectorMatrix > UEqn ()=0
Return the momentum equation.
virtual tmp< fvScalarMatrix > heEqn ()=0
Return the enthalpy equation.
virtual tmp< fvScalarMatrix > YiEqn (volScalarField &Yi)=0
Return the species fraction equation.
virtual bool read ()
Read phase properties dictionary.
virtual bool compressible () const
Return true if the phase is compressible otherwise false.
virtual const tmp< volScalarField > & divU () const
Return the phase dilatation rate (d(alpha)/dt + div(alpha*phi))
virtual void divU (const tmp< volScalarField > &divU)
Set the phase dilatation rate (d(alpha)/dt + div(alpha*phi))
virtual const volScalarField & K () const
Return the phase kinetic energy.
virtual const surfaceScalarField & DbyA () const
Return the phase diffusivity divided by the momentum coefficient.
virtual void DbyA (const tmp< surfaceScalarField > &DbyA)
Set the phase diffusivity divided by the momentum coefficient.
virtual const rhoThermo & thermo () const =0
Return const access to the thermophysical model.
virtual rhoThermo & thermo ()=0
Return non-const access to the thermophysical model.
virtual tmp< volScalarField > rho () const =0
Return the density field.
virtual const PtrList< volScalarField > & Y () const =0
Constant access the species mass fractions.
virtual PtrList< volScalarField > & Y ()=0
Access the species mass fractions.
virtual tmp< volVectorField > U () const =0
Constant access the velocity.
virtual volVectorField & U ()=0
Access the velocity.
virtual tmp< volVectorField > DUDt () const =0
Return the substantive acceleration.
virtual tmp< volScalarField > continuityError () const =0
Constant access the continuity error.
virtual tmp< surfaceScalarField > phi () const =0
Constant access the volumetric flux.
virtual surfaceScalarField & phi ()=0
Access the volumetric flux.
virtual tmp< surfaceScalarField > alphaPhi () const =0
Constant access the volumetric flux of the phase.
virtual surfaceScalarField & alphaPhi ()=0
Access the volumetric flux of the phase.
virtual tmp< surfaceScalarField > alphaRhoPhi () const =0
Constant access the mass flux of the phase.
virtual surfaceScalarField & alphaRhoPhi ()=0
Access the mass flux of the phase.
virtual tmp< volScalarField > mu () const =0
Return the laminar dynamic viscosity.
virtual tmp< scalarField > mu (const label patchi) const =0
Return the laminar dynamic viscosity on a patch.
virtual tmp< volScalarField > nu () const =0
Return the laminar kinematic viscosity.
virtual tmp< scalarField > nu (const label patchi) const =0
Return the laminar kinematic viscosity on a patch.
virtual tmp< volScalarField > kappa () const =0
Return the laminar thermal conductivity.
virtual tmp< scalarField > kappa (const label patchi) const =0
Return the laminar thermal conductivity on a patch.
virtual tmp< volScalarField > kappaEff (const volScalarField &alphat) const =0
Return the effective thermal conductivity.
virtual tmp< scalarField > kappaEff (const scalarField &alphat, const label patchi) const =0
Access the effective thermal conductivity.
virtual tmp< volScalarField > alpha () const =0
Return the laminar thermal diffusivity for enthalpy.
virtual tmp< scalarField > alpha (const label patchi) const =0
Return the laminar thermal diffusivity for enthalpy on a patch.
virtual tmp< volScalarField > alphaEff (const volScalarField &alphat) const =0
Return the effective thermal diffusivity for enthalpy.
virtual tmp< scalarField > alphaEff (const scalarField &alphat, const label patchi) const =0
Return the effective thermal diffusivity for enthalpy on a patch.
virtual const phaseCompressibleTurbulenceModel & turbulence () const =0
Return the turbulence model.
phaseModel (const twoPhaseSystem &fluid, const dictionary &phaseProperties, const word &phaseName)
virtual ~phaseModel ()
Destructor.
const word & name () const
Return the name of this phase.
const twoPhaseSystem & fluid () const
Return the twoPhaseSystem to which this phase belongs.
const phaseModel & otherPhase () const
Return the other phase in this two-phase system.
const dimensionedScalar & residualAlpha () const
Return the residual phase-fraction for given phase.
scalar alphaMax () const
Optional maximum phase-fraction (e.g. packing limit)
tmp< volScalarField > d () const
Return the Sauter-mean diameter.
const PhaseCompressibleTurbulenceModel< phaseModel > & turbulence () const
Return the turbulence model.
PhaseCompressibleTurbulenceModel< phaseModel > & turbulence ()
Return non-const access to the turbulence model.
const rhoThermo & thermo () const
Return the thermophysical model.
rhoThermo & thermo ()
Return non-const access to the thermophysical model.
tmp< volScalarField > nu () const
Return the laminar viscosity.
tmp< scalarField > nu (const label patchi) const
Return the laminar viscosity for patch.
tmp< volScalarField > mu () const
Return the laminar dynamic viscosity.
tmp< scalarField > mu (const label patchi) const
Return the laminar dynamic viscosity for patch.
tmp< scalarField > kappa (const label patchi) const
Return the thermal conductivity on a patch.
tmp< volScalarField > kappa () const
Return the thermal conductivity.
tmp< volScalarField > kappaEff (const volScalarField &alphat) const
Return the laminar thermal conductivity.
tmp< scalarField > kappaEff (const scalarField &alphat, const label patchi) const
Return the laminar thermal conductivity on a patch.
tmp< volScalarField > alpha () const
Return the laminar thermal diffusivity for enthalpy.
tmp< scalarField > alpha (const label patchi) const
Return the laminar thermal diffusivity for enthalpy on a patch.
tmp< volScalarField > alphaEff (const volScalarField &alphat) const
Return the effective thermal diffusivity for enthalpy.
tmp< scalarField > alphaEff (const scalarField &alphat, const label patchi) const
Return the effective thermal diffusivity for enthalpy on a patch.
tmp< volScalarField > Cp () const
Return the specific heat capacity.
const volScalarField & rho () const
Return the density.
const volVectorField & U () const
Return the velocity.
volVectorField & U ()
Return non-const access to the velocity.
const surfaceScalarField & phi () const
Return the volumetric flux.
surfaceScalarField & phi ()
Return non-const access to the volumetric flux.
const surfaceScalarField & alphaPhi () const
Return the volumetric flux of the phase.
surfaceScalarField & alphaPhi ()
Return non-const access to the volumetric flux of the phase.
const surfaceScalarField & alphaRhoPhi () const
Return the mass flux of the phase.
surfaceScalarField & alphaRhoPhi ()
Return non-const access to the mass flux of the phase.
void correct ()
Correct the phase properties.
virtual bool read (const dictionary &phaseProperties)
Read phaseProperties dictionary.
virtual bool read ()
Dummy Read for transportModel.
Public Member Functions inherited from GeometricField< scalar, fvPatchField, volMesh >
TypeName ("GeometricField")
Runtime type information.
GeometricField (const IOobject &, const Mesh &, const dimensionSet &, const word &patchFieldType=fvPatchField< scalar >::calculatedType())
Constructor given IOobject, mesh, dimensions and patch type.
GeometricField (const IOobject &, const Mesh &, const dimensionSet &, const wordList &wantedPatchTypes, const wordList &actualPatchTypes=wordList())
Constructor given IOobject, mesh, dimensions and patch types.
GeometricField (const IOobject &, const Mesh &, const dimensioned< scalar > &, const word &patchFieldType=fvPatchField< scalar >::calculatedType())
Constructor given IOobject, mesh, dimensioned<Type> and patch type.
GeometricField (const IOobject &, const Mesh &, const dimensioned< scalar > &, const wordList &wantedPatchTypes, const wordList &actualPatchTypes=wordList())
Constructor given IOobject, mesh, dimensioned<Type> and patch types.
GeometricField (const IOobject &, const Internal &, const PtrList< fvPatchField< scalar >> &)
Constructor from components.
GeometricField (const IOobject &, const Mesh &, const dimensionSet &, const Field< scalar > &, const PtrList< fvPatchField< scalar >> &)
Constructor from components.
GeometricField (const IOobject &, const Mesh &)
Construct and read given IOobject.
GeometricField (const IOobject &, const Mesh &, const dictionary &)
Construct from dictionary.
GeometricField (const GeometricField< scalar, fvPatchField, volMesh > &)
Construct as copy.
GeometricField (const tmp< GeometricField< scalar, fvPatchField, volMesh >> &)
Construct as copy of tmp<GeometricField> deleting argument.
GeometricField (const IOobject &, const GeometricField< scalar, fvPatchField, volMesh > &)
Construct as copy resetting IO parameters.
GeometricField (const IOobject &, const tmp< GeometricField< scalar, fvPatchField, volMesh >> &)
Construct as copy of tmp<GeometricField> resetting IO parameters.
GeometricField (const word &newName, const GeometricField< scalar, fvPatchField, volMesh > &)
Construct as copy resetting name.
GeometricField (const word &newName, const tmp< GeometricField< scalar, fvPatchField, volMesh >> &)
Construct as copy resetting name.
GeometricField (const IOobject &, const GeometricField< scalar, fvPatchField, volMesh > &, const word &patchFieldType)
Construct as copy resetting IO parameters and patch type.
GeometricField (const IOobject &, const GeometricField< scalar, fvPatchField, volMesh > &, const wordList &patchFieldTypes, const wordList &actualPatchTypes=wordList())
Construct as copy resetting IO parameters and boundary types.
GeometricField (const IOobject &, const tmp< GeometricField< scalar, fvPatchField, volMesh >> &, const wordList &patchFieldTypes, const wordList &actualPatchTypes=wordList())
Construct as copy resetting IO parameters and boundary types.
virtual ~GeometricField ()
Destructor.
Internal & ref ()
Return a reference to the dimensioned internal field.
const Internal & internalField () const
Return a const-reference to the dimensioned internal field.
const Internal & v () const
Return a const-reference to the dimensioned internal field.
Internal::FieldType & primitiveFieldRef ()
Return a reference to the internal field.
const Internal::FieldType & primitiveField () const
Return a const-reference to the internal field.
Boundary & boundaryFieldRef ()
Return a reference to the boundary field.
const Boundary & boundaryField () const
Return const-reference to the boundary field.
label timeIndex () const
Return the time index of the field.
label & timeIndex ()
Return the time index of the field.
void storeOldTimes () const
Store the old-time fields.
void storeOldTime () const
Store the old-time field.
label nOldTimes () const
Return the number of old time fields stored.
const GeometricField< scalar, fvPatchField, volMesh > & oldTime () const
Return old time field.
GeometricField< scalar, fvPatchField, volMesh > & oldTime ()
Return non-const old time field.
void storePrevIter () const
Store the field as the previous iteration value.
const GeometricField< scalar, fvPatchField, volMesh > & prevIter () const
Return previous iteration field.
void correctBoundaryConditions ()
Correct boundary field.
bool needReference () const
Does the field need a reference level for solution.
tmp< GeometricField< cmptType, fvPatchField, volMesh > > component (const direction) const
Return a component of the field.
tmp< GeometricField< scalar, fvPatchField, volMesh > > component (const direction) const
tmp< GeometricField< scalar, fvPatchField, volMesh > > component (const direction) const
bool writeData (Ostream &) const
WriteData member function required by regIOobject.
tmp< GeometricField< scalar, fvPatchField, volMesh > > T () const
Return transpose (only if it is a tensor field)
void relax (const scalar alpha)
Relax field (for steady-state solution).
void relax ()
Relax field (for steady-state solution).
word select (bool final) const
Select the final iteration parameters if `final' is true.
void writeMinMax (Ostream &os) const
Helper function to write the min and max to an Ostream.
void negate ()
void replace (const direction, const GeometricField< cmptType, fvPatchField, volMesh > &)
void replace (const direction, const dimensioned< cmptType > &)
void replace (const direction, const GeometricField< scalar, fvPatchField, volMesh > &gsf)
void replace (const direction, const GeometricField< scalar, fvPatchField, volMesh > &sf)
void max (const dimensioned< scalar > &)
void max (const GeometricField< scalar, fvPatchField, volMesh > &, const dimensioned< scalar > &)
void min (const dimensioned< scalar > &)
void min (const GeometricField< scalar, fvPatchField, volMesh > &, const dimensioned< scalar > &)
void scale (const GeometricField< scalar, fvPatchField, volMesh > &, const GeometricField< scalar, fvPatchField, volMesh > &)
void scale (const GeometricField< scalar, fvPatchField, volMesh > &, const dimensioned< scalar > &)
const Internal & operator() () const
Return a const-reference to the dimensioned internal field.
void operator= (const GeometricField< scalar, fvPatchField, volMesh > &)
void operator= (const tmp< GeometricField< scalar, fvPatchField, volMesh >> &)
void operator= (const dimensioned< scalar > &)
void operator== (const tmp< GeometricField< scalar, fvPatchField, volMesh >> &)
void operator== (const dimensioned< scalar > &)
void operator+= (const GeometricField< scalar, fvPatchField, volMesh > &)
void operator+= (const tmp< GeometricField< scalar, fvPatchField, volMesh >> &)
void operator+= (const dimensioned< scalar > &)
void operator-= (const GeometricField< scalar, fvPatchField, volMesh > &)
void operator-= (const tmp< GeometricField< scalar, fvPatchField, volMesh >> &)
void operator-= (const dimensioned< scalar > &)
void operator*= (const GeometricField< scalar, fvPatchField, volMesh > &)
void operator*= (const tmp< GeometricField< scalar, fvPatchField, volMesh >> &)
void operator*= (const dimensioned< scalar > &)
void operator/= (const GeometricField< scalar, fvPatchField, volMesh > &)
void operator/= (const tmp< GeometricField< scalar, fvPatchField, volMesh >> &)
void operator/= (const dimensioned< scalar > &)
Public Member Functions inherited from DimensionedField< Type, GeoMesh >
TypeName ("DimensionedField")
Runtime type information.
DimensionedField (const IOobject &, const Mesh &mesh, const dimensionSet &, const Field< Type > &)
Construct from components.
DimensionedField (const IOobject &, const Mesh &mesh, const dimensionSet &, const bool checkIOFlags=true)
Construct from components.
DimensionedField (const IOobject &, const Mesh &mesh, const dimensioned< Type > &, const bool checkIOFlags=true)
Construct from components.
DimensionedField (const IOobject &, const Mesh &mesh, const word &fieldDictEntry="value")
Construct from Istream.
DimensionedField (const IOobject &, const Mesh &mesh, const dictionary &fieldDict, const word &fieldDictEntry="value")
Construct from dictionary.
DimensionedField (const DimensionedField< Type, GeoMesh > &)
Construct as copy.
DimensionedField (DimensionedField< Type, GeoMesh > &, bool reuse)
Construct as copy or re-use as specified.
DimensionedField (const Xfer< DimensionedField< Type, GeoMesh >> &)
Construct by transferring the DimensionedField.
DimensionedField (const tmp< DimensionedField< Type, GeoMesh >> &)
Construct as copy of tmp<DimensionedField> deleting argument.
DimensionedField (const IOobject &, const DimensionedField< Type, GeoMesh > &)
Construct as copy resetting IO parameters.
DimensionedField (const IOobject &, DimensionedField< Type, GeoMesh > &, bool reuse)
Construct as copy resetting IO parameters and re-use as specified.
DimensionedField (const word &newName, const DimensionedField< Type, GeoMesh > &)
Construct as copy resetting name.
DimensionedField (const word &newName, DimensionedField< Type, GeoMesh > &, bool reuse)
Construct as copy resetting name and re-use as specified.
DimensionedField (const word &newName, const Xfer< DimensionedField< Type, GeoMesh >> &)
Construct by transferring the DimensionedField with a new name.
DimensionedField (const word &newName, const tmp< DimensionedField< Type, GeoMesh >> &)
Construct as copy resetting name.
tmp< DimensionedField< Type, GeoMesh > > clone () const
Clone.
virtual ~DimensionedField ()
Destructor.
void readField (const dictionary &fieldDict, const word &fieldDictEntry="value")
const Mesh & mesh () const
Return mesh.
const dimensionSet & dimensions () const
Return dimensions.
dimensionSet & dimensions ()
Return non-const access to dimensions.
const Field< Type > & field () const
Field< Type > & field ()
tmp< DimensionedField< cmptType, GeoMesh > > component (const direction) const
Return a component field of the field.
void replace (const direction, const DimensionedField< cmptType, GeoMesh > &)
Replace a component field of the field.
void replace (const direction, const tmp< DimensionedField< cmptType, GeoMesh >> &)
Replace a component field of the field.
tmp< DimensionedField< Type, GeoMesh > > T () const
Return the field transpose (only defined for second rank tensors)
dimensioned< Type > average () const
Calculate and return arithmetic average.
dimensioned< Type > weightedAverage (const DimensionedField< scalar, GeoMesh > &) const
Calculate and return weighted average.
dimensioned< Type > weightedAverage (const tmp< DimensionedField< scalar, GeoMesh >> &) const
Calculate and return weighted average.
bool writeData (Ostream &, const word &fieldDictEntry) const
void operator= (const DimensionedField< Type, GeoMesh > &)
void operator= (const tmp< DimensionedField< Type, GeoMesh >> &)
void operator= (const dimensioned< Type > &)
void operator+= (const DimensionedField< Type, GeoMesh > &)
void operator+= (const tmp< DimensionedField< Type, GeoMesh >> &)
void operator-= (const DimensionedField< Type, GeoMesh > &)
void operator-= (const tmp< DimensionedField< Type, GeoMesh >> &)
void operator*= (const DimensionedField< scalar, GeoMesh > &)
void operator*= (const tmp< DimensionedField< scalar, GeoMesh >> &)
void operator/= (const DimensionedField< scalar, GeoMesh > &)
void operator/= (const tmp< DimensionedField< scalar, GeoMesh >> &)
void operator+= (const dimensioned< Type > &)
void operator-= (const dimensioned< Type > &)
void operator*= (const dimensioned< scalar > &)
void operator/= (const dimensioned< scalar > &)
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, transferring registry registration to copy.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Construct as copy with new name, transfering registry registration.
regIOobject (const IOobject &, const regIOobject &)
Construct as copy with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
virtual void rename (const word &newName)
Rename.
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool readData (Istream &)
Virtual readData function.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType) const
Write using given format, version and compression.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Public Member Functions inherited from Field< Type >
Field ()
Construct null.
Field (const label)
Construct given size.
Field (const label, const Type &)
Construct given size and initial value.
Field (const label, const zero)
Construct given size and initialed to zero.
Field (const UList< Type > &)
Construct as copy of a UList<Type>
Field (const Xfer< List< Type >> &)
Construct by transferring the List contents.
Field (const UList< Type > &mapF, const labelUList &mapAddressing)
Construct by 1 to 1 mapping from the given field.
Field (const tmp< Field< Type >> &tmapF, const labelUList &mapAddressing)
Construct by 1 to 1 mapping from the given tmp field.
Field (const UList< Type > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Construct by interpolative mapping from the given field.
Field (const tmp< Field< Type >> &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Construct by interpolative mapping from the given tmp field.
Field (const UList< Type > &mapF, const FieldMapper &map, const bool applyFlip=true)
Construct by mapping from the given field.
Field (const UList< Type > &mapF, const FieldMapper &map, const Type &defaultValue, const bool applyFlip=true)
Construct by mapping from the given field.
Field (const UList< Type > &mapF, const FieldMapper &map, const UList< Type > &defaultValues, const bool applyFlip=true)
Construct by mapping from the given field.
Field (const tmp< Field< Type >> &tmapF, const FieldMapper &map, const bool applyFlip=true)
Construct by mapping from the given tmp field.
Field (const tmp< Field< Type >> &tmapF, const FieldMapper &map, const Type &defaultValue, const bool applyFlip=true)
Construct by mapping from the given tmp field. Supplied uniform.
Field (const tmp< Field< Type >> &tmapF, const FieldMapper &map, const UList< Type > &defaultValues, const bool applyFlip=true)
Construct by mapping from the given tmp field. Supplied values.
Field (const Field< Type > &)
Construct as copy.
Field (Field< Type > &, bool reuse)
Construct as copy or re-use as specified.
Field (const Xfer< Field< Type >> &)
Construct by transferring the Field contents.
Field (const tmp< Field< Type >> &)
Construct as copy of tmp<Field>
Field (Istream &)
Construct from Istream.
Field (const word &keyword, const dictionary &, const label size)
Construct from a dictionary entry.
tmp< Field< Type > > clone () const
Clone.
void map (const UList< Type > &mapF, const labelUList &mapAddressing)
1 to 1 map from the given field
void map (const tmp< Field< Type >> &tmapF, const labelUList &mapAddressing)
1 to 1 map from the given tmp field
void map (const UList< Type > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Interpolative map from the given field.
void map (const tmp< Field< Type >> &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Interpolative map from the given tmp field.
void map (const UList< Type > &mapF, const FieldMapper &map, const bool applyFlip=true)
Map from the given field.
void map (const tmp< Field< Type >> &tmapF, const FieldMapper &map, const bool applyFlip=true)
Map from the given tmp field.
void autoMap (const FieldMapper &map, const bool applyFlip=true)
Map from self.
void rmap (const UList< Type > &mapF, const labelUList &mapAddressing)
1 to 1 reverse-map from the given field
void rmap (const tmp< Field< Type >> &tmapF, const labelUList &mapAddressing)
1 to 1 reverse-map from the given tmp field
void rmap (const UList< Type > &mapF, const labelUList &mapAddressing, const UList< scalar > &weights)
Interpolative reverse map from the given field.
void rmap (const tmp< Field< Type >> &tmapF, const labelUList &mapAddressing, const UList< scalar > &weights)
Interpolative reverse map from the given tmp field.
void negate ()
Negate this field.
tmp< Field< cmptType > > component (const direction) const
Return a component field of the field.
void replace (const direction, const UList< cmptType > &)
Replace a component field of the field.
void replace (const direction, const tmp< Field< cmptType >> &)
Replace a component field of the field.
void replace (const direction, const cmptType &)
Replace a component field of the field.
template<class VSForm >
VSForm block (const label start) const
tmp< Field< Type > > T () const
Return the field transpose (only defined for second rank tensors)
void writeEntry (const word &keyword, Ostream &os) const
Write the field as a dictionary entry.
void operator= (const Field< Type > &)
void operator= (const UList< Type > &)
void operator= (const SubField< Type > &)
void operator= (const tmp< Field< Type >> &)
void operator= (const Type &)
void operator= (const zero)
template<class Form , class Cmpt , direction nCmpt>
void operator= (const VectorSpace< Form, Cmpt, nCmpt > &)
void operator+= (const UList< Type > &)
void operator+= (const tmp< Field< Type >> &)
void operator-= (const UList< Type > &)
void operator-= (const tmp< Field< Type >> &)
void operator*= (const UList< scalar > &)
void operator*= (const tmp< Field< scalar >> &)
void operator/= (const UList< scalar > &)
void operator/= (const tmp< Field< scalar >> &)
void operator+= (const Type &)
void operator-= (const Type &)
void operator*= (const scalar &)
void operator/= (const scalar &)
template<class Type>
void operator= (const tmp< Field > &rhs)
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Public Member Functions inherited from List< Type >
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const Type &)
Construct with given size and value for all elements.
List (const label, const zero)
Construct with given size initializing all elements to zero.
List (const List< Type > &)
Copy constructor.
List (const List< T2 > &)
Copy constructor from list containing another type.
List (const Xfer< List< Type >> &)
Construct by transferring the parameter contents.
List (List< Type > &, bool reuse)
Construct as copy or re-use as specified.
List (const UList< Type > &, const labelUList &mapAddressing)
Construct as subset.
List (InputIterator first, InputIterator last)
Construct given start and end iterators.
List (const FixedList< Type, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< Type > &)
Construct as copy of PtrList<T>
List (const SLList< Type > &)
Construct as copy of SLList<T>
List (const UIndirectList< Type > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< Type > &)
Construct as copy of BiIndirectList<T>
List (std::initializer_list< Type >)
Construct from an initializer list.
List (Istream &)
Construct from Istream.
label size () const
Return the number of elements in the UList.
autoPtr< List< Type > > clone () const
Clone.
~List ()
Destructor.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const Type &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const Type &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const Type &)
Append an element at the end of the list.
void append (const UList< Type > &)
Append a List at the end of this list.
void append (const UIndirectList< Type > &)
Append a UIndirectList at the end of this list.
void transfer (List< Type > &)
Transfer the contents of the argument List into this list.
void transfer (DynamicList< Type, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< Type > &)
Transfer the contents of the argument List into this list.
Xfer< List< Type > > xfer ()
Transfer contents to the Xfer container.
Type & newElmt (const label)
Return subscript-checked element of UList.
void shallowCopy (const UList< Type > &)=delete
Disallow implicit shallowCopy.
void operator= (const UList< Type > &)
Assignment to UList operator. Takes linear time.
void operator= (const List< Type > &)
Assignment operator. Takes linear time.
void operator= (const SLList< Type > &)
Assignment to SLList operator. Takes linear time.
void operator= (const UIndirectList< Type > &)
Assignment to UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< Type > &)
Assignment to BiIndirectList operator. Takes linear time.
void operator= (std::initializer_list< Type >)
Assignment to an initializer list.
void operator= (const Type &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
Public Member Functions inherited from UList< Type >
void operator= (const Type &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
UList ()
Null constructor.
UList (Type *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const Type * cdata () const
Return a const pointer to the first data element,.
Type * data ()
Return a pointer to the first data element,.
Type & first ()
Return the first element of the list.
const Type & first () const
Return first element of the list.
Type & last ()
Return the last element of the list.
const Type & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1)
void checkSize (const label size) const
Check size is within valid range (0 ... size)
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1)
void shallowCopy (const UList< Type > &)
Copy the pointer held by the given UList.
void deepCopy (const UList< Type > &)
Copy elements of the given UList.
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
Type & operator[] (const label)
Return element of UList.
const Type & operator[] (const label) const
Return element of constant UList.
const bool & operator[] (const label i) const
operator const Foam::List< Type > & () const
Allow cast to a const List<T>&.
iterator begin ()
Return an iterator to begin traversing the UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero)
void swap (UList< Type > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< Type > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< Type > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< Type > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< Type > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< Type > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< Type > &) const
Return true if !(a < b). Takes linear time.
Public Member Functions inherited from transportModel
TypeName ("transportModel")
Runtime type information.
transportModel ()
Construct from components.
virtual ~transportModel ()
Destructor.
Static Public Member Functions
static autoPtr< phaseModel > New (const phaseSystem &fluid, const word &phaseName, const label index)
Static Public Member Functions inherited from GeometricField< scalar, fvPatchField, volMesh >
static const GeometricField< scalar, fvPatchField, volMesh > & null ()
Return a null geometric field.
Static Public Member Functions inherited from DimensionedField< Type, GeoMesh >
static const DimensionedField< Type, GeoMesh > & null ()
Return a null DimensionedField.
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Static Public Member Functions inherited from Field< Type >
static const Field< Type > & null ()
Return a null field.
template<class Type2 >
static tmp< Field< Type > > NewCalculatedType (const Field< Type2 > &f)
Return a pointer to a new calculatedFvPatchFieldField created on.
Static Public Member Functions inherited from List< Type >
static const List< Type > & null ()
Return a null List.
Static Public Member Functions inherited from UList< Type >
static const UList< Type > & null ()
Return a null UList.
Additional Inherited Members
Public Types inherited from GeometricField< scalar, fvPatchField, volMesh >
typedef volMesh ::Mesh Mesh
Type of mesh on which this GeometricField is instantiated.
typedef volMesh ::BoundaryMesh BoundaryMesh
Type of boundary mesh on which this.
typedef DimensionedField< scalar, volMesh > Internal
Type of the internal field from which this GeometricField is derived.
typedef fvPatchField< scalar > Patch
Type of the patch field of which the.
typedef Field< scalar >::cmptType cmptType
Public Types inherited from DimensionedField< Type, GeoMesh >
typedef GeoMesh::Mesh Mesh
Type of mesh on which this DimensionedField is instantiated.
typedef Field< Type > FieldType
Type of the field from which this DimensionedField is derived.
typedef Field< Type >::cmptType cmptType
Component type of the elements of the field.
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Public Types inherited from Field< Type >
typedef pTraits< Type >::cmptType cmptType
Component type.
typedef SubField< Type > subField
Declare type of subField.
Public Types inherited from List< Type >
typedef SubList< Type > subList
Declare type of subList.
Public Types inherited from UList< Type >
typedef Type value_type
Type of values the UList contains.
typedef Type & reference
Type that can be used for storing into.
typedef const Type & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef Type * iterator
Random access iterator for traversing UList.
typedef const Type * const_iterator
Random access iterator for traversing UList.
typedef Type * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const Type * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Static Public Attributes inherited from Field< Type >
static const char *const typeName
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Protected Member Functions inherited from List< Type >
void size (const label)
Override size to be inconsistent with allocated storage.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
Single incompressible phase derived from the phase-fraction. Used as part of the multiPhaseMixture for interface-capturing multi-phase simulations.
Source files
phaseModel.H
phaseModel.C
Source files
phaseModel.H
phaseModel.C
Source files
phaseModel.H
phaseModel.C
Source files
phaseModel.H
phaseModel.C
Definition at line 53 of file phaseModel.H.
Constructor & Destructor Documentation
phaseModel() [1/4]
phaseModel (const word & phaseName, const volScalarField & p, const volScalarField & T)
Construct from components.
Referenced by phaseModel::iNew::operator()().
phaseModel() [2/4]
phaseModel (const word & phaseName, const dictionary & phaseDict, const fvMesh & mesh)
~phaseModel() [1/3]
virtual ~phaseModel () virtual
Destructor.
Referenced by phaseModel::iNew::operator()().
phaseModel() [3/4]
phaseModel (const phaseSystem & fluid, const word & phaseName, const label index)
~phaseModel() [2/3]
virtual ~phaseModel () virtual
Destructor.
phaseModel() [4/4]
phaseModel (const twoPhaseSystem & fluid, const dictionary & phaseProperties, const word & phaseName)
~phaseModel() [3/3]
virtual ~phaseModel () virtual
Destructor.
Member Function Documentation
clone() [1/3]
autoPtr<phaseModel> clone () const
Return clone.
name() [1/4]
const word& name () const inline
Definition at line 109 of file phaseModel.H.
Referenced by phaseModel::keyword(), and phaseModel::iNew::operator()().
keyword() [1/3]
const word& keyword () const inline
Definition at line 114 of file phaseModel.H.
References phaseModel::name().
Referenced by phaseModel::iNew::operator()().
thermo() [1/6]
const rhoThermo& thermo () const inline
Return const-access to phase rhoThermo.
Definition at line 120 of file phaseModel.H.
Referenced by phaseModel::iNew::operator()(), and phaseModel::thermo().
thermo() [2/6]
rhoThermo& thermo () inline
Return access to phase rhoThermo.
Definition at line 126 of file phaseModel.H.
dgdt() [1/2]
const volScalarField& dgdt () const inline
Return const-access to phase divergence.
Definition at line 132 of file phaseModel.H.
dgdt() [2/2]
volScalarField& dgdt () inline
Return access to phase divergence.
Definition at line 138 of file phaseModel.H.
References phaseModel::correct().
correct() [1/4]
void correct () virtual
Correct the laminar viscosity.
Implements transportModel.
Referenced by phaseModel::alphaPhi(), phaseModel::alphaRhoPhi(), phaseModel::dgdt(), and phaseModel::iNew::operator()().
clone() [2/3]
autoPtr<phaseModel> clone () const
Return clone.
name() [2/4]
const word& name () const inline
Definition at line 138 of file phaseModel.H.
keyword() [2/3]
const word& keyword () const inline
Definition at line 143 of file phaseModel.H.
References phaseModel::d(), and phaseModel::name().
d() [1/3]
tmp<volScalarField> d () const
Referenced by phaseModel::fluid(), phaseModel::keyword(), and phaseModel::iNew::operator()().
nu() [1/5]
const dimensionedScalar& nu () const inline virtual
Return the laminar viscosity.
Implements transportModel.
Definition at line 150 of file phaseModel.H.
Referenced by phaseModel::iNew::operator()().
kappa() [1/5]
const dimensionedScalar& kappa () const inline
Definition at line 155 of file phaseModel.H.
Referenced by phaseModel::iNew::operator()().
Cp() [1/2]
const dimensionedScalar& Cp () const inline
Definition at line 160 of file phaseModel.H.
rho() [1/3]
const dimensionedScalar& rho () const inline
Definition at line 165 of file phaseModel.H.
Referenced by phaseModel::iNew::operator()(), mixtureKEpsilon< BasicTurbulenceModel >::rhogEff(), and mixtureKEpsilon< BasicTurbulenceModel >::rholEff().
U() [1/6]
const volVectorField& U () const inline
Definition at line 170 of file phaseModel.H.
Referenced by phaseModel::iNew::operator()(), and phaseModel::U().
U() [2/6]
volVectorField& U () inline
Definition at line 175 of file phaseModel.H.
DDtU() [1/2]
const volVectorField& DDtU () const inline
Definition at line 180 of file phaseModel.H.
DDtU() [2/2]
volVectorField& DDtU () inline
Definition at line 185 of file phaseModel.H.
phi() [1/6]
const surfaceScalarField& phi () const inline
Definition at line 190 of file phaseModel.H.
Referenced by phaseModel::iNew::operator()().
phi() [2/6]
surfaceScalarField& phi () inline
Definition at line 195 of file phaseModel.H.
alphaPhi() [1/6]
const surfaceScalarField& alphaPhi () const inline
Definition at line 200 of file phaseModel.H.
Referenced by phaseModel::iNew::operator()().
alphaPhi() [2/6]
surfaceScalarField& alphaPhi () inline
Definition at line 205 of file phaseModel.H.
References phaseModel::correct(), phaseModel::read(), and regIOobject::read().
correct() [2/4]
void correct () virtual
Correct the phase properties.
Implements transportModel.
read() [1/4]
bool read (const dictionary & phaseDict)
Read base transportProperties dictionary.
ClassName()
ClassName ("phaseModel")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , phaseModel , phaseSystem , (const phaseSystem &fluid, const word &phaseName, const label index) , (fluid, phaseName, index))
clone() [3/3]
autoPtr<phaseModel> clone () const
Return clone.
New()
static autoPtr<phaseModel> New (const phaseSystem & fluid, const word & phaseName, const label index) static
Referenced by phaseModel::iNew::operator()().
name() [3/4]
const word& name () const
Return the name of this phase.
keyword() [3/3]
const word& keyword () const
Return the name of the phase for use as the keyword in PtrDictionary.
index()
label index () const
Return the index of the phase.
Referenced by phaseModel::iNew::operator()().
fluid() [1/2]
const phaseSystem& fluid () const
Return the system to which this phase belongs.
Referenced by IATEsource::fluid(), and phaseModel::iNew::operator()().
residualAlpha() [1/2]
const dimensionedScalar& residualAlpha () const
Return the residual phase-fraction for given phase.
Used to stabilize the phase momentum as the phase-fraction -> 0
Referenced by phaseModel::fluid(), and phaseModel::iNew::operator()().
alphaMax() [1/2]
scalar alphaMax () const
Return the maximum phase-fraction (e.g. packing limit)
Referenced by phaseModel::fluid(), and phaseModel::iNew::operator()().
d() [2/3]
tmp<volScalarField> d () const
Return the Sauter-mean diameter.
correct() [3/4]
virtual void correct () virtual
Correct the phase properties.
Implements transportModel.
correctKinematics()
virtual void correctKinematics () virtual
Correct the kinematics.
Referenced by phaseModel::iNew::operator()().
correctThermo()
virtual void correctThermo () virtual
Correct the thermodynamics.
Referenced by phaseModel::iNew::operator()().
correctTurbulence()
virtual void correctTurbulence () virtual
Correct the turbulence.
Referenced by phaseModel::iNew::operator()().
correctEnergyTransport()
virtual void correctEnergyTransport () virtual
Correct the energy transport e.g. alphat.
Referenced by phaseModel::iNew::operator()().
UEqn()
virtual tmp<fvVectorMatrix> UEqn () pure virtual
Return the momentum equation.
Referenced by phaseModel::iNew::operator()().
heEqn()
virtual tmp<fvScalarMatrix> heEqn () pure virtual
Return the enthalpy equation.
Referenced by phaseModel::iNew::operator()().
YiEqn()
virtual tmp<fvScalarMatrix> YiEqn (volScalarField & Yi) pure virtual
Return the species fraction equation.
Referenced by phaseModel::iNew::operator()().
read() [2/4]
virtual bool read () virtual
Read phase properties dictionary.
Implements transportModel.
Referenced by phaseModel::alphaPhi(), phaseModel::alphaRhoPhi(), and phaseModel::iNew::operator()().
compressible()
virtual bool compressible () const virtual
Return true if the phase is compressible otherwise false.
Referenced by phaseModel::iNew::operator()().
divU() [1/2]
virtual const tmp<volScalarField>& divU () const virtual
Return the phase dilatation rate (d(alpha)/dt + div(alpha*phi))
Referenced by phaseModel::iNew::operator()().
divU() [2/2]
virtual void divU (const tmp< volScalarField > & divU) virtual
Set the phase dilatation rate (d(alpha)/dt + div(alpha*phi))
K()
virtual const volScalarField& K () const virtual
Return the phase kinetic energy.
Referenced by phaseModel::iNew::operator()().
DbyA() [1/2]
virtual const surfaceScalarField& DbyA () const virtual
Return the phase diffusivity divided by the momentum coefficient.
Referenced by phaseModel::iNew::operator()().
DbyA() [2/2]
virtual void DbyA (const tmp< surfaceScalarField > & DbyA) virtual
Set the phase diffusivity divided by the momentum coefficient.
thermo() [3/6]
virtual const rhoThermo& thermo () const pure virtual
Return const access to the thermophysical model.
thermo() [4/6]
virtual rhoThermo& thermo () pure virtual
Return non-const access to the thermophysical model.
for correction
rho() [2/3]
virtual tmp<volScalarField> rho () const pure virtual
Return the density field.
Y() [1/2]
virtual const PtrList<volScalarField>& Y () const pure virtual
Constant access the species mass fractions.
Referenced by phaseModel::iNew::operator()().
Y() [2/2]
virtual PtrList<volScalarField>& Y () pure virtual
Access the species mass fractions.
U() [3/6]
virtual tmp<volVectorField> U () const pure virtual
Constant access the velocity.
U() [4/6]
virtual volVectorField& U () pure virtual
Access the velocity.
DUDt()
virtual tmp<volVectorField> DUDt () const pure virtual
Return the substantive acceleration.
Referenced by phaseModel::iNew::operator()().
continuityError()
virtual tmp<volScalarField> continuityError () const pure virtual
Constant access the continuity error.
Referenced by phaseModel::iNew::operator()().
phi() [3/6]
virtual tmp<surfaceScalarField> phi () const pure virtual
Constant access the volumetric flux.
phi() [4/6]
virtual surfaceScalarField& phi () pure virtual
Access the volumetric flux.
alphaPhi() [3/6]
virtual tmp<surfaceScalarField> alphaPhi () const pure virtual
Constant access the volumetric flux of the phase.
alphaPhi() [4/6]
virtual surfaceScalarField& alphaPhi () pure virtual
Access the volumetric flux of the phase.
alphaRhoPhi() [1/4]
virtual tmp<surfaceScalarField> alphaRhoPhi () const pure virtual
Constant access the mass flux of the phase.
Referenced by phaseModel::iNew::operator()().
alphaRhoPhi() [2/4]
virtual surfaceScalarField& alphaRhoPhi () pure virtual
Access the mass flux of the phase.
mu() [1/4]
virtual tmp<volScalarField> mu () const pure virtual
Return the laminar dynamic viscosity.
Referenced by phaseModel::iNew::operator()().
mu() [2/4]
virtual tmp<scalarField> mu (const label patchi) const pure virtual
Return the laminar dynamic viscosity on a patch.
nu() [2/5]
virtual tmp<volScalarField> nu () const pure virtual
Return the laminar kinematic viscosity.
Implements transportModel.
nu() [3/5]
virtual tmp<scalarField> nu (const label patchi) const pure virtual
Return the laminar kinematic viscosity on a patch.
Implements transportModel.
kappa() [2/5]
virtual tmp<volScalarField> kappa () const pure virtual
Return the laminar thermal conductivity.
kappa() [3/5]
virtual tmp<scalarField> kappa (const label patchi) const pure virtual
Return the laminar thermal conductivity on a patch.
kappaEff() [1/4]
virtual tmp<volScalarField> kappaEff (const volScalarField & alphat) const pure virtual
Return the effective thermal conductivity.
Referenced by phaseModel::kappa(), phaseModel::kappaEff(), and phaseModel::iNew::operator()().
kappaEff() [2/4]
virtual tmp<scalarField> kappaEff (const scalarField & alphat, const label patchi) const pure virtual
Access the effective thermal conductivity.
alpha() [1/4]
virtual tmp<volScalarField> alpha () const pure virtual
Return the laminar thermal diffusivity for enthalpy.
Referenced by phaseModel::iNew::operator()().
alpha() [2/4]
virtual tmp<scalarField> alpha (const label patchi) const pure virtual
Return the laminar thermal diffusivity for enthalpy on a patch.
alphaEff() [1/4]
virtual tmp<volScalarField> alphaEff (const volScalarField & alphat) const pure virtual
Return the effective thermal diffusivity for enthalpy.
Referenced by phaseModel::alpha(), phaseModel::alphaEff(), and phaseModel::iNew::operator()().
alphaEff() [2/4]
virtual tmp<scalarField> alphaEff (const scalarField & alphat, const label patchi) const pure virtual
Return the effective thermal diffusivity for enthalpy on a patch.
turbulence() [1/3]
virtual const phaseCompressibleTurbulenceModel& turbulence () const pure virtual
Return the turbulence model.
Referenced by phaseModel::fluid(), and phaseModel::iNew::operator()().
name() [4/4]
const word& name () const inline
Return the name of this phase.
Definition at line 121 of file phaseModel.H.
fluid() [2/2]
const twoPhaseSystem& fluid () const inline
Return the twoPhaseSystem to which this phase belongs.
Definition at line 127 of file phaseModel.H.
References phaseModel::alphaMax(), phaseModel::d(), phaseModel::otherPhase(), phaseModel::residualAlpha(), and phaseModel::turbulence().
otherPhase()
const phaseModel& otherPhase () const
Return the other phase in this two-phase system.
Referenced by phaseModel::fluid(), and IATEsource::otherPhase().
residualAlpha() [2/2]
const dimensionedScalar& residualAlpha () const inline
Return the residual phase-fraction for given phase.
Used to stabilize the phase momentum as the phase-fraction -> 0
Definition at line 137 of file phaseModel.H.
alphaMax() [2/2]
scalar alphaMax () const inline
Optional maximum phase-fraction (e.g. packing limit)
Defaults to 1
Definition at line 144 of file phaseModel.H.
d() [3/3]
tmp<volScalarField> d () const
Return the Sauter-mean diameter.
turbulence() [2/3]
const PhaseCompressibleTurbulenceModel<phaseModel>& turbulence () const
Return the turbulence model.
turbulence() [3/3]
PhaseCompressibleTurbulenceModel<phaseModel>& turbulence ()
Return non-const access to the turbulence model.
for correction
thermo() [5/6]
const rhoThermo& thermo () const inline
Return the thermophysical model.
Definition at line 162 of file phaseModel.H.
References phaseModel::thermo().
thermo() [6/6]
rhoThermo& thermo () inline
Return non-const access to the thermophysical model.
for correction
Definition at line 169 of file phaseModel.H.
nu() [4/5]
tmp<volScalarField> nu () const inline virtual
Return the laminar viscosity.
Implements transportModel.
Definition at line 175 of file phaseModel.H.
nu() [5/5]
tmp<scalarField> nu (const label patchi) const inline virtual
Return the laminar viscosity for patch.
Implements transportModel.
Definition at line 181 of file phaseModel.H.
mu() [3/4]
tmp<volScalarField> mu () const inline
Return the laminar dynamic viscosity.
Definition at line 187 of file phaseModel.H.
mu() [4/4]
tmp<scalarField> mu (const label patchi) const inline
Return the laminar dynamic viscosity for patch.
Definition at line 193 of file phaseModel.H.
kappa() [4/5]
tmp<scalarField> kappa (const label patchi) const inline
Return the thermal conductivity on a patch.
Definition at line 199 of file phaseModel.H.
kappa() [5/5]
tmp<volScalarField> kappa () const inline
Return the thermal conductivity.
Definition at line 205 of file phaseModel.H.
References phaseModel::kappaEff().
kappaEff() [3/4]
tmp<volScalarField> kappaEff (const volScalarField & alphat) const inline
Return the laminar thermal conductivity.
Definition at line 212 of file phaseModel.H.
References phaseModel::kappaEff().
kappaEff() [4/4]
tmp<scalarField> kappaEff (const scalarField & alphat, const label patchi) const inline
Return the laminar thermal conductivity on a patch.
Definition at line 221 of file phaseModel.H.
alpha() [3/4]
tmp<volScalarField> alpha () const inline
Return the laminar thermal diffusivity for enthalpy.
Definition at line 230 of file phaseModel.H.
alpha() [4/4]
tmp<scalarField> alpha (const label patchi) const inline
Return the laminar thermal diffusivity for enthalpy on a patch.
Definition at line 236 of file phaseModel.H.
References phaseModel::alphaEff().
alphaEff() [3/4]
tmp<volScalarField> alphaEff (const volScalarField & alphat) const inline
Return the effective thermal diffusivity for enthalpy.
Definition at line 243 of file phaseModel.H.
References phaseModel::alphaEff().
alphaEff() [4/4]
tmp<scalarField> alphaEff (const scalarField & alphat, const label patchi) const inline
Return the effective thermal diffusivity for enthalpy on a patch.
Definition at line 252 of file phaseModel.H.
Cp() [2/2]
tmp<volScalarField> Cp () const inline
Return the specific heat capacity.
Definition at line 261 of file phaseModel.H.
rho() [3/3]
const volScalarField& rho () const inline
Return the density.
Definition at line 267 of file phaseModel.H.
U() [5/6]
const volVectorField& U () const inline
Return the velocity.
Definition at line 273 of file phaseModel.H.
References phaseModel::U().
U() [6/6]
volVectorField& U () inline
Return non-const access to the velocity.
Used in the momentum equation
Definition at line 280 of file phaseModel.H.
phi() [5/6]
const surfaceScalarField& phi () const inline
Return the volumetric flux.
Definition at line 286 of file phaseModel.H.
phi() [6/6]
surfaceScalarField& phi () inline
Return non-const access to the volumetric flux.
Definition at line 292 of file phaseModel.H.
alphaPhi() [5/6]
const surfaceScalarField& alphaPhi () const inline
Return the volumetric flux of the phase.
Definition at line 298 of file phaseModel.H.
alphaPhi() [6/6]
surfaceScalarField& alphaPhi () inline
Return non-const access to the volumetric flux of the phase.
Definition at line 304 of file phaseModel.H.
alphaRhoPhi() [3/4]
const surfaceScalarField& alphaRhoPhi () const inline
Return the mass flux of the phase.
Definition at line 310 of file phaseModel.H.
alphaRhoPhi() [4/4]
surfaceScalarField& alphaRhoPhi () inline
Return non-const access to the mass flux of the phase.
Definition at line 316 of file phaseModel.H.
References phaseModel::correct(), and phaseModel::read().
correct() [4/4]
void correct () virtual
Correct the phase properties.
other than the thermodynamics and turbulence which have special treatment
Implements transportModel.
read() [3/4]
virtual bool read (const dictionary & phaseProperties) virtual
Read phaseProperties dictionary.
read() [4/4]
virtual bool read () inline virtual
Dummy Read for transportModel.
Implements transportModel.
Definition at line 330 of file phaseModel.H.
The documentation for this class was generated from the following file:
applications/solvers/multiphase/compressibleMultiphaseInterFoam/multiphaseMixtureThermo/phaseModel/phaseModel.H