OpenFOAM: phase Class Reference
phase Class Reference
Single incompressible phase derived from the phase-fraction. Used as part of the multiPhaseMixture for interface-capturing multi-phase simulations.
Classes
class iNew
Return a pointer to a new phase created on freestore.
Public Member Functions
phase (const word &name, const dictionary &phaseDict, const volVectorField &U, const surfaceScalarField &phi)
Construct from components.
autoPtr< phase > clone () const
Return clone.
const word & name () const
const word & keyword () const
const viscosityModel & nuModel () const
Return const-access to phase1 viscosityModel.
tmp< volScalarField > nu () const
Return the kinematic laminar viscosity.
tmp< scalarField > nu (const label patchi) const
Return the laminar viscosity for patch.
const dimensionedScalar & rho () const
Return const-access to phase1 density.
void correct ()
Correct the phase properties.
bool read (const dictionary &phaseDict)
Read base transportProperties dictionary.
Public Member Functions inherited from GeometricField< Type, PatchField, GeoMesh >
TypeName ("GeometricField")
Runtime type information.
GeometricField (const IOobject &, const Mesh &, const dimensionSet &, const word &patchFieldType=PatchField< Type >::calculatedType())
Constructor given IOobject, mesh, dimensions and patch type.
GeometricField (const IOobject &, const Mesh &, const dimensionSet &, const wordList &wantedPatchTypes, const wordList &actualPatchTypes=wordList())
Constructor given IOobject, mesh, dimensions and patch types.
GeometricField (const IOobject &, const Mesh &, const dimensioned< Type > &, const word &patchFieldType=PatchField< Type >::calculatedType())
Constructor given IOobject, mesh, dimensioned<Type> and patch type.
GeometricField (const IOobject &, const Mesh &, const dimensioned< Type > &, const wordList &wantedPatchTypes, const wordList &actualPatchTypes=wordList())
Constructor given IOobject, mesh, dimensioned<Type> and patch types.
GeometricField (const IOobject &, const Internal &, const PtrList< PatchField< Type >> &)
Constructor from components.
GeometricField (const IOobject &, const Mesh &, const dimensionSet &, const Field< Type > &, const PtrList< PatchField< Type >> &)
Constructor from components.
GeometricField (const IOobject &, const Mesh &)
Construct and read given IOobject.
GeometricField (const IOobject &, const Mesh &, const dictionary &)
Construct from dictionary.
GeometricField (const GeometricField< Type, PatchField, GeoMesh > &)
Construct as copy.
GeometricField (const tmp< GeometricField< Type, PatchField, GeoMesh >> &)
Construct as copy of tmp<GeometricField> deleting argument.
GeometricField (const IOobject &, const GeometricField< Type, PatchField, GeoMesh > &)
Construct as copy resetting IO parameters.
GeometricField (const IOobject &, const tmp< GeometricField< Type, PatchField, GeoMesh >> &)
Construct as copy of tmp<GeometricField> resetting IO parameters.
GeometricField (const word &newName, const GeometricField< Type, PatchField, GeoMesh > &)
Construct as copy resetting name.
GeometricField (const word &newName, const tmp< GeometricField< Type, PatchField, GeoMesh >> &)
Construct as copy resetting name.
GeometricField (const IOobject &, const GeometricField< Type, PatchField, GeoMesh > &, const word &patchFieldType)
Construct as copy resetting IO parameters and patch type.
GeometricField (const IOobject &, const GeometricField< Type, PatchField, GeoMesh > &, const wordList &patchFieldTypes, const wordList &actualPatchTypes=wordList())
Construct as copy resetting IO parameters and boundary types.
GeometricField (const IOobject &, const tmp< GeometricField< Type, PatchField, GeoMesh >> &, const wordList &patchFieldTypes, const wordList &actualPatchTypes=wordList())
Construct as copy resetting IO parameters and boundary types.
virtual ~GeometricField ()
Destructor.
Internal & ref ()
Return a reference to the dimensioned internal field.
const Internal & internalField () const
Return a const-reference to the dimensioned internal field.
const Internal & v () const
Return a const-reference to the dimensioned internal field.
Internal::FieldType & primitiveFieldRef ()
Return a reference to the internal field.
const Internal::FieldType & primitiveField () const
Return a const-reference to the internal field.
Boundary & boundaryFieldRef ()
Return a reference to the boundary field.
const Boundary & boundaryField () const
Return const-reference to the boundary field.
label timeIndex () const
Return the time index of the field.
label & timeIndex ()
Return the time index of the field.
void storeOldTimes () const
Store the old-time fields.
void storeOldTime () const
Store the old-time field.
label nOldTimes () const
Return the number of old time fields stored.
const GeometricField< Type, PatchField, GeoMesh > & oldTime () const
Return old time field.
GeometricField< Type, PatchField, GeoMesh > & oldTime ()
Return non-const old time field.
void storePrevIter () const
Store the field as the previous iteration value.
const GeometricField< Type, PatchField, GeoMesh > & prevIter () const
Return previous iteration field.
void correctBoundaryConditions ()
Correct boundary field.
bool needReference () const
Does the field need a reference level for solution.
tmp< GeometricField< cmptType, PatchField, GeoMesh > > component (const direction) const
Return a component of the field.
bool writeData (Ostream &) const
WriteData member function required by regIOobject.
tmp< GeometricField< Type, PatchField, GeoMesh > > T () const
Return transpose (only if it is a tensor field)
void relax (const scalar alpha)
Relax field (for steady-state solution).
void relax ()
Relax field (for steady-state solution).
word select (bool final) const
Select the final iteration parameters if `final' is true.
void writeMinMax (Ostream &os) const
Helper function to write the min and max to an Ostream.
void negate ()
void replace (const direction, const GeometricField< cmptType, PatchField, GeoMesh > &)
void replace (const direction, const dimensioned< cmptType > &)
void max (const dimensioned< Type > &)
void min (const dimensioned< Type > &)
void max (const GeometricField< Type, PatchField, GeoMesh > &, const dimensioned< Type > &)
void min (const GeometricField< Type, PatchField, GeoMesh > &, const dimensioned< Type > &)
void scale (const GeometricField< Type, PatchField, GeoMesh > &, const GeometricField< Type, PatchField, GeoMesh > &)
void scale (const GeometricField< Type, PatchField, GeoMesh > &, const dimensioned< Type > &)
const Internal & operator() () const
Return a const-reference to the dimensioned internal field.
void operator= (const GeometricField< Type, PatchField, GeoMesh > &)
void operator= (const tmp< GeometricField< Type, PatchField, GeoMesh >> &)
void operator= (const dimensioned< Type > &)
void operator== (const tmp< GeometricField< Type, PatchField, GeoMesh >> &)
void operator== (const dimensioned< Type > &)
void operator+= (const GeometricField< Type, PatchField, GeoMesh > &)
void operator+= (const tmp< GeometricField< Type, PatchField, GeoMesh >> &)
void operator-= (const GeometricField< Type, PatchField, GeoMesh > &)
void operator-= (const tmp< GeometricField< Type, PatchField, GeoMesh >> &)
void operator*= (const GeometricField< scalar, PatchField, GeoMesh > &)
void operator*= (const tmp< GeometricField< scalar, PatchField, GeoMesh >> &)
void operator/= (const GeometricField< scalar, PatchField, GeoMesh > &)
void operator/= (const tmp< GeometricField< scalar, PatchField, GeoMesh >> &)
void operator+= (const dimensioned< Type > &)
void operator-= (const dimensioned< Type > &)
void operator*= (const dimensioned< scalar > &)
void operator/= (const dimensioned< scalar > &)
template<>
tmp< GeometricField< scalar, fvPatchField, volMesh > > component (const direction) const
template<>
void replace (const direction, const GeometricField< scalar, fvPatchField, volMesh > &gsf)
template<>
tmp< GeometricField< scalar, fvPatchField, volMesh > > component (const direction) const
template<>
void replace (const direction, const GeometricField< scalar, fvPatchField, volMesh > &sf)
Public Member Functions inherited from DimensionedField< Type, GeoMesh >
TypeName ("DimensionedField")
Runtime type information.
DimensionedField (const IOobject &, const Mesh &mesh, const dimensionSet &, const Field< Type > &)
Construct from components.
DimensionedField (const IOobject &, const Mesh &mesh, const dimensionSet &, const bool checkIOFlags=true)
Construct from components.
DimensionedField (const IOobject &, const Mesh &mesh, const dimensioned< Type > &, const bool checkIOFlags=true)
Construct from components.
DimensionedField (const IOobject &, const Mesh &mesh, const word &fieldDictEntry="value")
Construct from Istream.
DimensionedField (const IOobject &, const Mesh &mesh, const dictionary &fieldDict, const word &fieldDictEntry="value")
Construct from dictionary.
DimensionedField (const DimensionedField< Type, GeoMesh > &)
Construct as copy.
DimensionedField (DimensionedField< Type, GeoMesh > &, bool reuse)
Construct as copy or re-use as specified.
DimensionedField (const Xfer< DimensionedField< Type, GeoMesh >> &)
Construct by transferring the DimensionedField.
DimensionedField (const tmp< DimensionedField< Type, GeoMesh >> &)
Construct as copy of tmp<DimensionedField> deleting argument.
DimensionedField (const IOobject &, const DimensionedField< Type, GeoMesh > &)
Construct as copy resetting IO parameters.
DimensionedField (const IOobject &, DimensionedField< Type, GeoMesh > &, bool reuse)
Construct as copy resetting IO parameters and re-use as specified.
DimensionedField (const word &newName, const DimensionedField< Type, GeoMesh > &)
Construct as copy resetting name.
DimensionedField (const word &newName, DimensionedField< Type, GeoMesh > &, bool reuse)
Construct as copy resetting name and re-use as specified.
DimensionedField (const word &newName, const Xfer< DimensionedField< Type, GeoMesh >> &)
Construct by transferring the DimensionedField with a new name.
DimensionedField (const word &newName, const tmp< DimensionedField< Type, GeoMesh >> &)
Construct as copy resetting name.
tmp< DimensionedField< Type, GeoMesh > > clone () const
Clone.
virtual ~DimensionedField ()
Destructor.
void readField (const dictionary &fieldDict, const word &fieldDictEntry="value")
const Mesh & mesh () const
Return mesh.
const dimensionSet & dimensions () const
Return dimensions.
dimensionSet & dimensions ()
Return non-const access to dimensions.
const Field< Type > & field () const
Field< Type > & field ()
tmp< DimensionedField< cmptType, GeoMesh > > component (const direction) const
Return a component field of the field.
void replace (const direction, const DimensionedField< cmptType, GeoMesh > &)
Replace a component field of the field.
void replace (const direction, const tmp< DimensionedField< cmptType, GeoMesh >> &)
Replace a component field of the field.
tmp< DimensionedField< Type, GeoMesh > > T () const
Return the field transpose (only defined for second rank tensors)
dimensioned< Type > average () const
Calculate and return arithmetic average.
dimensioned< Type > weightedAverage (const DimensionedField< scalar, GeoMesh > &) const
Calculate and return weighted average.
dimensioned< Type > weightedAverage (const tmp< DimensionedField< scalar, GeoMesh >> &) const
Calculate and return weighted average.
bool writeData (Ostream &, const word &fieldDictEntry) const
void operator= (const DimensionedField< Type, GeoMesh > &)
void operator= (const tmp< DimensionedField< Type, GeoMesh >> &)
void operator= (const dimensioned< Type > &)
void operator+= (const DimensionedField< Type, GeoMesh > &)
void operator+= (const tmp< DimensionedField< Type, GeoMesh >> &)
void operator-= (const DimensionedField< Type, GeoMesh > &)
void operator-= (const tmp< DimensionedField< Type, GeoMesh >> &)
void operator*= (const DimensionedField< scalar, GeoMesh > &)
void operator*= (const tmp< DimensionedField< scalar, GeoMesh >> &)
void operator/= (const DimensionedField< scalar, GeoMesh > &)
void operator/= (const tmp< DimensionedField< scalar, GeoMesh >> &)
void operator+= (const dimensioned< Type > &)
void operator-= (const dimensioned< Type > &)
void operator*= (const dimensioned< scalar > &)
void operator/= (const dimensioned< scalar > &)
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &, const bool isTime=false)
Construct from IOobject. Optional flag for if IOobject is the.
regIOobject (const regIOobject &)
Construct as copy.
regIOobject (const regIOobject &, bool registerCopy)
Construct as copy, transferring registry registration to copy.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Construct as copy with new name, transfering registry registration.
regIOobject (const IOobject &, const regIOobject &)
Construct as copy with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry.
bool checkOut ()
Remove object from registry.
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release ()
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set up to date (obviously)
virtual void rename (const word &newName)
Rename.
Istream & readStream (const word &)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool readData (Istream &)
Virtual readData function.
virtual bool read ()
Read object.
label watchIndex () const
Return file-monitoring handle.
label & watchIndex ()
Return file-monitoring handle.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType) const
Write using given format, version and compression.
virtual bool write () const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from path, registry, io options.
Foam::autoPtr< IOobject > clone () const
Clone.
virtual ~IOobject ()
Destructor.
const Time & time () const
Return time.
const objectRegistry & db () const
Return the local objectRegistry.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
string & note ()
Return non-constant access to the optional note.
const string & note () const
Return the optional note.
bool & registerObject ()
Register object created from this IOobject with registry if true.
bool registerObject () const
Register object created from this IOobject with registry if true.
readOption readOpt () const
readOption & readOpt ()
writeOption writeOpt () const
writeOption & writeOpt ()
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
Return complete path.
fileName path (const word &instance, const fileName &local="") const
Return complete path with alternative instance and local.
fileName objectPath () const
Return complete path + object name.
fileName filePath () const
Return complete path + object name if the file exists.
bool readHeader (Istream &)
Read header.
bool headerOk ()
Read and check header info.
bool writeHeader (Ostream &) const
Write header.
bool writeHeader (Ostream &, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &)
template<class Name >
Foam::word groupName (Name name, const word &group)
Public Member Functions inherited from Field< Type >
Field ()
Construct null.
Field (const label)
Construct given size.
Field (const label, const Type &)
Construct given size and initial value.
Field (const label, const zero)
Construct given size and initialed to zero.
Field (const UList< Type > &)
Construct as copy of a UList<Type>
Field (const Xfer< List< Type >> &)
Construct by transferring the List contents.
Field (const UList< Type > &mapF, const labelUList &mapAddressing)
Construct by 1 to 1 mapping from the given field.
Field (const tmp< Field< Type >> &tmapF, const labelUList &mapAddressing)
Construct by 1 to 1 mapping from the given tmp field.
Field (const UList< Type > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Construct by interpolative mapping from the given field.
Field (const tmp< Field< Type >> &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Construct by interpolative mapping from the given tmp field.
Field (const UList< Type > &mapF, const FieldMapper &map, const bool applyFlip=true)
Construct by mapping from the given field.
Field (const UList< Type > &mapF, const FieldMapper &map, const Type &defaultValue, const bool applyFlip=true)
Construct by mapping from the given field.
Field (const UList< Type > &mapF, const FieldMapper &map, const UList< Type > &defaultValues, const bool applyFlip=true)
Construct by mapping from the given field.
Field (const tmp< Field< Type >> &tmapF, const FieldMapper &map, const bool applyFlip=true)
Construct by mapping from the given tmp field.
Field (const tmp< Field< Type >> &tmapF, const FieldMapper &map, const Type &defaultValue, const bool applyFlip=true)
Construct by mapping from the given tmp field. Supplied uniform.
Field (const tmp< Field< Type >> &tmapF, const FieldMapper &map, const UList< Type > &defaultValues, const bool applyFlip=true)
Construct by mapping from the given tmp field. Supplied values.
Field (const Field< Type > &)
Construct as copy.
Field (Field< Type > &, bool reuse)
Construct as copy or re-use as specified.
Field (const Xfer< Field< Type >> &)
Construct by transferring the Field contents.
Field (const tmp< Field< Type >> &)
Construct as copy of tmp<Field>
Field (Istream &)
Construct from Istream.
Field (const word &keyword, const dictionary &, const label size)
Construct from a dictionary entry.
tmp< Field< Type > > clone () const
Clone.
void map (const UList< Type > &mapF, const labelUList &mapAddressing)
1 to 1 map from the given field
void map (const tmp< Field< Type >> &tmapF, const labelUList &mapAddressing)
1 to 1 map from the given tmp field
void map (const UList< Type > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Interpolative map from the given field.
void map (const tmp< Field< Type >> &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Interpolative map from the given tmp field.
void map (const UList< Type > &mapF, const FieldMapper &map, const bool applyFlip=true)
Map from the given field.
void map (const tmp< Field< Type >> &tmapF, const FieldMapper &map, const bool applyFlip=true)
Map from the given tmp field.
void autoMap (const FieldMapper &map, const bool applyFlip=true)
Map from self.
void rmap (const UList< Type > &mapF, const labelUList &mapAddressing)
1 to 1 reverse-map from the given field
void rmap (const tmp< Field< Type >> &tmapF, const labelUList &mapAddressing)
1 to 1 reverse-map from the given tmp field
void rmap (const UList< Type > &mapF, const labelUList &mapAddressing, const UList< scalar > &weights)
Interpolative reverse map from the given field.
void rmap (const tmp< Field< Type >> &tmapF, const labelUList &mapAddressing, const UList< scalar > &weights)
Interpolative reverse map from the given tmp field.
void negate ()
Negate this field.
tmp< Field< cmptType > > component (const direction) const
Return a component field of the field.
void replace (const direction, const UList< cmptType > &)
Replace a component field of the field.
void replace (const direction, const tmp< Field< cmptType >> &)
Replace a component field of the field.
void replace (const direction, const cmptType &)
Replace a component field of the field.
template<class VSForm >
VSForm block (const label start) const
tmp< Field< Type > > T () const
Return the field transpose (only defined for second rank tensors)
void writeEntry (const word &keyword, Ostream &os) const
Write the field as a dictionary entry.
void operator= (const Field< Type > &)
void operator= (const UList< Type > &)
void operator= (const SubField< Type > &)
void operator= (const tmp< Field< Type >> &)
void operator= (const Type &)
void operator= (const zero)
template<class Form , class Cmpt , direction nCmpt>
void operator= (const VectorSpace< Form, Cmpt, nCmpt > &)
void operator+= (const UList< Type > &)
void operator+= (const tmp< Field< Type >> &)
void operator-= (const UList< Type > &)
void operator-= (const tmp< Field< Type >> &)
void operator*= (const UList< scalar > &)
void operator*= (const tmp< Field< scalar >> &)
void operator/= (const UList< scalar > &)
void operator/= (const tmp< Field< scalar >> &)
void operator+= (const Type &)
void operator-= (const Type &)
void operator*= (const scalar &)
void operator/= (const scalar &)
template<class Type>
void operator= (const tmp< Field > &rhs)
Public Member Functions inherited from refCount
int count () const
Return the current reference count.
bool unique () const
Return true if the reference count is zero.
void operator++ ()
Increment the reference count.
void operator++ (int)
Increment the reference count.
void operator-- ()
Decrement the reference count.
void operator-- (int)
Decrement the reference count.
Public Member Functions inherited from List< Type >
List ()
Null constructor.
List (const label)
Construct with given size.
List (const label, const Type &)
Construct with given size and value for all elements.
List (const label, const zero)
Construct with given size initializing all elements to zero.
List (const List< Type > &)
Copy constructor.
List (const List< T2 > &)
Copy constructor from list containing another type.
List (const Xfer< List< Type >> &)
Construct by transferring the parameter contents.
List (List< Type > &, bool reuse)
Construct as copy or re-use as specified.
List (const UList< Type > &, const labelUList &mapAddressing)
Construct as subset.
List (InputIterator first, InputIterator last)
Construct given start and end iterators.
List (const FixedList< Type, Size > &)
Construct as copy of FixedList<T, Size>
List (const PtrList< Type > &)
Construct as copy of PtrList<T>
List (const SLList< Type > &)
Construct as copy of SLList<T>
List (const UIndirectList< Type > &)
Construct as copy of UIndirectList<T>
List (const BiIndirectList< Type > &)
Construct as copy of BiIndirectList<T>
List (std::initializer_list< Type >)
Construct from an initializer list.
List (Istream &)
Construct from Istream.
label size () const
Return the number of elements in the UList.
autoPtr< List< Type > > clone () const
Clone.
~List ()
Destructor.
void resize (const label)
Alias for setSize(const label)
void resize (const label, const Type &)
Alias for setSize(const label, const T&)
void setSize (const label)
Reset size of List.
void setSize (const label, const Type &)
Reset size of List and value for new elements.
void clear ()
Clear the list, i.e. set size to zero.
void append (const Type &)
Append an element at the end of the list.
void append (const UList< Type > &)
Append a List at the end of this list.
void append (const UIndirectList< Type > &)
Append a UIndirectList at the end of this list.
void transfer (List< Type > &)
Transfer the contents of the argument List into this list.
void transfer (DynamicList< Type, SizeInc, SizeMult, SizeDiv > &)
Transfer the contents of the argument List into this list.
void transfer (SortableList< Type > &)
Transfer the contents of the argument List into this list.
Xfer< List< Type > > xfer ()
Transfer contents to the Xfer container.
Type & newElmt (const label)
Return subscript-checked element of UList.
void shallowCopy (const UList< Type > &)=delete
Disallow implicit shallowCopy.
void operator= (const UList< Type > &)
Assignment to UList operator. Takes linear time.
void operator= (const List< Type > &)
Assignment operator. Takes linear time.
void operator= (const SLList< Type > &)
Assignment to SLList operator. Takes linear time.
void operator= (const UIndirectList< Type > &)
Assignment to UIndirectList operator. Takes linear time.
void operator= (const BiIndirectList< Type > &)
Assignment to BiIndirectList operator. Takes linear time.
void operator= (std::initializer_list< Type >)
Assignment to an initializer list.
void operator= (const Type &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
Public Member Functions inherited from UList< Type >
void operator= (const Type &)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
UList ()
Null constructor.
UList (Type *__restrict__ v, label size)
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. the next index.
label rcIndex (const label i) const
Return the reverse circular index, i.e. the previous index.
std::streamsize byteSize () const
Return the binary size in number of characters of the UList.
const Type * cdata () const
Return a const pointer to the first data element,.
Type * data ()
Return a pointer to the first data element,.
Type & first ()
Return the first element of the list.
const Type & first () const
Return first element of the list.
Type & last ()
Return the last element of the list.
const Type & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range (0 ... size-1)
void checkSize (const label size) const
Check size is within valid range (0 ... size)
void checkIndex (const label i) const
Check index i is within valid range (0 ... size-1)
void shallowCopy (const UList< Type > &)
Copy the pointer held by the given UList.
void deepCopy (const UList< Type > &)
Copy elements of the given UList.
void writeEntry (Ostream &) const
Write the UList as a dictionary entry.
void writeEntry (const word &keyword, Ostream &) const
Write the UList as a dictionary entry with keyword.
Type & operator[] (const label)
Return element of UList.
const Type & operator[] (const label) const
Return element of constant UList.
const bool & operator[] (const label i) const
operator const Foam::List< Type > & () const
Allow cast to a const List<T>&.
iterator begin ()
Return an iterator to begin traversing the UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const
Return the number of elements in the UList.
label max_size () const
Return size of the largest possible UList.
bool empty () const
Return true if the UList is empty (ie, size() is zero)
void swap (UList< Type > &)
Swap two ULists of the same type in constant time.
bool operator== (const UList< Type > &) const
Equality operation on ULists of the same type.
bool operator!= (const UList< Type > &) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< Type > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< Type > &) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< Type > &) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< Type > &) const
Return true if !(a < b). Takes linear time.
Additional Inherited Members
Public Types inherited from GeometricField< Type, PatchField, GeoMesh >
typedef GeoMesh::Mesh Mesh
Type of mesh on which this GeometricField is instantiated.
typedef GeoMesh::BoundaryMesh BoundaryMesh
Type of boundary mesh on which this.
typedef DimensionedField< Type, GeoMesh > Internal
Type of the internal field from which this GeometricField is derived.
typedef PatchField< Type > Patch
Type of the patch field of which the.
typedef Field< Type >::cmptType cmptType
Public Types inherited from DimensionedField< Type, GeoMesh >
typedef GeoMesh::Mesh Mesh
Type of mesh on which this DimensionedField is instantiated.
typedef Field< Type > FieldType
Type of the field from which this DimensionedField is derived.
typedef Field< Type >::cmptType cmptType
Component type of the elements of the field.
Public Types inherited from regIOobject
enum fileCheckTypes { timeStamp, timeStampMaster, inotify, inotifyMaster }
Types of communications.
Public Types inherited from IOobject
enum objectState { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
Public Types inherited from Field< Type >
typedef pTraits< Type >::cmptType cmptType
Component type.
typedef SubField< Type > subField
Declare type of subField.
Public Types inherited from List< Type >
typedef SubList< Type > subList
Declare type of subList.
Public Types inherited from UList< Type >
typedef Type value_type
Type of values the UList contains.
typedef Type & reference
Type that can be used for storing into.
typedef const Type & const_reference
Type that can be used for storing into.
typedef label difference_type
The type that can represent the difference between any two.
typedef label size_type
The type that can represent the size of a UList.
typedef Type * iterator
Random access iterator for traversing UList.
typedef const Type * const_iterator
Random access iterator for traversing UList.
typedef Type * reverse_iterator
Reverse iterator for reverse traversal of UList.
typedef const Type * const_reverse_iterator
Reverse iterator for reverse traversal of constant UList.
Static Public Member Functions inherited from GeometricField< Type, PatchField, GeoMesh >
static const GeometricField< Type, PatchField, GeoMesh > & null ()
Return a null geometric field.
Static Public Member Functions inherited from DimensionedField< Type, GeoMesh >
static const DimensionedField< Type, GeoMesh > & null ()
Return a null DimensionedField.
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class Name >
static word groupName (Name name, const word &group)
template<class Stream >
static Stream & writeBanner (Stream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
template<class Stream >
static Stream & writeDivider (Stream &os)
Write the standard file section divider.
template<class Stream >
static Stream & writeEndDivider (Stream &os)
Write the standard end file divider.
Static Public Member Functions inherited from Field< Type >
static const Field< Type > & null ()
Return a null field.
template<class Type2 >
static tmp< Field< Type > > NewCalculatedType (const Field< Type2 > &f)
Return a pointer to a new calculatedFvPatchFieldField created on.
Static Public Member Functions inherited from List< Type >
static const List< Type > & null ()
Return a null List.
Static Public Member Functions inherited from UList< Type >
static const UList< Type > & null ()
Return a null UList.
Static Public Attributes inherited from regIOobject
static const NamedEnum< fileCheckTypes, 4 > fileCheckTypesNames
static int fileModificationSkew
static fileCheckTypes fileModificationChecking
Static Public Attributes inherited from Field< Type >
static const char *const typeName
Protected Member Functions inherited from IOobject
Istream * objectStream ()
Construct and return an IFstream for the object.
Istream * objectStream (const fileName &)
Construct and return an IFstream for the object given the.
void setBad (const string &)
Set the object state to bad.
Protected Member Functions inherited from refCount
refCount ()
Construct null initializing count to 0.
Protected Member Functions inherited from List< Type >
void size (const label)
Override size to be inconsistent with allocated storage.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
Single incompressible phase derived from the phase-fraction. Used as part of the multiPhaseMixture for interface-capturing multi-phase simulations.
Source files
phase.H
phase.C
Definition at line 52 of file phase.H.
Constructor & Destructor Documentation
phase()
phase (const word & name, const dictionary & phaseDict, const volVectorField & U, const surfaceScalarField & phi)
Construct from components.
Referenced by phase::iNew::operator()().
Member Function Documentation
clone()
autoPtr<phase> clone () const
Return clone.
name()
const word& name () const inline
Definition at line 109 of file phase.H.
Referenced by phase::keyword().
keyword()
const word& keyword () const inline
Definition at line 114 of file phase.H.
References phase::name().
nuModel()
const viscosityModel& nuModel () const inline
Return const-access to phase1 viscosityModel.
Definition at line 120 of file phase.H.
nu() [1/2]
tmp<volScalarField> nu () const inline
Return the kinematic laminar viscosity.
Definition at line 126 of file phase.H.
nu() [2/2]
tmp<scalarField> nu (const label patchi) const inline
Return the laminar viscosity for patch.
Definition at line 132 of file phase.H.
rho()
const dimensionedScalar& rho () const inline
Return const-access to phase1 density.
Definition at line 138 of file phase.H.
References phase::correct(), and regIOobject::read().
correct()
void correct ()
Correct the phase properties.
Referenced by phase::rho().
read()
bool read (const dictionary & phaseDict)
Read base transportProperties dictionary.
The documentation for this class was generated from the following file:
applications/solvers/multiphase/multiphaseInterFoam/multiphaseMixture/phase/phase.H