OpenFOAM: diameterModel Class Reference
diameterModel Class Reference abstract
Abstract base-class for dispersed-phase particle diameter models.
Public Member Functions
TypeName ("diameterModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, diameterModel, dictionary,(const dictionary &dict, const phaseModel &phase),(dict, phase))
diameterModel (const dictionary &dict, const phaseModel &phase)
virtual ~diameterModel ()
Destructor.
virtual tmp< volScalarField > d () const =0
Return the phase mean diameter field.
TypeName ("diameterModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, diameterModel, dictionary,(const dictionary &diameterProperties, const phaseModel &phase),(diameterProperties, phase))
diameterModel (const dictionary &diameterProperties, const phaseModel &phase)
virtual ~diameterModel ()
Destructor.
const dictionary & diameterProperties () const
Return the phase diameter properties dictionary.
const phaseModel & phase () const
Return the phase.
virtual tmp< volScalarField > d () const =0
Return the phase mean diameter field.
virtual void correct ()
Correct the diameter field.
virtual bool read (const dictionary &phaseProperties)=0
Read phaseProperties dictionary.
TypeName ("diameterModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, diameterModel, dictionary,(const dictionary &diameterProperties, const phaseModel &phase),(diameterProperties, phase))
diameterModel (const dictionary &diameterProperties, const phaseModel &phase)
virtual ~diameterModel ()
Destructor.
const dictionary & diameterProperties () const
Return the phase diameter properties dictionary.
const phaseModel & phase () const
Return the phase.
virtual tmp< volScalarField > d () const =0
Return the phase mean diameter field.
virtual void correct ()
Correct the diameter field.
virtual bool read (const dictionary &phaseProperties)=0
Read phaseProperties dictionary.
Static Public Member Functions
static autoPtr< diameterModel > New (const dictionary &dict, const phaseModel &phase)
static autoPtr< diameterModel > New (const dictionary &diameterProperties, const phaseModel &phase)
static autoPtr< diameterModel > New (const dictionary &diameterProperties, const phaseModel &phase)
Protected Attributes
const dictionary & dict_
const phaseModel & phase_
dictionary diameterProperties_
Detailed Description
Abstract base-class for dispersed-phase particle diameter models.
A2stract base-class for dispersed-phase particle diameter models.
Source files
diameterModel.H
diameterModel.C
newDiameterModel.C
Source files
diameterModel.H
diameterModel.C
newDiameterModel.C
Source files
diameterModel.H
diameterModel.C
newDiameterModel.C
Definition at line 51 of file diameterModel.H.
Constructor & Destructor Documentation
diameterModel() [1/3]
diameterModel (const dictionary & dict, const phaseModel & phase)
~diameterModel() [1/3]
virtual ~diameterModel () virtual
Destructor.
diameterModel() [2/3]
diameterModel (const dictionary & diameterProperties, const phaseModel & phase)
~diameterModel() [2/3]
virtual ~diameterModel () virtual
Destructor.
diameterModel() [3/3]
diameterModel (const dictionary & diameterProperties, const phaseModel & phase)
~diameterModel() [3/3]
virtual ~diameterModel () virtual
Destructor.
Member Function Documentation
TypeName() [1/3]
TypeName ("diameterModel")
Runtime type information.
declareRunTimeSelectionTable() [1/3]
declareRunTimeSelectionTable (autoPtr , diameterModel , dictionary , (const dictionary &dict, const phaseModel &phase) , (dict, phase))
New() [1/3]
static autoPtr<diameterModel> New (const dictionary & dict, const phaseModel & phase) static
d() [1/3]
virtual tmp<volScalarField> d () const pure virtual
Return the phase mean diameter field.
Implemented in IATE, IATE, isothermal, isothermal, isothermal, constant, constant, and constant.
Referenced by diameterModel::phase().
TypeName() [2/3]
TypeName ("diameterModel")
Runtime type information.
declareRunTimeSelectionTable() [2/3]
declareRunTimeSelectionTable (autoPtr , diameterModel , dictionary , (const dictionary &diameterProperties, const phaseModel &phase) , (diameterProperties, phase))
New() [2/3]
static autoPtr<diameterModel> New (const dictionary & diameterProperties, const phaseModel & phase) static
diameterProperties() [1/2]
const dictionary& diameterProperties () const inline
Return the phase diameter properties dictionary.
Definition at line 108 of file diameterModel.H.
References diameterModel::diameterProperties_.
phase() [1/2]
const phaseModel& phase () const inline
Return the phase.
Definition at line 114 of file diameterModel.H.
References diameterModel::correct(), diameterModel::d(), diameterModel::phase_, and diameterModel::read().
Referenced by IATEsource::fluid(), and IATEsource::phase().
d() [2/3]
virtual tmp<volScalarField> d () const pure virtual
Return the phase mean diameter field.
Implemented in IATE, IATE, isothermal, isothermal, isothermal, constant, constant, and constant.
correct() [1/2]
virtual void correct () virtual
Correct the diameter field.
Reimplemented in IATE, and IATE.
Referenced by diameterModel::phase().
read() [1/2]
virtual bool read (const dictionary & phaseProperties) pure virtual
Read phaseProperties dictionary.
Implemented in IATE, IATE, isothermal, isothermal, constant, and constant.
Referenced by diameterModel::phase().
TypeName() [3/3]
TypeName ("diameterModel")
Runtime type information.
declareRunTimeSelectionTable() [3/3]
declareRunTimeSelectionTable (autoPtr , diameterModel , dictionary , (const dictionary &diameterProperties, const phaseModel &phase) , (diameterProperties, phase))
New() [3/3]
static autoPtr<diameterModel> New (const dictionary & diameterProperties, const phaseModel & phase) static
diameterProperties() [2/2]
const dictionary& diameterProperties () const inline
Return the phase diameter properties dictionary.
Definition at line 108 of file diameterModel.H.
References diameterModel::diameterProperties_.
phase() [2/2]
const phaseModel& phase () const inline
Return the phase.
Definition at line 114 of file diameterModel.H.
References diameterModel::correct(), diameterModel::d(), diameterModel::phase_, and diameterModel::read().
d() [3/3]
virtual tmp<volScalarField> d () const pure virtual
Return the phase mean diameter field.
Implemented in IATE, IATE, isothermal, isothermal, isothermal, constant, constant, and constant.
correct() [2/2]
virtual void correct () virtual
Correct the diameter field.
Reimplemented in IATE, and IATE.
read() [2/2]
virtual bool read (const dictionary & phaseProperties) pure virtual
Read phaseProperties dictionary.
Implemented in IATE, IATE, isothermal, isothermal, constant, and constant.
Member Data Documentation
dict_
const dictionary& dict_ protected
Definition at line 57 of file diameterModel.H.
phase_
const phaseModel & phase_ protected
Definition at line 58 of file diameterModel.H.
Referenced by IATE::a(), and diameterModel::phase().
diameterProperties_
dictionary diameterProperties_ protected
Definition at line 58 of file diameterModel.H.
Referenced by diameterModel::diameterProperties().
The documentation for this class was generated from the following file:
applications/solvers/multiphase/multiphaseEulerFoam/multiphaseSystem/diameterModels/diameterModel/diameterModel.H