OpenFOAM: alphatWallBoilingWallFunctionFvPatchScalarField Class Reference
alphatWallBoilingWallFunctionFvPatchScalarField Class Reference
Compressible turbulence » Compressible Turbulence BCs » Compressible turbulence wall functions
A thermal wall function for simulation of subcooled nucleate wall boiling.
Public Member Functions
TypeName ("compressible::alphatWallBoilingWallFunction")
Runtime type information.
alphatWallBoilingWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
alphatWallBoilingWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
alphatWallBoilingWallFunctionFvPatchScalarField (const alphatWallBoilingWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
alphatWallBoilingWallFunctionFvPatchScalarField (const alphatWallBoilingWallFunctionFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
alphatWallBoilingWallFunctionFvPatchScalarField (const alphatWallBoilingWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField
TypeName ("compressible::alphatPhaseChangeJayatillekeWallFunction")
Runtime type information.
alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField (const alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField (const alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField &)
Construct as copy.
alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField (const alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
Public Member Functions inherited from alphatPhaseChangeWallFunctionFvPatchScalarField
TypeName ("compressible::alphatPhaseChangeWallFunction")
Runtime type information.
alphatPhaseChangeWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
alphatPhaseChangeWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
alphatPhaseChangeWallFunctionFvPatchScalarField (const alphatPhaseChangeWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
alphatPhaseChangeWallFunctionFvPatchScalarField (const alphatPhaseChangeWallFunctionFvPatchScalarField &)
Construct as copy.
alphatPhaseChangeWallFunctionFvPatchScalarField (const alphatPhaseChangeWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
const scalarField & dmdt () const
Return the rate of phase-change.
const scalarField & mDotL () const
Return the enthelpy source due to phase-change.
Additional Inherited Members
Protected Member Functions inherited from alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField
void checkType ()
Check the type of the patch.
tmp< scalarField > Psmooth (const scalarField &Prat) const
'P' function
tmp< scalarField > yPlusTherm (const scalarField &P, const scalarField &Prat) const
Calculate y+ at the edge of the thermal laminar sublayer.
tmp< scalarField > calcAlphat (const scalarField &prevAlphat) const
Update turbulent thermal diffusivity.
Protected Attributes inherited from alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField
scalar Prt_
Turbulent Prandtl number.
scalar Cmu_
Cmu coefficient.
scalar kappa_
Von Karman constant.
scalar E_
E coefficient.
Protected Attributes inherited from alphatPhaseChangeWallFunctionFvPatchScalarField
scalarField dmdt_
Rate of phase-change.
scalarField mDotL_
Latent heat of the phase-change.
Static Protected Attributes inherited from alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField
static scalar maxExp_
static scalar tolerance_
static label maxIters_
Detailed Description
A thermal wall function for simulation of subcooled nucleate wall boiling.
Implements a version of the well-known RPI wall boiling model (Kurul & Podowski, 1991). The model implementation is similar to the model described by Peltola & Pättikangas (2012).
References:
    "On the modeling of multidimensional effects in boiling channels"
    Kurul, N., Podowski, M.Z.,
    ANS Proceedings, National Heat Transfer Conference,
    Minneapolis, Minnesota, USA, July 28-31, 1991,
    ISBN: 0-89448-162-1, pp. 30-40
    "Development and validation of a boiling model for OpenFOAM
    multiphase solver"
    Peltola, J., Pättikangas, T.J.H.,
    CFD4NRS-4 Conference Proceedings, paper 59,
    Daejeon, Korea, September 10-12 2012
See also
Foam::fixedValueFvPatchField
Source files
alphatWallBoilingWallFunctionFvPatchScalarField.H
alphatWallBoilingWallFunctionFvPatchScalarField.C
Definition at line 77 of file alphatWallBoilingWallFunctionFvPatchScalarField.H.
Constructor & Destructor Documentation
alphatWallBoilingWallFunctionFvPatchScalarField() [1/5]
alphatWallBoilingWallFunctionFvPatchScalarField (const fvPatch & , const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
Referenced by alphatWallBoilingWallFunctionFvPatchScalarField::clone().
alphatWallBoilingWallFunctionFvPatchScalarField() [2/5]
alphatWallBoilingWallFunctionFvPatchScalarField (const fvPatch & , const DimensionedField< scalar, volMesh > & , const dictionary &)
Construct from patch, internal field and dictionary.
alphatWallBoilingWallFunctionFvPatchScalarField() [3/5]
alphatWallBoilingWallFunctionFvPatchScalarField (const alphatWallBoilingWallFunctionFvPatchScalarField & , const fvPatch & , const DimensionedField< scalar, volMesh > & , const fvPatchFieldMapper &)
Construct by mapping given.
alphatWallBoilingWallFunctionFvPatchScalarField onto a new patch
alphatWallBoilingWallFunctionFvPatchScalarField() [4/5]
alphatWallBoilingWallFunctionFvPatchScalarField (const alphatWallBoilingWallFunctionFvPatchScalarField &)
Construct as copy.
alphatWallBoilingWallFunctionFvPatchScalarField() [5/5]
alphatWallBoilingWallFunctionFvPatchScalarField (const alphatWallBoilingWallFunctionFvPatchScalarField & , const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
Member Function Documentation
TypeName()
TypeName ("compressible::alphatWallBoilingWallFunction")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Reimplemented from alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField.
Definition at line 134 of file alphatWallBoilingWallFunctionFvPatchScalarField.H.
References alphatWallBoilingWallFunctionFvPatchScalarField::alphatWallBoilingWallFunctionFvPatchScalarField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Reimplemented from alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField.
Definition at line 151 of file alphatWallBoilingWallFunctionFvPatchScalarField.H.
References alphatWallBoilingWallFunctionFvPatchScalarField::alphatWallBoilingWallFunctionFvPatchScalarField(), alphatWallBoilingWallFunctionFvPatchScalarField::updateCoeffs(), and alphatWallBoilingWallFunctionFvPatchScalarField::write().
updateCoeffs()
virtual void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Reimplemented from alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField.
Referenced by alphatWallBoilingWallFunctionFvPatchScalarField::clone().
write()
virtual void write (Ostream &) const virtual
Write.
Reimplemented from alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField.
Referenced by alphatWallBoilingWallFunctionFvPatchScalarField::clone().
The documentation for this class was generated from the following file:
applications/solvers/multiphase/reactingEulerFoam/reactingTwoPhaseEulerFoam/twoPhaseCompressibleTurbulenceModels/derivedFvPatchFields/alphatWallBoilingWallFunction/alphatWallBoilingWallFunctionFvPatchScalarField.H