OpenFOAM: JohnsonJacksonParticleSlipFvPatchVectorField Class Reference
JohnsonJacksonParticleSlipFvPatchVectorField Class Reference
Partial slip boundary condition for the particulate velocity.
Public Member Functions
TypeName ("JohnsonJacksonParticleSlip")
Runtime type information.
JohnsonJacksonParticleSlipFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
JohnsonJacksonParticleSlipFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
JohnsonJacksonParticleSlipFvPatchVectorField (const JohnsonJacksonParticleSlipFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping onto a new patch.
JohnsonJacksonParticleSlipFvPatchVectorField (const JohnsonJacksonParticleSlipFvPatchVectorField &)
Construct as copy.
virtual tmp< fvPatchVectorField > clone () const
Construct and return a clone.
JohnsonJacksonParticleSlipFvPatchVectorField (const JohnsonJacksonParticleSlipFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchVectorField &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
virtual void updateCoeffs ()
Update the coefficients.
virtual void write (Ostream &) const
Write.
TypeName ("JohnsonJacksonParticleSlip")
Runtime type information.
JohnsonJacksonParticleSlipFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
JohnsonJacksonParticleSlipFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
JohnsonJacksonParticleSlipFvPatchVectorField (const JohnsonJacksonParticleSlipFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping onto a new patch.
JohnsonJacksonParticleSlipFvPatchVectorField (const JohnsonJacksonParticleSlipFvPatchVectorField &)
Construct as copy.
virtual tmp< fvPatchVectorField > clone () const
Construct and return a clone.
JohnsonJacksonParticleSlipFvPatchVectorField (const JohnsonJacksonParticleSlipFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchVectorField &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
virtual void updateCoeffs ()
Update the coefficients.
virtual void write (Ostream &) const
Write.
Detailed Description
Partial slip boundary condition for the particulate velocity.
References:
    "Multifluid Eulerian modeling of dense gas–solids fluidized bed
     hydrodynamics: Influence of the dissipation parameters"
    Reuge, N.,
    Chemical Engineering Science
    Volume 63, Issue 22, November 2008, pp. 5540-5551
    "Frictional-collisional constitutive relations for granular materials,
     with application to plane shearing"
    Johnson, P.C., and Jackson, R.,
    Journal of Fluid Mechanics
    Volume 176, March 1987, pp. 67-93
Source files
JohnsonJacksonParticleSlipFvPatchVectorField.H
JohnsonJacksonParticleSlipFvPatchVectorField.C
References:
    "Multifluid Eulerian modeling of dense gas–solids fluidized bed
     hydrodynamics: Influence of the dissipation parameters"
    Reuge, N.,
    Chemical Engineering Science
    Volume 63, Issue 22, November 2008, pp. 5540-5551
    "Frictional-collisional constitutive relations for granular materials,
     with application to plane shearing"
    Johnson, P.C., and Jackson, R.,
    Journal of Fluid Mechanics
    Volume 176, March 1987, pp. 67-93
Source files
JohnsonJacksonParticleSlipFvPatchVectorField.H
JohnsonJacksonParticleSlipFvPatchVectorField.C
Definition at line 65 of file JohnsonJacksonParticleSlipFvPatchVectorField.H.
Constructor & Destructor Documentation
JohnsonJacksonParticleSlipFvPatchVectorField() [1/10]
JohnsonJacksonParticleSlipFvPatchVectorField (const fvPatch & , const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
Referenced by JohnsonJacksonParticleSlipFvPatchVectorField::clone().
JohnsonJacksonParticleSlipFvPatchVectorField() [2/10]
JohnsonJacksonParticleSlipFvPatchVectorField (const fvPatch & , const DimensionedField< vector, volMesh > & , const dictionary &)
Construct from patch, internal field and dictionary.
JohnsonJacksonParticleSlipFvPatchVectorField() [3/10]
JohnsonJacksonParticleSlipFvPatchVectorField (const JohnsonJacksonParticleSlipFvPatchVectorField & , const fvPatch & , const DimensionedField< vector, volMesh > & , const fvPatchFieldMapper &)
Construct by mapping onto a new patch.
JohnsonJacksonParticleSlipFvPatchVectorField() [4/10]
JohnsonJacksonParticleSlipFvPatchVectorField (const JohnsonJacksonParticleSlipFvPatchVectorField &)
Construct as copy.
JohnsonJacksonParticleSlipFvPatchVectorField() [5/10]
JohnsonJacksonParticleSlipFvPatchVectorField (const JohnsonJacksonParticleSlipFvPatchVectorField & , const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
JohnsonJacksonParticleSlipFvPatchVectorField() [6/10]
JohnsonJacksonParticleSlipFvPatchVectorField (const fvPatch & , const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
JohnsonJacksonParticleSlipFvPatchVectorField() [7/10]
JohnsonJacksonParticleSlipFvPatchVectorField (const fvPatch & , const DimensionedField< vector, volMesh > & , const dictionary &)
Construct from patch, internal field and dictionary.
JohnsonJacksonParticleSlipFvPatchVectorField() [8/10]
JohnsonJacksonParticleSlipFvPatchVectorField (const JohnsonJacksonParticleSlipFvPatchVectorField & , const fvPatch & , const DimensionedField< vector, volMesh > & , const fvPatchFieldMapper &)
Construct by mapping onto a new patch.
JohnsonJacksonParticleSlipFvPatchVectorField() [9/10]
JohnsonJacksonParticleSlipFvPatchVectorField (const JohnsonJacksonParticleSlipFvPatchVectorField &)
Construct as copy.
JohnsonJacksonParticleSlipFvPatchVectorField() [10/10]
JohnsonJacksonParticleSlipFvPatchVectorField (const JohnsonJacksonParticleSlipFvPatchVectorField & , const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
Member Function Documentation
TypeName() [1/2]
TypeName ("JohnsonJacksonParticleSlip")
Runtime type information.
clone() [1/4]
virtual tmp<fvPatchVectorField> clone () const inline virtual
Construct and return a clone.
Definition at line 114 of file JohnsonJacksonParticleSlipFvPatchVectorField.H.
References JohnsonJacksonParticleSlipFvPatchVectorField::JohnsonJacksonParticleSlipFvPatchVectorField().
Referenced by JohnsonJacksonParticleSlipFvPatchVectorField::clone().
clone() [2/4]
virtual tmp<fvPatchVectorField> clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 131 of file JohnsonJacksonParticleSlipFvPatchVectorField.H.
References JohnsonJacksonParticleSlipFvPatchVectorField::autoMap(), JohnsonJacksonParticleSlipFvPatchVectorField::JohnsonJacksonParticleSlipFvPatchVectorField(), JohnsonJacksonParticleSlipFvPatchVectorField::rmap(), JohnsonJacksonParticleSlipFvPatchVectorField::updateCoeffs(), and JohnsonJacksonParticleSlipFvPatchVectorField::write().
autoMap() [1/2]
virtual void autoMap (const fvPatchFieldMapper &) virtual
Map (and resize as needed) from self given a mapping object.
Referenced by JohnsonJacksonParticleSlipFvPatchVectorField::clone().
rmap() [1/2]
virtual void rmap (const fvPatchVectorField & , const labelList &) virtual
Reverse map the given fvPatchField onto this fvPatchField.
Referenced by JohnsonJacksonParticleSlipFvPatchVectorField::clone().
updateCoeffs() [1/2]
virtual void updateCoeffs () virtual
Update the coefficients.
Referenced by JohnsonJacksonParticleSlipFvPatchVectorField::clone().
write() [1/2]
virtual void write (Ostream &) const virtual
Write.
Referenced by JohnsonJacksonParticleSlipFvPatchVectorField::clone().
TypeName() [2/2]
TypeName ("JohnsonJacksonParticleSlip")
Runtime type information.
clone() [3/4]
virtual tmp<fvPatchVectorField> clone () const inline virtual
Construct and return a clone.
Definition at line 114 of file JohnsonJacksonParticleSlipFvPatchVectorField.H.
References JohnsonJacksonParticleSlipFvPatchVectorField::clone(), and JohnsonJacksonParticleSlipFvPatchVectorField::JohnsonJacksonParticleSlipFvPatchVectorField().
clone() [4/4]
virtual tmp<fvPatchVectorField> clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 131 of file JohnsonJacksonParticleSlipFvPatchVectorField.H.
References JohnsonJacksonParticleSlipFvPatchVectorField::autoMap(), JohnsonJacksonParticleSlipFvPatchVectorField::JohnsonJacksonParticleSlipFvPatchVectorField(), JohnsonJacksonParticleSlipFvPatchVectorField::rmap(), JohnsonJacksonParticleSlipFvPatchVectorField::updateCoeffs(), and JohnsonJacksonParticleSlipFvPatchVectorField::write().
autoMap() [2/2]
virtual void autoMap (const fvPatchFieldMapper &) virtual
Map (and resize as needed) from self given a mapping object.
rmap() [2/2]
virtual void rmap (const fvPatchVectorField & , const labelList &) virtual
Reverse map the given fvPatchField onto this fvPatchField.
updateCoeffs() [2/2]
virtual void updateCoeffs () virtual
Update the coefficients.
write() [2/2]
virtual void write (Ostream &) const virtual
Write.
The documentation for this class was generated from the following file:
applications/solvers/multiphase/reactingEulerFoam/reactingTwoPhaseEulerFoam/twoPhaseCompressibleTurbulenceModels/kineticTheoryModels/derivedFvPatchFields/JohnsonJacksonParticleSlip/JohnsonJacksonParticleSlipFvPatchVectorField.H