OpenFOAM: MomentumTransferPhaseSystem< BasePhaseSystem > Class Template Reference
MomentumTransferPhaseSystem< BasePhaseSystem > Class Template Reference
Class which models interfacial momenum transfer between a number of phases. Drag, virtual mass, lift, wall lubrication and turbulent dispersion are all modelled. The explicit contribution from the drag is omitted from the transfer matrices, as this forms part of the solution of the pressure equation.
Public Member Functions
MomentumTransferPhaseSystem (const fvMesh &)
Construct from fvMesh.
virtual ~MomentumTransferPhaseSystem ()
Destructor.
virtual const phaseSystem::KdTable & Kds () const
Constant access to drag coefficients.
virtual tmp< volScalarField > Kd (const phasePairKey &key) const
Return the drag coefficient.
virtual tmp< surfaceScalarField > Kdf (const phasePairKey &key) const
Return the face drag coefficient.
virtual tmp< volScalarField > Kd (const phaseModel &phase) const
Return the drag coefficient for phase.
virtual tmp< volScalarField > Vm (const phasePairKey &key) const
Return the virtual mass coefficient.
virtual tmp< surfaceScalarField > Vmf (const phasePairKey &key) const
Return the face virtual mass coefficient.
virtual tmp< volVectorField > F (const phasePairKey &key) const
Return the combined force (lift + wall-lubrication)
virtual autoPtr< PtrList< volVectorField > > Fs () const
Return the combined force (lift + wall-lubrication)
virtual autoPtr< PtrList< surfaceScalarField > > phiDs (const PtrList< volScalarField > &rAUs) const
Return the turbulent dispersion force on faces for phase pair.
virtual tmp< surfaceScalarField > Ff (const phasePairKey &key) const
Return the combined face-force (lift + wall-lubrication)
virtual tmp< volScalarField > D (const phasePairKey &key) const
Return the turbulent diffusivity.
virtual autoPtr< phaseSystem::momentumTransferTable > momentumTransfer () const
Return the momentum transfer matrices.
virtual bool read ()
Read base phaseProperties dictionary.
Protected Types
typedef HashTable< autoPtr< BlendedInterfacialModel< dragModel > >, phasePairKey, phasePairKey::hash > dragModelTable
typedef HashTable< autoPtr< BlendedInterfacialModel< virtualMassModel > >, phasePairKey, phasePairKey::hash > virtualMassModelTable
typedef HashTable< autoPtr< BlendedInterfacialModel< liftModel > >, phasePairKey, phasePairKey::hash > liftModelTable
typedef HashTable< autoPtr< BlendedInterfacialModel< wallLubricationModel > >, phasePairKey, phasePairKey::hash > wallLubricationModelTable
typedef HashTable< autoPtr< BlendedInterfacialModel< turbulentDispersionModel > >, phasePairKey, phasePairKey::hash > turbulentDispersionModelTable
Detailed Description
template<class BasePhaseSystem>
class Foam::MomentumTransferPhaseSystem< BasePhaseSystem >
Class which models interfacial momenum transfer between a number of phases. Drag, virtual mass, lift, wall lubrication and turbulent dispersion are all modelled. The explicit contribution from the drag is omitted from the transfer matrices, as this forms part of the solution of the pressure equation.
Source files
MomentumTransferPhaseSystem.H
MomentumTransferPhaseSystem.C
Definition at line 64 of file MomentumTransferPhaseSystem.H.
Member Typedef Documentation
dragModelTable
typedef HashTable< autoPtr<BlendedInterfacialModel<dragModel> >, phasePairKey, phasePairKey::hash > dragModelTable protected
Definition at line 77 of file MomentumTransferPhaseSystem.H.
virtualMassModelTable
typedef HashTable< autoPtr<BlendedInterfacialModel<virtualMassModel> >, phasePairKey, phasePairKey::hash > virtualMassModelTable protected
Definition at line 84 of file MomentumTransferPhaseSystem.H.
liftModelTable
typedef HashTable< autoPtr<BlendedInterfacialModel<liftModel> >, phasePairKey, phasePairKey::hash > liftModelTable protected
Definition at line 91 of file MomentumTransferPhaseSystem.H.
wallLubricationModelTable
typedef HashTable< autoPtr<BlendedInterfacialModel<wallLubricationModel> >, phasePairKey, phasePairKey::hash > wallLubricationModelTable protected
Definition at line 98 of file MomentumTransferPhaseSystem.H.
turbulentDispersionModelTable
typedef HashTable< autoPtr<BlendedInterfacialModel<turbulentDispersionModel> >, phasePairKey, phasePairKey::hash > turbulentDispersionModelTable protected
Definition at line 105 of file MomentumTransferPhaseSystem.H.
Constructor & Destructor Documentation
MomentumTransferPhaseSystem()
MomentumTransferPhaseSystem (const fvMesh &)
Construct from fvMesh.
~MomentumTransferPhaseSystem()
virtual ~MomentumTransferPhaseSystem () virtual
Destructor.
Member Function Documentation
Kds()
virtual const phaseSystem::KdTable& Kds () const inline virtual
Constant access to drag coefficients.
Definition at line 165 of file MomentumTransferPhaseSystem.H.
References MomentumTransferPhaseSystem< BasePhaseSystem >::D(), MomentumTransferPhaseSystem< BasePhaseSystem >::F(), MomentumTransferPhaseSystem< BasePhaseSystem >::Ff(), MomentumTransferPhaseSystem< BasePhaseSystem >::Fs(), MomentumTransferPhaseSystem< BasePhaseSystem >::Kd(), MomentumTransferPhaseSystem< BasePhaseSystem >::Kdf(), MomentumTransferPhaseSystem< BasePhaseSystem >::momentumTransfer(), MomentumTransferPhaseSystem< BasePhaseSystem >::phiDs(), rAUs(), MomentumTransferPhaseSystem< BasePhaseSystem >::read(), MomentumTransferPhaseSystem< BasePhaseSystem >::Vm(), and MomentumTransferPhaseSystem< BasePhaseSystem >::Vmf().
Kd() [1/2]
virtual tmp<volScalarField> Kd (const phasePairKey & key) const virtual
Return the drag coefficient.
Referenced by MomentumTransferPhaseSystem< BasePhaseSystem >::Kds().
Kdf()
virtual tmp<surfaceScalarField> Kdf (const phasePairKey & key) const virtual
Return the face drag coefficient.
Referenced by MomentumTransferPhaseSystem< BasePhaseSystem >::Kds().
Kd() [2/2]
virtual tmp<volScalarField> Kd (const phaseModel & phase) const virtual
Return the drag coefficient for phase.
Vm()
virtual tmp<volScalarField> Vm (const phasePairKey & key) const virtual
Return the virtual mass coefficient.
Referenced by MomentumTransferPhaseSystem< BasePhaseSystem >::Kds().
Vmf()
virtual tmp<surfaceScalarField> Vmf (const phasePairKey & key) const virtual
Return the face virtual mass coefficient.
Referenced by MomentumTransferPhaseSystem< BasePhaseSystem >::Kds().
F()
virtual tmp<volVectorField> F (const phasePairKey & key) const virtual
Return the combined force (lift + wall-lubrication)
Referenced by MomentumTransferPhaseSystem< BasePhaseSystem >::Kds().
Fs()
virtual autoPtr<PtrList<volVectorField> > Fs () const virtual
Return the combined force (lift + wall-lubrication)
Referenced by MomentumTransferPhaseSystem< BasePhaseSystem >::Kds().
phiDs()
virtual autoPtr<PtrList<surfaceScalarField> > phiDs (const PtrList< volScalarField > & rAUs) const virtual
Return the turbulent dispersion force on faces for phase pair.
Referenced by MomentumTransferPhaseSystem< BasePhaseSystem >::Kds().
Ff()
virtual tmp<surfaceScalarField> Ff (const phasePairKey & key) const virtual
Return the combined face-force (lift + wall-lubrication)
Referenced by MomentumTransferPhaseSystem< BasePhaseSystem >::Kds().
D()
virtual tmp<volScalarField> D (const phasePairKey & key) const virtual
Return the turbulent diffusivity.
Multiplies the phase-fraction gradient
Referenced by MomentumTransferPhaseSystem< BasePhaseSystem >::Kds().
momentumTransfer()
virtual autoPtr<phaseSystem::momentumTransferTable> momentumTransfer () const virtual
Return the momentum transfer matrices.
Referenced by MomentumTransferPhaseSystem< BasePhaseSystem >::Kds().
read()
virtual bool read () virtual
Read base phaseProperties dictionary.
Referenced by MomentumTransferPhaseSystem< BasePhaseSystem >::Kds().
The documentation for this class was generated from the following file:
applications/solvers/multiphase/reactingEulerFoam/phaseSystems/PhaseSystems/MomentumTransferPhaseSystem/MomentumTransferPhaseSystem.H