OpenFOAM: JohnsonJacksonParticleThetaFvPatchScalarField Class Reference
JohnsonJacksonParticleThetaFvPatchScalarField Class Reference
Robin condition for the particulate granular temperature.
Public Member Functions
TypeName ("JohnsonJacksonParticleTheta")
Runtime type information.
JohnsonJacksonParticleThetaFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
JohnsonJacksonParticleThetaFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
JohnsonJacksonParticleThetaFvPatchScalarField (const JohnsonJacksonParticleThetaFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping onto a new patch.
JohnsonJacksonParticleThetaFvPatchScalarField (const JohnsonJacksonParticleThetaFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
JohnsonJacksonParticleThetaFvPatchScalarField (const JohnsonJacksonParticleThetaFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchScalarField &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
virtual void updateCoeffs ()
Update the coefficients.
virtual void write (Ostream &) const
Write.
TypeName ("JohnsonJacksonParticleTheta")
Runtime type information.
JohnsonJacksonParticleThetaFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
JohnsonJacksonParticleThetaFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
JohnsonJacksonParticleThetaFvPatchScalarField (const JohnsonJacksonParticleThetaFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping onto a new patch.
JohnsonJacksonParticleThetaFvPatchScalarField (const JohnsonJacksonParticleThetaFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
JohnsonJacksonParticleThetaFvPatchScalarField (const JohnsonJacksonParticleThetaFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchScalarField &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
virtual void updateCoeffs ()
Update the coefficients.
virtual void write (Ostream &) const
Write.
Detailed Description
Robin condition for the particulate granular temperature.
References:
    "Multifluid Eulerian modeling of dense gas–solids fluidized bed
     hydrodynamics: Influence of the dissipation parameters"
    Reuge, N.,
    Chemical Engineering Science
    Volume 63, Issue 22, November 2008, pp. 5540-5551
    "Frictional-collisional constitutive relations for granular materials,
     with application to plane shearing"
    Johnson, P.C., and Jackson, R.,
    Journal of Fluid Mechanics
    Volume 176, March 1987, pp. 67-93
Source files
JohnsonJacksonParticleThetaFvPatchScalarField.H
JohnsonJacksonParticleThetaFvPatchScalarField.C
References:
    "Multifluid Eulerian modeling of dense gas–solids fluidized bed
     hydrodynamics: Influence of the dissipation parameters"
    Reuge, N.,
    Chemical Engineering Science
    Volume 63, Issue 22, November 2008, pp. 5540-5551
    "Frictional-collisional constitutive relations for granular materials,
     with application to plane shearing"
    Johnson, P.C., and Jackson, R.,
    Journal of Fluid Mechanics
    Volume 176, March 1987, pp. 67-93
Source files
JohnsonJacksonParticleThetaFvPatchScalarField.H
JohnsonJacksonParticleThetaFvPatchScalarField.C
Definition at line 65 of file JohnsonJacksonParticleThetaFvPatchScalarField.H.
Constructor & Destructor Documentation
JohnsonJacksonParticleThetaFvPatchScalarField() [1/10]
JohnsonJacksonParticleThetaFvPatchScalarField (const fvPatch & , const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
Referenced by JohnsonJacksonParticleThetaFvPatchScalarField::clone().
JohnsonJacksonParticleThetaFvPatchScalarField() [2/10]
JohnsonJacksonParticleThetaFvPatchScalarField (const fvPatch & , const DimensionedField< scalar, volMesh > & , const dictionary &)
Construct from patch, internal field and dictionary.
JohnsonJacksonParticleThetaFvPatchScalarField() [3/10]
JohnsonJacksonParticleThetaFvPatchScalarField (const JohnsonJacksonParticleThetaFvPatchScalarField & , const fvPatch & , const DimensionedField< scalar, volMesh > & , const fvPatchFieldMapper &)
Construct by mapping onto a new patch.
JohnsonJacksonParticleThetaFvPatchScalarField() [4/10]
JohnsonJacksonParticleThetaFvPatchScalarField (const JohnsonJacksonParticleThetaFvPatchScalarField &)
Construct as copy.
JohnsonJacksonParticleThetaFvPatchScalarField() [5/10]
JohnsonJacksonParticleThetaFvPatchScalarField (const JohnsonJacksonParticleThetaFvPatchScalarField & , const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
JohnsonJacksonParticleThetaFvPatchScalarField() [6/10]
JohnsonJacksonParticleThetaFvPatchScalarField (const fvPatch & , const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
JohnsonJacksonParticleThetaFvPatchScalarField() [7/10]
JohnsonJacksonParticleThetaFvPatchScalarField (const fvPatch & , const DimensionedField< scalar, volMesh > & , const dictionary &)
Construct from patch, internal field and dictionary.
JohnsonJacksonParticleThetaFvPatchScalarField() [8/10]
JohnsonJacksonParticleThetaFvPatchScalarField (const JohnsonJacksonParticleThetaFvPatchScalarField & , const fvPatch & , const DimensionedField< scalar, volMesh > & , const fvPatchFieldMapper &)
Construct by mapping onto a new patch.
JohnsonJacksonParticleThetaFvPatchScalarField() [9/10]
JohnsonJacksonParticleThetaFvPatchScalarField (const JohnsonJacksonParticleThetaFvPatchScalarField &)
Construct as copy.
JohnsonJacksonParticleThetaFvPatchScalarField() [10/10]
JohnsonJacksonParticleThetaFvPatchScalarField (const JohnsonJacksonParticleThetaFvPatchScalarField & , const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
Member Function Documentation
TypeName() [1/2]
TypeName ("JohnsonJacksonParticleTheta")
Runtime type information.
clone() [1/4]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 117 of file JohnsonJacksonParticleThetaFvPatchScalarField.H.
References JohnsonJacksonParticleThetaFvPatchScalarField::JohnsonJacksonParticleThetaFvPatchScalarField().
Referenced by JohnsonJacksonParticleThetaFvPatchScalarField::clone().
clone() [2/4]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 134 of file JohnsonJacksonParticleThetaFvPatchScalarField.H.
References JohnsonJacksonParticleThetaFvPatchScalarField::autoMap(), JohnsonJacksonParticleThetaFvPatchScalarField::JohnsonJacksonParticleThetaFvPatchScalarField(), JohnsonJacksonParticleThetaFvPatchScalarField::rmap(), JohnsonJacksonParticleThetaFvPatchScalarField::updateCoeffs(), and JohnsonJacksonParticleThetaFvPatchScalarField::write().
autoMap() [1/2]
virtual void autoMap (const fvPatchFieldMapper &) virtual
Map (and resize as needed) from self given a mapping object.
Referenced by JohnsonJacksonParticleThetaFvPatchScalarField::clone().
rmap() [1/2]
virtual void rmap (const fvPatchScalarField & , const labelList &) virtual
Reverse map the given fvPatchField onto this fvPatchField.
Referenced by JohnsonJacksonParticleThetaFvPatchScalarField::clone().
updateCoeffs() [1/2]
virtual void updateCoeffs () virtual
Update the coefficients.
Referenced by JohnsonJacksonParticleThetaFvPatchScalarField::clone().
write() [1/2]
virtual void write (Ostream &) const virtual
Write.
Referenced by JohnsonJacksonParticleThetaFvPatchScalarField::clone().
TypeName() [2/2]
TypeName ("JohnsonJacksonParticleTheta")
Runtime type information.
clone() [3/4]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 117 of file JohnsonJacksonParticleThetaFvPatchScalarField.H.
References JohnsonJacksonParticleThetaFvPatchScalarField::clone(), and JohnsonJacksonParticleThetaFvPatchScalarField::JohnsonJacksonParticleThetaFvPatchScalarField().
clone() [4/4]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 134 of file JohnsonJacksonParticleThetaFvPatchScalarField.H.
References JohnsonJacksonParticleThetaFvPatchScalarField::autoMap(), JohnsonJacksonParticleThetaFvPatchScalarField::JohnsonJacksonParticleThetaFvPatchScalarField(), JohnsonJacksonParticleThetaFvPatchScalarField::rmap(), JohnsonJacksonParticleThetaFvPatchScalarField::updateCoeffs(), and JohnsonJacksonParticleThetaFvPatchScalarField::write().
autoMap() [2/2]
virtual void autoMap (const fvPatchFieldMapper &) virtual
Map (and resize as needed) from self given a mapping object.
rmap() [2/2]
virtual void rmap (const fvPatchScalarField & , const labelList &) virtual
Reverse map the given fvPatchField onto this fvPatchField.
updateCoeffs() [2/2]
virtual void updateCoeffs () virtual
Update the coefficients.
write() [2/2]
virtual void write (Ostream &) const virtual
Write.
The documentation for this class was generated from the following file:
applications/solvers/multiphase/reactingEulerFoam/reactingTwoPhaseEulerFoam/twoPhaseCompressibleTurbulenceModels/kineticTheoryModels/derivedFvPatchFields/JohnsonJacksonParticleTheta/JohnsonJacksonParticleThetaFvPatchScalarField.H