OpenFOAM: IATEsource Class Reference
IATEsource Class Reference abstract
IATE (Interfacial Area Transport Equation) bubble diameter model run-time selectable sources.
Classes
class iNew
Class used for the read-construction of.
Public Member Functions
TypeName ("IATEsource")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, IATEsource, dictionary,(const IATE &iate, const dictionary &dict),(iate, dict))
IATEsource (const IATE &iate)
autoPtr< IATEsource > clone () const
virtual ~IATEsource ()
Destructor.
const phaseModel & phase () const
const twoPhaseSystem & fluid () const
const phaseModel & otherPhase () const
scalar phi () const
tmp< volScalarField > Ur () const
Return the bubble relative velocity.
tmp< volScalarField > Ut () const
Return the bubble turbulent velocity.
tmp< volScalarField > Re () const
Return the bubble Reynolds number.
tmp< volScalarField > CD () const
Return the bubble drag coefficient.
tmp< volScalarField > Mo () const
Return the bubble Morton number.
tmp< volScalarField > Eo () const
Return the bubble Eotvos number.
tmp< volScalarField > We () const
Return the bubble Webber number.
virtual tmp< volScalarField > R () const =0
TypeName ("IATEsource")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, IATEsource, dictionary,(const IATE &iate, const dictionary &dict),(iate, dict))
IATEsource (const IATE &iate)
autoPtr< IATEsource > clone () const
virtual ~IATEsource ()
Destructor.
const phaseModel & phase () const
const twoPhaseSystem & fluid () const
const phaseModel & otherPhase () const
scalar phi () const
tmp< volScalarField > Ur () const
Return the bubble relative velocity.
tmp< volScalarField > Ut () const
Return the bubble turbulent velocity.
tmp< volScalarField > Re () const
Return the bubble Reynolds number.
tmp< volScalarField > CD () const
Return the bubble drag coefficient.
tmp< volScalarField > Mo () const
Return the bubble Morton number.
tmp< volScalarField > Eo () const
Return the bubble Eotvos number.
tmp< volScalarField > We () const
Return the bubble Webber number.
virtual tmp< volScalarField > R () const =0
Static Public Member Functions
static autoPtr< IATEsource > New (const word &type, const IATE &iate, const dictionary &dict)
static autoPtr< IATEsource > New (const word &type, const IATE &iate, const dictionary &dict)
Protected Attributes
const IATE & iate_
Reference to the IATE this source applies to.
Detailed Description
IATE (Interfacial Area Transport Equation) bubble diameter model run-time selectable sources.
Source files
IATEsource.H
IATEsource.C
Source files
IATEsource.H
IATEsource.C
Definition at line 53 of file IATEsource.H.
Constructor & Destructor Documentation
IATEsource() [1/2]
IATEsource (const IATE & iate) inline
Definition at line 109 of file IATEsource.H.
~IATEsource() [1/2]
virtual ~IATEsource () inline virtual
Destructor.
Definition at line 132 of file IATEsource.H.
IATEsource() [2/2]
IATEsource (const IATE & iate) inline
Definition at line 108 of file IATEsource.H.
~IATEsource() [2/2]
virtual ~IATEsource () inline virtual
Destructor.
Definition at line 131 of file IATEsource.H.
Member Function Documentation
TypeName() [1/2]
TypeName ("IATEsource")
Runtime type information.
declareRunTimeSelectionTable() [1/2]
declareRunTimeSelectionTable (autoPtr , IATEsource , dictionary , (const IATE &iate, const dictionary &dict) , (iate, dict))
clone() [1/2]
autoPtr<IATEsource> clone () const inline
Definition at line 114 of file IATEsource.H.
References IATEsource::New(), NotImplemented, and Foam::type().
New() [1/2]
static autoPtr<IATEsource> New (const word & type, const IATE & iate, const dictionary & dict) static
Referenced by IATEsource::clone(), and IATEsource::iNew::operator()().
phase() [1/2]
const phaseModel& phase () const inline
Definition at line 138 of file IATEsource.H.
References diameterModel::phase().
Referenced by IATEsource::otherPhase().
fluid() [1/2]
const twoPhaseSystem& fluid () const inline
Definition at line 143 of file IATEsource.H.
References phaseModel::fluid(), and diameterModel::phase().
Referenced by IATEsource::otherPhase().
otherPhase() [1/2]
const phaseModel& otherPhase () const inline
Definition at line 148 of file IATEsource.H.
References IATEsource::fluid(), twoPhaseSystem::otherPhase(), and IATEsource::phase().
phi() [1/2]
scalar phi () const inline
Definition at line 153 of file IATEsource.H.
References IATEsource::CD(), IATEsource::Eo(), IATEsource::Mo(), Foam::constant::mathematical::pi(), IATEsource::R(), IATEsource::Re(), IATEsource::Ur(), IATEsource::Ut(), and IATEsource::We().
Ur() [1/2]
tmp<volScalarField> Ur () const
Return the bubble relative velocity.
Referenced by IATEsource::phi().
Ut() [1/2]
tmp<volScalarField> Ut () const
Return the bubble turbulent velocity.
Referenced by IATEsource::phi().
Re() [1/2]
tmp<volScalarField> Re () const
Return the bubble Reynolds number.
Referenced by IATEsource::phi().
CD() [1/2]
tmp<volScalarField> CD () const
Return the bubble drag coefficient.
Referenced by IATEsource::phi().
Mo() [1/2]
tmp<volScalarField> Mo () const
Return the bubble Morton number.
Referenced by IATEsource::phi().
Eo() [1/2]
tmp<volScalarField> Eo () const
Return the bubble Eotvos number.
Referenced by IATEsource::phi().
We() [1/2]
tmp<volScalarField> We () const
Return the bubble Webber number.
Referenced by IATEsource::phi().
R() [1/2]
virtual tmp<volScalarField> R () const pure virtual
Implemented in randomCoalescence, randomCoalescence, turbulentBreakUp, turbulentBreakUp, wakeEntrainmentCoalescence, wakeEntrainmentCoalescence, dummy, and dummy.
Referenced by IATEsource::phi().
TypeName() [2/2]
TypeName ("IATEsource")
Runtime type information.
declareRunTimeSelectionTable() [2/2]
declareRunTimeSelectionTable (autoPtr , IATEsource , dictionary , (const IATE &iate, const dictionary &dict) , (iate, dict))
clone() [2/2]
autoPtr<IATEsource> clone () const inline
Definition at line 113 of file IATEsource.H.
References IATEsource::New(), NotImplemented, and Foam::type().
New() [2/2]
static autoPtr<IATEsource> New (const word & type, const IATE & iate, const dictionary & dict) static
phase() [2/2]
const phaseModel& phase () const inline
Definition at line 137 of file IATEsource.H.
fluid() [2/2]
const twoPhaseSystem& fluid () const inline
Definition at line 142 of file IATEsource.H.
otherPhase() [2/2]
const phaseModel& otherPhase () const inline
Definition at line 147 of file IATEsource.H.
References phaseModel::otherPhase(), and IATEsource::phase().
phi() [2/2]
scalar phi () const inline
Definition at line 152 of file IATEsource.H.
References IATEsource::CD(), IATEsource::Eo(), IATEsource::Mo(), Foam::constant::mathematical::pi(), IATEsource::R(), IATEsource::Re(), IATEsource::Ur(), IATEsource::Ut(), and IATEsource::We().
Ur() [2/2]
tmp<volScalarField> Ur () const
Return the bubble relative velocity.
Ut() [2/2]
tmp<volScalarField> Ut () const
Return the bubble turbulent velocity.
Re() [2/2]
tmp<volScalarField> Re () const
Return the bubble Reynolds number.
CD() [2/2]
tmp<volScalarField> CD () const
Return the bubble drag coefficient.
Mo() [2/2]
tmp<volScalarField> Mo () const
Return the bubble Morton number.
Eo() [2/2]
tmp<volScalarField> Eo () const
Return the bubble Eotvos number.
We() [2/2]
tmp<volScalarField> We () const
Return the bubble Webber number.
R() [2/2]
virtual tmp<volScalarField> R () const pure virtual
Implemented in randomCoalescence, randomCoalescence, turbulentBreakUp, turbulentBreakUp, wakeEntrainmentCoalescence, wakeEntrainmentCoalescence, dummy, and dummy.
Member Data Documentation
iate_
const IATE & iate_ protected
Reference to the IATE this source applies to.
Definition at line 61 of file IATEsource.H.
The documentation for this class was generated from the following file:
applications/solvers/multiphase/reactingEulerFoam/reactingTwoPhaseEulerFoam/twoPhaseSystem/diameterModels/IATE/IATEsources/IATEsource/IATEsource.H