OpenFOAM: tractionDisplacementCorrectionFvPatchVectorField Class Reference
tractionDisplacementCorrectionFvPatchVectorField Class Reference
Public Member Functions
TypeName ("tractionDisplacement")
Runtime type information.
tractionDisplacementCorrectionFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
tractionDisplacementCorrectionFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, Istream &)
Construct from patch, internal field and Istream.
tractionDisplacementCorrectionFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
tractionDisplacementCorrectionFvPatchVectorField (const tractionDisplacementCorrectionFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
tractionDisplacementCorrectionFvPatchVectorField (const tractionDisplacementCorrectionFvPatchVectorField &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchVectorField > clone () const
Construct and return a clone.
tractionDisplacementCorrectionFvPatchVectorField (const tractionDisplacementCorrectionFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual const vectorField & traction () const
virtual vectorField & traction ()
virtual const scalarField & pressure () const
virtual scalarField & pressure ()
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchVectorField &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Detailed Description
Definition at line 41 of file tractionDisplacementCorrectionFvPatchVectorField.H.
Constructor & Destructor Documentation
tractionDisplacementCorrectionFvPatchVectorField() [1/6]
tractionDisplacementCorrectionFvPatchVectorField (const fvPatch & , const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
Referenced by tractionDisplacementCorrectionFvPatchVectorField::clone().
tractionDisplacementCorrectionFvPatchVectorField() [2/6]
tractionDisplacementCorrectionFvPatchVectorField (const fvPatch & , const DimensionedField< vector, volMesh > & , Istream &)
Construct from patch, internal field and Istream.
tractionDisplacementCorrectionFvPatchVectorField() [3/6]
tractionDisplacementCorrectionFvPatchVectorField (const fvPatch & , const DimensionedField< vector, volMesh > & , const dictionary &)
Construct from patch, internal field and dictionary.
tractionDisplacementCorrectionFvPatchVectorField() [4/6]
tractionDisplacementCorrectionFvPatchVectorField (const tractionDisplacementCorrectionFvPatchVectorField & , const fvPatch & , const DimensionedField< vector, volMesh > & , const fvPatchFieldMapper &)
Construct by mapping given.
tractionDisplacementCorrectionFvPatchVectorField onto a new patch
tractionDisplacementCorrectionFvPatchVectorField() [5/6]
tractionDisplacementCorrectionFvPatchVectorField (const tractionDisplacementCorrectionFvPatchVectorField &)
Construct as copy setting internal field reference.
tractionDisplacementCorrectionFvPatchVectorField() [6/6]
tractionDisplacementCorrectionFvPatchVectorField (const tractionDisplacementCorrectionFvPatchVectorField & , const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
Member Function Documentation
TypeName()
TypeName ("tractionDisplacement")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchVectorField> clone () const inline virtual
Construct and return a clone.
Definition at line 100 of file tractionDisplacementCorrectionFvPatchVectorField.H.
References tractionDisplacementCorrectionFvPatchVectorField::tractionDisplacementCorrectionFvPatchVectorField().
clone() [2/2]
virtual tmp<fvPatchVectorField> clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 117 of file tractionDisplacementCorrectionFvPatchVectorField.H.
References tractionDisplacementCorrectionFvPatchVectorField::tractionDisplacementCorrectionFvPatchVectorField().
traction() [1/2]
virtual const vectorField& traction () const inline virtual
Definition at line 132 of file tractionDisplacementCorrectionFvPatchVectorField.H.
traction() [2/2]
virtual vectorField& traction () inline virtual
Definition at line 137 of file tractionDisplacementCorrectionFvPatchVectorField.H.
pressure() [1/2]
virtual const scalarField& pressure () const inline virtual
Definition at line 142 of file tractionDisplacementCorrectionFvPatchVectorField.H.
pressure() [2/2]
virtual scalarField& pressure () inline virtual
Definition at line 147 of file tractionDisplacementCorrectionFvPatchVectorField.H.
References tractionDisplacementCorrectionFvPatchVectorField::autoMap(), tractionDisplacementCorrectionFvPatchVectorField::rmap(), tractionDisplacementCorrectionFvPatchVectorField::updateCoeffs(), and tractionDisplacementCorrectionFvPatchVectorField::write().
autoMap()
virtual void autoMap (const fvPatchFieldMapper &) virtual
Map (and resize as needed) from self given a mapping object.
Referenced by tractionDisplacementCorrectionFvPatchVectorField::pressure().
rmap()
virtual void rmap (const fvPatchVectorField & , const labelList &) virtual
Reverse map the given fvPatchField onto this fvPatchField.
Referenced by tractionDisplacementCorrectionFvPatchVectorField::pressure().
updateCoeffs()
virtual void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Referenced by tractionDisplacementCorrectionFvPatchVectorField::pressure().
write()
virtual void write (Ostream &) const virtual
Write.
Referenced by tractionDisplacementCorrectionFvPatchVectorField::pressure().
The documentation for this class was generated from the following file:
applications/solvers/stressAnalysis/solidEquilibriumDisplacementFoam/tractionDisplacementCorrection/tractionDisplacementCorrectionFvPatchVectorField.H