OpenFOAM: IATE Class Reference
IATE Class Reference
IATE (Interfacial Area Transport Equation) bubble diameter model.
Public Member Functions
TypeName ("IATE")
Runtime type information.
IATE (const dictionary &diameterProperties, const phaseModel &phase)
Construct from components.
virtual ~IATE ()
Destructor.
const volScalarField & kappai () const
Return the interfacial curvature.
tmp< volScalarField > a () const
Return the interfacial area.
virtual tmp< volScalarField > d () const
Return the Sauter-mean diameter.
virtual void correct ()
Correct the diameter field.
virtual bool read (const dictionary &phaseProperties)
Read phaseProperties dictionary.
TypeName ("IATE")
Runtime type information.
IATE (const dictionary &diameterProperties, const phaseModel &phase)
Construct from components.
virtual ~IATE ()
Destructor.
const volScalarField & kappai () const
Return the interfacial curvature.
tmp< volScalarField > a () const
Return the interfacial area.
virtual tmp< volScalarField > d () const
Return the Sauter-mean diameter.
virtual void correct ()
Correct the diameter field.
virtual bool read (const dictionary &phaseProperties)
Read phaseProperties dictionary.
Public Member Functions inherited from diameterModel
TypeName ("diameterModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, diameterModel, dictionary,(const dictionary &dict, const phaseModel &phase),(dict, phase))
diameterModel (const dictionary &dict, const phaseModel &phase)
virtual ~diameterModel ()
Destructor.
TypeName ("diameterModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, diameterModel, dictionary,(const dictionary &diameterProperties, const phaseModel &phase),(diameterProperties, phase))
diameterModel (const dictionary &diameterProperties, const phaseModel &phase)
virtual ~diameterModel ()
Destructor.
const dictionary & diameterProperties () const
Return the phase diameter properties dictionary.
const phaseModel & phase () const
Return the phase.
TypeName ("diameterModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, diameterModel, dictionary,(const dictionary &diameterProperties, const phaseModel &phase),(diameterProperties, phase))
diameterModel (const dictionary &diameterProperties, const phaseModel &phase)
virtual ~diameterModel ()
Destructor.
const dictionary & diameterProperties () const
Return the phase diameter properties dictionary.
const phaseModel & phase () const
Return the phase.
Friends
class IATEsource
Additional Inherited Members
Static Public Member Functions inherited from diameterModel
static autoPtr< diameterModel > New (const dictionary &dict, const phaseModel &phase)
static autoPtr< diameterModel > New (const dictionary &diameterProperties, const phaseModel &phase)
static autoPtr< diameterModel > New (const dictionary &diameterProperties, const phaseModel &phase)
Protected Attributes inherited from diameterModel
const dictionary & dict_
const phaseModel & phase_
dictionary diameterProperties_
Detailed Description
IATE (Interfacial Area Transport Equation) bubble diameter model.
Solves for the interfacial curvature per unit volume of the phase rather than interfacial area per unit volume to avoid stability issues relating to the consistency requirements between the phase fraction and interfacial area per unit volume. In every other respect this model is as presented in the paper:
    "Development of Interfacial Area Transport Equation"
    Ishii, M., Kim, S. and Kelly, J.,
    Nuclear Engineering and Technology, Vol.37 No.6 December 2005
Source files
IATE.H
IATE.C
Solves for the interfacial curvature per unit volume of the phase rather than interfacial area per unit volume to avoid stability issues relating to the consistency requirements between the phase fraction and interfacial area per unit volume. In every other respect this model is as presented in the paper:
    "Development of Interfacial Area Transport Equation"
    Ishii, M., Kim, S. and Kelly, J.,
    Nuclear Engineering and Technology, Vol.37 No.6 December 2005
Source files
IATE.H
IATE.C
Definition at line 65 of file IATE.H.
Constructor & Destructor Documentation
IATE() [1/2]
IATE (const dictionary & diameterProperties, const phaseModel & phase)
Construct from components.
~IATE() [1/2]
virtual ~IATE () virtual
Destructor.
IATE() [2/2]
IATE (const dictionary & diameterProperties, const phaseModel & phase)
Construct from components.
~IATE() [2/2]
virtual ~IATE () virtual
Destructor.
Member Function Documentation
TypeName() [1/2]
TypeName ("IATE")
Runtime type information.
kappai() [1/2]
const volScalarField& kappai () const inline
Return the interfacial curvature.
Definition at line 120 of file IATE.H.
a() [1/2]
tmp<volScalarField> a () const inline
Return the interfacial area.
Definition at line 126 of file IATE.H.
References diameterModel::phase_.
d() [1/2]
virtual tmp<volScalarField> d () const inline virtual
Return the Sauter-mean diameter.
Implements diameterModel.
Definition at line 132 of file IATE.H.
References IATE::correct(), and IATE::read().
correct() [1/2]
virtual void correct () virtual
Correct the diameter field.
Reimplemented from diameterModel.
Referenced by IATE::d().
read() [1/2]
virtual bool read (const dictionary & phaseProperties) virtual
Read phaseProperties dictionary.
Implements diameterModel.
Referenced by IATE::d().
TypeName() [2/2]
TypeName ("IATE")
Runtime type information.
kappai() [2/2]
const volScalarField& kappai () const inline
Return the interfacial curvature.
Definition at line 120 of file IATE.H.
a() [2/2]
tmp<volScalarField> a () const inline
Return the interfacial area.
Definition at line 126 of file IATE.H.
References diameterModel::phase_.
d() [2/2]
virtual tmp<volScalarField> d () const inline virtual
Return the Sauter-mean diameter.
Implements diameterModel.
Definition at line 132 of file IATE.H.
References IATE::correct(), and IATE::read().
correct() [2/2]
virtual void correct () virtual
Correct the diameter field.
Reimplemented from diameterModel.
read() [2/2]
virtual bool read (const dictionary & phaseProperties) virtual
Read phaseProperties dictionary.
Implements diameterModel.
Friends And Related Function Documentation
IATEsource
IATEsource friend
Definition at line 97 of file IATE.H.
The documentation for this class was generated from the following file:
applications/solvers/multiphase/reactingEulerFoam/reactingTwoPhaseEulerFoam/twoPhaseSystem/diameterModels/IATE/IATE.H