OpenFOAM: randomCoalescence Class Reference
randomCoalescence Class Reference
Random coalescence IATE source as defined in paper:
Public Member Functions
TypeName ("randomCoalescence")
Runtime type information.
randomCoalescence (const IATE &iate, const dictionary &dict)
virtual ~randomCoalescence ()
Destructor.
virtual tmp< volScalarField > R () const
TypeName ("randomCoalescence")
Runtime type information.
randomCoalescence (const IATE &iate, const dictionary &dict)
virtual ~randomCoalescence ()
Destructor.
virtual tmp< volScalarField > R () const
Public Member Functions inherited from IATEsource
TypeName ("IATEsource")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, IATEsource, dictionary,(const IATE &iate, const dictionary &dict),(iate, dict))
IATEsource (const IATE &iate)
autoPtr< IATEsource > clone () const
virtual ~IATEsource ()
Destructor.
const phaseModel & phase () const
const twoPhaseSystem & fluid () const
const phaseModel & otherPhase () const
scalar phi () const
tmp< volScalarField > Ur () const
Return the bubble relative velocity.
tmp< volScalarField > Ut () const
Return the bubble turbulent velocity.
tmp< volScalarField > Re () const
Return the bubble Reynolds number.
tmp< volScalarField > CD () const
Return the bubble drag coefficient.
tmp< volScalarField > Mo () const
Return the bubble Morton number.
tmp< volScalarField > Eo () const
Return the bubble Eotvos number.
tmp< volScalarField > We () const
Return the bubble Webber number.
TypeName ("IATEsource")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, IATEsource, dictionary,(const IATE &iate, const dictionary &dict),(iate, dict))
IATEsource (const IATE &iate)
autoPtr< IATEsource > clone () const
virtual ~IATEsource ()
Destructor.
const phaseModel & phase () const
const twoPhaseSystem & fluid () const
const phaseModel & otherPhase () const
scalar phi () const
tmp< volScalarField > Ur () const
Return the bubble relative velocity.
tmp< volScalarField > Ut () const
Return the bubble turbulent velocity.
tmp< volScalarField > Re () const
Return the bubble Reynolds number.
tmp< volScalarField > CD () const
Return the bubble drag coefficient.
tmp< volScalarField > Mo () const
Return the bubble Morton number.
tmp< volScalarField > Eo () const
Return the bubble Eotvos number.
tmp< volScalarField > We () const
Return the bubble Webber number.
Additional Inherited Members
Static Public Member Functions inherited from IATEsource
static autoPtr< IATEsource > New (const word &type, const IATE &iate, const dictionary &dict)
static autoPtr< IATEsource > New (const word &type, const IATE &iate, const dictionary &dict)
Protected Attributes inherited from IATEsource
const IATE & iate_
Reference to the IATE this source applies to.
Detailed Description
Random coalescence IATE source as defined in paper:
    "Development of Interfacial Area Transport Equation"
    Ishii, M., Kim, S. and Kelly, J.,
    Nuclear Engineering and Technology, Vol.37 No.6 December 2005
Source files
randomCoalescence.H
randomCoalescence.C
    "Development of Interfacial Area Transport Equation"
    Ishii, M., Kim, S. and Kelly, J.,
    Nuclear Engineering and Technology, Vol.37 No.6 December 2005
Source files
randomCoalescence.H
randomCoalescence.C
Definition at line 59 of file randomCoalescence.H.
Constructor & Destructor Documentation
randomCoalescence() [1/2]
randomCoalescence (const IATE & iate, const dictionary & dict)
~randomCoalescence() [1/2]
virtual ~randomCoalescence () inline virtual
Destructor.
Definition at line 85 of file randomCoalescence.H.
References randomCoalescence::R().
randomCoalescence() [2/2]
randomCoalescence (const IATE & iate, const dictionary & dict)
~randomCoalescence() [2/2]
virtual ~randomCoalescence () inline virtual
Destructor.
Definition at line 85 of file randomCoalescence.H.
References randomCoalescence::R().
Member Function Documentation
TypeName() [1/2]
TypeName ("randomCoalescence")
Runtime type information.
R() [1/2]
virtual tmp<volScalarField> R () const virtual
Implements IATEsource.
Referenced by randomCoalescence::~randomCoalescence().
TypeName() [2/2]
TypeName ("randomCoalescence")
Runtime type information.
R() [2/2]
virtual tmp<volScalarField> R () const virtual
Implements IATEsource.
The documentation for this class was generated from the following file:
applications/solvers/multiphase/reactingEulerFoam/reactingTwoPhaseEulerFoam/twoPhaseSystem/diameterModels/IATE/IATEsources/randomCoalescence/randomCoalescence.H