OpenFOAM: tractionDisplacementFvPatchVectorField Class Reference
tractionDisplacementFvPatchVectorField Class Reference
Fixed traction boundary condition for the standard linear elastic, fixed coefficient displacement equation.
Public Member Functions
TypeName ("tractionDisplacement")
Runtime type information.
tractionDisplacementFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
tractionDisplacementFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
tractionDisplacementFvPatchVectorField (const tractionDisplacementFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
tractionDisplacementFvPatchVectorField (const tractionDisplacementFvPatchVectorField &)
Construct as copy.
virtual tmp< fvPatchVectorField > clone () const
Construct and return a clone.
tractionDisplacementFvPatchVectorField (const tractionDisplacementFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual const vectorField & traction () const
virtual vectorField & traction ()
virtual const scalarField & pressure () const
virtual scalarField & pressure ()
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchVectorField &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Detailed Description
Fixed traction boundary condition for the standard linear elastic, fixed coefficient displacement equation.
Source files
tractionDisplacementFvPatchVectorField.H
tractionDisplacementFvPatchVectorField.C
Definition at line 50 of file tractionDisplacementFvPatchVectorField.H.
Constructor & Destructor Documentation
tractionDisplacementFvPatchVectorField() [1/5]
tractionDisplacementFvPatchVectorField (const fvPatch & , const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
Referenced by tractionDisplacementFvPatchVectorField::clone().
tractionDisplacementFvPatchVectorField() [2/5]
tractionDisplacementFvPatchVectorField (const fvPatch & , const DimensionedField< vector, volMesh > & , const dictionary &)
Construct from patch, internal field and dictionary.
tractionDisplacementFvPatchVectorField() [3/5]
tractionDisplacementFvPatchVectorField (const tractionDisplacementFvPatchVectorField & , const fvPatch & , const DimensionedField< vector, volMesh > & , const fvPatchFieldMapper &)
Construct by mapping given.
tractionDisplacementFvPatchVectorField onto a new patch
tractionDisplacementFvPatchVectorField() [4/5]
tractionDisplacementFvPatchVectorField (const tractionDisplacementFvPatchVectorField &)
Construct as copy.
tractionDisplacementFvPatchVectorField() [5/5]
tractionDisplacementFvPatchVectorField (const tractionDisplacementFvPatchVectorField & , const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
Member Function Documentation
TypeName()
TypeName ("tractionDisplacement")
Runtime type information.
clone() [1/2]
virtual tmp<fvPatchVectorField> clone () const inline virtual
Construct and return a clone.
Definition at line 101 of file tractionDisplacementFvPatchVectorField.H.
References tractionDisplacementFvPatchVectorField::tractionDisplacementFvPatchVectorField().
clone() [2/2]
virtual tmp<fvPatchVectorField> clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 118 of file tractionDisplacementFvPatchVectorField.H.
References tractionDisplacementFvPatchVectorField::tractionDisplacementFvPatchVectorField().
traction() [1/2]
virtual const vectorField& traction () const inline virtual
Definition at line 133 of file tractionDisplacementFvPatchVectorField.H.
traction() [2/2]
virtual vectorField& traction () inline virtual
Definition at line 138 of file tractionDisplacementFvPatchVectorField.H.
pressure() [1/2]
virtual const scalarField& pressure () const inline virtual
Definition at line 143 of file tractionDisplacementFvPatchVectorField.H.
pressure() [2/2]
virtual scalarField& pressure () inline virtual
Definition at line 148 of file tractionDisplacementFvPatchVectorField.H.
References tractionDisplacementFvPatchVectorField::autoMap(), tractionDisplacementFvPatchVectorField::rmap(), tractionDisplacementFvPatchVectorField::updateCoeffs(), and tractionDisplacementFvPatchVectorField::write().
autoMap()
virtual void autoMap (const fvPatchFieldMapper &) virtual
Map (and resize as needed) from self given a mapping object.
Referenced by tractionDisplacementFvPatchVectorField::pressure().
rmap()
virtual void rmap (const fvPatchVectorField & , const labelList &) virtual
Reverse map the given fvPatchField onto this fvPatchField.
Referenced by tractionDisplacementFvPatchVectorField::pressure().
updateCoeffs()
virtual void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Referenced by tractionDisplacementFvPatchVectorField::pressure().
write()
virtual void write (Ostream &) const virtual
Write.
Referenced by tractionDisplacementFvPatchVectorField::pressure().
The documentation for this class was generated from the following file:
applications/solvers/stressAnalysis/solidDisplacementFoam/tractionDisplacement/tractionDisplacementFvPatchVectorField.H