OpenFOAM: IATEsource::iNew Class Reference
IATEsource::iNew Class Reference
Class used for the read-construction of.
Public Member Functions
iNew (const IATE &iate)
autoPtr< IATEsource > operator() (Istream &is) const
iNew (const IATE &iate)
autoPtr< IATEsource > operator() (Istream &is) const
Detailed Description
Class used for the read-construction of.
PtrLists of IATE sources
Definition at line 87 of file IATEsource.H.
Constructor & Destructor Documentation
iNew() [1/2]
iNew (const IATE & iate) inline
Definition at line 93 of file IATEsource.H.
iNew() [2/2]
iNew (const IATE & iate) inline
Definition at line 92 of file IATEsource.H.
Member Function Documentation
operator()() [1/2]
autoPtr<IATEsource> operator() (Istream & is) const inline
Definition at line 98 of file IATEsource.H.
References dict, IATEsource::New(), and Foam::type().
operator()() [2/2]
autoPtr<IATEsource> operator() (Istream & is) const inline
Definition at line 97 of file IATEsource.H.
References dict, IATEsource::New(), and Foam::type().
The documentation for this class was generated from the following file:
applications/solvers/multiphase/reactingEulerFoam/reactingTwoPhaseEulerFoam/twoPhaseSystem/diameterModels/IATE/IATEsources/IATEsource/IATEsource.H