OpenFOAM: applications/solvers/compressible/rhoCentralFoam/createFieldRefs.H File Reference
createFieldRefs.H File Reference
Functions
bool inviscid (true)
if (max(mu.primitiveField()) > 0.0)
Variables
volScalarField & p = thermo.p()
const volScalarField & T = thermo.T()
const volScalarField & psi = thermo.psi()
const volScalarField & mu = thermo.mu()
Atomic mass unit.
Function Documentation
inviscid()
bool inviscid (true)
Referenced by if().
if()
if (max(mu.primitiveField()) , 0. 0)
Definition at line 7 of file createFieldRefs.H.
References inviscid().
Variable Documentation
p
volScalarField& p = thermo.p()
Definition at line 1 of file createFieldRefs.H.
T
const volScalarField& T = thermo.T()
Definition at line 2 of file createFieldRefs.H.
psi
const volScalarField& psi = thermo.psi()
Definition at line 3 of file createFieldRefs.H.
mu
const volScalarField& mu = thermo.mu()
Atomic mass unit.
Definition at line 4 of file createFieldRefs.H.
Referenced by interRegionExplicitPorositySource::addSup(), forces::calcForcesMoment(), incompressibleTwoPhaseMixture::calcNu(), tetrahedron< Point, PointRef >::circumCentre(), tetrahedron< Point, PointRef >::circumRadius(), NoAtomization< CloudType >::clone(), NoBreakup< CloudType >::clone(), ReitzKHRT< CloudType >::clone(), BlobsSheetAtomization< CloudType >::clone(), ReitzDiwakar< CloudType >::clone(), ETAB< CloudType >::clone(), PilchErdman< CloudType >::clone(), LISAAtomization< CloudType >::clone(), TAB< CloudType >::clone(), SHF< CloudType >::clone(), ThermoSurfaceFilm< CloudType >::drySplashInteraction(), Foam::interpolateSplineXY(), sutherlandTransport< Thermo >::kappa(), filmViscosityModel::New(), porosityModel::iNew::operator()(), BSpline::position(), CatmullRomSpline::position(), polyLine::position(), SprayParcel< ParcelType >::readFields(), laminar::Su(), BreakupModel< Foam::SprayCloud< Foam::DSMCCloud > >::TABtwoWeCrit(), porosityModel::transformModelData(), ReitzKHRT< CloudType >::update(), SHF< CloudType >::update(), inclinedFilmNusseltHeightFvPatchScalarField::updateCoeffs(), inclinedFilmNusseltInletVelocityFvPatchVectorField::updateCoeffs(), splineInterpolationWeights::valueWeights(), ThermoSurfaceFilm< CloudType >::wetSplashInteraction(), and SprayParcel< ParcelType >::writeFields().