OpenFOAM: applications/solvers/combustion/chemFoam/createFieldRefs.H File Reference
createFieldRefs.H File Reference
Variables
scalar dtChem = refCast<const psiChemistryModel>(chemistry).deltaTChem()[0]
basicMultiComponentMixture & composition = thermo.composition()
PtrList< volScalarField > & Y = composition.Y()
volScalarField & p = thermo.p()
Variable Documentation
dtChem
scalar dtChem = refCast<const psiChemistryModel>(chemistry).deltaTChem()[0]
Definition at line 1 of file createFieldRefs.H.
Referenced by if().
composition
basicMultiComponentMixture& composition = thermo.composition()
Definition at line 2 of file createFieldRefs.H.
Referenced by ReactingParcel< ParcelType >::calc(), ReactingMultiphaseParcel< ParcelType >::calc(), SprayParcel< ParcelType >::calc(), SprayParcel< ParcelType >::calcAtomization(), ReactingMultiphaseParcel< ParcelType >::calcDevolatilisation(), ReactingParcel< ParcelType >::calcPhaseChange(), ReactingMultiphaseCloud< Foam::DSMCCloud >::checkParcelProperties(), ReactingCloud< Foam::DSMCCloud >::checkParcelProperties(), SprayParcel< ParcelType >::chi(), forAll(), if(), ReactingCloud< Foam::DSMCCloud >::ReactingCloud(), ReactingMultiphaseCloud< Foam::DSMCCloud >::ReactingMultiphaseCloud(), SprayCloud< Foam::DSMCCloud >::setParcelThermoProperties(), ReactingMultiphaseCloud< Foam::DSMCCloud >::setParcelThermoProperties(), ReactingCloud< Foam::DSMCCloud >::setParcelThermoProperties(), TDACChemistryModel< CompType, ThermoType >::solve(), SprayCloud< Foam::DSMCCloud >::SprayCloud(), TDACChemistryModel< CompType, ThermoType >::TDACChemistryModel(), ReactingMultiphaseCloud< Foam::DSMCCloud >::writeFields(), and ReactingCloud< Foam::DSMCCloud >::writeFields().
Y
PtrList<volScalarField>& Y = composition.Y()
Definition at line 3 of file createFieldRefs.H.
Referenced by SprayParcel< ParcelType >::calc(), SprayParcel< ParcelType >::calcAtomization(), LiquidEvaporationBoil< CloudType >::calculate(), LiquidEvaporation< CloudType >::calcXc(), LiquidEvaporationBoil< CloudType >::calcXc(), dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::findNearest(), indexedOctree< Foam::treeDataFace >::findNearest(), forAll(), singleStepReactingMixture< ThermoType >::fresCorrect(), greyMeanAbsorptionEmission::greyMeanAbsorptionEmission(), if(), ReactingParcel< ParcelType >::readFields(), coordSet::scalarCoord(), SprayCloud< Foam::DSMCCloud >::setParcelThermoProperties(), basicSymmetryFvPatchField< Type >::snGradTransformDiag(), symmetryPlaneFvPatchField< Type >::snGradTransformDiag(), fixedNormalSlipFvPatchField< Type >::snGradTransformDiag(), directionMixedFvPatchField< Type >::snGradTransformDiag(), partialSlipFvPatchField< Type >::snGradTransformDiag(), TDACChemistryModel< CompType, ThermoType >::solve(), TDACChemistryModel< CompType, ThermoType >::TDACChemistryModel(), Vector< vector >::Vector(), Vector2D< scalar >::Vector2D(), basicSpecieMixture::W(), wideBandAbsorptionEmission::wideBandAbsorptionEmission(), ReactingParcel< ParcelType >::writeFields(), Vector2D< scalar >::y(), and Vector< vector >::y().
p
volScalarField& p = thermo.p()
Definition at line 4 of file createFieldRefs.H.
Referenced by greyMeanAbsorptionEmission::aCont(), wideBandAbsorptionEmission::aCont(), preserveBafflesConstraint::add(), snappyLayerDriver::addLayers(), advectiveFvPatchField< Type >::advectiveFvPatchField(), KinematicCloud< Cloud< basicKinematicCollidingParcel > >::alpha(), attachPolyTopoChanger::attach(), FreeStream< CloudType >::autoMap(), Cloud< streamLineParticle >::autoMap(), SprayParcel< ParcelType >::calcBreakup(), CentredFitSnGradData< Polynomial >::calcFit(), FitData< CentredFitSnGradData< Polynomial >, extendedCentredCellToFaceStencil, Polynomial >::calcFit(), forces::calcForcesMoment(), ThermoParcel< ParcelType >::calcHeatTransfer(), Stochastic< CloudType >::calculate(), KinematicParcel< ParcelType >::calcVelocity(), polyMesh::cellZones(), polyMeshTetDecomposition::checkFaceTets(), NoInteraction< CloudType >::clone(), NoDamping< CloudType >::clone(), NoPacking< CloudType >::clone(), Rebound< CloudType >::clone(), SphereDragForce< CloudType >::clone(), NoSurfaceFilm< CloudType >::clone(), VirtualMassForce< CloudType >::clone(), GravityForce< CloudType >::clone(), SRFForce< CloudType >::clone(), DistortedSphereDragForce< CloudType >::clone(), ErgunWenYuDragForce< CloudType >::clone(), PlessisMasliyahDragForce< CloudType >::clone(), WenYuDragForce< CloudType >::clone(), PressureGradientForce< CloudType >::clone(), ParamagneticForce< CloudType >::clone(), Relaxation< CloudType >::clone(), LiquidEvaporation< CloudType >::clone(), VoidFraction< CloudType >::clone(), LiftForce< CloudType >::clone(), LocalInteraction< CloudType >::clone(), Implicit< CloudType >::clone(), Explicit< CloudType >::clone(), LiquidEvaporationBoil< CloudType >::clone(), NonInertialFrameForce< CloudType >::clone(), PatchPostProcessing< CloudType >::clone(), ParticleTrap< CloudType >::clone(), ParticleForce< CloudType >::clone(), ParticleTracks< CloudType >::clone(), ParticleErosion< CloudType >::clone(), StandardWallInteraction< CloudType >::clone(), BrownianMotionForce< CloudType >::clone(), CloudFunctionObject< CloudType >::clone(), iC3H8O::clone(), nC3H8O::clone(), C8H10::clone(), H2O::clone(), aC10H7CH3::clone(), Ar::clone(), C3H6O::clone(), bC10H7CH3::clone(), C10H22::clone(), MultiInteraction< CloudType >::clone(), C12H26::clone(), C13H28::clone(), C14H30::clone(), C16H34::clone(), C2H5OH::clone(), C2H6::clone(), C2H6O::clone(), C3H8::clone(), C4H10O::clone(), C6H14::clone(), C6H6::clone(), C7H16::clone(), C7H8::clone(), C8H18::clone(), C9H20::clone(), CH3OH::clone(), CH4N2O::clone(), IC8H18::clone(), N2::clone(), MB::clone(), NonSphereDragForce< CloudType >::clone(), FacePostProcessing< CloudType >::clone(), IDEA::clone(), cyclicAMIPolyPatch::clone(), ThermoSurfaceFilm< CloudType >::clone(), ParticleCollector< CloudType >::clone(), KinematicCloud< Cloud< basicKinematicCollidingParcel > >::cloneBare(), SuppressionCollision< CloudType >::collide(), ORourkeCollision< CloudType >::collide(), molecule::constantProperties::constantProperties(), face::contactSphereDiameter(), cyclicACMIGAMGInterfaceField::cyclicACMIGAMGInterfaceField(), cyclicAMIGAMGInterfaceField::cyclicAMIGAMGInterfaceField(), cyclicGAMGInterfaceField::cyclicGAMGInterfaceField(), fvFieldDecomposer::decomposeField(), IOstream::defaultPrecision(), Cloud< streamLineParticle >::deleteLostParticles(), Cloud< streamLineParticle >::deleteParticle(), LiquidEvaporationBoil< CloudType >::dh(), KinematicCloud< Cloud< basicKinematicCollidingParcel > >::Dij(), plane::ray::dir(), KinematicCloud< Cloud< basicKinematicCollidingParcel > >::Dmax(), Foam::domainName(), pitchForkRing::energy(), atmBoundaryLayer::epsilon(), externalCoupledMixedFvPatchField< scalar >::externalCoupledMixedFvPatchField(), mappedPatchBase::facePoint(), for(), forAll(), pitchForkRing::force(), FreeStream< CloudType >::FreeStream(), PatchTools::gatherAndMerge(), get_geom_list(), Hash< Foam::label >::Hash(), heThermo< BasicSolidThermo, MixtureType >::he(), particle< Type >::hitWallFaces(), if(), ILList< LListBase, T >::ILList(), Ostream::incrIndent(), FreeStream< CloudType >::inflow(), polyPatch::initMovePoints(), DSMCCloud< DSMCParcel< ParcelType > >::internalEnergyOfSystem(), regionModel::interRegionAMI(), cell::labels(), DSMCCloud< DSMCParcel< ParcelType > >::linearKineticEnergyOfSystem(), KinematicCloud< Cloud< basicKinematicCollidingParcel > >::linearKineticEnergyOfSystem(), DSMCCloud< DSMCParcel< ParcelType > >::linearMomentumOfSystem(), KinematicCloud< Cloud< basicKinematicCollidingParcel > >::linearMomentumOfSystem(), pyramid< Point, PointRef, polygonRef >::mag(), regionModel::mapRegionPatchField(), regionModel::mapRegionPatchInternalField(), DSMCCloud< DSMCParcel< ParcelType > >::massInSystem(), KinematicCloud< Cloud< basicKinematicCollidingParcel > >::massInSystem(), rigidBodyModel::masterPoint(), cellDistFuncs::mesh(), MeshedSurface< Foam::face >::MeshedSurface(), layeredEngineMesh::move(), Cloud< streamLineParticle >::move(), DSMCParcel< ParcelType >::move(), MPPICParcel< ParcelType >::move(), CollidingParcel< ParcelType >::move(), surfaceInterpolation::movePoints(), NamedEnum< directionType, 3 >::names(), regionModel::nbrCoupledPatchID(), tetrahedron< Point, PointRef >::nearestPoint(), pointPatchField< vector >::New(), fvsPatchField< Type >::New(), fvPatchField< Type >::New(), fvsPatchField< Type >::NewCalculatedType(), fvPatchField< Type >::NewCalculatedType(), surfacePatch::operator!=(), geometricSurfacePatch::operator!=(), listPlusEqOp< T >::operator()(), sigmaRadial::operator()(), Hash< Foam::string >::operator()(), tetrahedron< Point, PointRef >::storeOp::operator()(), Hash< Foam::word >::operator()(), Hash< Foam::fileName >::operator()(), Hash< Foam::wordRe >::operator()(), Hash< Foam::keyType >::operator()(), KinematicParcel< ParcelType >::iNew::operator()(), Foam::operator*(), Foam::operator/(), Foam::operator<<(), token::operator=(), dynamicTreeDataPoint::overlaps(), wallBoundedParticle::patchInteraction(), SprayCloud< Foam::DSMCCloud >::penetration(), cell::points(), cellShape::points(), triFace::points(), face::points(), PatchPostProcessing< CloudType >::postPatch(), processorGAMGInterfaceField::processorGAMGInterfaceField(), triangle< Point, PointRef >::ray(), solidParticle::readFields(), MPPICParcel< ParcelType >::readFields(), CollidingParcel< ParcelType >::readFields(), DSMCParcel< ParcelType >::readFields(), ReactingParcel< ParcelType >::readFields(), ReactingMultiphaseParcel< ParcelType >::readFields(), ThermoParcel< ParcelType >::readFields(), SprayParcel< ParcelType >::readFields(), particle< Type >::readFields(), KinematicParcel< ParcelType >::readFields(), EFA< CompType, ThermoType >::reduceMechanism(), PFA< CompType, ThermoType >::reduceMechanism(), DRG< CompType, ThermoType >::reduceMechanism(), DAC< CompType, ThermoType >::reduceMechanism(), DRGEP< CompType, ThermoType >::reduceMechanism(), NullMRF::relative(), UILList< LListBase, T >::remove(), SLListBase::remove(), autoPtr< Foam::lduMatrix::solver >::reset(), linear< Type >::rho(), KinematicCloud< Cloud< basicKinematicCollidingParcel > >::rhoEff(), CollidingCloud< KinematicCloud< Cloud< basicKinematicCollidingParcel > > >::rotationalKineticEnergyOfSystem(), general::sample(), multiNormal::sample(), coordSet::scalarCoord(), autoPtr< Foam::lduMatrix::solver >::set(), PointIndexHit< Point >::setPoint(), PointHit< point >::setPoint(), liquidMixtureProperties::sigma(), liquidMixtureProperties::size(), ode< ChemistryModel >::solve(), SprayParcel< ParcelType >::solveTABEq(), thermo< Thermo, Type >::thermo(), constantFilmThermo::thermoData::thermoData(), KinematicCloud< Cloud< basicKinematicCollidingParcel > >::theta(), ThermoCloud< Foam::DSMCCloud >::Tmax(), ThermoCloud< Foam::DSMCCloud >::Tmin(), dictionary::topDict(), CV2D::toPoint2D(), CV2D::toPoint3D(), wallBoundedParticle::TrackingData< Cloud< wallBoundedStreamLineParticle > >::TrackingData(), streamLineParticle::trackingData::trackingData(), wallBoundedStreamLineParticle::trackingData::trackingData(), particle< Type >::trackToFace(), heheuPsiThermo< BasicPsiThermo, MixtureType >::Tu(), infiniteReactionRate::type(), thirdBodyArrheniusReactionRate::type(), ArrheniusReactionRate::type(), LandauTellerReactionRate::type(), solidArrheniusReactionRate::type(), powerSeriesReactionRate::type(), JanevReactionRate::type(), LangmuirHinshelwoodReactionRate::type(), FallOffReactionRate< ReactionRate, FallOffFunction >::type(), ChemicallyActivatedReactionRate< ReactionRate, ChemicallyActivationFunction >::type(), hConstThermo< EquationOfState >::typeName(), hRefConstThermo< EquationOfState >::typeName(), constTransport< Thermo >::typeName(), eConstThermo< EquationOfState >::typeName(), polynomialTransport< Thermo, PolySize >::typeName(), janafThermo< EquationOfState >::typeName(), hPolynomialThermo< EquationOfState, PolySize >::typeName(), logPolynomialTransport< Thermo, PolySize >::typeName(), hPowerThermo< EquationOfState >::typeName(), sutherlandTransport< Thermo >::typeName(), SHF< CloudType >::update(), MPPICParcel< ParcelType >::TrackingData< CloudType >::updateAverages(), ReactingParcel< ParcelType >::updateMassFraction(), meshRefinement::userFaceData(), KinematicCloud< Cloud< basicKinematicCollidingParcel > >::vDotSweep(), coordSet::vectorCoord(), waveTransmissiveFvPatchField< Type >::waveTransmissiveFvPatchField(), while(), OBJedgeFormat::write(), dsmcFields::write(), OBJstream::write(), meshToMeshMethod::writeConnectivity(), solidParticle::writeFields(), MPPICParcel< ParcelType >::writeFields(), CollidingParcel< ParcelType >::writeFields(), DSMCParcel< ParcelType >::writeFields(), ReactingParcel< ParcelType >::writeFields(), ReactingMultiphaseParcel< ParcelType >::writeFields(), ThermoParcel< ParcelType >::writeFields(), SprayParcel< ParcelType >::writeFields(), KinematicParcel< ParcelType >::writeFields(), Cloud< streamLineParticle >::writePositions(), liquidMixtureProperties::Xs(), basicSpecieMixture::~basicSpecieMixture(), Gulders::~Gulders(), GuldersEGR::~GuldersEGR(), IrreversibleReaction< ReactionType, ReactionThermo, ReactionRate >::~IrreversibleReaction(), leastSquaresVectors::~leastSquaresVectors(), liquidProperties::~liquidProperties(), multiComponentMixture< ThermoType >::~multiComponentMixture(), NonEquilibriumReversibleReaction< ReactionType, ReactionThermo, ReactionRate >::~NonEquilibriumReversibleReaction(), RaviPetersen::~RaviPetersen(), Reaction< ReactionThermo >::~Reaction(), ReversibleReaction< ReactionType, ReactionThermo, ReactionRate >::~ReversibleReaction(), skewCorrectionVectors::~skewCorrectionVectors(), SpecieMixture< MixtureType >::~SpecieMixture(), thermophysicalFunction::~thermophysicalFunction(), and TRIsurfaceFormatCore::~TRIsurfaceFormatCore().