OpenFOAM: applications/solvers/combustion/coldEngineFoam/createFieldRefs.H File Reference
createFieldRefs.H File Reference
Variables
const volScalarField & psi = thermo.psi()
const volScalarField & T = thermo.T()
Variable Documentation
psi
const volScalarField& psi = thermo.psi()
Definition at line 1 of file createFieldRefs.H.
Referenced by Amultiplier< Type, LUType >::addAmul(), SemiImplicitSource< Type >::addSup(), LduMatrix< Type, DType, LUType >::Amul(), lduMatrix::Amul(), LduMatrix< Type, DType, LUType >::asymmetric(), lduMatrix::asymmetric(), rotorDiskSource::constructGeometry(), Foam::fvc::DDt(), Foam::MULES::explicitSolve(), for(), if(), Foam::MULES::implicitSolve(), lduMatrix::solver::interfaces(), lduMatrix::smoother::interfaces(), Foam::MULES::limiter(), Foam::MULES::limiterCorr(), LduMatrix< Type, DType, LUType >::solver::matrix(), LduMatrix< Type, DType, LUType >::smoother::matrix(), steadyStateDdtScheme< Type >::mesh(), EulerDdtScheme< Type >::mesh(), boundedDdtScheme< Type >::mesh(), backwardDdtScheme< Type >::mesh(), CoEulerDdtScheme< Type >::mesh(), SLTSDdtScheme< Type >::mesh(), localEulerDdtScheme< Type >::mesh(), interpolation< Foam::Vector >::New(), CrankNicolsonDdtScheme< Type >::ocCoeff(), fixedTrim::read(), diagonalSolver::read(), LduMatrix< Type, DType, LUType >::residual(), lduMatrix::residual(), fvMatrix< Type >::setValuesFromList(), fvMatrix< Type >::fvSolver::solve(), fvMatrix< Type >::solveCoupled(), fvMatrix< Type >::solveSegregated(), targetCoeffTrim::thetag(), LduMatrix< Type, DType, LUType >::Tmul(), lduMatrix::Tmul(), EulerCoordinateRotation::transformVector(), while(), PBiCCCG< Type, DType, LUType >::~PBiCCCG(), PBiCG::~PBiCG(), PBiCGStab::~PBiCGStab(), PBiCICG< Type, DType, LUType >::~PBiCICG(), PCG::~PCG(), PCICG< Type, DType, LUType >::~PCICG(), and smoothSolver::~smoothSolver().
T
const volScalarField& T = thermo.T()
Definition at line 2 of file createFieldRefs.H.
Referenced by mapDistributeBase::accessAndFlip(), UList< Foam::wordRe >::byteSize(), SprayParcel< ParcelType >::calc(), SprayParcel< ParcelType >::calcAtomization(), SprayParcel< ParcelType >::calcBreakup(), FixedList< bool, Foam::pTraits< Type >::nComponents >::cdata(), SprayParcel< ParcelType >::chi(), tmp< Foam::surfaceInterpolationScheme< GType > >::clear(), Pstream::combineGather(), Pstream::combineScatter(), MixedDiffuseSpecular< CloudType >::correct(), particle< Type >::correctAfterParallelTransfer(), PengRobinsonGas< Specie >::cp(), PengRobinsonGas< Specie >::cpMcv(), Foam::createWithValues(), UList< Foam::wordRe >::deepCopy(), mapDistributeBase::distribute(), linearViscousStress< RASModel< BasicTurbulenceModel > >::divDevRhoReff(), ReynoldsStress< RASModel< BasicTurbulenceModel > >::divDevRhoReff(), Dictionary< simpleObjectRegistryEntry >::erase(), HashPtrTable< ThermoType >::erase(), LPtrList< LListBase, T >::eraseHead(), Pstream::exchange(), FixedList< bool, Foam::pTraits< Type >::nComponents >::FixedList(), mapDistributeBase::flipAndCombine(), forAll(), forAllIter(), rigidBodyModel::forwardDynamics(), DictionaryBase< DLPtrList< T >, T >::found(), meshRefinement::gAverage(), CompositionModel< Foam::ReactingCloud< Foam::DSMCCloud > >::H(), HashPtrTable< ThermoType >::HashPtrTable(), heThermo< BasicSolidThermo, MixtureType >::he(), CompositionModel< Foam::ReactingCloud< Foam::DSMCCloud > >::Hs(), if(), Dual< Type >::interpolateGrad(), thermo< Thermo, Type >::K(), hPowerThermo< EquationOfState >::limit(), List< Field< scalar > >::List(), LList< Foam::chemPointISAT< CompType, ThermoType > *>::LList(), dictionary::lookupOrDefault(), Moment< Type >::Moment(), sutherlandTransport< Thermo >::mu(), radiationModel::New(), Foam::NullObjectPtr(), Foam::NullObjectRef(), LandauTellerReactionRate::operator()(), JanevReactionRate::operator()(), autoPtr< Foam::lduMatrix::solver >::operator()(), StaticHashTable< T, Key, Hash >::operator()(), autoPtr< Foam::lduMatrix::solver >::operator->(), CompactIOList< face, label >::operator=(), HashPtrTable< ThermoType >::operator=(), tmp< Foam::surfaceInterpolationScheme< GType > >::operator=(), PtrList< MRFZone >::operator=(), LList< Foam::chemPointISAT< CompType, ThermoType > *>::operator=(), UList< Foam::wordRe >::operator=(), List< Field< scalar > >::operator=(), FixedList< bool, Foam::pTraits< Type >::nComponents >::operator==(), UList< Foam::wordRe >::operator==(), StaticHashTable< T, Key, Hash >::operator[](), StaticHashTable< T, Key, Hash >::printInfo(), HashTable< Foam::phase *>::printInfo(), perfectFluid< Specie >::psi(), PengRobinsonGas< Specie >::psi(), autoPtr< Foam::lduMatrix::solver >::ptr(), tmp< Foam::surfaceInterpolationScheme< GType > >::ptr(), PtrList< MRFZone >::read(), ThermoParcel< ParcelType >::readFields(), Foam::ReadHex(), EFA< CompType, ThermoType >::reduceMechanism(), PFA< CompType, ThermoType >::reduceMechanism(), DRG< CompType, ThermoType >::reduceMechanism(), DAC< CompType, ThermoType >::reduceMechanism(), DRGEP< CompType, ThermoType >::reduceMechanism(), HashPtrTable< ThermoType >::remove(), DictionaryBase< DLPtrList< T >, T >::remove(), DynamicList< Foam::Tensor >::remove(), PtrList< MRFZone >::reorder(), UPtrList< Foam::Field< Type > >::reorder(), perfectFluid< Specie >::rho(), incompressiblePerfectGas< Specie >::rho(), PengRobinsonGas< Specie >::rho(), PtrListDictionary< phaseModel >::set(), autoPtr< Foam::lduMatrix::solver >::set(), UPtrList< Foam::Field< Type > >::set(), PtrList< MRFZone >::setSize(), List< Field< scalar > >::setSize(), ode< ChemistryModel >::solve(), HashTable< Foam::phase *>::sortedToc(), FixedList< bool, Foam::pTraits< Type >::nComponents >::swap(), FieldField< Foam::Field, LUType >::T(), Field< Foam::Vector2D >::T(), thermo< Thermo, Type >::TEa(), thermo< Thermo, Type >::TEs(), meshRefinement::testSyncBoundaryFaceList(), thermo< Thermo, Type >::THa(), thermo< Thermo, Type >::THs(), FixedList< bool, Foam::pTraits< Type >::nComponents >::transfer(), Foam::transformPoints(), tmp< Foam::surfaceInterpolationScheme< GType > >::typeName(), meshRefinement::updateList(), HashPtrTable< ThermoType >::write(), FixedList< bool, Foam::pTraits< Type >::nComponents >::writeEntry(), UList< Foam::wordRe >::writeEntry(), ThermoParcel< ParcelType >::writeFields(), and PengRobinsonGas< Specie >::Z().