OpenFOAM: applications/solvers/multiphase/reactingEulerFoam/reactingTwoPhaseEulerFoam/createFieldRefs.H File Reference
createFieldRefs.H File Reference
Variables
phaseModel & phase1 = fluid.phase1()
phaseModel & phase2 = fluid.phase2()
volScalarField & alpha1 = phase1
volScalarField & alpha2 = phase2
volVectorField & U1 = phase1.U()
surfaceScalarField & phi1 = phase1.phi()
surfaceScalarField & alphaPhi1 = phase1.alphaPhi()
surfaceScalarField & alphaRhoPhi1 = phase1.alphaRhoPhi()
volVectorField & U2 = phase2.U()
surfaceScalarField & phi2 = phase2.phi()
surfaceScalarField & alphaPhi2 = phase2.alphaPhi()
surfaceScalarField & alphaRhoPhi2 = phase2.alphaRhoPhi()
surfaceScalarField & phi = fluid.phi()
rhoThermo & thermo1 = phase1.thermo()
rhoThermo & thermo2 = phase2.thermo()
volScalarField & rho1 = thermo1.rho()
const volScalarField & psi1 = thermo1.psi()
volScalarField & rho2 = thermo2.rho()
const volScalarField & psi2 = thermo2.psi()
const IOMRFZoneList & MRF = fluid.MRF()
fv::options & fvOptions = fluid.fvOptions()
Variable Documentation
phase1
phaseModel& phase1 = fluid.phase1()
Definition at line 1 of file createFieldRefs.H.
Referenced by for(), forAll(), if(), and while().
phase2
phaseModel& phase2 = fluid.phase2()
Definition at line 2 of file createFieldRefs.H.
Referenced by for(), forAll(), forAllIter(), if(), and while().
alpha1
volScalarField& alpha1 = phase1
Definition at line 4 of file createFieldRefs.H.
Referenced by for(), forAll(), if(), and while().
alpha2
volScalarField& alpha2 = phase2
Definition at line 5 of file createFieldRefs.H.
U1
volVectorField& U1 = phase1.U()
Definition at line 7 of file createFieldRefs.H.
Referenced by TrajectoryCollision< CloudType >::collideParcels(), ORourkeCollision< CloudType >::collideSorted(), for(), if(), and while().
phi1
surfaceScalarField& phi1 = phase1.phi()
Definition at line 8 of file createFieldRefs.H.
Referenced by while().
alphaPhi1
surfaceScalarField& alphaPhi1 = phase1.alphaPhi()
Definition at line 9 of file createFieldRefs.H.
Referenced by for(), and while().
alphaRhoPhi1
surfaceScalarField& alphaRhoPhi1 = phase1.alphaRhoPhi()
Definition at line 10 of file createFieldRefs.H.
U2
volVectorField& U2 = phase2.U()
Definition at line 12 of file createFieldRefs.H.
Referenced by TrajectoryCollision< CloudType >::collideParcels(), ORourkeCollision< CloudType >::collideSorted(), for(), if(), and while().
phi2
surfaceScalarField& phi2 = phase2.phi()
Definition at line 13 of file createFieldRefs.H.
Referenced by while().
alphaPhi2
surfaceScalarField& alphaPhi2 = phase2.alphaPhi()
Definition at line 14 of file createFieldRefs.H.
Referenced by for(), and while().
alphaRhoPhi2
surfaceScalarField& alphaRhoPhi2 = phase2.alphaRhoPhi()
Definition at line 15 of file createFieldRefs.H.
phi
surfaceScalarField& phi = fluid.phi()
Definition at line 16 of file createFieldRefs.H.
thermo1
rhoThermo& thermo1 = phase1.thermo()
Definition at line 18 of file createFieldRefs.H.
thermo2
rhoThermo& thermo2 = phase2.thermo()
Definition at line 19 of file createFieldRefs.H.
rho1
volScalarField& rho1 = thermo1.rho()
Definition at line 21 of file createFieldRefs.H.
psi1
const volScalarField& psi1 = thermo1.psi()
Definition at line 22 of file createFieldRefs.H.
rho2
volScalarField& rho2 = thermo2.rho()
Definition at line 24 of file createFieldRefs.H.
psi2
const volScalarField& psi2 = thermo2.psi()
Definition at line 25 of file createFieldRefs.H.
MRF
const IOMRFZoneList& MRF = fluid.MRF()
Definition at line 27 of file createFieldRefs.H.
fvOptions
fv::options& fvOptions = fluid.fvOptions()
Definition at line 28 of file createFieldRefs.H.