OpenFOAM: applications/solvers/compressible/sonicFoam/createFieldRefs.H File Reference
createFieldRefs.H File Reference
Variables
volScalarField & e = thermo.he()
Elementary charge.
const volScalarField & psi = thermo.psi()
Variable Documentation
e
volScalarField& e = thermo.he()
Elementary charge.
Definition at line 1 of file createFieldRefs.H.
Referenced by Foam::adjustPhi(), enrichedPatch::calcEnrichedFaces(), PatchTools::checkOrientation(), TrajectoryCollision< CloudType >::collideParcels(), edgeVertex::coord(), dtris2(), thermo< Thermo, Type >::E(), Foam::meshTools::findEdge(), indexedOctree< Foam::treeDataFace >::findLine(), dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::findNearest(), treeDataPrimitivePatch< PatchType >::getVolumeType(), if(), interpolationCellPointFace< Type >::interpolate(), TDACChemistryModel< CompType, ThermoType >::jacobian(), PatchTools::matchEdges(), treeDataPrimitivePatch< PatchType >::findSelfIntersectOp::operator()(), cell::opposingFace(), Foam::meshTools::otherEdge(), NASedgeFormat::read(), CodedSource< Type >::read(), GeometricField< Type, PatchField, GeoMesh >::Boundary::readField(), Foam::solve(), EulerImplicit< ChemistryModel >::solve(), SprayParcel< ParcelType >::solveTABEq(), PatchTools::sortedEdgeFaces(), swapec(), triangulation_plot_eps(), LISAAtomization< CloudType >::update(), vbedg(), timeVaryingMappedFixedValuePointPatchField< Type >::write(), timeVaryingMappedFixedValueFvPatchField< Type >::write(), edgeVertex::writeCut(), and VTKedgeFormat::writeEdges().
psi
const volScalarField& psi = thermo.psi()
Definition at line 2 of file createFieldRefs.H.