OpenFOAM: applications/solvers/incompressible/pimpleFoam/pimpleDyMFoam/pEqn.H File Reference
pEqn.H File Reference
Functions
volScalarField rAU (1.0/UEqn.A())
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p))
surfaceScalarField phiHbyA ("phiHbyA", fvc::flux(HbyA)+fvc::interpolate(rAU) *fvc::ddtCorr(U, Uf))
MRF makeRelative (phiHbyA)
if (p.needReference())
tmp< volScalarField > rAtU (rAU)
if (pimple.consistent())
if (pimple.nCorrPISO()<=1)
constrainPressure (p, U, phiHbyA, rAtU(), MRF)
while (pimple.correctNonOrthogonal())
p relax ()
U correctBoundaryConditions ()
fvOptions correct (U)
surfaceVectorField n (mesh.Sf()/mesh.magSf())
Variables
U = HbyA - rAtU*fvc::grad(p)
Uf = n*(phi/mesh.magSf() - (n & Uf))
Function Documentation
rAU()
volScalarField rAU (1.0/UEqn. A())
HbyA()
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p))
phiHbyA()
surfaceScalarField phiHbyA ("phiHbyA" , fvc::flux(HbyA)+fvc::interpolate(rAU) *fvc::ddtCorr(U, Uf))
makeRelative()
MRF makeRelative (phiHbyA)
if() [1/3]
if (p. needReference())
Definition at line 12 of file pEqn.H.
References adjustPhi(), Foam::fvc::makeAbsolute(), makeRelative(), p, phiHbyA, rAtU(), rAU(), and U.
rAtU()
tmp<volScalarField> rAtU (rAU)
if() [2/3]
if (pimple. consistent())
Definition at line 21 of file pEqn.H.
References Foam::fvc::grad(), HbyA, Foam::MULES::interpolate(), Foam::max(), mesh, p, phiHbyA, rAtU(), rAU(), Foam::fvc::snGrad(), and UEqn.
if() [3/3]
if (pimple.nCorrPISO()<= 1)
Definition at line 29 of file pEqn.H.
References constrainPressure(), MRF, p, phiHbyA, rAtU(), tUEqn(), and U.
constrainPressure()
constrainPressure (p , U , phiHbyA , rAtU() , MRF)
while()
while (pimple. correctNonOrthogonal())
Definition at line 38 of file pEqn.H.
References Foam::fvc::div(), Foam::fvc::laplacian(), mesh, p, phi, phiHbyA, pimple, pRefCell, pRefValue, and rAtU().
relax()
p relax ()
correctBoundaryConditions()
U correctBoundaryConditions ()
correct()
fvOptions correct (U)
n()
surfaceVectorField n (mesh. Sf)/mesh.magSf()
Variable Documentation
U
U = HbyA - rAtU*fvc::grad(p)
Definition at line 60 of file pEqn.H.
Uf
Uf = n*(phi/mesh.magSf() - (n & Uf))
Definition at line 67 of file pEqn.H.
Referenced by dynamicLagrangian< BasicTurbulenceModel >::correct(), MRFZoneList::correctBoundaryFlux(), Foam::fvc::ddt(), if(), and while().