OpenFOAM: applications/solvers/compressible/rhoSimpleFoam/pEqn.H File Reference
pEqn.H File Reference
Functions
surfaceScalarField rhorAUf ("rhorAUf", fvc::interpolate(rho *rAU))
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p))
tUEqn clear ()
if (simple.transonic())
MRF makeRelative (fvc::interpolate(rho), phiHbyA)
constrainPressure (p, rho, U, phiHbyA, rhorAUf, MRF)
while (simple.correctNonOrthogonal())
p relax ()
U correctBoundaryConditions ()
fvOptions correct (U)
if (closedVolume)
if (!simple.transonic())
Variables
bool closedVolume = false
else
U = HbyA - rAU*fvc::grad(p)
rho = thermo.rho()
Function Documentation
rhorAUf()
surfaceScalarField rhorAUf ("rhorAUf" , fvc::interpolate(rho *rAU))
HbyA()
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p))
clear()
tUEqn clear ()
if() [1/3]
if (simple. transonic())
Definition at line 9 of file pEqn.H.
References Foam::fvc::div(), Foam::fvc::flux(), fvOptions, HbyA, Foam::MULES::interpolate(), Foam::fvc::laplacian(), MRF, p, phi, phid(), pRefCell, pRefValue, psi, rho, rhorAUf(), and simple.
makeRelative()
MRF makeRelative (fvc::interpolate(rho) , phiHbyA)
constrainPressure()
constrainPressure (p , rho , U , phiHbyA , rhorAUf , MRF)
while()
while (simple. correctNonOrthogonal())
Definition at line 53 of file pEqn.H.
References Foam::fvc::div(), fvOptions, Foam::fvc::laplacian(), p, phi, pRefCell, pRefValue, psi, rho, rhorAUf(), and simple.
relax()
p relax ()
correctBoundaryConditions()
U correctBoundaryConditions ()
correct()
fvOptions correct (U)
if() [2/3]
if (closedVolume)
Definition at line 86 of file pEqn.H.
References Foam::fvc::domainIntegrate(), initialMass, p, and psi.
if() [3/3]
if (!simple. transonic())
Definition at line 96 of file pEqn.H.
References Foam::endl(), Foam::Info, Foam::max(), Foam::min(), and rho.
Variable Documentation
closedVolume
closedVolume = false
Definition at line 7 of file pEqn.H.
else
else
Initial value:
{
        surfaceScalarField phiHbyA("phiHbyA", fvc::flux(rho*HbyA))
Definition at line 44 of file pEqn.H.
U
U = HbyA - rAU*fvc::grad(p)
Definition at line 80 of file pEqn.H.
rho
rho = thermo.rho()
Definition at line 92 of file pEqn.H.