OpenFOAM: applications/solvers/lagrangian/reactingParcelFoam/simpleReactingParcelFoam/pEqn.H File Reference
pEqn.H File Reference
Functions
volScalarField rAU (1.0/UEqn.A())
surfaceScalarField rhorAUf ("rhorAUf", fvc::interpolate(rho *rAU))
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p))
tUEqn clear ()
surfaceScalarField phiHbyA ("phiHbyA", fvc::interpolate(rho) *fvc::flux(HbyA))
MRF makeRelative (fvc::interpolate(rho), phiHbyA)
constrainPressure (p, rho, U, phiHbyA, rhorAUf, MRF)
while (simple.correctNonOrthogonal())
p relax ()
thermo rho ()+
U correctBoundaryConditions ()
fvOptions correct (U)
Variables
U = HbyA - rAU*fvc::grad(p)
rho = thermo.rho()
Function Documentation
rAU()
volScalarField rAU (1.0/UEqn. A())
rhorAUf()
surfaceScalarField rhorAUf ("rhorAUf" , fvc::interpolate(rho *rAU))
HbyA()
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p))
clear()
tUEqn clear ()
phiHbyA()
surfaceScalarField phiHbyA ("phiHbyA" , fvc::interpolate(rho) *fvc::flux(HbyA))
makeRelative()
MRF makeRelative (fvc::interpolate(rho) , phiHbyA)
constrainPressure()
constrainPressure (p , rho , U , phiHbyA , rhorAUf , MRF)
while()
while (simple. correctNonOrthogonal())
Definition at line 21 of file pEqn.H.
References Foam::fvc::div(), fvOptions, Foam::fvc::laplacian(), p, phi, phiHbyA, psi, rho, rhorAUf(), simple, and thermo.
relax()
p relax ()
rho()
thermo rho ()
correctBoundaryConditions()
U correctBoundaryConditions ()
correct()
fvOptions correct (U)
Variable Documentation
U
U = HbyA - rAU*fvc::grad(p)
Definition at line 47 of file pEqn.H.
rho
rho = thermo.rho()
Definition at line 51 of file pEqn.H.