OpenFOAM: applications/solvers/heatTransfer/chtMultiRegionFoam/fluid/pEqn.H File Reference
pEqn.H File Reference
Functions
volScalarField rAU ("rAU", 1.0/UEqn.A())
surfaceScalarField rhorAUf ("rhorAUf", fvc::interpolate(rho *rAU))
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p_rgh))
surfaceScalarField phig (-rhorAUf *ghf *fvc::snGrad(rho) *mesh.magSf())
surfaceScalarField phiHbyA ("phiHbyA",(fvc::flux(rho *HbyA)+rhorAUf *fvc::ddtCorr(rho, U, phi))+phig)
MRF makeRelative (fvc::interpolate(rho), phiHbyA)
constrainPressure (p_rgh, rho, U, phiHbyA, rhorAUf, MRF)
thermo rho () -
for (int nonOrth=0;nonOrth<=nNonOrthCorr;nonOrth++)
if (thermo.dpdt())
Variables
dimensionedScalar compressibility = fvc::domainIntegrate(psi)
bool compressible = (compressibility.value() > SMALL)
rho = thermo.rho()
p = p_rgh + rho*gh
Function Documentation
rAU()
volScalarField rAU ("rAU" , 1.0/UEqn. A())
rhorAUf()
surfaceScalarField rhorAUf ("rhorAUf" , fvc::interpolate(rho *rAU))
HbyA()
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p_rgh))
phig()
surfaceScalarField phig (-rhorAUf *ghf * fvc::snGradrho) *mesh.magSf()
phiHbyA()
surfaceScalarField phiHbyA ("phiHbyA" , (fvc::flux(rho *HbyA)+rhorAUf *fvc::ddtCorr(rho, U, phi))+ phig)
makeRelative()
MRF makeRelative (fvc::interpolate(rho) , phiHbyA)
constrainPressure()
constrainPressure (p_rgh , rho , U , phiHbyA , rhorAUf , MRF)
rho()
thermo rho ()
for()
for (int nonOrth = 0; nonOrth<=nNonOrthCorr; nonOrth++)
Definition at line 40 of file pEqn.H.
References fvOptions, Foam::fvc::laplacian(), Foam::magSqr(), mesh, nCorr, nNonOrthCorr, nOuterCorr, p_rgh, p_rghDDtEqn(), phi, phig(), phiHbyA, psi, rAU(), Foam::fvc::reconstruct(), rhorAUf(), thermo, and U.
if()
if (thermo. dpdt())
Definition at line 81 of file pEqn.H.
References compressibility, Foam::fvc::ddt(), Foam::fvc::domainIntegrate(), dpdt, gh, initialMass, p, rho, and thermo.
Variable Documentation
compressibility
dimensionedScalar compressibility = fvc::domainIntegrate(psi)
Definition at line 3 of file pEqn.H.
compressible
bool compressible = (compressibility.value() > SMALL)
Definition at line 4 of file pEqn.H.
rho
rho = thermo.rho()
Definition at line 6 of file pEqn.H.
p
p = p_rgh + rho*gh
Definition at line 78 of file pEqn.H.