OpenFOAM: applications/solvers/incompressible/simpleFoam/porousSimpleFoam/pEqn.H File Reference
pEqn.H File Reference
Functions
if (pressureImplicitPorosity)
tUEqn clear ()
surfaceScalarField phiHbyA ("phiHbyA", fvc::flux(HbyA))
MRF makeRelative (phiHbyA)
adjustPhi (phiHbyA, U, p)
while (simple.correctNonOrthogonal())
p relax ()
U correctBoundaryConditions ()
fvOptions correct (U)
Variables
tmp< volVectorField > tHbyA
else
volVectorField & HbyA = tHbyA.ref()
Function Documentation
if()
if (pressureImplicitPorosity)
Definition at line 2 of file pEqn.H.
References Foam::constrainHbyA(), p, tHbyA, trTU, U, and UEqn.
clear()
tUEqn clear ()
phiHbyA()
surfaceScalarField phiHbyA ("phiHbyA" , fvc::flux(HbyA))
makeRelative()
MRF makeRelative (phiHbyA)
adjustPhi()
adjustPhi (phiHbyA , U , p)
while()
while (simple. correctNonOrthogonal())
Definition at line 19 of file pEqn.H.
References Foam::fvc::div(), fvOptions, Foam::fvc::grad(), Foam::fvc::laplacian(), p, phi, phiHbyA, pRefCell, pRefValue, pressureImplicitPorosity(), simple, trAU, trTU, and U.
relax()
p relax ()
correctBoundaryConditions()
U correctBoundaryConditions ()
correct()
fvOptions correct (U)
Variable Documentation
tHbyA
tmp<volVectorField> tHbyA
Definition at line 1 of file pEqn.H.
else
else
Initial value:
{
    tHbyA = constrainHbyA(trAU()*UEqn.H(), U, p)
Definition at line 7 of file pEqn.H.
HbyA
volVectorField& HbyA = tHbyA.ref()
Definition at line 10 of file pEqn.H.