OpenFOAM: applications/solvers/combustion/PDRFoam/pEqn.H File Reference
pEqn.H File Reference
Functions
volScalarField rAU (1.0/UEqn.A())
volVectorField HbyA (constrainHbyA(invA &UEqn.H(), U, p))
if (pimple.transonic())
while (pimple.correctNonOrthogonal())
U correctBoundaryConditions ()
fvOptions correct (U)
if (thermo.dpdt())
Variables
rho = thermo.rho()
else
U = HbyA - (invA & (betav*fvc::grad(p)))
K = 0.5*magSqr(U)
Function Documentation
rAU()
volScalarField rAU (1.0/UEqn. A())
HbyA()
volVectorField HbyA (constrainHbyA(invA &UEqn.H(), U, p))
if() [1/2]
if (pimple. transonic())
Definition at line 6 of file pEqn.H.
References betav, Foam::fvc::ddt(), Foam::fvc::ddtCorr(), Foam::fvc::div(), Foam::fvc::flux(), fvOptions, HbyA, Foam::MULES::interpolate(), invA(), Foam::fvc::laplacian(), mesh, p, phi, phid(), pimple, psi, rAU(), rho, and U.
while()
while (pimple. correctNonOrthogonal())
Definition at line 49 of file pEqn.H.
References betav, Foam::fvc::ddt(), Foam::fvc::div(), fvOptions, invA(), Foam::fvc::laplacian(), mesh, p, phi, pimple, psi, and rho.
correctBoundaryConditions()
U correctBoundaryConditions ()
correct()
fvOptions correct (U)
if() [2/2]
if (thermo. dpdt())
Definition at line 77 of file pEqn.H.
References Foam::fvc::ddt(), dpdt, and p.
Variable Documentation
rho
rho = thermo.rho()
Definition at line 1 of file pEqn.H.
else
else
Initial value:
{
    surfaceScalarField phiHbyA
    (
        "phiHbyA",
        (
            fvc::flux(rho*HbyA)
          + fvc::interpolate(rho*rAU)*fvc::ddtCorr(rho, U, phi)
        )
    )
Definition at line 39 of file pEqn.H.
U
U = HbyA - (invA & (betav*fvc::grad(p)))
Definition at line 72 of file pEqn.H.
K
K = 0.5*magSqr(U)
Definition at line 75 of file pEqn.H.