OpenFOAM: applications/solvers/heatTransfer/buoyantBoussinesqSimpleFoam/pEqn.H File Reference
pEqn.H File Reference
Functions
surfaceScalarField rAUf ("rAUf", fvc::interpolate(rAU))
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p_rgh))
tUEqn clear ()
surfaceScalarField phig (-rAUf *ghf *fvc::snGrad(rhok) *mesh.magSf())
surfaceScalarField phiHbyA ("phiHbyA", fvc::flux(HbyA))
MRF makeRelative (phiHbyA)
adjustPhi (phiHbyA, U, p_rgh)
constrainPressure (p_rgh, U, phiHbyA, rAUf, MRF)
while (simple.correctNonOrthogonal())
if (p_rgh.needReference())
Variables
phiHbyA = phig
p = p_rgh + rhok*gh
Function Documentation
rAUf()
surfaceScalarField rAUf ("rAUf" , fvc::interpolate(rAU))
HbyA()
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p_rgh))
clear()
tUEqn clear ()
phig()
surfaceScalarField phig (-rAUf *ghf * fvc::snGradrhok) *mesh.magSf()
phiHbyA()
surfaceScalarField phiHbyA ("phiHbyA" , fvc::flux(HbyA))
makeRelative()
MRF makeRelative (phiHbyA)
adjustPhi()
adjustPhi (phiHbyA , U , p_rgh)
Referenced by if().
constrainPressure()
constrainPressure (p_rgh , U , phiHbyA , rAUf , MRF)
while()
while (simple. correctNonOrthogonal())
Definition at line 25 of file pEqn.H.
References Foam::fvc::div(), fvOptions, Foam::getRefCellValue(), HbyA, Foam::fvc::laplacian(), p_rgh, phi, phig(), phiHbyA, pRefCell, rAU(), rAUf(), Foam::fvc::reconstruct(), simple, and U.
if()
if (p_rgh. needReference())
Definition at line 56 of file pEqn.H.
References Foam::getRefCellValue(), gh, p, p_rgh, pRefCell, pRefValue, and rhok.
Variable Documentation
phiHbyA
phiHbyA = phig
Definition at line 20 of file pEqn.H.
Referenced by for(), forAllIter(), if(), and while().
p
p = p_rgh + rhok*gh
Definition at line 54 of file pEqn.H.