OpenFOAM: applications/solvers/incompressible/pisoFoam/pEqn.H File Reference
pEqn.H File Reference
Functions
volScalarField rAU (1.0/UEqn.A())
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p))
surfaceScalarField phiHbyA ("phiHbyA", fvc::flux(HbyA)+fvc::interpolate(rAU) *fvc::ddtCorr(U, phi))
MRF makeRelative (phiHbyA)
adjustPhi (phiHbyA, U, p)
constrainPressure (p, U, phiHbyA, rAU, MRF)
while (piso.correctNonOrthogonal())
U correctBoundaryConditions ()
fvOptions correct (U)
Variables
U = HbyA - rAU*fvc::grad(p)
Function Documentation
rAU()
volScalarField rAU (1.0/UEqn. A())
HbyA()
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p))
phiHbyA()
surfaceScalarField phiHbyA ("phiHbyA" , fvc::flux(HbyA)+fvc::interpolate(rAU) *fvc::ddtCorr(U, phi))
makeRelative()
MRF makeRelative (phiHbyA)
adjustPhi()
adjustPhi (phiHbyA , U , p)
constrainPressure()
constrainPressure (p , U , phiHbyA , rAU , MRF)
while()
while (piso. correctNonOrthogonal())
Definition at line 18 of file pEqn.H.
References Foam::fvc::div(), Foam::fvc::laplacian(), mesh, p, phi, phiHbyA, piso(), pRefCell, pRefValue, and rAU().
correctBoundaryConditions()
U correctBoundaryConditions ()
correct()
fvOptions correct (U)
Variable Documentation
U
U = HbyA - rAU*fvc::grad(p)
Definition at line 39 of file pEqn.H.