OpenFOAM: applications/solvers/lagrangian/reactingParcelFoam/pEqn.H File Reference
pEqn.H File Reference
Functions
thermo rho () -
volScalarField rAU (1.0/UEqn.A())
surfaceScalarField rhorAUf ("rhorAUf", fvc::interpolate(rho *rAU))
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p))
surfaceScalarField phiHbyA ("phiHbyA",(fvc::flux(rho *HbyA)+rhorAUf *fvc::ddtCorr(rho, U, phi)))
MRF makeRelative (fvc::interpolate(rho), phiHbyA)
constrainPressure (p, rho, U, phiHbyA, rhorAUf, MRF)
fvScalarMatrix pDDtEqn (fvc::ddt(rho)+psi *correction(fvm::ddt(p))+fvc::div(phiHbyA)==parcels.Srho()+fvOptions(psi, p, rho.name()))
while (pimple.correctNonOrthogonal())
p relax ()
rhoEqn solve ()
fvOptions correct (rho)
Function Documentation
rho()
thermo rho ()
rAU()
volScalarField rAU (1.0/UEqn. A())
rhorAUf()
surfaceScalarField rhorAUf ("rhorAUf" , fvc::interpolate(rho *rAU))
HbyA()
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p))
phiHbyA()
surfaceScalarField phiHbyA ("phiHbyA" , (fvc::flux(rho *HbyA)+rhorAUf *fvc::ddtCorr(rho, U, phi)))
makeRelative()
MRF makeRelative (fvc::interpolate(rho) , phiHbyA)
constrainPressure()
constrainPressure (p , rho , U , phiHbyA , rhorAUf , MRF)
pDDtEqn()
fvScalarMatrix pDDtEqn (fvc::ddt(rho)+psi *correction(fvm::ddt(p))+fvc::div(phiHbyA) = =parcels.Srho()+fvOptions(psi, p, rho.name()))
while()
while (pimple. correctNonOrthogonal())
Definition at line 34 of file pEqn.H.
References Foam::fvc::ddt(), dpdt, Foam::endl(), fvOptions, Foam::fvc::grad(), Foam::Info, Foam::fvc::laplacian(), Foam::magSqr(), Foam::max(), mesh, Foam::min(), p, pDDtEqn(), phi, phiHbyA, pimple, psi, rAU(), rho, rhoMax(), rhoMin(), rhorAUf(), thermo, and U.
relax()
p relax ()
solve()
rhoEqn solve ()
Referenced by while().
correct()
fvOptions correct (rho)