OpenFOAM: applications/solvers/lagrangian/reactingParcelFilmFoam/pEqn.H File Reference
pEqn.H File Reference
Functions
volScalarField rAU (1.0/UEqn.A())
surfaceScalarField rhorAUf ("rhorAUf", fvc::interpolate(rho *rAU))
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p))
surfaceScalarField phig (-rhorAUf *ghf *fvc::snGrad(rho) *mesh.magSf())
surfaceScalarField phiHbyA ("phiHbyA",(fvc::flux(rho *HbyA)+rhorAUf *fvc::ddtCorr(rho, U, phi))+phig)
MRF makeRelative (fvc::interpolate(rho), phiHbyA)
constrainPressure (p_rgh, rho, U, phiHbyA, rhorAUf, MRF)
while (pimple.correctNonOrthogonal())
if (thermo.dpdt())
Variables
rho = thermo.rho()
p = p_rgh + rho*gh
K = 0.5*magSqr(U)
Function Documentation
rAU()
volScalarField rAU (1.0/UEqn. A())
rhorAUf()
surfaceScalarField rhorAUf ("rhorAUf" , fvc::interpolate(rho *rAU))
HbyA()
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p))
phig()
surfaceScalarField phig (-rhorAUf *ghf * fvc::snGradrho) *mesh.magSf()
phiHbyA()
surfaceScalarField phiHbyA ("phiHbyA" , (fvc::flux(rho *HbyA)+rhorAUf *fvc::ddtCorr(rho, U, phi))+ phig)
makeRelative()
MRF makeRelative (fvc::interpolate(rho) , phiHbyA)
constrainPressure()
constrainPressure (p_rgh , rho , U , phiHbyA , rhorAUf , MRF)
while()
while (pimple. correctNonOrthogonal())
Definition at line 24 of file pEqn.H.
References Foam::fvc::ddt(), Foam::fvc::div(), fvOptions, gh, Foam::fvc::laplacian(), mesh, p_rgh, phi, phig(), phiHbyA, pimple, psi, rAU(), Foam::fvc::reconstruct(), rho, rhorAUf(), surfaceFilm, and U.
if()
if (thermo. dpdt())
Definition at line 56 of file pEqn.H.
References Foam::fvc::ddt(), dpdt, and p.
Variable Documentation
rho
rho = thermo.rho()
Definition at line 1 of file pEqn.H.
p
p = p_rgh + rho*gh
Definition at line 49 of file pEqn.H.
K
K = 0.5*magSqr(U)
Definition at line 54 of file pEqn.H.