OpenFOAM: applications/solvers/compressible/sonicFoam/pEqn.H File Reference
pEqn.H File Reference
Functions
volScalarField rAU (1.0/UEqn.A())
surfaceScalarField rhorAUf ("rhorAUf", fvc::interpolate(rho *rAU))
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p))
surfaceScalarField phid ("phid", fvc::interpolate(psi) *(fvc::flux(HbyA)+rhorAUf *fvc::ddtCorr(rho, U, phi)/fvc::interpolate(rho)))
MRF makeRelative (fvc::interpolate(psi), phid)
while (pimple.correctNonOrthogonal())
U correctBoundaryConditions ()
fvOptions correct (U)
Variables
rho = thermo.rho()
U = HbyA - rAU*fvc::grad(p)
K = 0.5*magSqr(U)
Function Documentation
rAU()
volScalarField rAU (1.0/UEqn. A())
rhorAUf()
surfaceScalarField rhorAUf ("rhorAUf" , fvc::interpolate(rho *rAU))
HbyA()
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p))
phid()
surfaceScalarField phid ("phid" , fvc::interpolate(psi) *(fvc::flux(HbyA)+rhorAUf *fvc::ddtCorr(rho, U, phi)/fvc::interpolate(rho)))
Referenced by if(), kinematicSingleLayer::solveThickness(), and while().
makeRelative()
MRF makeRelative (fvc::interpolate(psi) , phid)
while()
while (pimple. correctNonOrthogonal())
Definition at line 19 of file pEqn.H.
References Foam::fvc::ddt(), Foam::fvc::div(), fvOptions, Foam::fvc::laplacian(), p, phi, phid(), pimple, psi, rho, and rhorAUf().
correctBoundaryConditions()
U correctBoundaryConditions ()
correct()
fvOptions correct (U)
Variable Documentation
rho
rho = thermo.rho()
Definition at line 1 of file pEqn.H.
U
U = HbyA - rAU*fvc::grad(p)
Definition at line 41 of file pEqn.H.
K
K = 0.5*magSqr(U)
Definition at line 44 of file pEqn.H.