OpenFOAM: applications/solvers/compressible/rhoPimpleFoam/pEqn.H File Reference
pEqn.H File Reference
Functions
rho relax ()
volScalarField rAU (1.0/UEqn.A())
surfaceScalarField rhorAUf ("rhorAUf", fvc::interpolate(rho *rAU))
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p))
if (pimple.nCorrPISO()<=1)
if (pimple.transonic())
MRF makeRelative (fvc::interpolate(rho), phiHbyA)
constrainPressure (p, rho, U, phiHbyA, rhorAUf, MRF)
while (pimple.correctNonOrthogonal())
Variables
rho = thermo.rho()
else
Function Documentation
relax()
rho relax ()
rAU()
volScalarField rAU (1.0/UEqn. A())
rhorAUf()
surfaceScalarField rhorAUf ("rhorAUf" , fvc::interpolate(rho *rAU))
HbyA()
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p))
if() [1/2]
if (pimple.nCorrPISO()<= 1)
Definition at line 10 of file pEqn.H.
References tUEqn().
if() [2/2]
if (pimple. transonic())
Definition at line 15 of file pEqn.H.
References Foam::fvc::ddt(), Foam::fvc::ddtCorr(), Foam::fvc::div(), Foam::fvc::flux(), fvOptions, HbyA, Foam::MULES::interpolate(), Foam::fvc::laplacian(), mesh, MRF, p, phi, phid(), pimple, psi, rho, rhorAUf(), and U.
makeRelative()
MRF makeRelative (fvc::interpolate(rho) , phiHbyA)
constrainPressure()
constrainPressure (p , rho , U , phiHbyA , rhorAUf , MRF)
while()
while (pimple. correctNonOrthogonal())
Definition at line 64 of file pEqn.H.
References Foam::fvc::ddt(), Foam::fvc::div(), dpdt, Foam::endl(), fvOptions, Foam::fvc::grad(), Foam::Info, Foam::fvc::laplacian(), Foam::magSqr(), Foam::max(), mesh, Foam::min(), p, phi, pimple, psi, rAU(), rho, rhoMax(), rhoMin(), rhorAUf(), thermo, and U.
Variable Documentation
rho
rho = thermo.rho()
Definition at line 1 of file pEqn.H.
else
else
Initial value:
{
    surfaceScalarField phiHbyA
    (
        "phiHbyA",
        (
            fvc::flux(rho*HbyA)
          + rhorAUf*fvc::ddtCorr(rho, U, phi)
        )
    )
Definition at line 49 of file pEqn.H.