OpenFOAM: applications/solvers/combustion/engineFoam/pEqn.H File Reference
pEqn.H File Reference
Functions
volScalarField rAU (1.0/UEqn.A())
surfaceScalarField rhorAUf ("rhorAUf", fvc::interpolate(rho *rAU))
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p))
if (pimple.transonic())
MRF makeRelative (fvc::interpolate(rho), phiHbyA)
constrainPressure (p, rho, U, phiHbyA, rhorAUf, MRF)
while (pimple.correctNonOrthogonal())
U correctBoundaryConditions ()
fvOptions correct (U)
surfaceVectorField n (mesh.Sf()/mesh.magSf())
if (thermo.dpdt())
Variables
rho = thermo.rho()
else
U = HbyA - rAU*fvc::grad(p)
K = 0.5*magSqr(U)
rhoUf = n*(fvc::absolute(phi, rho, U)/mesh.magSf() - (n & rhoUf))
Function Documentation
rAU()
volScalarField rAU (1.0/UEqn. A())
Referenced by meanVelocityForce::correct(), for(), if(), NullMRF::relative(), and while().
rhorAUf()
surfaceScalarField rhorAUf ("rhorAUf" , fvc::interpolate(rho *rAU))
Referenced by for(), if(), and while().
HbyA()
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p))
if() [1/2]
if (pimple. transonic())
Definition at line 7 of file pEqn.H.
References Foam::fvc::ddt(), Foam::fvc::ddtCorr(), Foam::fvc::div(), Foam::fvc::flux(), fvOptions, HbyA, Foam::MULES::interpolate(), Foam::fvc::laplacian(), makeRelative(), mesh, MRF, p, phi, phid(), pimple, psi, rho, rhorAUf(), rhoUf, and U.
makeRelative()
MRF makeRelative (fvc::interpolate(rho) , phiHbyA)
Referenced by if().
constrainPressure()
constrainPressure (p , rho , U , phiHbyA , rhorAUf , MRF)
Referenced by if().
while()
while (pimple. correctNonOrthogonal())
Definition at line 60 of file pEqn.H.
References Foam::fvc::ddt(), Foam::fvc::div(), fvOptions, Foam::fvc::laplacian(), mesh, p, phi, pimple, psi, rho, and rhorAUf().
correctBoundaryConditions()
U correctBoundaryConditions ()
Referenced by faceLimitedGrad< Type >::calcGrad(), faceMDLimitedGrad< Type >::calcGrad(), cellMDLimitedGrad< Type >::calcGrad(), cellLimitedGrad< Type >::calcGrad(), SlicedGeometricField< Type, PatchField, SlicedPatchField, GeoMesh >::correctBoundaryConditions(), makeFvGradScheme(), anisotropicFilter::operator()(), SlicedGeometricField< Type, PatchField, SlicedPatchField, GeoMesh >::SlicedGeometricField(), and solidBodyMotionFvMesh::update().
correct()
fvOptions correct (U)
n()
surfaceVectorField n (mesh. Sf)/mesh.magSf()
Referenced by while().
if() [2/2]
if (thermo. dpdt())
Definition at line 94 of file pEqn.H.
References Foam::fvc::ddt(), Foam::fvc::div(), dpdt, Foam::fvc::meshPhi(), p, rho, and U.
Variable Documentation
rho
rho = thermo.rho()
Definition at line 1 of file pEqn.H.
Referenced by forAllConstIter(), forAllIter(), if(), and while().
else
else
Initial value:
{
    surfaceScalarField phiHbyA
    (
        "phiHbyA",
        (
            fvc::flux(rho*HbyA)
          + rhorAUf*fvc::ddtCorr(rho, U, rhoUf)
        )
    )
Definition at line 44 of file pEqn.H.
U
U = HbyA - rAU*fvc::grad(p)
Definition at line 83 of file pEqn.H.
Referenced by MRFZone::addCoriolis(), buoyancyEnergy::addSup(), interRegionExplicitPorositySource::addSup(), radialActuationDiskSource::addSup(), actuationDiskSource::addSup(), effectivenessHeatExchangerSource::addSup(), atmBoundaryLayerInletVelocityFvPatchVectorField::atmBoundaryLayerInletVelocityFvPatchVectorField(), mixtureKEpsilon< BasicTurbulenceModel >::bubbleG(), Implicit< CloudType >::cacheFields(), SprayParcel< ParcelType >::calcAtomization(), SprayParcel< ParcelType >::calcBreakup(), powerLaw::calcForce(), forces::calcForcesMoment(), tabulatedHeatTransfer::calculateHtc(), NoBreakup< CloudType >::clone(), NoDispersion< CloudType >::clone(), StochasticDispersionRAS< CloudType >::clone(), ReitzKHRT< CloudType >::clone(), GradientDispersionRAS< CloudType >::clone(), ReitzDiwakar< CloudType >::clone(), ETAB< CloudType >::clone(), PilchErdman< CloudType >::clone(), TAB< CloudType >::clone(), SHF< CloudType >::clone(), SpecularReflection< CloudType >::correct(), MaxwellianThermal< CloudType >::correct(), MixedDiffuseSpecular< CloudType >::correct(), Rebound< CloudType >::correct(), LocalInteraction< CloudType >::correct(), StandardWallInteraction< CloudType >::correct(), thixotropicViscosity::correct(), kOmegaSSTLM< BasicTurbulenceModel >::correctReThetatGammaInt(), mixtureKEpsilon< BasicTurbulenceModel >::Ct2(), Foam::fvc::ddt(), forces::devRhoReff(), DispersionRASModel< CloudType >::epsilonModel(), for(), forAll(), forAllIter(), if(), FreeStream< CloudType >::inflow(), DispersionRASModel< CloudType >::kModel(), layeredEngineMesh::move(), fvMotionSolverEngineMesh::move(), solidParticleCloud::move(), streamLineParticle::move(), viscosityModel::New(), laminarModel< BasicTurbulenceModel >::New(), RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > >::New(), LESModel< BasicTurbulenceModel >::New(), ReynoldsStress< RASModel< BasicTurbulenceModel > >::nut(), porosityModel::iNew::operator()(), KinematicCloud< Cloud< basicKinematicCollidingParcel > >::patchData(), ParticleErosion< CloudType >::postPatch(), DSMCParcel< ParcelType >::readFields(), KinematicParcel< ParcelType >::readFields(), NullMRF::relative(), SprayParcel< ParcelType >::solveTABEq(), KinematicCloud< Cloud< basicKinematicCollidingParcel > >::SU(), BreakupModel< Foam::SprayCloud< Foam::DSMCCloud > >::TABtwoWeCrit(), streamLineParticle::trackingData::trackingData(), porosityModel::transformModelData(), TurbulenceModel< volScalarField, geometricOneField, incompressibleTurbulenceModel, TransportModel >::TurbulenceModel(), SRFModel::Uabs(), dynamicMotionSolverFvMesh::update(), rawTopoChangerFvMesh::update(), dynamicInkJetFvMesh::update(), solidBodyMotionFvMesh::update(), movingWallVelocityFvPatchVectorField::updateCoeffs(), translatingWallVelocityFvPatchVectorField::updateCoeffs(), mappedFlowRateFvPatchVectorField::updateCoeffs(), supersonicFreestreamFvPatchVectorField::updateCoeffs(), plenumPressureFvPatchScalarField::updateCoeffs(), MRFZone::updateMesh(), Implicit< CloudType >::velocityCorrection(), ThermoSurfaceFilm< CloudType >::wetSplashInteraction(), while(), DSMCParcel< ParcelType >::writeFields(), KinematicParcel< ParcelType >::writeFields(), FSD< CombThermoType, ThermoType >::~FSD(), limitVelocity::~limitVelocity(), linearViscousStress< RASModel< BasicTurbulenceModel > >::~linearViscousStress(), Maxwell< BasicTurbulenceModel >::~Maxwell(), and nonlinearEddyViscosity< incompressible::RASModel >::~nonlinearEddyViscosity().
K
K = 0.5*magSqr(U)
Definition at line 86 of file pEqn.H.
Referenced by while().
rhoUf
rhoUf = n*(fvc::absolute(phi, rho, U)/mesh.magSf() - (n & rhoUf))
Definition at line 91 of file pEqn.H.
Referenced by if(), and while().