OpenFOAM: applications/solvers/incompressible/pimpleFoam/SRFPimpleFoam/pEqn.H File Reference
pEqn.H File Reference
Functions
volScalarField rAUrel (1.0/UrelEqn.A())
volVectorField HbyA ("HbyA", Urel)
surfaceScalarField phiHbyA ("phiHbyA", fvc::flux(HbyA)+fvc::interpolate(rAUrel) *fvc::ddtCorr(Urel, phi))
adjustPhi (phiHbyA, Urel, p)
tmp< volScalarField > rAtUrel (rAUrel)
if (pimple.consistent())
if (pimple.nCorrPISO()<=1)
constrainPressure (p, Urel, phiHbyA, rAtUrel())
while (pimple.correctNonOrthogonal())
p relax ()
Urel correctBoundaryConditions ()
fvOptions correct (Urel)
Variables
HbyA = rAUrel*UrelEqn.H()
Urel = HbyA - rAtUrel()*fvc::grad(p)
Function Documentation
rAUrel()
volScalarField rAUrel (1.0/UrelEqn. A())
Referenced by if().
HbyA()
volVectorField HbyA ("HbyA" , Urel)
phiHbyA()
surfaceScalarField phiHbyA ("phiHbyA" , fvc::flux(HbyA)+fvc::interpolate(rAUrel) *fvc::ddtCorr(Urel, phi))
adjustPhi()
adjustPhi (phiHbyA , Urel , p)
rAtUrel()
tmp<volScalarField> rAtUrel (rAUrel)
Referenced by if(), and while().
if() [1/2]
if (pimple. consistent())
Definition at line 16 of file pEqn.H.
References Foam::fvc::grad(), HbyA, Foam::MULES::interpolate(), Foam::max(), mesh, p, phiHbyA, rAtUrel(), rAUrel(), Foam::fvc::snGrad(), and UrelEqn.
if() [2/2]
if (pimple.nCorrPISO()<= 1)
Definition at line 24 of file pEqn.H.
References constrainPressure(), p, phiHbyA, rAtUrel(), tUrelEqn(), and Urel.
constrainPressure()
constrainPressure (p , Urel , phiHbyA , rAtUrel())
while()
while (pimple. correctNonOrthogonal())
Definition at line 33 of file pEqn.H.
References Foam::fvc::div(), Foam::fvc::laplacian(), mesh, p, phi, phiHbyA, pimple, pRefCell, pRefValue, and rAtUrel().
relax()
p relax ()
correctBoundaryConditions()
Urel correctBoundaryConditions ()
correct()
fvOptions correct (Urel)
Variable Documentation
HbyA
HbyA = rAUrel*UrelEqn.H()
Definition at line 3 of file pEqn.H.
Urel
Urel = HbyA - rAtUrel()*fvc::grad(p)
Definition at line 56 of file pEqn.H.
Referenced by ThermoSurfaceFilm< CloudType >::absorbInteraction(), ThermoSurfaceFilm< CloudType >::bounceInteraction(), SprayParcel< ParcelType >::calcAtomization(), SprayParcel< ParcelType >::calcBreakup(), NoBreakup< CloudType >::clone(), NoAtomization< CloudType >::clone(), ReitzKHRT< CloudType >::clone(), BlobsSheetAtomization< CloudType >::clone(), ReitzDiwakar< CloudType >::clone(), ETAB< CloudType >::clone(), PilchErdman< CloudType >::clone(), TAB< CloudType >::clone(), LISAAtomization< CloudType >::clone(), SHF< CloudType >::clone(), ThermoSurfaceFilm< CloudType >::drySplashInteraction(), if(), SRFModel::New(), ThermoSurfaceFilm< CloudType >::splashInteraction(), BreakupModel< Foam::SprayCloud< Foam::DSMCCloud > >::TABtwoWeCrit(), LISAAtomization< CloudType >::update(), and ThermoSurfaceFilm< CloudType >::wetSplashInteraction().