OpenFOAM: applications/solvers/compressible/sonicFoam/sonicDyMFoam/pEqn.H File Reference
pEqn.H File Reference
Functions
volScalarField rAU (1.0/UEqn.A())
surfaceScalarField rhorAUf ("rhorAUf", fvc::interpolate(rho *rAU))
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p))
surfaceScalarField phid ("phid", fvc::interpolate(psi) *(fvc::flux(HbyA)+rhorAUf *fvc::ddtCorr(rho, U, rhoUf)/fvc::interpolate(rho)))
MRF makeRelative (fvc::interpolate(psi), phid)
while (pimple.correctNonOrthogonal())
U correctBoundaryConditions ()
fvOptions correct (U)
surfaceVectorField n (mesh.Sf()/mesh.magSf())
Variables
rho = thermo.rho()
U = HbyA - rAU*fvc::grad(p)
K = 0.5*magSqr(U)
rhoUf = n*(fvc::absolute(phi, rho, U)/mesh.magSf() - (n & rhoUf))
Function Documentation
rAU()
volScalarField rAU (1.0/UEqn. A())
rhorAUf()
surfaceScalarField rhorAUf ("rhorAUf" , fvc::interpolate(rho *rAU))
HbyA()
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p))
phid()
surfaceScalarField phid ("phid" , fvc::interpolate(psi) *(fvc::flux(HbyA)+rhorAUf *fvc::ddtCorr(rho, U, rhoUf)/fvc::interpolate(rho)))
makeRelative()
MRF makeRelative (fvc::interpolate(psi) , phid)
while()
while (pimple. correctNonOrthogonal())
Definition at line 20 of file pEqn.H.
References Foam::fvc::ddt(), Foam::fvc::div(), fvOptions, Foam::fvc::laplacian(), p, phi, phid(), pimple, psi, rho, and rhorAUf().
correctBoundaryConditions()
U correctBoundaryConditions ()
correct()
fvOptions correct (U)
n()
surfaceVectorField n (mesh. Sf)/mesh.magSf()
Variable Documentation
rho
rho = thermo.rho()
Definition at line 1 of file pEqn.H.
U
U = HbyA - rAU*fvc::grad(p)
Definition at line 42 of file pEqn.H.
K
K = 0.5*magSqr(U)
Definition at line 45 of file pEqn.H.
rhoUf
rhoUf = n*(fvc::absolute(phi, rho, U)/mesh.magSf() - (n & rhoUf))
Definition at line 50 of file pEqn.H.