OpenFOAM: applications/solvers/multiphase/cavitatingFoam/cavitatingDyMFoam/pEqn.H File Reference
pEqn.H File Reference
Functions
volScalarField rAU (1.0/UEqn.A())
surfaceScalarField rhorAUf ("rhorAUf", fvc::interpolate(rho *rAU))
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p))
surfaceScalarField phiGradp (rhorAUf *mesh.magSf() *fvc::snGrad(p))
volScalarField rho0 (rho - psi *p)
while (pimple.correctNonOrthogonal())
Variables
phi
Function Documentation
rAU()
volScalarField rAU (1.0/UEqn. A())
rhorAUf()
surfaceScalarField rhorAUf ("rhorAUf" , fvc::interpolate(rho *rAU))
HbyA()
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p))
phiGradp()
surfaceScalarField phiGradp (rhorAUf *mesh. magSf) *fvc::snGrad(p)
Referenced by while().
rho0()
volScalarField rho0 (rho - psi * p)
Referenced by if(), and while().
while()
while (pimple. correctNonOrthogonal())
Definition at line 28 of file pEqn.H.
References alphal, Foam::correction(), Foam::fvc::ddt(), Foam::fvc::div(), Foam::endl(), Foam::fvc::grad(), HbyA, Foam::Info, Foam::MULES::interpolate(), Foam::fvc::laplacian(), Foam::mag(), Foam::max(), mesh, Foam::min(), n(), p, phiGradp(), pimple, psi, rAU(), Foam::readLabel(), rho, rho0(), rhof(), rhoMin(), rhorAUf(), U, and Uf.
Variable Documentation
phi
phi
Initial value:
= fvc::flux(HbyA)
         + rhorAUf*fvc::ddtCorr(U, Uf)
Definition at line 18 of file pEqn.H.
Referenced by for(), forAllConstIter(), forAllIter(), if(), and while().