OpenFOAM: applications/solvers/lagrangian/DPMFoam/pEqn.H File Reference
pEqn.H File Reference
Functions
surfaceScalarField phiHbyA ("phiHbyA",(fvc::flux(HbyA)+alphacf *rAUcf *fvc::ddtCorr(Uc, phic)+phicForces))
constrainPressure (p, Uc, phiHbyA, rAUcf)
while (pimple.correctNonOrthogonal())
Variables
HbyA = rAUc*UcEqn.H()
Function Documentation
phiHbyA()
surfaceScalarField phiHbyA ("phiHbyA" , (fvc::flux(HbyA)+alphacf *rAUcf *fvc::ddtCorr(Uc, phic)+phicForces))
constrainPressure()
constrainPressure (p , Uc , phiHbyA , rAUcf)
while()
while (pimple. correctNonOrthogonal())
Definition at line 19 of file pEqn.H.
References Foam::fvc::ddt(), Foam::fvc::div(), HbyA, Foam::fvc::laplacian(), mesh, p, phic, phicForces(), phiHbyA, pimple, pRefCell, pRefValue, rAUc(), rAUcf(), and Foam::fvc::reconstruct().
Variable Documentation
HbyA
HbyA = rAUc*UcEqn.H()
Definition at line 3 of file pEqn.H.