OpenFOAM: applications/solvers/multiphase/compressibleInterFoam/pEqn.H File Reference
pEqn.H File Reference
Functions
surfaceScalarField rAUf ("rAUf", fvc::interpolate(rAU))
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p_rgh))
surfaceScalarField phiHbyA ("phiHbyA", fvc::flux(HbyA)+fvc::interpolate(rho *rAU) *fvc::ddtCorr(U, phi))
surfaceScalarField phig ((interface.surfaceTensionForce() - ghf *fvc::snGrad(rho)) *rAUf *mesh.magSf())
constrainPressure (p_rgh, U, phiHbyA, rAUf)
if (pimple.transonic())
volScalarField p_rgh_0 (p_rgh)
while (pimple.correctNonOrthogonal())
p_rgh correctBoundaryConditions ()
Variables
phiHbyA = phig
tmp< fvScalarMatrix > p_rghEqnComp1
tmp< fvScalarMatrix > p_rghEqnComp2
else
rho1 = psi1*(p_rgh - p_rgh_0)
rho2 = psi2*(p_rgh - p_rgh_0)
rho = alpha1*rho1 + alpha2*rho2
p_rgh = p - rho*gh
K = 0.5*magSqr(U)
Function Documentation
rAUf()
surfaceScalarField rAUf ("rAUf" , fvc::interpolate(rAU))
HbyA()
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p_rgh))
phiHbyA()
surfaceScalarField phiHbyA ("phiHbyA" , fvc::flux(HbyA)+fvc::interpolate(rho *rAU) *fvc::ddtCorr(U, phi))
phig()
surfaceScalarField phig ((interface.surfaceTensionForce() - ghf *fvc::snGrad(rho)) *rAUf *mesh.magSf())
constrainPressure()
constrainPressure (p_rgh , U , phiHbyA , rAUf)
if()
if (pimple. transonic())
Definition at line 28 of file pEqn.H.
References Foam::correction(), Foam::fvc::ddt(), Foam::deleteDemandDrivenData(), Foam::fvc::div(), Foam::MULES::interpolate(), p_rgh, phi, psi1, psi2, rho1, rho2, and Foam::fvc::Sp().
p_rgh_0()
volScalarField p_rgh_0 (p_rgh)
while()
while (pimple. correctNonOrthogonal())
Definition at line 67 of file pEqn.H.
References alpha1, alpha2, Foam::fvc::div(), gh, HbyA, Foam::fvc::laplacian(), Foam::max(), mesh, p, p_rgh, p_rghEqnComp1, p_rghEqnComp2, phi, phig(), phiHbyA, pimple, pMin(), Foam::pos(), rAUf(), Foam::fvc::reconstruct(), rho1, rho2, solve(), and U.
correctBoundaryConditions()
p_rgh correctBoundaryConditions ()
Variable Documentation
phiHbyA
phiHbyA = phig
Definition at line 20 of file pEqn.H.
p_rghEqnComp1
tmp<fvScalarMatrix> p_rghEqnComp1
Definition at line 25 of file pEqn.H.
p_rghEqnComp2
p_rghEqnComp2
Initial value:
=
            fvc::ddt(rho2) + psi2*correction(fvm::ddt(p_rgh))
          + fvc::div(phi, rho2) - fvc::Sp(fvc::div(phi), rho2)
Definition at line 26 of file pEqn.H.
else
else
Initial value:
{
        p_rghEqnComp1 =
            fvc::ddt(rho1) + psi1*correction(fvm::ddt(p_rgh))
          + fvc::div(phi, rho1) - fvc::Sp(fvc::div(phi), rho1)
Definition at line 54 of file pEqn.H.
rho1
rho1 = psi1*(p_rgh - p_rgh_0)
Definition at line 105 of file pEqn.H.
rho2
rho2 = psi2*(p_rgh - p_rgh_0)
Definition at line 106 of file pEqn.H.
rho
rho = alpha1*rho1 + alpha2*rho2
Definition at line 108 of file pEqn.H.
p_rgh
p_rgh = p - rho*gh
Definition at line 111 of file pEqn.H.
K
K = 0.5*magSqr(U)
Definition at line 114 of file pEqn.H.