OpenFOAM: applications/solvers/combustion/chemFoam/readControls.H File Reference
readControls.H File Reference
Functions
runTime controlDict ().lookup("adjustTimeStep") >> adjustTimeStep
Variables
maxDeltaT = readScalar(runTime.controlDict().lookup("maxDeltaT"))
Function Documentation
controlDict()
runTime controlDict ()
Referenced by GAMGProcAgglomeration::New(), GAMGAgglomeration::New(), and setTimeStepFunctionObject::read().
Variable Documentation
maxDeltaT
maxDeltaT = readScalar(runTime.controlDict().lookup("maxDeltaT"))
Definition at line 3 of file readControls.H.