OpenFOAM: applications/solvers/multiphase/interFoam/interDyMFoam/pEqn.H File Reference
pEqn.H File Reference
Functions
surfaceScalarField rAUf ("rAUf", fvc::interpolate(rAU))
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p_rgh))
surfaceScalarField phiHbyA ("phiHbyA", fvc::flux(HbyA)+fvc::interpolate(rho *rAU) *fvc::ddtCorr(U, Uf))
MRF makeRelative (phiHbyA)
if (p_rgh.needReference())
surfaceScalarField phig ((mixture.surfaceTensionForce() - ghf *fvc::snGrad(rho)) *rAUf *mesh.magSf())
constrainPressure (p_rgh, U, phiHbyA, rAUf)
while (pimple.correctNonOrthogonal())
surfaceVectorField n (mesh.Sf()/mesh.magSf())
Variables
phiHbyA = phig
Uf = n*(phi/mesh.magSf() - (n & Uf))
p == p_rgh + rho*gh
Function Documentation
rAUf()
surfaceScalarField rAUf ("rAUf" , fvc::interpolate(rAU))
HbyA()
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p_rgh))
phiHbyA()
surfaceScalarField phiHbyA ("phiHbyA" , fvc::flux(HbyA)+fvc::interpolate(rho *rAU) *fvc::ddtCorr(U, Uf))
makeRelative()
MRF makeRelative (phiHbyA)
if()
if (p_rgh. needReference())
Definition at line 13 of file pEqn.H.
References adjustPhi(), ghf, Foam::fvc::makeAbsolute(), makeRelative(), mesh, mixture, p_rgh, phig(), phiHbyA, rAUf(), rho, Foam::fvc::snGrad(), and U.
phig()
surfaceScalarField phig ((mixture.surfaceTensionForce() - ghf *fvc::snGrad(rho)) *rAUf *mesh.magSf())
constrainPressure()
constrainPressure (p_rgh , U , phiHbyA , rAUf)
while()
while (pimple. correctNonOrthogonal())
Definition at line 33 of file pEqn.H.
References Foam::fvc::div(), fvOptions, Foam::getRefCellValue(), HbyA, Foam::MULES::interpolate(), Foam::fvc::laplacian(), mesh, n(), p_rgh, phi, phig(), phiHbyA, pimple, pRefCell, rAUf(), Foam::fvc::reconstruct(), U, and Uf.
n()
surfaceVectorField n (mesh. Sf)/mesh.magSf()
Variable Documentation
phiHbyA
phiHbyA = phig
Definition at line 28 of file pEqn.H.
Uf
Uf = n*(phi/mesh.magSf() - (n & Uf))
Definition at line 61 of file pEqn.H.
p
p == p_rgh + rho*gh
Definition at line 67 of file pEqn.H.