OpenFOAM: applications/solvers/multiphase/reactingEulerFoam/reactingMultiphaseEulerFoam/pU/pEqn.H File Reference
pEqn.H File Reference
Functions
PtrList< surfaceScalarField > alphafs (phases.size())
PtrList< volScalarField > rAUs (phases.size())
PtrList< surfaceScalarField > alpharAUfs (phases.size())
forAll (phases, phasei)
PtrList< surfaceScalarField > phiFs (phases.size())
while (pimple.correct())
Function Documentation
alphafs()
PtrList<surfaceScalarField> alphafs (phases. size())
Referenced by forAll(), forAllIter(), and while().
rAUs()
PtrList<volScalarField> rAUs (phases. size())
alpharAUfs()
PtrList<surfaceScalarField> alpharAUfs (phases. size())
Referenced by forAll(), and while().
forAll()
forAll (phases , phasei)
Definition at line 5 of file pEqn.H.
References Foam::constant::atomic::alpha, alphafs(), alpharAUfs(), fluid, Foam::fvc::flux(), Foam::MULES::interpolate(), Foam::max(), Foam::name(), phasei, phases, phiFs(), rAUs(), and UEqns().
Referenced by if(), and while().
phiFs()
PtrList<surfaceScalarField> phiFs (phases. size())
Referenced by forAll(), and while().
while()
while (pimple. correct())
Definition at line 90 of file pEqn.H.
References Foam::constant::atomic::alpha, alphafs(), alpharAUfs(), Foam::fvc::average(), Foam::correction(), Foam::fvc::ddt(), Foam::deleteDemandDrivenData(), Foam::dimArea, Foam::dimVelocity, Foam::fvc::div(), fluid, Foam::fvc::flux(), forAll(), forAllConstIter(), fvOptions, g, gh, ghf, ghSnGradRho(), HbyAs(), Foam::MULES::interpolate(), K, Foam::fvc::laplacian(), Foam::mag(), Foam::max(), mesh, MRF, oldTime(), p, p_rgh, p_rgh_0(), patchi, phase1, phase2, phasei, phases, phi, phib, phid(), phiFs(), phiHbyA, phiHbyAs(), pimple, pMin(), Foam::pos(), rAUf(), rAUs(), Foam::fvc::reconstruct(), rho, setSnGrad< fixedFluxPressureFvPatchScalarField >(), Foam::fvc::snGrad(), solve(), Foam::fvc::Sp(), Foam::fvc::Su(), Foam::Swap(), and UEqns().