OpenFOAM: applications/solvers/multiphase/compressibleMultiphaseInterFoam/pEqn.H File Reference
pEqn.H File Reference
Functions
surfaceScalarField rAUf ("rAUf", fvc::interpolate(rAU))
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p_rgh))
surfaceScalarField phiHbyA ("phiHbyA", fvc::flux(HbyA)+fvc::interpolate(rho *rAU) *fvc::ddtCorr(U, phi))
surfaceScalarField phig ((mixture.surfaceTensionForce() - ghf *fvc::snGrad(rho)) *rAUf *mesh.magSf())
constrainPressure (p_rgh, U, phiHbyA, rAUf)
PtrList< fvScalarMatrix > p_rghEqnComps (mixture.phases().size())
forAllConstIter (PtrDictionary< phaseModel >, mixture.phases(), phase)
volScalarField p_rgh_0 (p_rgh)
while (pimple.correctNonOrthogonal())
mixture correctRho (p_rgh - p_rgh_0)
p_rgh correctBoundaryConditions ()
Variables
phiHbyA = phig
label phasei = 0
p = max(p_rgh + mixture.rho()*gh, pMin)
rho = mixture.rho()
p_rgh = p - rho*gh
K = 0.5*magSqr(U)
Function Documentation
rAUf()
surfaceScalarField rAUf ("rAUf" , fvc::interpolate(rAU))
HbyA()
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p_rgh))
phiHbyA()
surfaceScalarField phiHbyA ("phiHbyA" , fvc::flux(HbyA)+fvc::interpolate(rho *rAU) *fvc::ddtCorr(U, phi))
phig()
surfaceScalarField phig ((mixture.surfaceTensionForce() - ghf *fvc::snGrad(rho)) *rAUf *mesh.magSf())
constrainPressure()
constrainPressure (p_rgh , U , phiHbyA , rAUf)
p_rghEqnComps()
PtrList<fvScalarMatrix> p_rghEqnComps (mixture. phases).size()
Referenced by forAllConstIter(), and while().
forAllConstIter()
forAllConstIter (PtrDictionary< phaseModel > , mixture. phases(), phase)
Definition at line 29 of file pEqn.H.
References Foam::correction(), Foam::fvc::ddt(), Foam::fvc::div(), p_rgh, p_rgh_0(), p_rghEqnComps(), phi, rho, Foam::fvc::Sp(), and thermo.
Referenced by greyMeanAbsorptionEmission::aCont(), singleProcessorFaceSetsConstraint::add(), sixDoFRigidBodyMotion::addConstraints(), sixDoFRigidBodyMotion::addRestraints(), topoSet::addSet(), KinematicCloud< Cloud< basicKinematicCollidingParcel > >::alpha(), boundaryRegion::append(), cellTable::append(), setToPointZone::applyToSet(), setToCellZone::applyToSet(), setToFaceZone::applyToSet(), normalToFace::applyToSet(), setAndNormalToFaceZone::applyToSet(), setsToFaceZone::applyToSet(), distribution::approxTotalEntries(), boundaryRegion::boundaryTypes(), nearWallFields::calcAddressing(), cellToFaceStencil::calcFaceStencil(), forces::calcForcesMoment(), cellMatcher::calcLocalFaces(), wallShearStress::calcShearStress(), GAMGAgglomeration::calculateRegionMaster(), primitiveMesh::cellEdges(), primitiveMesh::cellPoints(), topoSet::check(), argList::check(), primitiveMesh::checkCommonOrder(), primitiveMesh::checkDuplicateFaces(), edgeCollapser::checkMeshQuality(), coalCloudList::coalCloudList(), cellTable::combine(), hexRef8::consistentSlowRefinement(), inverseFaceDistanceDiffusivity::correct(), inversePointDistanceDiffusivity::correct(), patchPatchDist::correct(), pointPatchDist::correct(), advectionDiffusion::correct(), nearWallFields::createFields(), meshRefinement::createZoneBaffles(), simpleControl::criteriaSatisfied(), pimpleControl::criteriaSatisfied(), structuredDecomp::decompose(), decompositionMethod::decompositionMethod(), topoSet::deleteSet(), dictionary::digest(), KinematicCloud< Cloud< basicKinematicCollidingParcel > >::Dij(), fvMeshDistribute::distribute(), KinematicCloud< Cloud< basicKinematicCollidingParcel > >::Dmax(), DSMCCloud< DSMCParcel< ParcelType > >::dumpParticlePositions(), edgeSurface::edgeSurface(), turbulenceFields::execute(), cellClassification::fillRegionPoints(), boundaryRegion::findIndex(), cellTable::findIndex(), coupleGroupIdentifier::findOtherPatchID(), polyMeshAdder::findSharedPoints(), forAll(), genericFvPatchField< Type >::genericFvPatchField(), genericPointPatchField< Type >::genericPointPatchField(), undoableMeshCutter::getAddedCells(), surfaceSets::getHangingCells(), combineFaces::getMergeSets(), undoableMeshCutter::getSplitFaces(), greyMeanAbsorptionEmission::greyMeanAbsorptionEmission(), greyMeanSolidAbsorptionEmission::greyMeanSolidAbsorptionEmission(), meshRefinement::growFaceCellFace(), if(), InjectionModelList< Foam::KinematicCloud< Cloud< basicKinematicCollidingParcel > > >::InjectionModelList(), injectionModelList::injectionModelList(), DSMCCloud< DSMCParcel< ParcelType > >::internalEnergyOfSystem(), surfaceInterpolate::interpolateFields(), meshToMesh::interpolationMethodAMI(), dictionary::keys(), layerParameters::layerParameters(), lduPrimitiveMesh::lduPrimitiveMesh(), DSMCCloud< DSMCParcel< ParcelType > >::linearKineticEnergyOfSystem(), KinematicCloud< Cloud< basicKinematicCollidingParcel > >::linearKineticEnergyOfSystem(), DSMCCloud< DSMCParcel< ParcelType > >::linearMomentumOfSystem(), KinematicCloud< Cloud< basicKinematicCollidingParcel > >::linearMomentumOfSystem(), IOobjectList::lookup(), objectRegistry::lookupClass(), IOobjectList::lookupClass(), Foam::MapDimensionedFields(), DSMCCloud< DSMCParcel< ParcelType > >::massInSystem(), KinematicCloud< Cloud< basicKinematicCollidingParcel > >::massInSystem(), cellTable::materialTypes(), cellToCellStencil::merge(), cellToFaceStencil::merge(), dictionary::merge(), edgeMesh::mergeEdges(), meshRefinement::mergePatchFacesUndo(), edgeMesh::mergePoints(), MGridGenGAMGAgglomeration::MGridGenGAMGAgglomeration(), objectRegistry::modified(), MRFZone::MRFZone(), multiLevelDecomp::multiLevelDecomp(), multiSolidBodyMotionFvMesh::multiSolidBodyMotionFvMesh(), objectRegistry::names(), NamedEnum< directionType, 3 >::names(), boundaryRegion::names(), IOobjectList::names(), cellTable::names(), surfaceFeatures::nearestEdges(), surfaceFeatures::nearestSamples(), cellCuts::nonAnchorPoints(), minEqOpFace::operator()(), minEqOp< labelPair >::operator()(), ListPlusEqOp< T, Size >::operator()(), mapDistribute::transformPosition::operator()(), dictionary::operator+=(), dictionary::operator<<=(), dictionary::operator=(), Foam::operator>>(), dictionary::operator|=(), Foam::parseNASCoord(), ParticleForceList< KinematicCloud< Cloud< basicKinematicCollidingParcel > > >::ParticleForceList(), patchInjection::patchInjection(), patchDistMethod::patchTypes(), SprayCloud< Foam::DSMCCloud >::penetration(), phaseProperties::phaseProperties(), probes::prepare(), fvMeshDistribute::printFieldInfo(), argList::printNotes(), argList::printUsage(), solutionControl::read(), NASsurfaceFormat< Face >::read(), FixedValueConstraint< Type >::read(), multiMotion::read(), wallHeatFlux::read(), wallShearStress::read(), functionObjectList::read(), turbulenceFields::read(), wallBoundedStreamLine::read(), forces::read(), Time::readDict(), GeometricField< Type, PatchField, GeoMesh >::Boundary::readField(), Foam::readFields(), ReactionList< Foam::sutherlandTransport >::readReactionDict(), Foam::readUniformFields(), pointFieldReconstructor::reconstructFields(), fvFieldReconstructor::reconstructFvSurfaceFields(), fvFieldReconstructor::reconstructFvVolumeFields(), fvFieldReconstructor::reconstructFvVolumeInternalFields(), Foam::reconstructLagrangianFieldFields(), Foam::reconstructLagrangianFields(), Foam::reconstructLagrangianPositions(), dynamicRefineFvMesh::refine(), refinementSurfaces::refinementSurfaces(), boundaryRegion::rename(), zoltanRenumber::renumber(), structuredRenumber::renumber(), porosityModelList::reset(), MRFZoneList::reset(), optionList::reset(), faceAreaWeightAMI< SourcePatch, TargetPatch >::restartUncoveredSourceFace(), KinematicCloud< Cloud< basicKinematicCollidingParcel > >::rhoEff(), rigidBodyMeshMotion::rigidBodyMeshMotion(), rigidBodyMeshMotionSolver::rigidBodyMeshMotionSolver(), rigidBodyModel::rigidBodyModel(), CollidingCloud< KinematicCloud< Cloud< basicKinematicCollidingParcel > > >::rotationalKineticEnergyOfSystem(), nearWallFields::sampleBoundaryField(), motionSmootherAlgo::scaleMesh(), searchableSurfaceCollection::searchableSurfaceCollection(), searchableSurfaces::searchableSurfaces(), cellTable::selectType(), SemiImplicitSource< Type >::setFieldData(), hexRef8::setInstance(), fvMeshSubset::setLargeCellSubset(), duplicatePoints::setRefinement(), refinementIterator::setRefinement(), perfectInterface::setRefinement(), faceCollapser::setRefinement(), boundaryCutter::setRefinement(), removePoints::setRefinement(), undoableMeshCutter::setRefinement(), removeFaces::setRefinement(), meshCutAndRemove::setRefinement(), meshCutter::setRefinement(), edgeCollapser::setRefinement(), displacementLayeredMotionMotionSolver::solve(), rigidBodyMeshMotionSolver::solve(), topoSet::subset(), dictionary::substituteKeyword(), dictionary::substituteScopedKeyword(), surfaceIntersection::surfaceIntersection(), faceSet::sync(), pointSet::sync(), syncTools::syncEdgeMap(), syncTools::syncPointMap(), KinematicCloud< Cloud< basicKinematicCollidingParcel > >::theta(), ThermoCloud< Foam::DSMCCloud >::Tmax(), ThermoCloud< Foam::DSMCCloud >::Tmin(), dictionary::toc(), distribution::totalEntries(), globalIndexAndTransform::transformIndicesForPatches(), triSurfaceTools::triangulate(), triSurfaceTools::triangulateFaceCentre(), Foam::unitSet(), Foam::UnMapped(), dynamicRefineFvMesh::unrefine(), MPPICParcel< ParcelType >::TrackingData< CloudType >::updateAverages(), uniformInterpolatedDisplacementPointPatchVectorField::updateCoeffs(), topoSet::updateLabels(), edgeVertex::updateLabels(), boundaryCutter::updateMesh(), localPointRegion::updateMesh(), meshCutAndRemove::updateMesh(), meshCutter::updateMesh(), hexRef8::updateMesh(), USERD_get_part_coords(), USERD_get_part_node_ids(), KinematicCloud< Cloud< basicKinematicCollidingParcel > >::vDotSweep(), meshReader::warnDuplicates(), while(), wideBandAbsorptionEmission::wideBandAbsorptionEmission(), gnuplotGraph::write(), jplotGraph::write(), xmgrGraph::write(), ReactionList< Foam::sutherlandTransport >::write(), genericPointPatchField< Type >::write(), genericPolyPatch::write(), wallHeatFlux::write(), genericFvPatchField< Type >::write(), wallShearStress::write(), turbulenceFields::write(), regionSizeDistribution::write(), dictionary::write(), IOPosition< CloudType >::writeData(), wallBoundedStreamLineParticle::writeFields(), solidParticle::writeFields(), MPPICParcel< ParcelType >::writeFields(), streamLineParticle::writeFields(), CollidingParcel< ParcelType >::writeFields(), DSMCParcel< ParcelType >::writeFields(), wallBoundedParticle::writeFields(), molecule::writeFields(), ReactingParcel< ParcelType >::writeFields(), ReactingMultiphaseParcel< ParcelType >::writeFields(), ThermoParcel< ParcelType >::writeFields(), SprayParcel< ParcelType >::writeFields(), particle< Type >::writeFields(), KinematicParcel< ParcelType >::writeFields(), objectRegistry::writeObject(), Cloud< streamLineParticle >::writePositions(), graph::writeTable(), moleculeCloud::writeXYZ(), and greyMeanSolidAbsorptionEmission::~greyMeanSolidAbsorptionEmission().
p_rgh_0()
volScalarField p_rgh_0 (p_rgh)
while()
while (pimple. correctNonOrthogonal())
Definition at line 53 of file pEqn.H.
References Foam::fvc::div(), forAllConstIter(), forAllIter(), HbyA, Foam::fvc::laplacian(), Foam::max(), mesh, mixture, p_rgh, p_rghEqnComps(), phasei, phi, phig(), phiHbyA, pimple, Foam::pos(), rAUf(), Foam::fvc::reconstruct(), rho, solve(), thermo, and U.
correctRho()
mixture correctRho (p_rgh - p_rgh_0)
correctBoundaryConditions()
p_rgh correctBoundaryConditions ()
Variable Documentation
phiHbyA
phiHbyA = phig
Definition at line 20 of file pEqn.H.
phasei
label phasei = 0
Definition at line 27 of file pEqn.H.
Referenced by CompositionModel< Foam::ReactingCloud< Foam::DSMCCloud > >::componentNames(), CompositionModel< Foam::ReactingCloud< Foam::DSMCCloud > >::Cp(), for(), forAll(), forAllIter(), CompositionModel< Foam::ReactingCloud< Foam::DSMCCloud > >::H(), CompositionModel< Foam::ReactingCloud< Foam::DSMCCloud > >::Hc(), CompositionModel< Foam::ReactingCloud< Foam::DSMCCloud > >::Hs(), if(), CompositionModel< Foam::ReactingCloud< Foam::DSMCCloud > >::L(), Foam::MULES::limitSum(), CompositionModel< Foam::ReactingCloud< Foam::DSMCCloud > >::localId(), CompositionModel< Foam::ReactingCloud< Foam::DSMCCloud > >::localToCarrierId(), while(), CompositionModel< Foam::ReactingCloud< Foam::DSMCCloud > >::X(), and CompositionModel< Foam::ReactingCloud< Foam::DSMCCloud > >::Y0().
p
p = max(p_rgh + mixture.rho()*gh, pMin)
Definition at line 119 of file pEqn.H.
rho
rho = mixture.rho()
Definition at line 123 of file pEqn.H.
p_rgh
p_rgh = p - rho*gh
Definition at line 126 of file pEqn.H.
K
K = 0.5*magSqr(U)
Definition at line 129 of file pEqn.H.