OpenFOAM: applications/solvers/multiphase/cavitatingFoam/pEqn.H File Reference
pEqn.H File Reference
Functions
volScalarField rAU (1.0/UEqn.A())
surfaceScalarField rhorAUf ("rhorAUf", fvc::interpolate(rho *rAU))
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p))
surfaceScalarField phiGradp (rhorAUf *mesh.magSf() *fvc::snGrad(p))
while (pimple.correctNonOrthogonal())
p correctBoundaryConditions ()
Variables
phi
Info<< "Predicted p max-min : "<< max(p).value()<< " "<< min(p).value()<< endl;rho==max(psi *p+alphal *rhol0+((alphav *psiv+alphal *psil) - psi) *pSat, rhoMin);# 1 "/home/dm2/henry/OpenFOAM/OpenFOAM-dev/applications/solvers/multiphase/cavitatingFoam/alphavPsi.H" 1{ alphav=max(min((rho - rholSat)/(rhovSat - rholSat), scalar(1)), scalar(0));alphal=1.0 - alphav;Info<< "max-min alphav: "<< max(alphav).value()<< " "<< min(alphav).value()<< endl;psiModel-> correct ()
p
Function Documentation
rAU()
volScalarField rAU (1.0/UEqn. A())
rhorAUf()
surfaceScalarField rhorAUf ("rhorAUf" , fvc::interpolate(rho *rAU))
HbyA()
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p))
phiGradp()
surfaceScalarField phiGradp (rhorAUf *mesh. magSf) *fvc::snGrad(p)
while()
while (pimple. correctNonOrthogonal())
Definition at line 25 of file pEqn.H.
References alphal, Foam::fvc::ddt(), Foam::fvc::div(), Foam::endl(), Foam::Info, Foam::fvc::laplacian(), Foam::max(), mesh, Foam::min(), p, phiGradp(), pimple, psi, rho, rhof(), rhoMin(), and rhorAUf().
correctBoundaryConditions()
p correctBoundaryConditions ()
Variable Documentation
phi
phi
Initial value:
= fvc::flux(HbyA)
         + rhorAUf*fvc::ddtCorr(U, phi)
Definition at line 18 of file pEqn.H.
correct
radiation correct ()
Definition at line 72 of file pEqn.H.
Referenced by porosityModel::addResistance(), interRegionHeatTransferModel::addSup(), Chung::Chung(), motionDirectionalDiffusivity::correct(), Foam::MULES::correct(), PaSR< Type >::correct(), linearViscousStress< RASModel< BasicTurbulenceModel > >::correct(), eddyViscosity< RASModel< BasicTurbulenceModel > >::correct(), ReynoldsStress< RASModel< BasicTurbulenceModel > >::correct(), DeardorffDiffStress< BasicTurbulenceModel >::correct(), Poisson::correct(), laminarModel< BasicTurbulenceModel >::correct(), SSG< BasicTurbulenceModel >::correct(), SpalartAllmaras< BasicTurbulenceModel >::correct(), kEpsilon< EddyDiffusivity< compressible::turbulenceModel > >::correct(), kOmega< BasicTurbulenceModel >::correct(), LaunderSharmaKE< BasicTurbulenceModel >::correct(), RNGkEpsilon< BasicTurbulenceModel >::correct(), realizableKE< BasicTurbulenceModel >::correct(), LRR< BasicTurbulenceModel >::correct(), LESModel< BasicTurbulenceModel >::correct(), RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > >::correct(), advectionDiffusion::correct(), mixtureKEpsilon< BasicTurbulenceModel >::correct(), v2f< BasicTurbulenceModel >::correct(), kOmegaSST< LESeddyViscosity< BasicTurbulenceModel >, BasicTurbulenceModel >::correct(), directionalDiffusivity::directionalDiffusivity(), for(), if(), inverseDistanceDiffusivity::inverseDistanceDiffusivity(), inverseFaceDistanceDiffusivity::inverseFaceDistanceDiffusivity(), inversePointDistanceDiffusivity::inversePointDistanceDiffusivity(), inverseVolumeDiffusivity::inverseVolumeDiffusivity(), linear::linear(), meshStructure::meshStructure(), sampledSets::movePoints(), patchDataWave< TransferType >::patchDataWave(), patchPatchDist::patchPatchDist(), pointPatchDist::pointPatchDist(), primitiveMeshGeometry::primitiveMeshGeometry(), sampledSets::readUpdate(), TDACChemistryModel< CompType, ThermoType >::solve(), chemistryModel< CompType, ThermoType >::solve(), sampledSets::updateMesh(), wallDistData< TransferType >::wallDistData(), Wallis::Wallis(), and optionList::~optionList().
p
p
Initial value:
=
    (
        rho
      - alphal*rhol0
      - ((alphav*psiv + alphal*psil) - psi)*pSat
    )/psi
Definition at line 57 of file pEqn.H.