OpenFOAM: applications/solvers/multiphase/multiphaseEulerFoam/pEqn.H File Reference
pEqn.H File Reference
Functions
PtrList< volVectorField > HbyAs (fluid.phases().size())
PtrList< surfaceScalarField > phiHbyAs (fluid.phases().size())
PtrList< volScalarField > rAUs (fluid.phases().size())
PtrList< surfaceScalarField > rAlphaAUfs (fluid.phases().size())
forAllIter (PtrDictionary< phaseModel >, fluid.phases(), iter)
surfaceScalarField phiHbyA (IOobject("phiHbyA", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh, dimensionedScalar("phiHbyA", dimArea *dimVelocity, 0))
volScalarField rho ("rho", fluid.rho())
surfaceScalarField ghSnGradRho (ghf *fvc::snGrad(rho) *mesh.magSf())
surfaceScalarField rAUf (IOobject("rAUf", runTime.timeName(), mesh), mesh, dimensionedScalar("rAUf", dimensionSet(-1, 3, 1, 0, 0), 0))
setSnGrad< fixedFluxPressureFvPatchScalarField > (p_rgh.boundaryFieldRef(),(phiHbyA.boundaryField() - MRF.relative(phib))/(mesh.magSf().boundaryField() *rAUf.boundaryField()))
while (pimple.correctNonOrthogonal())
Variables
phasei = 0
phib = 0
Function Documentation
HbyAs()
PtrList<volVectorField> HbyAs (fluid. phases).size()
Referenced by forAllIter(), and while().
phiHbyAs()
PtrList<surfaceScalarField> phiHbyAs (fluid. phases).size()
Referenced by forAllIter(), and while().
rAUs()
PtrList<volScalarField> rAUs (fluid. phases).size()
Referenced by forAll(), forAllIter(), MomentumTransferPhaseSystem< BasePhaseSystem >::Kds(), and while().
rAlphaAUfs()
PtrList<surfaceScalarField> rAlphaAUfs (fluid. phases).size()
Referenced by forAllIter(), and while().
forAllIter()
forAllIter (PtrDictionary< phaseModel > , fluid. phases(), iter)
Definition at line 34 of file pEqn.H.
References Foam::constant::atomic::alpha, alphafs(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), Foam::fvc::ddtCorr(), Foam::dimArea, Foam::dimVelocity, dragCoeffs(), fluid, Foam::fvc::flux(), g, ghf, ghSnGradRho(), HbyAs(), Foam::MULES::interpolate(), Foam::mag(), mesh, MRF, phase2, phasei, phi, phib, phiHbyA, phiHbyAs(), rAlphaAUfs(), rAUf(), rAUs(), rho, Foam::fvc::snGrad(), and UEqns().
Referenced by while().
phiHbyA()
surfaceScalarField phiHbyA (IOobject("phiHbyA", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE) , mesh , dimensionedScalar("phiHbyA", dimArea *dimVelocity, 0))
rho()
volScalarField rho ("rho" , fluid. rho())
ghSnGradRho()
surfaceScalarField ghSnGradRho (ghf * fvc::snGradrho) *mesh.magSf()
Referenced by forAllIter(), and while().
rAUf()
surfaceScalarField rAUf (IOobject("rAUf", runTime.timeName(), mesh) , mesh , dimensionedScalar("rAUf", dimensionSet(-1, 3, 1, 0, 0), 0))
setSnGrad< fixedFluxPressureFvPatchScalarField >()
setSnGrad< fixedFluxPressureFvPatchScalarField > (p_rgh. boundaryFieldRef(), (phiHbyA.boundaryField() - MRF.relative(phib))/(mesh.magSf().boundaryField() *rAUf.boundaryField()))
Referenced by while().
while()
while (pimple. correctNonOrthogonal())
Definition at line 213 of file pEqn.H.
References Foam::constant::atomic::alpha, alphafs(), Foam::fvc::div(), fluid, forAllIter(), g, gh, ghSnGradRho(), HbyAs(), Foam::MULES::interpolate(), Foam::fvc::laplacian(), Foam::mag(), mesh, p, p_rgh, phasei, phi, phiHbyA, phiHbyAs(), pimple, pRefCell, pRefValue, rAlphaAUfs(), rAUf(), Foam::fvc::reconstruct(), rho, solve(), U, and Foam::Zero.
Variable Documentation
phasei
phasei = 0
Definition at line 33 of file pEqn.H.
phib
phib = 0
Definition at line 191 of file pEqn.H.
Referenced by forAllIter(), and while().