OpenFOAM: applications/solvers/multiphase/potentialFreeSurfaceFoam/potentialFreeSurfaceDyMFoam/pEqn.H File Reference
pEqn.H File Reference
Functions
surfaceScalarField rAUf ("rAUf", fvc::interpolate(rAU))
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p_gh))
if (pimple.nCorrPISO()<=1)
surfaceScalarField phiHbyA ("phiHbyA", fvc::flux(HbyA)+rAUf *fvc::ddtCorr(U, Uf))
MRF makeRelative (phiHbyA)
if (p_gh.needReference())
constrainPressure (p_gh, U, phiHbyA, rAUf)
while (pimple.correctNonOrthogonal())
surfaceVectorField n (mesh.Sf()/mesh.magSf())
Variables
Uf = n*(phi/mesh.magSf() - (n & Uf))
p = p_gh + (g & mesh.C())
Function Documentation
rAUf()
surfaceScalarField rAUf ("rAUf" , fvc::interpolate(rAU))
HbyA()
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p_gh))
if() [1/2]
if (pimple.nCorrPISO()<= 1)
Definition at line 6 of file pEqn.H.
References Foam::fvc::ddtCorr(), Foam::fvc::flux(), HbyA, MRF, phiHbyA, rAUf(), tUEqn(), U, and Uf.
phiHbyA()
surfaceScalarField phiHbyA ("phiHbyA" , fvc::flux(HbyA)+rAUf *fvc::ddtCorr(U, Uf))
makeRelative()
MRF makeRelative (phiHbyA)
if() [2/2]
if (p_gh. needReference())
Definition at line 20 of file pEqn.H.
References adjustPhi(), constrainPressure(), Foam::fvc::makeAbsolute(), makeRelative(), rAUf(), and U.
constrainPressure()
constrainPressure (p_gh , U , phiHbyA , rAUf)
while()
while (pimple. correctNonOrthogonal())
Definition at line 31 of file pEqn.H.
References Foam::fvc::div(), fvOptions, Foam::fvc::grad(), HbyA, Foam::MULES::interpolate(), Foam::fvc::laplacian(), mesh, n(), phi, pimple, rAU(), rAUf(), U, and Uf.
n()
surfaceVectorField n (mesh. Sf)/mesh.magSf()
Variable Documentation
Uf
Uf = n*(phi/mesh.magSf() - (n & Uf))
Definition at line 60 of file pEqn.H.
p
p = p_gh + (g & mesh.C())
Definition at line 66 of file pEqn.H.