OpenFOAM: applications/solvers/incompressible/simpleFoam/porousSimpleFoam/UEqn.H File Reference
UEqn.H File Reference
Functions
MRF correctBoundaryVelocity (U)
tmp< fvVectorMatrix > tUEqn (fvm::div(phi, U)+MRF.DDt(U)+turbulence->divDevReff(U)==fvOptions(U))
UEqn relax ()
if (pressureImplicitPorosity)
fvOptions constrain (UEqn)
solve (UEqn==-fvc::grad(p))
fvOptions correct (U)
trAU ref ().rename("rAU")
Variables
fvVectorMatrix & UEqn = tUEqn.ref()
tmp< volScalarField > trAU = 1.0/UEqn.A()
tmp< volTensorField > trTU
else
Function Documentation
correctBoundaryVelocity()
MRF correctBoundaryVelocity (U)
tUEqn()
tmp<fvVectorMatrix> tUEqn (fvm::div(phi, U)+MRF.DDt(U)+turbulence->divDevReff(U) = =fvOptions(U))
relax()
UEqn relax ()
if()
if (pressureImplicitPorosity)
Definition at line 24 of file UEqn.H.
References fvOptions, Foam::fvc::grad(), Foam::I, Foam::inv(), nUCorr, p, pZones(), trTU, and U.
constrain()
fvOptions constrain (UEqn)
solve()
solve (UEqn = =-fvc::grad(p))
correct()
fvOptions correct (U)
ref()
trAU ref ()
Variable Documentation
UEqn
fvVectorMatrix& UEqn = tUEqn.ref()
Definition at line 13 of file UEqn.H.
trAU
trAU = 1.0/UEqn.A()
Definition at line 21 of file UEqn.H.
trTU
tmp<volTensorField> trTU
Definition at line 22 of file UEqn.H.
else
else
Initial value:
{
        pZones.addResistance(UEqn)
Definition at line 44 of file UEqn.H.