OpenFOAM: applications/solvers/multiphase/cavitatingFoam/UEqn.H File Reference
UEqn.H File Reference
Functions
fvVectorMatrix UEqn (fvm::ddt(rho, U)+fvm::div(rhoPhi, U)+turbulence->divDevRhoReff(rho, U))
UEqn relax ()
if (pimple.momentumPredictor())
Function Documentation
UEqn()
fvVectorMatrix UEqn (fvm::ddt(rho, U)+fvm::div(rhoPhi, U)+turbulence->divDevRhoReff(rho, U))
relax()
UEqn relax ()
if()
if (pimple. momentumPredictor())
Definition at line 10 of file UEqn.H.
References Foam::endl(), Foam::fvc::grad(), Foam::Info, Foam::mag(), Foam::max(), p, solve(), U, and UEqn.