OpenFOAM: applications/solvers/heatTransfer/buoyantPimpleFoam/UEqn.H File Reference
UEqn.H File Reference
Functions
MRF correctBoundaryVelocity (U)
fvVectorMatrix UEqn (fvm::ddt(rho, U)+fvm::div(phi, U)+MRF.DDt(rho, U)+turbulence->divDevRhoReff(U)==fvOptions(rho, U))
UEqn relax ()
fvOptions constrain (UEqn)
if (pimple.momentumPredictor())
Function Documentation
correctBoundaryVelocity()
MRF correctBoundaryVelocity (U)
UEqn()
fvVectorMatrix UEqn (fvm::ddt(rho, U)+fvm::div(phi, U)+MRF.DDt(rho, U)+turbulence->divDevRhoReff(U) = =fvOptions(rho, U))
relax()
UEqn relax ()
constrain()
fvOptions constrain (UEqn)
if()
if (pimple. momentumPredictor())
Definition at line 18 of file UEqn.H.
References fvOptions, ghf, Foam::magSqr(), mesh, p_rgh, Foam::fvc::reconstruct(), rho, Foam::fvc::snGrad(), solve(), U, and UEqn.