OpenFOAM: applications/solvers/combustion/XiFoam/EauEqn.H File Reference
EauEqn.H File Reference
Functions
if (ign.ignited())
Function Documentation
if()
if (ign. ignited())
fvm::div(muEff*fvc::grad(b)/(b + 0.001), heau)
+ fvm::Sp(fvc::div(muEff*fvc::grad(b)/(b + 0.001)), heau)
Definition at line 1 of file EauEqn.H.
References Foam::fvc::absolute(), Foam::fvc::ddt(), Foam::fvc::div(), dpdt, fvOptions, Foam::MULES::interpolate(), Foam::fvc::laplacian(), mvConvection(), p, phi, rho, thermo, turbulence, and U.