OpenFOAM: applications/solvers/heatTransfer/chtMultiRegionFoam/solid/solidRegionDiffusionNo.H File Reference
solidRegionDiffusionNo.H File Reference
Functions
forAll (solidRegions, i)
Variables
scalar DiNum = -GREAT
Function Documentation
forAll()
forAll (solidRegions , i)
Note: do not use setRegionSolidFields.H to avoid double registering Cp
#include "setRegionSolidFields.H"
Definition at line 3 of file solidRegionDiffusionNo.H.
References cp, DiNum, Foam::mag(), Foam::max(), rho, Foam::solidRegionDiffNo(), solidRegions(), tcp, thermo, thermos(), and trho.
Variable Documentation
DiNum
scalar DiNum = -GREAT
Definition at line 1 of file solidRegionDiffusionNo.H.