OpenFOAM: applications/solvers/multiphase/cavitatingFoam/cavitatingDyMFoam/correctPhi.H File Reference
correctPhi.H File Reference
Functions
correctUphiBCs (U, phi)
surfaceScalarField rhof (fvc::interpolate(rho, "div(phi,rho)"))
dimensionedScalar rAUf ("rAUf", dimTime, 1.0)
mesh setFluxRequired (pcorr.name())
while (pimple.correctNonOrthogonal())
Function Documentation
correctUphiBCs()
correctUphiBCs (U , phi)
Referenced by Foam::CorrectPhi().
rhof()
surfaceScalarField rhof (fvc::interpolate(rho, "div(phi,rho)"))
Referenced by if(), kinematicSingleLayer::solveThickness(), and while().
rAUf()
dimensionedScalar rAUf ("rAUf" , dimTime , 1. 0)
Referenced by while().
setFluxRequired()
mesh setFluxRequired (pcorr. name())
while()
while (pimple. correctNonOrthogonal())
Definition at line 24 of file correctPhi.H.
References Foam::fvc::ddt(), Foam::fvc::div(), Foam::fvc::laplacian(), phi, pimple, rAUf(), rho, and rhof().