OpenFOAM: applications/solvers/multiphase/interFoam/setRDeltaT.H File Reference
setRDeltaT.H File Reference
Functions
scalar maxCo (pimpleDict.lookupOrDefault< scalar >("maxCo", 0.9))
scalar maxAlphaCo (pimpleDict.lookupOrDefault< scalar >("maxAlphaCo", 0.2))
scalar rDeltaTSmoothingCoeff (pimpleDict.lookupOrDefault< scalar >("rDeltaTSmoothingCoeff", 0.1))
label nAlphaSpreadIter (pimpleDict.lookupOrDefault< label >("nAlphaSpreadIter", 1))
scalar alphaSpreadDiff (pimpleDict.lookupOrDefault< scalar >("alphaSpreadDiff", 0.2))
scalar alphaSpreadMax (pimpleDict.lookupOrDefault< scalar >("alphaSpreadMax", 0.99))
scalar alphaSpreadMin (pimpleDict.lookupOrDefault< scalar >("alphaSpreadMin", 0.01))
label nAlphaSweepIter (pimpleDict.lookupOrDefault< label >("nAlphaSweepIter", 5))
scalar rDeltaTDampingCoeff (pimpleDict.lookupOrDefault< scalar >("rDeltaTDampingCoeff", 1.0))
scalar maxDeltaT (pimpleDict.lookupOrDefault< scalar >("maxDeltaT", GREAT))
volScalarField rDeltaT0 ("rDeltaT0", rDeltaT)
rDeltaT ref ()
if (maxAlphaCo< maxCo)
rDeltaT correctBoundaryConditions ()
Variables
const dictionary & pimpleDict = pimple.dict()
Function Documentation
maxCo()
scalar maxCo (pimpleDict.lookupOrDefault< scalar > "maxCo", 0.9)
maxAlphaCo()
scalar maxAlphaCo (pimpleDict.lookupOrDefault< scalar > "maxAlphaCo", 0.2)
Referenced by if().
rDeltaTSmoothingCoeff()
scalar rDeltaTSmoothingCoeff (pimpleDict.lookupOrDefault< scalar > "rDeltaTSmoothingCoeff", 0.1)
nAlphaSpreadIter()
label nAlphaSpreadIter (pimpleDict.lookupOrDefault< label > "nAlphaSpreadIter", 1)
Referenced by if().
alphaSpreadDiff()
scalar alphaSpreadDiff (pimpleDict.lookupOrDefault< scalar > "alphaSpreadDiff", 0.2)
Referenced by if().
alphaSpreadMax()
scalar alphaSpreadMax (pimpleDict.lookupOrDefault< scalar > "alphaSpreadMax", 0.99)
Referenced by if().
alphaSpreadMin()
scalar alphaSpreadMin (pimpleDict.lookupOrDefault< scalar > "alphaSpreadMin", 0.01)
Referenced by if().
nAlphaSweepIter()
label nAlphaSweepIter (pimpleDict.lookupOrDefault< label > "nAlphaSweepIter", 5)
Referenced by if().
rDeltaTDampingCoeff()
scalar rDeltaTDampingCoeff (pimpleDict.lookupOrDefault< scalar > "rDeltaTDampingCoeff", 1.0)
maxDeltaT()
scalar maxDeltaT (pimpleDict.lookupOrDefault< scalar > "maxDeltaT", GREAT)
rDeltaT0()
volScalarField rDeltaT0 ("rDeltaT0" , rDeltaT)
ref()
rDeltaT ref ()
if()
if ()
Definition at line 66 of file setRDeltaT.H.
References alpha1, alphaSpreadDiff(), alphaSpreadMax(), alphaSpreadMin(), Foam::fvc::average(), Foam::endl(), Foam::gMax(), Foam::gMin(), Foam::Info, Foam::mag(), Foam::max(), maxAlphaCo(), mesh, nAlphaSpreadIter(), nAlphaSweepIter(), phi, Foam::pos(), rDeltaT0(), rDeltaTDampingCoeff(), rDeltaTSmoothingCoeff(), Foam::fvc::smooth(), Foam::fvc::spread(), Foam::fvc::surfaceSum(), and Foam::fvc::sweep().
correctBoundaryConditions()
rDeltaT correctBoundaryConditions ()
Variable Documentation
pimpleDict
const dictionary& pimpleDict = pimple.dict()
Definition at line 4 of file setRDeltaT.H.