OpenFOAM: applications/solvers/compressible/rhoSimpleFoam/pcEqn.H File Reference
pcEqn.H File Reference
Functions
volScalarField rAU (1.0/UEqn.A())
volScalarField rAtU (1.0/(1.0/rAU - UEqn.H1()))
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p))
tUEqn clear ()
if (simple.transonic())
MRF makeRelative (fvc::interpolate(rho), phiHbyA)
volScalarField rhorAtU ("rhorAtU", rho *rAtU)
constrainPressure (p, rho, U, phiHbyA, rhorAtU, MRF)
while (simple.correctNonOrthogonal())
p relax ()
U correctBoundaryConditions ()
fvOptions correct (U)
if (closedVolume)
if (!simple.transonic())
Variables
bool closedVolume = false
else
phiHbyA = fvc::interpolate(rho*(rAtU - rAU))*fvc::snGrad(p)*mesh.magSf()
HbyA = (rAU - rAtU)*fvc::grad(p)
U = HbyA - rAtU*fvc::grad(p)
rho = thermo.rho()
Function Documentation
rAU()
volScalarField rAU (1.0/UEqn. A())
rAtU()
volScalarField rAtU (1.0/ 1.0/rAU - UEqn.H1())
HbyA()
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p))
clear()
tUEqn clear ()
Referenced by cyclicAMIPolyPatch::calcTransforms(), cyclicPolyPatch::calcTransforms(), ILList< LListBase, T >::clear(), HashPtrTable< ThermoType >::clear(), DictionaryBase< DLPtrList< T >, T >::clear(), LPtrList< LListBase, T >::clear(), ZoneMesh< cellZone, polyMesh >::clear(), wordRe::clear(), LList< Foam::chemPointISAT< CompType, ThermoType > *>::clear(), DynamicList< Foam::Tensor >::clearStorage(), HashTable< Foam::phase *>::clearStorage(), DSMCCloud< DSMCParcel< ParcelType > >::DSMCCloud(), fieldExpression::execute(), sampledPatch::expire(), sampledTriSurfaceMesh::expire(), moleculeCloud::moleculeCloud(), HashPtrTable< ThermoType >::operator=(), UILList< LListBase, T >::operator=(), tmp< Foam::surfaceInterpolationScheme< GType > >::operator=(), LPtrList< LListBase, T >::operator=(), LList< Foam::chemPointISAT< CompType, ThermoType > *>::operator=(), Matrix< RectangularMatrix< Type >, Type >::operator=(), HashTable< Foam::phase *>::operator=(), MeshedSurface< Foam::face >::operator=(), dictionary::parent(), reactingMixture< ThermoType >::reactingMixture(), extendedEdgeMeshFormat::read(), extendedFeatureEdgeMeshFormat::read(), NASedgeFormat::read(), OBJsurfaceFormat< Face >::read(), GTSsurfaceFormat< Face >::read(), NASsurfaceFormat< Face >::read(), OFFsurfaceFormat< Face >::read(), VTKsurfaceFormat< Face >::read(), AC3DsurfaceFormat< Face >::read(), TRIsurfaceFormat< Face >::read(), STARCDsurfaceFormat< Face >::read(), edgeMeshFormat::read(), OFSsurfaceFormat< Face >::read(), STLsurfaceFormat< Face >::read(), MeshedSurface< Foam::face >::read(), GeometricField< Type, PatchField, GeoMesh >::Boundary::readField(), PtrList< MRFZone >::setSize(), UPtrList< Foam::Field< Type > >::setSize(), List< Field< scalar > >::setSize(), singleStepReactingMixture< ThermoType >::singleStepReactingMixture(), PtrList< MRFZone >::transfer(), LPtrList< LListBase, T >::transfer(), LList< Foam::chemPointISAT< CompType, ThermoType > *>::transfer(), List< Field< scalar > >::transfer(), Matrix< RectangularMatrix< Type >, Type >::transfer(), HashTable< Foam::phase *>::transfer(), MeshedSurface< Foam::face >::transfer(), autoPtr< Foam::lduMatrix::solver >::~autoPtr(), HashPtrTable< ThermoType >::~HashPtrTable(), HashTable< Foam::phase *>::~HashTable(), LList< Foam::chemPointISAT< CompType, ThermoType > *>::~LList(), LPtrList< LListBase, T >::~LPtrList(), and tmp< Foam::surfaceInterpolationScheme< GType > >::~tmp().
if() [1/3]
if (simple. transonic())
Definition at line 8 of file pcEqn.H.
References Foam::fvc::div(), Foam::fvc::flux(), fvOptions, Foam::fvc::grad(), HbyA, Foam::MULES::interpolate(), Foam::fvc::laplacian(), mesh, MRF, p, phi, phic, phid(), pRefCell, pRefValue, psi, rAtU(), rAU(), rho, rhorAtU(), simple, and Foam::fvc::snGrad().
makeRelative()
MRF makeRelative (fvc::interpolate(rho) , phiHbyA)
rhorAtU()
volScalarField rhorAtU ("rhorAtU" , rho * rAtU)
constrainPressure()
constrainPressure (p , rho , U , phiHbyA , rhorAtU , MRF)
while()
while (simple. correctNonOrthogonal())
Definition at line 68 of file pcEqn.H.
References Foam::fvc::div(), fvOptions, Foam::fvc::laplacian(), p, phi, pRefCell, pRefValue, psi, rho, rhorAtU(), and simple.
relax()
p relax ()
correctBoundaryConditions()
U correctBoundaryConditions ()
correct()
fvOptions correct (U)
if() [2/3]
if (closedVolume)
Definition at line 102 of file pcEqn.H.
References Foam::fvc::domainIntegrate(), initialMass, p, and psi.
if() [3/3]
if (!simple. transonic())
Definition at line 113 of file pcEqn.H.
References Foam::endl(), Foam::Info, Foam::max(), Foam::min(), and rho.
Variable Documentation
closedVolume
closedVolume = false
Definition at line 6 of file pcEqn.H.
else
else
Initial value:
{
    surfaceScalarField phiHbyA("phiHbyA", fvc::flux(rho*HbyA))
Definition at line 54 of file pcEqn.H.
phiHbyA
phiHbyA = fvc::interpolate(rho*(rAtU - rAU))*fvc::snGrad(p)*mesh.magSf()
Definition at line 60 of file pcEqn.H.
HbyA
HbyA = (rAU - rAtU)*fvc::grad(p)
Definition at line 61 of file pcEqn.H.
U
U = HbyA - rAtU*fvc::grad(p)
Definition at line 96 of file pcEqn.H.
rho
rho = thermo.rho()
Definition at line 109 of file pcEqn.H.