OpenFOAM: applications/solvers/compressible/rhoPimpleFoam/setRDeltaT.H File Reference
setRDeltaT.H File Reference
Functions
scalar maxCo (pimpleDict.lookupOrDefault< scalar >("maxCo", 0.8))
scalar rDeltaTSmoothingCoeff (pimpleDict.lookupOrDefault< scalar >("rDeltaTSmoothingCoeff", 0.02))
scalar rDeltaTDampingCoeff (pimpleDict.lookupOrDefault< scalar >("rDeltaTDampingCoeff", 1.0))
scalar maxDeltaT (pimpleDict.lookupOrDefault< scalar >("maxDeltaT", GREAT))
volScalarField rDeltaT0 ("rDeltaT0", rDeltaT)
rDeltaT ref ()
if (pimple.transonic())
rDeltaT correctBoundaryConditions ()
Variables
const dictionary & pimpleDict = pimple.dict()
Function Documentation
maxCo()
scalar maxCo (pimpleDict.lookupOrDefault< scalar > "maxCo", 0.8)
rDeltaTSmoothingCoeff()
scalar rDeltaTSmoothingCoeff (pimpleDict.lookupOrDefault< scalar > "rDeltaTSmoothingCoeff", 0.02)
rDeltaTDampingCoeff()
scalar rDeltaTDampingCoeff (pimpleDict.lookupOrDefault< scalar > "rDeltaTDampingCoeff", 1.0)
maxDeltaT()
scalar maxDeltaT (pimpleDict.lookupOrDefault< scalar > "maxDeltaT", GREAT)
rDeltaT0()
volScalarField rDeltaT0 ("rDeltaT0" , rDeltaT)
Referenced by if().
ref()
rDeltaT ref ()
if()
if (pimple. transonic())
Definition at line 36 of file setRDeltaT.H.
References Foam::endl(), Foam::fvc::flux(), Foam::gMax(), Foam::gMin(), Foam::Info, Foam::MULES::interpolate(), Foam::mag(), Foam::max(), maxCo(), mesh, phid(), psi, rDeltaT0(), rDeltaTDampingCoeff(), rDeltaTSmoothingCoeff(), Foam::fvc::smooth(), Foam::fvc::surfaceSum(), and U.
correctBoundaryConditions()
rDeltaT correctBoundaryConditions ()
Variable Documentation
pimpleDict
const dictionary& pimpleDict = pimple.dict()
Definition at line 4 of file setRDeltaT.H.