OpenFOAM: applications/solvers/combustion/reactingFoam/setRDeltaT.H File Reference
setRDeltaT.H File Reference
Functions
scalar maxCo (readScalar(pimpleDict.lookup("maxCo")))
scalar maxDeltaT (pimpleDict.lookupOrDefault< scalar >("maxDeltaT", GREAT))
scalar rDeltaTSmoothingCoeff (pimpleDict.lookupOrDefault< scalar >("rDeltaTSmoothingCoeff", 0.1))
scalar rDeltaTDampingCoeff (pimpleDict.lookupOrDefault< scalar >("rDeltaTDampingCoeff", 1))
scalar alphaTemp (pimpleDict.lookupOrDefault("alphaTemp", 0.05))
Variables
const dictionary & pimpleDict = pimple.dict()
Detailed Description
Original source file setRDeltaT.H
Definition in file setRDeltaT.H.
Function Documentation
maxCo()
scalar maxCo (readScalar(pimpleDict.lookup("maxCo")))
Referenced by forAll(), and if().
maxDeltaT()
scalar maxDeltaT (pimpleDict.lookupOrDefault< scalar > "maxDeltaT", GREAT)
Referenced by forAll().
rDeltaTSmoothingCoeff()
scalar rDeltaTSmoothingCoeff (pimpleDict.lookupOrDefault< scalar > "rDeltaTSmoothingCoeff", 0.1)
Referenced by forAll(), and if().
rDeltaTDampingCoeff()
scalar rDeltaTDampingCoeff (pimpleDict.lookupOrDefault< scalar > "rDeltaTDampingCoeff", 1)
Referenced by if().
alphaTemp()
scalar alphaTemp (pimpleDict. lookupOrDefault"alphaTemp", 0.05)
Variable Documentation
pimpleDict
const dictionary& pimpleDict = pimple.dict()
Definition at line 29 of file setRDeltaT.H.
Referenced by forAll(), and pimpleControl::read().