OpenFOAM: applications/solvers/multiphase/interFoam/interMixingFoam/alphaEqns.H File Reference
alphaEqns.H File Reference
Functions
word alpharScheme ("div(phirb,alpha)")
surfaceScalarField phir (IOobject("phir", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), mixture.cAlpha() *mag(phi/mesh.magSf()) *mixture.nHatf())
for (int gCorr=0;gCorr< nAlphaCorr;gCorr++)
Function Documentation
alpharScheme()
word alpharScheme ("div(phirb,alpha)")
phir()
surfaceScalarField phir (IOobject("phir", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE) , mixture. cAlpha) *mag(phi/mesh.magSf()) *mixture.nHatf()
for()
for ()
Definition at line 18 of file alphaEqns.H.
References alpha1, alpha2, alphaPhi1, alphaPhi2, alpharScheme(), Foam::fvc::ddt(), Foam::dimless, Foam::fvc::div(), Foam::endl(), Foam::fvc::flux(), Foam::Info, Foam::MULES::interpolate(), lambda(), Foam::fvc::laplacian(), Foam::MULES::limiter(), LTS, Foam::max(), mesh, Foam::min(), phi, phir(), Foam::pos(), rho1, rho2, rhoPhi, scalarField(), Foam::fvc::snGrad(), and solve().