OpenFOAM: applications/solvers/heatTransfer/chtMultiRegionFoam/fluid/createFluidFields.H File Reference
createFluidFields.H File Reference
Functions
PtrList< rhoThermo > thermoFluid (fluidRegions.size())
PtrList< volScalarField > rhoFluid (fluidRegions.size())
PtrList< volVectorField > UFluid (fluidRegions.size())
PtrList< surfaceScalarField > phiFluid (fluidRegions.size())
PtrList< uniformDimensionedVectorField > gFluid (fluidRegions.size())
PtrList< uniformDimensionedScalarField > hRefFluid (fluidRegions.size())
PtrList< volScalarField > ghFluid (fluidRegions.size())
PtrList< surfaceScalarField > ghfFluid (fluidRegions.size())
PtrList< compressible::turbulenceModel > turbulence (fluidRegions.size())
PtrList< volScalarField > p_rghFluid (fluidRegions.size())
PtrList< radiation::radiationModel > radiation (fluidRegions.size())
PtrList< volScalarField > KFluid (fluidRegions.size())
PtrList< volScalarField > dpdtFluid (fluidRegions.size())
List< scalar > initialMassFluid (fluidRegions.size())
List< bool > frozenFlowFluid (fluidRegions.size(), false)
PtrList< IOMRFZoneList > MRFfluid (fluidRegions.size())
PtrList< fv::options > fluidFvOptions (fluidRegions.size())
forAll (fluidRegions, i)
Function Documentation
thermoFluid()
PtrList<rhoThermo> thermoFluid (fluidRegions. size())
rhoFluid()
PtrList<volScalarField> rhoFluid (fluidRegions. size())
UFluid()
PtrList<volVectorField> UFluid (fluidRegions. size())
phiFluid()
PtrList<surfaceScalarField> phiFluid (fluidRegions. size())
gFluid()
PtrList<uniformDimensionedVectorField> gFluid (fluidRegions. size())
hRefFluid()
PtrList<uniformDimensionedScalarField> hRefFluid (fluidRegions. size())
ghFluid()
PtrList<volScalarField> ghFluid (fluidRegions. size())
ghfFluid()
PtrList<surfaceScalarField> ghfFluid (fluidRegions. size())
turbulence()
PtrList<compressible::turbulenceModel> turbulence (fluidRegions. size())
p_rghFluid()
PtrList<volScalarField> p_rghFluid (fluidRegions. size())
radiation()
PtrList<radiation::radiationModel> radiation (fluidRegions. size())
KFluid()
PtrList<volScalarField> KFluid (fluidRegions. size())
Referenced by forAll().
dpdtFluid()
PtrList<volScalarField> dpdtFluid (fluidRegions. size())
Referenced by forAll().
initialMassFluid()
List<scalar> initialMassFluid (fluidRegions. size())
frozenFlowFluid()
List<bool> frozenFlowFluid (fluidRegions. size(), false)
MRFfluid()
PtrList<IOMRFZoneList> MRFfluid (fluidRegions. size())
fluidFvOptions()
PtrList<fv::options> fluidFvOptions (fluidRegions. size())
forAll()
forAll (fluidRegions , i)
Definition at line 23 of file createFluidFields.H.
References C, Foam::cmptMag(), Foam::dimLength, Foam::dimTime, Foam::fvc::domainIntegrate(), dpdtFluid(), Foam::endl(), fluidFvOptions(), fluidRegions(), frozenFlowFluid(), gFluid(), ghfFluid(), ghFluid(), hRefFluid(), Foam::Info, initialMassFluid(), KFluid(), Foam::linearInterpolate(), Foam::mag(), Foam::magSqr(), MRFfluid(), Foam::name(), Foam::New(), Foam::nl, p, p_rghFluid(), phiFluid(), pimpleDict, radiation(), rho, rhoFluid(), T, thermoFluid(), turbulence(), and UFluid().