OpenFOAM: applications/solvers/multiphase/compressibleInterFoam/alphaEqnsSubCycle.H File Reference
alphaEqnsSubCycle.H File Reference
Functions
label nAlphaCorr (readLabel(alphaControls.lookup("nAlphaCorr")))
label nAlphaSubCycles (readLabel(alphaControls.lookup("nAlphaSubCycles")))
surfaceScalarField phic (mag(phi/mesh.magSf()))
volScalarField divU (fvc::div(fvc::absolute(phi, U)))
if (nAlphaSubCycles > 1)
Variables
phic = min(interface.cAlpha()*phic, max(phic))
Function Documentation
nAlphaCorr()
label nAlphaCorr (readLabel(alphaControls.lookup("nAlphaCorr")))
nAlphaSubCycles()
label nAlphaSubCycles (readLabel(alphaControls.lookup("nAlphaSubCycles")))
Referenced by if().
phic()
surfaceScalarField phic (mag(phi/mesh.magSf()))
divU()
volScalarField divU (fvc::div(fvc::absolute(phi, U)))
Referenced by kEqn< BasicTurbulenceModel >::correct(), dynamicKEqn< BasicTurbulenceModel >::correct(), kEpsilon< EddyDiffusivity< compressible::turbulenceModel > >::correct(), kOmega< BasicTurbulenceModel >::correct(), LaunderSharmaKE< BasicTurbulenceModel >::correct(), realizableKE< BasicTurbulenceModel >::correct(), RNGkEpsilon< BasicTurbulenceModel >::correct(), v2f< BasicTurbulenceModel >::correct(), kOmegaSST< LESeddyViscosity< BasicTurbulenceModel >, BasicTurbulenceModel >::correct(), for(), and if().
if()
if (nAlphaSubCycles , 1)
Definition at line 9 of file alphaEqnsSubCycle.H.
References alpha1, mesh, nAlphaSubCycles(), and rhoPhi.
Variable Documentation
phic
phic = min(interface.cAlpha()*phic, max(phic))
Definition at line 5 of file alphaEqnsSubCycle.H.
Referenced by if(), ETAB< CloudType >::update(), TAB< CloudType >::update(), and while().