OpenFOAM: applications/solvers/heatTransfer/chtMultiRegionFoam/fluid/compressibleMultiRegionCourantNo.H File Reference
compressibleMultiRegionCourantNo.H File Reference
Functions
forAll (fluidRegions, regionI)
Variables
scalar CoNum = -GREAT
Function Documentation
forAll()
forAll (fluidRegions , regionI)
Definition at line 3 of file compressibleMultiRegionCourantNo.H.
References Foam::compressibleCourantNo(), CoNum, fluidRegions(), Foam::max(), phiFluid(), and rhoFluid().
Variable Documentation
CoNum
scalar CoNum = -GREAT
Definition at line 1 of file compressibleMultiRegionCourantNo.H.