OpenFOAM: applications/solvers/multiphase/compressibleInterFoam/alphaEqns.H File Reference
alphaEqns.H File Reference
Functions
word alpharScheme ("div(phirb,alpha)")
surfaceScalarField phir (phic *interface.nHatf())
for (int gCorr=0;gCorr< nAlphaCorr;gCorr++)
Function Documentation
alpharScheme()
word alpharScheme ("div(phirb,alpha)")
Referenced by for().
phir()
surfaceScalarField phir (phic *interface. nHatf())
Referenced by for(), and while().
for()
for ()
Definition at line 7 of file alphaEqns.H.
References alpha1, alpha2, alphaPhi1, alpharScheme(), divU(), Foam::endl(), Foam::MULES::explicitSolve(), Foam::fvc::flux(), forAll, Foam::Info, Foam::MULES::interpolate(), mesh, Foam::min(), phi, phir(), rho1, rho2, rhoPhi, Foam::fvc::Sp(), and Foam::fvc::Su().