OpenFOAM: applications/solvers/multiphase/twoLiquidMixingFoam/alphaCourantNo.H File Reference
alphaCourantNo.H File Reference
Calculates and outputs the mean and maximum Courant Numbers.
Functions
scalar maxAlphaCo (readScalar(runTime.controlDict().lookup("maxAlphaCo")))
if (mesh.nInternalFaces())
Variables
scalar alphaCoNum = 0.0
scalar meanAlphaCoNum = 0.0
Detailed Description
Calculates and outputs the mean and maximum Courant Numbers.
Original source file alphaCourantNo.H
Definition in file alphaCourantNo.H.
Function Documentation
maxAlphaCo()
scalar maxAlphaCo (readScalar(runTime.controlDict().lookup("maxAlphaCo")))
if()
if (mesh. nInternalFaces())
Definition at line 37 of file alphaCourantNo.H.
References alpha1, Foam::endl(), Foam::gMax(), Foam::gSum(), Foam::Info, Foam::mag(), mesh, phi, Foam::pos(), scalarField(), and Foam::fvc::surfaceSum().
Variable Documentation
alphaCoNum
scalar alphaCoNum = 0.0
Definition at line 34 of file alphaCourantNo.H.
meanAlphaCoNum
scalar meanAlphaCoNum = 0.0
Definition at line 35 of file alphaCourantNo.H.