OpenFOAM: applications/solvers/multiphase/reactingEulerFoam/reactingMultiphaseEulerFoam/pU/UEqns.H File Reference
UEqns.H File Reference
Functions
Info<< "Constructing momentum equations"<< endl;PtrList< fvVectorMatrix > UEqns (phases.size())
phaseSystem::momentumTransferTable & momentumTransfer (momentumTransferPtr())
forAll (phases, phasei)
Function Documentation
UEqns()
Info<< "Constructing momentum equations" << endl;PtrList<fvVectorMatrix> UEqns (phases. size())
momentumTransfer()
phaseSystem::momentumTransferTable& momentumTransfer (momentumTransferPtr())
Referenced by forAll().
forAll()
forAll (phases , phasei)
Definition at line 12 of file UEqns.H.
References Foam::constant::atomic::alpha, fvOptions, momentumTransfer(), phasei, phases, rho, U, and UEqns().