OpenFOAM: applications/solvers/multiphase/reactingEulerFoam/reactingMultiphaseEulerFoam/EEqns.H File Reference
EEqns.H File Reference
Functions
for (int Ecorr=0;Ecorr< nEnergyCorrectors;Ecorr++)
forAll (phases, phasei)
Function Documentation
for()
for ()
Definition at line 1 of file EEqns.H.
References Foam::constant::atomic::alpha, EEqn(), fluid, forAll(), fvOptions, g, phasei, phases, rho, and U.
forAll()
forAll (phases , phasei)
Initial value:
{
    autoPtr<PtrList<volVectorField>> Fs = fluid.Fs()
Definition at line 41 of file EEqns.H.
References Foam::endl(), Foam::Info, Foam::max(), Foam::min(), phasei, and phases.
Referenced by for().