OpenFOAM: applications/solvers/multiphase/reactingEulerFoam/reactingTwoPhaseEulerFoam/EEqns.H File Reference
EEqns.H File Reference
Functions
for (int Ecorr=0;Ecorr< nEnergyCorrectors;Ecorr++)
Function Documentation
for()
for ()
Definition at line 1 of file EEqns.H.
References alpha1, alpha2, E1Eqn, Foam::endl(), fluid, fvOptions, g, Foam::Info, Foam::max(), Foam::min(), phase1, phase2, rho1, rho2, U1, and U2.