OpenFOAM: applications/utilities/postProcessing/dataConversion/foamToEnsightParts/getTimeIndex.H File Reference
getTimeIndex.H File Reference
Functions
if (optIndex)
else if (runTime.timeName() !=runTime.constant() &&runTime.timeName() !="0")
timeIndices insert (timeIndex, timeDirs[timeI].value())
Variables
label timeIndex = 0
Function Documentation
if() [1/2]
if (optIndex)
Definition at line 6 of file getTimeIndex.H.
References timeIndex.
if() [2/2]
else if (runTime.timeName() ! = runTime.constant() && runTime.timeName() != "0")
Definition at line 11 of file getTimeIndex.H.
References Foam::endl(), Foam::Info, Foam::nl, timeDirs, and timeIndex.
insert()
timeIndices insert (timeIndex , timeDirs. value()[timeI])
Referenced by dynamicIndexedOctree< Foam::dynamicTreeDataPoint >::dynamicIndexedOctree(), graph::graph(), HashPtrTable< ThermoType >::HashPtrTable(), HashSet< label, Hash< label > >::HashSet(), HashTable< Foam::phase *>::HashTable(), HashSet< label, Hash< label > >::insert(), DictionaryBase< DLPtrList< T >, T >::insert(), cellShapeControlMesh::insert(), LList< Foam::chemPointISAT< CompType, ThermoType > *>::insert(), cellShapeControlMesh::insertFar(), CV2D::movePoint(), NamedEnum< directionType, 3 >::NamedEnum(), StaticHashTable< T, Key, Hash >::operator()(), HashTable< Foam::phase *>::operator()(), HashPtrTable< ThermoType >::operator=(), HashTable< Foam::phase *>::operator=(), HashSet< label, Hash< label > >::operator^=(), HashSet< label, Hash< label > >::operator|=(), and graph::wordify().
Variable Documentation
timeIndex
label timeIndex = 0
Definition at line 4 of file getTimeIndex.H.
Referenced by externalCoupledMixedFvPatchField< scalar >::evaluate(), if(), fvMesh::movePoints(), polyMesh::movePoints(), Time::operator++(), scalarRanges::selected(), layerAdditionRemoval::setRefinement(), sixDoFRigidBodyMotionSolver::solve(), rigidBodyMeshMotionSolver::solve(), rigidBodyMeshMotion::solve(), GeometricField< vector, pointPatchField, pointMesh >::storeOldTimes(), Time::subCycle(), ensightMesh::uniquePointMap(), linearValveLayersFvMesh::update(), linearValveFvMesh::update(), dynamicRefineFvMesh::update(), fixedFluxPressureFvPatchScalarField::updateCoeffs(), turbulentInletFvPatchField< Type >::updateCoeffs(), syringePressureFvPatchScalarField::updateCoeffs(), and plenumPressureFvPatchScalarField::updateCoeffs().