OpenFOAM: applications/utilities/postProcessing/lagrangian/steadyParticleTracks/createFields.H File Reference
createFields.H File Reference
Functions
const word dictName ("particleTrackDict")
IOdictionary propsDict (dictIO)
word cloudName (propsDict.lookup("cloudName"))
List< word > userFields (propsDict.lookup("fields"))
Function Documentation
dictName()
const word dictName ("particleTrackDict")
Referenced by if(), basicThermo::lookupThermo(), moleFractions< ThermoType >::moleFractions(), basicChemistryModel::New(), basicSolidChemistryModel::New(), basicThermo::New(), and pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::pyrolysisChemistryModel().
propsDict()
IOdictionary propsDict (dictIO)
cloudName()
word cloudName (propsDict. lookup"cloudName")
userFields()
List<word> userFields (propsDict. lookup"fields")