OpenFOAM: applications/utilities/preProcessing/applyBoundaryLayer/createFields.H File Reference
createFields.H File Reference
Functions
Info<< "Reading field U< endl;volVectorField U(IOobject("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::NO_WRITE), mesh);Info<< "Calculating wall distance field"<< endl;const volScalarField &y(wallDist::New(mesh).y());dimensionedScalar ybl("ybl", dimLength, 0);if(args.optionFound("ybl")){ ybl.value()=args.optionRead< scalar > ("ybl")
else if (args.optionFound("Cbl"))
Detailed Description
Original source file createFields.H
Definition in file createFields.H.
Function Documentation
Info<< "Reading field U\< endl;volVectorField U(IOobject("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::NO_WRITE), mesh);Info<< "Calculating wall distance field"<< endl;const volScalarField &y(wallDist::New(mesh).y());dimensionedScalar ybl("ybl", dimLength, 0);if(args.optionFound("ybl")){ ybl.value()=args.optionRead< scalar >()
Info<< "Reading field U\<< endl;volVectorField U(IOobject("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::NO_WRITE), mesh);Info<< "Calculating wall distance field"<< endl;const volScalarField &y(wallDist::New(mesh).y());dimensionedScalar ybl("ybl", dimLength, 0);if(args.optionFound("ybl")){ ybl.value()=args.optionRead< scalar > ("ybl")
if()
else if (args. optionFound"Cbl")
Definition at line 51 of file createFields.H.
References args, Foam::dimless, Foam::endl(), Foam::gAverage(), Foam::Info, mesh, Foam::nl, argList::optionRead(), and y.