OpenFOAM: applications/utilities/postProcessing/lagrangian/particleTracks/createFields.H File Reference
createFields.H File Reference
Functions
IOdictionary propsDict (IOobject("particleTrackProperties", runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED))
const word cloudName (propsDict.lookup("cloudName"))
label sampleFrequency (readLabel(propsDict.lookup("sampleFrequency")))
label maxPositions (readLabel(propsDict.lookup("maxPositions")))
word setFormat (propsDict.lookupOrDefault< word >("setFormat", "vtk"))
Function Documentation
propsDict()
IOdictionary propsDict (IOobject("particleTrackProperties", runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED))
Referenced by meanVelocityForce::meanVelocityForce(), fieldAverage::readAveragingProperties(), fieldAverage::writeAveragingProperties(), and meanVelocityForce::writeProps().
cloudName()
const word cloudName (propsDict. lookup"cloudName")
Referenced by Relaxation< CloudType >::cacheFields(), Implicit< CloudType >::cacheFields(), Explicit< CloudType >::cacheFields(), if(), Foam::MapLagrangianFields(), Foam::reconstructLagrangianFieldFields(), Foam::reconstructLagrangianFields(), and cloudInfo::write().
sampleFrequency()
label sampleFrequency (readLabel(propsDict.lookup("sampleFrequency")))
maxPositions()
label maxPositions (readLabel(propsDict.lookup("maxPositions")))
setFormat()
word setFormat (propsDict.lookupOrDefault< word > "setFormat", "vtk")