OpenFOAM: applications/solvers/combustion/chemFoam/createFields.H File Reference
createFields.H File Reference
Functions
if (mesh.nCells() !=1)
Info<< "Reading initial conditions.\"<< endl;IOdictionary initialConditions(IOobject("initialConditions", runTime.constant(), runTime, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE));scalar p0=readScalar(initialConditions.lookup("p"));scalar T0=readScalar(initialConditions.lookup("T"));# 24 "/home/dm2/henry/OpenFOAM/OpenFOAM-dev/applications/solvers/combustion/chemFoam/createFields.H" 2 Info<< nl<< "Reading thermophysicalProperties"<< endl;autoPtr< psiChemistryModel > pChemistry (psiChemistryModel::New(mesh))
thermo validate (args.executable(), "h")
volScalarField rho (IOobject("rho", runTime.timeName(), runTime, IOobject::NO_READ, IOobject::AUTO_WRITE), thermo.rho())
volScalarField Rspecific (IOobject("Rspecific", runTime.timeName(), runTime, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh, dimensionedScalar("zero", dimensionSet(dimEnergy/dimMass/dimTemperature), 0.0))
volVectorField U (IOobject("U", runTime.timeName(), runTime, IOobject::NO_READ, IOobject::NO_WRITE), mesh, dimensionedVector("zero", dimVelocity, Zero))
OFstream post (args.path()/"chemFoam.out")
Variables
psiChemistryModel & chemistry = pChemistry()
psiReactionThermo & thermo = chemistry.thermo()
Function Documentation
if()
if (mesh.nCells() ! = 1)
Definition at line 1 of file createFields.H.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::Info, mesh, Foam::New(), Foam::nl, pChemistry(), and readScalar.
pChemistry()
Info<< "Reading initial conditions.\n" << endl; IOdictionary initialConditions (IOobject ("initialConditions", runTime.constant(), runTime, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE)); scalar p0 = readScalar(initialConditions.lookup("p")); scalar T0 = readScalar(initialConditions.lookup("T"));# 24 "/home/dm2/henry/OpenFOAM/OpenFOAM-dev/applications/solvers/combustion/chemFoam/createFields.H" 2 Info<< nl << "Reading thermophysicalProperties" << endl; autoPtr<psiChemistryModel> pChemistry (psiChemistryModel::New(mesh))
Referenced by if().
validate()
thermo validate (args. executable(), "h")
Referenced by surfMesh::surfZones().
rho()
volScalarField rho (IOobject("rho", runTime.timeName(), runTime, IOobject::NO_READ, IOobject::AUTO_WRITE) , thermo. rho())
Rspecific()
volScalarField Rspecific (IOobject("Rspecific", runTime.timeName(), runTime, IOobject::NO_READ, IOobject::AUTO_WRITE) , mesh , dimensionedScalar("zero", dimensionSet(dimEnergy/dimMass/dimTemperature), 0.0))
U()
volVectorField U (IOobject("U", runTime.timeName(), runTime, IOobject::NO_READ, IOobject::NO_WRITE) , mesh , dimensionedVector("zero", dimVelocity, Zero))
Referenced by forAll(), and if().
post()
OFstream post (args.path()/"chemFoam.out")
Variable Documentation
chemistry
psiChemistryModel& chemistry = pChemistry()
Definition at line 29 of file createFields.H.
Referenced by chemistryTabulationMethod< CompType, ThermoType >::New(), and chemistryReductionMethod< CompType, ThermoType >::New().
thermo
psiReactionThermo& thermo = chemistry.thermo()
Definition at line 31 of file createFields.H.
Referenced by TDACChemistryModel< CompType, ThermoType >::active(), LiquidEvaporationBoil< CloudType >::calculate(), chemistryModel< CompType, ThermoType >::calculate(), chemistryModel< CompType, ThermoType >::calculateRR(), LiquidEvaporation< CloudType >::calcXc(), LiquidEvaporationBoil< CloudType >::calcXc(), for(), forAll(), forAllConstIter(), if(), laminar< Type >::R(), ReactingCloud< Foam::DSMCCloud >::ReactingCloud(), TDACChemistryModel< CompType, ThermoType >::setActive(), ReactingCloud< Foam::DSMCCloud >::setParcelThermoProperties(), singleStepCombustion< CombThermoType, ThermoType >::singleStepCombustion(), TDACChemistryModel< CompType, ThermoType >::solve(), chemistryModel< CompType, ThermoType >::solve(), chemistryModel< CompType, ThermoType >::tc(), TDACChemistryModel< CompType, ThermoType >::TDACChemistryModel(), and while().