OpenFOAM: applications/utilities/postProcessing/graphics/PV3Readers/PV3blockMeshReader/vtkPV3blockMesh/vtkOpenFOAMPoints.H File Reference
vtkOpenFOAMPoints.H File Reference
Functions
void vtkInsertNextOpenFOAMPoint (vtkPoints *points, const Foam::point &p)
void vtkInsertNextOpenFOAMPoint (vtkPoints *points, const Foam::point &p, const Foam::scalar scaleFactor)
Detailed Description
Original source file vtkOpenFOAMPoints.H
InClass vtkPV3blockMesh
Definition in file vtkOpenFOAMPoints.H.
Function Documentation
vtkInsertNextOpenFOAMPoint() [1/2]
void vtkInsertNextOpenFOAMPoint (vtkPoints * points, const Foam::point & p) inline
Definition at line 38 of file vtkOpenFOAMPoints.H.
References Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
Referenced by vtkInsertNextOpenFOAMPoint().
vtkInsertNextOpenFOAMPoint() [2/2]
void vtkInsertNextOpenFOAMPoint (vtkPoints * points, const Foam::point & p, const Foam::scalar scaleFactor) inline
Definition at line 47 of file vtkOpenFOAMPoints.H.
References Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().