OpenFOAM: applications/utilities/postProcessing/graphics/PV3Readers/PV3FoamReader/vtkPV3Foam/vtkOpenFOAMPoints.H File Reference
vtkOpenFOAMPoints.H File Reference
Functions
void vtkInsertNextOpenFOAMPoint (vtkPoints *points, const Foam::point &p)
Detailed Description
Original source file vtkOpenFOAMPoints.H
InClass vtkPV3Foam
Definition in file vtkOpenFOAMPoints.H.
Function Documentation
vtkInsertNextOpenFOAMPoint()
void vtkInsertNextOpenFOAMPoint (vtkPoints * points, const Foam::point & p) inline
Definition at line 38 of file vtkOpenFOAMPoints.H.
References forAll, Foam::New(), List< T >::size(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().