OpenFOAM: applications/solvers/compressible/rhoCentralFoam/createFields.H File Reference
createFields.H File Reference
Functions
Info<< "Reading thermophysical properties\"<< endl;autoPtr< psiThermo > pThermo (psiThermo::New(mesh))
Variables
psiThermo & thermo = pThermo()
volScalarField & e = thermo.he()
Elementary charge.
Info<< "Reading field U\"<< endl;volVectorField U(IOobject("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);volScalarField rho(IOobject("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), thermo.rho());volVectorField rhoU(IOobject("rhoU", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), rho *U);volScalarField rhoE(IOobject("rhoE", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), rho *(e+0.5 *magSqr(U)));surfaceScalarField pos(IOobject("pos", runTime.timeName(), mesh), mesh, dimensionedScalar("pos", dimless, 1.0));surfaceScalarField neg(IOobject("neg", runTime.timeName(), mesh), mesh, dimensionedScalar("neg", dimless, -1.0));surfaceScalarField phi("phi", fvc::flux(rhoU));Info<< "Creating turbulence model\"<< endl;autoPtr< compressible::turbulenceModel > turbulence (compressible::turbulenceModel::New(rho, U, phi, thermo))
Function Documentation
pThermo()
Info<< "Reading thermophysical properties\n" << endl;autoPtr<psiThermo> pThermo (psiThermo::New(mesh))
Variable Documentation
thermo
psiThermo& thermo = pThermo()
Definition at line 9 of file createFields.H.
e
volScalarField& e = thermo.he()
Elementary charge.
Definition at line 11 of file createFields.H.
turbulence
Info<< "Reading field U\n" << endl;volVectorField U(IOobject ("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);volScalarField rho(IOobject ("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), thermo.rho());volVectorField rhoU(IOobject ("rhoU", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), rho*U);volScalarField rhoE(IOobject ("rhoE", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), rho*(e + 0.5*magSqr(U)));surfaceScalarField pos(IOobject ("pos", runTime.timeName(), mesh), mesh, dimensionedScalar("pos", dimless, 1.0));surfaceScalarField neg(IOobject ("neg", runTime.timeName(), mesh), mesh, dimensionedScalar("neg", dimless, -1.0));surfaceScalarField phi("phi", fvc::flux(rhoU));Info<< "Creating turbulence model\n" << endl;autoPtr<compressible::turbulenceModel> turbulence(compressible::turbulenceModel::New(rho, U, phi, thermo))
Definition at line 94 of file createFields.H.
Referenced by PaSR< Type >::correct(), diffusion< CombThermoType, ThermoType >::correct(), relaxation::correct(), forAll(), forAllIter(), if(), and LESdelta::New().