OpenFOAM: applications/solvers/lagrangian/reactingParcelFilmFoam/createFields.H File Reference
createFields.H File Reference
Functions
Info<< "Creating combustion model\"<< endl;autoPtr< combustionModels::psiCombustionModel > combustion (combustionModels::psiCombustionModel::New(mesh))
thermo validate (args.executable(), "h", "e")
SLGThermo slgThermo (mesh, thermo)
const word inertSpecie (thermo.lookup("inertSpecie"))
if (!composition.species().found(inertSpecie))
Info<< "Creating field rho\"<< endl;volScalarField rho(IOobject("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), thermo.rho());volScalarField &p=thermo.p();Info<< "\Reading field U\"<< endl;volVectorField U(IOobject("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);Info<< "Creating turbulence model\"<< endl;autoPtr< compressible::turbulenceModel > turbulence (compressible::turbulenceModel::New(rho, U, phi, thermo))
combustion setTurbulence (turbulence())
forAll (Y, i)
fields add (thermo.he())
IOdictionary additionalControlsDict (IOobject("additionalControls", runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE))
Switch solvePrimaryRegion (additionalControlsDict.lookup("solvePrimaryRegion"))
volScalarField dQ (IOobject("dQ", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh, dimensionedScalar("dQ", dimEnergy/dimTime, 0.0))
Variables
psiReactionThermo & thermo = combustion->thermo()
basicSpecieMixture & composition = thermo.composition()
PtrList< volScalarField > & Y = composition.Y()
Info<< "Creating field dpdt\"<< endl;volScalarField dpdt(IOobject("dpdt", runTime.timeName(), mesh), mesh, dimensionedScalar("dpdt", p.dimensions()/dimTime, 0));Info<< "Creating field kinetic energy K\"<< endl;volScalarField K("K", 0.5 *magSqr(U));volScalarField p_rgh(IOobject("p_rgh", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);p_rgh=p - rho *gh;mesh.setFluxRequired(p_rgh.name());multivariateSurfaceInterpolationScheme< scalar >::fieldTable fields
Function Documentation
combustion()
Info<< "Creating combustion model\n" << endl;autoPtr<combustionModels::psiCombustionModel> combustion (combustionModels::psiCombustionModel::New(mesh))
validate()
thermo validate (args. executable(), "h" , "e")
slgThermo()
SLGThermo slgThermo (mesh , thermo)
inertSpecie()
const word inertSpecie (thermo. lookup"inertSpecie")
if()
if (!composition. species).found(inertSpecie)
Definition at line 17 of file createFields.H.
References args, combustion(), Foam::dimTime, dpdt, Foam::endl(), argList::executable(), Foam::exit(), Foam::FatalIOError, FatalIOErrorIn, gh, inertSpecie(), Foam::Info, Foam::magSqr(), mesh, Foam::New(), p, p_rgh(), phi, rho, thermo, turbulence, and U().
turbulence()
Info<< "Creating field rho\n" << endl;volScalarField rho(IOobject ("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), thermo.rho());volScalarField& p = thermo.p();Info<< "\nReading field U\n" << endl;volVectorField U(IOobject ("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);Info<< "Creating turbulence model\n" << endl;autoPtr<compressible::turbulenceModel> turbulence (compressible::turbulenceModel::New(rho, U, phi, thermo))
setTurbulence()
combustion setTurbulence (turbulence())
forAll()
forAll (Y , i)
Definition at line 114 of file createFields.H.
References additionalControlsDict(), Foam::dimEnergy, Foam::dimTime, dQ(), mesh, and solvePrimaryRegion().
add()
fields add (thermo. he())
additionalControlsDict()
IOdictionary additionalControlsDict (IOobject("additionalControls", runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE))
solvePrimaryRegion()
Switch solvePrimaryRegion (additionalControlsDict. lookup"solvePrimaryRegion")
dQ()
volScalarField dQ (IOobject("dQ", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE) , mesh , dimensionedScalar("dQ", dimEnergy/dimTime, 0.0))
Variable Documentation
thermo
psiReactionThermo& thermo = combustion->thermo()
Definition at line 8 of file createFields.H.
composition
basicSpecieMixture& composition = thermo.composition()
Definition at line 13 of file createFields.H.
Y
PtrList<volScalarField>& Y = composition.Y()
Definition at line 14 of file createFields.H.
fields
Info<< "Creating field dpdt\n" << endl;volScalarField dpdt(IOobject ("dpdt", runTime.timeName(), mesh), mesh, dimensionedScalar("dpdt", p.dimensions()/dimTime, 0));Info<< "Creating field kinetic energy K\n" << endl;volScalarField K("K", 0.5*magSqr(U));volScalarField p_rgh(IOobject ("p_rgh", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);p_rgh = p - rho*gh;mesh.setFluxRequired(p_rgh.name());multivariateSurfaceInterpolationScheme<scalar>::fieldTable fields
Definition at line 112 of file createFields.H.