OpenFOAM: applications/solvers/incompressible/adjointShapeOptimizationFoam/createFields.H File Reference
createFields.H File Reference
Functions
Info<< "Reading field p\"<< endl;volScalarField p(IOobject("p", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);Info<< "Reading field U\"<< endl;volVectorField U(IOobject("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);label pRefCell=0;scalar pRefValue=0.0;setRefCell(p, simple.dict(), pRefCell, pRefValue);mesh.setFluxRequired(p.name());Info<< "Reading field pa\"<< endl;volScalarField pa(IOobject("pa", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);Info<< "Reading field Ua\"<< endl;volVectorField Ua(IOobject("Ua", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);# 66 "/home/dm2/henry/OpenFOAM/OpenFOAM-dev/applications/solvers/incompressible/adjointShapeOptimizationFoam/createFields.H" 2label paRefCell=0;scalar paRefValue=0.0;setRefCell(pa, simple.dict(), paRefCell, paRefValue);mesh.setFluxRequired(pa.name());singlePhaseTransportModel laminarTransport(U, phi);autoPtr< incompressible::turbulenceModel > turbulence (incompressible::turbulenceModel::New(U, phi, laminarTransport))
dimensionedScalar zeroSensitivity ("0", dimVelocity *dimVelocity, 0.0)
dimensionedScalar zeroAlpha ("0", dimless/dimTime, 0.0)
dimensionedScalar lambda (laminarTransport.lookup("lambda"))
dimensionedScalar alphaMax (laminarTransport.lookup("alphaMax"))
volScalarField alpha (IOobject("alpha", runTime.timeName(), mesh, IOobject::READ_IF_PRESENT, IOobject::AUTO_WRITE), lambda *max(Ua &U, zeroSensitivity))
zeroCells (alpha, inletCells)
Variables
const labelList & inletCells = mesh.boundary()["inlet"].faceCells()
Function Documentation
turbulence()
Info<< "Reading field p\n" << endl;volScalarField p(IOobject ("p", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);Info<< "Reading field U\n" << endl;volVectorField U(IOobject ("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);label pRefCell = 0;scalar pRefValue = 0.0;setRefCell(p, simple.dict(), pRefCell, pRefValue);mesh.setFluxRequired(p.name());Info<< "Reading field pa\n" << endl;volScalarField pa(IOobject ("pa", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);Info<< "Reading field Ua\n" << endl;volVectorField Ua(IOobject ("Ua", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);# 66 "/home/dm2/henry/OpenFOAM/OpenFOAM-dev/applications/solvers/incompressible/adjointShapeOptimizationFoam/createFields.H" 2label paRefCell = 0;scalar paRefValue = 0.0;setRefCell(pa, simple.dict(), paRefCell, paRefValue);mesh.setFluxRequired(pa.name());singlePhaseTransportModel laminarTransport(U, phi);autoPtr<incompressible::turbulenceModel> turbulence (incompressible::turbulenceModel::New(U, phi, laminarTransport))
zeroSensitivity()
dimensionedScalar zeroSensitivity ("0" , dimVelocity * dimVelocity, 0. 0)
zeroAlpha()
dimensionedScalar zeroAlpha ("0" , dimless/ dimTime, 0. 0)
lambda()
dimensionedScalar lambda (laminarTransport. lookup"lambda")
Referenced by tetrahedron< Point, PointRef >::circumCentre(), tetrahedron< Point, PointRef >::circumRadius(), cubic< Type >::correction(), particle< Type >::findTris(), for(), particle< Type >::hitWallFaces(), if(), Foam::MULES::implicitSolve(), surfaceInterpolationScheme< GType >::interpolate(), Foam::MULES::limit(), Foam::MULES::limitCorr(), Foam::MULES::limiter(), Foam::MULES::limiterCorr(), Foam::MULES::limitSum(), BSpline::position(), CatmullRomSpline::position(), polyLine::position(), and kOmegaSSTLM< BasicTurbulenceModel >::ReThetat0().
alphaMax()
dimensionedScalar alphaMax (laminarTransport. lookup"alphaMax")
Referenced by MPPICCloud< Foam::DSMCCloud >::info().
alpha()
volScalarField alpha (IOobject("alpha", runTime.timeName(), mesh, IOobject::READ_IF_PRESENT, IOobject::AUTO_WRITE) , lambda * maxUa &U, zeroSensitivity)
zeroCells()
zeroCells (alpha , inletCells)
Variable Documentation
inletCells
const labelList& inletCells = mesh.boundary()["inlet"].faceCells()
Definition at line 95 of file createFields.H.