OpenFOAM: applications/solvers/heatTransfer/buoyantBoussinesqSimpleFoam/readTransportProperties.H File Reference
readTransportProperties.H File Reference
Functions
singlePhaseTransportModel laminarTransport (U, phi)
dimensionedScalar beta ("beta", dimless/dimTemperature, laminarTransport)
dimensionedScalar TRef ("TRef", dimTemperature, laminarTransport)
dimensionedScalar Pr ("Pr", dimless, laminarTransport)
dimensionedScalar Prt ("Prt", dimless, laminarTransport)
Function Documentation
laminarTransport()
singlePhaseTransportModel laminarTransport (U , phi)
beta()
dimensionedScalar beta ("beta" , dimless/ dimTemperature, laminarTransport)
Referenced by IntegrationScheme< Type >::integrationResult::average(), ReactingMultiphaseParcel< ParcelType >::calcDevolatilisation(), fieldAverage::calculateMeanFieldType(), fieldAverage::calculatePrime2MeanFieldType(), Analytical< Type >::clone(), Euler< Type >::clone(), TrajectoryCollision< CloudType >::collideParcels(), rotorDiskSource::constructGeometry(), kOmegaSST< LESeddyViscosity< BasicTurbulenceModel >, BasicTurbulenceModel >::correct(), mixtureKEpsilon< BasicTurbulenceModel >::Ct2(), Analytical< Type >::integrate(), triangleFuncs::intersectAxesBundle(), ConeNozzleInjection< CloudType >::setPositionAndCell(), ConeInjection< CloudType >::setProperties(), PBiCICG< Type, DType, LUType >::solve(), PBiCCCG< Type, DType, LUType >::solve(), PCICG< Type, DType, LUType >::solve(), PBiCG::solve(), PCG::solve(), PBiCGStab::solve(), FacePostProcessing< CloudType >::write(), and ParticleCollector< CloudType >::write().
TRef()
dimensionedScalar TRef ("TRef" , dimTemperature , laminarTransport)
Referenced by StaticHashTable< T, Key, Hash >::Iterator< T &, StaticHashTable< T, Key, Hash > &>::Iterator(), StaticHashTable< T, Key, Hash >::Iterator< T &, StaticHashTable< T, Key, Hash > &>::operator!=(), StaticHashTable< T, Key, Hash >::Iterator< T &, StaticHashTable< T, Key, Hash > &>::operator()(), StaticHashTable< T, Key, Hash >::Iterator< T &, StaticHashTable< T, Key, Hash > &>::operator++(), StaticHashTable< T, Key, Hash >::Iterator< T &, StaticHashTable< T, Key, Hash > &>::operator=(), and StaticHashTable< T, Key, Hash >::Iterator< T &, StaticHashTable< T, Key, Hash > &>::operator==().
Pr()
dimensionedScalar Pr ("Pr" , dimless , laminarTransport)
Referenced by ThermoParcel< ParcelType >::calc(), NoPhaseChange< CloudType >::clone(), RanzMarshall< CloudType >::clone(), LiquidEvaporation< CloudType >::clone(), LiquidEvaporationBoil< CloudType >::clone(), PengRobinsonGas< Specie >::h(), TroeFallOffFunction::operator()(), SRIFallOffFunction::operator()(), FallOffReactionRate< ReactionRate, FallOffFunction >::operator()(), ChemicallyActivatedReactionRate< ReactionRate, ChemicallyActivationFunction >::operator()(), SprayParcel< ParcelType >::iNew::operator()(), ThermoParcel< ParcelType >::iNew::operator()(), PengRobinsonGas< Specie >::s(), LindemannFallOffFunction::type(), TroeFallOffFunction::type(), SRIFallOffFunction::type(), convectiveHeatTransferFvPatchScalarField::updateCoeffs(), alphatFilmWallFunctionFvPatchScalarField::updateCoeffs(), and alphatJayatillekeWallFunctionFvPatchScalarField::updateCoeffs().
Prt()
dimensionedScalar Prt ("Prt" , dimless , laminarTransport)