OpenFOAM: applications/solvers/multiphase/driftFluxFoam/createFields.H File Reference
createFields.H File Reference
Functions
Info<< "Reading field p_rgh\"<< endl;volScalarField p_rgh(IOobject("p_rgh", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);Info<< "Reading field U\"<< endl;volVectorField U(IOobject("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);Info<< "Reading incompressibleTwoPhaseInteractingMixture\"<< endl;incompressibleTwoPhaseInteractingMixture mixture(U, phi);volScalarField &alpha1(mixture.alpha1());volScalarField rho(IOobject("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), mixture.rho());surfaceScalarField rhoPhi(IOobject("rhoPhi", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), fvc::interpolate(rho) *phi);autoPtr< relativeVelocityModel > UdmModelPtr (relativeVelocityModel::New(mixture, mixture))
autoPtr< CompressibleTurbulenceModel< incompressibleTwoPhaseInteractingMixture >> turbulence (CompressibleTurbulenceModel< incompressibleTwoPhaseInteractingMixture > ::New(rho, U, rhoPhi, mixture))
volScalarField p (IOobject("p", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), p_rgh+rho *gh)
setRefCell (p, p_rgh, pimple.dict(), pRefCell, pRefValue)
if (p_rgh.needReference())
mesh setFluxRequired (p_rgh.name())
mesh setFluxRequired (alpha1.name())
Variables
label pRefCell = 0
scalar pRefValue = 0.0
tmp< surfaceScalarField > talphaPhiCorr0
Function Documentation
UdmModelPtr()
Info<< "Reading field p_rgh\n" << endl;volScalarField p_rgh(IOobject ("p_rgh", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);Info<< "Reading field U\n" << endl;volVectorField U(IOobject ("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);Info<< "Reading incompressibleTwoPhaseInteractingMixture\n" << endl;incompressibleTwoPhaseInteractingMixture mixture(U, phi);volScalarField& alpha1(mixture.alpha1());volScalarField rho(IOobject ("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), mixture.rho());surfaceScalarField rhoPhi(IOobject ("rhoPhi", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), fvc::interpolate(rho)*phi);autoPtr<relativeVelocityModel> UdmModelPtr (relativeVelocityModel::New(mixture, mixture))
turbulence()
autoPtr< CompressibleTurbulenceModel<incompressibleTwoPhaseInteractingMixture>> turbulence (CompressibleTurbulenceModel< incompressibleTwoPhaseInteractingMixture > ::Newrho, U, rhoPhi, mixture)
p()
volScalarField p (IOobject("p", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE) , p_rgh+rho * gh)
setRefCell()
setRefCell (p , p_rgh , pimple. dict(), pRefCell , pRefValue)
if()
if (p_rgh. needReference())
Definition at line 117 of file createFields.H.
References alpha1(), Foam::getRefCellValue(), gh, mesh, p, p_rgh(), and rho.
setFluxRequired() [1/2]
mesh setFluxRequired (p_rgh. name())
setFluxRequired() [2/2]
mesh setFluxRequired (alpha1. name())
Variable Documentation
pRefCell
label pRefCell = 0
Definition at line 106 of file createFields.H.
pRefValue
scalar pRefValue = 0.0
Definition at line 107 of file createFields.H.
talphaPhiCorr0
tmp<surfaceScalarField> talphaPhiCorr0
Definition at line 132 of file createFields.H.
Referenced by if().