OpenFOAM: applications/solvers/lagrangian/reactingParcelFoam/simpleReactingParcelFoam/createFields.H File Reference
createFields.H File Reference
Functions
Info<< "Creating combustion model\"<< endl;autoPtr< combustionModels::rhoCombustionModel > combustion (combustionModels::rhoCombustionModel::New(mesh))
thermo validate (args.executable(), "h", "e")
SLGThermo slgThermo (mesh, thermo)
const word inertSpecie (thermo.lookup("inertSpecie"))
if (!composition.species().found(inertSpecie))
volScalarField rho (IOobject("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), thermo.rho())
Info<< "\Reading field U\"<< endl;volVectorField U(IOobject("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);mesh.setFluxRequired(p.name());dimensionedScalar rhoMax(dimensionedScalar::lookupOrDefault("rhoMax", simple.dict(), dimDensity, GREAT));dimensionedScalar rhoMin(dimensionedScalar::lookupOrDefault("rhoMin", simple.dict(), dimDensity, 0));Info<< "Creating turbulence model\"<< endl;autoPtr< compressible::turbulenceModel > turbulence (compressible::turbulenceModel::New(rho, U, phi, thermo))
combustion setTurbulence (turbulence())
forAll (Y, i)
fields add (thermo.he())
volScalarField dQ (IOobject("dQ", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh, dimensionedScalar("dQ", dimEnergy/dimTime, 0.0))
Variables
rhoReactionThermo & thermo = combustion->thermo()
basicSpecieMixture & composition = thermo.composition()
PtrList< volScalarField > & Y = composition.Y()
volScalarField & p = thermo.p()
Info<< "Creating multi-variate interpolation scheme\"<< endl;multivariateSurfaceInterpolationScheme< scalar >::fieldTable fields
Function Documentation
combustion()
Info<< "Creating combustion model\n" << endl;autoPtr<combustionModels::rhoCombustionModel> combustion (combustionModels::rhoCombustionModel::New(mesh))
validate()
thermo validate (args. executable(), "h" , "e")
slgThermo()
SLGThermo slgThermo (mesh , thermo)
inertSpecie()
const word inertSpecie (thermo. lookup"inertSpecie")
if()
if (!composition. species).found(inertSpecie)
Definition at line 19 of file createFields.H.
References args, argList::executable(), Foam::exit(), Foam::FatalIOError, FatalIOErrorIn, inertSpecie(), and thermo.
rho()
volScalarField rho (IOobject("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE) , thermo. rho())
turbulence()
Info<< "\nReading field U\n" << endl;volVectorField U(IOobject ("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);mesh.setFluxRequired(p.name());dimensionedScalar rhoMax(dimensionedScalar::lookupOrDefault ("rhoMax", simple.dict(), dimDensity, GREAT));dimensionedScalar rhoMin(dimensionedScalar::lookupOrDefault ("rhoMin", simple.dict(), dimDensity, 0));Info<< "Creating turbulence model\n" << endl;autoPtr<compressible::turbulenceModel> turbulence (compressible::turbulenceModel::New(rho, U, phi, thermo))
setTurbulence()
combustion setTurbulence (turbulence())
forAll()
forAll (Y , i)
Definition at line 100 of file createFields.H.
References Foam::dimEnergy, Foam::dimTime, dQ(), and mesh.
add()
fields add (thermo. he())
dQ()
volScalarField dQ (IOobject("dQ", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE) , mesh , dimensionedScalar("dQ", dimEnergy/dimTime, 0.0))
Variable Documentation
thermo
rhoReactionThermo& thermo = combustion->thermo()
Definition at line 10 of file createFields.H.
composition
basicSpecieMixture& composition = thermo.composition()
Definition at line 15 of file createFields.H.
Y
PtrList<volScalarField>& Y = composition.Y()
Definition at line 16 of file createFields.H.
p
volScalarField& p = thermo.p()
Definition at line 27 of file createFields.H.
fields
Info<< "Creating multi-variate interpolation scheme\n" << endl;multivariateSurfaceInterpolationScheme<scalar>::fieldTable fields
Definition at line 98 of file createFields.H.