OpenFOAM: applications/solvers/multiphase/interPhaseChangeFoam/createFields.H File Reference
createFields.H File Reference
Functions
volScalarField & alpha1 (mixture->alpha1())
volScalarField & alpha2 (mixture->alpha2())
volScalarField rho (IOobject("rho", runTime.timeName(), mesh, IOobject::READ_IF_PRESENT), alpha1 *rho1+alpha2 *rho2)
rho oldTime ()
interfaceProperties interface (alpha1, U, mixture())
autoPtr< incompressible::turbulenceModel > turbulence (incompressible::turbulenceModel::New(U, phi, mixture()))
volScalarField p (IOobject("p", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), p_rgh+rho *gh)
setRefCell (p, p_rgh, pimple.dict(), pRefCell, pRefValue)
if (p_rgh.needReference())
mesh setFluxRequired (p_rgh.name())
mesh setFluxRequired (alpha1.name())
Variables
Info<< "Reading field p_rgh\"<< endl;volScalarField p_rgh(IOobject("p_rgh", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);Info<< "Reading field U\"<< endl;volVectorField U(IOobject("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);Info<< "Creating phaseChangeTwoPhaseMixture\"<< endl;autoPtr< phaseChangeTwoPhaseMixture > mixture
const dimensionedScalar & rho1 = mixture->rho1()
const dimensionedScalar & rho2 = mixture->rho2()
label pRefCell = 0
scalar pRefValue = 0.0
Function Documentation
alpha1()
volScalarField& alpha1 (mixture-> alpha1())
Referenced by if().
alpha2()
volScalarField& alpha2 (mixture-> alpha2())
Referenced by if().
rho()
volScalarField rho (IOobject("rho", runTime.timeName(), mesh, IOobject::READ_IF_PRESENT) , alpha1 *rho1+alpha2 * rho2)
oldTime()
rho oldTime ()
Referenced by backwardDdtScheme< Type >::meshPhi(), fileMonitorWatcher::removeWatch(), plenumPressureFvPatchScalarField::updateCoeffs(), and while().
interface()
interfaceProperties interface (alpha1 , U , mixture())
Referenced by lduPrimitiveMesh::gather(), if(), and LUscalarMatrix::LUscalarMatrix().
turbulence()
autoPtr<incompressible::turbulenceModel> turbulence (incompressible::turbulenceModel::New(U, phi, mixture()))
p()
volScalarField p (IOobject("p", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE) , p_rgh+rho * gh)
setRefCell()
setRefCell (p , p_rgh , pimple. dict(), pRefCell , pRefValue)
if()
if (p_rgh. needReference())
Definition at line 97 of file createFields.H.
References alpha1(), Foam::getRefCellValue(), gh, mesh, p, p_rgh(), and rho.
setFluxRequired() [1/2]
mesh setFluxRequired (p_rgh. name())
setFluxRequired() [2/2]
mesh setFluxRequired (alpha1. name())
Variable Documentation
mixture
Info<< "Reading field p_rgh\n" << endl;volScalarField p_rgh(IOobject ("p_rgh", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);Info<< "Reading field U\n" << endl;volVectorField U(IOobject ("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);Info<< "Creating phaseChangeTwoPhaseMixture\n" << endl;autoPtr<phaseChangeTwoPhaseMixture> mixture
Initial value:
=
    phaseChangeTwoPhaseMixture::New(U, phi)
Definition at line 33 of file createFields.H.
Referenced by for(), if(), EulerImplicit< ChemistryModel >::solve(), and while().
rho1
const dimensionedScalar& rho1 = mixture->rho1()
Definition at line 39 of file createFields.H.
rho2
const dimensionedScalar& rho2 = mixture->rho2()
Definition at line 40 of file createFields.H.
pRefCell
label pRefCell = 0
Definition at line 86 of file createFields.H.
pRefValue
scalar pRefValue = 0.0
Definition at line 87 of file createFields.H.