OpenFOAM: src/finiteVolume/cfdTools/general/include/alphaControls.H File Reference
alphaControls.H File Reference
Functions
label nAlphaCorr (readLabel(alphaControls.lookup("nAlphaCorr")))
label nAlphaSubCycles (readLabel(alphaControls.lookup("nAlphaSubCycles")))
bool MULESCorr (alphaControls.lookupOrDefault< Switch >("MULESCorr", false))
bool alphaApplyPrevCorr (alphaControls.lookupOrDefault< Switch >("alphaApplyPrevCorr", false))
scalar icAlpha (alphaControls.lookupOrDefault< scalar >("icAlpha", 0))
Variables
const dictionary & alphaControls = mesh.solverDict(alpha1.name())
Function Documentation
nAlphaCorr()
label nAlphaCorr (readLabel(alphaControls.lookup("nAlphaCorr")))
nAlphaSubCycles()
label nAlphaSubCycles (readLabel(alphaControls.lookup("nAlphaSubCycles")))
Referenced by if(), and localEulerDdt::localEulerDdt().
MULESCorr()
bool MULESCorr (alphaControls.lookupOrDefault< Switch > "MULESCorr", false)
Referenced by for().
alphaApplyPrevCorr()
bool alphaApplyPrevCorr (alphaControls.lookupOrDefault< Switch > "alphaApplyPrevCorr", false)
Referenced by if().
icAlpha()
scalar icAlpha (alphaControls.lookupOrDefault< scalar > "icAlpha", 0)
Referenced by if().
Variable Documentation
alphaControls
const dictionary& alphaControls = mesh.solverDict(alpha1.name())
Definition at line 1 of file alphaControls.H.