OpenFOAM: applications/solvers/multiphase/reactingEulerFoam/reactingMultiphaseEulerFoam/CourantNo.H File Reference
CourantNo.H File Reference
Calculates and outputs the mean and maximum Courant Numbers.
Functions
if (mesh.nInternalFaces())
Variables
scalar CoNum = 0.0
scalar meanCoNum = 0.0
Detailed Description
Calculates and outputs the mean and maximum Courant Numbers.
Original source file CourantNo.H
Definition in file CourantNo.H.
Function Documentation
if()
if (mesh. nInternalFaces())
Definition at line 32 of file CourantNo.H.
References CoNum, Foam::endl(), forAll, Foam::gMax(), Foam::gSum(), Foam::Info, Foam::mag(), Foam::max(), meanCoNum, mesh, phasei, phases, phi, scalarField(), and Foam::fvc::surfaceSum().
Variable Documentation
CoNum
scalar CoNum = 0.0
Definition at line 29 of file CourantNo.H.
meanCoNum
scalar meanCoNum = 0.0
Definition at line 30 of file CourantNo.H.