OpenFOAM: applications/utilities/postProcessing/miscellaneous/postChannel/readFields.H File Reference
readFields.H File Reference
Functions
IOobject UMeanHeader ("UMean", runTime.timeName(), mesh, IOobject::MUST_READ)
if (!UMeanHeader.headerOk())
volVectorField UMean (UMeanHeader, mesh)
volSymmTensorField UPrime2Mean (IOobject("UPrime2Mean", runTime.timeName(), mesh, IOobject::MUST_READ), mesh)
volScalarField Rxx (UPrime2Mean.component(symmTensor::XX))
volScalarField Ryy (UPrime2Mean.component(symmTensor::YY))
volScalarField Rzz (UPrime2Mean.component(symmTensor::ZZ))
volScalarField Rxy (UPrime2Mean.component(symmTensor::XY))
volScalarField pPrime2Mean (IOobject("pPrime2Mean", runTime.timeName(), mesh, IOobject::MUST_READ), mesh)
Function Documentation
UMeanHeader()
IOobject UMeanHeader ("UMean" , runTime. timeName(), mesh , IOobject::MUST_READ)
Referenced by if().
if()
if (!UMeanHeader. headerOk())
Definition at line 9 of file readFields.H.
References Foam::endl(), Foam::Info, mesh, pPrime2Mean(), Rxx(), Rxy(), Ryy(), Rzz(), UMean(), UMeanHeader(), and UPrime2Mean().
UMean()
volVectorField UMean (UMeanHeader , mesh)
Referenced by if(), and dsmcFields::write().
UPrime2Mean()
volSymmTensorField UPrime2Mean (IOobject("UPrime2Mean", runTime.timeName(), mesh, IOobject::MUST_READ) , mesh)
Referenced by if().
Rxx()
volScalarField Rxx (UPrime2Mean. componentsymmTensor::XX)
Referenced by if().
Ryy()
volScalarField Ryy (UPrime2Mean. componentsymmTensor::YY)
Referenced by if().
Rzz()
volScalarField Rzz (UPrime2Mean. componentsymmTensor::ZZ)
Referenced by if().
Rxy()
volScalarField Rxy (UPrime2Mean. componentsymmTensor::XY)
Referenced by if().
pPrime2Mean()
volScalarField pPrime2Mean (IOobject("pPrime2Mean", runTime.timeName(), mesh, IOobject::MUST_READ) , mesh)
Referenced by if().