OpenFOAM: src/OpenFOAM/db/IOstreams/Pstreams/UPstream.C File Reference
UPstream.C File Reference
Classes
class addcommsTypeToOpt
Namespaces
Foam
Namespace for OpenFOAM.
Functions
defineTypeNameAndDebug (UPstream, 0)
registerOptSwitch ("floatTransfer", bool, Foam::UPstream::floatTransfer)
registerOptSwitch ("nProcsSimpleSum", int, Foam::UPstream::nProcsSimpleSum)
registerOptSwitch ("nPollProcInterfaces", int, Foam::UPstream::nPollProcInterfaces)
Variables
Foam::UPstream::communicator serialComm (-1, Foam::labelList(1, Foam::label(0)), false)
addcommsTypeToOpt addcommsTypeToOpt_ ("commsType")
Detailed Description
Original source file UPstream.C
Definition in file UPstream.C.
Function Documentation
registerOptSwitch() [1/3]
registerOptSwitch ("floatTransfer" , bool , Foam::UPstream::floatTransfer)
Referenced by UPstream::procNo(), and addcommsTypeToOpt::writeData().
registerOptSwitch() [2/3]
registerOptSwitch ("nProcsSimpleSum" , int , Foam::UPstream::nProcsSimpleSum)
registerOptSwitch() [3/3]
registerOptSwitch ("nPollProcInterfaces" , int , Foam::UPstream::nPollProcInterfaces)
Variable Documentation
serialComm
Foam::UPstream::communicator serialComm(-1, Foam::labelList(1, Foam::label(0)), false)
Referenced by UPstream::procNo().